### ISSUE TITLE
[Not an issue] Congratulations on being featured at Changelog Weekly

### ISSUE THREAD

**Issue by markogresak** [sindresorhus/caprine#10]
The [new issue of Changelog](http://email.changelog.com/t/ViewEmail/t/7F181BD5C75B60B7/D204DE08D70E0D4CC67FD2F38AC4859C) just arrived and this repo was one of the projects listed. And I must say Caprine works incredibly well, much better than any other messenger apps I've tried so far.

**Comment by sindresorhus** [comment]
Thanks for letting me know :D Happy to hear it works well for you. Let me know if there are any improvements that could be made ;)
