### ISSUE TITLE
Dark mode makes "type a message" hard to read

### ISSUE THREAD

**Issue by jvacek** [sindresorhus/caprine#1001]
![image](https://user-images.githubusercontent.com/1302278/61321330-95a16600-a80b-11e9-8771-b04ef0af7f57.png)
I'm on PopOS!

**Comment by nepoveda** [comment]
Same Linux Mint 19 Cinnamon but it's white on white 
![caprine](https://user-images.githubusercontent.com/17991830/61323085-6f7dc500-a80f-11e9-8667-286b3c5e8d2f.png)

**Comment by exiva** [comment]
macOS 10.14.5 is like @jvacek's screenshot on 2.34.0
<img width="490" alt="Screen Shot 2019-07-16 at 6 47 27 PM" src="https://user-images.githubusercontent.com/56931/61335076-2f601780-a7fa-11e9-86d4-ca9eb53f0a3c.png">

**Comment by MaYa-12** [comment]
Caprine 2.11.0 on Windows 10 v.1809

![image](https://user-images.githubusercontent.com/53095064/61554816-beb53700-aa55-11e9-9579-13397c4cdcb6.png)
![image](https://user-images.githubusercontent.com/53095064/61554841-d12f7080-aa55-11e9-9f9e-c929fc96b8b5.png)

**Comment by neelrr1** [comment]
Seems to be fixed on Windows in the latest version

![image](https://user-images.githubusercontent.com/18130673/61581237-b0f0c780-aad0-11e9-8cc4-a789dbb66b5d.png)

**Comment by mikigal** [comment]
It depend which version of Facebook UI you have. 
Update Caprine to newest version, it should fix problems with newest version of Facebook UI

**Comment by nepoveda** [comment]
> It depend which version of Facebook UI you have.
> Update Caprine to newest version, it should fix problems with newest version of Facebook UI

thx, it helps

**Comment by keyboard-clacker** [comment]
I think this is still an issue on macOS, but if you go to the menu item `Caprine > Caprine Preferences > Advanced > Custom Styles`, you can put this CSS at the end of that file and it will make it a bit lighter grey:

```
[id^=placeholder] {
  color: var(--base-seventy) !important;
  -webkit-text-fill-color: var(--base-seventy) !important;
}
```

**Comment by DeveloperBlue** [comment]
Just got the latest v2.34.0 version off of Releases, and I'm encountering the same dark text on a dark background. Windows 10. 
![image](https://user-images.githubusercontent.com/11480933/62014816-c4a4c980-b173-11e9-906e-1368b90169be.png)

**Comment by MaYa-12** [comment]
wanted to try what keyboard-clacker suggested but there doesn't seem to be a CSS file for the Windows 10 app :(

**Comment by keyboard-clacker** [comment]
@MaYa-12 I think this css should work:
```css
._4rv3 ._1mf {
	color: /* <insert some color here> */;
	-webkit-text-fill-color: /* <insert that same color here> */;
}
```
In this selector, `_4rv3` is the message composer, and `_1mf` is specifically any entered text

**Comment by MaYa-12** [comment]
@keyboard-clacker it worked a dream, thank you so much

**Comment by keyboard-clacker** [comment]
np! If you want to find any of these selectors btw @MaYa-12 , you can inspect any elements in the web app and they have the same class names
