### ISSUE TITLE
Store Cache/ .cache, not .config on Linux

### ISSUE THREAD

**Issue by tkedwards** [sindresorhus/caprine#1005]
Thanks for making Caprine!

I've noticed on Linux (Ubuntu 18.04 with Caprine installed from the Snap package) that the cache is stored in the directory ~/.config/Cache. Cache data should be under ~/.cache/caprine on Linux:

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html 

I sync my ~/.config between machines and having cache data in there makes it much bigger than it should be - currently over 200MB

**Comment by CvX** [comment]
It's an Electron bug. You can follow the updates on this issue here: https://github.com/electron/electron/issues/8124
