### ISSUE TITLE
Snap does not run from Wayland Session

### ISSUE THREAD

**Issue by zigford** [sindresorhus/caprine#1006]
**Describe the bug**
Snap package immediately exits if run from within a wayland session. Additionally, if you have had a wayland session running, then switch to Xorg, the same problem exists as described [here](https://forum.snapcraft.io/t/electron-apps-and-wayland/12315)

**To Reproduce**
1. Install the snap
2. Ensure your logged into a Wayland session over Xorg
3. Attempt to run snap
4. Error is shown:

`Gtk-WARNING **: cannot open display: :0`

**Expected behavior**
The app opens

**Desktop (please complete the following information):**
 - OS: Gentoo linux
 - Installation package snap
 - Version [2.34.0]

**Additional context**

**Workaround**
A workaround is to set env variable `DISABLE_WAYLAND=1 snap run caprine`
This forces the electron app to fall back to XWayland

I will create a PR for the fix.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/caprine/pull/1007#issuecomment-514854648
