### ISSUE TITLE
Messenger Update Breaks Dark & Light mode

### ISSUE THREAD

**Issue by artistro08** [sindresorhus/caprine#1008]
Check screenshot
![image](https://user-images.githubusercontent.com/6427230/61584227-af8fc100-ab09-11e9-9dd0-0b72e991351e.png)

**Comment by artistro08** [comment]
Should note, I downloaded it from the Windows store

**Comment by sindresorhus** [comment]
The Windows store version has not been updated for years.

**Comment by sindresorhus** [comment]
@nozzlegear Can you please take it down from the Windows Store?

**Comment by nozzlegear** [comment]
@sindresorhus Sure thing, I've unpublished it. 

Sorry to everyone who's been using it, I simply haven't had the time to keep up with upstream changes and never found a great way to automate publishing to the Windows Store. If anyone wants to try their hand at it, check out the [appx.ps1](https://github.com/nozzlegear/caprine/blob/14c36db6dbc041f907b6834421cc712374ef7ba5/build/appx.ps1) file in my fork of Caprine, it should have enough info to get you started.

**Comment by sindresorhus** [comment]
@nozzlegear Thank you! 🙌
