### ISSUE TITLE
Feature request: Making titlebar more uniform on windows

### ISSUE THREAD

**Issue by artistro08** [sindresorhus/caprine#1009]
Not sure if this is possible with the setup in Windows with the way that you are building it. But I just saw this type of design done on windows and I would like to see it in the app. If it's not doable, I completely understand. 

This is app is todoist from the windows store to give an example: 

![image](https://user-images.githubusercontent.com/6427230/61635266-c7c22600-ac58-11e9-9e1d-62b7818f680f.png)

If it can't be done, It can't be done.

**Comment by CvX** [comment]
Already tracked in #652 🙂

**Comment by artistro08** [comment]
Thanks! Wasn't sure!
