### ISSUE TITLE
Unable to move window on Mac OS X 10.11.4

### ISSUE THREAD

**Issue by c99koder** [sindresorhus/caprine#101]
Just upgraded from 0.2.1 to 1.4.0 (really need some kind of update notifications) and I'm no longer able to drag the window around to reposition it.  Previously I was able to drag the window title bar to move the app to my 2nd monitor, but the current version ignores mouse drags in the title bar area.  I can kind of move it around the main monitor by resizing it, but I can't get it onto the 2nd monitor this way as OS X 10.11 doesn't allow windows to span multiple monitors.  I'm using Mac OS X 10.11.4, Caprine v1.4.0.

**Comment by danhp** [comment]
Ref: https://github.com/electron/electron/pull/5557
