### ISSUE TITLE
Portable (portapps.io) version crashes on startup (JavaScript error)

### ISSUE THREAD

**Issue by MattKneale** [sindresorhus/caprine#1016]
![image](https://user-images.githubusercontent.com/20257128/62144158-394d4480-b2e9-11e9-8595-3eea8645b0ab.png)

Crashes immediately upon startup. Appreciate a portable build probably won't be at the top of your priorities, but any solutions are welcomed if available!

**Comment by MattKneale** [comment]
Never mind - direct download of 2.3.4 here is portable and so no need to go via Portapps.io. This one works! Thanks anyway.

**Comment by sindresorhus** [comment]
We don’t manage the one at PortableApps.
