### ISSUE TITLE
Removed message doesn't follow dark theme

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1017]
If you are using dark mode and remove a message in a chat, the resultant message bubble shows up completely white (with white text). If you highlight it, you can see the message, "You removed a message", but it is very hard to see.

Similar to #776 and #868, but those were for much older versions.

Version 2.34.0, Linux Mint 19.1, installed via .deb

![normal view](https://user-images.githubusercontent.com/17033543/62315974-80ac1000-b464-11e9-9864-79f456532b44.png)

![highlighted version](https://user-images.githubusercontent.com/17033543/62315997-8c97d200-b464-11e9-994a-814344e56c21.png)

**Comment by simjes** [comment]
I would like to work on this issue
