### ISSUE TITLE
Dark Mode text box staying white

### ISSUE THREAD

**Issue by Armandfgs** [sindresorhus/caprine#1018]
-> Turn on dark mode
-> Look at text box

This is how it looks:
![image](https://user-images.githubusercontent.com/23267566/62411801-14aee080-b5f9-11e9-8b33-2681177bb325.png)

This is how it looks when typing:
![image](https://user-images.githubusercontent.com/23267566/62411807-21333900-b5f9-11e9-96f0-933f38104bd5.png)

To ensure that there is text and to check that I didn't do any spelling mistakes I have to select it as such:
![image](https://user-images.githubusercontent.com/23267566/62411812-2b553780-b5f9-11e9-8d1a-8d3a677d9cd1.png)

---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.18362

**Comment by CvX** [comment]
Already fixed in #1012, will be released in 2.35.0.
