### ISSUE TITLE
Option to always display newest (unread) conversation on startup

### ISSUE THREAD

**Issue by tiritto** [sindresorhus/caprine#1019]
I would like to suggest a new feature. Right now, whenever we open Messanger, by default it displays the most recent conversation that was marked as Read. Personally, I find this behaviour pretty annoying as I would rather prefer to always see the newest message first (even if it's unread).

Therefore, I would like to suggest new feature for Caprine that would allow us to change that behaviour and always open on the newest message (conversation on top of the list). It could probably be available as simple toggle in the settings.

**Comment by sindresorhus** [comment]
I think we should just make it the default behavior.
