### ISSUE TITLE
Opening the info sidebar results in super-wrapped text if window is thin

### ISSUE THREAD

**Issue by Ariane-B** [sindresorhus/caprine#1020]
I like to use Caprine as a sidebar. It occupies maybe the left 20% of my screen, and whatever else I'm doing has the rest. It works fine for most applications. If I open someone's info (circled "i" button), however, it looks... funny.

![image](https://user-images.githubusercontent.com/6244273/62436272-30a3a680-b70d-11e9-97ee-fd13e2b31ed0.png)

It would be nice if this could be improved. By adding putting that part in a pop-up when the window is too thin, for instance.

**Comment by whitecrownclown** [comment]
The `messenger.com` behaviour is to have a set min-width on the window. We could do that or we could overflow the content instead. I'd prefer the `messenger.com` behaviour.

@CvX @sindresorhus What do you guys think?

**Comment by CvX** [comment]
It would be better to still allow small window sizes. Maybe we could make the sidebar sit on top of other content (rather than beside it) when the window's width is lower than X?

**Comment by whitecrownclown** [comment]
<img width="512" alt="Screenshot 2019-08-05 at 20 28 33" src="https://user-images.githubusercontent.com/8309417/62483856-673af900-b7c1-11e9-9232-fa504c13bc45.png">

@CvX Is this something close to what you imagined?

**Comment by CvX** [comment]
Yeah! 😃 It could even be full height – at this width you'd most likely open the sidebar, do whatever, and close it. Dunno. 🙂

**Comment by whitecrownclown** [comment]
Yeah, I also think it might be better for it to be full height. I'll open up a PR and we can talk over it.
