### ISSUE TITLE
Issues with dark theme

### ISSUE THREAD

**Issue by HBOlsen** [sindresorhus/caprine#1021]
The input textbox is still white when running app in "dark theme" mode. The area around the "thumbs up" icon in chats also has a white square around it.

![image](https://user-images.githubusercontent.com/22715517/62447527-e39fee80-b765-11e9-86bc-a65ad69a5c13.png)

Caprine 2.27.1
Electron 4.0.1
win32 10.0.17134
Locale: en-US

**Comment by CvX** [comment]
Please try the latest version: 2.34.0

**Comment by HBOlsen** [comment]
2.34.0 seems to have fixed the issue. The text placeholder text in the input area is however barely visible. Is there any chance you could tweak this to a lighter color?
I also noticed the auto updater stopped working? In the past I've had a notification near the top of Caprine telling me there was a new version but not now?

**Comment by CvX** [comment]
> The text placeholder text in the input area is however barely visible. Is there any chance you could tweak this to a lighter color?

The fix for that has just been released in [2.35.0](https://github.com/sindresorhus/caprine/releases/tag/v2.35.0)! 🙂 

> In the past I've had a notification near the top of Caprine telling me there was a new version but not now?

That's the Messenger's update notification, not Caprine's. 🙂 Caprine silently checks for updates, and if there is one, it installs it the next time you start the app.

**Comment by HBOlsen** [comment]
> The fix for that has just been released in 2.35.0! 🙂
Awesome, thank you very much!

> Caprine silently checks for updates, and if there is one, it installs it the next time you start the app.
This doesn't happen on either of my two machines. One is still running 2.29.x and one was manually updated to 2.34.0 yesterday. Is there a way to trigger the update in-app?
