### ISSUE TITLE
Window go back to default size

### ISSUE THREAD

**Issue by myszaa** [sindresorhus/caprine#1026]
After restart Caprine, application window go back to default window size, it is flustarting, when you need to increase window size after every run application.

Resolution: save application window size and position

**Comment by sindresorhus** [comment]
Caprine does persist the window size and position. I can't really help without more info about your Caprine version, operating system, etc.

**Comment by myszaa** [comment]
MacOS 10.14.6, Caprine 2.34.0 so the latest version. When i completly quit from application and start it again, windows size and position is setted as default, not thta, which was befor exit application.
