### ISSUE TITLE
Lags and high CPU load when searching contacts 

### ISSUE THREAD

**Issue by amykhas** [sindresorhus/caprine#1029]
After the latest update, when using Search Messanger in a sidebar list, the app starts to freeze and use a lot of CPU. Works so 10 out 10 times.  

---

Caprine 2.34.0
Electron 5.0.6
darwin 18.6.0
Locale: en-US

**Comment by CvX** [comment]
Does this feature work for you at https://messenger.com?

I don't think Caprine is augmenting the search in any way. 🤔

**Comment by amykhas** [comment]
Messenger works great in Safari. In the latest version of Caprine, the sidebar was updated - it got semi-transparent background and you can't drag app window holding your pointer in a sidebar area

**Comment by andygmorris** [comment]
@amykhas Late I know, but as no solution posted... I found high cpu (~70% by both core app and renderer helper) to be caused on macos when Caprine > View > Follow System Appearance was checked. Switching that off and selecting Dark Mode (my preference) removed the high cpu. Adding Sidebar-only Vibracy for a bit of extra decoration did not add to any cpu either. Hope it helps.

**Comment by whitecrownclown** [comment]
@andygmorris @amykhas 

I think the issue was fixed with #1247. Can you let us know if that's the case by trying the latest version? Thanks!

**Comment by amykhas** [comment]
Yes, it was fixed. Now able to reproduce on 2.43 and 2.44.
