### ISSUE TITLE
Uncaught exception at startup

### ISSUE THREAD

**Issue by matkaz** [sindresorhus/caprine#1035]
Each time I log in I can see the following window:
![obraz](https://user-images.githubusercontent.com/12645105/62832491-5bbb5800-bc2f-11e9-80fe-1de654779411.png)
I've noticed that it takes some time on my computer to connect with the network. This error occurs before it connects but I don't know is it related.
This is a regression. At 2.32.0 I could see a window asking me if I want to wait for connection instead.

I've downgraded Caprine to 2.34.0. It seems to be free of this bug.
---

Caprine 2.35.0
Electron 6.0.1
linux 4.15.0-55-generic
Locale: pl

**Comment by whitecrownclown** [comment]
@sindresorhus @CvX @matkaz 	The fix for this is included in #1037.

**Comment by matkaz** [comment]
Now it works. I'm closing the issue. Thanks @whitecrownclown for fixing it so fast.
