### ISSUE TITLE
Click on avatar in a group chat leads to login page

### ISSUE THREAD

**Issue by z-ax** [sindresorhus/caprine#104]
Hi, got this today, decided to submit just in case: in a group chat when I click on avatar - login page appears after the short blink of chat with selected person, but on "Follow link" selected chat appears as expected. Kinda weird, probably a FB bug :)

![1735f1e2-2725-11e6-8e75-490c516e7471](https://cloud.githubusercontent.com/assets/1391015/15669120/59718362-2727-11e6-821a-1ffd5fb5747b.png)

**Comment by danhp** [comment]
This got fixed on Facebook's end of things.
Closing this out.
