### ISSUE TITLE
Bugs in 2.36.0.1586: vibrancy gone + sign-in broken

### ISSUE THREAD

**Issue by Andro** [sindresorhus/caprine#1042]
Bugs in 2.36.0.1586 in macOS: vibrancy gone + have to sign in every time I open the app, with "keep me signed in" ticked...

Caprine 2.36.0
Electron 5.0.6
darwin 18.7.0
Locale: en-US

**Comment by neegool** [comment]
Same bug as mentioned above. Also noting that the auto-updater still points to the 2.36 build
