### ISSUE TITLE
Refusal to stay signed in

### ISSUE THREAD

**Issue by arcues19875** [sindresorhus/caprine#1044]
Every time I close out of Caprine, it instantly logs me out, having to log in again every time that I open Caprine. I have closed out of it using the Quit Caprine button, I have done Command + Q and have tried logging out of it, logging back in and quitting with the same result.
---

Caprine 2.36.0
Electron 5.0.6
darwin 18.7.0
Locale: en-GB

**Comment by khvnhtung** [comment]
Same problem for me.
Caprine 2.36.0
MacOS Mojave 10.14.6

**Comment by sneila** [comment]
same here

**Comment by stevyhacker** [comment]
Here as well.

**Comment by RaunoT** [comment]
Can confirm.

**Comment by epicserve** [comment]
I can't seem to sign in at all or type in the username and password fields. This started today for me.

<img width="1058" alt="Messenger 2019-08-13 07-50-25" src="https://user-images.githubusercontent.com/191620/62943062-3b121000-bd9f-11e9-933c-3a8e22179d91.png">

### Versions
macOS Mojave: 10.14.16
Caprine: 2.36.0 (2.36.0.1586)

**Comment by CvX** [comment]
@epicserve This one is related to #712, as a workaround you can just temporarily disable vibrancy and/or dark mode.

**Comment by ssztemberg** [comment]
How to disable auto app updates?

**Comment by epicserve** [comment]
@CvX, Thanks for the help, unfortunately, I ran into a new issue where my security key for 2FA doesn't work. Has that issue been reported at all?

**Comment by ookangzheng** [comment]
Me too ~~ 2FA and blank scren

**Comment by DaivikGoel** [comment]
Same issue here

**Comment by epicserve** [comment]
I think it would be helpful to stop with the "me too" posts and just add a thumbs up to issue at the top. The "me too" posts spam everyone following the issue and add unnecessary clutter to sort through. 🙂

**Comment by matkaz** [comment]
Sounds similar to #1036

**Comment by khvnhtung** [comment]
It's the MeToo movement.

**Comment by hieuhuynh93** [comment]
Same here. I have no enabled the vibrancy option.
![igf0.png](https://i.snapgo.top/igf0.png)

**Comment by ookangzheng** [comment]
> How to disable auto app updates?

There's no way to stop auto app update, It kinda sucks that I have to use Firewall(Littlesnitch) to block caprine from surfing github.com. 🙅‍♂

**Comment by zebapy** [comment]
Not sure autoupdate matters. I just downloaded v1 and still same problem cause it's gotta be due to messenger website.

**Comment by thisiskeithb** [comment]
> There's no way to stop auto app update, It kinda sucks that I have to use Firewall(Littlesnitch) to block caprine from surfing github.com. 🙅‍♂

Ohhhh, I didn't even think to do that. Blocking now!

**Comment by stevensacks** [comment]
Same. It's definitely the latest version.

**Comment by gentb** [comment]
Caprine 2.36.0
macOS 10.14.5

Got it to work by uninstalling with [AppCleaner ](https://freemacsoft.net/appcleaner/) (note: this will remove any settings via pref/config files you have set on caprine). Drag and drop caprine from applications dir into AppCleaner and remove all files suggested.

Then proceed normally with a clean reinstall of 2.36.0.

**Comment by mgol** [comment]
@gentb That helped, thanks a lot!

**Comment by hieuhuynh93** [comment]
@gentb Thanks. That helped. We also can use either AppCleaner or CleanMyMac to uninstall the current Caprine app. The issue was resolved.

**Comment by shivaalroy** [comment]
@gentb thank you! worked for me

**Comment by antonio-ramadas** [comment]
I uninstalled Caprine, removed Caprine's folder in the `userData` directory and then installed again. It solved the problem! I had no need to either use AppCleaner or CleanMyMac to have the issue fixed.

I think uninstalling Caprine was an unnecessary step. Just removing the directory with the app closed should be effective as well.

If you want to try the same, the directory I mentioned is:
 - `%APPDATA%` on Windows
 - `$XDG_CONFIG_HOME` or `~/.config` on Linux
 - `~/Library/Application\ Support` on macOS

In case you are wondering how I got to these directories:
 1. Caprine uses [electron-store](https://github.com/sindresorhus/caprine/blob/master/package.json#L33) to save its state. We can check its usage in [_config.ts_](https://github.com/sindresorhus/caprine/blob/09376506cd6a82417556fba57c2bcc38a2844458/source/config.ts#L169).
 2. [electron-store](https://github.com/sindresorhus/electron-store) uses [`userData` as the default path](https://github.com/sindresorhus/electron-store#cwd). Underlying, this package uses the electron API [`app.getPath(name)`](https://electronjs.org/docs/api/app#appgetpathname).

**Comment by Mattrak** [comment]
Confirm that just removing the directory is effective. Thanks!

**Comment by dusansimic** [comment]
This seems to be fixed by https://github.com/sindresorhus/caprine/issues/1044#issuecomment-521925982. I'll close this now.
