### ISSUE TITLE
Vibrancy, "follow system appearance" and "stay logged in" failure

### ISSUE THREAD

**Issue by erettandris** [sindresorhus/caprine#1046]
I downloaded the latest version of Caprine and it doesn't stay logged in (when I quit the application it loose my email and passwd while the "stay logged in" was checked. so when I open the app next time I have to log in again). The "follow system appearance" is on, but caprine doesn't change to dark mode (or light mode) automatically, I have to restart the app. The vibrancy doesn't work at all

---

Caprine 2.36.0
Electron 5.0.6
darwin 18.6.0
Locale: hu

**Comment by richardqhill** [comment]
Also on Version 2.36.0 (2.36.0.1586) and it doesn't stay logged in after I quit and re-open

**Comment by iamuros** [comment]
Bumping up the same issue. Version 2.36.0

**Comment by lyapustin** [comment]
Same here. Quite annoying :(

**Comment by stpfr** [comment]
Same issue here. V 2.36.0 on darwin.

**Comment by voriondev** [comment]
Same issue here, with version 2.36.0.1586.

**Comment by scott-slash** [comment]
Same issue here - doesn't stay logged in.

Version 2.36.0 (2.36.0.1586)
