### ISSUE TITLE
Messenger Code Block highlighting color in Dark Mode

### ISSUE THREAD

**Issue by Yukaii** [sindresorhus/caprine#105]
![bright](http://i.imgur.com/kmh0qvc.png)

![dark](http://i.imgur.com/6ep1IZk.png)

**Comment by sindresorhus** [comment]
How do you do a code block in Messenger?

**Comment by Yukaii** [comment]
using markdown syntax:

![](http://i.imgur.com/YstDPTK.png)

**Comment by sindresorhus** [comment]
Oh, awesome! I didn't realize that was possible. We'll definitely make it look better in dark mode then :)
