### ISSUE TITLE
caprine does not start after deleting configuration

### ISSUE THREAD

**Issue by Piscium** [sindresorhus/caprine#1050]
I run Caprine in two PCs using Arch, I am using the dark theme:
- old, ASUS mother board with Nvidia card
- newer, Dell with embedded Intel graphics

I am running Caprine v. 2.35 in the newer PC, Electron v. 6.0.1.

Caprine freezes in both, however far more often in the newer PC. So today I deleted the Caprine configuration in the newer PC (in ~/.config/Caprine) to see if that would solve the problem but it got worse, now Caprine does not start at all. I reinstalled it but did not make any difference. Starting from a terminal this is what I get:

___________________________________
$ caprine
(node:7188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:7188) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:7188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Piscium** [comment]
$ pacman -Qi caprine
Name            : caprine
Version         : 2.34.0-1
Description     : Unofficial Facebook Messenger app
Architecture    : any
URL             : https://github.com/sindresorhus/caprine
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : electron
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 9.98 MiB
Packager        : Nicola Squartini <tensor5@gmail.com>
Build Date      : Mon 15 Jul 2019 06:02:10 IST
Install Date    : Sat 03 Aug 2019 17:18:59 IST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

$ pacman -Qi electron
Name            : electron
Version         : 6.0.1-1
Description     : Build cross platform desktop apps with web technologies
Architecture    : x86_64
URL             : https://electronjs.org/
Licenses        : MIT  custom
Groups          : None
Provides        : None
Depends On      : c-ares  ffmpeg  gtk3  http-parser  libevent  libnghttp2  libxslt  libxss  minizip  nss  re2  snappy
Optional Deps   : kde-cli-tools: file deletion support (kioclient5) [installed]
                  trash-cli: file deletion support (trash-put) [installed]
                  xdg-utils: open URLs with desktop's default (xdg-email, xdg-open) [installed]
Required By     : caprine
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 135.32 MiB
Packager        : Nicola Squartini <tensor5@gmail.com>
Build Date      : Sat 10 Aug 2019 08:48:39 IST
Install Date    : Sat 10 Aug 2019 11:24:54 IST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

**Comment by whitecrownclown** [comment]
@Piscium This issue has been fixed and will be in a future release (https://github.com/sindresorhus/caprine/pull/1037).

Until then you can use `v2.34` or `v2.36` (they're basically the same) to avoid this issue.

**Comment by Piscium** [comment]
Yes, I downgraded back to 2.34 and the problem disappeared. However the original issue of the freeze is still there. I will close this issue and create a new one about the freeze.
