### ISSUE TITLE
Caprine freezes sometimes when a new message arrives

### ISSUE THREAD

**Issue by Piscium** [sindresorhus/caprine#1051]
I run Caprine in two PCs:

- old, ASUS mother board with Nvidia card
- newer, Dell with embedded Intel graphics

Caprine freezes in both, however far more often in the newer PC. The freeze happens when a new message arrives, though not every time a message arrives. When it freezes I have to kill the Caprine process.

I am running Caprine v. 2.34 and Electron v. 6.0.1 on Arch Linux using the dark theme.

I noticed that on the PC where Caprine freezes most often there are usually 4 processes running Electron whereas there are 5 in the PC where Caprine freezes less often. Not sure if this matters!

**Comment by Piscium** [comment]
So today I updated Caprine on the newer computer to the Git master version and the issue is still there. I can't understand why this manifests in one computer and not the other. Could it be because of internet connection speed? The newer computer is on a slower connection.

**Comment by Piscium** [comment]
To investigate this issue further I enabled and disabled various Caprine settings to see if it made any difference. Conclusion of my tests: **if I choose "Mute Notifications" Caprine does not freeze**. Notifications are not working for me anyway as I never saw any. So the above is a workaround until the problem is fixed.

**Comment by NickDuBois** [comment]
Reporting here that on ubuntu 22, on a new dell laptop caprine freezes with every new message and I have to close the processes and restart. 

I just uninstalled and reinstalled it.  Fingers crossed cause this is super annoying.

**Comment by Piscium** [comment]
> Reporting here that on ubuntu 22, on a new dell laptop caprine freezes with every new message and I have to close the processes and restart.

Same here. I first reported this issue 4 years ago and it still exists. Funny thing, for me on Arch Linux it did not happen (if I remember well) with the previous version. Yesterday I upgraded and today is happening a lot. These are the changes:
https://gitlab.archlinux.org/archlinux/packaging/packages/caprine/-/commit/855fdbe24682f22f0399949a20987879c40364dd

So it is the same source code, only the package version number changed, presumably because the package maintainer wanted to force a rebuild of the package to pick up new libraries. Electron changed from 24.6 (when the previous Caprine package was built)  to 24.8. I reinstalled the Caprine version that worked and so far the issue did not appear (although I received only one message since).

I have Conky installed where I can see how much CPU is being used and which are the top six processors using RAM and CPU. When the issue happens Caprine is using 100% or one of the cores.

I would not mind trying to run some diagnostics with some tools, however I know about nothing of Javascript so someone would need to tell me how to do it.

I don't understand why so few people get this issue. Over the years I have deleted the configuration folder and started again several times with no effect.

**Comment by 151SoGood** [comment]
Agree - this issue has persistently happened to me over the last 3 years I've used it - I always have to restart the app. Any fixes?

**Comment by Piscium** [comment]
It happened again to me a couple of days ago on Arch with the latest version, 2.59.0. I downgraded to 2.58.0 and so far it has not happened. 2.58.0 seems more stable although I would not go as far as saying that the issue does not exist in it.

I wonder if this Github issue could not be reopened as it is still active? Probably it takes an admin to do that, I don't think I have permission.
