### ISSUE TITLE
Dark Mode broken in 2.36.0

### ISSUE THREAD

**Issue by lonecactus** [sindresorhus/caprine#1052]
Upgraded to Caprine 2.36 on Mojave 10.14.6. Was using Caprine's Dark Mode (View > Dark Mode: checked). After closing Caprine and reopening, dark mode now looks like this.

![Menubar_and_Messenger](https://user-images.githubusercontent.com/46927805/63196879-5f424b00-c044-11e9-8e5b-135bcdf5b792.jpg)

Normal non-dark mode appears to be working fine.

**Comment by riconaranjo** [comment]
I have this same issue, but without any vibrancy the dark mode version works fine

**Comment by lonecactus** [comment]
Confirming riconaranjo's workaround restores dark mode functionality for me

**Comment by marcinlesek** [comment]
Any updates on Vibrancy bug maybe @sindresorhus @CvX? 🤔

**Comment by nathan-fiscaletti** [comment]
Awe, i literally just downloaded this for the dark mode + vibrancy feature. Hopefully this can get fixed soon :(

**Comment by CvX** [comment]
@marcinlesek you can try out the workaround in #1070
