### ISSUE TITLE
Why no Win32 build?

### ISSUE THREAD

**Issue by RJVB** [sindresorhus/caprine#1054]
Why isn't it possible to do a Win32 build? If I understand correctly this application is written in interpreted code, or code that can be run in a (JavaScript) interpreter, to execute remote code that runs perfectly fine in a 32bit browser.

Is this for the same reason why it has become practically impossible to build for older OS X version, i.e. because Electron is no longer available for that OS version (IOW, we just have to put up with what the electron powers that be decide for us)?

**Comment by sindresorhus** [comment]
It’s mostly because I cannot test for it and don’t care. Everyone should be on 64-bit in 2019.

**Comment by sindresorhus** [comment]
You are of course free to do a 32-bit build yourself. It’s not hard.

**Comment by RJVB** [comment]
That’s BS. Good luck running Win64 on a (tablet) device with only 2Gb of RAM, regardless of what year you bought it. And that’s exactly the kind of device where a dedicated Messenger app makes sense.

I don’t care if an official build is provided, and would be perfectly happy to build and test (= use) it myself.

**Comment by RJVB** [comment]
You are of course free to do a 32-bit build yourself. It’s not hard.

I’m not having any luck figuring out how (I’d have to do this on a Linux machine)

**Comment by RJVB** [comment]
As a courtesy to others in the same position as I:

Doing a 32bit build is easy indeed once you've found out how, which is NOT straightforward for the casual builder.

The trick is to create a `.npmrc`, containing a line that says `arch=ia32`. If necessary, clean by deleting the `node_modules` and `dist` directories, and rebuild/package.
