### ISSUE TITLE
Logout bug

### ISSUE THREAD

**Issue by sgolemanski** [sindresorhus/caprine#1055]
The program stopped remembering my login details and requires them every time I open it.

---

Caprine 2.36.0
Electron 5.0.6
darwin 18.7.0
Locale: en-GB

**Comment by Trychlik** [comment]
same problem, on 2.35 its ok, but there is autoupdate, which cannot be disabled and after restart app, problem is back :/

**Comment by harpalassi** [comment]
same issue here. makes me log in every time I open it.

**Comment by satya164** [comment]
Duplicate of #1044

**Comment by sgolemanski** [comment]
I managed to fix it by uninstalling Caprine with the help of CleanMyMac, and then installed it again and now it remembers the login credentials.

**Comment by Trychlik** [comment]
> I managed to fix it by uninstalling Caprine with the help of CleanMyMac, and then installed it again and now it remembers the login credentials.

thanks, worked for me too
