### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ldelestre** [sindresorhus/caprine#1056]
<img width="1440" alt="Capture d’écran 2019-08-20 à 11 32 51" src="https://user-images.githubusercontent.com/40627369/63335784-44baeb00-c33e-11e9-83d9-443f784bb7bb.png">

How can I fix that ? I re-downloaded Caprine but it still doesn't work.
---

Caprine 2.36.0
Electron 5.0.6
darwin 18.7.0
Locale: fr

**Comment by ldelestre** [comment]
I found out that dark mode makes the bug.

**Comment by stpfr** [comment]
Confirmed fixed in 2.37
