### ISSUE TITLE
AUR out of date (and broken)

### ISSUE THREAD

**Issue by kamiyay** [sindresorhus/caprine#1058]
The current version available for Arch via the AUR is currently 2.35-1, when the latest version otherwise is 2.3.7. When caprine is installed via the AUR there is an error upon launching that appears to have been fixed in 2.3.6.

**Comment by sindresorhus** [comment]
We don't maintain the Arch build.

// @Vincevrp

**Comment by Vincevrp** [comment]
I don't maintain it either, and I can't seem to find caprine in the AUR. Caprine is in the community repo, which should not be confused with the AUR. It is maintained by @tensor5
