### ISSUE TITLE
Auto-update issue on Mac OS X with v2.37.0

### ISSUE THREAD

**Issue by evanwon** [sindresorhus/caprine#1059]
I noticed that Carpine was not auto-updating on my computer (macOS Mojave, 10.14.6). I checked out the logs today, which contained the following:

```
2019-08-20 16:26:19.694] [info] Checking for update
[2019-08-20 16:26:20.710] [error] Error: Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/sindresorhus/caprine/releases/download/v2.37.0/latest-mac.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/sindresorhus/caprine/releases/download/v2.37.0/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

When I look at the v2.37.0 release, I see that it doesn't contain `latest-mac.yml` as is mentioned in the error message.

**Comment by CvX** [comment]
Yeah, the build process is currently broken (see: https://github.com/electron-userland/electron-builder/issues/4134). I've reverted that release to the "draft" status.

@sindresorhus could you build and publish locally in the meantime?

**Comment by dusansimic** [comment]
We've switched to GitHub Actions and there seem to be no issues with auto updating.
