### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by PearsAreGross** [sindresorhus/caprine#1065]
(node:18760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:18760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:18760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dusansimic** [comment]
Closing this issue as it is stale. If the error is still there, please ping me in the comment.
