### ISSUE TITLE
Improve the look of code blocks

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#107]
They look pretty ugly by default, and would be nice to have a different style in dark mode.

Follow-up to https://github.com/sindresorhus/caprine/issues/105.

**Comment by SimenB** [comment]
It's messed up for me (unreadable)

![image](https://cloud.githubusercontent.com/assets/1404810/17773758/3668bfae-6550-11e6-8aa3-0d3d3a9b58c0.png)

Without dark mode:
![image](https://cloud.githubusercontent.com/assets/1404810/17773765/3e00bb86-6550-11e6-809e-62e8869a65b1.png)

**Comment by sindresorhus** [comment]
They probably changed some CSS selectors. 

<img width="86" alt="screen shot 2016-08-18 at 17 10 47" src="https://cloud.githubusercontent.com/assets/170270/17779084/b9fc0f36-6566-11e6-8c33-0cf1cc751121.png"> 😉

**Comment by tschuy** [comment]
looks like the lightest color is the only broken one.

I'll poke around at this in a few hours when I'm off work :)

**Comment by katopz** [comment]
I'm curious that why css class name look [unreadable](https://github.com/sindresorhus/caprine/blob/master/browser.css#L6) 
I think I could help but it's kinda hard to guess what is it.

**Comment by Bo-Duke** [comment]
So, I use code blocks a lot, and seeing that I'm not the only one finding those very ugly, I made a thing : 

![code-blocks-choice](https://user-images.githubusercontent.com/9383709/27517897-1fcb76aa-59d4-11e7-86dd-b1f1a57d75b4.gif)

But this seems a bit overkill for an app that isn't really targeted at developers, so I also made this : 

![code-blocks-toggle](https://user-images.githubusercontent.com/9383709/27517899-3cf54454-59d4-11e7-83e9-c1f9a4ebbc78.gif)

Of course I can do this with any other color scheme

**Comment by sindresorhus** [comment]
The second one looks amazing. Would you be interested in doing a pull request?

**Comment by Bo-Duke** [comment]
Of course, I'll do it when I get home
