### ISSUE TITLE
Blurry profile pictures

### ISSUE THREAD

**Issue by curiousyetlost** [sindresorhus/caprine#1073]
I appear to suddenly have blurry profile pictures. I have restarted the application and the machine repeatedly since it began several days ago but there appears to be nothing that is causing it that I can find. It happens immediately on load. I created a new user on the local machine and it is doing the same thing and I have redownloaded the app, same deal. Screenshot attached. Any thoughts?

![Screen Shot 2019-09-04 at 3 38 43 PM](https://user-images.githubusercontent.com/7131599/64265016-19cdbb00-cf2a-11e9-988f-adc1409f5eaa.png)

---

Caprine 2.37.0
Electron 6.0.3
darwin 19.0.0
Locale: en-US

**Comment by CvX** [comment]
Looks like you’ve accidentally enabled “Hide Names and Avatars”

<kbd>Command/Control</kbd> <kbd>Shift</kbd> <kbd>n</kbd>
