### ISSUE TITLE
app install error message

### ISSUE THREAD

**Issue by tfdjim** [sindresorhus/caprine#1074]
Equipment: Toshiba laptop, intel i5 processor
Operating system: Linux Mint Debian Edition 3

Installed Snap without incident. Installed two Snap apps: hello-world and simplenote with no problem. 

Attempted to install caprine and got this error message:

$ sudo snap install caprine
[sudo] password for jim:         
error: cannot perform the following tasks:
- Mount snap "caprine" (28) (cannot find required base "core18")

Any idea what is causing the error message?

**Comment by dusansimic** [comment]
Try this solution out: https://github.com/snapcore/core18/issues/128#issuecomment-494221517.
