### ISSUE TITLE
"Insert [content]" options do not work as expected

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1076]
**Current Behavior:**
Insert GIF: Seems to do nothing at the moment, even if GIF or emoji selection pop-up is opened.
Insert Emoji: Toggles the emoji selection pop-up. The GIF selection pop-up is unaffected by the emoji selection pop-up, so both can be showing at once.
Insert Text: Seems to do nothing at the moment, even if any pop-ups are showing

**Expected Behavior:**
Insert GIF: Toggle the GIF selection pop-up
Insert Emoji: Toggle the emoji selection pop-up. If the GIF selection pop-up is already showing, it would close that before opening in the emoji pop-up.
Insert Text: Put the cursor in the text box and minimize any pop-up menus (Emoji or GIF) that are currently showing.

Caprine v2.37.0
Installed via .deb
Linux Mint 19.2

**Comment by sindresorhus** [comment]
This was fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.38.0

**Comment by mquevill** [comment]
Is it expected to open multiple of these on top of each other? I would expect one window to close if I open another. For instance, the current behavior is ctrl+G opens GIF window, ctrl+E opens emoji window _on top of_ GIF. The messenger.com interface only shows one window at a time, and clicking another menu will close any open menu.
