### ISSUE TITLE
Random high upload traffic

### ISSUE THREAD

**Issue by AggelosM** [sindresorhus/caprine#1078]
Every a couple of hours Caprine sends full traffic to an IP without stopping. Using NetLimiter I found that the IP is 2a03:2880:f028:11:face:b00c:0:2:443.

I have to restart it to make it stop.

---

Caprine 2.37.0
Electron 6.0.3
win32 10.0.17763
Locale: en-US

**Comment by rvshi** [comment]
I believe that's just the IP for messenger.com (https://tools.tracemyip.org/lookup/messenger.com)

**Comment by dusansimic** [comment]
Messenger does this, not Caprine. I wouldn't mess around with this since it might break some Messenger functionality. If it's an enormous amount of data (a couple hundreds of megabytes), we'll look into. Otherwise this is closed.
