### ISSUE TITLE
No UTF-8 support

### ISSUE THREAD

**Issue by ventaquil** [sindresorhus/caprine#108]
I can't send messages with Polish signs like "_ę_", "_ą_", "_ć_". I can't write this letters in text field :disappointed:

**Comment by sindresorhus** [comment]
Works fine for me on OS X. What OS and Caprine version are you on?

**Comment by ventaquil** [comment]
I'm working on xubuntu 16.04. Caprine version is 1.4.1 for Linux.

**Comment by sindresorhus** [comment]
If it's actually a problem, it's with Electron, not this app. Try the latest version. Maybe it has been fixed: https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
