### ISSUE TITLE
can't drag window 

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#1083]
i can't drag the interface window by click-dragging the upper part. click-dragging the part below that however, has the expected behavior of moving the window.
usually, like how other apps function, the whole top area, including the empty area to the right of the three colored dots, can be click-dragged

---

Caprine 2.37.0
Electron 6.0.3
darwin 18.5.0
Locale: nb

**Comment by CvX** [comment]
I'm guessing this https://github.com/sindresorhus/caprine/blob/master/css/browser.css#L30-L36 has to be updated to include the latest changes in the "new Messenger UI".

**Comment by dusansimic** [comment]
Since this seems to work now I'll close this issue. If there are any more problems, please ping me in the comment.
