### ISSUE TITLE
Messenger Contacts not display

### ISSUE THREAD

**Issue by tlkw79** [sindresorhus/caprine#1086]
Messenger contacts in sidebar never show up after login.
---

Caprine 2.38.0
Electron 6.0.7
linux 5.0.0-29-generic
Locale: en-US

**Comment by dusansimic** [comment]
Please update to the latest version of Caprine and check if your sidebar is enabled (`View -> Sidebar -> Hide Sidebar`). It's easy to accidentally hide the sidebar using `Ctrl+Shift+S` combination.
