### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by rymar1** [sindresorhus/caprine#1089]
Can't swicth to dark mode as the text entry box makes the cursor invisible. Running Linux mint 64
![image](https://user-images.githubusercontent.com/24767721/65799286-9d915680-e128-11e9-861a-b7d07b1c440f.png)
 
---

Caprine 2.16.0
Electron 2.0.4
linux x64 4.15.0-64-generic

**Comment by CvX** [comment]
Please update to version 2.38.0

**Comment by dusansimic** [comment]
I'll close this as it seems to be just an outdated version of Caprine and the problem doesn't occur in the latest one.
