### ISSUE TITLE
Icons blurry on retina displays

### ISSUE THREAD

**Issue by ChristianKlee** [sindresorhus/caprine#109]
On retina displays the icons (Emoji and other elements) are not displayed in the retina mode and look blurry. Is it possible to enable a retina mode?

**Comment by derekjobst** [comment]
Any ideas on why this might be happening?

**Comment by sindresorhus** [comment]
It's seems to be an issue with the Facebook retina screen detection. I have yet to find a workaround for it...

Caprine is not the only app with this issue: https://github.com/rsms/fb-mac-messenger/issues?utf8=%E2%9C%93&q=retina

**Comment by dangh** [comment]
After look around messenger source code, I found out that they use a cookie name `dpr` to calculate the pixel ratio. You can enter `require('PixelRatioConst')` in dev tools console and see.

I tried to persist the cookie in electron but haven't success, so I end up alternating cookie header of all GET requests before send to messenger.com

I have added a pull request here #172

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
