### ISSUE TITLE
Does not switch between dark/light modes without restart

### ISSUE THREAD

**Issue by stackptr** [sindresorhus/caprine#1091]
It's unclear to me if this is as intended (i.e., not implemented) or if I am experiencing a bug.

Reading this [guide](https://electronjs.org/docs/tutorial/mojave-dark-mode-guide) on implementing dark mode in Electron, it seems like the check on the current "mode" is via `api.systemPreferences.isDarkMode` which I see in `source/browser.ts: setDarkMode()`. Yet that guide also mentions the `AppleInterfaceThemeChangedNotification` which I cannot grep for.

I can work on adding this if it is indeed missing but I wanted to check here first

Version: `2.38.0 (2.38.0.1617)`

**Comment by stackptr** [comment]
The issue I'm experiencing around the "Follow system appearance" option is referenced but not elaborated on in these other issues: #1010 #1046

**Comment by iandrewt** [comment]
Supposedly this requires electron 7.0.0 to fix properly (at least in Catalina), or an Info.plist file with `NSRequiresAquaSystemAppearance`.

Electron 7 isn't out yet (it's in beta), so we might need to wait for that before this can be fixed. According to [Electron's release timeline](https://electronjs.org/docs/tutorial/electron-timelines), that should be October 22nd.
