### ISSUE TITLE
MacOS Mojave: caprine, doesn't prompt need Microphone Access

### ISSUE THREAD

**Issue by pheiduck** [sindresorhus/caprine#1093]
Caprine, has no Access to the Microphone

**Comment by pheiduck** [comment]
And has no access to camera
<img width="485" alt="Bildschirmfoto 2019-09-29 um 13 24 41" src="https://user-images.githubusercontent.com/47042125/65831686-deba6f80-e2bc-11e9-9e9d-c2523790e60c.png">

**Comment by effektsvk** [comment]
This might be macOS issue. I had this same problem with Discord. Try resetting PRAM, I think it will help. Also, you can try to downgrade to older version where you are sure it works, then after updating, permissions should stay there.

**Comment by shirazd** [comment]
same issue. after downgrading to 2.39.0 to overcome the blank popup, now the popup is as follows:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/464638/73607563-6286b000-456c-11ea-9bf0-45d8de5a3674.png">

despite the fact that I have granted Chrome both microphone and camera access, and Caprine itself doesn't show up as as requesting access.

**Comment by whitecrownclown** [comment]
This seems to be related https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos

> This user consent was not required until macOS 10.14 Mojave, so this method will always return true if your system is running 10.13 High Sierra or lower.

**Comment by pheiduck** [comment]
hm, on the newest version the "Call Windows" is white 
![Video_Call_0](https://user-images.githubusercontent.com/47042125/73611655-3f97e280-45e4-11ea-9c8a-6aaa04ce6545.jpg)

**Comment by shirazd** [comment]
pheiduck, the white screen on any version after 2.39.0 is a separately-ticketed open issue
