### ISSUE TITLE
Option to keep menu open after click

### ISSUE THREAD

**Issue by AndyL964** [sindresorhus/caprine#1099]
Great for first time users, and doesn't make keyboard shortcuts as much of a necessity to learn.

**Comment by sindresorhus** [comment]
What menu?

**Comment by AndyL964** [comment]
> 
> 
> What menu?

The options in the menu (specifically Caprine settings). Closes every time you click on something, so it's super tedious to set up for first time or when changing stuff in bulk.

**Comment by dusansimic** [comment]
That doesn't seem like expected settings from menu bar options. It's expected from menu bar in any in any application to be closed after you click on some option. I'll close this now.
