### ISSUE TITLE
Linux: Javascript Error

### ISSUE THREAD

**Issue by battlemidget** [sindresorhus/caprine#11]
I am starting to look into what is needed to make this work flawlessly on Linux, right now the app works using the dev commands, one thing that is popping up is this error:

```
Uncaught Exception:
TypeError: Cannot read property 'setBadge' of undefined
    at updateBadge (/home/adam/Projects/caprine/index.js:22:10)
    at BrowserWindow.<anonymous> (/home/adam/Projects/caprine/index.js:52:3)
    at emitTwo (events.js:87:13)
    at BrowserWindow.emit (events.js:172:7)
```

I'm going to see if I can fix some of those todo items in the other bug as well.

Heres a screenshot for anyone curious what it looks like on Ubuntu running KDE

![image](https://cloud.githubusercontent.com/assets/51892/9977997/baac9cf8-5eea-11e5-8930-924e35790674.png)

**Comment by sindresorhus** [comment]
Cool :)

Yup, seems I need to put [this](https://github.com/sindresorhus/caprine/blob/5f351dec8a8eb0648076c7dfe4cb209a68d904f5/index.js#L22) into an if statement. On OS X we use the dock badge to show a count of notifications? Is there anything similar for Linux?

**Comment by battlemidget** [comment]
Just from my limited reading for electron I think https://github.com/atom/electron/blob/master/docs/api/tray.md may be what you want for cross platform tray indication. Still looking into it and will patch the code to see if I can make it work

**Comment by 3nit** [comment]
Same error (`Cannot read property 'setBadge' of undefined`) happens on Windows too.
