### ISSUE TITLE
Missing menu on Windows 10

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#110]
That's what the top of the window looks like on Windows 10:
![messenger-screenshot](https://cloud.githubusercontent.com/assets/1758366/15801233/df32db4e-2a8e-11e6-88d9-0ef1de2eced0.png)
The menu is missing.

**Comment by danhp** [comment]
You can hit the `alt` key and it'll pop up. This is a common behavior for the platform.

**Comment by mgol** [comment]
I'm aware of Alt showing the hidden menu in some system apps but it's mostly a hidden feature for advanced users, it seems weird to not have a user-visible way to get to even the app's basic settings, e.g. just to enable notifications or disable sounds.
