### ISSUE TITLE
Minimum width recently increased

### ISSUE THREAD

**Issue by kingmustard** [sindresorhus/caprine#1107]
As of around a week ago, the minimum width for the window, whilst still keeping the chat names visible, is now 903px.

It used to be much smaller, I'm guessing at around 700px.

![eb_minwidth1](https://user-images.githubusercontent.com/1947304/66703480-fd802380-ed0a-11e9-84aa-7d141bf58391.png)

**Comment by riconaranjo** [comment]
I too did not like encountering this issue

**Comment by zebapy** [comment]
Yes this is a nuisance. Perhaps a custom width setting or a toggle for 'start at wider width'? Or just start at it..

**Comment by whitecrownclown** [comment]
This is the same behaviour that you can see on [messenger](https://www.messenger.com).

**Comment by kingmustard** [comment]
The recently released v2.40 hasn't solved it, unfortunately.
