### ISSUE TITLE
Big like emoji not displayed

### ISSUE THREAD

**Issue by huylv** [sindresorhus/caprine#1108]
The big like icon (when you press and hold 'like' button) is not shown in Caprine:
![image](https://user-images.githubusercontent.com/2832672/66709652-fd167580-ed68-11e9-9983-803ce5b85edb.png)
This is how it should be on messenger.com:
![image](https://user-images.githubusercontent.com/2832672/66709640-d2c4b800-ed68-11e9-8d83-ac1fef8ef69d.png)

Affected versions: Caprine 2.38, 2.39
OS: macOS 10.13.6

**Comment by panda7789** [comment]
It's only on Like emoji. When you change emoji to something different it shows normally.

**Comment by huylv** [comment]
Yes, regular emojis show just fine. But this issue is about the default Like emoji.

**Comment by CvX** [comment]
Fixed in 139d06d947d8bbe63cc7f611da62d20af4c5764f
