### ISSUE TITLE
[OS X] Add an option for a Dock bounce animation

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#111]
Some apps are able to bounce the Dock icon when a notification appears, see:
![dock-bounce](https://cloud.githubusercontent.com/assets/1758366/15806338/8260e1e6-2b41-11e6-89a6-d1fa972d2be8.gif)
It'd be cool if Caprine was able to do it as well.

For me it's a notification that slightly catches my attention but not that much as banners so it's easier for me to skip it if I don't have time for it at the moment.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/caprine/pull/169.
