### ISSUE TITLE
Custom CSS doesn't work no matter the changes

### ISSUE THREAD

**Issue by jonny333** [sindresorhus/caprine#1110]
Hello, 

I've recently discovered your app (being using the messenger for desktop but  since the new design update of fb it's butchered) however whatever I'd like to have my dark mode a little more darker, but whatever I change on the css file in advanced options the appearence stays the same could you please tell me if it's on the app or maybe I'm doing something wrong and which section is to what

**Comment by jonny333** [comment]
That's the changes that I made so far I suppose those are for dark background and changes of the blue color 
![Screenshot 2019-10-13 at 19 41 28](https://user-images.githubusercontent.com/48863056/66718902-c9336280-edf1-11e9-8361-e83f761260a8.png)

**Comment by dusansimic** [comment]
That's correct. But `--container-dark-color` changes the background color of the login screen, not the app itself. To change the background color of the app, you'll have to change `--container-color` variable. The `--blue` variable changes the accents that have the blue messenger color. Let me know if this helped you!
