### ISSUE TITLE
CMD+SHIFT+Z shortcut problem

### ISSUE THREAD

**Issue by TigerCat-hu** [sindresorhus/caprine#1111]
Hi,
In another application I write a "Redo" shortcut (⇧⌘Z), however, Caprine will be active and in focus. Very annoying bug! Please fix it!
Thanks!
:-)
Krisztian

**Comment by TigerCat-hu** [comment]
This is only a problem with the Hungarian keyboard layout. How do I turn this off?

<img width="583" alt="Caprine_toggle_main_window" src="https://user-images.githubusercontent.com/33827733/66763802-ca739680-eea8-11e9-87fc-1e672c75460d.png">

![Hungarian_layout_mac](https://user-images.githubusercontent.com/33827733/66763926-06a6f700-eea9-11e9-8ee7-07b1fe6e1977.png)

**Comment by TigerCat-hu** [comment]
Please help me, so I can't work!
Thank You!
:-)

**Comment by TigerCat-hu** [comment]
Any idea how to change this shortcut?

**Comment by TigerCat-hu** [comment]
Please-please add modification to the "Toggle main window" hotkey!
Thanks!

**Comment by dusansimic** [comment]
I can't reproduce this issue
