### ISSUE TITLE
No profil picture/Blur profil picture

### ISSUE THREAD

**Issue by 0wlyW00d** [sindresorhus/caprine#1112]
Hi,

Since few days the profile pictures on each conversation are blurry, and the only way to see which conversation is with who is to select it and to look on the right panel.

This happened since the last Caprine's update.

Cheers,

**Comment by CvX** [comment]
Looks like you've accidentally enabled "Hide Names and Avatars" (<kbd>Command/Control</kbd> <kbd>Shift</kbd> <kbd>n</kbd>)

Maybe we should add a confirmation prompt when using the keyboard shortcut. @alexandrepa, what do you think? 🙂 (This is a second report of an accidental privacy mode activation)

**Comment by alexandrepa** [comment]
> Looks like you've accidentally enabled "Hide Names and Avatars" (Command/Control Shift n)
> 
> Maybe we should add a confirmation prompt when using the keyboard shortcut. @alexandrepa, what do you think? 🙂 (This is a second report of an accidental privacy mode activation)

That's a good idea, I'll give it a try !
