### ISSUE TITLE
About Caprine page is blank via .deb

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1115]
When I click on Help > About Caprine, the window that pops up looks like:
![image](https://user-images.githubusercontent.com/17033543/66759967-30432c80-ee6f-11e9-9490-65ae5a8b17e4.png)
Previously, this page showed the version number, copyright info, etc.

Caprine v2.39.0
Linux Mint 19.2, Cinnamon 4.2.4, Kernel 5.0.0-29

**Comment by mquevill** [comment]
Still exists with v2.40.0.

**Comment by vanushwashere** [comment]
also exists on v2.41.0

**Comment by mquevill** [comment]
I'm guessing this bug was introduced in `aboutMenuItem when [electron-util](https://github.com/sindresorhus/electron-util) was updated from 0.11.0 to 0.12.1, since that was the breaking change. Seems like it is related to [electron-util #16](https://github.com/sindresorhus/electron-util/pull/16), but I haven't been able to track down the cause of the issue.

**Comment by dusansimic** [comment]
Closing since it's fixed #1674
