### ISSUE TITLE
Option for chat window staying always on top

### ISSUE THREAD

**Issue by veniversum** [sindresorhus/caprine#112]
Menu or tray menu option to keep the chat windows above others would be nice.

**Comment by mckennajones** [comment]
I tried messing around with the 'alwaysOnTop' option of the BrowserWindow class but it was not behaving as I would expect. For example I tried adding `alwaysOnTop: true` to the creating of the BrowserWindow in the 'createMainWindow' function in index.js, however it had no effect. I also tried adding `win.setAlwaysOnTop(true);` to the end of the same function but it had no effect...

@sindresorhus Any thoughts about this?

**Comment by veniversum** [comment]
@mckennajones Sorry I've actually added this feature on a personal fork and have forgotten to push upstream. Just opened a pull request now.

**Comment by mckennajones** [comment]
Awesome. I actually just tested out your work and it works like a charm. Good work!
