### ISSUE TITLE
Battery life

### ISSUE THREAD

**Issue by drakitsu** [sindresorhus/caprine#1120]
Hello,
I have some trouble about battery life.
On my laptop, when Caprin is on my battery life is divided by 3.
Can you fix it?
Thanks

**Comment by thesamesam** [comment]
I think this might be because hardware acceleration is enabled by default which uses the discrete GPU regardless of if on power/battery.

**Comment by yllekz** [comment]
Also noticing Caprine tanking my Surface's battery life. Is there a workaround?
