### ISSUE TITLE
MSI package 

### ISSUE THREAD

**Issue by geosone** [sindresorhus/caprine#1121]
could you pleas also create msi packages.
this way a mass deploy if thsi software would be easyser.

the electron-builder already supports msi

**Comment by sindresorhus** [comment]
I tried the `msi` build target and got this error:

> Error: Cannot find suitable Parallels Desktop virtual machine (Windows 10 is required)
    at getWindowsVm (/Users/sindresorhus/dev/oss/caprine/node_modules/app-builder-lib/src/vm/vm.ts:27:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)  stackTrace=

Caprine is built on Travis CI and we can't install Parallels there, so doesn't look like this is feasible. I'm not interested in having to manually build it locally for each version.

**Comment by sindresorhus** [comment]
You could probably mass-deploy the NSIS installer too: https://community.spiceworks.com/topic/310117-best-way-to-mass-deploy-an-installer-created-with-nsis

**Comment by geosone** [comment]
i tried the nsis install but it just breaks when installed as system user.

**Comment by geosone** [comment]
could you try build the nsis with the in the electron doku specified config.

https://www.electron.build/configuration/nsis

"Is it possible to made single installer that will allow configuring user/machine installation?"

Yes, you need to switch to assisted installer (not default one-click).

package.json
"build": {
  "nsis": {
    "oneClick": false
  }
}
