### ISSUE TITLE
White line in thread replies when using default dark mode in Windows 

### ISSUE THREAD

**Issue by KTsarlz** [sindresorhus/caprine#1127]
Running the laetst version of Caprine. 2.39.0
Windows 10 LTSC
Here's the screenshot, as there are no error logs

![Screenshot_1](https://user-images.githubusercontent.com/9140507/67156422-d5b73e00-f350-11e9-990d-6f9d6ee8683b.png)

**Comment by panda7789** [comment]
Solved in #1126 😄

**Comment by KTsarlz** [comment]
@panda7789 which is still not released right?

**Comment by panda7789** [comment]
@KTsarlz Not yet

**Comment by misterpyrrhuloxia** [comment]
> Solved in #1126 😄

@panda7789, does that apply to the Mac Caprine build too? And do you have any idea when that build will be released?

**Comment by panda7789** [comment]
@misterpyrrhuloxia It is already released in Caprine 2.40.0. Please download the latest version and try again. This fix should be also for Mac.

**Comment by misterpyrrhuloxia** [comment]
Thanks!!
