### ISSUE TITLE
Preferences in Gnome 3

### ISSUE THREAD

**Issue by davidcortesortuno** [sindresorhus/caprine#113]
I can't find the `Preferences` option in Gnome 3:

![screenshot from 2016-07-20 21-41-38](https://cloud.githubusercontent.com/assets/12200541/17002423/1d1104d8-4ec3-11e6-87af-c8e3ef4dc3af.png)

Is it in  different place? The tray icon only shows me the `Toggle` option.

**Comment by sindresorhus** [comment]
Preferences (and all other menu items) are in the app menu, not in the tray menu.

**Comment by forivall** [comment]
Press the "alt" key for the menu to appear inside the app's window. Otherwise, electron needs to support the gnome 3 topbar application menu.
