### ISSUE TITLE
about is empty

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#1131]
this is ubuntu lts based distro:
https://framapic.org/vC6bbXoqAmi5/Me7FBxQco3Ar.png

**Comment by RDKRACZ** [comment]
Still:
![image](https://user-images.githubusercontent.com/43277609/114207440-ab01e080-995c-11eb-9dde-3c57384a5ec7.png)

**Comment by dusansimic** [comment]
Duplicate of #1435
