### ISSUE TITLE
Adopt Messenger's new rounded chat design

### ISSUE THREAD

**Issue by 1nikolas** [sindresorhus/caprine#1133]
It would be nice to implement this design. [This is what I'm talking about](https://monosnap.com/file/AWxYuIC1hdPzQYjiDaiZtGLQr0gMiB)
Thanks in advance

---

Caprine 2.40.0
Electron 6.0.11
darwin 18.6.0
Locale: en-GB

**Comment by whitecrownclown** [comment]
@1nikolas I'm pretty sure this is the new messenger style, you might be on the old one still. So there's nothing to do here, except wait for messenger design changes to roll out for everyone.

**Comment by 1nikolas** [comment]
@whitecrownclown I know that. I have the new design on Caprine but the chat shape is rectangular not rounded. Anyway not a major problem but it would be nice to have that

**Comment by dusansimic** [comment]
The new design is being rolled out now. I'll close this.
