### ISSUE TITLE
Caprine is not brought back on X11 session restore

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#1134]
This is regarding Linux compatibility. Apparently Caprine is not following the standard session protocol on X. Can this be looked into? 

X11 documentation: https://www.x.org/releases/X11R7.7/doc/libSM/xsmp.html

This would allow Linux users (on X) to save Caprine with session and not launch manually after each boot.
Thank You

**Comment by sindresorhus** [comment]
This is probably better reported on https://github.com/electron/electron.

**Comment by alekksander** [comment]
https://github.com/electron/electron/issues/20822 this is a proper electron issue report
