### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by khoaho** [sindresorhus/caprine#114]
Hi,

I ran "npm run build:windows" to build the distributed package but getting the following errors:

17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:windows"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error caprine@1.4.1 build:windows: `electron-packager . --overwrite --asar --out=dist --ignore='^media$' --prune --platform=win32 --arch=ia32 --icon=static/Icon.ico --version-string.ProductName=$npm_package_productName --app-version=$npm_package_version && cd dist/Caprine-win32-ia32 && zip -ryq9 ../Caprine-windows-${npm_package_version}.zip *`
22 error Exit status 1
23 error Failed at the caprine@1.4.1 build:windows script 'electron-packager . --overwrite --asar --out=dist --ignore='^media$' --prune --platform=win32 --arch=ia32 --icon=static/Icon.ico --version-string.ProductName=$npm_package_productName --app-version=$npm_package_version && cd dist/Caprine-win32-ia32 && zip -ryq9 ../Caprine-windows-${npm_package_version}.zip *'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the caprine package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . --overwrite --asar --out=dist --ignore='^media$' --prune --platform=win32 --arch=ia32 --icon=static/Icon.ico --version-string.ProductName=$npm_package_productName --app-version=$npm_package_version && cd dist/Caprine-win32-ia32 && zip -ryq9 ../Caprine-windows-${npm_package_version}.zip *
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs caprine
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls caprine
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sindresorhus** [comment]
You can't build on Windows. I'm working on switching over to `electron-builder` which will work on Windows. For now, just use the binaries.
