### ISSUE TITLE
Menu items should be disabled after window is hidden

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#1140]
When I hide the window (but keep the app running) on macOS by pressing ⌘W or the red traffic light button, the app remains the active app, so the menu items can be accessed. If I select any of the menu items, the app gets visible again, the action will be performed.

This sounds cool, but unfortunately it is very annoying. In real life I close the window, then I press the back gesture on my touchpad (hoping that the topmost visible app will receive the event), but Caprine gets the event and suddenly reappears.

I think either app must be deactivated (not be the focued app) or menu items should be disabled when it's window is hidden.

**Comment by drewclauson** [comment]
From my experience, this is how Mac operates by default.  Try it with TextEdit - ⌘W or the red traffic light button on the last window open keep the app running, but the window closes and the app continues to remain the active app so it will receive any commands.  

In a situation like this, I use ⌘H, which hides the current app completely and then the next app should receive actions.

**Comment by gklka** [comment]
Yes, but to remain at the TextEdit analogy: if I close the TextEdit window, then I won't be able to select "Bold" menu item, and it will definitely not reopen the window.

**Comment by drewclauson** [comment]
Oh, right.  _The menu items!_ 🤦‍♂   Sorry - makes sense, yes, I'd agree that seems not typical for an app to function like this.

+1 on this from me :-)
