### ISSUE TITLE
Bug: Caprine doesn't switch to dark mode when OS dark mode setting changes

### ISSUE THREAD

**Issue by aterenin** [sindresorhus/caprine#1152]
Steps to reproduce.

1. Ensure OS is in light mode.
2. Open Caprine.
3. Switch OS to dark mode using either System Preferences or a helper app.

All Windows are now in dark mode, except Caprine, which is still in light mode and needs to be restarted for styles to update.

The following Atom extension may help in figuring out how Electron is notified when the system's dark node setting changes: https://github.com/paysonwallach/mojave-dark-mode/blob/bfa3a6c8eaa75cd5f80798c7ebf8cc6856662943/lib/main.ts#L73

I'd make a PR myself, but not quite familiar enough with Electron to figure things out.

**Comment by jyoo980** [comment]
I can take a stab at this 🤔

**Comment by jyoo980** [comment]
@aterenin 

Which OS and version of Caprine are you on? I have the following settings

* OS: macOS 10.14.6
* Caprine: 2.40.0

and it looks like it's respecting the system settings when I change from dark->light and vice versa.

**Comment by aterenin** [comment]
10.15.1
2.40.0

No auto switch when Caprine is already opened.

I also had a Google Photos desktop app stop working on OS update, so I simply rebuilt my own with dark mode support here: https://github.com/aterenin/Photos/blob/master/main.js 

The relevant Electron API is `systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', ..)` which appears not to be used anywhere in Caprine.

**Comment by jyoo980** [comment]
@aterenin 

I'll try updating my macOS and seeing if the problem rears its head. Thanks!

**Comment by jyoo980** [comment]
@aterenin 

Did some digging, and it looks like this issue only persists on macOS 10.15 + (aka. Catalina). I think there are some other changes that need to be made first before I can work on this issue

See #1091 for more details 😄

**Comment by aterenin** [comment]
Makes sense. Is there currently a built-in Caprine function that can be called to change the theme? Maybe fixing this is as simple as adding the line above in whatever code is called when the window is opened?

**Comment by aterenin** [comment]
I could also take a stab at fixing this, but the code looked just a bit more fearsome than something I could just dive into.

**Comment by whitecrownclown** [comment]
@aterenin There is `setDarkMode`, however that would not fix it since when you toggle darkMode `systemPreferences.isDarkMode()` returns the same value. At least that's what i'm seeing on 10.15. I think we need electron v7 for this.

**Comment by aterenin** [comment]
> @aterenin There is `setDarkMode`, however that would not fix it since when you toggle darkMode `systemPreferences.isDarkMode()` returns the same value. At least that's what i'm seeing on 10.15. I think we need electron v7 for this.

That makes sense. The repo I linked uses Electron v7. If there's an Electron bug that prevents this until the upgrade, then we'll need to wait for that.

**Comment by aterenin** [comment]
Fixed in latest version.
