### ISSUE TITLE
openExternalSync is deprecated (and removed in Electron 7)

### ISSUE THREAD

**Issue by AidanGG** [sindresorhus/caprine#1153]
https://github.com/sindresorhus/caprine/blob/d27f5af0be14baeb02a602736e8ada44d54a8e07/source/index.ts#L456-L460
and
https://github.com/sindresorhus/caprine/blob/d27f5af0be14baeb02a602736e8ada44d54a8e07/source/index.ts#L500-L503

This function is not available on Electron 7 (which will presumably be supported in the future, and is the only way to use Caprine on Arch Linux right now). I'm not asking to switch to Electron 7, but could we perhaps switch to using the asynchronous `shell.openExternal` instead, which returns `Promise<void>` since the Boolean result of `openExternalSync` is unused? This should restore link opening on Arch Linux.

**Comment by Saboteur777** [comment]
:+1:

**Comment by sindresorhus** [comment]
Should be fixed by https://github.com/sindresorhus/caprine/releases/tag/v2.41.0
