### ISSUE TITLE
Stuck on the loading wheel

### ISSUE THREAD

**Issue by freewill404** [sindresorhus/caprine#1154]
Tried re-installing it from scratch multiple times, experiencing the same issue: chat windows are empty and it's loading (the blue loading gif) endlessly. All other functions seem to work though, I just don't see any previous messages. Am able to send new messages, but when I move away from the screen and click the chat again, it's back to the loading gif.

<img width="752" alt="prob" src="https://user-images.githubusercontent.com/42697129/67848119-57069180-fb04-11e9-81b9-d518a5a634df.png">

MacOS Catalina 10.15.1
Caprine Version 2.40.0 (2.40.0.1662)

**Comment by Constant-ine** [comment]
Same thing, latest version on windows 10.

**Comment by DenyDarko** [comment]
It's not Caprine, It's messenger.com issue.

Since yesterday

**Comment by ShaneOH** [comment]
This is happening to me too. I can't load any previous messages being stuck on the loading wheel, but if I send new messages I can see the conversation from then on (but it's still buggy -- won't scroll down automatically with incoming messages for example). 

I also have my FB account deactivated but haven't had any issues with that prior to this

**Comment by kiernann** [comment]
This definitely has to do with Facebook's handling of Messenger accounts without a full on Facebook account (i.e., not a Caprine issue). I too deleted my Facebook account and have been experiencing this issue on Caprine and the www.messenger.com desktop client.

**Comment by shawnburke** [comment]
+1 yeah I have a disabled FB account, if I try to log into messenger.com I get:

     You Can't Do That Right Now
     This is because you tried to do something too many times. Please try again later.

This seems pretty lame.  I have a friend who works on messenger, I'll ask him about it.

**Comment by ngocphamm** [comment]
Yeah had to login to FB to fix this (deactivated account). If this is true they are gonna require an active FB account onward, pretty dick move from FB I would say.

**Comment by snoozi** [comment]
I'm also stuck with this issue. Fairly sure I'm deactivated, but it's been years. It takes so long to load any conversation. I tried reinstalling previous versions, clearing app cache + any traces, etc. It ALSO is clearing any prior conversations I attempt to have, so the message history fails to load as if I deleted a chat window when I clearly did not.

**Comment by shawnburke** [comment]
> Yeah had to login to FB to fix this (deactivated account). 

Yeah the good news is if you reactivate then deactivate your facebook account it starts working again.

The bad news is that this doesn't survive a re-login from Caprine.

**Comment by freewill404** [comment]
> The bad news is that this doesn't survive a re-login from Caprine.

Not only a re-login, but even a close/open.

**Comment by shawnburke** [comment]
It looks like this may have resolved?

**Comment by rgcv** [comment]
> It looks like this may have resolved?

I think I can second that motion. Seems to be working again.

**Comment by snoozi** [comment]
Yeah, it's working fine for me after deactivating again :)
