### ISSUE TITLE
Older versions upgrading to 2.40.0 may run into a config issue with the 'vibrancy' value

### ISSUE THREAD

**Issue by FlaminSarge** [sindresorhus/caprine#1161]
OS: Win10
Steps to reproduce:

1. Install 2.10.0 and run the app.
2. Install 2.40.0 and run the app; an error occurs due to the 'vibrancy' config field.

I recently upgraded from 2.10.0 to 2.40.0. 'vibrancy' was a boolean 'false' in the config under 2.10.0 and is now a string. config.ts complains about this and the app doesn't open, and I had to edit the config.json file manually to set the value to "none" to get it to work.

Seems like migration logic in config.ts can't handle boolean values here, and while it's not feasible to add handling for every past config version, handling at least the 2.x range might be worthwhile.

**Comment by dougestey** [comment]
Same issue here.

Worse, after this happens, uninstalling 2.10.0 and then attempting to install 2.40.0 results in a hanging installer.

![Untitled](https://user-images.githubusercontent.com/680366/68427136-f15b7a80-017f-11ea-8d82-ae15a8665130.png)

**Comment by dougestey** [comment]
Deleting the `vibrancy` key in `config.ts` was my only way around this, and required unpacking/repacking `app.asar`.

**Comment by dalbitresb12** [comment]
Same problem here.

Had to delete `vibrancy` key in `config.ts` under `app.asar/source/`, and in `config.js` and `config.d.ts` under `app.asar/dist-js/`. After that, Caprine worked fine.

I just used 7Zip with a plugin to open asar files and replaced the files in the `app.asar` file. It is [this](http://www.tc4shell.com/en/7zip/asar/) one.

**Comment by FlaminSarge** [comment]
To the above, this can be fixed by editing 'config.json' wherever it is on your system (I'll update this comment with the path mine was in on Win10), rather than editing app.asar and config.ts.

**Comment by sindresorhus** [comment]
// @janosorcsik @whitecrownclown

**Comment by janosorcsik** [comment]
@sindresorhus In the _conf_ module you always validate the schema. But the old and the new schema differ.
https://github.com/sindresorhus/conf/blob/master/index.js#L121

**Comment by whitecrownclown** [comment]
@sindresorhus , @janosorcsik 

I was thinking of using [migrations](https://github.com/sindresorhus/conf#migrations) and handling the `type` changes there so people don't have to manually edit their config files. What do you think?   It seems we can't use it until [this](https://github.com/sindresorhus/conf/issues/92) is fixed.

**Comment by triangulum** [comment]
Still broken in 2020

**Comment by FlaminSarge** [comment]
Sorry for the delay, found the file:

**WORKAROUND**
Windows: Open `%APPDATA%/Caprine/config.json` (`C:\Users\username\AppData\Roaming\Caprine\config.json`) and edit the `"vibrancy"` value from `false` to `"none"` (with quotation marks as shown).
