### ISSUE TITLE
No scroll capabilities

### ISSUE THREAD

**Issue by schaiba** [sindresorhus/caprine#1162]
There was an update to Caprine (I think -- using Ubuntu 18.04 LTS), and I was prompted to restart. After that, I don't have a scroll bar anymore, nor can I use the arrow keys or the mouse wheel to scroll. 

---

Caprine 2.40.0
Electron 6.0.11
linux 5.0.0-32-generic
Locale: en-US

**Comment by dusansimic** [comment]
Is this the scroll bar in the message box?
