### ISSUE TITLE
New facebook sl

### ISSUE THREAD

**Issue by zolyyy** [sindresorhus/caprine#1165]
Emoji style->messenger
![image](https://user-images.githubusercontent.com/5923144/68305023-38c20800-00a7-11ea-98fa-077b01f36c43.png)

**Comment by sindresorhus** [comment]
Please explain in words what the problem is and how to reproduce.

**Comment by dusansimic** [comment]
Issue is stale so I'll close it. If there is still a problem, ping me in the comment with a detailed explanation of the problem and how to reproduce it.
