### ISSUE TITLE
Can't open links

### ISSUE THREAD

**Issue by D54** [sindresorhus/caprine#1166]
Every time I'd like to open a link, I get the following error in a popup window:
(text is not selectable there, that's why I pasted as a screenshot)

![image](https://user-images.githubusercontent.com/6825569/68305396-ea613900-00a7-11ea-8599-2dc6e5307b09.png)

Caprine 2.40.0
Electron 7.0.1

**Comment by sindresorhus** [comment]
This will be fixed by #1157
