### ISSUE TITLE
Colors does not match on Windows dark mode.

### ISSUE THREAD

**Issue by ComputerPark** [sindresorhus/caprine#1171]
It simply does not look sleek and unified. (Main colors are different from upper menu etc...)

Also, any plans for supporting acrylic design on windows 10? It will be great to do so...

Screenshot: 

![image](https://user-images.githubusercontent.com/30792695/68384292-abf87680-019a-11ea-925e-f73f94f9dcc8.png)

**Comment by sindresorhus** [comment]
Duplicate of #935

**Comment by ComputerPark** [comment]
What about the colors?

**Comment by CvX** [comment]
That's #652

**Comment by ComputerPark** [comment]
Oh, okay. Thanks!
