### ISSUE TITLE
Bug on background color of "replied to" 

### ISSUE THREAD

**Issue by esfox** [sindresorhus/caprine#1174]
The background of the "replied to" text is not dark. See screenshot below.
---
![image](https://user-images.githubusercontent.com/18418806/68541002-0c72f800-03d5-11ea-9775-d2bffabb43a1.png)

Caprine 2.34.0
Electron 5.0.6
win32 10.0.18362
Locale: ko

**Comment by CvX** [comment]
This has been fixed in #1126. Please update to the latest version of the app. 🙂
