### ISSUE TITLE
using this in Web Broser and disable imput so it can be used like Messanger wiever

### ISSUE THREAD

**Issue by veso266** [sindresorhus/caprine#1175]
Hi there I realy like Caprine because it looks like official facebook messanger and best of all has all emoji support, picture preview and it shows people likes on your messages

So I was wondering if it is possible to run this in web browser as a website and disable chat imput so you could for instance show your conversation to someone without being worried that they will ruining it by writing stupid things

If there is any app that would do that I would love to know its name (specialy that it supported EMOJIs and peoples reactions like Facebook messanger does)

Thanks for Anwsering and Best Regards

**Comment by sindresorhus** [comment]
No, you can not run Caprine in a web browser. However, you could probably modify Caprine to disable input, but that's outside the scope of the project.

**Comment by veso266** [comment]
Thanks
You maybe know how does this hook into Messanger API, because I heard that your account can get locked if you use unofficial fb apis  like this one: https://github.com/Schmavery/facebook-chat-api ?

as this is a web app talking messnging (only need that as it has emojis and reactions) part of it out would probably work
