### ISSUE TITLE
Dark mode toggle is not working on Linux

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#1176]
![image](https://user-images.githubusercontent.com/24995381/68617947-bc358c00-04e1-11ea-8960-cd1982a6386c.png)
As you can see there is no dark mode but option is checked.
Toggling option have no impact.

OS: KDE neon 5.17
Kernel: x86_64 Linux 5.0.0-32-generic
DE: KDE 5.63.0 / Plasma 5.17.2
Caprine version: v2.41.0 Installed via .deb package

**Comment by yxinolija** [comment]
![Caprine_36w1vciyX1](https://user-images.githubusercontent.com/57045983/68622370-483fb780-04d2-11ea-81d4-4b1ad1ac67e4.png)

I second this on Windows 10 64-bit

Caprine v2.41.0

**Comment by aude** [comment]
Dark mode does not work for me in v2.41.0 :x: 

Dark mode works for me in v2.40.0 :heavy_check_mark: Downgraded to check.

So dark mode has stopped working between v2.40.0 and v2.41.0.

OS: Arch Linux
Caprine version: v2.41.0 [Arch Linux package](https://www.archlinux.org/packages/community/any/caprine/)

**Comment by cptpcrd** [comment]
This appears to have been broken in the changes to `source/browser.ts` in commit 2c1a3c95a40d1fbb4b3be8a5058269278d1e4e67. Specifically, reverting the change to line 275 of that file (adding back `is.macos &&` to the condition) should fix it. Dark mode is still there and it still works; that commit just made it impossible to enable unless you are on macOS.

For a temporary fix, close Caprine, open `~/.config/Caprine/config.json` (on Linux) or `%APPDATA%/Caprine/config.json` (on Windows), and change `"followSystemAppearance": true` to `"followSystemAppearance": false`.

**Comment by aude** [comment]
Great, you've found it.

The `Follow System Appearance` menu item is not visible on Windows and Linux: https://github.com/sindresorhus/caprine/blob/74416e6c299d3034196d3e48ec7817f41678621c/source/menu.ts#L351

That option is being set to `true` on my Linux at least, probably because it was unset.

So then the `darkMode` setting is ignored:
https://github.com/sindresorhus/caprine/blob/74416e6c299d3034196d3e48ec7817f41678621c/source/browser.ts#L275-L279

Might need to add back `is.macos &&`, like @cptpcrd is saying.

**Comment by CvX** [comment]
Okay, I've released [2.41.1](https://github.com/sindresorhus/caprine/releases/tag/v2.41.1) that fixes this issue. 🙂

**Comment by John15321** [comment]
@CvX Hey, Its not working again. Version 2.51.2 (both Manjaro Official Repository and Snap) 😥
The reason I want to use Caprine is that its more responsive than their damn messenger.com website. But when I cant have a dark mode Im not going to use it because I like to have my eyes not burnet
