### ISSUE TITLE
Chat does not auto-scroll when a new message is received

### ISSUE THREAD

**Issue by Daniel1618033988749** [sindresorhus/caprine#1177]
1. Open chat window and scroll to very bottom

2. Receive new message

3. Window does not scroll, leaving the message entirely un-readable or it scrolls a tiny bit (but never to the very bottom) 

_Very_ annoying bug, been happening for months and months. It was also happening on Messenger For Desktop. I switched to Caprine because I hoped it would not be an issue here, but it is.

**Comment by dusansimic** [comment]
This is fixed by #1382. Update to the latest version of Caprine to get the fix.
