### ISSUE TITLE
Dark Mode stuffed up

### ISSUE THREAD

**Issue by rosoau** [sindresorhus/caprine#1179]
Ubuntu xenial, kernel 4.15.0-66 caprine 2.41
caprine 2.40 was perfect
now on this version dark mode is not different from white
it makes no difference
but caprine 2.40 was perfect; dark mode worked well on linux
here we say; don't fix what ain't broke

**Comment by TheodoreBellas** [comment]
Seconded- updated to 2.4.1 on Mint 19, `4.15.0-66-generic` and dark mode stopped working. Downgrading to the 2.4.0 deb fixed it.

**Comment by Nawor3565** [comment]
Same issue on Windows 10 Spring 2019 Update, dark mode looks the same as white mode.

**Comment by yerbestpal** [comment]
This same issue is present on the Snap when used on Opensuse. Presumably, this is the case across the board.

**Comment by ashtonx** [comment]
Same, I had some errors  recently, before when I clicked on links today it stopped working.
Links now work without erroring out though.

**Comment by CvX** [comment]
The issue is tracked in #1176.
