### ISSUE TITLE
The dark theme switch no longer works.

### ISSUE THREAD

**Issue by septicwolf818** [sindresorhus/caprine#1182]
### The dark theme has not been working for some time. 
Despite the fact that it is turned on, nothing changes. A few days ago everything was fine, the dark theme was working.
The dark theme has stopped working, in my opinion, not by updating the system. 
The function does not seem to respond to user actions.
I'm running Ubuntu 19.10 and I have installed Caprine from Ubuntu Software.

---

Caprine 2.41.0
Electron 7.1.1
linux 5.3.0-22-generic
Locale: pl

**Comment by SoptikHa2** [comment]
This works for me again in version `caprine-2.41.1-1`, probably fixed by commit 081b6ed457eeb3a676baa9189df66bf5eadc3fb4.

**Comment by CvX** [comment]
Yeah, this has been corrected in a bugfix release 2.41.1.
