### ISSUE TITLE
Error running on MacOS Catalina

### ISSUE THREAD

**Issue by reganlawton** [sindresorhus/caprine#1183]
This issue is relates to [this](https://medium.com/cacher-app/getting-your-electron-app-working-on-macos-catalina-10-15-63e53f397da2).

I'm unable to run the release versions on Catalina but if I build a new `dist` from source with the following command I can get pass the error.

```"dist": "tsc && electron-builder --macos --linux --windows --publish always",```

An example of the error can be seen below.

![Error example](https://miro.medium.com/max/840/1*q6syhoL9Z2OafEykn_8qNQ.png)

**Comment by sindresorhus** [comment]
Yes, Caprine is not yet notarized. You can open it by right-clicking the app and then select "Open" the first time.

**Comment by reganlawton** [comment]
@sindresorhus I tried that too wasn't working I could only get it working using the publish. I'm k to build from source just useful for anyone else with the issue to have a issue to reference.

**Comment by mschinis** [comment]
I get the same too downloading via the github releases. Installing via homebrew works for me 👌
