### ISSUE TITLE
App goes blank after clicking emoji button

### ISSUE THREAD

**Issue by Dokixi** [sindresorhus/caprine#1185]
(I have the app set to dark mode)
When I try to click on the emoji button in the chat window, your messenger app goes black. If I want to fix it I need to quit the app and relaunch it. But the same thing happens again when I click on the emoji button, so it is really easy to reproduce.

---

Caprine 2.41.1
Electron 7.1.1
darwin 18.7.0
Locale: nb

**Comment by amulya-b** [comment]
I'm also running into this issue starting today as well!

**Comment by yauuik** [comment]
same here, I have to close and relaunch the app each time...

**Comment by megseoh** [comment]
Same issue. Also have to quit Caprine to get back to messages.

**Comment by stevek123** [comment]
I'm not in dark mode, but I also have this issue, and the app goes white.

**Comment by Trychlik** [comment]
same for me

**Comment by Waitsnake** [comment]
Got it to work again after having the same issue with app going black after pressing the emoji button by uninstalling with [AppCleaner](https://freemacsoft.net/appcleaner/) (this will remove any settings via pref/config files you have set on caprine!). Drag and drop Caprine from applications dir into AppCleaner and remove all files suggested. Then do a clean reinstall of 2.24.1.

**Comment by yauuik** [comment]
Come on, 1 month and still no fix? This bug is really annoying and brick the app. I've to relaunch Caprine at least 30 time a day. I'm considering switching from Caprine... It's a shame because it's such a beautiful piece of software.

**Comment by Pauligrinder** [comment]
Same here. The console says as follows:
`ErrorUtils caught an error: "Tried to dispatch action UPDATE_TRAY_DATA while already dispatching TRAY_DATA...". Subsequent errors won't be logged; see https://fburl.com/debugjs.`

**Comment by pouletfou** [comment]
Same here

**Comment by chrismin13** [comment]
Same here, on Mac OS Mojave 10.14.6 on a hackintosh. Also happened on Catalina 10.15. Dark theme or light theme doesn't matter, nor changing the emojis used from Messenger's to System's or anything else.

**Comment by dapetcu21** [comment]
I tried to do a bit more debugging here, following @n-nikol98 's lead and it seems that `urlToCanvas` is what's causing the crash. I have no idea what's interacting with facebook's code, though. It's just loading an image and then calling `drawIcon`, which I tried mocking and still got the crash.

So, something about the profile pics being preloaded is probably causing this.

**Comment by dapetcu21** [comment]
Even worse, looks like no matter what image gets preloaded (I tried replacing the URL with an unrelated Imgur link), it still crashes. Very very weird. Even tried with a timer promise to simulate the synchronicity of an image load. Still not it. Apparently preloading *any* image makes the emoji bar crash. Weirdest bug I've seen in a while.
