### ISSUE TITLE
Emojis not showing in whole pop-up window when at min width

### ISSUE THREAD

**Issue by LivJes** [sindresorhus/caprine#1187]
For the last few days whenever I have the window resized to minimal width the emoji pop up window is buggy. All emojis are shown in just one column. If I make the window a bit wider it goes back to normal.

This was not an issue before even at that size of window.

![image](https://user-images.githubusercontent.com/41999662/68954252-f04fcc00-07c3-11ea-8f89-ebd6c648a1cd.png)

//edit: caprine version - 2.41.1, which I've already reinstalled, problem persists

**Comment by dusansimic** [comment]
This shouldn't occur on the latest version of Caprine. Please update it and if the issue still occurs, I'll reopen the issue.
