### ISSUE TITLE
Lack of new emojis

### ISSUE THREAD

**Issue by BetterB0y** [sindresorhus/caprine#1191]
Facebook's 4.0 emoji list.
https://emojipedia.org/facebook/4.0/

I don't know if you can add this? Or we have to wait for facebook update or somthing?

**Comment by mikigal** [comment]
I searched fbcdn with emoji URL pattern that Caprine uses (https://static.xx.fbcdn.net/images/emoji.php/v9/" + emoji_code + "27/2/32/1f600.png"). There's only 3 emoji types that are already implemented in Caprine, so we must wait for 4.0 release

**Comment by dusansimic** [comment]
We can't add Facebooks emoji 4 if it's not supported in Messenger.com. Once they do that, we'll add it.
