### ISSUE TITLE
how are you parsing Facebbok chat window?

### ISSUE THREAD

**Issue by veso266** [sindresorhus/caprine#1192]
Hi there, when reading through Caprine sources a bit I see you are parsing Facebook chat windows HTML

was wondering how did you archive that, is there any Login URL that you can login and get a token and then use this token to get the html?

lets say I would like to get a particulars person chat

so I would need to:

1. Login to facebook (maybe using a cookie or somehow) and get a token/cookie
2. Use this cookie to somehow open chat window and get the HTML data out which I could then display in a DIV

Was just wondering how are you doing this?

**Comment by borowyalan** [comment]
@veso266 
From what I see the app is using Electron's [BrowserWindow](https://electronjs.org/docs/api/browser-windowl) to display the [messenger.com](https://www.messenger.com/login/) window.
So no direct parsing / data manipulation takes place.

**Comment by borowyalan** [comment]
You didn't specify whether you need newest messages or a conversation in general. If the latter, it is possible to [download your conversations log](https://www.facebook.com/help/community/question/?id=10152460879660132) in HTML / JSON format.

**Comment by veso266** [comment]
would like to get conversation in general

I know that you can download the log, but does that log also include pictures and emojis and emoji reactions to messages or picture?

**Comment by borowyalan** [comment]
Yes, the log contains pictures, emojis and emojis reactions.

Visual example (HTML):
![image](https://user-images.githubusercontent.com/38703820/69008145-4ef18300-0947-11ea-94e9-85bf6d04f9d4.png)

**Comment by veso266** [comment]
do you have any quck instructions on what to click on because for some reason the link you gave won't open (as help is not uvailable in my language it doesn't even open it when changing it to English for some reason)

**Comment by borowyalan** [comment]
Sure, here's a direct [link to Facebook's Support Center](https://www.facebook.com/help/www/1701730696756992) with a detailed instructions how to download your data.
