### ISSUE TITLE
v2.41.1 - call is not available

### ISSUE THREAD

**Issue by pipiscrew** [sindresorhus/caprine#1193]
either call me either I press phone or videocamera, getting an empty window

![563](https://user-images.githubusercontent.com/3852762/69012854-2fbc1b00-0972-11ea-865a-f19452f4011a.png)

win7x64.

v2.39 worked well.

**Comment by pipiscrew** [comment]
Duplicate of #1189

**Comment by marekop** [comment]
Same problem with mine (Ubuntu 19.10).

**Comment by DongDuong9E** [comment]
Can reproduce on Windows 10 1903

**Comment by pipiscrew** [comment]
I downgrade to v2.39, all fine.

**Comment by jonsolberg** [comment]
> I downgrade to v2.39, all fine.

Same problem, work with downgrading. However, Caprine insist on upgrading without asking again braking video and call functionality. Any way of stopping the automatic upgrade?

**Comment by pipiscrew** [comment]
dont know, Im behind firewall, always update manually. Do the same.

**Comment by jonsolberg** [comment]
> dont know, Im behind firewall, always update manually. Do the same.

The same? Stay behind a firewall? I'm behind a firewall (which has absolutely nothing to do with Caprine's autoupdate feature).

If you are behind a firewall and have configured it to block Caprine's servers you could have provided a hint of how you did that, instead of coming with an non-helpful answer. Simple staying behind a firewall does not imply anything - you could just as well told me to unplug my network cable.

**Comment by pipiscrew** [comment]
when getting the update it getting unpacked to a tmp folder, then request again internet, then because this pathfilename is not allowed to have internet, automatically exits.

dont know, give a try and append
`127.0.0.1 caprine.com`

at C:\Windows\System32\drivers\etc\hosts file.

**Comment by pipiscrew** [comment]
moreover, the temporary installer downloaded at 
C:\Users\x\AppData\Local\caprine-updater\pending

**Comment by pipiscrew** [comment]
and now showing that get installed at :
C:\Users\x\AppData\Local\Programs\caprine

because I moved the folder v2.3.9 to another location, thats why is not getting updated!!

**Comment by jonsolberg** [comment]
Yes, I'm aware of that. Blocking github.com (which is where Caprine downloads from) is not an option.
