### ISSUE TITLE
Integrate PGP into Caprine

### ISSUE THREAD

**Issue by freewill404** [sindresorhus/caprine#1200]
Would be cool to be able to integrate PGP into Caprine and encrypt incoming/outgoing messages should both recipients have privkeys in their Caprine settings.

Something like:

https://blog.stanko.io/hacking-privacy-into-facebook-s-messenger-in-24-hours-3da239baf6c5 / https://github.com/monorkin/copenhacks-2016
https://github.com/DomWilliams0/messenger-crypt
https://github.com/tomzilla/fbpgp
https://github.com/maxisme/crypter

**Comment by sindresorhus** [comment]
This is a cool idea, unfortunately it’s not something I’m willing to maintain. Caprine is close to feature complete at this point. If you really want this, you can always fork Caprine and build it yourself.
