### ISSUE TITLE
Calls not working

### ISSUE THREAD

**Issue by robinsrk** [sindresorhus/caprine#1203]
Trying to call, but only white screen showing. And whenever try to receive incoming calls, again same problem. Both audio and video calls has same problem.

**Comment by tnilzon** [comment]
Same here, calls not working.

Caprine (caprine)  2.41.1-1
Linux Manjaro gnome 3.34

**Comment by vladbalanescu** [comment]
Same here, nothing working, simply getting a white screen on macOS Catalina. Any updates?

**Comment by rosoau** [comment]
Same here, call window blank and "about" window only shows name "caprine" nothing else
caprine 2.41.1
Linux Ubuntu 16.04

**Comment by SwiftWinds** [comment]
y'all getting something like this? 

![image](https://user-images.githubusercontent.com/12981958/70380529-aef99a80-18f1-11ea-883b-9648b8dbd1b0.png)

**Comment by tnilzon** [comment]
> y'all getting something like this?

Yes, that's what it looks like.

**Comment by CvX** [comment]
Issue tracked in #1189
