### ISSUE TITLE
Call and video call issue

### ISSUE THREAD

**Issue by ValouH** [sindresorhus/caprine#1208]
Sorry for my english
I have Caprine on Ubuntu 19.10 but call and video call don't work. I click on phone logo or video logo but nothing append, it just opening a white window.

---

Caprine 2.41.1
Electron 7.1.1
linux 5.3.0-23-generic
Locale: fr

**Comment by raphtabe** [comment]
The same issue for me.
Caprine 2.41.1
Mac OS Catalina 10.15.1 (19B88)
Local Fr
<img width="1392" alt="Capture d’écran 2019-12-04 à 14 50 46" src="https://user-images.githubusercontent.com/42490379/70147914-7feee900-16a5-11ea-873a-054ed799d6cf.png">

**Comment by gonewild8** [comment]
same for me

Caprine 2.41.1
Elementary OS 5.1 Hera
Built on Ubuntu 18.04.3 LTS
Linux 5.0.0-37-generic
GTK 3.22.30
local IT

**Comment by skewballfox** [comment]
Same for me

Caprine 2.41.1
Fedora 30
using Appimage from release page
GTK 3.24.11
Locale: US

**Comment by Siand** [comment]
Same for me

Caprine 2.41.1
Electron 7.1.1
win32 10.0.18362
Locale: en-US

**Comment by CvX** [comment]
Issue tracked in #1189
