### ISSUE TITLE
Scroll issues when switching between conversations

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#1209]
I have several conversations (with GIFs and shared links, images in them) which refuse to remain scrolled to the bottom, to see the newest message when I switch to an another conversation and back. Happens since this summer, but is more and more frequently.

**Comment by jamesaspence** [comment]
This might be related to https://github.com/sindresorhus/caprine/issues/1177

**Comment by dusansimic** [comment]
This is fixed by #1382. Update to the latest version of Caprine to get the fix.
