### ISSUE TITLE
Dekstop Notifications aren't working

### ISSUE THREAD

**Issue by Johnny2525** [sindresorhus/caprine#121]
I have notifications option enabled and still nothing.

Anyway to fix that?

I have Wndows 8.1 system and I'm using Caprine 1.5.0.

**Comment by iansinnott** [comment]
I seem to be running into the same issue on OSX 10.11.6 (El Capitan). Clicking the "Turn on desktop notifications" button in the settings does nothing. I'm guessing an error is getting thrown somewhere and there's no indication in the UI. Caprine also does not appear in the Notifications settings pane.

![screen shot 2016-11-09 at 9 08 55 am](https://cloud.githubusercontent.com/assets/3154865/20147285/55ff9a34-a65c-11e6-9686-a0e90f9bdb5f.png)

**Comment by vitalykorolev** [comment]
Works fine for me on macOS Sierra. @iansinnott please check your Notification settings in System Preferences.

**Comment by iansinnott** [comment]
Yeah things seem to be working for me now. Not sure what happened though or how to reproduce. Oh well.

**Comment by sindresorhus** [comment]
@Johnny2525 Try the latest version: https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
