### ISSUE TITLE
Caprine Icon Problem

### ISSUE THREAD

**Issue by rahayon** [sindresorhus/caprine#1213]
---Caprine Icon does not show in Application Menu and Dock. I am using Elementary OS 5.1 Hera.

Caprine 2.41.1
Electron 7.1.1
linux 5.0.0-37-generic
Locale: en-US

**Comment by tracker1** [comment]
I'm seeing this issue in both the latest appimage as well as the .deb ... I tried installing the latest snap, but it wouldn't launch.

**Comment by chrisjimallen** [comment]
I am seeing the same issue with the .deb. Ubuntu 191.0.
![Screenshot from 2020-02-07 11-37-29](https://user-images.githubusercontent.com/1681063/74026575-610b1c80-499e-11ea-8ff3-b92457809699.png)

**Comment by tracker1** [comment]
@chrisjimallen thanks, now I just need to remember this when I get home.

**Comment by BananaManCJ** [comment]
This could be fixed by adding the appropriate sizes to /usr/share/icons/hicolor/<size>x<size>/apps/caprine.png in the .deb file. The only one icon now is at /usr/share/icons/hicolor/0x0/apps/caprine.png which makes no sense to me.

**Comment by BananaManCJ** [comment]
I have located the issue and will make a pull request soon

**Comment by alekksander** [comment]
i cannot confirm this one on kde's plasma. all of you guys are on gtk de? 
![Screenshot_20200425_154337](https://user-images.githubusercontent.com/3148302/80281453-90166c00-870b-11ea-94e3-97f313df8e12.png)

**Comment by tracker1** [comment]
@alekksander I think you need to add a plugin for extra notification icons in current Gnome (unsure of others)... was kind of a pain iirc... Been on windows for a couple months because of work, will probably switch back soon-ish.

**Comment by BananaManCJ** [comment]
I made a deb that has just the Caprine icons and fixes it [here](https://drive.google.com/file/d/1el5d570FtILum6mh-VoOyWDlD5f4IBjW/view?usp=sharing). If you want to extract it to make sure I'm not installing malicious code, you can do ```dpkg-deb -R <path to deb>```

**Comment by yermulnik** [comment]
@BananaManCJ Thanks for the .deb. I could install it w/o any issue and icons are where they're expected. Though Caprine's systray icon is still missing for me =( What else can I try to fix the issue?

**Comment by BananaManCJ** [comment]
> @BananaManCJ Thanks for the .deb. I could install it w/o any issue and icons are where they're expected. Though Caprine's systray icon is still missing for me =( What else can I try to fix the issue?
Let me take a look

**Comment by BananaManCJ** [comment]
> @BananaManCJ Thanks for the .deb. I could install it w/o any issue and icons are where they're expected. Though Caprine's systray icon is still missing for me =( What else can I try to fix the issue?

Try removing the folder /usr/share/icons/hicolor/0x0

**Comment by yermulnik** [comment]
@BananaManCJ no luck =( I'm on Linux Mint 18.3 Sylvia with Mate as DE.

**Comment by yermulnik** [comment]
I winder how do I debug Caprine. It doesn't output any messages to stdout/stderr when ran from CLI...

**Comment by BananaManCJ** [comment]
I'm on GNOME and the systray icon works fine, try running it with --debug. It's an electron app so that should work.

**Comment by yermulnik** [comment]
No output with `--debug` %-\

**Comment by BananaManCJ** [comment]
You do have "Show Tray Icon" enabled in the Caprine settings, right?

**Comment by yermulnik** [comment]
Yeah, definitely I do. It's working fine up until version 2.43.0 of Caprine. Any newer version fails to show systray icon. I've read through a bunch of issues here and in Electron repo and no workaround worked for me =( Thanks for helping though.

**Comment by BananaManCJ** [comment]
If you run it from source you can debug it

**Comment by BananaManCJ** [comment]
Saw that [this](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-659879082) fixes the icon problem

**Comment by yermulnik** [comment]
> Saw that [this](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-659879082) fixes the icon problem

Is this something that should be done during build or a user can incorporate it after install or something?

**Comment by BananaManCJ** [comment]
> > Saw that [this](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-659879082) fixes the icon problem
> 
> Is this something that should be done during build or a user can incorporate it after install or something?

What distro are you using?

**Comment by yermulnik** [comment]
> > > Saw that [this](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-659879082) fixes the icon problem
> > 
> > 
> > Is this something that should be done during build or a user can incorporate it after install or something?
> 
> What distro are you using?

Linux Mint 18.3 Sylvia (Ubuntu 16.04).

**Comment by BananaManCJ** [comment]
@yermulnik a missing system tray icon is a different issue, make a new issue

**Comment by dusansimic** [comment]
The app icon problem (desktop icon) is a bug in Electron Builder that builds the app for Linux. This is a bug that is present for a few years now and still is not fixed which is really bad. For now on Linux AFAIK deb package has an icon problem but AppImage and Snap don't have that problem or Arch in it's repositories. To fix it follow instructions in this issue or [this](https://github.com/sindresorhus/caprine/issues/782#issuecomment-465383700) comment.

Regarding tray icon, install libappindicator and if you're using Gnome install [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) extension.

As all issues are resolved or have a workaround, I'll close this issue.
