### ISSUE TITLE
dark mode - forwarded message - text colour

### ISSUE THREAD

**Issue by rtpHarry** [sindresorhus/caprine#1218]
I appreciate the work you do to try to keep the dark mode dark.

It seems they are always breaking things, and I've stopped reporting the more obvious ones as I'm sure you're going to see and fix them.

This one seems a bit more hidden though and not something I have seen before.

It looks like the text in a forwarded message has its own background color injected but the text colour isn't being updated as well:

![image](https://user-images.githubusercontent.com/1038062/70806144-8f131c80-1db2-11ea-8805-feac156dec56.png)

**Comment by rtpHarry** [comment]
oops missed the selected rule:

![image](https://user-images.githubusercontent.com/1038062/70806567-8b33ca00-1db3-11ea-91da-57ecfa8c1b52.png)

**Comment by dusansimic** [comment]
Hi! Thanks for reporting this. Is there some way I can reproduce this on my machine?
