### ISSUE TITLE
Caprine opening chat in blank window

### ISSUE THREAD

**Issue by alynur** [sindresorhus/caprine#1219]
Just installed Caprine on my Samsung laptop running Peppermint 9. The launch is normal and I can select a contact to start a video chat with but when I click on the camera icon, a new window opens and remains blank. I installed Caprine using the .deb file.
---

Caprine 2.41.1
Electron 7.1.1
linux 5.3.0-24-generic
Locale: en-US

**Comment by CvX** [comment]
Issue tracked in #1189
