### ISSUE TITLE
Cannot Disable Windows Notification Sound

### ISSUE THREAD

**Issue by KZcheese** [sindresorhus/caprine#1224]
When notifications are enabled in Windows 10, they play the default notification sound, which plays on top of the Messenger ping when sounds are enabled. I'd like to be able to disable this and just keep the Messenger ping. 

The Windows sound is much longer in duration and gets really annoying when I'm getting messages often, and I can't disable the Messenger ping without disabling all messenger sounds.

Apps like slack are able to use custom notification sounds, so perhaps you could rip the Messenger ping and set Caprine to use that as the notification sound? Or just give us the option to silence desktop notifications. Some apps allow you to customize how Windows handles notifications in the `System -> Notifications & Actions`, but Caprine doesn't' show up here.

![image](https://user-images.githubusercontent.com/8646140/71135039-76e63780-21ce-11ea-837e-97ff2809252d.png)

Caprine 2.41.1
Electron 7.1.1
win32 10.0.18363
Locale: en-US

**Comment by dusansimic** [comment]
You can disable sounds in Messenger settings (`File -> Messenger Settings` or `Ctrl+Comma`).
