### ISSUE TITLE
Mesasnger Call

### ISSUE THREAD

**Issue by zezkin** [sindresorhus/caprine#1226]
Whenever I make a voice call or video chat, neither of them works, I just get  a blank white page.
![image](https://user-images.githubusercontent.com/8850324/71383821-bf469080-25e6-11ea-96c5-ad9dbe5e0d0c.png)

---

Caprine 2.41.1
Electron 7.1.1
win32 10.0.18362
Locale: en-US

**Comment by CvX** [comment]
See #1189
