### ISSUE TITLE
Video Call

### ISSUE THREAD

**Issue by ngt308** [sindresorhus/caprine#1227]
Video Call windows is not working. Just only white screen with nothing...
<img width="1392" alt="Screen Shot 2019-12-23 at 22 47 38" src="https://user-images.githubusercontent.com/10971804/71410135-bc937c00-2676-11ea-91a6-feb50be0976c.png">

---

Caprine 2.41.1
Electron 7.1.1
darwin 19.2.0
Locale: en-US

**Comment by CvX** [comment]
See #1189
