### ISSUE TITLE
Emojis blank the window after installing 2.41.1

### ISSUE THREAD

**Issue by artiste212** [sindresorhus/caprine#1228]
I love this app but 2.41.1 introduced a bug on my Mac running Catalina. Clicking on the emoji symbol causes the entire main window to go blank. Nothing short of restarting the app fixes it. I've tried using System emoji, Facebook emoji, and Messenger emoji. I deleted prefs and reinstalled, and it didn't help. 

Window width has no effect on this issue, either.

Help?

**Comment by CvX** [comment]
Reported in #1185
