### ISSUE TITLE
Catalina can't open app because Apple can't check it for malicious software

### ISSUE THREAD

**Issue by CatEntangler** [sindresorhus/caprine#1229]
edit: Before this is closed please read @sindresorhus's Comment below for instructions on how to start the app.

Installed caprine today and got this message upon opening the app:

![Screen Shot 2020-01-02 at 10 24 23 AM](https://user-images.githubusercontent.com/9761464/71678229-47950600-2d4a-11ea-8b21-a48a43dfda76.png)

OS: macOS Catalina 10.15.2

**Comment by manaslupisani** [comment]
same here

**Comment by sindresorhus** [comment]
Yeah, we need to notarize the app. For now, just right-click on Caprine, select Open, and then OK in the prompt, after that you can launch Caprine normally.

**Comment by yermulnik** [comment]
> Yeah, we need to notarize the app.

Any ETA on this?

**Comment by bartskowron** [comment]
The lack of notarization is due to costs involved?
I mean, this issue should be on a priority list to take a challenge and prove a security level of the application which main focus is on privacy matters.
