### ISSUE TITLE
Unable to launch app on Linux

### ISSUE THREAD

**Issue by mrgigabyte** [sindresorhus/caprine#123]
Might be pretty noobish/basic/stupidish question to ask but i followed all the steps stated in the readme.md but i'm still not able to launch the application. I get no error/popups. Nothing actually happens when i try to run the app. What am I doing wrong ? 
![photo_2016-08-24_17-40-14](https://cloud.githubusercontent.com/assets/18233002/17930044/e7c49af4-6a21-11e6-95cf-b40d4e63f569.jpg)

**Comment by hron84** [comment]
Try to switch to `Terminal=true` this starts the program inside a terminal and you maybe can read the error.

Also, check `$HOME/.xsession-errors` file, maybe it contains the error.

**Comment by sindresorhus** [comment]
Try https://github.com/sindresorhus/caprine/releases/tag/v2.0.0 It comes with installers.
