### ISSUE TITLE
[Mac] High performance GPU required

### ISSUE THREAD

**Issue by vyrgozunqk** [sindresorhus/caprine#1231]
On Mac OS Mojave and High Sierra it seems that the GPU renderer requires the high performance(Radeon) GPU, which leads to excessive heat and battery drain. The built-in GPU should be more than sufficient. 

The laptop is: 2017 15" MBP with Radeon 560 and Intel 630

**Comment by x1unix** [comment]
@vyrgozunqk Electron (the technology for web-apps to behave like native apps used here) sucks by default.

**Comment by coreybruce** [comment]
> @vyrgozunqk Electron (the technology for web-apps to behave like native apps used here) sucks by default.

Actually it's not electron here at fault, it would be Facebook messegers web UI doing it

**Comment by vyrgozunqk** [comment]
> > @vyrgozunqk Electron (the technology for web-apps to behave like native apps used here) sucks by default.
> 
> Actually it's not electron here at fault, it would be Facebook messegers web UI doing it

Question, how does the messenger web UI requests the secondary GPU? I don't think it uses WebGL. By the way, there's another open source messenger. I think project is pretty much dead now, but it still works. It doesn't wake the secondary GPU. I am not sure though if it uses CEF or Electron.

**Comment by coreybruce** [comment]
Well if a computer has a GPU and that's were the output is coming from than it's always going to be using the GPU to accelerate, render stuff 2d or 3d etc in your computer regardless if it's a Mac or PC. The issue I have noticed in messenger and Facebook in general is as you scroll through Facebook's website especially is it doesn't do any sort of junk collection and is very bloated which mean as you scroll though, watch videos ect ram usage will in increase. As for gpu memory usage it could be a simular thing, as it renders more stuff on the page it might increase in gpu vram usage.

What GPU do you have?

**Comment by x1unix** [comment]
@vyrgozunqk a few years ago I had MBP mid 2010 with dead discrete GPU (GeForce 330m i think) and I had to switch to internal onboard Intel GPU with [GFXCardStatus](https://gfx.io/).

Although I've switched to internal GPU, sometimes Chrome may switch to discrete GPU randomly. The single solution here was to kill Chrome and switch back to Intel GPU manually.

Since the project is based on Electron (that based on Chrome), I think that your issue is related to my story above.

I can recommend you to try [gfxCardStatus](https://gfx.io/) and switch to onboard GPU.

**Comment by coreybruce** [comment]
Hmm I see well I don't have a Macbook to test this myself. Seems like Mac isn't doing a correct job or telling what devices use what gpu on the macbook.

**Comment by x1unix** [comment]
@coreybruce according to experienced behavior, some apps may force request discrete GPU.

I recommend to try to disable GPU acceleration (there is some flag for that)

**Comment by ookangzheng** [comment]
Mbpr 15 inch, 16gb Ram, 256GB SSD, Late 2015 model (It only has Intel HD graphic)
Fans getting crazy within these 2 days....

**Comment by ookangzheng** [comment]
My Mbpr. 15inch Late 2018 16GB, 256GB SSD
Fans also getting crazy, Caprine (Version 2.42.0 (2.42.0.1762)

![image](https://user-images.githubusercontent.com/6301735/72659514-981f8b00-39fb-11ea-93fb-4d7be0271897.png)

**Comment by rtpHarry** [comment]
the fans going crazy was a bug that was fixed in the patch released about 5 hours ago

**Comment by rtpHarry** [comment]
However, the gpu issue is still present and the only app on my system which constantly wants to keep the gpu running. I'm getting about 3hrs battery on a brand new mbp 16" 2019.

<img width="865" alt="Screenshot 2020-01-21 at 12 25 39 am" src="https://user-images.githubusercontent.com/1038062/72765574-f3f93800-3be4-11ea-8010-cbd29815536e.png">

**Comment by whitecrownclown** [comment]
@rtpHarry 
@vyrgozunqk 
The gpu is used by electron if `hardware acceleration` is activated. You can read more [here](https://electronjs.org/docs/tutorial/offscreen-rendering).

If you don't want to use this option, `Caprine` allows you to disable it. (uncheck `Hardware Acceleration` from the options.

**Comment by rtpHarry** [comment]
@whitecrownclown thanks for the tip! This does work for me.

As I read it I was wondering if this could be automatically toggled when the battery mode is detected, but before anyone else joins me in that idea, it seems that Caprine has to be restarted to run without Hardware Acceleration, so it can't just be toggled as you plug and unplug the device.

Hopefully this will be a net benefit and I won't find I'm impacted by the missing hardware acceleration features. Interestingly, the link to the official Electron documentation that @whitecrownclown provides doesn't sound like a big fan of the hardware acceleration anyway.

**Comment by jrunning** [comment]
This may be related to #1244.
