### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by boetter** [sindresorhus/caprine#1235]
Just tried to set up Caprine on a new Mac and its impossible for me to login, as this is what the first screen looks like and I can't get to enter anything into the fields. Any clues? Still working on my old Mac which is already logged in.

<img width="714" alt="Screenshot 2020-01-10 at 09 23 28" src="https://user-images.githubusercontent.com/1336222/72137372-01aff180-338b-11ea-9558-4752da6be27e.png">

**Comment by whitecrownclown** [comment]
@boetter What version are you using?

This is what looks on v2.41.1

<img width="1191" alt="Screenshot 2020-01-10 at 15 10 31" src="https://user-images.githubusercontent.com/8309417/72155250-6420e600-33bb-11ea-8d36-d09bc452521d.png">

**Comment by boetter** [comment]
Same version. Just checked Little Snitch to be sure, and its not limiting traffic and AdGuard is off too.

<img width="702" alt="Screenshot 2020-01-10 at 14 13 13" src="https://user-images.githubusercontent.com/1336222/72155466-7b5bd580-33b3-11ea-89c6-4740a1965210.png">

**Comment by devTomek** [comment]
What will happen when you click: shit + cmd + 1?

**Comment by Gideon-Felt** [comment]
I just recieve a White screen and am entirely able to do nothing with the application.
