### ISSUE TITLE
Window out of bounce (Windows)

### ISSUE THREAD

**Issue by sfenne** [sindresorhus/caprine#1236]
I have multiple monitors and sometimes I toggle the main monitor, which could be the cause of Caprine Messenger to wind up in the void.

Because I can't move the Caprine window with WIN + L/R, the Caprine Window is stuck outside my screens. 

Any possible fix w/o uninstalling and installing Caprine again?

**Comment by sfenne** [comment]
Found I fix myself:

On your start bar, hold your mouse over the Caprine icon and wait until the thumbnail shows up.
Right click the thumbnail and click move. Then hold your (for me) left key until the window star

![image](https://user-images.githubusercontent.com/2726664/72240315-06bbad80-35e4-11ea-8509-5733b8f802e6.png)

**Comment by tomioe** [comment]
This should be fixed in [PR 1280](https://github.com/sindresorhus/caprine/pull/1280).
