### ISSUE TITLE
White screen when opening up Emoticon dropdown

### ISSUE THREAD

**Issue by lynhbn** [sindresorhus/caprine#1237]
Environment:
Mac OS 10.13.6
Caprine Version 2.41.1 (2.41.1.1739)

Steps:
1. Open a conversation chat window
2. Click Emoticon button to show the icon list
3. White screen appears immediately!

Please check this bug. It's so annoying that we could not use Emoticons anymore!

**Comment by CvX** [comment]
Tracked in #1185
