### ISSUE TITLE
High CPU usage with v2.42

### ISSUE THREAD

**Issue by giubil** [sindresorhus/caprine#1239]
When launching Caprine this morning I was greeted with a new version. However I was also greeted with 130% CPU utilization on idle (relaunched multiple times, the issue persists).

I've reinstalled v2.41.1 and the issue disappeared. This poses a problem however, as Caprine auto-updates, and I haven't found a way to pin the version in the settings.

Here is a screenshot of Activity Monitor of Caprine idling on v2.41.1 : 

![image](https://user-images.githubusercontent.com/9071882/72606454-ea3eae80-391e-11ea-8188-b3cab6df0836.png)

And here is a screenshot of Caprine idling on v2.42 : 

![image](https://user-images.githubusercontent.com/9071882/72606541-0e9a8b00-391f-11ea-85e0-69bb76ec600d.png)

I'm on MacOS 10.14.5, with a macbook pro 13" 2018 if that helps.

**Comment by wentz-s** [comment]
Currently having the same issue, only thing that's different is I have a 2015 macbook instead

**Comment by NielsKersic** [comment]
Same issue here on 2019 15" MacBook Pro

**Comment by Xanarkan** [comment]
Same issue here.
**Caprine Version 2.42.0 (2.42.0.1762)
macOS Catalina 10.15.2 (19C57)**
MacBook Pro 15 2018 (Intel Core i9-8950HK, 32 GB DDR4, 1 To SSD, AMD Radeon Vega 20 & Intel UHD Graphics 630)

My laptop's fans were blowing air endlessly and I began to worry about it. I'm almost reassured that it's juste Caprine (and probably Electron) that's eating CPU ressources.

**Comment by zenopopovici** [comment]
Download a lower version, set app as read-only. Temp fix.

**Comment by faboyds** [comment]
> Download a lower version, set app as read-only. Temp fix.

Which version are you using? In 2.41.1 it doesn't happen?

**Comment by NielsKersic** [comment]
> > Download a lower version, set app as read-only. Temp fix.
> 
> Which version are you using? In 2.41.1 it doesn't happen?

2.41.1 is stable

**Comment by mwkcoding** [comment]
I'm having this issue on my MacBook Pro 16" 2019

@zenopopovici Can you make a step-by-step guide for the temp fix?

**Specs**
Intel Core i9 2.3GHz
16 GB RAM
Radeon Pro 5500M
1TB SSD

Caprine version 2.42
macOS Catalina 10.15.2

**Comment by zenopopovici** [comment]
@mwkcoding Download 2.41.1, overwrite the one you have in your Application folder, click it ->CMD+i->Sharing & Permissions->Set all to read only.

**Comment by mattnoir** [comment]
Same issue here, MP Pro 15" 2014 running on Mojave

**Comment by h3x4d3x4** [comment]
Same issue here on latest Catalina, Caprine Version 2.42.0. Guess something is broken somewhere.

**Comment by yauuik** [comment]
same

**Comment by gferreroferri** [comment]
Same here

**Comment by marcinlesek** [comment]
MacBook 2018 15", Mojave 10.15.2 (19C57), this same, unfortunately 😕

**Comment by NielsKersic** [comment]
@sindresorhus @CvX @veniversum would any of you be able to check this out? It appears to be a widespread and high-priority issue.

**Comment by CvX** [comment]
Fixed by @whitecrownclown in 2.42.1
