### ISSUE TITLE
Stuttering when typing with autocorrection

### ISSUE THREAD

**Issue by czif** [sindresorhus/caprine#1242]
when i type and it's correcting with native macOS feature it stutters. it didn't do that on 2.41

---

Caprine 2.42.0
Electron 7.1.9
darwin 18.7.0
Locale: pl

**Comment by czif** [comment]
i use macOS Mojave 18G2022 with i5 8th generation so it shouldn't work bad at all

**Comment by CvX** [comment]
Possibly related to #1239, #1243. Does this still occur in 2.42.1?

**Comment by czif** [comment]
Problem seems to be fixed on 2.42.1 (2.42.1.1768).
App is updating silently so I didn't even know it was updated. 
Thanks / Dziękuję Jarku :)
