### ISSUE TITLE
CPU 100% usage

### ISSUE THREAD

**Issue by carlsonbin** [sindresorhus/caprine#1243]
MacBook Pro (15-inch, 2018); MacOS 10.15.2

CPU constantly using 100% after updated to 2.42

---

Caprine 2.42.0
Electron 7.1.9
darwin 19.2.0
Locale: en-GB

**Comment by nebbles** [comment]
Seems like duplicate of #1239

**Comment by gferreroferri** [comment]
Same here. Caprine helper goes to 91% and my MBP 2018 becomes really hot

**Comment by AndresSalinas97** [comment]
Same here. High CPU usage even when logged out.

**Comment by marcinlesek** [comment]
This same here.
