### ISSUE TITLE
Memory usage increases upto 1300mb as far as seen. 

### ISSUE THREAD

**Issue by shohabmsk** [sindresorhus/caprine#1244]
Just running in the background. The memory usage increases a lot without any message coming or doing anything. Running 64bit win 10 lates t with all updates installed. Didn't check earlier versions of caprine memory usages.

---

Caprine 2.42.0
Electron 7.1.9
win32 10.0.18363
Locale: en-GB

**Comment by varystargaryen** [comment]
Same issue on macOS 10.15.3 Beta (19D62e) and Caprine 2.42.1

**Comment by dondolarson** [comment]
I don't have such an issue as you guys. Autostart run 4 processes and running in background on my machine they takes just under 400MB of memory.

**Comment by krasnoludkolo** [comment]
After  being open ~2 days Caprine currently is using 1,8GB of RAM. (Ubuntu 18.04 LTS)

**Comment by ShaneOH** [comment]
I'm seeing a huge amount of energy consumption by Caprine as well. I'm wondering if this is a Caprine issue or an Electron one.

<img width="800" alt="Screen Shot 2020-01-22 at 4 17 15 PM" src="https://user-images.githubusercontent.com/5799260/72897352-cfab7180-3d32-11ea-9dbf-051a288a29cb.png">

**Comment by tard3x** [comment]
4 processes with ~200MB in Windows 10 Pro 1909. No problem here.

**Comment by krasnoludkolo** [comment]
Imo important question is: how long have the process been on?

**Comment by dondolarson** [comment]
> 4 processes with ~200MB in Windows 10 Pro 1909. No problem here. Latest Caprine 2.42.1 version.

Same here. 200MB and even less, right after restarting my machine. Same setup as you. It's increasing when PC hasn't been restarted for days but I guess it's normal.

**Comment by whitecrownclown** [comment]
This might be fixed by https://github.com/sindresorhus/caprine/pull/1247

**Comment by jepes1981** [comment]
almost a Gig of memory consumption for only 6 hours of use. Running Windows 10 64-bit v1903. Relaunching reverts it back to 196Mb.

**Comment by dondolarson** [comment]
![Caprine](https://user-images.githubusercontent.com/49354563/76768140-e2727d80-679a-11ea-8af5-c0ae24bf102e.jpg)

Everything is fine here with Caprine 2.44.0 on Windows 10 1909 February update. System restart since yesterday 22:19 (17-18 hours ago) and I've used Caprine couple of times since that. It's how it always look for me.

**Comment by pktiuk** [comment]
In my case Caprine 2.45 took 1.5 GB
It was active about 12 hours.

On Ubuntu 20.04

**Comment by pktiuk** [comment]
This is especially visible when you have many images in your conversation.
5 minutes of scrolling through images and Caprine takes 550MB, and when I close window (caprine still in system tray) it doesn't free this memory.
Maybe it just stores all of the images in RAM?
