### ISSUE TITLE
Caprine crashs on emoji modal open

### ISSUE THREAD

**Issue by faboyds** [sindresorhus/caprine#1248]
When I open the emoji modal, the windows turns white and I have to restart Caprine.

![Captura de ecrã 2020-01-21, às 11 54 06](https://user-images.githubusercontent.com/17494275/72803036-00ad7880-3c45-11ea-83e2-76ba11d88a29.png)

Caprine version: 2.42.1
MacOS: Mojave 10.14.6

**Comment by CvX** [comment]
Reported in #1185
