### ISSUE TITLE
Forward not working properly

### ISSUE THREAD

**Issue by dondolarson** [sindresorhus/caprine#1251]
Application doesn't find contacts while trying to forward a message to them, or they're somewhere on the looooooong list of all profiles available on Messenger plattform with specified name & surname, though these are in your contacts/chat with them for some hours/minutes ago. These contacts should be in the beginning of the list when their name & surname has been typed. 

---

Caprine 2.42.1
Electron 7.1.9
win32 10.0.18363
Locale: sv

**Comment by CvX** [comment]
If that's how the https://messenger.com also works for you, there's no way to fix it in Caprine.

**Comment by dondolarson** [comment]
Thank you for your input. I was never using messenger.com, just the mobile Messenger Android app where everything works perfectly so I didn't knew about it. Just did a check and agree with you. This case can be closed, I guess.
