### ISSUE TITLE
Emoji link breaks interface

### ISSUE THREAD

**Issue by garretthyder** [sindresorhus/caprine#1252]
With the latest update if I click on the emoji link the popup takes over the screen and is fully blank. I'm unable to exit or anything and have to quit the application and open it. For now I'm just stopped using emojis.

Screencast;
https://i.gyazo.com/c9a7e15ca84e6603a4663bfc4fddafc4.gif

---

Caprine 2.42.1
Electron 7.1.9
darwin 19.2.0
Locale: en-US

**Comment by CvX** [comment]
Tracked in #1185
