### ISSUE TITLE
How can I trust you my password is secure?

### ISSUE THREAD

**Issue by ciembor** [sindresorhus/caprine#1259]
I don't have an experience with Facebook authentication, but typing a password in a third-party application sounds ridiculous (however I did it and I don't know if I regret it or I regret some other mistake).

**Comment by sindresorhus** [comment]
You have to trust the app, or rather its authors. My reputation is on the line. And the full source is available here on GitHub and you can also inspect the source of the downloaded app.

Regardless, you should always use [2FA](https://www.facebook.com/help/148233965247823).
