### ISSUE TITLE
[Feature request]Viewing removed messages

### ISSUE THREAD

**Issue by riverstore** [sindresorhus/caprine#1261]
Hi, 

Can you please support viewing removed messages, and definitely, only for messages that was sent and removed when Caprine are running.

Thanks a lot.

Best regard.

**Comment by jyoo980** [comment]
I'm not sure if this is a feature that's feasible within Caprine (or FB Messenger app for that matter). Once a message is removed from a conversation, it's gone - that's the remove message feature working as intended. 

AFAIK there's not really a way to bring the message back, even in the native FB messenger application.

**Comment by riverstore** [comment]
Hi @jyoo980 , 

I know that when message is removed, it's gone. I mean that, when a message was sent why Caprine is running, Caprine can "save" it, and when that message is removed, Caprine can show it to user.
