### ISSUE TITLE
Caprine nie łączy się z użytkownikami.Proszę o pomoc ! Pozdrawiam Zdzisław 

### ISSUE THREAD

**Issue by zdzislaw623** [sindresorhus/caprine#1263]
---

Caprine 2.43.0
Electron 7.1.11
linux 5.4.15-arch1-1
Locale: pl

**Comment by CvX** [comment]
Could you specify what exactly is the issue? If it's the calls, the issue is tracked in #1189.

---

Czy możesz sprecyzować w czym dokładnie jest problem? Jeśli chodzi o połączenia audio/video to problem został zgłoszony w #1189.

**Comment by zdzislaw623** [comment]
Najnowsza wersja Caprine 2.43.0-1 nie pozwala  na połączenie się z użytkownikami FB w systemie Linux oraz Win 10, natomiast wersje archiwalne działają i połączenia są uzyskiwane. Załączam obraz jaki się ukazuje po wybraniu użtkownika FB. Nie wiem gdzie i do jakiego pliku linux zapisuje te akcjie bo też bym załączył.   Pozdrawim i jestm zaskoczony szybką reakcją.   Zdzisław Oblizajek

**Comment by CvX** [comment]
This issue is tracked in #1189

---

Ten problem został już zgłoszony w #1189
