### ISSUE TITLE
use cmd/ctrl + number hotkeys for switching channels instead of archive/other

### ISSUE THREAD

**Issue by zebapy** [sindresorhus/caprine#127]
Feels far more common to use `cmd+1` (through 9) hotkeys to switch between chats (another popular desktop FB messenger app does this) over using the hotkeys to archive or delete channels. This is also how browser hotkeys work for switching between tabs. It'd be nice if Caprine had this functionality. 

edit: Slack also mimics this when switching teams.

**Comment by sindresorhus** [comment]
Sure, if someone does a good pull request and comes up with some good shortcuts for those existing actions :)

**Comment by zebapy** [comment]
@sindresorhus I have some of it started. What would you recommend we switch the Mute, Delete, Archive hotkeys to?

**Comment by zebapy** [comment]
@sindresorhus have you noticed these have stopped working?

**Comment by arielserafini** [comment]
"Select Next Conversation" and "Select Previous Conversation" have also stopped working.

**Comment by zebapy** [comment]
Did this stop working yet again?
