### ISSUE TITLE
Container colors in custom style are not applied

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1272]
Right now, the differences between `--container-color` and `--container-dark-color` seem muddled. When editing custom styles, changing `--container-color` only affects the dark mode, while `--container-dark-color` doesn't seem to change anything.

**Comment by dusansimic** [comment]
https://github.com/sindresorhus/caprine/blob/master/css/dark-mode.css#L837
Ass seen here, `--container-dark-color` seems to affect login screen and 2FA screen background color.
Hope this helps 😁.
