### ISSUE TITLE
Taskbar Icon doesn't show menu

### ISSUE THREAD

**Issue by tlkw79** [sindresorhus/caprine#1274]
The taskbar icon doesn't show a menu at all. 
---

Caprine 2.44.0
Electron 8.0.0
linux 5.3.0-28-generic
Locale: en-US

**Comment by zer09** [comment]
same here, but I rolled back to v2.42 and it works

**Comment by djvar94** [comment]
Same here with Caprine snap (snap package) on Ubuntu MATE 20.04 with MATE v.1.24
