### ISSUE TITLE
Messages don't scroll to the bottom

### ISSUE THREAD

**Issue by wilg** [sindresorhus/caprine#1278]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/caprine/issues/1278)

Most of the time, when new messages are received or you switch conversations, the scroll position does not move to the bottom and you have to manually scroll to see conversations.

This is such a frustrating bug, it must only happen in certain scenarios that don't happen to the authors, because the app is so well thought through otherwise. I am not sure what is unusual about what I am doing though.

---

Caprine 2.44.0
Electron 8.0.0
darwin 19.3.0
Locale: en-US

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars1.githubusercontent.com/u/54353?v=4' alt='wilg' width=24 height=24> wilg](https://issuehunt.io/u/wilg) ($50.00)

### Submitted pull Requests
- [#1295 Autoscroll (#1278) ](https://issuehunt.io/r/sindresorhus/caprine/pull/1295)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/caprine/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by mquevill** [comment]
I have this problem too. It doesn't seem to be remembering previous places or anything. It seems to just randomly go up a ways, requiring the user to scroll down to the bottom.

Caprine 2.44.0
Linux Mint 19.3 (installed via .deb)

**Comment by mmirkov** [comment]
+1 

Caprine 2.44.0
Windows 10 (1909)

**Comment by mquevill** [comment]
Actually, this may be an issue inherent in the Messenger interface. Even when switching between chats on messenger.com, this issue occurs. Furthermore, it may be difficult to implement in Electron (see https://github.com/electron/electron/issues/5884). So if Caprine itself wants to force a scroll to the bottom to address this issue, a workaround might be necessary.

**Comment by NightMean** [comment]
I was using v2.33.1 and it kept happening to me always but today I updated to latest and the issue mostly dissapeared. It still sometimes isn't at the end of the conversation but that's like 5% of the time and it was way worse in v2.33.1 as I had to scroll like 50 messages down now it's like 2-3 messages.

**Comment by maxoku** [comment]
I can confirm this on Windows 8.1. In browser it scrolls to bottom when switching chats. Though in both doesn't scroll to bottom in first open chat after opening app/page.

In some chats it scrolls on switching, but in some it's persistent to not 🤔 and always on the same position.

**Comment by maxoku** [comment]
It seems the reason is in rescaling the medias. When chat is loaded it is on the bottom, but some medias just change their size while keeping the view (top) in the same place. But if media is bigger then the bottom is lower, so it's not in the view anymore.

Also videos (if setting Autoplay Video is enabled) are just getting bigger than in the browser. At some point it does have its benefits if video is just too small, but generally is causing only new problems like the one discussed here.
