### ISSUE TITLE
Selected contact in search in dark mode is near-invisible

### ISSUE THREAD

**Issue by andersfischernielsen** [sindresorhus/caprine#128]
The "selected contact" indicator under the search field when in dark mode is nearly impossible to see, usually resulting in me choosing the wrong contact. A fix for this would be a styling change. 
(Dark mode is awesome otherwise, though)

![screen shot 2016-09-20 at 15 15 06](https://cloud.githubusercontent.com/assets/5990738/18671653/3750eb08-7f45-11e6-83ed-f7628d90af5a.png)

**Comment by sindresorhus** [comment]
PR welcome for a fix, but I unfortunately don't have time improve dark mode.

-

// @danhp @rrdelaney @lukyth

**Comment by andersfischernielsen** [comment]
See #129. :)
