### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/caprine#1285]
As you can see it tries to load Facebook instead of Messenger:

![image](https://user-images.githubusercontent.com/36894700/75257366-24845100-57e5-11ea-92f0-21caefe54dc7.png)

Also there's some white text: `Please try closing and reopening your browser window.
`

**Comment by szmarczak** [comment]
Restarting Caprine does not help :(

**Comment by sindresorhus** [comment]
Hi

**Comment by sindresorhus** [comment]
Is this still an issue? Usually these kinds of issues are temporary Facebook issues. If it's still an issue, try logging out and in again.

**Comment by szmarczak** [comment]
> If it's still an issue, try logging out and in again.

Tried that too. 

> Usually these kinds of issues are temporary Facebook issues.

These are not. It happens 99% of the time. `messenger.com` works fine in the browser tho.

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/75713916-04fc9500-5ccb-11ea-8e45-66c78ebe5b5e.png)

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/75713990-28274480-5ccb-11ea-8b76-391430ebcf8e.png)
![image](https://user-images.githubusercontent.com/36894700/75714004-31181600-5ccb-11ea-8b53-d96dbcab664f.png)

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/75714286-b8fe2000-5ccb-11ea-8039-923c30541177.png)

**Comment by szmarczak** [comment]
This is the timing of `password/`

![image](https://user-images.githubusercontent.com/36894700/75714715-86085c00-5ccc-11ea-95d8-27e96112bf99.png)

**Comment by szmarczak** [comment]
I know how to reproduce this. `password/` takes ~1s. After it goes 302 it doesn't redirect you straight away. If you click Continue again, it makes a new `password/` and fails.

**Comment by szmarczak** [comment]
After you click "Continue" you shoud add a "Signing in..." page / overlay.

**Comment by sindresorhus** [comment]
Hard for me to debug this when I cannot reproduce. Maybe we need to add some more URL patterns to https://github.com/sindresorhus/caprine/blob/5daa934f88e31dc40c4ef5aa5467d900d72031cd/source/index.ts#L505

**Comment by szmarczak** [comment]
I'll try to provide some reproducible code soon.

**Comment by szmarczak** [comment]
When you're about to log in, click "Continue", wait until the `/password` request gives 302 and then click "Continue" yet again:

![caprine](https://user-images.githubusercontent.com/36894700/76103336-cff58880-5fd1-11ea-8085-51af059e34c2.gif)
