### ISSUE TITLE
Window always on top

### ISSUE THREAD

**Issue by nguyenandersonp** [sindresorhus/caprine#1286]
This app is always on top of other windows even when clicking on other windows and another window is the "active" window.

---

Caprine 2.43.0
Electron 7.1.10
darwin 18.7.0
Locale: en-US

**Comment by sindresorhus** [comment]
Sounds like you have activated the "Alway on Top" preference.

**Comment by PrimozR** [comment]
Just found this, maybe ctrl shift T is not the most sensible shortcut? It's the 'open last closed tab' shortcut in a browser and if you have the wrong window focused it's easy to put Caprine on top by mistake and not know what happened...
