### ISSUE TITLE
Voice and video calls do not work

### ISSUE THREAD

**Issue by ghost** [sindresorhus/caprine#1290]
Voice and video calls do not work! Windows 10(1909)x64

[Аннотация 2020-03-01 153906-1](https://user-images.githubusercontent.com/61655463/75626864-ca640100-5bd3-11ea-840c-3102af07c290.jpg)

Аннотация 2020-03-01 154216](https://user-images.githubusercontent.com/61655463/75626842-a30d3400-5bd3-11ea-801a-315fb7c3d5f4.jpg)
------------------------------------------------------------------------
Voice and video calls do not work
The latest version in which voice and video communication works is Caprine 2.30.

---

Caprine 2.44.0
Electron 8.0.0
win32 10.0.18363
Locale: ru

**Comment by vogu66** [comment]
#1189

**Comment by lashkevi** [comment]
The same on Linux, Caprine 2.44.0 (Appimage). Empty window on attempts to start audio or video calls.
