### ISSUE TITLE
Feature Request change notification click action.

### ISSUE THREAD

**Issue by vesterlay** [sindresorhus/caprine#1294]
While you get a notification instead of dismissing it on click, redirect the user to the message in the app. 

OS: Manjaro gnome

**Comment by sindresorhus** [comment]
That’s how it’s supposed to work. It’s a bug if it does not.

**Comment by vesterlay** [comment]
So it's a bug, apparently. Let me know if you want me to provide any logs or smth. My gnome version is 3.34.4.

**Comment by areographe** [comment]
Just want to mention that Cinnamon 4.4.8 (manjaro) shows the same behaviour. if the app is toggled invisible / hidden / systray-icon-only, clicking on the notification dismisses it but doesn't open the caprine window or show the correct chat. @vesterlay have you made a bug report? i can do that if necessary

**Comment by areographe** [comment]
just to clarify, if the caprine window is not hidden, it works as expected.
