### ISSUE TITLE
Tray icon disappear after the suspension

### ISSUE THREAD

**Issue by vesterlay** [sindresorhus/caprine#1296]
After the suspension caprine tray icon disappear. Nonetheless, all functionality is present even if an icon is missing. 

Caprine 2.44.0
Electron 8.0.2
linux 5.4.23-1-MANJARO 
Gnome 3.34.4
Locale: en-GB

**Comment by JBudny** [comment]
It may be related with #1241

**Comment by vladimiry** [comment]
https://github.com/electron/electron/issues/22443

**Comment by dparvanov** [comment]
A temporary fix is to switch to work chat and back to messanger ( File -> Switch to Work Chat... , File -> Switch to Messanger...)

**Comment by dusansimic** [comment]
It seems that this is Gnome + Chromium related. There is a [workaround](https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150) for this bug until it gets fixed in Chromium. @sindresorhus what do You think? Could we add this temporarily?

**Comment by carestad** [comment]
At least I am able to get the sys icon re-appearing again by toggling the `File > Caprine Settings > Show Tray Icon`. But that doesn't work if I have closed the app before suspending the laptop

**Comment by JBudny** [comment]
I've just found out that Electron is restoring an old implementation of tray icons that Chromium removed with Electron v8.

PR: [23674](https://github.com/electron/electron/pull/23674)

**Comment by JBudny** [comment]
I've just found out that Electron is restoring an old implementation of tray icons that was removed from Chromium in Electron v8.

PR: [23674](https://github.com/electron/electron/pull/23674)

**Comment by dusansimic** [comment]
AFAIK, this issue has been fixed on all platforms that were affected. This can be closed.

**Comment by vesterlay** [comment]
You are right, everything works alright now. Closing..
