### ISSUE TITLE
scrolling, using arrow keys 

### ISSUE THREAD

**Issue by janbassett** [sindresorhus/caprine#1299]
Very disappointed after so long this issue, (very basic!) has not been fixed!  You CAN'T SCROLL!  CAN'T USE ARROW KEYS!  This is Very much needed, not all the time, but when you need it, you Really need it!  IE,  if text you've sent fairly long, after sending you want to proofread - and you can't!  Very frustrating!  The scroll bar is TOTALLY USELESS!  For one thing, it Immediately disappears, if you can even remember its there!  But it doesn't even matter since it DOESN'T WORK, you can't grab with mouse and make it go up/down.  I've tried using the tab key while holding the down or up arrow key, nope.  You can end up at text from MONTHS AGO.  

PLEASE FIX THIS IMMEDI A T E L Y!!!!   

---

Caprine 2.18.0
Electron 2.0.8
win32 x64 10.0.18363

**Comment by RDKRACZ** [comment]
I don't know why this person uses capital letters, doesn't use the scroll wheel, and gives orders but it's funny. But yea scrolling with arrows would be nice.

**Comment by dusansimic** [comment]
IIRC this issue is fixed. Please download latest release and check if it works. Let me know about the results.

**Comment by dusansimic** [comment]
> I don't know why this person uses capital letters, doesn't use the scroll wheel, and gives orders but it's funny. But yea scrolling with arrows would be nice.

@RDKRACZ, this issue is not a feature request to scroll with arrows rather and issue report that there is no way to scroll content in message input box. This is was due to bad style patch but it was fixed. I'll close this issue now.
