### ISSUE TITLE
Feature Request: Proxy Settings

### ISSUE THREAD

**Issue by reece146** [sindresorhus/caprine#1302]
Just discovered this app. It works quite nice; looks good on my Linux box. 

Would it be possible to incorporate a proxy setting menu in File -> Caprine Settings ?

This way it would be possible to route the Caprine Messenger traffic through a local VPN proxy or similar.

In the meantime does Caprine respect http[s]_proxy environment variables? I could wrap it in a shell script for now.

Thanks.

**Comment by lefterisgar** [comment]
Duplicate of #1399.
