### ISSUE TITLE
Add option to reduce font size in side element

### ISSUE THREAD

**Issue by Selich** [sindresorhus/caprine#1309]
Hi!

I didn't find any option to reduce the font size of any text contained in the sidebar. That includes name, options etc. Didn't find the issue regarding that.

I am currently doing it manually using the dev tools as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/10079878/77168144-a0597c80-6ab7-11ea-8bfc-6be11578dd10.png)

I could probably add the feature and do a PR if you don't mind or have any other plans for it.

**Comment by sindresorhus** [comment]
This is not something we’re interested in adding an option for. However, you can add your own custom CSS overrides in the Preferences.
