### ISSUE TITLE
Bad Idea: Change app name to “Messenger”

### ISSUE THREAD

**Issue by davidbarsky** [sindresorhus/caprine#131]
Probably is a terrible idea for a boat load of reasons, but: it’d be super convenient to be able to search `Messenger` in Spotlight and open up that app. Currently need to do some mental remapping of “Caprine” to “Messenger”, which is kinda a pain.

Opening this issue because I wanted to see if there’s an interest in making this change.

(Really useful app, thanks!)

**Comment by bl4de** [comment]
I think (or maybe almost 100%sure) Messenger is a registered trademark of FB :)

PS. Why don't you juts rename your local Caprine executable into Messenger?

**Comment by sindresorhus** [comment]
It's intentionally not named "Messenger" as I didn't want any potential issues with Facebook. Just rename the app yourself or create an alias.
