### ISSUE TITLE
Feature request: Pop-out images

### ISSUE THREAD

**Issue by Ariane-B** [sindresorhus/caprine#1310]
I use Caprine in a very thin window. It occupies the left 20% of my screen or so. Doing this allows me to keep an eye on it while having a large window to focus on what I'm doing. I love this layout, except for how images will open inside that small sidebar. I understand why it's that way, and I don't even know if it's technically feasible, but **I wish the images that I click to enlarge could open out of the application's bounds and take up most of my screen**. Zooming into an image has little meaning if it's still tiny, after all.

**Comment by dusansimic** [comment]
This request is outdated since the ui has changed and clicking on an image now opens a modal which shows the image in full size (takes up the whole window).

**Comment by Ariane-B** [comment]
Does it only take up the whole *window*? Because if so, that's not what I'm asking for. I'm asking for something that can take the whole *screen* regardless of window size.

**Comment by dusansimic** [comment]
I don't think that what you would like would be a good default behaviour. Most applications like this open images inside the current window. I could be implemented as an option but for now we don't plan on adding any new features, rather work on fixing current ones. PR's are welcome tho.

After your clarification of the feature request, I can see that this is basically the same as #255 so I'll leave this closed in favour of that one. Also an interesting suggestion is already filed in #875. Could this be a valid solution?

**Comment by Ariane-B** [comment]
Sure!
