### ISSUE TITLE
video call and simple call doesn't work at all

### ISSUE THREAD

**Issue by Jonathanr67** [sindresorhus/caprine#1313]
Hi with caprine video call and simple call doesn''t work at all. I try with the .deb and appimage and the result is the [same.)
rauch.jonath@gmail.com
![Capture du 2020-03-23 12-01-23](https://user-images.githubusercontent.com/31011858/77310218-40084c00-6cfe-11ea-9f91-16a15a64b996.png)

---

Caprine 2.44.0
Electron 8.0.0
linux 4.15.0-91-generic
Locale: fr

**Comment by radekjuthner** [comment]
I have the same problem, Caprine 2.44.0

**Comment by Friedd** [comment]
same here

**Comment by MrGKanev** [comment]
Same here.
OS -> `DISTRIB_ID=ManjaroLinux    DISTRIB_RELEASE=19.0.2`
Electron -> v8.1.1
Caprine -> 2.44.0-1

**Comment by vogu66** [comment]
#1189

**Comment by swiatlyk** [comment]
Same for me. KDE-Neon and .deb package
