### ISSUE TITLE
macOS Catalina - No Push Notifications

### ISSUE THREAD

**Issue by ghost** [sindresorhus/caprine#1314]
Caprine seems to be missing from my notifications center within my system settings in macOS Catalina.  I am having the same issue with Discord, Skype, and WhatsApp as well so perhaps there was a change in macOS that causes this?  Unable to enable or access push settings for any of these.

**Comment by riconaranjo** [comment]
I'm running the latest version of macOS Catalina and I have no issues with push notifications from Caprine, including in notification centre.

**Comment by dusansimic** [comment]
Stale and notifications were removed from messenger website.
