### ISSUE TITLE
TrayIcon does not appear at all (Debian)

### ISSUE THREAD

**Issue by ginsterbusch** [sindresorhus/caprine#1317]
After installation via deb package, Caprine works flawlessly, but the Tray Icon never appears. Closing the application seems to lead to a complete exit, and restarting it leads to an additional thread .. 

---

Caprine 2.44.0
Electron 8.0.0
linux 4.19.0-1-amd64
XFCE 4.12
Locale: de

**Comment by toantk238** [comment]
@ginsterbusch Have you enable "File -> Caprine Settings -> Launch Minimized" ?

Anw, the tray icon seems only works for few minutes. It could disappear suddenly. When I check whether app is running or not via Task Monitor, I still see "caprine".

**Comment by GiORdANio** [comment]
Install xfce4-statusnotifier-plugin.
Works for now.
![icontray](https://user-images.githubusercontent.com/18457972/78948805-39395180-7ad2-11ea-802a-9e3efab0e440.png)

**Comment by ginsterbusch** [comment]
> Install xfce4-statusnotifier-plugin.
> Works for now.
> ![icontray](https://user-images.githubusercontent.com/18457972/78948805-39395180-7ad2-11ea-802a-9e3efab0e440.png)

What is that? Some non-Debian package?

**Comment by ginsterbusch** [comment]
> @ginsterbusch Have you enabled "File -> Caprine Settings -> Launch Minimized" ?
> 
> Anw, the tray icon seems only works for few minutes. It could disappear suddenly. When I check whether app is running or not via Task Monitor, I still see "caprine".

I dont see the tray icon at all, but certainly, htop, pgrep and ps show me that caprine is running.

cu, w0lf.

**Comment by GiORdANio** [comment]
> > Install xfce4-statusnotifier-plugin.
> > Works for now.
> > ![icontray](https://user-images.githubusercontent.com/18457972/78948805-39395180-7ad2-11ea-802a-9e3efab0e440.png)
> 
> What is that? Some non-Debian package?
> Addition: Apparently talking about this one: https://docs.xfce.org/panel-plugins/xfce4-statusnotifier-plugin
> Without any compilation or installation instructions supplied its a mostly useless suggestion though.
> 
> Nope. Won't work. Compilation not possible, because of apparently outdated libraries. Won't recompile XFCE4 just out of a whim .. this being my main work environment ..

It is debian package:
https://packages.debian.org/search?keywords=+xfce4-statusnotifier-plugin&searchon=names&suite=stable&section=all

You can find in you package installer.
Here is it in MX Linux 19.1:
![image](https://user-images.githubusercontent.com/18457972/78975266-6c083780-7b1c-11ea-86a8-19b085cb6d01.png)

**Comment by wereii** [comment]
`sudo apt-get install xfce4-statusnotifier-plugin` ;)

**Comment by ginsterbusch** [comment]
> > > Install xfce4-statusnotifier-plugin.
> > > Works for now.
> > > ![icontray](https://user-images.githubusercontent.com/18457972/78948805-39395180-7ad2-11ea-802a-9e3efab0e440.png)
> > 
> > 
> > What is that? Some non-Debian package?
> > Addition: Apparently talking about this one: https://docs.xfce.org/panel-plugins/xfce4-statusnotifier-plugin
> > Without any compilation or installation instructions supplied its a mostly useless suggestion though.
> > Nope. Won't work. Compilation not possible, because of apparently outdated libraries. Won't recompile XFCE4 just out of a whim .. this being my main work environment ..
> 
> It is debian package:
> https://packages.debian.org/search?keywords=+xfce4-statusnotifier-plugin&searchon=names&suite=stable&section=all
> 
> You can find in you package installer.
> Here is it in MX Linux 19.1:
> ![image](https://user-images.githubusercontent.com/18457972/78975266-6c083780-7b1c-11ea-86a8-19b085cb6d01.png)

No, I cannot. It is **MX Linux 18.3**, **NOT** 19. 19 is based on Debian 10, while 18.x is still based on Debian 9.

**Comment by ginsterbusch** [comment]
> `sudo apt-get install xfce4-statusnotifier-plugin` ;)

Let's try that, shall we? Result is as expected:

> https://packages.debian.org/search?suite=stretch&searchon=names&keywords=xfce4-statusnotifier-plugin

It doesnt work in Debian Stretch nor MX Linux 18 **now**. But did it ever work before? Ie. was it always broken in XFCE / Debian? If not, then I wouldn't mind downgrading just to get this working properly.

cu, w0lf.

**Comment by wereii** [comment]
Sorry, you didn't specify you actually don't have the package in your distro version.

Basically, electron requires that package when using Xfce4 for Tray icons to work properly ([issue](https://github.com/electron/electron/issues/21445)).
Going with [this comment](https://github.com/electron/electron/issues/21445#issuecomment-565710027) on that issue (recap part), there is some alternative to that package but it seems you would still have to do some building (?).

**Comment by dusansimic** [comment]
As I can see from this thread, installing `xfce4-statusnotifier-plugin` fixes the issue. Weather installation/compilation fails or not on some specific distro version is not related to Caprine. I will close this now.
