### ISSUE TITLE
Phone and video calling do not work on Arch Linux 

### ISSUE THREAD

**Issue by kzoli429** [sindresorhus/caprine#1323]
1. Starting Caprine; login to Messenger OK. However no tray icon appears.
2. Trying external phone call or video call, no joy. An empty overlay window with white background and  Menu (File, Edit, View etc.) titled 'Video Call 0' displayed, but nothing happens afterwords. No calling sound. 
3. Also, when trying to receive a call from outside, a pop-up window with caller name , photo displayed with refuse / accept options. After pressing the accept button, however, again, an empty overlay window with white background and  Menu (File, Edit, View etc.) titled 'Video Call 0' displayed, but nothing happens afterwords. No calling sound. 
---

Caprine 2.44.0
Electron 8.2.0
linux 5.5.13-arch2-1
Locale: en-US
Arch Linux, XFCE Desktop v4.14

**Comment by kzoli429** [comment]
Update:
After installing xfce4-statusnotifier-plugin, tray icon is shown with very simple functions 'toggle' and 'quit'. Nothing else changed; i.e. phone or video calls still do not work.

**Comment by wereii** [comment]
Might be this [issue](https://github.com/sindresorhus/caprine/issues/1189) already.
