### ISSUE TITLE
Can't delete chats

### ISSUE THREAD

**Issue by Wim4rk** [sindresorhus/caprine#1324]
Hi,

Ubuntu 18.04.03 LTS
Can't delete chats, not by menu, nor by hot keys.
---

Caprine 2.44.0
Electron 8.0.0
linux 4.15.0-88-generic
Locale: sv

**Comment by alekksander** [comment]
so this does not work for You?
![Screenshot_20200407_133252](https://user-images.githubusercontent.com/3148302/78664445-57d1f980-78d4-11ea-87c3-a0f4c386136d.png)

**Comment by Wim4rk** [comment]
Unfortuantly not...

Allt gott!

Olov Wimark
Tfn: +46 739-89 80 71


Den tis 7 apr. 2020 kl 13:33 skrev alekksander <notifications@github.com>:

**Comment by Wim4rk** [comment]
Walk-around works! Many thanks.
