### ISSUE TITLE
Vibrancy on Linux

### ISSUE THREAD

**Issue by oxodao** [sindresorhus/caprine#1327]
Hello,
I've seen issues about vibrancy on Windows but none about Linux.

Implementing it would be pretty simple, just set the transparency on the window. 

Compositor like the Gnome/KDE one will take care of the blurring, which are used by most distributions. 

People not using Gnome or KDE are most likely powerusers so they probably know how to set-up Compton/Picom to achieve the same effect.

**Comment by StefanAvra** [comment]
Vibrancy and transparency are different effects. I don't think there is vibrancy in Gnome - correct me if I'm wrong.
As far as I know the electron app does support vibrancy only for macOS.

**Comment by oxodao** [comment]
That's not as good looking as vibrancy in osx yes but transparency+blur is still good nonetheless. 
Indeed this is not supported by default under Gnome https://www.youtube.com/watch?v=AN-cVA_tCR0

**Comment by dusansimic** [comment]
Vibrancy is available only for macOS. Transparency+blur is more of a hack than a feature so I don't think it will be supported here since it's not officially supported by Electron.
