### ISSUE TITLE
Custom CSS doesn't allow changing the own user bubble colour and how to fix

### ISSUE THREAD

**Issue by brunomiguel** [sindresorhus/caprine#1328]
Caprine doesn't allow changing the bubble colour from the user by changing the variables in custom.css. However, adding the following style rule to that file fixes that:

```
._43by[style*='background-color'] {
	background-color: #0f85ca !important;
}
```
Could you provide a fix for this, please?

**Comment by dusansimic** [comment]
This is not being done in Caprine but in Messenger. We have nothing to fix here since chat bubbles are not affected by css variables that are defined by us. You can change chat bubble color in chat settings or with custom css as you've shown in the comment.
