### ISSUE TITLE
macos alert notifications don't go away when message read

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#1329]
the good thing with alerts compared to banners are you don't miss mail, messages, messenger posts. but how they are suposed to work, when you've read the message, they should go away. apple messages do that. because obviously if you got four five units, i cannot fill my life with deleting old unsynced notifications

---

Caprine 2.44.0
Electron 8.0.0
darwin 19.3.0
Locale: en-GB

**Comment by 639me** [comment]
i noticed btw the whole upper part is now draggable. great!
nicolashorne@me.com

**Comment by dusansimic** [comment]
Stale and notifications have been removed from messenger website.
