### ISSUE TITLE
 system tray 

### ISSUE THREAD

**Issue by wojciechGaudnik** [sindresorhus/caprine#1331]
I cannot put it into the system tray 

---

Caprine 2.45.0
Electron 8.2.1
linux 5.3.0-46-generic
Locale: en-US

**Comment by FrogMcRibbit** [comment]
I also don't have anykind of system tray with Caprine 2.45.0. If I close the window normally (not quitting the program), I still have processes related to Caprine, and if someone sends me a message, I do get notified about it.
---

Caprine 2.45.0
Electron 8.2.1
linux 5.4.31-1-MANJARO
Desktop environment: Cinnamon 4.4.8
Locale: en-GB

**Comment by FrogMcRibbit** [comment]
Okay, so I do have a tray icon in KDE, but not on Cinnamon.

It might be an issue that is related to my desktop environment though, and not to Caprine in itself, considering that there was some upcoming changes announced for Cinnamon because of Electron.

> StatusNotifier, libAppIndicator and libAyatana
> 
> Following a change in Electron, XappStatusIcon applets will gain support for StatusNotifier, libAppIndicator and libAyatana.
> 
> [...]
> 
> LibAppIndicator and libAyatana have the ability to fallback to xembed (the GTK tray technology), so in Cinnamon, even though support for these technologies was disabled by default, applications using these libraries would still get their icon into the tray. In Mint, the situation was even better because libAppIndicator was patched to fallback to XappStatusIcon before falling back to xembed, thus preserving compatibility with HiDPI and symbolic icons. The problem was with applications using StatusNotifier directly.. which just didn’t fallback to anything at all and had no visible tray icon. With Electron moving to StatusNotifier this issue became more urgent.
> 
> XappStatusIcon applets gaining support for these technologies will guarantee better support for modern Electron apps and indicators and it will do so in all distributions, without the need to patch anything.
Source: https://blog.linuxmint.com/?p=3887

Welp, I guess I will have to wait for updates of my desktop environment (at least in my case, I don't know is OP also uses Cinnamon or not).

**Comment by yermulnik** [comment]
Same issue in Mint with Mate =(

**Comment by wojciechGaudnik** [comment]
Recently I discovered that Caprine show icon when I run and next restart by changing options (for example Hardware Accelerate)

**Comment by yermulnik** [comment]
@wojciechGaudnik Do you have to do it every time you start the app or it kind of memorizes this behavior?

**Comment by wojciechGaudnik** [comment]
@yatharth Only after hard restart comp.  When woke up from sleep mode(to RAM) than it is ok.

**Comment by yermulnik** [comment]
> changing options (for example Hardware Accelerate)

Didn't work for me. Have to stay at 2.43.0 version for now =(

**Comment by Swash1972** [comment]
Pop_Os 19.10 (Ubuntu 19.10) x64
Gnome 3.34.2
Caprine 2.45
Also missing tray icon, even with showing legacy icons.
Disable and enabling Hardware Acceleration, did not help.

**Comment by snoozi** [comment]
Pop_OS 20.04 x64
Caprine 2.46
GNOME 3.36.2
X11

disappears from tray after wake from suspend; sometimes disappears for unknown additional reasons I haven't quite figured out. Will reappear upon restart. 

Other thread suggested hicolor/0x0 is the problem, will see if it improves the situation over time.

**Comment by yermulnik** [comment]
There's a somewhat related PR in Electron that has been merged today: https://github.com/electron/electron/pull/23674

**Comment by Syndamia** [comment]
I found a workaround for Cinnamon, switch to work chat (`Ctrl + Shift + 2`) and then it will appear. 

Now you can go back to normal chat (`Ctrl + Shift + 1`) and you are still gonna have a tray icon.

**Comment by yermulnik** [comment]
Out of the blue tray icon started to work for me at `v2.48.0` :confused:

**Comment by wildcard-f8** [comment]
I had this problem on Gnome. I just turned on the Gnome extension called Unite and I could see the system tray icon again. For some reason it was hiding it if I turned the extension off.

**Comment by dusansimic** [comment]
This was a bug caused in Chromium itself and it is fixed as some comments said just arround version 2.48 (Caprine). Since it's fixed now I'll close this issue.
