### ISSUE TITLE
"tel" and "video" icons are not displayed then i can't call

### ISSUE THREAD

**Issue by promeneur** [sindresorhus/caprine#1332]
openSuse Leap 15.1
kde apps 19.12.3
plasma 5.18.3
frameworks 5.68.0
qt 5.14.1

"tel" and "video" icons are not displayed then i can't call
![tel_video](https://user-images.githubusercontent.com/240424/79073104-f7342980-7ce4-11ea-893f-801306f3246a.png)

**Comment by CvX** [comment]
It's not a Caprine issue. Those buttons show up only for contacts/profile that you can call.
