### ISSUE TITLE
Ubuntu 18.04 - A Javascript error occurred in  the main process

### ISSUE THREAD

**Issue by centraleffects** [sindresorhus/caprine#1333]
I have tried the .deb and .AppImage version and it doesn't work on my Ubuntu 18.04.1
See Javascript error below:

![image](https://user-images.githubusercontent.com/3509894/79086897-44111200-7d70-11ea-99d4-3ef9a5bfdabc.png)

Thanks!

**Comment by dusansimic** [comment]
Hi! This an expected error when updating from a very old release. Remove `~/.config/Caprine` and start Caprine again.
