### ISSUE TITLE
Mute Notifications persistence problem

### ISSUE THREAD

**Issue by Ph0enixKM** [sindresorhus/caprine#1334]
**Mute notifications** option in Caprine settings does not save. When I restart - it's turned off as if I never turned it on.

---

Caprine 2.45.0
Electron 8.2.1
linux 5.3.0-46-generic
Locale: en-US

**Comment by timhor** [comment]
Having the same issue on Windows 10 (version 1909). Also with Caprine 2.45.0.

**Comment by vanushwashere** [comment]
Same on the Ubuntu 20.04, installed via Snap
