### ISSUE TITLE
Doesn't start when blocking ICanHazIP.com & ipify.org

### ISSUE THREAD

**Issue by Vilscon** [sindresorhus/caprine#1335]
I'm using LittleSnitch on Mac to block outgoing/incoming requests from ICanHazIP.com & Ipify.org and notices by doing so, Caprine doesn't start.

Why is this app dependent on these trackers to start?

**Comment by sindresorhus** [comment]
To check whether you’re online.

**Comment by jaddie** [comment]
Why would the app need to get the user's IP in order to see if you are online, accessing anything such as google or even a dns resolution or ping to a large service like cloudflare would be more suiting and not make people have a concerned reaction?

**Comment by Vilscon** [comment]
Completely agree with @jaddie here.

**Comment by dusansimic** [comment]
I agree that IP is not needed to check if user is online however Caprine uses [is-online][1] module to do that. This issue should be reported there since that module makes the requests.

[1]:https://github.com/sindresorhus/caprine#keyboard-shortcuts
