### ISSUE TITLE
video call and simple call does not work on ubuntu 20.04lts

### ISSUE THREAD

**Issue by Jonathanr67** [sindresorhus/caprine#1344]
video call and simple call does not work on ubuntu 20.04
---

Caprine 2.44.0
Electron 8.0.0
linux 5.4.0-26-generic
Locale: fr

**Comment by MrGKanev** [comment]
Update to a newer version of Caprine. It is fixed in 2.45.0.

**Comment by Jonathanr67** [comment]
Ok thanks you it's fond. Juste une little problèm with 2.45.0. I didn't
have icon

Le dim. 26 avr. 2020 à 22:11, Gabriel Kanev <notifications@github.com> a
écrit :

**Comment by michaelarnauts** [comment]
The snap store doesn't have an updated 2.45.0 version.

See https://snapcraft.io/caprine

**Comment by Jonathanr67** [comment]
Ok thank you

Rauch Jonathan

Le mar. 5 mai 2020 à 17:36, Michaël Arnauts <notifications@github.com> a
écrit :

**Comment by MrGKanev** [comment]
If this is answered @Jonathanr67 (and you don't have a problem anymore ) you can close the issue? And I didn't find it in the information that he installed it from a snap @michaelarnauts . If you have the same issue and you are on 2.44 you can download the snap or deb file from here (github). There is a 2.45 version here.

**Comment by michaelarnauts** [comment]
I installed the deb from here. Couldn't get the snap to install.

I do also have the icon issue, but that is probably reported in another issue.
