### ISSUE TITLE
Video thumbnail is blank.

### ISSUE THREAD

**Issue by AggelosM** [sindresorhus/caprine#1345]
The last week or so, when you send, or someone sends you a video from FB, the thumbnail of it is empty.

---

Caprine 2.45.0
Electron 8.2.1
win32 10.0.18363
Locale: en-US

**Comment by alekksander** [comment]
![Screenshot_20200501_140143](https://user-images.githubusercontent.com/3148302/80804055-4e2a7180-8bb4-11ea-874d-d847a0264b3a.png)
confirm

**Comment by maxoku** [comment]
It's strange, when I switch to conversation with video I see for a short moment something and then it's vanishes to show that small icon in a top-left corner. Well the first I see probably a shot from video and it changes then to thumbnail. But if it can't load it for some reason then maybe it should at least leave the video shot from begining?

**Comment by jtp755** [comment]
I have this problem as well. Ive tried changing a few of the settings but to no avail. Any ideas on a fix or work around?

**Comment by maxoku** [comment]
That's interesting. With enabled that option to **video autoplay** the thumbnails do show up indeed. And I haven't noticed that is autoplaying any video though. It seems that it works that way, but the name of setting is confusing. Maybe it should be called **video autoload**, though without it some videos can not load at all, so maybe rather **video load** generally.

**Comment by jtp755** [comment]
> That's interesting. With enabled that option to **video autoplay** the thumbnails do show up indeed. And I haven't noticed that is autoplaying any video though. It seems that it works that way, but the name of the setting is confusing. Maybe it should be called **video autoload**, though without it some videos can not load at all, so maybe rather **video load** generally.

Agreed. I dont get auto-playing videos at all but the thumbnails do load now with no issues.

**Comment by ggrelet** [comment]
Made a gif for illustration:

![vid](https://user-images.githubusercontent.com/10114131/84805867-304e8a00-b005-11ea-990e-9a2d9a654c5d.gif)
