### ISSUE TITLE
Can I run src on my website or on browser?

### ISSUE THREAD

**Issue by tradanghi1999** [sindresorhus/caprine#1350]
I am a new developer in Javascript. I have read your Caprine Typescript code and found it very interesting. May I use your code for developing an App on webrowser which may and can use some of your code. I am not sure if these Typescript code may run on browser / website. Thanks for your help and for your contribution.

**Comment by sindresorhus** [comment]
Sure. You're free to use any of the code here as long as you follow the MIT license.
