### ISSUE TITLE
Light and Dark mode not auto switching

### ISSUE THREAD

**Issue by duylhng** [sindresorhus/caprine#1352]
---

Caprine 2.45.0
Electron 8.2.1
darwin 19.4.0
Locale: en-GB

**Comment by MrGKanev** [comment]
@duylhng I don't think Caprine has an auto switcher for Light and Dark mode. It uses Messanger's version of it.

**Comment by Martus0** [comment]
It used to work well. I would say it has been broken for around 2 months.

**Comment by MrGKanev** [comment]
Deam, then it is my bad then. I checked in the readme just to be sure but didn't find it there either. I have never seen it in use, but I'm always using the dark theme.

**Comment by dusansimic** [comment]
Caprine doesn't have auto switching of dark/light theme. Both themes are supported however. You can change them with `View -> Dark Mode` option.
