### ISSUE TITLE
Is there any way to show icon in top bar with Gnome 3.30.2 and TopIcons Redux Extension?

### ISSUE THREAD

**Issue by assmblyreq** [sindresorhus/caprine#1366]
---

Caprine 2.46.0
Electron 8.2.5
linux 4.19.0-9-amd64
Locale: en-US

**Comment by dusansimic** [comment]
You sould be able to display tray icon using libappindicator and KStatusNotifierItem extension on Gnome. Electron usually works with libappindicator and KStatusNotifierItem shows the tray icon that uses libappindicator.
