### ISSUE TITLE
Receiving notification tones with lid closed on MBP 13 inch 2019

### ISSUE THREAD

**Issue by dannyziggy** [sindresorhus/caprine#1378]
Hi,

I have noticed for the last few weeks that if I leave Caprine open when shutting the lid to sleep my MBP 2019 I will still receive notification tones when I receive messages overnight. 

This has only happened over the last couple of weeks. If I "quit" caprine before shutting the lid, I receive no notifications. This is happening regularly unless I either quit the app or turn on Do Not Disturb on my MacBook.

I don't want to disable notifications as I find them useful, however the sounds in the middle of the night are very frustrating, as the MacBook should be sleeping.

Is this a bug or am I missing a setting?

Thanks
Dan
---

Caprine 2.47.0
Electron 9.0.1
darwin 19.5.0
Locale: en-GB

**Comment by bowiechen** [comment]
You could [schedule Do Not Disturb](https://support.apple.com/guide/mac-help/use-do-not-disturb-mchl999b7c1a/mac) to suppress notifications at night.

**Comment by dusansimic** [comment]
To me it doesn't look like a bug. If you can receive notifications with the lid closed, then Caprine is behaving properly. You should either disable the notifications at night, schedule Do not Disturb mode or close Caprine. There is no mechanism for automatic disabling of notifications during the night in Caprine or Messenger.
