### ISSUE TITLE
Better highlighting for current tab

### ISSUE THREAD

**Issue by adrianvoica** [sindresorhus/caprine#138]
First, great job!
Second, please make a better highlighting system for the current tab (current open user in the left pane).
I ended up sending some messages to a different user, since I couldn't quite visually distinguish between the currently selected and its neighboring tabs.

![image](https://cloud.githubusercontent.com/assets/3178286/20136765/468df2b2-a67f-11e6-84c0-6c3a97198f15.png)

Cheers!

**Comment by sindresorhus** [comment]
👍 Pull request welcome :)
