### ISSUE TITLE
Desktop/Menu Icon Problem

### ISSUE THREAD

**Issue by rahayon** [sindresorhus/caprine#1383]
I am using elementary os  5.1.5. I install caprine in my os. but icon does not showing my application menu.

Caprine 2.46.0
Electron 8.2.5
linux 5.3.0-59-generic
Locale: en-US

**Comment by mquevill** [comment]
This is a known problem. Please follow the steps in https://github.com/sindresorhus/caprine/issues/782#issuecomment-465383700 .
