### ISSUE TITLE
Feature request: add option to hide conversations avatars to make sidelist more compact

### ISSUE THREAD

**Issue by jose-d** [sindresorhus/caprine#1386]
as there is option "Narrow sidebar" which hides conversation names, it would be really cool to have similar option, which would hide conversation avatar/the round picture there and keep only textual description/conversation name, making the sidelist more compact.

![Screenshot_20200625_164253](https://user-images.githubusercontent.com/7630424/85742146-4ba34e80-b703-11ea-95f2-87ff056108f4.png)

**Comment by dusansimic** [comment]
We don't plan on adding any new substantial features. This could be done through Custom CSS option (File > Caprine Settings > Advanced > Custom Styles).
