### ISSUE TITLE
issue with bangla font

### ISSUE THREAD

**Issue by Abdunnafi** [sindresorhus/caprine#1390]
bangla fonts are shown broken. please add an option to change fonts in the app. please...

---

Caprine 2.47.0
Electron 9.0.3
linux 4.19.126-1-MANJARO
Locale: en-US

**Comment by whitecrownclown** [comment]
@Abdunnafi There is an option to add [custom styles](https://github.com/sindresorhus/caprine#custom-styles)

**Comment by dusansimic** [comment]
This seems to be resolved.

**Comment by Oymate** [comment]
@Abdunnafi have you checked if the fonts are correct? (removed bad fonts and installed noto fonts or such)

**Comment by Abdunnafi** [comment]
I haven't checked yet. Okay I'll try to check and inform you.

রবি, 12 সেপ্টেম্বর, 2021 4:52 PM তারিখে Oymate ***@***.***>
লিখেছেন:

**Comment by Abdunnafi** [comment]
I'm no longer using Manjaro. I'm using Linux mint now. But I think the
issue is fixed (I didn't check though).

সোম, 13 সেপ্টেম্বর, 2021 6:47 PM তারিখে Alif B ***@***.***>
লিখেছেন:
