### ISSUE TITLE
Running Caprine in Ubuntu 20.04 in WSL2

### ISSUE THREAD

**Issue by jdelano0310** [sindresorhus/caprine#1391]
Hello,

First and foremost this app is top-notch, I run Windows Insider build which is currently at build 20161, the Facebook Messenger app has stopped working under this (and the previous build). It gave me a good excuse to try using WSL 2 (Ubuntu 20.04) and running a Linux app to go through that process. I am using XLaunch, followed https://dannyda.com/2020/06/15/how-to-launch-gui-software-programs-from-windows-subsystem-for-linux-2-wsl2-how-to-convert-from-wsl-1-to-wsl-2/.

So it does run and works great, I do see these messages displayed in the terminal window. 
`Welcome to Ubuntu 20.04 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Jul 13 10:29:13 EDT 2020

  System load:  0.0                Processes:             8
  Usage of /:   0.8% of 250.98GB   Users logged in:       0
  Memory usage: 0%                 IPv4 address for eth0: 172.18.19.159
  Swap usage:   0%

78 updates can be installed immediately.
33 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update

This message is shown once once a day. To disable it please create the
/home/jon/.hushlogin file.
jon@Ryzen5:~$ caprine

(caprine:85): libappindicator-WARNING **: 10:29:19.261: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(caprine:85): LIBDBUSMENU-GLIB-WARNING **: 10:29:19.261: Unable to get session bus: Unknown or unsupported transport “dijon@Ryzen5:~$

(caprine:85): libnotify-WARNING **: 11:25:12.020: Failed to connect to proxy

(caprine:85): libnotify-WARNING **: 11:25:12.021: Failed to connect to proxy

(caprine:85): libnotify-WARNING **: 11:25:12.021: Failed to connect to proxy

(caprine:85): libnotify-WARNING **: 12:33:58.802: Failed to connect to proxy

(caprine:85): libnotify-WARNING **: 12:33:58.803: Failed to connect to proxy

(caprine:85): libnotify-WARNING **: 12:33:58.803: Failed to connect to proxy
^C
jon@Ryzen5:~$`

obviously this isn't the standard method to run your app, thought I'd post to see if this was anything that could be "fixed" or I could help checking into.

**Comment by BananaManCJ** [comment]
Why not just use the Windows binary?

**Comment by jdelano0310** [comment]
Yes, that was an option, I wanted to see how to use a Linux app in WSL2 and this was a good test. It worked perfectly fine. I just thought they'd like to see some info is all.

**Comment by BananaManCJ** [comment]
Since it's not officially supported, I'd wait for the official gui app support from Microsoft coming soon.

**Comment by dusansimic** [comment]
As I understand, WSL2 is not yet in regular Windows release and also I'm not sure if X windows is officially supported by WSL2 so until any of this is official, I'd like to close this issue. From the log that @jdelano0310 supplied, I can see that Caprine is showing some warnings about libnotify and libappindicator which are libraries for showing app indicator and notifications on desktop. Now as there is currently no real desktop with WSL2 from what I know, this is actually meant to happen. Also, I wouldn't recommend running Caprine from WSL2 since there is already a Windows build of Caprine.
