### ISSUE TITLE
Caprine doesn't start 

### ISSUE THREAD

**Issue by gaetan1903** [sindresorhus/caprine#1392]
My probleme is caprine requires internet connection, 

I don't have Internet but, i have only access on Facebook and Messenger. 

My request is, can you test the internet with facebook and messenger when you test the internet connection? 

Thank you.

**Comment by dusansimic** [comment]
If your internet access is restricted only to Facebook and Messenger by the internet provider, then Caprine should work since it is Messenger.com. Check if you can use Messenger.com, if not then you internet provider restricts you from using it.

**Comment by gaetan1903** [comment]
Yes, I can access messenger.com, 

But when I start caprine, it doesn't work , ..

If I start caprine with Internet connection not restricted in the first run,  it's work, even if i change my internet connection with the restricted. 


Sorry for bad english .

**Comment by dusansimic** [comment]
So if I understand correctly, you start caprine without restricted connection and Caprine loads but when you start with the restricted connection it doesn't load. Messenger.com loads with both restricted and unrestricted connection.

Does any window pop up when you start Caprine or is it just blank window? Does a window show saying "You appear to be offline."?

Also which version of Caprine are you running? If it's not v2.51.0, please update to the latest version.

**Comment by RDKRACZ** [comment]
No response so should be closed I think.

**Comment by gaetan1903** [comment]
I close it for the moment because, My Internet is not restricted anymore
