### ISSUE TITLE
The app has no icons

### ISSUE THREAD

**Issue by wildcard-f8** [sindresorhus/caprine#1395]
I installed the latest version and the app doesn't any icon. I'm on Ubuntu 20.04.
![Screenshot from 2020-08-03 13-17-38](https://user-images.githubusercontent.com/51791246/89148201-bd38ad00-d58b-11ea-846e-db38578be8cc.png)

**Comment by dusansimic** [comment]
@wildcard-f8 how did you install Caprine. With .deb package, snap or appimage?

**Comment by wildcard-f8** [comment]
@dusansimic I installed the .deb package.

**Comment by BananaManCJ** [comment]
This is a duplicate of #1213

**Comment by wildcard-f8** [comment]
awsome! it worked! thanks!
