### ISSUE TITLE
Caprine not loading on boot without internet

### ISSUE THREAD

**Issue by SamWWJD420** [sindresorhus/caprine#1398]
If I boot up manjaro kde with Caprine set to auto run on startup, my system boots before the internet is connected resulting in caprine showing a blank screen without an option to refresh

---

Caprine 2.48.0
Electron 9.1.0
linux 5.7.9-1-MANJARO
Locale: en-US

**Comment by vogu66** [comment]
You can use ctrl+R to reload, in the meanwhile.

Actually there was an issue like that a while ago, and it was solved (as far as I can tell) by having a dialog pop up and ask whether you wanted to wait for internet or stop Caprine. Now, on my computer, when Caprine starts before internet has started loading I see that dialog. When nm-applet shows that it is connecting or just connected I get the blank page and when it has connected already everything works normally.

**Comment by dusansimic** [comment]
As mentioned in the comment, this issue was fixed.

**Comment by vogu66** [comment]
Well, it doesn't work every time
