### ISSUE TITLE
Blank Window Upon Launch

### ISSUE THREAD

**Issue by pissywissygal** [sindresorhus/caprine#1402]
It launches just fine but doesn't load anything. Just a blank window. Killed the processes related to Caprine, restarted the computer, uninstalled/reinstalled. Can't seem to fix it with the usual approaches. 

---

Caprine 2.48.0
Electron 9.0.5
linux 5.4.0-42-generic
Locale: en-US

**Comment by dusansimic** [comment]
Duplicate of #1404
