### ISSUE TITLE
Refreshing to latest version of facebook messenger breaks app even across killing the app.

### ISSUE THREAD

**Issue by PaarthShah** [sindresorhus/caprine#1403]
1. Refreshed to latest version of messenger for web (as of the time of writing)
2. Window (besides menu bar) shows up as completely gray; notification sounds still come through accurately, but no elements are even invisibly clickable.

---

Caprine 2.48.0
Electron 9.0.5
win32 10.0.19041
Locale: en-US

**Comment by mmoore7** [comment]
I'm also getting a blank window with just menu options at the top.

Caprine 2.48.0-1
Electron 9.2.1-1
OS: Arch Linux
KERNEL: 5.8.5-arch1-1

**Comment by dusansimic** [comment]
Duplicate of #1404
