### ISSUE TITLE
Messenger.com moved

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1404]
Since messenger.com is now redirected to facebook.com/messages, this should be fixed asap. It's fairly easy to get rid of the banner but most of the custom css with be broken. I'd like to help out as much as I can.

@sindresorhus @CvX 
@mquevill, You've started responding to the issues about this. Are you interested in helping out?

**Comment by dusansimic** [comment]
It looks like messenger.com is not being redirected to facebook.com anymore. It could be just a temporary thing. However, this does not seem like an issue anymore. I'd still like to keep this open in case this happens for real at some point.

**Comment by RDKRACZ** [comment]
> I'd still like to keep this open in case this happens for real at some point.

Can't you then open a new issue? This one should be closed I think.
