### ISSUE TITLE
Caprine not loading

### ISSUE THREAD

**Issue by pep-prog** [sindresorhus/caprine#1406]
The application is not loading, it 's just a blank window. Please help to work with the problem. Here is my system information:

System:    Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop Mobo: N/A model: Intel X79 serial: <filter> UEFI: American Megatrends 
           v: 4.6.5 date: 07/17/2019 
CPU:       Topology: 6-Core model: Intel Xeon E5-2620 0 bits: 64 type: MT MCP arch: Sandy Bridge 
           rev: 7 L2 cache: 15.0 MiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 47893 
           Speed: 1197 MHz min/max: 1200/2500 MHz Core speeds (MHz): 1: 1197 2: 1197 3: 1197 
           4: 1197 5: 1197 6: 1197 7: 1197 8: 1197 9: 1197 10: 1197 11: 1197 12: 1197 
Graphics:  Device-1: NVIDIA GM107 [GeForce GTX 750 Ti] vendor: ASUSTeK driver: nvidia v: 440.95.01 
           bus ID: 03:00.0 chip ID: 10de:1380 
           Display: x11 server: X.Org 1.20.8 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1600x1200~60Hz 
           OpenGL: renderer: GeForce GTX 750 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 440.95.01 
           direct render: Yes 

---

Caprine 2.48.0
Electron 9.0.5
linux 5.4.0-42-generic
Locale: en-US

**Comment by dusansimic** [comment]
Is this issue still occurring? It might be related to a Messenger issue that used to happen in August.
