### ISSUE TITLE
Copy/Pasta image from Brave make caprine freeze

### ISSUE THREAD

**Issue by GThibaut** [sindresorhus/caprine#1409]
Everything is in the title, this behavior work well with firefox and chromium.

My environment:
Ubuntu 18.04.5 LTS
Brave: Version 1.13.82 Chromium: 85.0.4183.83

**Comment by CaptainYesz** [comment]
Yeah I have the same thing, I'm copy pasting something and then it's resulting in a huge memory leak in windows. I'm switching off Caprine for the time being using facebook's windows app since I paste a lot of images into my chats
