### ISSUE TITLE
What --minimize flag ? [masOS 10.12]

### ISSUE THREAD

**Issue by tristanlepachyderme** [sindresorhus/caprine#141]
<img width="541" alt="capture d ecran 2016-11-28 a 23 17 57" src="https://cloud.githubusercontent.com/assets/19967168/20696537/338446ca-b5c1-11e6-873a-0131f067b136.png">

Yeah I renamed the app in Messenger, but that's all.

And idk if the calls are supposed to work... but i understood that's a underlying problem.

Thanks for helping me !

(My problem might be super stupid)

**Comment by shihrer** [comment]
I think what's happening is `--minimize` is being read as an argument for the `open` command.  Try doing `open -a /Applications/Messenger.app --args --minimize`.

**Comment by tristanlepachyderme** [comment]
Thanks it's working !
