### ISSUE TITLE
Caprine becomes unresponsive 

### ISSUE THREAD

**Issue by robinsrk** [sindresorhus/caprine#1412]
Whenever I get a new message and I am on a different workspace, the caprine becomes unresponsive. when I switch to that workspace, caprine just stuck and doesn't do anything.

**Comment by tracker1** [comment]
What OS and Version(s) are you using?

If Linux, what Windowing system (Gnome, KDE, etc), platform (X11, Wayland) and OS/Distro are you using?

**Comment by robinsrk** [comment]
Arcolinux i3wm and bspwm. But switched to different distro now and there is no problem now

**Comment by dusansimic** [comment]
If there is no problem on your new distor/de the I will close this however, if this happens again, ping this issue.
