### ISSUE TITLE
Stuck on 2FA

### ISSUE THREAD

**Issue by laned130** [sindresorhus/caprine#1413]
I enter my login details, get the Please verify your account page, then get the Two-factor authentication page asking for a 6-digit code. I enter the code and click continue, which opens Facebook in a new Chrome tab, but leaves Caprine in the same place. File>Messenger Settings does nothing. File>Log Out does nothing. Restarting Caprine, reverts to the login page. Entering the wrong 2FA code, or leaving it blank, doesn't throw an error. Changed default browser to Firefox, restarted Caprine, went through the Caprine login again and clicked Continue 2FA, which launched FF instead, and then I had to login and go through 2FA in FF, but Caprine is still waiting.

**Comment by laned130** [comment]
I tried to bypass the issue by generating an App Password in Facebook, but Caprine is saying incorrect password. Generated a new one, and that's failed too. C&pasting password, so no typos. Verified paste into username box, so c&p working ok.
I'm assuming this is a totally separate issue?

**Comment by BLCRAFT-Gaming** [comment]
I put in the 2FA code and got the Facebook tab too. I solved this by clicking on the Facebook notif asking if I just signed in and saying that it was me, then quitting Caprine and then launching again. I only needed to put in the email and password this time, and then it brought me to messenger.

**Comment by laned130** [comment]
Yeh, I got that FB notification right at the beginning, but it didn't make any difference for me.

**Comment by laned130** [comment]
It has now worked but I don't know what was different. Didn't need to put a 2FA code into Caprine - just verified a 2FA notification in FB, restarted Caprine, logged in again and it worked.
