### ISSUE TITLE
YubiKey 2FA not working (probable cause: new window is opened in default system browser?)

### ISSUE THREAD

**Issue by jan-oratowski** [sindresorhus/caprine#1414]
YubiKey 2FA doesn't work
Snap:
When trying to login using snap installed version, there is no way to use 2FA (there will be a page saying to insert the YubiKey and press the button, but nothing will happen when inserting or pressing it).
If I click on "try different method", a new windows will open in my browser (Firefox), since I'm already logged in there, it will just show my Facebook.

Deb:
When trying to login using deb package, there will be a prompt requiring YubiKey and inserting it and pressing the button will work, I will get a message that the 2FA login was successful, however there is no way to get past it. Caprine will open new tab in Firefox displaying the Facebook page and nothing will happen in the Caprine window. When I restart Caprine, the whole process will be lost and I will have to start over.

---

Caprine 2.49.0
Electron 10.1.1
linux 5.4.0-47-generic
Locale: en-US

**Comment by alex-the-man** [comment]
https://github.com/sindresorhus/caprine/pull/1417
