### ISSUE TITLE
Login with 2FA doesn't work

### ISSUE THREAD

**Issue by gregorytopos** [sindresorhus/caprine#1415]
When trying to log in with 2FA enabled, the "Please verify your Facebook Account" page appears. Continuing and submitting the 2FA code gets you back to this page again, regardless of selecting save or don't save browser. After you are redirected, clicking on continue does nothing, Caprine is stuck on the "Please verify your Facebook Account" page. Quitting and restarting the application gets you back to the login page, starting the login progress over. Resetting app data or settings doesn't help.

This makes Caprine completely unusable as you're unable to login. Tried on 3 different devices, all running the same version of Arch Linux.

<hr></hr>

Caprine 2.48.0-1
Electron 9.2.1-1
Linux 5.8.10-arch1
Locale: en-US

**Comment by alex-the-man** [comment]
https://github.com/sindresorhus/caprine/pull/1417
