### ISSUE TITLE
Windows error message come saying "0xc00007b error-The app can't be opened".

### ISSUE THREAD

**Issue by ResearchTt** [sindresorhus/caprine#1418]
Since yesterday, it became impossible to open Caprine, and a Windows error message came saying
"0xc00007b error-The app can't be opened".
Therefore I uninstalled the 2.49 version, reinstalled it, same bug.
Then downloaded 2.48, same bug.
Then I tried today the new 2.50 Windows version, same bug.
Then I downloaded every version from 2.48 to 2.41, and I encountered the same bug.
Have been using Caprine over a year on my MSI Gaming Computer therefore I was surprised.
I downloaded the latest build of Windows (I use the Windows Home Insider Preview Dev Channel for fast release). When it first started bugging it was the build 2215, but it didn't change with build 2221).
For context, I don't run any antivirus apart of the built-in Windows Security. Should I tweak some of these parameters? Or is it unrelated? I've tried to disable almost of all the anti-virus features but nothing changes. My computer BIOS is normal, with virtualization enabled. Of course, I've tried restarting both the app and the computer but with no effect. Also to run it with "Administrator privilege" but to no avail 
Has anybody advice, like I'm genuinely flabbergasted_

**Comment by dusansimic** [comment]
Hi! Could you try deleting Caprine config folder (C:\Users\username\AppData\Caprine)? After that try reinstalling Caprine.

**Comment by ResearchTt** [comment]
Thanks very much for this precious answer @dusansimic , went to (C:\Users\username\AppData\Local\CaprineUpdater, deleted everything! Then downloaded Caprine 2.51 (latest build) and was able to see the new logo! After double clicking to launch it, got a prompt in black and yellow  *User account control*"Do you want to allow this app from an unknown publisher to make changes to your device". Clicked yes ofc. And then nothing happens, Caprine doesn't launch:(

**Comment by ResearchTt** [comment]
Then went to Control Panel, disabled the prompt. Caprine still can't launch.

**Comment by dusansimic** [comment]
I've just tried installing Caprine on Windows and it works with no problems. I'm running a regular version (not insiders build) however.

Could you try removing `C:\Users\username\AppData\Roaming\Caprine`? That folder contains Caprine configuration which could cause some trouble.
