### ISSUE TITLE
Different icons in different locations

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1419]
I noticed that the icon at `media/AppIcon.png` was updated in https://github.com/sindresorhus/caprine/commit/a4052b99c37f12fdc84149f907d23d947a76c8d6, but the icon at `build/icon.png` is still the old icon. Is there a reason for this? Or does the `build/` icon need to be updated?

**Comment by sindresorhus** [comment]
Weird. I was sure I updated that. It will be fixed next time I do a release, probably in some weeks.
