### ISSUE TITLE
Gtk-Message: Failed to load module "pantheon-filechooser-module"

### ISSUE THREAD

**Issue by TbhT** [sindresorhus/caprine#142]
It happens on **elementary OS 0.4 loki**, and i found some resons for that maybe. [THE LINK](http://elementaryos.stackexchange.com/questions/1859/gtk-message-failed-to-load-module-pantheon-filechooser-module).

> It is not possible to use the file chooser module with non-gtk3 apps. You will always see this warning message with those apps. When the module fails to load, you'll get the fallback gtk2 chooser.

**Comment by sindresorhus** [comment]
Looks like an Electron issue: https://github.com/electron/electron/issues
