### ISSUE TITLE
Messages repetedly becomes unread

### ISSUE THREAD

**Issue by victordahl** [sindresorhus/caprine#1422]
I keep having certain messages become unread. Only appears for 2-3 conversations at a time but not the same conversations all the time. I thought maby an FB update caused trouble with the blocking of seen indicators, but that didn't remove the issue. I have tried to uninstall/reinstall from fresh download. Problem started a week or two back maybe.

---

Caprine 2.50.0
Electron 10.1.1
win32 10.0.19041
Locale: en-US

**Comment by dusansimic** [comment]
Hi! Is there any way I could reproduce this. Is the message sent from other person in the conversation or is it sent by you? Do you use block seen indicator option or is it disabled?
