### ISSUE TITLE
App stuck on Facebook verification

### ISSUE THREAD

**Issue by NorbertBodziony** [sindresorhus/caprine#1423]
After passing 2FA app is stuck on "Please verify your facebook account" screen. Clicking continue does nothing. Restart of app forces reinserting credentials but again its stuck.
![image](https://user-images.githubusercontent.com/38857779/95574880-00047e80-0a2e-11eb-84ff-46d362920b6c.png)

**Comment by myknbani** [comment]
happens to me too.  workaround is to switch off 2FA, and turn it back on when Caprine has logged in

**Comment by tracker1** [comment]
Not sure if this is a bug with Caprine and/or Facebook, but got caught in this as well... I recently hit "log out of all sessions" as a security precaution after changing my passphrase, and enabling 2FA, this was the odd man out, so to speak.

**Comment by NorbertBodziony** [comment]
Ok thanks for tip. Actually it somehow passed this screen after couple of restarts. Weird.

**Comment by devanes** [comment]
I was able to get past continue to the 2FA screen. But after I did that, I just got back to this screen again.

**Comment by vanushwashere** [comment]
Same on my end on Kubuntu 20.04

**Comment by Jonathanr67** [comment]
Same problem on ubuntu with caprine.

**Comment by Jonathanr67** [comment]
fix issue

https://www.youtube.com/watch?v=yZ2Oma2Fzdk

**Comment by devanes** [comment]
I don't call that a fix. It's a workaround at best.

**Comment by tracker1** [comment]
I was able to get around the issue by temporarily disabling 2FA... though this isn't a great fix.

This seems to be related to FB either interfering with, or being less familiar with the Agent being used.  It *might* be worthwhile to just use a user agent that matches or closely aligns with Chrome.

**Comment by lpalgarvio** [comment]
same happening here
