### ISSUE TITLE
Taskbar icon displayed wrongly

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/caprine#1429]
After update taskbar icon (when running) is displayed wrongly, cut off mostly. Only a little from top is visible. When it's closed it's displayed normally, everywhere else too.
Win8.1 64-bit.

---

Caprine 2.51.0
Electron 10.1.3
win32 6.3.9600
Locale: pl

**Comment by artiste212** [comment]
The Mac icon looks different, depending on whether apps are viewed in list or icon mode in the Finder. Curious!

**Comment by maxoku** [comment]
Update. It's displayed wrongly if label is showed, it's okay if label is hidden.

**Comment by jonyroda97** [comment]
![image](https://user-images.githubusercontent.com/8282833/96792691-cf8bef80-13f2-11eb-8011-29e10fec9f01.png)
![image](https://user-images.githubusercontent.com/8282833/96792695-d61a6700-13f2-11eb-9b09-04c19426b49f.png)

Same here. Added images for better understanding of the problem.
Both images are from the taskbar

**Comment by jed84** [comment]
Not to mention, the icon has a wrong size and it doesnt look good on the white backhround and with cropped edges.
![obraz](https://user-images.githubusercontent.com/47121522/99286027-3654cb00-2830-11eb-91f6-1d170002a40c.png)

Can we revert to the previous icon?

**Comment by kacnje** [comment]
Same here. The icon is cropped.

**Comment by BloodRaven0** [comment]
I'd also love the old icon back.

**Comment by dusansimic** [comment]
Seems like this https://github.com/electron-userland/electron-builder/issues/2128#issuecomment-411797743 is a valid solution. Just explicitly specify the icon. I've tried this out and seems like it works. I'll write a pr for this.

**Comment by maxoku** [comment]
Will that be fixed in the next update? When we can expect it?

**Comment by dusansimic** [comment]
The pull request was merged 6 minutes ago. The fix will be available in the next update however we're not sure when it will roll out.

**Comment by maxoku** [comment]
Thank you for the answer.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/caprine/releases/tag/v2.51.2

**Comment by maxoku** [comment]
Thank you for the update, it's fixed now.
