### ISSUE TITLE
Can't access Messenger Settings

### ISSUE THREAD

**Issue by tomeczeka** [sindresorhus/caprine#1430]
Can't access Messenger settings either from the menu (File>Messenger Settings) or ctrl+comma. (not Caprine settings)

---

Caprine 2.51.0
Electron 10.1.3
win32 10.0.18363
Locale: en-GB

**Comment by mquevill** [comment]
Should be fixed with 6d1ff3511bf2969c09ac490c2ba501a49b333e71. Does this issue still exist?
