### ISSUE TITLE
I made an RPM baised of the Latest Version Using Alien, it works amazingly well

### ISSUE THREAD

**Issue by LinuxFanboy745** [sindresorhus/caprine#1433]
I made this RPM from the deb package using alien, it converted very well with all features working, I'll attach it below for those who want it. 
EDIT: Github won't let me attach the RPM so a link for it will be here: https://gofile.io/d/Dt4a24

**Comment by dusansimic** [comment]
I've made an RPM by adding it to the target list in package.json. It works well also, however, I don't think maintainers opinion on adding any more targets has changed. I'll work on making a repo for downloading Caprine on rpm based distros via yum or dnf but as mentioned in other issue https://github.com/sindresorhus/caprine/issues/1432, there will be not official rpm build.
