### ISSUE TITLE
Broken "About Caprine" dialogue on Linux deb package since v2.39.0

### ISSUE THREAD

**Issue by PeterDaveHello** [sindresorhus/caprine#1435]
The problem was discovered and reproduced, tested using **Linux deb package**, on **Linux Mint 20**, which is based on **Ubuntu 20.04 LTS**, the software package was downloaded from the [Releases page on GitHub](https://github.com/sindresorhus/caprine/releases).

Looks like the "About Caprine" dialogue from the "Help" menu is broken since **v2.39.0**, there is no meaningful information in the window. Screenshot captured as below for the reference.

I manually tested many versions before and after **v2.38.0**, and to the latest version, just confirmed this issue was introduced since v2.39.0, and I assume it's in all versions between this range, though I didn't see related changed mentioned in the Release/Changelog info.

v2.38.0
![image](https://user-images.githubusercontent.com/3691490/97996848-3a8deb00-1e23-11eb-9990-fb248679884b.png)

v2.39.0
![image](https://user-images.githubusercontent.com/3691490/97996922-52fe0580-1e23-11eb-9331-9dfe97975610.png)

.
.
.

v2.51.0
![image](https://user-images.githubusercontent.com/3691490/97997316-cb64c680-1e23-11eb-8bbc-6f063bedfd00.png)

Please feel free to let me know if there is any fix needed to be tested and verified and I'll be happy to help ;)

**Comment by dusansimic** [comment]
Hi! I've noticed that issue too. Thanks for reporting it!

The about dialogue is created using [electron-util](https://github.com/sindresorhus/electron-util) and it looks like there are problems with showing icon on Linux https://github.com/sindresorhus/electron-util/issues/19 and for some reason. Also, the name of the app is in lowercase for some weird reason.

This seems to be broken on all Linux builds.

**Comment by PeterDaveHello** [comment]
Yeah, I also noticed the app name became lowercase 😱 but I'm not sure if it's the same or related problem 😅

**Comment by dusansimic** [comment]
It seems like a lot of things are broken with electron-util. I'll look into it when I can but any help from anyone who can would be very welcome.

**Comment by vogu66** [comment]
On Manjaro I get this:

![image](https://user-images.githubusercontent.com/24728720/100322239-430db780-2fc4-11eb-8afc-22689f677415.png)

Not sure if it's because it's at Caprine 2.51 (Electron 10) and newer than the version of the bug, or just a different issue.
