### ISSUE TITLE
Clicking on notification doesn't open caprine

### ISSUE THREAD

**Issue by shohabmsk** [sindresorhus/caprine#1438]
When a message notification comes, clicking on it doesn't open caprine or the message. I have to launch caprine from taskbar icon. Running **Windows 8.1**. 
Irrelavent: Official desktop messenger is not working on 8.1(doesn't open), so caprine is the only solution.

**Comment by dusansimic** [comment]
This seems to be a duplicate of #644. I'll close here so we'll track the issue there.
