### ISSUE TITLE
System Tray Icon Always "Relevant" in KDE Plasma

### ISSUE THREAD

**Issue by praxishumanus** [sindresorhus/caprine#1441]
In KDE Plasma system tray there are four options for displaying an app icon.
1. Always show.
2. Shown when relevant.
3. Always hidden.
4. Disabled.

The expected behavior when using option 2 is that the icon will only show when the app has new activity e.g. a new message, an update is available, an installation is complete, etc.
Caprine does not follow this standard. Instead when set to option 2, the system tray icon is always present.

**Comment by dusansimic** [comment]
Is [this](https://userbase.kde.org/Plasma/SystemTray/en) the behaviour you're talking about?

**Comment by praxishumanus** [comment]
That page is antiquated due to being last updated in 2018. This image shows the current options.
![systemtraysettings](https://user-images.githubusercontent.com/74373318/99200919-e57c9e00-276d-11eb-8fc7-3be932f790e7.png)

**Comment by dusansimic** [comment]
Is there an up to date docs page where this behavior is described?
