### ISSUE TITLE
Cannot log in with Messenger account

### ISSUE THREAD

**Issue by Skoti** [sindresorhus/caprine#1442]
Until Nov 12 I could use Caprine with Messenger account.
Starting today it displays a facebook login only and when I try to log in with my phone numer I get:
> This account only works in Messenger
This phone number belongs to Messenger account, but not to Facebook account. In order to log in with the phone number, open Messenger.

Is this something that can be fixed on the Caprine side?

Caprine version: 2.51.0 (2.51.0.1889)

**Comment by mattnoir** [comment]
There might've been some changes on facebook side. I just had my account suspended for suspicious activity and had to update my password and review my posts and comments. Didn't click on any links. So the only options are - someone reported my account or there were some changes and Caprine was flagged as suspicious for this

**Comment by Skoti** [comment]
I think it was due to Caprine. My account was also suspended and a password update was required.

**Comment by Vortelf** [comment]
Updated my password by clearing the cookies, but what is the chance of this happening again if I continue to use Caprine?

**Comment by dusansimic** [comment]
I didn't have any problems in the past few days. Does this problem still occur? When opening, Caprine loads `https://messenger.com/login` which is a login page for Messenger.com. If that's not happening, are there any steps that I could use to reproduce this issue?

**Comment by Skoti** [comment]
Seems like Caprine was considered suspicious, after resetting the password via Messenger (it was not possible via Caprine), I could use Caprine without any issues.

**Comment by dusansimic** [comment]
This seemed to be a weird one time issue. If it occurs again without obvious reasons while using Caprine, please ping this issue. I'll close this for now.
