### ISSUE TITLE
Feature Request - Pinephone Version

### ISSUE THREAD

**Issue by Darklink999999** [sindresorhus/caprine#1443]
Hello, I would like to ask if there is a way to build caprine for Pinephone (ARM) or if there are any plans for a Pinephone version (Linux ARM version). Thank you very much.

**Comment by dusansimic** [comment]
First thing is that we don't really have a plan for adding any more build targets for Caprine. I'd be good idea to add more detailed build instructions on how to add other targets but we won't have official builds for other platforms. Also I'm not really sure how building apps works for Pinephone and if it's supported by electron-builder.

Second, Caprine is essentially a wrapper around Messenger.com with many features added. The thing is if the Messenger.com UI is not responsive and it isn't, then it won't look really good on the phone.

**Comment by Darklink999999** [comment]
> First thing is that we don't really have a plan for adding any more build targets for Caprine. I'd be good idea to add more detailed build instructions on how to add other targets but we won't have official builds for other platforms. Also I'm not really sure how building apps works for Pinephone and if it's supported by electron-builder.
> 
> Second, Caprine is essentially a wrapper around Messenger.com with many features added. The thing is if the Messenger.com UI is not responsive and it isn't, then it won't look really good on the phone.

Ok thank you very much. I think this would be useful for any Linux ARM machine (not just Pinephone) so If you could add the build instructions that would be great so maybe we could use it on other devices as well.

**Comment by pktiuk** [comment]
Pinephone would be an ideal target for this application.

**Comment by vlabo** [comment]
Pinephone can run AppImages so just fallowing the instructions from README you can build the app on your phone. And it works quite well.
I noticed some strange behaviour which can be caused from somewhere else. When pressing cyrillic letter "у" it scrolls up  and when pressing cyrillic "с" acts like Home button, instead of inserting the letters.

**Comment by pktiuk** [comment]
@vlabo  
Does long-term usage affect performance? (I am thinking about current memory issues https://github.com/sindresorhus/caprine/issues/1427)

**Comment by vlabo** [comment]
@pktiuk 
Can't really tell. I have been trying it for 1-2 days now and I'm closing the app when I'm not using it to save battery.
And also until the keyboard issue gets fixed its not really usable for me, I'm using only cyrillic alphabet to communicate.

**Comment by dusansimic** [comment]
AFAIK, we don't have a Pinephone and thus we can't resolve any issues related to that and also we do not officially support Pinephone.

On the topic of the keyboard issue @vlabo, if you are using the OS keybaord (not anything inside the app), then that issue is not related to Caprine and should be filed elsewhere.

**Comment by adamwawrzynski** [comment]
@vlabo Could You provide more detailed instructions how to build/run Caprine on PinePhone?

I'm using Mobian (20210516) and both running AppImage and `npm install & npm start` results in errors. First one gives:
`-bash: ./Caprine-2.53.0.AppImage: cannot execute binary file: Exec format error`, second one results in this error message:
```> caprine@2.53.0 start
> tsc && electron .

The futex facility returned an unexpected error code.
/home/mobian/caprine/node_modules/electron/dist/electron exited with signal SIGABRT
npm ERR! code 1
npm ERR! path /home/mobian/caprine
npm ERR! command failed
npm ERR! command sh -c tsc && electron .

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mobian/.npm/_logs/2021-05-23T08_12_18_891Z-debug.log
```
And log file:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.21.0
3 timing config:load:defaults Completed in 11ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 12ms
5 timing config:load:builtin Completed in 13ms
6 timing config:load:cli Completed in 12ms
7 timing config:load:env Completed in 3ms
8 timing config:load:file:/home/mobian/caprine/.npmrc Completed in 2ms
9 timing config:load:project Completed in 6ms
10 timing config:load:file:/home/mobian/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 4ms
17 timing config:load:setEnvs Completed in 6ms
18 timing config:load Completed in 64ms
19 verbose npm-session a528abd9c65dc588
20 timing npm:load Completed in 127ms
21 timing command:run-script Completed in 35597ms
22 timing command:start Completed in 35615ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:314:20)
23 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24 verbose pkgid caprine@2.53.0
25 verbose cwd /home/mobian/caprine
26 verbose Linux 5.10-sunxi64
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v12.21.0
29 verbose npm  v7.5.2
30 error code 1
31 error path /home/mobian/caprine
32 error command failed
33 error command sh -c tsc && electron .
34 verbose exit 1
```

**Comment by vlabo** [comment]
I don't remember exactly but I don't think I did anything different then you. Just run `npm install & npm start` command in the root folder of the repository also on mobian. This was 6 months ago so maybe something changed. You can try checking out some of the old releases and try on them.

The official AppImage is obviously not going to work because it is build for x86 platform
