### ISSUE TITLE
Caprine Error - Unable to Log In if FB Account Disabled, but Still Use Messenger

### ISSUE THREAD

**Issue by TripArtist** [sindresorhus/caprine#1446]
**Version 2.51.0**

If I enable my FB account and make my profile visible, it loads Caprine fine.
If I disable my FB account but leave Messenger active, I get the error below:

/Title Bar
Error

/Content
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Go Back

Facebook © 2019 · Help

![image](https://user-images.githubusercontent.com/74574866/99325242-c09a3080-282a-11eb-9f0e-173eaad99c1a.png)

**Comment by dusansimic** [comment]
Did you try restarting Caprine?

**Comment by TripArtist** [comment]
Absolutely.
Restarted Caprine
Restarted two laptops (Lenovo Legion Y520 and Lenovo Thinkpad T480)
Both machines are up to date with the latest version of Caprine and Windows 10 2004 Build

**Comment by dusansimic** [comment]
And can you login to messenger at all or you can't even login (while Facebook account is disabled)?

**Comment by TripArtist** [comment]
Yes. I can login to messenger using Messenger on my phone (Galaxy Note 20 Ultra) and previous phone (Galaxy S8) without any issue.

**Comment by dusansimic** [comment]
I meant on Caprine, can you log in with Caprine?

**Comment by TripArtist** [comment]
My apologies. I have re-enabled my FB account to test this. With FB enabled, it starts up, but provides no dark mode that I usually have.

When I click "Log Out", it will not allow me to log out. It leaves me at my dashboard.

I will do an uninstall with my FB account active, reinstall and see if I can log in as you are requesting.

**Comment by dusansimic** [comment]
Just to be clear, I wanted to know can you login to Caprine with Facebook account disabled since you should be able to do that.

**Comment by TripArtist** [comment]
Loud and clear.

If I have my FB enabled:
- I am unable to log out of Caprine to test. Log Out makes no change and still shows my chat dashboard.
- If I uninstall and reinstall Caprine (now to 2.51.1), it brings me in right away.

If I have my FB disabled:
- I get the error window I showed before and do not get the log in screen.

I re-enabled FB and removed Caprine as a trusted device.
![image](https://user-images.githubusercontent.com/74574866/99421967-d142b900-28b3-11eb-9230-96d6220e9f0a.png)

I then closed Caprine and opened it back up.
I got the login screen you asked about.
I disabled my FB before logging in to Caprine.
I was asked about authenticating my browser:
![image](https://user-images.githubusercontent.com/74574866/99422256-372f4080-28b4-11eb-83be-79e922c7e13e.png)

When I clicked "Save my Browser", it then shows the same error screen again:
![image](https://user-images.githubusercontent.com/74574866/99422438-6645b200-28b4-11eb-899a-8c4ea5caeef2.png)

----

Repeating the process, if I do this with my FB enabled, it logs in and I can see my dashboard, but it still does not allow dark mode (separate issue?)

**Comment by dusansimic** [comment]
Weird, I disabled my Facebook account and tried this and seems to be working perfectly. Try logging in with Facebook account disabled on [messenger.com](https://www.messenger.com/).

**Comment by TripArtist** [comment]
Good find!

It does not work on here either. Same error message. This must be an account issue for me.
![image](https://user-images.githubusercontent.com/74574866/99431859-3ef4e200-28c0-11eb-88fc-ab348dfa4f9e.png)


I will try to investigate with FB and re-open another ticket for Caprine if necessary.

Thank you for your time and thank you for all of your hard work. :)
