### ISSUE TITLE
Dark mode no longer works

### ISSUE THREAD

**Issue by baq-86** [sindresorhus/caprine#1447]
Something changed on messenger.com code and Caprine's dark mode no longer works :( 

---

Caprine 2.51.1
Electron 10.1.5
linux 4.15.0-123-generic
Locale: pl

**Comment by baq-86** [comment]
Actually, most of (or all) functionalities added by Caprine to messenger.com service no longer works...

**Comment by dusansimic** [comment]
Hi! Is there some error message displayed? Are you using custom styles? Is there a specific way that I can reproduce this since I'm running latest version of Caprine and I have no problems whatsoever. Also, how did you install Caprine?

**Comment by dusansimic** [comment]
Duplicate of #1439
