### ISSUE TITLE
Can't open images

### ISSUE THREAD

**Issue by mattnoir** [sindresorhus/caprine#1449]
The title says it all, I am not able to open images sent to or from me. No error message, no action. Just suddenly started happening.
Using 2.51.1
Windows 10 2004 version
Tried also on 2.51.0 after uninstalling 2.51.1

**Comment by dusansimic** [comment]
Usually Messenger loads thumbnails in chat but full size image when clicked. Sometimes, if internet is slow at that moment or there are some other bottlenecks, image loading takes a bit longer but there is no indication that image is being loaded. This is a problem in Messenger, not Caprine.

If this behavior still occurs (images never load, even after let to load for some time) please let me know.

**Comment by mattnoir** [comment]
No idea why it stopped working yesterday, I don't have slow internet and it worked fine in normal messenger and it actually never loaded, only the thumbnail in the chat.
It works now, so thank you for the reply, I know more now
