### ISSUE TITLE
New icon is lowres and buggy

### ISSUE THREAD

**Issue by BloodRaven0** [sindresorhus/caprine#1453]
![sshot-2020-11-23-18-44-39](https://user-images.githubusercontent.com/42444745/99990074-0f604100-2dbc-11eb-925b-1f18a49d59b8.png)
The new icon is capped at 38x38 pixels (a weird format, maybe the actual file has empty space around it and it's actually 48x48 or 64x64) on my desktop and won't scale further (signified by the box surrounding it). Also, it is strangely aliased and jaggy-looking. Official messenger app icon for comparison.
![sshot-2020-11-23-18-44-48](https://user-images.githubusercontent.com/42444745/99990079-0ff8d780-2dbc-11eb-8de3-8233e5b17819.png)
Also in the taskbar for some reason it is only rendered halfway. This was reported in another issue, so I'll just link it
https://github.com/sindresorhus/caprine/issues/1429

And the third problem is that with the new messenger UI, the tray icon always stays grey, no matter if you have unread messages.

P.S. I think the old icon without the white background looked better (and certainly worked better lol)
I'm using Windows 10 pro x64

**Comment by dusansimic** [comment]
> The new icon is capped at 38x38 pixels (a weird format, maybe the actual file has empty space around it and it's actually 48x48 or 64x64) on my desktop and won't scale further (signified by the box surrounding it). Also, it is strangely aliased and jaggy-looking. Official messenger app icon for comparison.

This due to the design of the icon. It has some transparent space around it. @CvX a simple solution would be making an icon for MacOS+Linux (the current one) and an icon for Windows (one without the whitespace).

> Also in the taskbar for some reason it is only rendered halfway. This was reported in another issue, so I'll just link it

We'll track that issue on the one you linked, not here.

> And the third problem is that with the new messenger UI, the tray icon always stays grey, no matter if you have unread messages.

This will also be tracked on this issue #1439, not here.

> I think the old icon without the white background looked better (and certainly worked better lol)

These issues are unrelated to the icon design, rather to the Windows feature of adding a dot when there is an unread message.
