### ISSUE TITLE
Use official Messenger dark mode

### ISSUE THREAD

**Issue by 1nikolas** [sindresorhus/caprine#1459]
Facebook actually has an official dark mode for Messenger. Take a look https://www.facebook.com/messages/ go there with dark mode on facebook.com. Then there is an iframe with a token (if you want to hide the facebook bar) and that iframe is messenger.com in dark mode. This even has stickers and gifs in dark mode and should be easy to implement

**Comment by dusansimic** [comment]
Thanks for pointing that out however Messenger is rolling out a major UI redesign which will break (and is already breaking) almost all of Caprine features. This is currently a priority for us, including fixing the current way we handle dark mode. We will look into this option in the future but in my opinion, we should wait for Messenger.com to get native dark mode instead of hacking around facebook.com/messages.

**Comment by MathPlayer** [comment]
Waiting might be in vain, messenger.com does not have dark mode for quite a lot of time now, compared to facebook.com/messages. Hopefully messenger.com will also get the facelift, yet I doubt that.
As an interesting fact, I asked some facebook employees how is their messenger.com looking, they do get the blueish dark mode as default.

**Comment by dexter93** [comment]
messenger.com at the moment is basically facebook.com/messages
While there is no button to trigger the dark mode you can easily do that by adding class "__fb-dark-mode" to the html
![image](https://user-images.githubusercontent.com/1979042/101846430-9271ed00-3b59-11eb-8c7b-4f43cad61180.png)

**Comment by DavidGereb** [comment]
as a workaround based on @dexter93 answer, trigger dev tools with F12 and add `__fb-dark-mode` the class to the html

**Comment by kazik56** [comment]
If there would be a way to execute JS on startup this would apply this class automatically:
`document.querySelector('html').classList.add('__fb-dark-mode')`

**Comment by dusansimic** [comment]
@dexter93 thanks for that awesome info. That seems to work on new design only since I have the old design of messenger and it doesn't work. I'd like to ask @CvX about this. If this actually works on the new design, we could ditch our dark mode altogether and just add patches that we'd like to the both dark mode and light mode. Of corse, we'll keep custom CSS feature there.

**Comment by dexter93** [comment]
> @dexter93 thanks for that awesome info. That seems to work on new design only since I have the old design of messenger and it doesn't work. I'd like to ask @CvX about this. If this actually works on the new design, we could ditch our dark mode altogether and just add patches that we'd like to the both dark mode and light mode. Of corse, we'll keep custom CSS feature there.

no probs. I got tired of eye bleeding white so I took a look deeper

you can pull my current dark mode enabled commits here and try it out
https://github.com/sindresorhus/caprine/issues/1452#issuecomment-742886261

**Comment by mzso** [comment]
[**@dusansimic**](https://github.com/dusansimic) commented on [2020. dec. 8. 12:10 CET](https://github.com/sindresorhus/caprine/issues/1459#issuecomment-740554907 "2020-12-08T11:10:57Z - Replied by Github Reply Comments"):
> Thanks for pointing that out however Messenger is rolling out a major UI redesign which will break (and is already breaking) almost all of Caprine features. This is currently a priority for us, including fixing the current way we handle dark mode. We will look into this option in the future but in my opinion, we should wait for Messenger.com to get native dark mode instead of hacking around facebook.com/messages.

Seems like that's already is happening. And dark mode is broken already.

**Comment by PrimozR** [comment]
FYI, I currently have a dark mode enabled messenger.com.

Is the features breaking problem including notifications in Caprine not working?

**Comment by dusansimic** [comment]
The fix is merged into master so dark mode will work on next Caprine update.
