### ISSUE TITLE
"Keep the conversation going" bar at top of interface

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#146]
Is there a means of having this advertisement from Facebook removed?

Currently using 1.7.0 on Ubuntu

![screenshot from 2016-12-09 20-57-19](https://cloud.githubusercontent.com/assets/3089512/21064327/18cc2502-be52-11e6-902d-1852b1fe567d.png)

**Comment by sindresorhus** [comment]
Yes, but you need to find the CSS class/ID for us as I don't see that banner. Clone this repo, `npm install`, and then `npm start`.

**Comment by jamesrobb** [comment]
Any chance it would have the same CSS class/ID as on messenger.com?

It'd be a lot easier to extract it that way (no cloning or installations required).

**Comment by sindresorhus** [comment]
Yes, would work too.

**Comment by jamesrobb** [comment]
The class appears to be "_s15"

I have also included a screenshot of my inspector panel in Firefox, so you could see its parent elements. The reason the bar is now teal-ish in color, rather than black, is because it is selected in the inspector.

![screenshot from 2016-12-10 00-42-13](https://cloud.githubusercontent.com/assets/3089512/21069435/b375e2f4-be71-11e6-96b9-39c12cac51cf.png)
