### ISSUE TITLE
[Linux] Notification sounds go through speakers even if headphones are plugged in

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/caprine#1462]
I am receiving notification sounds through my laptop speakers even though I have headphones plugged in (via USB) and the system sounds are routed through the headphones. For example, I was listening to music via headphones, but the notifications came out from my laptop's speakers _only_.

Caprine v2.51.2
Installed via .deb
Linux Mint 20 (kernel 5.8.0-31)

**Comment by mquevill** [comment]
This may be more of a system-wide issue (for me), since I have had Slack notifications do the same thing. I'll report back after I've done a little more digging…

**Comment by mquevill** [comment]
System sound settings were messed up internally. Changing output device and back fixed the issue for me.

**Comment by dusansimic** [comment]
@mquevill glad you got that fixed 😁. Sorry but I was quite busy and couldn't research the issue. That does tend to happen from time to time. Linux sound system is garbage and output/input devices even if they are detected rarely switch automatically. There are sound servers that work better but are more hardcore like [JACK](https://jackaudio.org/). I did try out these programs but never really used them over a longer period of time so I can't vouch for them but it might help you out 😁.
