### ISSUE TITLE
Dark mode and notifications stopped working

### ISSUE THREAD

**Issue by yrek150** [sindresorhus/caprine#1466]
today notifications and dark theme stopped working. There's no matter I use dark or white theme. only color of menu bar changes, rest of the window stays white.
About notifications, I can only hear notification sound, but there's no notofication banner anymore
---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.19042
Locale: pl

**Comment by dusansimic** [comment]
Duplicate of #1439
