### ISSUE TITLE
Block seen indicator didn't work.

### ISSUE THREAD

**Issue by Perzot** [sindresorhus/caprine#1469]
Anyone know how to fix this? Dark Mode has also stopped working.

**Comment by rhysinku** [comment]
same here dude i try downgrading it and still dont work

**Comment by dusansimic** [comment]
This is probably due to Messenger redesigning their UI. If those issues still occur once we fix those issues, please report it again.

**Comment by dusansimic** [comment]
Duplicate of #1439
