### ISSUE TITLE
Can't move the window

### ISSUE THREAD

**Issue by massayoshi** [sindresorhus/caprine#1471]
Updated to the latest version as of today (2.51.2) and I can't move the window only resize it. Also, tried removing the app completely and couldn't login back on facebook.

---
Caprine 2.51.2
Electron 10.1.5
darwin 18.7.0
Locale: en-GB

EDIT: Also on Mojave 10.14.6

**Comment by MaxiBerdy** [comment]
I have the exact same problem since today... I hope Facebook is not targeting this app in order to make users change to their own desktop app, it would be such a mean move 😢

**Comment by incace** [comment]
It's because there is no designated draggable space (ie. window frame). The only way to move the window currently is to click, hold and drag when you are at an edge, like top edge and your window resize icon shows. It's kind of annoying, but I also have a fix for this that I used on some Nativefier apps a while back. Let me track it down and I will post the fix shortly.

**Comment by jayonda** [comment]
Thanks for looking into this. 
Same thing happened to me a starting a few(?) days ago, OSX 10.14.6, Caprine 2.51.1.  All of a sudden Dark mode wasent working and lost the ability to drag the window. Resize is ok. 
I did a clean uninstall and installed 2.51.2 hoping there was some underlying change but same results.

**Comment by incace** [comment]
You can re-enable dark mode so to speak by adding the css from [this post](https://github.com/sindresorhus/caprine/issues/1452#issuecomment-742437765) to your custom.css file and reloading the app. I added a couple fixes below [here as well](https://github.com/sindresorhus/caprine/issues/1452#issuecomment-747189935), just append to the bottom.

**Comment by dusansimic** [comment]
This issue is fixed now.

**Comment by tuhuynh27** [comment]
It's happening again in the latest version

<img width="396" alt="image" src="https://user-images.githubusercontent.com/13906546/199405761-e911c9ba-5940-4fae-98a8-e974bd5a1648.png">
