### ISSUE TITLE
Caprine is not allowing me to sign in!

### ISSUE THREAD

**Issue by BunghezOvidiu37** [sindresorhus/caprine#1474]
I am not sure if there is a problem with Facebook (I am saying this because for the last 2 days, even my facebook app on android crashed on me multiple times. And I saw that many people have issues with this.)
I just want to let you know that there is a problem signing in on Caprine Messenger (AUR - Official Repo) - on Manjaro Gnome.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.8.18-1-MANJARO
Locale: en-US

**Comment by dusansimic** [comment]
Is there any message shown when you try to log in on Caprine or is there an error message? If the same thing occurs on Android app, then it's probably Facebook problem. There have been high number of reports for Messenger outage. If this problem doesn't occur anymore, please let me know.

**Comment by BunghezOvidiu37** [comment]
Thank your for reply! 
So on my Android phone, the Facebook messenger works fine now. 
On Caprine Messenger, it still this error:

#################################################

Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Go Back

Facebook © 2019 · Help

#################################################

So 3 days ago, I saw on www.Downdetector.com, that lots of users have issues with Facebook Messenger and Instagram. That was the day when my Caprine started to behave weird (did not sent messeges anymore and deleted my settings for black mode that I changed on the app. After that, I deteted the app and reinstall it = and it doesn't allow me to log in any longer. 
Thank you again for trying to help me!!

**Comment by dusansimic** [comment]
Try logging in on a web browser. Go to [messenger.com](https://messenger.com) and see if the result will be the same. If it is, there's a problem on Facebook side of things.

**Comment by BunghezOvidiu37** [comment]
I tried that right now!  Messenger.com on the web browser is working as usual. The only problem is on Caprine. (I tried the AUR version and the Snap Version = same issue)

**Comment by BunghezOvidiu37** [comment]
I tried on a different laptop with Manjaro. I have the same issue. Maybe it is a problem from Facebook. Hope it will solved soon! Thank you again for your help! Have a nice one!

**Comment by tarnas14** [comment]
it seems like something is wrong on facebook, because I tried logging into messenger from caprine, ferdi, rambox on arch and ubuntu and it doesn't work, but I can use it just fine from a browser...

**Comment by BunghezOvidiu37** [comment]
Same on mine! We'll see! Hopefully it will work soon!

**Comment by samuelfarkas** [comment]
Same problem on Manjaro :/ Any news?

**Comment by plonerp** [comment]
same problem on ubuntu

**Comment by samuelfarkas** [comment]
@BunghezOvidiu37 
So I figured it out. If you have 2FA active, it will not let you log in. You have to disable it. :/

**Comment by BunghezOvidiu37** [comment]
@samuelfarkas :1st_place_medal: 
Man, you saved me! I tried everything but this!  I disabled the 2FA, I logged back in Caprine, and enable the Authy again after that. It works so good now! Cant wait to go in Advanced Settings to make it Black Mode again! :+1: 

Guys @plonerp @tarnas14 , do the same, and it will work!
Thank you again!
