### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by ciprian-cucu** [sindresorhus/caprine#1480]
After filling in user and pass, I get:
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Go Back
---

Caprine 2.51.2
Electron 10.1.5
linux 4.15.0-123-generic
Locale: en-US

**Comment by MaxiM-PL** [comment]
Phew! So it's not just me then. I did a full (clean) reinstall and I still can't get in. Started 2-3 days ago.

Caprine 2.51.2, Win7 SP1 always up to date.

**Comment by zdunex25** [comment]
Yeah, same here.

**Comment by dusansimic** [comment]
Duplicate of #1474
