### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by lehoangan02school** [sindresorhus/caprine#1486]
![Screenshot from 2020-12-16 21-19-52](https://user-images.githubusercontent.com/76113074/102360330-769c9a00-3fe4-11eb-9e66-11425ef7dd21.png)

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-58-generic
Locale: en-US
It meant page is not available or removed.

**Comment by dusansimic** [comment]
How did this happen? What were you doing so this page was displayed? Did you click on the "Return to messenger.com" button and if you did, what happened?
