### ISSUE TITLE
The link you followed may be broken, or the page may have been removed.

### ISSUE THREAD

**Issue by martin666-alt** [sindresorhus/caprine#1505]
i logged in and i was redirected to "this page is not available" followed by the error "The link you followed may be broken, or the page may have been removed."
pls help

---

Caprine 2.51.2
Electron 10.1.5
linux 5.9.0-kali1-amd64
Locale: en-GB

**Comment by st-vit** [comment]
same

**Comment by Roadhog360** [comment]
I'm getting the same issue, can this be reopened?

**Comment by hoxton314** [comment]
same problem
