### ISSUE TITLE
Use native OS font stack

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#151]
This is what I'm currently using on a few sites, and it looks really in place on messenger as well:
```
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
text-rendering: optimizeLegibility !important;
font-feature-settings: "liga", "clig", "dlig", "kern";
```
I know that messenger.com is already using Segoe UI on windows, but San Franciso looks better as a UI font, and there are other platforms as well. Not to mention the shiny ligatures and the `optimizeLegibility`.

**Comment by sindresorhus** [comment]
No point in opening both an issue and PR. PRs are issues.

For reference: https://github.com/sindresorhus/caprine/pull/152

**Comment by ivancuric** [comment]
Sorry, forgot to close issue after deciding to make a PR
