### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by Ansari-Abdul** [sindresorhus/caprine#1510]
Clicking "View" in the Menu Bar on the Caprine window and then clicking "Dark Mode" (or pressing the shortcut keys CTRL+D) changes nothing. 

---

Caprine 2.51.2
Electron 11.1.1
linux 5.9.14-arch1-1
Locale: en-US

**Comment by tenpaiyomi** [comment]
Duplicate of #1439
