### ISSUE TITLE
dark mod and notification dont work 

### ISSUE THREAD

**Issue by samson510** [sindresorhus/caprine#1513]
dark mod dosent work  i try remove  caprine  and then remove folder in .config and dark mod only show on login screen after you type mail and password then goes agine in burning white  also sometimes notifications dosent work  when got message i hear sound of notification but dosent show me who sending message and what message is nothing except sound  and sometimes show 

Caprine 2.51.2
Electron 11.1.1
linux 5.9.14-arch1-1
Locale: en-US

**Comment by dusansimic** [comment]
Dark mode issue is fixed and will be available in the next updated. Notifications are already reported and are being worked on.
