### ISSUE TITLE
Dark Mode doesn't function in Ubuntu 20.04.1 

### ISSUE THREAD

**Issue by formidabilus** [sindresorhus/caprine#1515]
Dark Mode doesn't function in Ubuntu 20.04.1 

Steps to reproduce:
1. Open Caprin 2.51.2 or 2.51.1
2. Navigate to "View" and select "Dark Mode"

Expected result:
- Caprine should be displayed in Dark Mode;

Actual result:
- Caprine doesn't display in Dark Mode, but the "Dark Mode" option is checked (Doesn't work using CTRL + D, also).
---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-58-generic
Locale: en-US

**Comment by dusansimic** [comment]
This is fixed and pulled into master. It will be available on next release.
