### ISSUE TITLE
About Caprine appears behind of "always on top" caprine

### ISSUE THREAD

**Issue by kwongtn** [sindresorhus/caprine#1517]
Just opening Help -> About Caprine

![image](https://user-images.githubusercontent.com/5886584/103499675-d79cec80-4e83-11eb-8361-417435e46ae9.png)

---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.21277
Locale: en-US

**Comment by mquevill** [comment]
This also happens when switching emoji styles. The popup saying "Caprine needs to be restarted..." appears behind Caprine.
