### ISSUE TITLE
Menu bar doesn't work

### ISSUE THREAD

**Issue by MaciejWitkowskiDev** [sindresorhus/caprine#1519]
I installed Caprine using pacman -S caprine.
The menu bar does not seem to do anything. It doesn't even allow me to logout.
The native functions work - so I am able to go into Caprine settings, but the messenger website itself does not seem to respond to other options.

---

Caprine 2.51.2
Electron 11.1.0
linux 5.4.85-1-MANJARO
Locale: en-US

**Comment by dusansimic** [comment]
Duplicate of #1439

**Comment by charrion** [comment]
It's 2025 and this issue has obviously never even been looked at.
