### ISSUE TITLE
ctrl-tab not working

### ISSUE THREAD

**Issue by jantap** [sindresorhus/caprine#1520]
for some time now (probably since the last big messenger update but i'm not sure) the keybindings ctrl-tab and ctrl-shift-tab stopped working. I know that caprine lost a lot of features after that update,  but this (and the dark mode) are two of my favorite features. Is there anyway to fix them?

**Comment by dusansimic** [comment]
Work is in progress on chat switching shortcuts #1514 and dark mode fix is merged into master but it's not yet available in Caprine. On next update dark mode will be available and we hope that most of other features will be fixed to.
