### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by js-beaulieu** [sindresorhus/caprine#1526]
Ubuntu 20.04, both the deb and the snap exhibit the same behavior on my end.

Turning on Dark mode simply doesn't do anything once the chat is loaded up. The window background is dark on boot before the webpage shows, but once Messenger is loaded up, everything is still light. Tried most combinations of toggling then reloading or relaunching, nothing seems to do it. Nothing in devtools apart from a sourcemap warning. The `dark-mode` class seems to apply to the `html` element, but that's it, chat is still very much white.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.8.0-36-generic
Locale: en-GB

**Comment by dusansimic** [comment]
This issue is already fixed and the fix is merged into master. It will be available on the next version of Caprine.
