### ISSUE TITLE
Text Resizing and Dark Mode do not work

### ISSUE THREAD

**Issue by wadesmart** [sindresorhus/caprine#1530]
View > Increase or Decrease Text Size - does not work. Clicking the button does nothing. Holding CTL and - or + does nothing. 

View > Dark Mode or Ctl +D does nothing. App stays white. 

Tried logging out, restarting, reinstalling. 
Even on fresh install those things do not work.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-60-generic
Locale: en-US

**Comment by dusansimic** [comment]
Once #1514 this PR gets merged and a new release is made, these issues will be fixed. It's our plan to make a release with some fixes soon.
