### ISSUE TITLE
Show Unread Badge not working on new design

### ISSUE THREAD

**Issue by nguyenngocduy20** [sindresorhus/caprine#1536]
Preference > Show Unread Badge is not working on Caprine Version 2.52.0 (MacOS Big Sur 11.1)

**Comment by dotpointer** [comment]
Is the Unread Badge the same as or maybe related to the icon in the system tray? Because it has stopped working too, not showing any new messages, as mentioned in another issue.

**Comment by nguyenngocduy20** [comment]
It does not work on both menu bar & dock icon.

**Comment by dusansimic** [comment]
Hi! This issue is due to the redesign of the messenger website. It's being worked on however any help is very welcome!
