### ISSUE TITLE
Shortcuts not working on non US locale

### ISSUE THREAD

**Issue by goorkamateusz** [sindresorhus/caprine#1544]

**Comment by dusansimic** [comment]
Please update to the latest version of Caprine (v2.52).

**Comment by goorkamateusz** [comment]
I download caprine installer yesterday, so I've the lastes version...

On console I have this report:
![image](https://user-images.githubusercontent.com/52463898/106457643-8f2b1b80-648f-11eb-99be-42f3e1cb2040.png)

**Comment by dusansimic** [comment]
Okay, that's weird 😅. Could you please check these things:

1. Are you using shortcuts `Ctrl`+`+` and `Ctrl`+`-` for increasing and decreasing text size?
2. Are the menu options for increasing/decreasing text size working (View -> Increase/Decrease Text Size)?
3. Is there an error shown whenever you click those shortcuts or is there no error?
4. Do you have the Caprine window in focus?

I think that the error you see right now in the console is unrelated to this issue. It is referring to a Facebook url which means it's some issue regarding Facebooks code.

**Comment by goorkamateusz** [comment]
1. Not working;
2. Not working;
3. No reactions on shortcuts, and increasing in the menu;
4. Yes, I have.

I noticed that any options in `View` menu not working apart from `Dark mode`. Also:
- from Converation -> Insert GIF to -> Attach file;
- File -> New Conversation;
- and File -> Messenger Settings;

And any keyboard shurtcuts not working apart from some like `Ctrl`+`C` / `V`.

I suppose it's some sdependency problem...

**Comment by dusansimic** [comment]
Hi! The problem seems to be that we're targeting elements in the website using `aria-label` attributes whose values get changed when the locale gets changed. This could be fixed by using class names instead of aria labels. It will take some time to fix things but at least we know what is the solution.
