### ISSUE TITLE
Preference window opens on startup

### ISSUE THREAD

**Issue by stamatgeorge** [sindresorhus/caprine#1547]
When I open Caprine, I automatically get the preference windows. Is that normal? Any way to get rid of it?

![Screen Shot 2021-02-03 at 5 45 23 PM](https://user-images.githubusercontent.com/22395087/106819350-ad3b7c00-6647-11eb-858c-bae4aed66176.png)

---

Caprine 2.52.0
Electron 10.1.5
darwin 20.3.0
Locale: en-US

**Comment by dusansimic** [comment]
Hi! No that is not normal. I'd just like to clarify some things.

 * Does that happen every time when you open Caprine.
 * Does it happen while you're using the app, not just when you're starting it.
 * Did it happen on any of the previous versions of the app?
 * Is it possible that you by accident clicked the preferences shortcut, `Ctrl/Cmd`+`,`.

**Comment by meszarosdezso** [comment]
@dusansimic this happens to me also every time I start the app, only on first start (2.52.0, Catalina)
