### ISSUE TITLE
Reduce spacing between messages

### ISSUE THREAD

**Issue by Skoti** [sindresorhus/caprine#1548]
After updating to 2.51.2 the spacing between messages got too large. Please bring back the previous spacing. Now in 641 px window I only got 11 messages...
![caprine-spacing](https://user-images.githubusercontent.com/1700160/106869779-9c831880-66d0-11eb-9fc1-dcc8ac30ff7e.png)

**Comment by dusansimic** [comment]
This is not related to Caprine update, rather to Messenger website update. This could be handled through Custom Styles option.

**Comment by Skoti** [comment]
Custom Styles file only contains colour styles by default. Is there any list that includes styles that can be customised and with what parameters/units?
Could you point out for me the one that changes the spacing?

**Comment by dusansimic** [comment]
Custom Styles accept any CSS styles you want to add. It's basically adding styles to a website which will be applied to the user interface. You would wan't to change the margins of message bubbles so there would be more space. To see the html for the website, you can open DevTools (right click on empty space in the app and click Inspect Element menu option). Then you can find which elements you want to change styles for and use their CSS classes. The element you want to change styles for are located inside element `<div aria-label="Messages" role="grid">`. I hope this helps!

**Comment by Skoti** [comment]
Thanks for help!
I have managed to style it properly. Although "right click and inspect" didn't work for me, I have used "select an element in the page to inspect it" option from the dev tools - it was highlighting the hovered element and displaying it properties after clicking on it.
