### ISSUE TITLE
Dark Mode Turns off When Application is Closed

### ISSUE THREAD

**Issue by juniper409** [sindresorhus/caprine#1556]
Dark mode is turned on, but when I quit the application and restart it, the application goes back to light mode. When I go to the view menu to turn dark mode back on, I find that dark mode is still checked.

---

Caprine 2.52.0
Electron 10.1.5
linux 5.8.0-41-generic
Locale: en-US

**Comment by dusansimic** [comment]
Duplicate of #1525
