### ISSUE TITLE
Video in chat doesn't start

### ISSUE THREAD

**Issue by kacnje** [sindresorhus/caprine#1558]
I use Caprine 2.52.0. I noticed that the video which someone is sent to me, can't be played. I press the PLAY button in the middle of the video box, but nothing happens. 
Any idea?

**Comment by dusansimic** [comment]
Hi! Is the video you're talking about from Facebook or is it sent as a media message in Messenger? Does this happen for all videos or for just some of the videos? Are you able to play the video on messenger.com website and on Facebook website?

**Comment by kacnje** [comment]
I can't believe it. Now I see that problem also exists in Messenger. 
Can you close the issue? I'm sorry.

**Comment by dusansimic** [comment]
No problem, glad I could be of help 😁!
