### ISSUE TITLE
Refactor Github Actions for better automation

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1563]
Currently GitHub Actions is used as a CI/CD service for Caprine. There are some problems with it (every test on PR fails since build process is inside test job and there are no CSC keys for signing packages on forked repo and thus it fails). Also as far as I can tell, CI is not really automating snap deployment. Maintainer still needs to publish the snap manually by running `npm run release`. This could all be automated using Actions without the need for any manual intervention. Also there is an issue reported in #1554. Package hashes don't match the reported hash in yaml files which seems to be fixed by building each package on it's target OS.

I've already started testing out some configurations on my clone [dusansimic/caprine-playground](https://github.com/dusansimic/caprine-playground) and got to a point where everything seems to work fine. I'm using [Electron Builder Action](https://github.com/marketplace/actions/electron-builder-action) alongside [Snapcraft Action](https://github.com/marketplace/actions/snapcraft-action) which together allow me to build Caprine for all platforms and upload snap package to Snap Store. In addition I'm caching npm packages so the Action would be shorter. I haven't yet tested code signing but this seems to have good results since I don't have secrets set in my repo and the build still passes (just skips signing). That would mean PR won't fail anymore when there is no CSC secrets. I've also split the test job into two jobs: test and build. This would make it easier to understand which part of the testing pipeline failed (is it `npm test` or build process and on which platform it failed). I'm using the GitHub release workflow recommended by Electron Builder docs explained [here](https://www.electron.build/configuration/publish#recommended-github-releases-workflow). I don't know what current release process is but this seems to work without any problems for me.

I know this is adding more things to the build process but it automates every part of the deployment process. Maintainer just needs to create a draft release and once everything is ready, publish the release. It also fixes the problems on pull requests. There won't be any need for running `dist` script since it's run by Electron Builder Action and it would minimize the number of scripts in the package.json.

I'd like to hear some thoughts on this and recommendations for improving the process.

// @sindresorhus 
// @CvX

**Comment by sindresorhus** [comment]
Sure. PR welcome 👍🏻
