### ISSUE TITLE
Linux settings

### ISSUE THREAD

**Issue by MageJohn** [sindresorhus/caprine#157]
There doesn't seem to be any way to access settings on Linux. The indicator icon in the bar just has the option to toggle the window, and there are no settings buttons visible in the app. I was able to access some settings with the shortcut <ctrl>+<comma>, but that didn't include things like a logout button. Am I missing something, or is there something broken?

**Comment by sindresorhus** [comment]
It's right in the menubar:

<img width="517" alt="screen shot 2017-01-13 at 10 46 31" src="https://cloud.githubusercontent.com/assets/170270/21917850/98c4bfee-d97d-11e6-9cce-6232e27a4ab3.png">

<img width="502" alt="screen shot 2017-01-13 at 10 47 12" src="https://cloud.githubusercontent.com/assets/170270/21917855/ab0e1c36-d97d-11e6-9e4f-3622e27699ae.png">

**Comment by MageJohn** [comment]
Ah, that's the problem. That menu bar seems to be only visible in the Ubuntu Unity interface, where it's been integrated into the global panel at the top. Outside of that interface, though, the menubar is not visible. See for example Gnome 3, what I'm using currently: 

![Screenshot 1](https://cloud.githubusercontent.com/assets/3520558/21923669/52013f2a-d96d-11e6-8fb2-99284b34f71e.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/3520558/21923668/51fd57c0-d96d-11e6-835f-63b437746855.png)

So, am I still missing something?

**Comment by sindresorhus** [comment]
I don't know. That would be something to ask on the [Electron issue tracker](https://github.com/electron/electron/issues). I'm just using their API to set the menu.

**Comment by airtonix** [comment]
@MageJohn what's the keyboard shortcut for opening the settings? i think you missed that from your initial message.

**Comment by AydenMurray97** [comment]
@MageJohn have you tried using pressing Alt? I'm using Xubuntu which also didn't show the menu bar by default but using Alt toggles it

**Comment by MageJohn** [comment]
Hey guys, sorry I've been quiet. 

@airtonix Sorry, the shortcut is there, I just didn't make it very clear. It's <Ctrl+Comma>. 

@AydenMurray97 That works! That's great, thanks. Maybe this should be documented somewhere?
