### ISSUE TITLE
Caprine 2.52.0 \ 2 scroll bars on the right side.

### ISSUE THREAD

**Issue by igor-werry** [sindresorhus/caprine#1573]
Hi,
A very minor issue/question; 
Why there are 2 side scrollbars in the client? The left one works ok, to scroll the chats; the right one - it's inactive, no matter how I size the window. Thank you so much for an amazing client :)
![2021-03-04 11_22_28-Messenger](https://user-images.githubusercontent.com/51317962/109949823-20ceb880-7cdc-11eb-8cfc-e2a6d3665f98.png)

**Comment by dusansimic** [comment]
Hi @igor-werry! The fix for this is already merged into main branch (#1545) and will be available in the next update. The right scrollbar will be hidden and the left scrollbar will still be present. I'll close this issue since it's already fixed.
