### ISSUE TITLE
Native ✅ emoji is clipped

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/caprine#1575]
The actual emoji:

# ✅

As converted into an image for the Messenger UI:

<img alt="" width=30 src="https://user-images.githubusercontent.com/25517624/110222930-1828de80-7ea4-11eb-9c51-fdbc5fa36aac.png">

Note how it’s clipped at the bottom.

**Comment by lefterisgar** [comment]
Should be fixed now.
