### ISSUE TITLE
Suggestions for Cosmetic Changes

### ISSUE THREAD

**Issue by IRlyLikeBac0n** [sindresorhus/caprine#1576]
Hey! Just came across the project recently and am a huge fan. Just had some minor visual suggestions I wanted to give:

1. **Windows App Icon Too Small** - Not sure if this is just me, but it feels like the Windows taskbar icon is just slightly smaller than the "average" size. Here's some of the icons on my taskbar for reference:
![image](https://user-images.githubusercontent.com/62923135/110393570-c5346000-8038-11eb-8031-3f71a5617823.png)

2. **Messenger Rooms Icon Inconsistent Color Scheme in Dark Mode** - The other icons are white on gray, whereas this one keeps the black:
![image](https://user-images.githubusercontent.com/62923135/110393796-2fe59b80-8039-11eb-933a-a1026ff6233e.png)

3. **Other Chat UI Buttons Don't Scale with Text Size** - The new Windows 10 desktop Messenger app resizes everything proportionally (chat buttons along with text), so I figured this should be a consistent behavior on Caprine. For reference, these are the buttons I'm pointing towards:
![image](https://user-images.githubusercontent.com/62923135/110394056-c31ed100-8039-11eb-9645-f1477df96ab2.png)

Looking forward to new updates for the app!

**Comment by mquevill** [comment]
2. Is fixed as of #1572 (included in v2.52.1)
3. Not only is this true of the buttons, but also the input text box does not change sizes with the rest of the text!

**Comment by dusansimic** [comment]
Hi!

1. There have been a couple of reports about this. It would be good if we do something about this however I don't have software to open the `.sketch` file in which the original, editing version of the icon is stored. It would be good if we had the icon in a cross platform and open format (svg). I'll tag @sindresorhus for this.
2. As already mentioned, it's fixed.
3. If I recall correctly, that was the actual behavior of the text size feature on the old design. It did not increase or decrease the size of every ui element. I would however be useful if you're using a HiDPI monitor or display and you would like to make the ui a bit larger.

Thanks for the report!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/caprine/commit/fe4d1b9a6d9b6ab04adb5a9f7ff0cd2464d7ec5a

The icon cannot be properly represented in SVG.
