### ISSUE TITLE
npm install fails on Linux Mint

### ISSUE THREAD

**Issue by rudinskizvonimir** [sindresorhus/caprine#158]
OS:Linux Mint 18.1 Cinnamon
Description: When I run `npm install` the command fails.
It complains something about the electron package.
Error log:
`npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> electron@1.4.14 postinstall /home/zvonimir/Documents/caprine/node_modules/electron
> node install.js

sh: 1: node: not found
caprine@1.8.0 /home/zvonimir/Documents/caprine
├─┬ electron-config@0.2.1 
│ └─┬ conf@0.11.2 
│   ├── dot-prop@3.0.0 
│   ├── env-paths@0.3.1 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   └─┬ pkg-up@1.0.0 
│     └── find-up@1.1.2 
├─┬ electron-context-menu@0.8.0 
│ └── electron-is-dev@0.1.2 
├─┬ electron-debug@1.1.0 
│ └── electron-localshortcut@0.6.1 
├─┬ electron-dl@1.6.0 
│ ├── pupa@1.0.0 
│ └─┬ unused-filename@0.1.0 
│   ├── modify-filename@1.1.0 
│   └── path-exists@3.0.0 
├─┬ electron-packager@8.5.0 
│ ├─┬ asar@0.12.4 
│ │ ├── chromium-pickle-js@0.2.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├── cuint@0.2.2 
│ │ ├─┬ glob@6.0.4 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ ├── inherits@2.0.3 
│ │ │ ├── once@1.4.0 
│ │ │ └── path-is-absolute@1.0.1 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├─┬ mksnapshot@0.3.0 
│ │ │ ├─┬ decompress-zip@0.3.0 
│ │ │ │ ├─┬ binary@0.3.0 
│ │ │ │ │ ├── buffers@0.1.1 
│ │ │ │ │ └─┬ chainsaw@0.1.0 
│ │ │ │ │   └── traverse@0.3.9 
│ │ │ │ ├── mkpath@0.1.0 
│ │ │ │ ├─┬ nopt@3.0.6 
│ │ │ │ │ └── abbrev@1.0.9 
│ │ │ │ ├── q@1.4.1 
│ │ │ │ ├─┬ readable-stream@1.1.14 
│ │ │ │ │ └── isarray@0.0.1 
│ │ │ │ └─┬ touch@0.0.3 
│ │ │ │   └── nopt@1.0.10 
│ │ │ ├── fs-extra@0.26.7 
│ │ │ └─┬ request@2.55.0 
│ │ │   ├── aws-sign2@0.5.0 
│ │ │   ├─┬ bl@0.9.5 
│ │ │   │ └── readable-stream@1.0.34 
│ │ │   ├── caseless@0.9.0 
│ │ │   ├─┬ combined-stream@0.0.7 
│ │ │   │ └── delayed-stream@0.0.5 
│ │ │   ├── forever-agent@0.6.1 
│ │ │   ├─┬ form-data@0.2.0 
│ │ │   │ └── async@0.9.2 
│ │ │   ├─┬ har-validator@1.8.0 
│ │ │   │ └── bluebird@2.11.0 
│ │ │   ├─┬ hawk@2.3.1 
│ │ │   │ ├── boom@2.10.1 
│ │ │   │ ├── cryptiles@2.0.5 
│ │ │   │ ├── hoek@2.16.3 
│ │ │   │ └── sntp@1.0.9 
│ │ │   ├─┬ http-signature@0.10.1 
│ │ │   │ ├── asn1@0.1.11 
│ │ │   │ ├── assert-plus@0.1.5 
│ │ │   │ └── ctype@0.5.3 
│ │ │   ├── isstream@0.1.2 
│ │ │   ├── json-stringify-safe@5.0.1 
│ │ │   ├─┬ mime-types@2.0.14 
│ │ │   │ └── mime-db@1.12.0 
│ │ │   ├── node-uuid@1.4.7 
│ │ │   ├── oauth-sign@0.6.0 
│ │ │   ├── qs@2.4.2 
│ │ │   ├── stringstream@0.0.5 
│ │ │   ├─┬ tough-cookie@2.3.2 
│ │ │   │ └── punycode@1.4.1 
│ │ │   └── tunnel-agent@0.4.3 
│ │ └─┬ tmp@0.0.28 
│ │   └── os-tmpdir@1.0.2 
│ ├─┬ debug@2.6.0 
│ │ └── ms@0.7.2 
│ ├─┬ electron-download@3.2.0 
│ │ ├─┬ fs-extra@0.30.0 
│ │ │ └── rimraf@2.5.4 
│ │ ├── home-path@1.0.3 
│ │ ├─┬ nugget@2.0.1 
│ │ │ ├─┬ pretty-bytes@1.0.4 
│ │ │ │ └── get-stdin@4.0.1 
│ │ │ ├─┬ progress-stream@1.2.0 
│ │ │ │ ├── speedometer@0.1.4 
│ │ │ │ └─┬ through2@0.2.3 
│ │ │ │   └─┬ xtend@2.1.2 
│ │ │ │     └── object-keys@0.4.0 
│ │ │ ├─┬ request@2.79.0 
│ │ │ │ ├── aws-sign2@0.6.0 
│ │ │ │ ├── aws4@1.5.0 
│ │ │ │ ├── caseless@0.11.0 
│ │ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ │ └── delayed-stream@1.0.0 
│ │ │ │ ├── extend@3.0.0 
│ │ │ │ ├─┬ form-data@2.1.2 
│ │ │ │ │ └── asynckit@0.4.0 
│ │ │ │ ├── har-validator@2.0.6 
│ │ │ │ ├── hawk@3.1.3 
│ │ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ │ └── verror@1.3.6 
│ │ │ │ │ └─┬ sshpk@1.10.2 
│ │ │ │ │   ├── asn1@0.2.3 
│ │ │ │ │   ├── assert-plus@1.0.0 
│ │ │ │ │   ├── bcrypt-pbkdf@1.0.0 
│ │ │ │ │   ├─┬ dashdash@1.14.1 
│ │ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │ │   ├── ecc-jsbn@0.1.1 
│ │ │ │ │   ├─┬ getpass@0.1.6 
│ │ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │ │   ├── jodid25519@1.0.2 
│ │ │ │ │   ├── jsbn@0.1.0 
│ │ │ │ │   └── tweetnacl@0.14.5 
│ │ │ │ ├── is-typedarray@1.0.0 
│ │ │ │ ├─┬ mime-types@2.1.14 
│ │ │ │ │ └── mime-db@1.26.0 
│ │ │ │ ├── oauth-sign@0.8.2 
│ │ │ │ ├── qs@6.3.0 
│ │ │ │ └── uuid@3.0.1 
│ │ │ ├── single-line-log@1.1.2 
│ │ │ └── throttleit@0.0.2 
│ │ ├── path-exists@2.1.0 
│ │ ├─┬ rc@1.1.6 
│ │ │ ├── deep-extend@0.4.1 
│ │ │ ├── ini@1.3.4 
│ │ │ └── strip-json-comments@1.0.4 
│ │ └─┬ sumchecker@1.3.0 
│ │   └── es6-promise@4.0.5 
│ ├─┬ electron-osx-sign@0.4.2 
│ │ ├── bluebird@3.4.7 
│ │ ├── compare-version@0.1.2 
│ │ ├── isbinaryfile@3.0.2 
│ │ └─┬ tempfile@1.1.1 
│ │   └── uuid@2.0.3 
│ ├─┬ extract-zip@1.6.0 
│ │ ├─┬ concat-stream@1.5.0 
│ │ │ ├─┬ readable-stream@2.0.6 
│ │ │ │ ├── core-util-is@1.0.2 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ ├── process-nextick-args@1.0.7 
│ │ │ │ ├── string_decoder@0.10.31 
│ │ │ │ └── util-deprecate@1.0.2 
│ │ │ └── typedarray@0.0.6 
│ │ ├── debug@0.7.4 
│ │ ├─┬ mkdirp@0.5.0 
│ │ │ └── minimist@0.0.8 
│ │ └─┬ yauzl@2.4.1 
│ │   └─┬ fd-slicer@1.0.1 
│ │     └── pend@1.2.0 
│ ├─┬ fs-extra@1.0.0 
│ │ ├── graceful-fs@4.1.11 
│ │ ├── jsonfile@2.4.0 
│ │ └── klaw@1.3.1 
│ ├─┬ get-package-info@1.0.0 
│ │ ├── bluebird@3.4.7 
│ │ ├── lodash.get@4.4.2 
│ │ └─┬ read-pkg-up@2.0.0 
│ │   ├── find-up@2.1.0 
│ │   └─┬ read-pkg@2.0.0 
│ │     ├─┬ load-json-file@2.0.0 
│ │     │ └── strip-bom@3.0.0 
│ │     └── path-type@2.0.0 
│ ├─┬ plist@2.0.1 
│ │ ├── base64-js@1.1.2 
│ │ ├── xmlbuilder@8.2.2 
│ │ └── xmldom@0.1.27 
│ ├── rcedit@0.7.0 
│ ├── resolve@1.2.0 
│ ├── run-series@1.1.4 
│ ├─┬ sanitize-filename@1.6.1 
│ │ └─┬ truncate-utf8-bytes@1.0.2 
│ │   └── utf8-byte-length@1.0.4 
│ └── semver@5.3.0 
├── minimist@1.2.0 
└─┬ xo@0.17.1 
  ├── arrify@1.0.1 
  ├─┬ deep-assign@1.0.0 
  │ └── is-obj@1.0.1 
  ├─┬ eslint@3.13.1 
  │ ├─┬ babel-code-frame@6.20.0 
  │ │ └── js-tokens@2.0.0 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├── has-ansi@2.0.0 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├─┬ doctrine@1.5.0 
  │ │ └── isarray@1.0.0 
  │ ├─┬ escope@3.6.0 
  │ │ ├─┬ es6-map@0.1.4 
  │ │ │ ├── d@0.1.1 
  │ │ │ ├── es5-ext@0.10.12 
  │ │ │ ├── es6-iterator@2.0.0 
  │ │ │ ├── es6-set@0.1.4 
  │ │ │ ├── es6-symbol@3.1.0 
  │ │ │ └── event-emitter@0.3.4 
  │ │ ├── es6-weak-map@2.0.1 
  │ │ └─┬ esrecurse@4.1.0 
  │ │   └── estraverse@4.1.1 
  │ ├─┬ espree@3.3.2 
  │ │ ├── acorn@4.0.4 
  │ │ └─┬ acorn-jsx@3.0.1 
  │ │   └── acorn@3.3.0 
  │ ├── estraverse@4.2.0 
  │ ├── esutils@2.0.2 
  │ ├─┬ file-entry-cache@2.0.0 
  │ │ └─┬ flat-cache@1.2.2 
  │ │   ├── circular-json@0.3.1 
  │ │   ├─┬ del@2.2.2 
  │ │   │ ├── globby@5.0.0 
  │ │   │ ├── is-path-cwd@1.0.0 
  │ │   │ └─┬ is-path-in-cwd@1.0.0 
  │ │   │   └── is-path-inside@1.0.0 
  │ │   └── write@0.2.1 
  │ ├─┬ glob@7.1.1 
  │ │ └── fs.realpath@1.0.0 
  │ ├── globals@9.14.0 
  │ ├── ignore@3.2.0 
  │ ├── imurmurhash@0.1.4 
  │ ├─┬ inquirer@0.12.0 
  │ │ ├── ansi-regex@2.1.1 
  │ │ ├─┬ cli-cursor@1.0.2 
  │ │ │ └─┬ restore-cursor@1.0.1 
  │ │ │   ├── exit-hook@1.1.1 
  │ │ │   └── onetime@1.1.0 
  │ │ ├── cli-width@2.1.0 
  │ │ ├── figures@1.7.0 
  │ │ ├─┬ readline2@1.0.1 
  │ │ │ ├── code-point-at@1.1.0 
  │ │ │ ├─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │ └── number-is-nan@1.0.1 
  │ │ │ └── mute-stream@0.0.5 
  │ │ ├── run-async@0.1.0 
  │ │ ├── rx-lite@3.1.2 
  │ │ ├── string-width@1.0.2 
  │ │ └── through@2.3.8 
  │ ├─┬ is-my-json-valid@2.15.0 
  │ │ ├── generate-function@2.0.0 
  │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ └── is-property@1.0.2 
  │ │ ├── jsonpointer@4.0.1 
  │ │ └── xtend@4.0.1 
  │ ├─┬ is-resolvable@1.0.0 
  │ │ └── tryit@1.0.3 
  │ ├─┬ js-yaml@3.7.0 
  │ │ ├─┬ argparse@1.0.9 
  │ │ │ └── sprintf-js@1.0.3 
  │ │ └── esprima@2.7.3 
  │ ├─┬ json-stable-stringify@1.0.1 
  │ │ └── jsonify@0.0.0 
  │ ├─┬ levn@0.3.0 
  │ │ ├── prelude-ls@1.1.2 
  │ │ └── type-check@0.3.2 
  │ ├── lodash@4.17.4 
  │ ├── natural-compare@1.4.0 
  │ ├─┬ optionator@0.8.2 
  │ │ ├── deep-is@0.1.3 
  │ │ ├── fast-levenshtein@2.0.6 
  │ │ └── wordwrap@1.0.0 
  │ ├── path-is-inside@1.0.2 
  │ ├── pluralize@1.2.1 
  │ ├── progress@1.1.8 
  │ ├─┬ require-uncached@1.0.3 
  │ │ ├─┬ caller-path@0.1.0 
  │ │ │ └── callsites@0.2.0 
  │ │ └── resolve-from@1.0.1 
  │ ├─┬ shelljs@0.7.6 
  │ │ ├── interpret@1.0.1 
  │ │ └── rechoir@0.6.2 
  │ ├── strip-bom@3.0.0 
  │ ├── strip-json-comments@2.0.1 
  │ ├─┬ table@3.8.3 
  │ │ ├─┬ ajv@4.10.4 
  │ │ │ └── co@4.6.0 
  │ │ ├── ajv-keywords@1.5.0 
  │ │ ├── slice-ansi@0.0.4 
  │ │ └─┬ string-width@2.0.0 
  │ │   └── is-fullwidth-code-point@2.0.0 
  │ ├── text-table@0.2.0 
  │ └─┬ user-home@2.0.0 
  │   └── os-homedir@1.0.2 
  ├── eslint-config-xo@0.17.0 
  ├─┬ eslint-formatter-pretty@1.1.0 
  │ ├── ansi-escapes@1.4.0 
  │ ├── log-symbols@1.0.2 
  │ ├─┬ plur@2.1.2 
  │ │ └── irregular-plurals@1.2.0 
  │ └─┬ string-width@2.0.0 
  │   └── is-fullwidth-code-point@2.0.0 
  ├─┬ eslint-plugin-ava@3.1.1 
  │ ├─┬ deep-strict-equal@0.2.0 
  │ │ └─┬ core-assert@0.2.1 
  │ │   ├── buf-compare@1.0.1 
  │ │   └── is-error@2.2.1 
  │ ├── enhance-visitors@1.0.0 
  │ ├─┬ espurify@1.6.0 
  │ │ └── core-js@2.4.1 
  │ └── req-all@0.1.0 
  ├─┬ eslint-plugin-import@2.2.0 
  │ ├── builtin-modules@1.1.1 
  │ ├── contains-path@0.1.0 
  │ ├── eslint-import-resolver-node@0.2.3 
  │ ├─┬ eslint-module-utils@2.0.0 
  │ │ ├─┬ debug@2.2.0 
  │ │ │ └── ms@0.7.1 
  │ │ └── pkg-dir@1.0.0 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.1.0 
  │ └── lodash.cond@4.5.2 
  ├─┬ eslint-plugin-no-use-extend-native@0.3.12 
  │ ├─┬ is-get-set-prop@1.0.0 
  │ │ ├── get-set-props@0.1.0 
  │ │ └── lowercase-keys@1.0.0 
  │ ├─┬ is-js-type@2.0.0 
  │ │ └── js-types@1.0.0 
  │ ├─┬ is-obj-prop@1.0.0 
  │ │ └── obj-props@1.1.0 
  │ └─┬ is-proto-prop@1.0.0 
  │   └── proto-props@0.2.1 
  ├── eslint-plugin-promise@3.4.0 
  ├─┬ eslint-plugin-unicorn@1.0.0 
  │ ├── lodash.camelcase@4.3.0 
  │ ├── lodash.kebabcase@4.1.1 
  │ ├── lodash.snakecase@4.1.1 
  │ └── lodash.upperfirst@4.3.1 
  ├── get-stdin@5.0.1 
  ├─┬ globby@6.1.0 
  │ ├─┬ array-union@1.0.2 
  │ │ └── array-uniq@1.0.3 
  │ ├── object-assign@4.1.0 
  │ ├── pify@2.3.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├── has-flag@2.0.0 
  ├─┬ meow@3.7.0 
  │ ├─┬ camelcase-keys@2.1.0 
  │ │ └── camelcase@2.1.1 
  │ ├── decamelize@1.2.0 
  │ ├─┬ loud-rejection@1.6.0 
  │ │ ├─┬ currently-unhandled@0.4.1 
  │ │ │ └── array-find-index@1.0.2 
  │ │ └── signal-exit@3.0.2 
  │ ├── map-obj@1.0.1 
  │ ├─┬ normalize-package-data@2.3.5 
  │ │ ├── hosted-git-info@2.1.5 
  │ │ ├── is-builtin-module@1.0.0 
  │ │ └─┬ validate-npm-package-license@3.0.1 
  │ │   ├─┬ spdx-correct@1.0.2 
  │ │   │ └── spdx-license-ids@1.2.2 
  │ │   └── spdx-expression-parse@1.0.4 
  │ ├─┬ read-pkg-up@1.0.1 
  │ │ └─┬ read-pkg@1.1.0 
  │ │   ├─┬ load-json-file@1.1.0 
  │ │   │ └─┬ strip-bom@2.0.0 
  │ │   │   └── is-utf8@0.2.1 
  │ │   └── path-type@1.1.0 
  │ ├─┬ redent@1.0.0 
  │ │ ├── indent-string@2.1.0 
  │ │ └── strip-indent@1.0.1 
  │ └── trim-newlines@1.0.0 
  ├─┬ multimatch@2.1.0 
  │ └── array-differ@1.0.0 
  ├─┬ parse-gitignore@0.3.1 
  │ ├── array-unique@0.2.1 
  │ └─┬ is-glob@2.0.1 
  │   └── is-extglob@1.0.0 
  ├── path-exists@3.0.0 
  ├─┬ pkg-conf@2.0.0 
  │ ├─┬ find-up@2.1.0 
  │ │ └─┬ locate-path@2.0.0 
  │ │   ├─┬ p-locate@2.0.0 
  │ │   │ └── p-limit@1.1.0 
  │ │   └── path-exists@3.0.0 
  │ └─┬ load-json-file@2.0.0 
  │   ├─┬ parse-json@2.2.0 
  │   │ └─┬ error-ex@1.3.0 
  │   │   └── is-arrayish@0.2.1 
  │   └── strip-bom@3.0.0 
  ├── resolve-cwd@1.0.0 
  ├── resolve-from@2.0.0 
  ├─┬ update-notifier@1.0.3 
  │ ├─┬ boxen@0.6.0 
  │ │ ├── ansi-align@1.1.0 
  │ │ ├── cli-boxes@1.0.0 
  │ │ ├── filled-array@1.1.0 
  │ │ ├─┬ repeating@2.0.1 
  │ │ │ └── is-finite@1.0.2 
  │ │ └── widest-line@1.0.0 
  │ ├─┬ configstore@2.1.0 
  │ │ ├── osenv@0.1.4 
  │ │ ├── uuid@2.0.3 
  │ │ └─┬ write-file-atomic@1.3.1 
  │ │   └── slide@1.1.6 
  │ ├── is-npm@1.0.0 
  │ ├─┬ latest-version@2.0.0 
  │ │ └─┬ package-json@2.4.0 
  │ │   ├─┬ got@5.7.1 
  │ │   │ ├─┬ create-error-class@3.0.2 
  │ │   │ │ └── capture-stack-trace@1.0.0 
  │ │   │ ├─┬ duplexer2@0.1.4 
  │ │   │ │ └─┬ readable-stream@2.2.2 
  │ │   │ │   └── isarray@1.0.0 
  │ │   │ ├── is-redirect@1.0.0 
  │ │   │ ├── is-retry-allowed@1.1.0 
  │ │   │ ├── node-status-codes@1.0.0 
  │ │   │ ├─┬ read-all-stream@3.1.0 
  │ │   │ │ └─┬ readable-stream@2.2.2 
  │ │   │ │   └── isarray@1.0.0 
  │ │   │ ├─┬ readable-stream@2.2.2 
  │ │   │ │ ├── buffer-shims@1.0.0 
  │ │   │ │ └── isarray@1.0.0 
  │ │   │ ├── timed-out@3.1.3 
  │ │   │ ├── unzip-response@1.0.2 
  │ │   │ └─┬ url-parse-lax@1.0.0 
  │ │   │   └── prepend-http@1.0.4 
  │ │   ├── registry-auth-token@3.1.0 
  │ │   └── registry-url@3.1.0 
  │ ├── lazy-req@1.1.0 
  │ ├── semver-diff@2.1.0 
  │ └── xdg-basedir@2.0.0 
  └─┬ xo-init@0.4.0 
    ├─┬ execa@0.5.1 
    │ ├─┬ cross-spawn@4.0.2 
    │ │ ├─┬ lru-cache@4.0.2 
    │ │ │ ├── pseudomap@1.0.2 
    │ │ │ └── yallist@2.0.0 
    │ │ └─┬ which@1.2.12 
    │ │   └── isexe@1.1.2 
    │ ├── get-stream@2.3.1 
    │ ├── is-stream@1.1.0 
    │ ├─┬ npm-run-path@2.0.2 
    │ │ └── path-key@2.0.1 
    │ ├── p-finally@1.0.0 
    │ └── strip-eof@1.0.0 
    ├── path-exists@3.0.0 
    ├─┬ read-pkg-up@2.0.0 
    │ ├── find-up@2.1.0 
    │ └─┬ read-pkg@2.0.0 
    │   ├─┬ load-json-file@2.0.0 
    │   │ └── strip-bom@3.0.0 
    │   └── path-type@2.0.0 
    ├── the-argv@1.0.0 
    └─┬ write-pkg@2.0.0 
      └─┬ write-json-file@2.0.0 
        └─┬ sort-keys@1.1.2 
          └── is-plain-obj@1.1.0 

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.4.14 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.4.14 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zvonimir/Documents/caprine/npm-debug.log
`

**Comment by sindresorhus** [comment]
> sh: 1: node: not found

You need to have `node` install. This isn't really the place to get general Node.js support. I'd recommend following the install instructions in the readme: https://github.com/sindresorhus/caprine#linux
