### ISSUE TITLE
New problems since Caprine 2.52.1

### ISSUE THREAD

**Issue by czerwinski76** [sindresorhus/caprine#1580]
All my private messages history is gone.
Only 13 private chats/group discussion are still there.

Transfering pictures ou messages doesn't work anymore.

---

Caprine 2.52.1
Electron 10.1.5
win32 10.0.18363
Locale: fr

**Comment by dusansimic** [comment]
Hi @czerwinski76! I'm not sure what you mean by private messages. Could you clarify what that private messages mean, what is the feature called?

Also I'm not really sure what transferring pictures mean. Do you mean you can't send pictures anymore?

**Comment by jonsolberg** [comment]
+1

I also have problems with displaying images and reacting to messages (thumbs up on a message e.g.). Recently stopped working, but functioned before on 2.52.1.
