### ISSUE TITLE
Caprine issue

### ISSUE THREAD

**Issue by rmaillet62** [sindresorhus/caprine#1581]
Java script error keeps popping up but it doesn't say where or what js has the error so I can't tell you which script is causing the error. I'm not that good at writing java or I'd see if I could fix the issue.  good luck fixing the issue, I like caprine

---

Caprine 2.52.0
Electron 10.1.5
linux 5.4.0-66-generic
Locale: en-US

**Comment by rosoau** [comment]
I saw the same error. I deleted the local folder ~/.config/Caprine. Restart Caprine and it made a new folder. There were significant changes in the last few weeks. Some files in the old folder have different sizes to the new one's. That proves that it was necessary to "rejuvenate".

**Comment by dusansimic** [comment]
Seems fixed.
