### ISSUE TITLE
Auto update Caprine section

### ISSUE THREAD

**Issue by czerwinski76** [sindresorhus/caprine#1586]
Hi ! 
Could you add and option to choose if we want to auto update Caprine or not please ?

Note : 
I found a way to do that. You have to change Caprine's folder permissions.
Install Caprine 2.52.0 and don't open it (auto update happens at program startup).
Go here : C:\Users\NAME\AppData\Local\Programs\caprine
Configure folder's permission like that : Read & Execution

![13-03-2021_093022](https://user-images.githubusercontent.com/19463267/111024389-d84f8300-83de-11eb-9005-c2213a45144c.png)

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
