### ISSUE TITLE
Picture displaying does not work on 2.52.1

### ISSUE THREAD

**Issue by girardcarillo** [sindresorhus/caprine#1587]
Hi,
When I click on a picture someone sent me, it only displays a white screen, not the picture.
---

Caprine 2.52.1
Electron 10.1.5
linux 4.15.0-136-generic
Locale: fr

**Comment by jonsolberg** [comment]
Same here. 2.52.1 on Windows 10.

**Comment by MaxiBerdy** [comment]
Got the same problem
Caprine 2.52.1
macOS Mojave 10.14.6

**Comment by not-AMM** [comment]
Same

Caprine 2.52.1
Windows 10 20H2

The only messages I could find were: 
- `[Violation] Forced reflow while executing JavaScript took **ms`- 

![imagen](https://user-images.githubusercontent.com/43765089/111534930-25f52400-872e-11eb-950e-c3c61145405e.png)

- `[Violation] 'message' handler took <N>ms`

![imagen](https://user-images.githubusercontent.com/43765089/111535399-aae03d80-872e-11eb-8301-c9a924e3b33d.png)

**Comment by yardstudio** [comment]
Same problems
2.52.1
Win 10 Pro 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎18.‎07.‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0
