### ISSUE TITLE
Caprine can't download images in app, need to use browser

### ISSUE THREAD

**Issue by JoseRodrigues443** [sindresorhus/caprine#159]
First: Your app is great.

I use linux (arch), this app is great, but misses the possibility to download images with this app. Im obligated to open my browser (firefox/chrome/opera/etc) , login in messenger and then  download the file.

I dont know if that is suported in mac/windows

thanks for all the work

**Comment by sindresorhus** [comment]
That's weird. Both right-clicking an image and choosing "Save Image" and using the Facebook "Download" button works fine for me on macOS. I don't see why it would be different on Linux. Are you using the latest version of Caprine?

**Comment by JoseRodrigues443** [comment]
I use arch and debian.
Gnome graphic interface, so the file manager is nautilus.

When i click on the download, it simply does nothing, does not display an error message.

I guess that the error is on the default app list on the linux version. But i never programmed in electron.
In java the System library haves the ability to open the default apps for file, mail, browser etc.

Maybe the equivalent in electron is not formatted in the proper way for linux. But other linux electron  apps work fine and cane download well (ex: gitcraken, simplesNote, etc)

**Comment by sindresorhus** [comment]
I just tried it on Ubuntu, and both methods works perfectly there.
