### ISSUE TITLE
Caprine Still No Notification

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1595]
I  have alerted you already to the fact that the System Tray Icon is inert/dead. It does neither Audio or Visual Notification.
I Uninstalled and still no love. Tho't maybe a corrupted download.
2ndly I pointed out that Videos AutoPlay despite my configuration.
Thank you for your kind attention.

---

Caprine 2.52.2
Electron 10.1.5
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment]
Duplicate of #1593
