### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#1603]
Especially Electron.

We need to add https://github.com/electron/remote. We're not going to rewrite the app to not use it.

// @dusansimic

**Comment by dusansimic** [comment]
Okay, I'm going to take a look at it this weekend and start working on a pr. 👍🏻

**Comment by dusansimic** [comment]
Out of all dependencies, only `electron-util` still doesn't have Electron 12 support ([pr](https://github.com/sindresorhus/electron-util/issues/36)). Once that lands I'll write a pr for upgrading dependencies and uprading Electron to v12.
