### ISSUE TITLE
Update to new Messenger icon

### ISSUE THREAD

**Issue by spoorun** [sindresorhus/caprine#1612]
Messenger updated it's icon last October...

![image](https://user-images.githubusercontent.com/627140/115128672-3cb1c380-9fd7-11eb-8d4b-18ba7adeaf36.png)

**Comment by spoorun** [comment]
Also the current icon has a white background, which makes it smaller and less clear than others (for example using HiDPI desktop).

Having a just the logo with a transparent background via .svg or .png would be great

![caprine-logo-background](https://user-images.githubusercontent.com/627140/115128772-193b4880-9fd8-11eb-8a3b-2fd3487cf773.png)

**Comment by spoorun** [comment]
https://commons.wikimedia.org/wiki/File:Facebook_Messenger_logo_2020.svg

https://en.facebookbrand.com/messenger/assets/messenger/

**Comment by dusansimic** [comment]
Here's a design I slapped together in a few minutes. I'm not a designer of any sort and I'm not very skilled with designer software but the final result I think would look something like this. It's based on the Inkscape icon for Big Sur since it was the only svg icon with the Big Sur design I found. I think it would be good to make an icon in an open format that can be easily edited but it wont however use official apple template for the icon.

[Here](https://gitlab.com/inkscape/inkscape/-/blob/ee58965003ca1960c20d7da276c3774166c18d42/share/branding/inkscape-mac.svg) is the link to the Inkscape icon that I used to make this one.

![caprine](https://user-images.githubusercontent.com/12685466/115139403-048b9e80-a032-11eb-84c8-2ab6cc320004.png)

**Comment by lefterisgar** [comment]
> Here's a design I slapped together in a few minutes. I'm not a designer of any sort and I'm not very skilled with designer software but the final result I think would look something like this. It's based on the Inkscape icon for Big Sur since it was the only svg icon with the Big Sur design I found. I think it would be good to make an icon in an open format that can be easily edited but it wont however use official apple template for the icon.
> 
> [Here](https://gitlab.com/inkscape/inkscape/-/blob/ee58965003ca1960c20d7da276c3774166c18d42/share/branding/inkscape-mac.svg) is the link to the Inkscape icon that I used to make this one.
> 
> ![caprine](https://user-images.githubusercontent.com/12685466/115139403-048b9e80-a032-11eb-84c8-2ab6cc320004.png)

Great work @dusansimic! I think we need to keep this!

**Comment by dusansimic** [comment]
> it doesn't integrate nicely with anything that's not macOS.

That's true, but I've come to like this style of icons, even on non macOS systems. Right now to me, this icon just feels like a Caprine icon and not like a Facebook Messenger icon if you know what I mean. I'd probably prefer this style over removing the white background.

What could be considered however is figuring out how to use the icon without the white background only for the places where a small icon is displayed. That way the issue with a really small icon would be fixed while still staying with this icon.

**Comment by lefterisgar** [comment]
> That's true, but I've come to like this style of icons, even on non macOS systems. Right now to me, this icon just feels like a Caprine icon and not like a Facebook Messenger icon if you know what I mean. I'd probably prefer this style over removing the white background.
> 
> What could be considered however is figuring out how to use the icon without the white background only for the places where a small icon is displayed. That way the issue with a really small icon would be fixed while still staying with this icon.

Yes, I understand. This icon definitely has its places (Readme, About Submenu, wherever else an icon is required). However, for things like the taskbar and start menu, it doesn't look "native". I use KDE but I feel that even on Windows it's more or less the same.

**Comment by sindresorhus** [comment]
One small nit: The icon should be 1024x1024 on macOS, not 512x512: https://github.com/sindresorhus/caprine/commit/cf78ee346aeb22bbd32e7455d1d5e8df5a0808b2#diff-63060568de228a27ee114f3282f9f261fde979d2adca7c981bb3152aa0ddff08

**Comment by lefterisgar** [comment]
I see. The original one however is 512x512 and I'm not sure if upscaling it would look good.
