### ISSUE TITLE
How are packaged assets included in releases?

### ISSUE THREAD

**Issue by zeke** [sindresorhus/caprine#162]
Hey @sindresorhus, what tools / commands are you using to create new GitHub releases of Caprine that include the built assets in `/dist`?

**Comment by sindresorhus** [comment]
I currently upload the ZIP files manually. I have a local branch to switch to [`electron-builder`](https://github.com/electron-userland/electron-builder), but haven't had time to finish it up yet. When that's done, I intend to use this method: https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

**Comment by zeke** [comment]
Thanks

**Comment by sindresorhus** [comment]
I now have `electron-builder` setup with automatic building on Travis and AppVeyor.

**Comment by zeke** [comment]
Nice. Do you have this set up in any public repos?

**Comment by sindresorhus** [comment]
Uhm, this repo is public.
