### ISSUE TITLE
No message preview on notification and the trayicon not change the color

### ISSUE THREAD

**Issue by Mitezuss** [sindresorhus/caprine#1622]
So that. I am running on windows 7.

No getting preview of msg.
The trayicon not change from grey to blue (like old version, idk if is it a bug or change in new version)

**Comment by rafae667** [comment]
I also have the same problem and I'm using windows 10. 
No message preview on notification and also tried the trayicon and it doesn't change color also.

**Comment by dusansimic** [comment]
Duplicate of #1562
