### ISSUE TITLE
Delivery receipts are not being blocked

### ISSUE THREAD

**Issue by B1zguy** [sindresorhus/caprine#1623]
I've just confirmed read receipts are still being sent in Caprine. I haven't confirmed the other privacy options yet I image they're the same. Could this be related to the Messenger redesign fiasco?

Version 2.52.4 (2.52.4)
MacOS Catalina 10.15.6 (19G73)

Caprine was reinstalled just before checking the read receipts.

**Comment by dusansimic** [comment]
Hi @B1zguy! This is related to the Messenger redesign and I'm trying to make a solution for it but it seems that it would take some time. Currently there is another issue open for tracking this so all new information should be posted there #1503.

**Comment by B1zguy** [comment]
Not a problem, thanks for clarifying. Sorry for not seeing the thread!
