### ISSUE TITLE
Picture & transfer problem

### ISSUE THREAD

**Issue by czerwinski76** [sindresorhus/caprine#1624]
Caprine Version V2.52.4
W10 x64 1909.

Transfering pictures doesn't work on V2.52.4.

**Comment by dusansimic** [comment]
Please describe in more detail what exactly is the issue. What part of sending the picture doesn't work? Can you select the picture for sending? Is the picture not being sent or is there an error message?

**Comment by czerwinski76** [comment]
Ok on 2.54.0.
