### ISSUE TITLE
Killing the Caprine helper makes reopening the app impossible

### ISSUE THREAD

**Issue by fatso83** [sindresorhus/caprine#164]
1. Use the app as normal.
2. At a time when you observe huge amounts of cpu being used, open the macOS task manager and kill the Caprine helper process.
3. Close Caprine.
4. Reopen Caprine. 
5. Observe a black canvas.
6. Look in the Activity monitor and verify that the Caprine helper is also running.
7. Scratch head. 

Have restarted Caprine several times. No go.
-

Caprine 1.4.1
Electron 1.1.1
darwin x64 16.3.0

**Comment by superzazu** [comment]
Can't reproduce the bug with [Caprine 1.8.0](https://github.com/sindresorhus/caprine/releases/tag/1.8.0).

**Comment by fatso83** [comment]
Seems gone in 1.8. Closing.
