### ISSUE TITLE
bulk download of pictures

### ISSUE THREAD

**Issue by devkral** [sindresorhus/caprine#1644]
It would be really nice to have a bulk download mode.
Instead of clicking each image and download it via browser, it would be nice to select all pictures and videos you want and export it directly in a zip file.
Or at least open them parallel.

**Comment by dusansimic** [comment]
This would need to be implemented in the Messenger website itself so we can't do that from Caprine. Also we don't plan on adding new features.

You could use [this](https://www.facebook.com/help/212802592074644/?ref=u2u) Facebook feature for exporting all data in a specified time period if you have a lot of images/videos to download.
