### ISSUE TITLE
Image preview and forward not working

### ISSUE THREAD

**Issue by yardstudio** [sindresorhus/caprine#1645]
1. When clicked to sent photo, opening new - but blank window 
[https://i.imgur.com/1MeVuLg.png](https://i.imgur.com/1MeVuLg.png)
must pusch ESC to return 

2. Is impossible forward image, button forward doing none
[https://i.imgur.com/yKbvkvM.png
](https://i.imgur.com/yKbvkvM.png
)
---

Caprine 2.53.0
Electron 10.1.5
win32 10.0.19043
Locale: en-US

**Comment by NightMean** [comment]
Same issue here. I experience it also on videos. 
I realized that if you press CTRL+R to reload Caprine, you will see the actual preview. After that you can't push escape but you have to click the messenger icon in the top left corner to go back to messages.

**Comment by austinhuang0131** [comment]
Other overlay windows (inviting members, Messenger preferences...) don't work either.

Caprine 2.53.0, macOS 10.14.6 Mojave.

**Comment by jonsolberg** [comment]
Same issue(s) here. Caprine 2.53.0, Windows 10, win64, 19043.1023. Locale: sv-SE.

**Comment by czerwinski76** [comment]
Same issue for me.
Caprine 2.53.0, Windows 10 x64, 20H2 v19042.985. Locale: fr-FR.

**Comment by t510599** [comment]
I have same issue too.
Caprine 2.53.0, Windows 10 x64, 20H2 v19042.1052. Locale: zh-TW.

**Comment by j-mortara** [comment]
Same issue for me too.
Caprine 2.53.0, Electron 12.0.9, linux 5.12.8-arch1-1, Locale: en-US.
