### ISSUE TITLE
Tray Icon menu is useless.

### ISSUE THREAD

**Issue by megatog615** [sindresorhus/caprine#1647]
![IMG_20210601_183122180_HDR~2](https://user-images.githubusercontent.com/3255620/120398309-f5be2a00-c307-11eb-92d8-55121a912800.jpg)

Sorry for poor quality picture. My DE doesn't let me take screenshots while a menu is open like this.

Left-clicking the tray icon should just toggle the window. If the menu must be a part of the app, make it appear on right click. There's no reason for a menu like this to exist. If I want to quit the app I can do that in the app itself.

It's genuinely infuriating and useless.

**Comment by mquevill** [comment]
Unfortunately, there are limitations in the Linux implementation of Electron (see limitations here: https://www.electronjs.org/docs/api/tray) There have been many issues opened on Electron's repository pertaining to this, which would need to be resolved before Caprine can change this behavior. There have been some workarounds proposed, but nothing too promising.

**Comment by dusansimic** [comment]
Since this is already answered, I'll close this.
