### ISSUE TITLE
"Hide names and avatars" does not hide names and avatars in group chat members and active contacts list

### ISSUE THREAD

**Issue by joulev** [sindresorhus/caprine#1648]
Names and avatars in the "Chat members" section of a group chat are not blurred.

Neither are names and avatars from "Active contacts" section here

![image](https://user-images.githubusercontent.com/44609036/120575311-04612a00-c44b-11eb-8915-a2bfb96f86ea.png)

**Comment by dusansimic** [comment]
Thanks for reporting the issue! Regarding chat members not being blurred, that is intentional. We found it useful to at least have a list of group chat members visible and it could be hidden if the user wants to (click on the "Chat members" button which will close the section).
