### ISSUE TITLE
Make Linux notifications persistent

### ISSUE THREAD

**Issue by gabrc52** [sindresorhus/caprine#165]
Some desktop environments like GNOME or KDE have a notification list, but Caprine's notifications are discarded as unimportant. Would setting the priority make them appear on the notification list until they're dismissed?

**Comment by sindresorhus** [comment]
Caprine uses Web Notifications which have no options for setting priority.

If you feel strongly for this you could try opening an issue on Electron: https://github.com/electron/electron/issues
