### ISSUE TITLE
NO MODAL WINDOW

### ISSUE THREAD

**Issue by dachronos** [sindresorhus/caprine#1650]
I tried to enter a group chat where there was a blocked user and the modal window does not appear and I cannot do anything to enter 

---

Caprine 2.53.0
Electron 10.1.5
linux 4.9.0-15-amd64
Locale: es-419

**Comment by mquevill** [comment]
I believe this should be fixed by #1646, like some of the other issues listed there. It is a localization issue when not using English.

**Comment by mquevill** [comment]
I believe updating to the newest version (v2.54.0) should have fixed this. Can you confirm @dachronos ?
