### ISSUE TITLE
Can't remove sent messages.

### ISSUE THREAD

**Issue by mzso** [sindresorhus/caprine#1659]
Clicking on the "delete" or "share" options is not handled. Nothing happens.

**Comment by austinhuang0131** [comment]
Duplicate of #1645

**Comment by mquevill** [comment]
I believe this should be fixed in the newest version (v2.54.0). Can you confirm @mzso that it is fixed?

**Comment by mzso** [comment]
[**@mquevill**](https://github.com/mquevill) commented on [2021. aug. 9. 17:18 CEST](https://github.com/sindresorhus/caprine/issues/1659#issuecomment-895313115 "2021-08-09T15:18:51Z - Replied by Github Reply Comments"):
> I believe this should be fixed in the newest version (v2.54.0). Can you confirm [@mzso](https://github.com/mzso) that it is fixed?

Yes.
