### ISSUE TITLE
Font glitch

### ISSUE THREAD

**Issue by GuillaumeSTEIN** [sindresorhus/caprine#166]
some letters have weird behaviours:
[shared link](http://i.imgur.com/31vqP9H.png)
[my text](http://i.imgur.com/L5jJntY.png)
[someone else text](http://i.imgur.com/nxNSRQk.png)

It's only for the "st" letters combination.
If I inspect and change font-familly, this solve my issue.
[explaination gif](http://i.imgur.com/kX1dPf2.gifv)

Caprine 1.8.0
Electron 1.4.15
linux x64 4.4.52-1-lts

Should we create a preference input for used font ? should I change my installed font (but everyone will have to do that)?

Let me know if you need more infos.
Thank you

**Comment by sindresorhus** [comment]
// @ivancuric

**Comment by ivancuric** [comment]
Ah, it's the discretionary ligatures from https://github.com/sindresorhus/caprine/commit/34badc76c6408691069ea4b731f260045ca5c569

I think I should remove both `dlig` and `clig`.

**Comment by GuillaumeSTEIN** [comment]
removing dlig indeed remove the bug.
but clig doesn't change anything to me
