### ISSUE TITLE
Title bar is always in dark mode

### ISSUE THREAD

**Issue by joulev** [sindresorhus/caprine#1660]
![image](https://user-images.githubusercontent.com/44609036/122702342-69a18180-d279-11eb-989d-0e6295305a69.png)

In Ubuntu 20.04 (at least), when switching to light mode, the title bar is still in dark mode.

For reference, in the screenshot, VSCode (another Electron app I frequently use) can change its (native) title bar colour according to the system theme.

---

Caprine 2.53.0
Electron 10.1.5
linux 5.8.0-55-generic
Locale: en-US

**Comment by joulev** [comment]
For some reasons it works now, probably it is due to a problem with my theme.

**Comment by mquevill** [comment]
The "follow system appearance" option should be available for all platforms in the next release (added in #1637). Hopefully that should refine some of these options. But please raise an issue if you still have troubles once those changes go live (sometime after 2.53.0).
