### ISSUE TITLE
Add option "open image in browser" or "copy image link" for images

### ISSUE THREAD

**Issue by joulev** [sindresorhus/caprine#1662]
I usually have to open images in a new browser tab to view it in the original scale and dimension.

Currently, in Caprine, every time I need to do so, I have to drag and drop the image from the Caprine window to the browser window.

The current dropdown from right click on images only have one option: to copy the image to clipboard. It would be great if other (imo more useful) options, such as "Copy image _link_" and "Open image in browser tab", are also available.

---

Caprine 2.53.0
Electron 10.1.5
linux 5.8.0-59-generic
Locale: en-US

**Comment by wmolicki** [comment]
When I click the image, app window just goes blank, and I have to click "New conversation" from the menu to navigate back

Caprine 2.53.0-1
system: 5.10.42-1-MANJARO

**Comment by Kristof22** [comment]
https://www.facebook.com/sara.kotlarova.77

**Comment by Kristof22** [comment]
https://www.facebook.com/sara.kotlarova.77

**Comment by Kristof22** [comment]
> When I click the image, app window just goes blank, and I have to click "New conversation" from the menu to navigate back
> 
> Caprine 2.53.0-1
> system: 5.10.42-1-MANJARO
