### ISSUE TITLE
Cannot get past Accept cookies from "Messenger on this browser?"

### ISSUE THREAD

**Issue by mnissov** [sindresorhus/caprine#1667]
Installed caprine by
```bash
sudo pacman -S caprine
```

Opening the app prompt a "Accept cookies from Messenger on this browser?" window, clicking on "accept all" results in the window disappearing, and then reappearing a second later, so completely locking my out of logging in.

```bash
$ pacman -Ss caprine
community/caprine 2.53.0-1 [installed]
    Elegant Facebook Messenger desktop app
```

**Comment by mnicky** [comment]
I have the same issue, have you managed to resolve it somehow?

**Comment by rwilkin** [comment]
I am also having this problem I'm on Debian 10
