### ISSUE TITLE
How to increase zoom

### ISSUE THREAD

**Issue by hi-flyer** [sindresorhus/caprine#1668]
I am on a 4k 15" screen. I have increased the zoom level (i.e. text size) to max. Is there a way to increase it more?
I am using Caprine-2.53.0.AppImage on Ubuntu 20.04
Thanks

**Comment by tpchuckles** [comment]
Same story here. Ubuntu 20.04 on a Macbook16,2 (13.3" screen, 2560x1600). I can mess with my dpi settings to "trick" it, but that's going to mess with the rest of the system

**Comment by mquevill** [comment]
For HiDPI systems, you can pass the `--force-device-scale-factor=2` option for however you usually call Caprine (or any Electron-based apps). You can mess with this number however you want, but I would recommend starting at 1.5 or 2. This will zoom the _entire_ app, not just the conversation text, as the built-in zoom feature does.

For instance, you can edit the desktop file (usually at `/usr/share/applications/caprine.desktop`) to include this flag.

```diff
 [Desktop Entry]
 Name=Caprine
-Exec=/opt/Caprine/caprine %U
+Exec=/opt/Caprine/caprine --force-device-scale-factor=2 %U
 Terminal=false
 Type=Application
 Icon=caprine
 StartupWMClass=Caprine
 Comment=Caprine is an unofficial and privacy focused Facebook Messenger app with many useful features.
 Categories=Network;Chat;
```

[This configuration works on my Linux Mint 20.2 (Ubuntu 20.04) system.]

**Comment by hi-flyer** [comment]
maybe that will work but found a better solution. the Caprine-2.53.0.AppImage creates a file in ~/.config/Caprins/config.json - in that file there is a "zoomFactor" which I set to 1.75 which does the trick for me. Thanks for the suggestion as it triggered me to go look for the correct solution for me.

**Comment by tpchuckles** [comment]
Very nice, both of you. 

worth noting: if you go with editing the .desktop launcher file, this will adjust the size of the text as you're writing it, whereas editing the config file's zoomFactor will not. (using the latter solution, i still struggled to read the text i was writing)

**Comment by mquevill** [comment]
@hi-flyer Yes, setting it manually can work, so I'm glad you were able to find that. The `"zoomFactor"` entry in the config.json file is limited to 0.7 to 1.6 via the shortcut key combination, so if you zoom out from the shortcut (ctrl+-), you will not be able to get back to 1.75 without setting it manually in config.json.

**Comment by tpchuckles** [comment]
One more comment: this is a qt app, so if you're struggling with zoom across all qt apps (like I was), there's a couple environment variables you can set (https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6), eg, I have QT_SCALE_FACTOR=2. 

correcting my system-wide scaling and font sizes, then doing this, took care of the funny discrepencies between in-app font size and menu text font size.
