### ISSUE TITLE
Zoom in/out only zooms message panel

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1678]
Expected behavior: zooming in and out via View -> Increase/Decrease Text Size should zoom all parts of the window, including the left conversation list, middle message text, bottom center message text input box, and right chat settings panels.

Actual behavior: zooming in and out via View ->Increase/Decrease Text Size only zooms the middle message text panel.

Windows 7
Caprine 2.54.0

![2021-08-02_204708](https://user-images.githubusercontent.com/43397938/127954755-1d0ff7d0-ccee-49b0-b365-9c1fdd52d19f.png)

**Comment by dusansimic** [comment]
Actually the designed behavior is to zoom only the messages box, it's not expected to zoom anything else.
