### ISSUE TITLE
Sometimes button to exit photo theatre mode is a messenger logo instead of an X

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1680]
Steps to reproduce:

- open Caprine
- go to a message where someone sent a photo
- click on the photo
- look at icon on the top left. it's normally an X to close/exit theatre mode. sometimes it will be a messenger logo instead of an X. when it is a messenger logo, it is unintuitive that this is the way to exit theatre mode.

Doesn't happen every time. Only very occasionally. If I can get it to do it again I'll add a screenshot.

**Comment by dusansimic** [comment]
This seems to be a problem in the Messenger website. I personally have not come across this problem. If the issue persists, please send a screenshot of the issue. Until then, I'll close the issue.

**Comment by RedDragonWebDesign** [comment]
Screenshot, as requested

![image](https://user-images.githubusercontent.com/43397938/130539788-66258d9a-9048-4454-9783-27c60d530c2b.png)

**Comment by RedDragonWebDesign** [comment]
Looks like the icon also disappears completely sometimes. That happened to me today.
