### ISSUE TITLE
Is it possible to add 2 shortcuts to  archive & delete chat?

### ISSUE THREAD

**Issue by stamatgeorge** [sindresorhus/caprine#1682]
Is it possible to add 2 shortcuts to 
1) archive chat
2) delete chat

**Comment by dusansimic** [comment]
They are already available:

Hide/Archive conversation      | <kbd>Command/Control</kbd> <kbd>Shift</kbd> <kbd>h</kbd>
Delete conversation    | <kbd>Command/Control</kbd> <kbd>Shift</kbd> <kbd>d</kbd>

This is copied from the [keyboard shortcuts section](https://github.com/sindresorhus/caprine#keyboard-shortcuts) in the readme.
