### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1689]
I've created [Flatpak package for Caprine][1] and would like to submit it to Flathub (central repository for Flatpaks) so it would be more accessible to users that don't have snap preinstalled on their system or are oriented more towards Flatpaks (Fedora and ElementaryOS just to name a few). Users would also receive automatic updates through the package manager.

I would maintain this and it'll follow upstream (without additional patches if possible). Since the Flathub guidelines say that the developer of the application (or a contributor) [should maintain the package][2] I'd like to ask for approval for doing this since it would be treated as an official package.

[1]: https://github.com/dusansimic/flatpaks/tree/main/com.sindresorhus.Caprine
[2]: https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do

// @sindresorhus 
// @CvX

**Comment by sindresorhus** [comment]
You have my approval 👍

**Comment by dusansimic** [comment]
All done!

https://flathub.org/apps/details/com.sindresorhus.Caprine

I'll create a pr for updating the list of Linux packages.

**Comment by RDKRACZ** [comment]
Can you add the .flatpakref file to the releases too? The .snap file is already there.
