### ISSUE TITLE
"About Caprine" window isn't centered.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1691]
When the Caprine window is in full-screen mode then the about window is opened on the top left corner.
When the main window is not full screen then the about window is opened next to it on the right or, if there is enough space, on the top left corner again.

I'm reporting this since in the deb version this box is always opened in the middle of the screen.

**Comment by dusansimic** [comment]
Interesting. On my machines Arch package, RPM package and Flatpak all have the same behavior which is they open next to the window when not in full screen and in the top left corner when in full screen. Also when about window is opened, it's not focused, the main window is.

It seems to me that this is not flatpak only issue.

**Comment by RDKRACZ** [comment]
It isn't centered in the Arch Linux version too.
