### ISSUE TITLE
[Flatpak] Can be opened multiple times.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1692]
The deb version just focuses, brings itself from the background, when opened from the Start menu.
![Screenshot from 2021-08-23 12-20-29](https://user-images.githubusercontent.com/43277609/130431683-12269469-6a1a-41e4-bdfd-e6eff7cf529d.png)

**Comment by RDKRACZ** [comment]
![Screenshot from 2021-08-23 12-19-00](https://user-images.githubusercontent.com/43277609/130431743-4c548f27-a83a-4761-af82-77d30f8e9645.png)

**Comment by dusansimic** [comment]
Please add more info. Desktop environemnt, version.

**Comment by RDKRACZ** [comment]
Ubuntu 21.04 with Cinnamon 4.8.6 on the only available Caprine flatpak 2.54.1.

**Comment by lefterisgar** [comment]
Does this bug still happen?
