### ISSUE TITLE
[Flatpak] No tray icon.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1693]
![Screenshot from 2021-08-23 12-19-00](https://user-images.githubusercontent.com/43277609/130431829-422d7d51-093c-436f-9e34-833e7c99abb2.png)

**Comment by dusansimic** [comment]
Please add more info. Desktop environemnt, version.

**Comment by RDKRACZ** [comment]
Ubuntu 21.04 with Cinnamon 4.8.6 on the only available Caprine flatpak 2.54.1.

**Comment by bonelifer** [comment]
Xubuntu 20.04, XFCE 4.14, Caprine flatpak 2.54.1. Shows a blank black space instead of an icon.

**Comment by bonelifer** [comment]
![caprine-iconless](https://user-images.githubusercontent.com/121736/131284032-d5fd3b3e-66a1-4301-903c-a565f1ab1656.jpg)
Caprine is right between Discord and KeePassXC.

**Comment by RodneyBrown** [comment]
My  tray icon shows up as three dots:
![image](https://user-images.githubusercontent.com/6181723/132739402-a04ceae6-1ec8-4387-848a-a661b727f992.png)

**Comment by varlesh** [comment]
Confirm this. Flatpak application ignore system style and not render tray icon. BUT appimage worked fine:
![Screenshot_20210923_172825](https://user-images.githubusercontent.com/8083855/134517739-b1431fd3-455b-47c5-ab3c-4c726000228c.png)
on left (window & tray) flatpak, on right (window & tray) appimage

**Comment by LeFloatyPancake** [comment]
I gave Caprine access to the `/tmp` directory via flatseal>filesystem>other files. The icon now shows up but I don't know if this workaround is considered "safe" though.

**Comment by varlesh** [comment]
I'm not a security expert, but / tmp is usually used for temporary files. I think it's safe

**Comment by dusansimic** [comment]
This should be fixed once the new package build is pushed to Flathub (might take a few hours). I'll close this now but if the issue persists please let me know.
