### ISSUE TITLE
Issues forms for better issue descriptions.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1694]
I made an issue template for Caprine and can open a PR with it if You want.
Preview:
![Screenshot from 2021-08-23 12-56-30](https://user-images.githubusercontent.com/43277609/130436306-d4476f0c-626d-4a0d-aefe-f6cdfc6b5cf7.png)

**Comment by lefterisgar** [comment]
Hi! Could you please open a PR?

**Comment by dusansimic** [comment]
Closing the issue since it's stale
