### ISSUE TITLE
Can not allow cookies

### ISSUE THREAD

**Issue by Iliyan0411** [sindresorhus/caprine#1699]
I use Messenger/Caprine without Facebook account and can't allow cookies

Error type is: "Error performing query."

Thank you in advance!
---

Caprine 2.52.4
Electron 10.1.5
linux 5.11.0-27-generic
Locale: en-US

**Comment by kovacslt** [comment]
I have the same problem, facebook is messing with us.
I checked messenger.com in Firefox, Chromium, and in those browser messenger doesn't work either.

**Comment by ElArtista** [comment]
Same thing here

**Comment by kovacslt** [comment]
Messenger.com works for my wife. She has a real FB account. I'm registered only with my phone number just to able to chat.
I wonder, if that makes the difference?

**Comment by GeorgeKatsandris** [comment]
Same thing here. I do not have a fb account and am using caprine on ubuntu 20.04.

**Comment by agicquel** [comment]
Some problem. I am also using Messenger without Facebook account. Strangely, Messenger works on the Android app.

**Comment by kovacslt** [comment]
I send them an error report from my Android every day.  : )

**Comment by ElArtista** [comment]
Seems to be a general problem of messenger.com, not just a caprine related one

**Comment by kovacslt** [comment]
Today it started to work for me.

**Comment by Iliyan0411** [comment]
Thank you for response. Have a nice day.

**Comment by ElArtista** [comment]
Yep it now works. Seems that theme is broken again though

**Comment by kovacslt** [comment]
I use dark theme too, and it seems OK to me.
Caprine 2.54.1
Debian Buster 
MATE DE

**Comment by ElArtista** [comment]
I did a full clean install, relogin, deleting everything under ~/.config/Caprine
Caprine 2.54.1
Arch Linux

**Comment by kovacslt** [comment]
Just to make it sure, I did now:
-quit caprine
- rm -rf  ~/.config/Caprine
- relaunch caprine
For me it looks still OK.
Try to show:
https://drive.google.com/file/d/1ELlIZTqOvwWOYh-RVssIp7I-tZVNRJEr/view?usp=sharing
Do you see this as broken? Is it different to what you get?
Maybe messenger tries to keep on messing with you... :(

**Comment by ElArtista** [comment]
This is with 'Dark' theme selected in the menu:
![image](https://user-images.githubusercontent.com/4622346/132814306-a5788e1b-b244-4c4a-8a9e-e9bbee42160e.png)
![image](https://user-images.githubusercontent.com/4622346/132814824-abf9aaf4-07ec-45a6-a0ec-d4bf974f6157.png)

**Comment by mquevill** [comment]
I see a "Debug" menu in your screenshot, which is usually only there for development builds. Does it say 2.54.1 in the Help Menu > About Caprine? The method of setting the theme changed in v2.54.0, so the `theme: "dark"` JSON entry will not apply for older builds.

**Comment by ElArtista** [comment]
I am using the latest stable release of caprine through the official Arch Linux repositories:
```
$ yay -Qi caprine
Name            : caprine
Version         : 2.54.1-1
Description     : Elegant Facebook Messenger desktop app
Architecture    : any
URL             : https://github.com/sindresorhus/caprine
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : electron
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 22.07 MiB
Packager        : Nicola Squartini <tensor5@gmail.com>
Build Date      : Sun 15 Aug 2021 05:00:20 AM EEST
Install Date    : Tue 17 Aug 2021 11:11:53 AM EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by dusansimic** [comment]
@ElArtista @mquevill I believe that is due to Arch Caprine package being updated to use Electron 14 which doesn't support remote api in Electron and requires either using [`@electron/remote`](https://github.com/electron/remote) package or removing use of remote api. Caprine will be able to use Electron 14 once #1603 is closed and [`electron-util`](https://github.com/sindresorhus/electron-util) package is upgraded to support Electron 12 (removes use of remote module. Until then dependency package in Arch should be downgraded to `electron13`. I will report this to the package maintainer.

**Comment by ElArtista** [comment]
Yep I suppose we can close this.
