### ISSUE TITLE
Does notifications only work on Yosemite?

### ISSUE THREAD

**Issue by jeromedecoster** [sindresorhus/caprine#17]
Hi,

The readme said "notifications can be turned on in Preferences"

I downloaded the 0.1.1 release, I have OSX 10.9 and when I open Caprine Preferences menu I only choose the mute delay:
![capture d ecran 2015-09-29 a 15 02 02](https://cloud.githubusercontent.com/assets/158071/10164671/18ade64a-66bb-11e5-8b54-1ffceb349f20.png)

I have not cool notification like you:
![](https://github.com/sindresorhus/caprine/blob/master/media/screenshot-notification.png?raw=true)

The only notification I have is https://github.com/sindresorhus/caprine/blob/master/index.js#L26
with this result:
<img width="50" alt="capture d ecran 2015-09-29 a 15 11 12" src="https://cloud.githubusercontent.com/assets/158071/10164909/88bb84a0-66bc-11e5-983c-e918355a676b.png">

Notification only works on Yosemite ?

Thanks

**Comment by sindresorhus** [comment]
No idea. It should just work. Haven't seen that preference dialog before. Here's how it looks for me:

<img width="536" alt="screen shot 2015-09-29 at 20 46 57" src="https://cloud.githubusercontent.com/assets/170270/10165808/547d90a0-66eb-11e5-8da1-dce8d5e43f0f.png">

**Comment by jeromedecoster** [comment]
Strange...
Thank you
