### ISSUE TITLE
Touch Bar support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#170]
The [next version of Electron](https://github.com/electron/electron/releases/tag/v1.6.3) will come with Touch Bar support. See: https://github.com/electron/electron/pull/8095

I'm interested in hearing people's opinion on what it should contain? What shortcuts would be useful to have? What are the most common actions you do?

I think it should at least have buttons to go to the next/previous conversation.

**Comment by mirshko** [comment]
It would be cool to have top chatted with people on it. Similar to the favorites chat heads on the mobile Messenger app. Maybe shortcut to start new private chat (not sure if those are supported on the web tho)

**Comment by marcooliveira** [comment]
Will be adding several comments, so people can *thumbs up* on what they like.

- Emojis:
  - Could be the most common.
  - Ideally would be the most frequently used.

**Comment by marcooliveira** [comment]
Next/previous conversation.

**Comment by marcooliveira** [comment]
Favourite contacts: Like @mirshko said, their "heads".

**Comment by marcooliveira** [comment]
Start audio & video call.

**Comment by marcooliveira** [comment]
Send a "Like". I feel like this is a big one. Separating it from the "Emojis" one, since it just has a lot of meaning and is very frequent.

**Comment by marcooliveira** [comment]
"New message":
  - Could use the same icon that's already on top left.
  - After tap, would show friends with some heuristics, based on combination of favourites and most recent friends.

**Comment by sindresorhus** [comment]
If anyone needs to test the Touch Bar and don't have a new MacBook Pro, there's https://github.com/sindresorhus/touch-bar-simulator

**Comment by CvX** [comment]
Touch Bar support has been added in #426! 🎉 Closing.
