### ISSUE TITLE
Tray icon is named "Electron"; "About Caprine window uses Electron icon in the taskbar.

### ISSUE THREAD

**Issue by K0-RR** [sindresorhus/caprine#1700]
![Screenshot from 2021-09-02 21-07-40](https://user-images.githubusercontent.com/43277609/131902723-01bf6fde-2ed2-4142-80ba-e9fbd603a696.png)

Using Caprine 2.54.1 on Arch Linux

**Comment by lefterisgar** [comment]
This bug is tracked upstream: electron/electron#28131. When it is fixed, we will release a patch.

**Comment by dusansimic** [comment]
I'd rather keep this open so there won't be new issues open (or if there are, we could close them as a duplicate).

**Comment by mquevill** [comment]
This bug was closed in https://github.com/electron/electron/pull/36333 and merged into Electron v22+, so this should be resolved in recent versions.
