### ISSUE TITLE
Window Flashes White on Launch Before Theme is Loaded

### ISSUE THREAD

**Issue by elsiehupp** [sindresorhus/caprine#1702]
## Version Info

* Caprine Version 2.54.1 (2.54.1)
* macOS Big Sur 11.5.2 (20G95)

## Expected Behavior

When launching the application, the window will use the specified background color immediately when it appears.

## Actual Behavior

When launching the application, the window is blank white (except for the macOS "traffic light" buttons) for a second or so before switching to the specified background color. The behavior is particularly noticeable in Dark Mode but may still be noticeable with other themes.

## Commentary

The application window flashing white while the application is starting up is a known issue with Electron. There are [two relatively straightforward fixes](https://www.christianengvall.se/electron-white-screen-app-startup/), though if you want to show some sort of splash screen instead (or while the main interface is loading), that would obviously take more doing.

**Comment by lefterisgar** [comment]
Should be fixed in the latest release.
