### ISSUE TITLE
Request ability to get notifications only from specific users?

### ISSUE THREAD

**Issue by stamatgeorge** [sindresorhus/caprine#1703]

**Comment by dusansimic** [comment]
You can mute users that you don't want to get notifications from. You could then receive notifications only from specific users.

**Comment by stamatgeorge** [comment]
What happens when you have 4,500 friends. It's not practical.
There should be a way to get notified only from specific users you want the same way you can allow calls from on the iPhone (when notifications is silenced). Ex: Everyone, No One, Favorites.
