### ISSUE TITLE
Cannot change Dark Theme or Text Size

### ISSUE THREAD

**Issue by yukina3230** [sindresorhus/caprine#1709]
Recently I can't switch to dark theme and increase text size, I tried to log out and log in again but it doesn't work.

Caprine 2.54.1
Arch Linux

**Comment by dusansimic** [comment]
This is due to Arch package using a newer Electron version (explained in [#1699][otherissue]). I've reached out to the Arch package maintainer and will send and update here once it's resolved.

[otherissue]: https://github.com/sindresorhus/caprine/issues/1699#issuecomment-918365634

**Comment by Kritiqual** [comment]
I have the same issue, hope this will be fixed soon

**Comment by dusansimic** [comment]
Solved
