### ISSUE TITLE
Windows - Taskbar icon no longer getting marked when receiving a message

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1713]
Windows - Taskbar icon no longer getting marked when receiving a message. Normally when a message is received, something happens to the taskbar icon. I forget what exactly. Blinks orange, or a little red circle with number, or something. Starting a couple of days ago, nothing happens now.

Windows 7
Caprine 2.54.1

![image](https://user-images.githubusercontent.com/43397938/135369163-e927da4d-3fd2-4bfc-8401-45cf874550fe.png)

**Comment by MineEric64** [comment]
same issue on Windows 10 and Caprine 2.55.0

**Comment by lefterisgar** [comment]
Closing as duplicate of #1823.
