### ISSUE TITLE
Facebook Marketplace Missing

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1714]
After restarting my Computer, I manually load Caprine. My Facebook Marketplace Contact(s) disappear. 
Usually they come back after a good while. If I want to check them at will, I can't. Tried reloading Caprine.

---

Caprine 2.54.1
Electron 10.1.5
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment]
@PreachJohn does the same issue happen on [messenger.com](https://messenger.com) website?

**Comment by PreachJohn** [comment]
As you know there is no FB Messenger per say for Win7. So I use Caprine. 
Which then goes to say that loading FB itself and accessing Messenger there, Marketplace is still there to access.
But not in Caprine as I've stated. Till eventually much later.
