### ISSUE TITLE
Text stays half written in the message box

### ISSUE THREAD

**Issue by mattnoir** [sindresorhus/caprine#1719]
Not sure if I can describe it correctly, however when I write some longer messages, usually with multiple line breaks (shift+enter), and after sending the message I switch to another person to write. When I switch back to the first person, there is at least a portion of the original message still present, as if it was not sent. I am not sure, but I feel it's somehow related to the new line as only text after the new line (or several, usually two I believe) is missing.
![image](https://user-images.githubusercontent.com/21099343/137637444-6225f66d-5270-41f4-a7c3-eeb453c788fb.png)
![image](https://user-images.githubusercontent.com/21099343/137637456-dfa82404-449a-46cb-b7f4-fb5abbf343a2.png)
This is my best effort at making an example, please have mercy on me :D

**Comment by lefterisgar** [comment]
Should be fixed in v2.56.1 (latest).
