### ISSUE TITLE
Windows: if you send a video and click on it too quickly, Caprine will crash

### ISSUE THREAD

**Issue by asheroto** [sindresorhus/caprine#1720]
Has happened several times over the past 2 months, two different machines.  Seems to occur if the video hasn't finished uploading yet.

**Comment by asheroto** [comment]
Why was this closed? Is it fixed?

**Comment by lefterisgar** [comment]
It might be fixed by updating Electron. At least I can't replicate it.

**Comment by asheroto** [comment]
Gotcha, I think it's fixed now. Bug seems to be gone! :-)
