### ISSUE TITLE
remember login details

### ISSUE THREAD

**Issue by HarkTu** [sindresorhus/caprine#1721]
If internet is not connected on new reboot, caprine logs out. "Stay connected" box doesn't help.
I use caprine for my mother, need it never to log out. If not possible, remember login details could help for easier login. 

---

Caprine 2.54.1
Electron 10.1.5
win32 10.0.19042
Locale: tr

**Comment by lefterisgar** [comment]
Closing, as it will probably be fixed in the next release.
