### ISSUE TITLE
FB Marketplace Missing

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1725]
FB Marketplace entry is missing again. To check status I have to load FB's Messenger where it is still in with the rest of my List of Active Contacts. So it's not missing there so that I can access it there. 
Where one time recently it was strangely not listed there either so understandably neither listed in Caprine.

---

Caprine 2.55.0
Electron 10.4.7
win32 6.1.7601
Locale: en-US

**Comment by Waxxx333** [comment]
Works for me as of 11/12/21

**Comment by dusansimic** [comment]
@PreachJohn is this what you mean #1776?

**Comment by PreachJohn** [comment]
'Consistency, thou art a jewel.'
I have written FB Messenger a number of times to tell them that
'Marketplace' keeps disappearing from my current Conversations. And then it
would make sense that it disappears also in Caprine. And that's what would
normally happen in hindsight.
When I click on it, there are presently 2 Conversations stored in there.
But for the last few days, Caprine still has 'Marketplace' name
placeholder. FB Messenger doesn't again.
However I have now found a workaround when FB Messenger and/or Caprine
don't have a 'Marketplace' name placeholder just like all my other current
Conversations do. The ones that when I click on one, our Conversation
History appears.
Go into FB Marketplace itself, and click on Inbox on the left. The two
Conversations I haven't Deleted yet are there, but not available in
Messenger per se where it's supposed to be.
Hope this clarifies what the issue is.
JohnB
