### ISSUE TITLE
Prevents idle on linux

### ISSUE THREAD

**Issue by blawly** [sindresorhus/caprine#1726]
Having Caprine open prevents my computer from blanking and locking screen. Only happens since the last update. Same with flatpak and .deb version.

---

Caprine 2.55.0
Electron 10.4.7
Pop!_OS 21.04
linux 5.13.0-7620-generic
Locale: en-US

**Comment by TranceGeniK** [comment]
Same issue here, it seems to come from video wake lock and videos autoplay. By the way, unchecking autoplay videos doesn't seem to have any effect.
