### ISSUE TITLE
Caprine 2.55.0 spellcheck choose error

### ISSUE THREAD

**Issue by pietryszak** [sindresorhus/caprine#1727]
In newest version 2.55.0  we have some issue with choose spell checking language.
In 2.54.1 config.json looks like
```

	"spellCheckerLanguages": [
		"pl",
		"en-US"
```
but in 2.55.0 is

```
"spellCheckerLanguages": [
		"p",
		"l",
		"e",
		"n",
		"-",
		"U",
		"S"
	]
```
That's show error message when select or deselect language from menu.
System Fedora 35. Package installed by dnf. I try appimage and the same issue exists.

**Comment by mquevill** [comment]
Thank you for raising this issue! In #1723, I had put a spread operator (`...`) on the language variable itself, so it was breaking the string apart into each letter.

You may have to re-check your available spell check languages to ensure support is there. But any invalid codes should be removed when you start Caprine again.
