### ISSUE TITLE
Messages have an ugly white border using dark mode.

### ISSUE THREAD

**Issue by nozzlegear** [sindresorhus/caprine#173]
This is probably something that Facebook changed on their side, but I didn't see this on my Ubuntu machine so I figured I'd create an issue. On Windows, message bubbles suddenly have a white border around them when using dark mode where they didn't before. It's present in both version 1.7 and 1.8.

![image](https://cloud.githubusercontent.com/assets/2417276/24205408/55ff3ec2-0ee9-11e7-9a25-7cf4d63299fb.png)

Edit: switched back to Ubuntu and the borders are now there too.

**Comment by dudeofawesome** [comment]
I've fixed this in [my fork](https://github.com/dudeofawesome/caprine/commit/4a1e16b0dda4673e8faf90e6797e08f7806c34fe). I'll send a PR shortly.

**Comment by iChristosK** [comment]
This issue is also on mac with the latest version.
<img width="703" alt="screen shot 2017-03-23 at 10 08 43" src="https://cloud.githubusercontent.com/assets/16455384/24237849/bba27060-0fb0-11e7-927f-a353d6005cb3.png">
