### ISSUE TITLE
`Hide Names and Avatars` does not hide names and nicknames in groups

### ISSUE THREAD

**Issue by henkyfen** [sindresorhus/caprine#1732]
The **Hide Names and Avatars** feature does not hide the names or nicknames of members in a group.

![Screenshot_2021-11-20_11-49-49](https://user-images.githubusercontent.com/43473144/142723613-76fa24ee-b9e9-42d1-b4a5-5b23e9bd0ec6.png)

---

Caprine 2.55.0
Electron 13.6.1
linux 5.13.19-2-MANJARO
Locale: en-US

**Comment by dusansimic** [comment]
Thanks for reporting this! I've sent a patch and it will be fixed on a new release.
