### ISSUE TITLE
Dark mode title bar for Windows 10

### ISSUE THREAD

**Issue by priprii** [sindresorhus/caprine#1735]
Electron uses a white titlebar, which is a bit blinding when using dark mode in apps like this.

Consider implementing something like [electron-titlebar-windows](https://github.com/sidneys/electron-titlebar-windows) to address this issue.

**Comment by Thorsky24** [comment]
I came here to ask for that, too. Also, the scroll bar for messages could either have a dark mode like the title bar, or use the same design as the scroll bar for choosing the discussion.
