### ISSUE TITLE
Does this support messenger accounts when facebook account is not active or has been deactivated?

### ISSUE THREAD

**Issue by sheldonhull** [sindresorhus/caprine#1736]
I don't have a facebook account, just a messenger account. 
I'm redirected to verify my facebook account, which the Windows 10 app doesn't require.

Is there a workaround for those using messenger that do not have an active facebook account, and only use messenger?
I think last time I tried this it reactivated my closed facebook account from a long time ago.

**Comment by gazsoimi** [comment]
it should.
It uses electron, in a nutshell its a stripped down web browser, which loads messenger.com, and adds some things, dark mode etc.

so as messenger.com works with standalone messenger account, here should also.

**Comment by sheldonhull** [comment]
Update: I tried proceeding, and the "continue to facebook" button just took me to the screen to enter 2FA code, not to log in to Facebook. This seemed to work fine, just was confusing wording since I wanted to avoid any renabling of my prior facebook account. Considering closed and working, thank you!
