### ISSUE TITLE
Colors broken in dark mode

### ISSUE THREAD

**Issue by frozenpandaman** [sindresorhus/caprine#1737]
Started happening within the past day. v2.55.0, installed via Homebrew on macOS 12.0.1.

![image](https://user-images.githubusercontent.com/7245874/144143047-b055dd80-3306-4487-aefe-80cc2c9380a7.png)

The black rectangles is my censoring of private information. The problems are that the chat body/background is white, black corners appear around messages sent by me, and text is invisible in messages sent by others.

**Comment by joshualagat** [comment]
Experiencing the same issue on Manjaro Linux with Caprine from Official Repositories

**Comment by Okiesmokie** [comment]
Same issue here on Windows 10, Caprine v2.55.0

**Comment by huoi** [comment]
Same issue here on Arch Linux, Caprine 2.55.0.

**Comment by jmmanlupig** [comment]
Can confirm as well.
Caprine 2.55.0
Arch Linux & Windows 10

**Comment by jcatrdev** [comment]
Also experienced the same problem. Just open up Caprine this morning then I saw the issue.
![Screenshot_20211201_090122](https://user-images.githubusercontent.com/86816436/144152995-4ebc4eb2-e50f-4414-b012-d99adb6f9b41.png)

**Comment by riverstore** [comment]
Hi, I meet same problem

Caprine 2.55.0
Electron 10.4.7
win32 10.0.18362
Locale: en-US

Regard.

**Comment by quanKM** [comment]
Same issue on Mac OS, Caprine 2.55.0.

**Comment by nkenschaft** [comment]
Same here

Pop!_OS 21.04
Caprine 2.55.0

**Comment by mquevill** [comment]
It looks like the row backgrounds aren't getting the dark mode set properly. It seems like a widespread issue, not specific to any OS or version. It is most likely caused by a change on Facebook's end.

For reference, the backgrounds are contained in the `role="row"` items (example below). These incorrectly have `__fb-light-mode` when they need `__fb-dark-mode` to have the right colors.
```html
<div role="row" class="__fb-light-mode l9j0dhe7" style="--mwp-reply-background-color:var(--comment-footer-background);">
```

**Comment by spyd3r-b0y** [comment]
last night everything was fine. Today I'm also facing same problem :|

**Comment by TheBricktop** [comment]
same here win10 caprine 2.55

**Comment by spyd3r-b0y** [comment]
how to solve this problem?

**Comment by maxoku** [comment]
I guess a css code could be a temporary solution until the next update. I don't know the proper colors, so I can't write one now.

**Comment by Koko2110** [comment]
A dumb temporary custom CSS style I wrote up in 2 minutes: https://pastebin.com/qeRwKFEe

It's just a swap of the dark and light mode classes with a bunch of !important's. It could maybe be a temporary solution for a few days.

**Comment by condimentman** [comment]
@Koko2110 nice can recommend this to people wanting to read their messages unblinded until they roll out a fix

**Comment by mquevill** [comment]
The fix by @Koko2110 will work as long as you have dark mode selected; if you switch back to light mode with that CSS, it will probably break things there.

Unfortunately, since the `__fb-light-mode` class is still there (and `__fb-dark-mode` is not), there is not a _simple_ workaround for all users.

**Comment by maxoku** [comment]
Thanks for the fix, I can confirm that it works.

**Comment by billybhaub** [comment]
How can I apply the CSS fix? (I'm running on Ubuntu 21.04)

**Comment by Koko2110** [comment]
> How can I apply the CSS fix? (I'm running on Ubuntu 21.04)

You should be able to find the "Custom Styles" option under File/Caprine Settings/Advanced. Save the edited file and relaunch.

**Comment by profucius** [comment]
Can confirm the CSS workaround works for me too. Here's hoping for a permanent fix in a future update of Caprine.

**Comment by frozenpandaman** [comment]
> A dumb temporary custom CSS style I wrote up in 2 minutes: https://pastebin.com/zC98S88r

>You should be able to find the "Custom Styles" option under File/Caprine Settings/Advanced. Save the edited file and relaunch.


@ Koko2110 Thanks! Works great.

For what it's worth, on Mac this is Caprine > Caprine Preferences > Advanced > Custom Styles, which opens up `~/Library/Application Support/Caprine/custom.css` in your default text editor.
