### ISSUE TITLE
Dark Mode has quit working, message area is all white with white letters. 

### ISSUE THREAD

**Issue by cobra3282000** [sindresorhus/caprine#1741]
i even reinstalled my whole system from scratch, it just stopped working. 

---

Caprine 2.54.1
Electron 10.1.5
linux 5.4.0-91-generic
Locale: en-
![Screenshot_2021-12-01_15-47-27](https://user-images.githubusercontent.com/77239090/144332333-9e5949ce-25a9-4708-984c-051c8848461a.png)
![Screenshot_2021-12-01_15-47-27](https://user-images.githubusercontent.com/77239090/144332364-58b52f0b-db17-457e-82c7-2b2e93f4fb54.png)
US

**Comment by mquevill** [comment]
This is a very recent issue with dark mode. See #1737 for a discussion and a temporary workaround. Alternatively, light mode should still work properly.
