### ISSUE TITLE
Remember "Mute Notifications" after restart?

### ISSUE THREAD

**Issue by swebervna** [sindresorhus/caprine#1743]
I want to disable the sound notifications for Caprine, but if I check "Mute Notifications" and restart Caprine, it forgets that setting and notifications turn back on. Is there a way to permanently disable sound notifications?

**Comment by joshualagat** [comment]
Have you tried turning it off via the config?

**Comment by swebervna** [comment]
> Have you tried turning it off via the config?

Do you mean a config file? Not sure where that is.

**Comment by tin-pham** [comment]
same problem, after restart it become uncheck again

**Comment by dusansimic** [comment]
This will most likely get fixed by #1881 on the next release. If it's not fixed, I'll repoen the issue.
