### ISSUE TITLE
failed uninstalling the program

### ISSUE THREAD

**Issue by Krenelek** [sindresorhus/caprine#1744]
Hi, I found that many people have a problem with uninstalling your software

---

Caprine 2.52.4
Electron 10.1.5
linux 5.11.0-41-generic
Locale: en-GB

**Comment by dusansimic** [comment]
Please elaborate. What are those problems? With this information we can't do anything.

**Comment by mquevill** [comment]
Also, what method did you use to install the software?

For instance, if you installed via .deb, you should be able to run `sudo apt-get remove caprine`. For a snap, you can run `sudo snap remove caprine`. If you are using an AppImage, those are not "installed" so you can just delete the file. It gets a little more complicated if you installed from source code.
