### ISSUE TITLE
Cannot loading media 

### ISSUE THREAD

**Issue by Kritiqual** [sindresorhus/caprine#1745]
When I clicked on some picture or videos I received, the screen turn black, and not thing is shown

**Comment by spinalgr1990** [comment]
that happens to me also ...

**Comment by ictnmd** [comment]
Me too

**Comment by mattnoir** [comment]
same here. When I try to reload with ctrl+r, it shows the picture, but with no option to close it, only to click on messenger logo to return back. Only started happening this evening

**Comment by mirenradia** [comment]
I think this is a duplicate of #1751 which provides a bit more information.

**Comment by dusansimic** [comment]
Duplicate of #1751
