### ISSUE TITLE
Dark Theme doesn't work

### ISSUE THREAD

**Issue by MrGoraj** [sindresorhus/caprine#1746]
![image](https://user-images.githubusercontent.com/32809530/144583140-d057d068-8ea3-4699-b01a-7430df273893.png)

---

Caprine 2.54.1
Electron 10.1.5
linux 5.4.0-91-generic
Locale: pl

**Comment by dusansimic** [comment]
Please update to the latest version of Caprine. It was fixed in [2.55.1](https://github.com/sindresorhus/caprine/releases/tag/v2.55.1).
