### ISSUE TITLE
dark mode buggy

### ISSUE THREAD

**Issue by Jio5** [sindresorhus/caprine#1747]
hello since a few days my caprine dark mode gets buggy, i join you a screenshot of what i get : 

![image](https://user-images.githubusercontent.com/62399357/144615381-84b900da-45ed-4e77-9363-10693098c721.png)

thank you for your help ! 

---

Caprine 2.54.1
Electron 10.1.5
win32 10.0.19043
Locale: fr

**Comment by dusansimic** [comment]
Please update Caprine to the latest version. It's fixed in [2.55.1](https://github.com/sindresorhus/caprine/releases/tag/v2.55.1).

**Comment by Jio5** [comment]
oh, sorry I read somewhere that caprine was doing auto update so i taught i was up to date x) thx for quick answer !
