### ISSUE TITLE
"Remove" & "Forward" buttons do nothing

### ISSUE THREAD

**Issue by frozenpandaman** [sindresorhus/caprine#1750]
macOS 12.0.1, v2.55.1.

![image](https://user-images.githubusercontent.com/7245874/144676776-3ad80464-91e4-498b-ae53-0657f3c417d1.png)

Clicking on "Remove" does nothing. On messenger.com, the following pop-up appears:

![image](https://user-images.githubusercontent.com/7245874/144676831-c4fcafb2-c039-4e92-9b07-09a1e8c2dd16.png)

Edit: "Forward" doesn't work either.

**Comment by dusansimic** [comment]
Related to #1751
