### ISSUE TITLE
The :v emote does not display

### ISSUE THREAD

**Issue by Lanthanariel** [sindresorhus/caprine#1752]
When I type the :v emote, it doesn't show in the screen, just a blank in its place.

---

Caprine 2.55.1
Electron 10.4.7
linux 5.15.5-76051505-generic
Locale: en-US

**Comment by frozenpandaman** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/7245874/145381499-fe095743-c8f9-4569-821b-560ee0a5644e.png)

Caprine 2.55.1
macOS 12.0.1
Locale: en-US

**Comment by Lanthanariel** [comment]
Funny enough, it works for me now, too. :/
