### ISSUE TITLE
Dark theme problem

### ISSUE THREAD

**Issue by massaf1** [sindresorhus/caprine#1754]
If you turn on dark mode you will see the issue.

Dark mode changes the overall theme of the application. BUT in the chat part it just changes the font color as it should in dark mode but the background color does not change to dark.

---

Caprine 2.55.0
Electron 10.4.7
linux 5.13.0-21-generic
Locale: en-US

**Comment by mquevill** [comment]
Fixed in v2.55.1. Please update the app first.

**Comment by massaf1** [comment]
I saw the update just a moment ago. Fixed it.
