### ISSUE TITLE
Remove Button Inert Too

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1755]
I know that Dark Mode not rendering correctly and Delete Chat button inert are reported.
I cannot now Remove a Video either. Button inert.
I appreciate that you are doing your best to repair. I simply want to give constructive feedback. That's all.

---

Caprine 2.55.1
Electron 10.4.7
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment]
Related to #1751
