### ISSUE TITLE
[Bug] Black screen when opening media

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/caprine#1759]
When I click on an image or video that it would be opened on whole screen I see only a black screen. The only way to return from it is to press escape button.

**Comment by profucius** [comment]
Same issue here. I noticed this started happening after the recent updated I think Facebook did that caused the app to be in semi-light mode. Even after the newest hotfix which fixes that, clicking on images to show them fullscreen only shows a black screen instead. It's as if the image does not load.

**Comment by dusansimic** [comment]
Duplicate of #1751

**Comment by maxoku** [comment]
Damn it, am I blind? I didn't see that issue at all, but now it's there in the front.
