### ISSUE TITLE
Bugs in the latest (2.55.1) version of Caprine

### ISSUE THREAD

**Issue by BorisitoT** [sindresorhus/caprine#1761]
1) Clicking on a picture produces a blank screen
2) Clicking on reactions does nothing.
3) Clicking on the Forward button also does nothing.
4) The same goes for the Remove function, you click it, nothing happens.
---

Caprine 2.55.1
Electron 10.4.7
win32 10.0.19042
Locale: en-US

**Comment by dusansimic** [comment]
Duplicate of #1751
