### ISSUE TITLE
Display names instead of ids

### ISSUE THREAD

**Issue by CoBC** [sindresorhus/caprine#1762]
Currently, in list of discussions, IDs are displayed, so it's really dificult to find a discussion. Can you display names of contact instead of ids?

---

Caprine 2.55.1
Electron 10.4.7
win32 10.0.22000
Locale: fr

**Comment by dusansimic** [comment]
Could you provide an example of what you're experiencing. Screenshots would be good. Also steps to reproduce are useful to see if we can also get that same issue.
