### ISSUE TITLE
Media enlarging doesn't work

### ISSUE THREAD

**Issue by PrimozR** [sindresorhus/caprine#1764]
Enlarging (maximizing) an image or video attached to a message doesn't work, all the conversation content is only covered by a gray overlay, only Esc brings me back (there aren't any buttons enabling me to close the overlay).

This has bee going on since the last Messenger update, when the dark mode was also broken (that was fixed with the Caprine update).

**Comment by mquevill** [comment]
There was another recent release (v2.55.2) that should have fixed this issue as well. (Dark mode was fixed in v2.55.1.). Please verify that you are using the most up-to-date version.

**Comment by PrimozR** [comment]
I was not, updated now, can confirm it's working.
