### ISSUE TITLE
Snap old version

### ISSUE THREAD

**Issue by pietryszak** [sindresorhus/caprine#1766]
Please update snap version in Snapcraft. At this moment is old 2.52.4 version instead newest

**Comment by jberlyn** [comment]
Any update regarding this? The Snapcraft version hasn't been updated since April 2021 and the pull request had an initial merge without support for Snapcraft builds.

**Comment by dusansimic** [comment]
The issue is fixed but the new version will be published on the next release. Until the you could manually install snap package from [releases page](https://github.com/sindresorhus/caprine/releases).

**Comment by dusansimic** [comment]
Snap has been updated.
