### ISSUE TITLE
Request: Update functionality for AppImage

### ISSUE THREAD

**Issue by PixsaOJ** [sindresorhus/caprine#1767]
Hi, I am using AppImageLauncher/appimagelauncherd service to manage my `.AppImage` programs.

While using AppImages, some software has update functionality built in.

[Here is link how that is implemented](https://docs.appimage.org/packaging-guide/optional/updates.html)

It would be nice if Caprine had it too.

Here is an example of how would it look like for me:

![image](https://user-images.githubusercontent.com/12684017/145940237-00eb0948-beb2-46b8-afb8-ad7356f1f403.png)

**Comment by PixsaOJ** [comment]
Why was this closed without response? I just got latest AppImage and it's not implemented. If you are not going to do this, let me know.

**Comment by lefterisgar** [comment]
Because it will be implemented in the next release.

**Comment by lefterisgar** [comment]
Automatic updates, just like Windows.

**Comment by PixsaOJ** [comment]
Okay, thanks! Don't do unattended updates though, generally not cool, and could cause problems.

**Comment by lefterisgar** [comment]
A toggle has been added for that reason. I don't like them too.
