### ISSUE TITLE
Messenger Kids

### ISSUE THREAD

**Issue by honza** [sindresorhus/caprine#1769]
I didn't see an obvious way to use Caprine as Messenger Kids. Is that something that's supported? If not, can you offer some hints if/how it could be implemented? Thanks

**Comment by dusansimic** [comment]
Afaik, Messenger Kids doesn't have a web app and since Caprine is just a wrapper around the Messenger web app ([messenger.com](https://messenger.com)), we can't do anything here. If a web app for Messenger Kids gets released, we'll maybe implement a wrapper around it.
