### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by vinnniv** [sindresorhus/caprine#1773]
![image](https://user-images.githubusercontent.com/96475323/146921270-d47196f7-654c-4266-9a0f-8e1c585caa45.png)

---

Caprine 2.52.4
Electron 10.1.5
linux 5.13.0-22-generic
Locale: fr

**Comment by mquevill** [comment]
This issue is fixed as of v2.55.1. Please update to the newest version. If using Snap, you will need to manually install, since the Snapcraft package is currently behind the proper releases (but should be updated on the next release).
