### ISSUE TITLE
Facebook Custom Themes

### ISSUE THREAD

**Issue by battery3996** [sindresorhus/caprine#1778]
This may seem like something small and not important, however can we get support for more than just gradient themes for the chat. The Official app and chat windows support image background themes. 

official app
https://i.imgur.com/TvRfY7M.png

Yours
https://i.imgur.com/yX5eVDN.png

**Comment by dusansimic** [comment]
This is an issue with [messenger.com](htttps://messenger.com) website. Caprine is just a wrapper around the website with some small features added in. Once the background theme gets implemented on the website, it will be present on Caprine too.
