### ISSUE TITLE
Caprine 2.0.0 window can't be resized or maximized on Windows 10

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#178]
Caprine 2.0.0 window can't be resized or maximized on Windows 10 while it works fine on macOS. I think it worked in 1.8.0.

The window on Windows 10 is also quite large, on a full HD display it takes most of the screen so when you take that all into account, positioning the window so that you can see everything is quite hard.

**Comment by zackschuster** [comment]
Can confirm the resizing issue. On my 2560x1600 display it fills (roughly) 1/4 of the screen.

**Comment by BlueHatbRit** [comment]
Roughly 1/4 of the screen on my 1920x1080 as well with the same issue.

**Comment by BlueHatbRit** [comment]
I've submitted a fix for this a PR 180
