### ISSUE TITLE
emoticon buttons no working

### ISSUE THREAD

**Issue by recon9030** [sindresorhus/caprine#1786]
The emoticon buttons of the messages in the bottom 80-100px of the screen don't work in every conversation.
Restarting Caprine or the desktop doesn't solve the problem
![fbm](https://user-images.githubusercontent.com/80802919/152584906-325c2f8c-0687-42b5-a783-24b0794d81d5.jpeg)

---

Caprine 2.52.4
Electron 10.1.5
linux 5.13.0-28-generic
Locale: nl

**Comment by mquevill** [comment]
That has been addressed in more recent releases (in b86cec1ebc3b09e3c025c807928c815f6855c8d6). Please update to the current version (2.55.2) to see these changes.
