### ISSUE TITLE
Dark mode not consistent - chat window has white background

### ISSUE THREAD

**Issue by PlotnicuRodica** [sindresorhus/caprine#1788]
Dark mode is not consistent - chat window has white background. 
I tried turning the mode off and on, didn't help.

Steps to reproduce:
- Go to View -> Dark mode
- Enable it
- Enter any chat
- Chat background is white. while everything else is dark grey.

---

Caprine 2.52.4
Electron 10.1.5
linux 5.13.0-28-generic
Locale: en-US

**Comment by mquevill** [comment]
This bug was fixed in more recent updates. Please update to v2.55.2 to verify that the theme is corrected.
