### ISSUE TITLE
Caprine weird bug

### ISSUE THREAD

**Issue by Baldovska** [sindresorhus/caprine#1789]
When I open carpine settings weird graphical bug appears. Same thing happens when I open help tab.

---
![Caprine bug](https://user-images.githubusercontent.com/99900653/154528569-9ee2e9e9-dfab-484f-81ce-078d4b237157.png)

Caprine 2.52.4
Electron 10.1.5
linux 5.13.0-28-generic (Ubuntu 20.04)
Locale: en-GB

**Comment by BienAtGitHub** [comment]
Can't replicate that on my instance.
Try disabling "Hide Names and Avatars" which uses blur effects and try again.
Blur seems to be broken on mine too (doesn't cover the chat list)
If that doesn't help, maybe check your compositor or your GPU.

**Comment by SpacingBat3** [comment]
This is likely a bug with the Electron itself, or maybe even Chromium engine (don't blame Caprine for that!). Also Electron 10 is quite old now (in fact I believe 13 is the *latest* release that has reached end-of-life), so I guess you may get better results with different Electron versions – be ready for the other bugs, however. The rendering should also differ from flags you use to e.g. enforce the driver. Maybe you could also disable hardware acceleration just to test if that helps.

**Comment by Baldovska** [comment]
Ok after a while I tried caprine again with the same issue. Also I noticed that caprine takes a while to load (sometimes even 30s!). Tried disabling hardware acceleration which fixed the problem (even the loading times are much better although could be better, around 3s to load up). Thank you for your reply!

> This is likely a bug with the Electron itself, or maybe even Chromium engine (don't blame Caprine for that!). Also Electron 10 is quite old now (in fact I believe 13 is the _latest_ release that has reached end-of-life), so I guess you may get better results with different Electron versions – be ready for the other bugs, however. The rendering should also differ from flags you use to e.g. enforce the driver. Maybe you could also disable hardware acceleration just to test if that helps.
