### ISSUE TITLE
Does not start on fedora/rawhide

### ISSUE THREAD

**Issue by david-hill** [sindresorhus/caprine#1790]
Does not start on fedora/rawhide

**Comment by retsimx** [comment]
+1. No longer starts on Arch either.

```
caprine --enable-features=UseOzonePlatform,VaapiVideoDecoder --ozone-platform=wayland
[1]    8159 trace trap (core dumped)  caprine --enable-features=UseOzonePlatform,VaapiVideoDecoder
```

However starting it with X11 works fine.

```caprine --enable-features=UseOzonePlatform,VaapiVideoDecoder --ozone-platform=x11```

Possibly an electron problem?

**Comment by lefterisgar** [comment]
Hi there! I guess it's too late now but I have managed to bump Electron to version 13.6.9 on my fork. Would you like to try out my release [here](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-2)? It would be very nice if you can give me some feedback. I had the same problem on Ubuntu 22.04 and thought I would fix until the pull request here is merged.

**Comment by lefterisgar** [comment]
Also this will be a HUGE issue when Ubuntu 22.04 LTS is released. The release is due this month by the way.

**Comment by david-hill** [comment]
This one starts with rawhide .

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
