### ISSUE TITLE
Caprine 2.54.1 not opening file attachments on Ubuntu 20.04.3 LTS.

### ISSUE THREAD

**Issue by neutron1954** [sindresorhus/caprine#1791]
Clicking on any graphic file attachment sent via Facebook Messenger results in Caprine going to a blank window.  Most file attachments are relatively low-res screen captures from a mobile phone.  None will open and result in a blank window that forces me to relaunch Caprine.

Bob Reed
Westminster, MD

---

Caprine 2.54.1
Electron 10.1.5
linux 5.4.0-100-generic
Locale: en-US

**Comment by mquevill** [comment]
Please update to the most recent version (v2.55.2) as I believe this issue should be resolved in that version.

**Comment by neutron1954** [comment]
Thank you for the guidance.  Updating to 2.55.2 did indeed resolve the problem.
