### ISSUE TITLE
Is it possible to prevent Messenger Rooms from opening with Caprine?

### ISSUE THREAD

**Issue by LuisCane** [sindresorhus/caprine#1792]
I'm using the flatpak version of Caprine 2.55.2 on Ubuntu 21.10 based PopOS. When I open Caprine, Messenger Rooms opens along with it automatically turning on my webcam. 
I haven't found a setting to disable that and Messenger Settings opens Messenger Rooms.

**Comment by lefterisgar** [comment]
Should be fixed.

**Comment by ErikRobles** [comment]
I also am experiencing this since the latest update. This should be fixed as it interferes with my other webcam based applications I use in my work and I would love to have Caprine open but due to the interference, I can't
