### ISSUE TITLE
fix scrollbar theme

### ISSUE THREAD

**Issue by dnlw07** [sindresorhus/caprine#1793]
Hello,
I have noticed that scrollbar theme doesn't fit to grey theme. 
Is possible to fix that?

![image](https://user-images.githubusercontent.com/23562689/156926906-24d09e21-d97e-4ebb-bab9-9a07217238c3.png)

**Comment by finnmerlett** [comment]
Interestingly it doesn't appear to change when adding scrollbar styling to the custom styles sheet either

**Comment by dnlw07** [comment]
thank you!

**Comment by lefterisgar** [comment]
I have tried fixing the issue in my fork. If you want, have a look and tell me what you think.

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
