### ISSUE TITLE
Dark mode problems

### ISSUE THREAD

**Issue by AbdelkarimMerabet** [sindresorhus/caprine#1794]
![Screenshot from 2022-03-13 18-37-49](https://user-images.githubusercontent.com/95025226/158072011-e40a7dbf-d80b-4219-a89a-1109912bb1b4.png)

Caprine 2.52.4
Electron 10.1.5
linux 5.16.11-76051611-generic
Locale: en-US

**Comment by mquevill** [comment]
This should be fixed in the newest version (v2.55.2). Please upgrade to see if this resolves your issue.
