### ISSUE TITLE
Text input bar so small in high definition screen

### ISSUE THREAD

**Issue by pqnhan** [sindresorhus/caprine#1801]
Is there a way that allows me to increase the size of the text input bar in Caprine?
I can increase the font size in the conversation but the text input bar is really too small and it makes my eyes very tired on my screen.

Any help is much appreciated.

---

Caprine 2.55.4
Electron 10.4.7
linux 4.18.1-041801-generic
Locale: en-US

**Comment by lefterisgar** [comment]
You can tweak the css but it's Messenger's fault, not ours.
