### ISSUE TITLE
For those who can't get Caprine to start on Linux

### ISSUE THREAD

**Issue by lefterisgar** [sindresorhus/caprine#1805]
### The issue

Recently, a lot of Linux users have been reporting that Caprine no longer starts on their PCs. That's because of a recent glibc update that enables clone3. To fix it, you need to bump the Electron version. Electron 13 (now unsupported) is the oldest version that actually got the patch.

### Affected distros

- Arch Linux (1 report [here](https://github.com/sindresorhus/caprine/issues/1790#issuecomment-1053631682))
- Fedora Rawhide (#1790)
- Ubuntu 22.04 LTS (got quickly reverted before 21.10 was released but made its way into 22.04 in mid-February)

### Workaround(s)

- **[Download](https://github.com/lefterisgar/caprine/releases) one of my premade binaries for your platform (Windows, Appimage, DEB and RPM are available)**
- Clone my [fork](https://github.com/lefterisgar/caprine) and run it just as you would official Caprine (npm start)
- [INSECURE] Run Caprine with the --no-sandbox flag to disable sandboxing (extremely extremely insecure!!!)

NOTE: I created this fork only as a temporary solution. I plan to maintain it on a regular basis but the actual fix is to merge my proposed changes here.

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.

**Comment by ucdailoi** [comment]
I have no idea what you are talking about when you offer a fix. I am a Ubuntu 22.04 user and have no skills when it comes to understanding the terminology.
So what can I do to make Caprine run properly. Is there a simple fix. I just updated it and it still plays up. Hangs

**Comment by lefterisgar** [comment]
> I have no idea what you are talking about when you offer a fix. I am a Ubuntu 22.04 user and have no skills when it comes to understanding the terminology. So what can I do to make Caprine run properly. Is there a simple fix. I just updated it and it still plays up. Hangs

I wasn't offering a fix but a workaround. The fix has now been implemented in the latest version of Caprine. If you still experience problems, open a new issue so people can see it and help.
