### ISSUE TITLE
No more portable and no more 32 bit app?

### ISSUE THREAD

**Issue by ktlinux** [sindresorhus/caprine#181]
Are you really leaving the 32 bit boat? OK, I understand that it is better to make the app installable rather than portable (although I like the idea of erasing a folder and deleting the programme simultaneously) since it is easier for many to use an installer. But there are people (including me) who can only use 32 bit apps. Why have you stopped supporting this version?

**Comment by sindresorhus** [comment]
I plan on adding a portable version when some bugs are fixed in electron-builder. 32-bit is not going to happen though. Time to move on.
