### ISSUE TITLE
Not opening pictures

### ISSUE THREAD

**Issue by RagnarBelial** [sindresorhus/caprine#1810]
All of a sudden, clicking on a picture sent by a contact in a chat doesn't open it. Instead of enlarging the picture in the window it moves into opening it, but the window stays dark (in a dark mode, of course)
Pressing escape works as if the pic was open, so the display returns to actual messaging. 

![Screenshot from 2022-04-11 09-24-38](https://user-images.githubusercontent.com/99590667/162695754-6694db64-23a8-4525-9855-7778b1ce0841.png)

---

Caprine 2.55.4
Electron 10.4.7
linux 5.14.0-1032-oem
Locale: en-GB

**Comment by tomeczeka** [comment]
same issue: it seems Messenger changed the way pictures display server-side to an overlay. forwarding messages and media doesn't work either

**Comment by czerwinski76** [comment]
Same here.

Latest W10 x64.
Caprine 2.55.4

**Comment by bgornicki** [comment]
Same here

**Comment by lefterisgar** [comment]
Could you try [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) and see if it works as expected? It contains the latest patch that fixes the issue.

**Comment by tomeczeka** [comment]
The installer keeps returning an error (Caprine is running. Click OK to close it) even though it’s not running, but it does update either way and pictures do open. Thanks, great work! Od: Lefteris GaryfalakisWysłano: czwartek, 14 kwietnia 2022 21:14Do: sindresorhus/caprineDW: tomeczeka; CommentTemat: Re: [sindresorhus/caprine] Not opening pictures (Issue #1810) Could you try this and see if it works as expected? It contains the latest patch that fixes the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by RagnarBelial** [comment]
> Could you try [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) and see if it works as expected? It contains the latest patch that fixes the issue.

Unfortunately still the same here.
![image](https://user-images.githubusercontent.com/99590667/163527087-b530f380-c755-45f3-914d-2c8fb6c773bf.png)

**Comment by lefterisgar** [comment]
You should download my package from the link provided. You are still using the official version.

**Comment by RagnarBelial** [comment]
> You should download my package from the link provided. You are still using the official version.

I did. I uninstalled the previously installed package and installed what you provided. I realise that the version shows the official package, which is confusing.

**Comment by lefterisgar** [comment]
I see. It is confusing Indeed. From what I could tell you are on Linux. Maybe you could try using the AppImage instead.

**Comment by RagnarBelial** [comment]
I give up :D 

![image](https://user-images.githubusercontent.com/99590667/163540159-da2c03d9-aa63-4ca7-878d-97a331f84334.png)

**Comment by lefterisgar** [comment]
Understandable. I don't know what could be causing this issue as I can't replicate it. 
Maybe doing ```$ mv ~/.config/Caprine ~/.config/Caprine.bak``` could help.

Also if you see 2.55.4 on the About Caprine section then it doesn't contain the patch.

Here is how it should look like:
![εικόνα](https://user-images.githubusercontent.com/46350667/163579890-6df667cd-9719-4103-85ff-b8852cacbc12.png)

**Comment by bgornicki** [comment]
2.55.4-3 fixed the issue on my side (I'm on Ubuntu)

**Comment by lefterisgar** [comment]
Nice! I'm on Kubuntu 22.04.

**Comment by RagnarBelial** [comment]
> Understandable. I don't know what could be causing this issue as I can't replicate it. Maybe doing `$ mv ~/.config/Caprine ~/.config/Caprine.bak` could help.
> 
> Also if you see 2.55.4 on the About Caprine section then it doesn't contain the patch. **EDIT: It could be that Caprine is still running on the background.**
> 
> Here is how it should look like: ![εικόνα](https://user-images.githubusercontent.com/46350667/163579890-6df667cd-9719-4103-85ff-b8852cacbc12.png)

Bingo. That was it. I had to remove the .config/Caprine directory. 

Thanks everyone.

**Comment by RagnarBelial** [comment]
I think it's only fair to close the issue as it has been resolved.

**Comment by sparkie3** [comment]
This was working, but I updated. I'm on 2.56.1, Ubuntu 22.04, and it's not working again.

**Comment by lefterisgar** [comment]
> This was working, but I updated. I'm on 2.56.1, Ubuntu 22.04, and it's not working again.

It was a change on Messenger's side. We didn't break anything.

**Comment by RagnarBelial** [comment]
> This was working, but I updated. I'm on 2.56.1, Ubuntu 22.04, and it's not working again.

I am also on 2.56.1 but on Mint 21. It still works for me.

**Comment by lefterisgar** [comment]
> > This was working, but I updated. I'm on 2.56.1, Ubuntu 22.04, and it's not working again.
> 
> I am also on 2.56.1 but on Mint 21. It still works for me.

You probably still use the old one. Same for me and the rest of the dev team.

**Comment by sparkie3** [comment]
Use the old what?

**Comment by lefterisgar** [comment]
> Use the old what?

user interface

Messenger has probably changed something on their side and we can't get access to it yet.

**Comment by sparkie3** [comment]
Oh, I see. I'm sure they probably do it intentionally. If there is a setting I can check or something I'm willing to help.

**Comment by lefterisgar** [comment]
> Oh, I see. I'm sure they probably do it intentionally.

Every time they change their design (website), Caprine breaks. And we can't use their APIs (which are more stable) due to legal reasons.

> If there is a setting I can check or something I'm willing to help.

You would need to find which class they have changed and see what the new one is. In short, just hope that someone who contributes to Caprine receives the new UI. 😥

**Comment by sparkie3** [comment]
Yea, I don't know how to do all that haha.
