### ISSUE TITLE
Media not working

### ISSUE THREAD

**Issue by marek9336** [sindresorhus/caprine#1812]
After open any media, Caprine show black sceen and nothing... ESC end it, but media still not show in "fullscreen"

![image](https://user-images.githubusercontent.com/24251631/162964755-a2fc4495-fabf-4862-80a9-8c1c5910e1d1.png)

---

Caprine 2.55.4
Electron 10.4.7
win32 10.0.22000
Locale: cs

**Comment by profucius** [comment]
Same here. Came to make an issue and found this one to +1

**Comment by St3fanos** [comment]
+1

**Comment by faithvoid** [comment]
Can also confirm the same issue on Arch Linux.

**Comment by lefterisgar** [comment]
Hi guys! Could you try [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) and report back if it works for you?

**Comment by St3fanos** [comment]
> Hi guys! Could you try [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) and report back if it works for you?

Leyteri doulevei mia xara pros to paron yeeeyy

It seems to work now ;)

**Comment by lefterisgar** [comment]
Στέφανε σ' ευχαριστώ για το feedback!

Thanks for the feedback!

**Comment by CaptainMazda** [comment]
This fixed it for me, but 5 minutes later it was broken again. Still running 2.55.4.

**Comment by lefterisgar** [comment]
In a terminal, you could try this command:
```$ rm -rf ~/.config/Caprine```
You will need to login again.

Also make sure Caprine is not running in the background because the old version might still be running.

**Comment by CaptainMazda** [comment]
Hey, I'm on W10 and have a Caprine folder in Local and Roaming. Is there a config file I need to edit? I think that terminal command is only for Linux/Mac if I'm not mistaken.

**Comment by lefterisgar** [comment]
Yes. This command works only in a bash shell (Linux). You could try deleting both folders. You don't need to edit anything.

**Comment by CaptainMazda** [comment]
I reinstalled the patch and now it's correctly showing 2.55.4-3. Not sure what happened the first time around but hopefully it'll keep working. Thanks!
