### ISSUE TITLE
 images not loading

### ISSUE THREAD

**Issue by Jirafey** [sindresorhus/caprine#1813]
images not loading
---
steps to replicate:
1) log in to caprine for the first time windows 10
2) click on any image.
3) image is just black
![image](https://user-images.githubusercontent.com/97115044/162981734-b95b2a3c-801b-4094-acc0-57222bbaa0e3.png)

Caprine 2.55.4
Electron 10.4.7
win32 10.0.19044
Locale: en-GB

**Comment by lefterisgar** [comment]
Can you please try [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) and see if it works for you?
