### ISSUE TITLE
Photos not opening in Linux

### ISSUE THREAD

**Issue by molove** [sindresorhus/caprine#1816]
This is happening on both my computers on Linux. When ever I click on a photo, I just get a window full of white and I have to restart Caprine to be able to use it again. This is a new phenomenon, I only came across it today, I rarely use Facebook so am not sure when this first started. This is what it looks like when the photos fail to open

![image](https://user-images.githubusercontent.com/20013346/163441006-d40b66a0-302d-4dbc-8c74-7d83350fbdbe.png)

Everything seems to work correctly under Windows 10 

---

Caprine 2.55.2
Electron 13.6.9
linux 5.15.28-1-MANJARO
Locale: en-GB

**Comment by lefterisgar** [comment]
I hope [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) works for you. It's a fork I've created to merge those kinds of fixes before the devs upstream do.

**Comment by PrimozR** [comment]
Same issue on Windows 10, just updated to 2.55.4 from .2 and there is no difference.

**Comment by lefterisgar** [comment]
> Same issue on Windows 10, just updated to 2.55.4 from .2 and there is no difference.

You will need to go to Help -> About Caprine. The version should be 2.55.4-3. You will need to download MY version as the official one doesn't contain the patch yet.

**Comment by billybhaub** [comment]
I have the same issue on Ubuntu 20.04, with the latest version of Caprine.
A quick workaround I found is to reload Caprine (ctrl+R) while still on the blank screen. The image now shows up without any issue.
But, I have to repeat the procedure everytime I want to open an image.
