### ISSUE TITLE
delete conversation not working RHEL 8 

### ISSUE THREAD

**Issue by pythonyalfa** [sindresorhus/caprine#1817]
Im new to this so forgive me if i didnt find a thread on this issue already. I wasn't able to delete a message in the app im using RHEL 8

**Comment by lefterisgar** [comment]
You could try installing [my fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3). It could be related to another issue that was fixed there.

**Comment by pythonyalfa** [comment]
Thanks! Im new to doing this so bear with me, does it also fix the not being able to log out and switch accounts ? Seems like I can't do that either. Cna you point me how to switch from the version I have to your fork ? Do I just download your code and overwrite my directory that has my install ?

**Comment by lefterisgar** [comment]
Hi and sorry for being late! I'm not sure as I'm not the one who created the patch. I think that RHEL uses .rpm packages. If so just download my release and it will install as an update. The version will change from 2.55.4 to 2.55.4-3. When you finish the installation go to Help -> About Caprine and verify the version. If it's not 2.55.4-3 then you don't have the patch. Also don't forget that if Caprine has been running in the background before the update then the old binary is still loaded. You need to close Caprine therefore.
