### ISSUE TITLE
Caprine does not allow you to change nicknames in Messenger.

### ISSUE THREAD

**Issue by machadofguilherme** [sindresorhus/caprine#1819]
1. Open Caprine.
2. Enter Messenger.
3. Change the nickname of any of the contacts.
---

Caprine 2.55.4
Electron 10.4.7
linux 5.17.2-gentoo
Locale: pt-BR

**Comment by mquevill** [comment]
I believe this was addressed in the changes that went into v2.55.5. Please upgrade to see if this problem still exists.
