### ISSUE TITLE
Images not showing when clicked on (Windows)

### ISSUE THREAD

**Issue by pufd** [sindresorhus/caprine#1821]
When I click on an image in a conversation to view a larger version of it, I'm instead shown a blank screen. There is also no button to go back to the conversation, and escape must be pressed instead.

**Comment by mquevill** [comment]
This issue is addressed in #1815, but has not made it to an official release yet.

**Comment by mjeveritt** [comment]
Also occurs for me in Linux (Ubuntu LTS, KDE)

**Comment by rosoau** [comment]
Same here too on Debian 11. I have to restart after clicking on an image, then copy the image link and open manually in Firefox. Also, only sometimes, Caprine starts as a whole face book page without content instead of the messenger window and a relaunch is required.Thanks guys for an excellent application, good work; it is a huge comittment.

**Comment by rosoau** [comment]
Here is the strange popu
![(7) Facebook_001](https://user-images.githubusercontent.com/13397926/164991825-6622136e-dd90-48e4-9716-425d35d0f12a.jpg)
p

**Comment by billybhaub** [comment]
I have the same issue on Ubuntu 20.04, using latest version of Caprine.
I have found a (very) temporary workaround : when the blank screen appears, I press CTRL+R to reload Caprine, and the image appears.
The downside is, you'll need to repeat for every image.

**Comment by lefterisgar** [comment]
Sorry for spamming here as well but... just download my [fork](https://github.com/lefterisgar/caprine/releases).

**Comment by TheRolf** [comment]
Temporary fix: F5 loads the picture for me.

**Comment by billybhaub** [comment]
> Sorry for spamming here as well but... just download my [fork](https://github.com/lefterisgar/caprine/releases).

I finally got myself to try it, and it works flawlessly. Thanks!

**Comment by mquevill** [comment]
These changes are now in the official releases as of v2.55.5. Please upgrade to a newer version to resolve this issue.
