### ISSUE TITLE
Some functions for group manipulation are broken.

### ISSUE THREAD

**Issue by wallmenis** [sindresorhus/caprine#1824]
Can't add members, can't change name of group, can't change group picture, can't change group theme, can't change group emoji, can't change nicknames: popup menu non existent to do the actions once the option is clicked.

It's the flatpak version if that matters.
---

Caprine 2.55.3
Electron 10.4.7
linux 5.17.3-zen1-1-zen
Locale: en-US

**Comment by lefterisgar** [comment]
Could you please try my [fork](https://github.com/lefterisgar/caprine/releases) and see if the issue persists?
