### ISSUE TITLE
get rid of golden border around message

### ISSUE THREAD

**Issue by dnlw07** [sindresorhus/caprine#1826]
Hello, 
I have noticed that golden border appears around the message when i click on it to select and copy text from that message.
Is it possible to get rid of that message in next update or by a custom CSS script?

Example:
![image](https://user-images.githubusercontent.com/23562689/164267334-82d8d517-9966-4122-8b3d-bd9bdbe1e932.png)

**Comment by lefterisgar** [comment]
Try my [fork](https://github.com/lefterisgar/caprine/releases) and see if you can reproduce it. If you can't, then it will probably be officially fixed in some time.

**Comment by dnlw07** [comment]
@lefterisgar thank you! works like a charm :)

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
