### ISSUE TITLE
Unable to start Caprine

### ISSUE THREAD

**Issue by igorgue** [sindresorhus/caprine#1828]
Hi I'm on *Pop OS 22.04* and when using *Carpine v2.55.4* from the *AppImage* and the *deb* and I get the following error:

```
./Caprine-2.55.4.AppImage       
[14143:0427/112308.485508:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    14143 trace trap (core dumped)  ./Caprine-2.55.4.AppImage
```

```
caprine
[14438:0427/112443.814595:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    14438 trace trap (core dumped)  caprine
```

Since it says *GPU*, I'm running: 

```
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile / Max-Q Refresh] (rev a1) (prog-if 00 [VGA controller])
```

**Comment by lefterisgar** [comment]
Hi! You can have a look [here](https://github.com/sindresorhus/caprine/issues/1805). TLDR: Download my [fork](https://github.com/lefterisgar/caprine/releases). It will probably take some time to be officially fixed.

**Comment by igorgue** [comment]
@lefterisgar That's interesting... why isn't your fork merged?

**Comment by lefterisgar** [comment]
I'm not really sure. There is a pull request open right now but they seem to have some issues.

**Comment by dimisjim** [comment]
same here, but snap worked for me: https://snapcraft.io/caprine :+1:

**Comment by lefterisgar** [comment]
While it's great that it worked, snap does come with a performance penalty.

**Comment by dimisjim** [comment]
> While it's great that it worked, snap does come with a performance penalty.

Is it really that visible?

**Comment by lefterisgar** [comment]
1) Yes it is really visible, as I have tested the Chromium snap vs Chromium deb and the latter starts faster (snap uses compression and doesn't use the shared libraries which are already loaded in RAM), which holds true for this Caprine as well since it uses Electron which itself uses Chromium. Also, snap itself slows down your PC while booting. Now don't get me wrong but you might not notice it that much if you have a powerful PC (unlike me). The list with snap's disadvantages goes on but let's not list it all there :) .
2) Now they both work even on the latest Ubuntu LTS since I have patched the Electron version in my fork. Just try it out if you want.

**Comment by dimisjim** [comment]
> 1. Yes it is really visible, as I have tested the Chromium snap vs Chromium deb and the latter starts faster (snap uses compression and doesn't use the shared libraries which are already loaded in RAM), which holds true for Caprine as well since it uses Electron which itself uses Chromium. Also, snap itself slows down your PC while booting. Now don't get me wrong but you might not notice it that much if you have a powerful PC (unlike me). The list with snap's disadvantages goes on but let's not list it all there :) .
> 2. Now they both work even on the latest Ubuntu LTS since I have patched the Electron version in my fork. Just try it out if you want.
> 
> For the benchmark, the Chrome deb scored higher.

yup, snap is definitely not get most performant.

Will try it out, thanks!

How about an AppImage though? Did you also try rebuilding the app into that? From a dew benchmarks that I have seen AppImage packages can be even more perfomant than deb packages!

**Comment by lefterisgar** [comment]
Sure! There is an AppImage available you can try. AppImages tend to be better IMO. Their only problem is size, and they are also compressed (if you decompress them they will start a little quicker).

Anyways, whatever suits you best!

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
