### ISSUE TITLE
Window shadow disappearing when minimized and restored on macOS

### ISSUE THREAD

**Issue by nahive** [sindresorhus/caprine#183]
When Caprine is minimized (either by button or by shortcut) and then restored to front, the shadow under the window disappears. I've also noticed this when toggling vibrancy effect, but I can't reproduce it in this scenario. Here's the screenshot attached.

<img width="854" alt="screen shot 2017-04-12 at 10 11 33" src="https://cloud.githubusercontent.com/assets/2961723/24970350/d4857c5e-1f68-11e7-9ba8-6a766d70cda1.png">

How to reproduce:

- open Caprine
- minimize it
- click Caprine icon to restore it
- shadow should appear behind window, but it doesn't

**Comment by sindresorhus** [comment]
That sounds like an Electron issue. Probably better to open an issue on https://github.com/electron/electron/issues with a minimal test case.

**Comment by sindresorhus** [comment]
I've been unable to reproduce this using the steps you've outlined.

**Comment by nahive** [comment]
That's weird - I can reproduce it all the time. I'm having caprine opened, I minimize it using cmd + m shortcut and I restore it by clicking the icon in the dock. Caprine looses it window shadow in the process. Let me know if you need other details.
