### ISSUE TITLE
Dockerizing the application

### ISSUE THREAD

**Issue by vaibhavkumar779** [sindresorhus/caprine#1830]
we can add a dockerfile to make this app OS independent. If yes please allow me add a dockerfile to it.
@sindresorhus

**Comment by sindresorhus** [comment]
This project is in maintenance mode, so I'm not interested in adding more stuff to it.

**Comment by yllekz** [comment]
I'd be interested in this as well. I'd rather self-host this app in a container as opposed to installing it. That way I can remote into it from a phone or something. Would be cool if someone put in a PR to add this functionality given the popularity of self-hosted Docker things
