### ISSUE TITLE
Pictures show black

### ISSUE THREAD

**Issue by shobuj-das** [sindresorhus/caprine#1831]
All pictures show black .
the forward option also not working. 

---

Caprine 2.55.2
Electron 10.4.7
linux 5.13.0-41-generic
Locale: en-US

**Comment by Xelbayria** [comment]
I had the same issue with pictures and also videos. 

Forward options work for me just fine. 
_______________________________________________________
Caprine: 2.55.4
OS: Windows 10 Pro (64bit)

**Comment by shobuj-das** [comment]
also, the delete option not working

**Comment by lefterisgar** [comment]
check #1827 for a fix

**Comment by mquevill** [comment]
This issue was fixed in v2.55.5. Please upgrade to a newer version to check that it is resolved.
