### ISSUE TITLE
Pictures, Forward, Remove

### ISSUE THREAD

**Issue by shobuj-das** [sindresorhus/caprine#1833]
I have upgraded the version from 2.55.2 to 2.55.4. Both versions have the same issues.
The picture shows black(white) when they are being clicked on. 
messages and documents are not being deleted.
No messages are being forwarded to others. 
---

Caprine 2.55.4
Electron 10.4.7
linux 5.13.0-41-generic
Locale: en-US

**Comment by lefterisgar** [comment]
I told you to check the other issue for a fix. You didn't and instead you keep creating duplicates.
