### ISSUE TITLE
Whole window black right after install

### ISSUE THREAD

**Issue by mimminou** [sindresorhus/caprine#1835]
I'm having an issue where Caprine just shows nothing when opened, everything is black, When i hover the mouse the cursor icon changes to the text input one (I'm guessing it's the id and password fields ).

Running Fedora 36 (Wayland) on Gnome With Nvidia proprietary drivers.

**Comment by lefterisgar** [comment]
Hi! Check [my fork](https://github.com/lefterisgar/caprine/releases) and see if the issue persists.

**Comment by mimminou** [comment]
> Hi! Check [my fork](https://github.com/lefterisgar/caprine/releases) and see if the issue persists.

Unfortunately the issue still persists ( just tried with the latest RPM v2.55.5-2 ).

**Comment by lefterisgar** [comment]
Really sad... Try running Caprine using the --disable-gpu flag since the proprietary NVIDIA driver isn't really stable on Wayland yet. I also have an NVIDIA gpu and experience similar problems. Also, keep using the fork as the newer Electron that is bundled makes it much better.

**Comment by mimminou** [comment]
Unfortunately even using the gpu disable flag did not solve the issue.

**Comment by lefterisgar** [comment]
Yeah that's unfortunate, it should work. In any case I will point you to [this post](https://www.reddit.com/r/Fedora/comments/qmv8qi/discord_loading_with_black_screen_on_wayland/) on reddit which is a similar case for another app (Discord). You might find the second flag they suggest useful: `--use-gl=desktop`

**Comment by mimminou** [comment]
> Yeah that's unfortunate, it should work. In any case I will point you to [this post](https://www.reddit.com/r/Fedora/comments/qmv8qi/discord_loading_with_black_screen_on_wayland/) on reddit which is a similar case for another app (Discord). You might find the second flag they suggest useful: `--use-gl=desktop`

This worked, thank you ( Actually I even tried the gpu disable flag back and it somehow worked, I think it's partly because I updated my Nvidia driver to 515, which fixed tons of bugs )
