### ISSUE TITLE
I cannot delete a message.

### ISSUE THREAD

**Issue by orbitalchicken** [sindresorhus/caprine#1837]
I click the 3 dots beside a message I wrote.
I select "Delete" (it is labeled "Supprimer" in my french Locale)
Nothing happen, no confirmation dialog appears or anything.
---

Caprine 2.55.4
Electron 10.4.7
linux 5.4.0-97-generic
Locale: fr

**Comment by mquevill** [comment]
Updating to v2.55.5 should resolve this issue.

**Comment by orbitalchicken** [comment]
Thanks. Indeed it work in v2.55.5.
