### ISSUE TITLE
How can i change focus color?

### ISSUE THREAD

**Issue by phucnoob** [sindresorhus/caprine#1838]
![image](https://user-images.githubusercontent.com/69722577/170740869-b8db3e7b-9161-4692-a28d-d3406ea68a32.png)
I do want to style some element but i don't know the class or the element
The focus color looks bad....
Is there any styling documentation?

**Comment by lefterisgar** [comment]
HI! Try my [fork](https://github.com/lefterisgar/caprine/releases) and see if you can reproduce it.
