### ISSUE TITLE
Black screen when enlarging a photo

### ISSUE THREAD

**Issue by maciej-kowalczyk** [sindresorhus/caprine#1839]
After clicking on the send photo, there is a black screen instead of the enlarged photo.
1. Send any photo to someone from your friends.
2. Click on it to enlarge

---

Caprine 2.55.4
Electron 13.6.9
linux 5.13.19-2-MANJARO
Locale: en-GB

**Comment by mquevill** [comment]
Please upgrade to v2.55.5 to fix this issue.
