### ISSUE TITLE
Download zip/doc file - URL signature expired

### ISSUE THREAD

**Issue by dy** [sindresorhus/caprine#184]
My friend sent me files 4 days ago:
![image](https://cloud.githubusercontent.com/assets/300067/25051393/5e546a8c-211a-11e7-80f9-fd805aaf85c5.png)
Clicking on the download we get browser opened with the following content:
![image](https://cloud.githubusercontent.com/assets/300067/25051432/91a4fd8e-211a-11e7-8a0e-eb4befdaa3a5.png)
Clicking "Follow Link" leads to blank page with
![image](https://cloud.githubusercontent.com/assets/300067/25051451/b40de994-211a-11e7-895a-c4a9bb549776.png)

These files are downloadable in facebook messenger

**Comment by veniversum** [comment]
This is probably caused by a stale Facebook CDN link. A new download link should be generated if you reload or restart the app. 

This is a limitation of Messenger app & the CDN, I don't think there's much we can do to prevent it.

**Comment by sindresorhus** [comment]
@veniversum I think we could intercept it and download the file right away instead of opening it in the browser.

**Comment by veniversum** [comment]
@sindresorhus Do you mean upon a `new-window` event when the user clicks to download or automatically download any files that the user receives? It shouldn't matter whether the link is opened in a browser or within electron.

The error will be encountered if the user clicks on a cached download link and the app has been open for a long while.

**Comment by sindresorhus** [comment]
No, I mean when they click the file in the chat.

**Comment by sindresorhus** [comment]
> The error will be encountered if the user clicks on a cached download link and the app has been open for a long while.

So why isn't this a problem in the Facebook Messenger web app?

**Comment by veniversum** [comment]
Probably because the FB Messenger in browser was opened after Caprine, so it had a new link generated but Caprine had a stale link.

If you search for `cdn.fbsbx.com` links in your browser history, most of them past a certain age will not work.

**Comment by sindresorhus** [comment]
Wonder if there's any way we can renew/refresh the links.

**Comment by dusansimic** [comment]
This seems to work now without problems.

**Comment by jaja1722** [comment]
Open this. https://cdn.fbsbx.com/v/t59.2708-21/452977078_2159820731050027_3174728528276052915_n.pdf/1.2-Scientific-Notation-and-Significant-Figures.pdf?_nc_cat=110&_nc_cb=47395efc-74c935b2&ccb=1-7&_nc_sid=2b0e22&_nc_ohc=t7hSHZfh4tsQ7kNvwHPA51T&_nc_oc=AdkO_SxJcJZEL2GF_c3TDyTNwSXeGxF0M0EI4MnXpaxoaKtcNAa9HHVb9cM5Q7OiDx0&_nc_zt=7&_nc_ht=cdn.fbsbx.com&_nc_gid=Eo2iXn5Edjixcfo1_u4xfA&oh=03_Q7cD2gF6iWBVydfMcMDltxhfK6ZB2c9xaKLQq3k7pDtNNAVYtQ&oe=68549468&dl=1

**Comment by emeraldnov2010-lgtm** [comment]
###
