### ISSUE TITLE
Bug in Dark mode of Ubuntu Environment

### ISSUE THREAD

**Issue by sayanta28** [sindresorhus/caprine#1840]
### Issue:
In Ubuntu Linux Environment when Changing the Mode from Light mode to Dark Mode the Interface colour is get broken. Some portions are showing white colour and some portions is showing dark colour.

### Screenshot or Proof: 
![WhatsApp Image 2022-06-02 at 10 42 55 PM](https://user-images.githubusercontent.com/32473531/171683391-443ce1cd-f5c8-4b1a-aaf6-7d33b2aefb84.jpeg)

### Environment Details: 
Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal
Memory: 8Gb
CPU: Intel CORE i5 7th Gen

**Comment by lefterisgar** [comment]
What happens if you try my [fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.5-1)? I can't seem to reproduce it there.

**Comment by sayanta28** [comment]
Thanks for sharing your fork. Now It's working. 
Actually, in the **Snap Store**, the version is old. Below, I attached the screenshot. 
![image](https://user-images.githubusercontent.com/32473531/172040555-2e754f81-4cf1-4205-bb1f-c7e3e90ca2a9.png)

Though Another some bugs I have found in the new release. 

**Colour Breaking in Group Logo inside thread:**
Without Dark Mode:
![image](https://user-images.githubusercontent.com/32473531/172040675-773293fe-1909-4ef8-96b3-ceb4e51ea9c8.png)

With Dark Mode: 
![image](https://user-images.githubusercontent.com/32473531/172040751-f88a682d-abd0-4606-be95-79fa0e6321b1.png)

**Audio Call Logo Invisible:** 
Without Dark Mode: 
![image](https://user-images.githubusercontent.com/32473531/172040705-94971ecd-fe55-4ee6-a783-6f1833e8f264.png)
 
 With Dark Mode: 
 
![image](https://user-images.githubusercontent.com/32473531/172040719-3fcad044-1efa-4f98-8dd1-6ec9f168f50a.png)

**Comment by lefterisgar** [comment]
Oh, I also have those... I really lack the knowledge to fix them though (I have tried). If someone makes a pull request I will update my fork. Just make sure to avoid snap for this reason and because it is waay slower.

Thank you!

**Comment by lefterisgar** [comment]
Well, it took some time but I fixed it! Try out the new version (2.55.6-1) of [my fork](https://github.com/lefterisgar/caprine/releases) and see for yourself!
It is a quite hacky and ugly implementation but it works!
![εικόνα](https://user-images.githubusercontent.com/46350667/173255603-d40c4123-7be5-4247-b6eb-b57e1bb248d6.png)
