### ISSUE TITLE
Scroll doesn't work in list of conversations

### ISSUE THREAD

**Issue by BZab** [sindresorhus/caprine#1841]
Scrolling search results after specifying some phrase in the 'search' field works.
However, list of latest conversations (when search field isn't used) is stuck.
No scrollbar appears and list can be traversed only with arrow keys (or Ctrl+0-9 hotkeys).

---

Caprine 2.52.4
Electron 10.1.5
linux 5.15.0-33-generic
Locale: pl

**Comment by mquevill** [comment]
Please upgrade to v2.55.5 to see if this issue is resolved. If using Snap, you may have to manually install the snap update.

**Comment by BZab** [comment]
How to manually install the snap update?

AppImage version crashes on debug trap:
`
Gtk-Message: 02:07:48.423: Failed to load module "topmenu-gtk-module"
[52484:0604/020750.347685:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Pułapka debuggera/breakpoint (zrzut pamięci)
`

**Comment by mquevill** [comment]
There is a .snap file in the releases section: https://github.com/sindresorhus/caprine/releases/download/v2.55.5/caprine_2.55.5_amd64.snap
I haven't actually used Snap myself, so I'm not familiar with the install process.

**Comment by BZab** [comment]
`sudo snap install <PATH_TO_FILE> --dangerous`

And no, bug is still present.

Caprine 2.55.5
Electron 10.4.7

**Comment by cobra3282000** [comment]
i have Caprine 2.55.5 same bug, scroll not working for contact list.

**Comment by BZab** [comment]
While rebooting the machine didn't help, after some time and multiple Caprine restarts the scroll in 2.55.5 has started working again.
