### ISSUE TITLE
'About caprine' opens window with broken information

### ISSUE THREAD

**Issue by BZab** [sindresorhus/caprine#1842]
![obraz](https://user-images.githubusercontent.com/3043400/171968087-2988a590-1399-4e6e-9439-482a9e6334fb.png)

---

Caprine 2.52.4
Electron 10.1.5
linux 5.15.0-33-generic
Locale: pl

**Comment by mquevill** [comment]
This was fixed in v2.54.0. Upgrading to a newer version should resolve this.
