### ISSUE TITLE
Dark mode icons not adjusted

### ISSUE THREAD

**Issue by RenautMestdagh** [sindresorhus/caprine#1843]
In dark mode, following icons are black when they should be white

file > messenger settings > manage payments & manage blocking icons

![Screenshot from 2022-06-05 17-48-24](https://user-images.githubusercontent.com/82072978/172058964-99bed75c-c088-4eab-88d6-32e7b19faab7.png)

**Comment by lefterisgar** [comment]
Just try [my fork](https://github.com/lefterisgar/caprine/releases) if you don't want to wait for the PR to be merged.
