### ISSUE TITLE
rpm release for opensuse

### ISSUE THREAD

**Issue by jshand2015** [sindresorhus/caprine#1852]
Would it be possible to include rpm packages for rpm distributions

**Comment by dusansimic** [comment]
Since rpm packages are distributed via [copr](https://copr.fedorainfracloud.org/coprs/dusansimic/caprine/), it is possible. Once I test it out and make sure that packages built on copr for opensuse actually work, I'll release them.

**Comment by dusansimic** [comment]
I've added the opensuse rpm to the copr repo. Let me know if there are any issues.

**Comment by lefterisgar** [comment]
I have included rpm in the list of Linux targets so the next build should have an rpm package.

**Comment by dusansimic** [comment]
@lefterisgar I'd rather avoid that. I'm building rpm packages already on my [copr](https://copr.fedorainfracloud.org/coprs/dusansimic/caprine/) repository which is added to the [readme](https://github.com/sindresorhus/caprine#linux) page. I think building rpm package with electron-builder and having them on release page would only create confusion. There should be only one source for packages. If there is a really good reason to have packages on both the release page and distribution repositories (for example snap package is built with ci and then it's published to the snap store so it's the same package) then it's fine, but in this case I'd prefer not doing that.

**Comment by lefterisgar** [comment]
@dusansimic Oh, I'm sorry. I will revert it because you have a good point here.
