### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by reveyo** [sindresorhus/caprine#1856]
Bonjour,
j'ai ce bug:
[47770:0712/152652.521500:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trappe pour point d'arrêt et de trace (core dumped

cdt,
David.

**Comment by lefterisgar** [comment]
#1805 is related. Check it out for a possible solution if you are on Linux.

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
