### ISSUE TITLE
macOS Ventura beta: window is unmovable and title bar is broken.

### ISSUE THREAD

**Issue by apotenza92** [sindresorhus/caprine#1857]
Traffic lights are overlapping profile picture, entire window is unmovable. It's like top area is not registering as a draggable element.
<img width="996" alt="image" src="https://user-images.githubusercontent.com/53612685/178653048-7332969a-8e7a-4938-a32e-27a3674b1169.png">

**Comment by sheldonhull** [comment]
- Related: #410
- Not sure it's specific to Ventura, as this is an issue on 12.5 (21G72) (Monterey).

I'm on 2.55.6 and seems to have the same issue. 
I can only drag if the window is not focused, but as soon as focused there is no drag region.

**Comment by relink2013** [comment]
I can confirm this on 12.5 as well.

**Comment by andrewbrereton** [comment]
This is still an issue on macOS Monetery 12.6.2.

<img width="171" alt="image" src="https://user-images.githubusercontent.com/682893/208218607-658741a3-dde1-481d-b368-e5ad3af4db9f.png">
