### ISSUE TITLE
clicking on an image to see it "full-screen" yields a blank windows until CTRL-R is pressed

### ISSUE THREAD

**Issue by jprobichaud** [sindresorhus/caprine#1859]
I have this weird issue, both on my freshly install Windows 11 laptop and my linux (Pop OS/Ubuntu 22.04) laptop.

When in a chat, someone sends me a picture, if I click on it, I get just a blank window (no buttons, no images).  Then I hit CTRL-R and I can see the picture, the messenger icon/button and the the download and forward buttons (and the prev/next arrows).

How can I debug this?

**Comment by jarnalyrkar** [comment]
I have the same issue, using version 2.56 on windows.

**Comment by TRENT310** [comment]
Same issue since 2.53 and still happening as of today's 2.56 release. Darn I was hoping this update would resolve it, but of course there are always changes happening behind the scenes at Meta that are uncoordinated with the development of independent clients like this. 

My workaround for now, in order to load full-screen media attachments is to use Ctrl+, or File > Messenger Settings which for some reason renders the image or video without a full reload.

**Comment by lefterisgar** [comment]
Does it still occur with the latest release (v2.56.1)?

**Comment by lefterisgar** [comment]
> Does it still occur with the latest release (v2.56.1)?

EDIT: You might be using Messenger's new UI which hasn't rolled out to everybody. If so, unless someone from the dev team receives it, we can't debug the issue.

**Comment by TRENT310** [comment]
Okay, 2.56.1 has broken my workaround completely using the Ctrl+, shortcut. I had to roll back to 2.56.0 for now to continue using Ctrl+, to load images.

I cannot control which users have access to certain user interface versions or what switches to trigger it manually or go back to the previous version. FB/Meta has been known to do this in the past even with other features or redesigns.

**Comment by dusansimic** [comment]
@TRENT310 Are you using some different locale from English?

**Comment by TRENT310** [comment]
@dusansimic No, the locale is showing en_US. 

The other clue is that the 'Install Messenger App' nag button is back in whatever this new UI version is, so the previous workarounds to suppress that have changed once again. Interesting that only appears in Caprine and not when accessing messenger.com with Firefox or Chromium.

**Comment by lefterisgar** [comment]
> @dusansimic No, the locale is showing en_US.
> 
> The other clue is that the 'Install Messenger App' nag button is back in whatever this new UI version is, so the previous workarounds to suppress that have changed once again. Interesting that only appears in Caprine and not when accessing messenger.com with Firefox or Chromium.

Did you try removing Caprine's directory? You might get the old UI again after doing that.

**Comment by TRENT310** [comment]
> Did you try removing Caprine's directory? You might get the old UI again after doing that.

I uninstalled, renamed `%userprofile%\AppData\Roaming\Caprine` to something else, re-installed 2.56.1, a new directory was created upon first launch - and it's the same issue with viewing images full-screen. 

I believe the new UI for Messenger is associated with the account, not the client browser - although forcing the directory to be re-created prompts the next login to go through all 2FA steps and browser verification. The client gets detected as 'Chrome on Windows 10' by Facebook. This is on Win10 Pro 21H1 19043.

**Comment by acorazza** [comment]
I have the same problem, on a fresh install from 2 days ago (never used Caprine on this computer before).

**Comment by dusansimic** [comment]
I'll say this is related to #1906. It will be fixed on next release.

**Comment by PixsaOJ** [comment]
> Does it still occur with the latest release (v2.56.1)?

2.56.1 Flatpak

**Comment by dusansimic** [comment]
I'll close this issue in favor of #1909. This periodically happens so we'll try to fix it asap.
