### ISSUE TITLE
Menu shortcuts don't play well with system shortcuts (mixed)

### ISSUE THREAD

**Issue by bokiscout** [sindresorhus/caprine#1860]
Issue:
Changing keyboard layout (LeftAlt + LeftShift) will move focus to app menu.

Description:
Caprine is usign ALT key to focus / hide / unhide the menu bar (rarely used feature by me).
KDE is using LeftAlt + LeftShift to toggle keyboard language layout (often used feature by me).

Steps to reproduce:
1. Open Caprine
2. Open any conversation
3. Focus the text input field
4. Change the keyboard language (LeftAlt + LeftShift)

Expectations:
- Keyboard layout to be changed
- Text input filed to remain focused

Reality (Bug)
- Keyboard layout is changed (OK)
- Focus is given to caprine menu (NOK)

Recommendation:
1. Provide option to disable the caprine shortcuts completely.
2. Provide option to change Caprine shortcuts
3. Make sure OS / DE shortcuts dont mix with caprine

---
Operating System: openSUSE Tumbleweed 20220714
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.9-2-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-2500 CPU @ 3.30GHz
Memory: 11.7 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: P67A-UD3-B3

Caprine 2.55.7
Electron 10.4.7
linux 5.18.9-2-default
Locale: en-US

**Comment by lefterisgar** [comment]
Hi! Can you try using [this fork](https://github.com/lefterisgar/caprine/releases)? I can't reproduce this issue when using that.

**Comment by bokiscout** [comment]
I can confirm that I can't reproduce with 2.55.7-2.

However, there is one deference:
2.55.7-2 is installed as AppImage
2.55.7 is installed from flathub as flatpack

**Comment by lefterisgar** [comment]
You could also use the rpm package since you are on openSUSE. This will also open faster & consume less disk space.
