### ISSUE TITLE
Scrollbars not following dark mode theme

### ISSUE THREAD

**Issue by frozenpandaman** [sindresorhus/caprine#1864]
![image](https://user-images.githubusercontent.com/7245874/180592416-c5b2f3e2-eeb7-4aa6-9469-c59593b58f3c.png)

Caprine v2.55.5
macOS 12.3.1 (M1/Apple Silicon)

**Comment by lefterisgar** [comment]
Hi! Try out this [fork](https://github.com/lefterisgar/caprine/releases). It might solve your issue.

**Comment by lefterisgar** [comment]
Hi! If you want, you can try [this fork](https://github.com/lefterisgar/caprine) where the issue has been fixed. Note: Currently there are no builds for macOS but you can build it yourself from source.

**Comment by frozenpandaman** [comment]
@lefterisgar Glad you found a fix! I'll just probably wait until this is merged into the main project, hopefully very soon. :)

For now, do you know if there's a temporary fix I can insert into Custom Styles (custom.css) which will solve the display issue? Can't find the commit in which you fixed this exact issue. Thanks!

**Comment by dusansimic** [comment]
@frozenpandaman https://github.com/sindresorhus/caprine/issues/1793 this issue includes the fix that was proposed in a pull request. I'll see if I can find some time to send the PR again.

**Comment by dusansimic** [comment]
Duplicate of #1793
