### ISSUE TITLE
Wrong colors when using names

### ISSUE THREAD

**Issue by OlaAlsaker** [sindresorhus/caprine#187]
The dialog that pops up when using @ in groups has wrong colors in dark-mode.
I guess the background-color of the dialog is wrong.

Please see picture.

![image](https://cloud.githubusercontent.com/assets/7793873/25121291/7f77a09e-2421-11e7-8ee7-fed824f7b4a5.png)

**Comment by sindresorhus** [comment]
Pull request welcome. Should be easy to inspect, find the class, and update `dark-mode.css`.
