### ISSUE TITLE
CI errors and missing file

### ISSUE THREAD

**Issue by lefterisgar** [sindresorhus/caprine#1877]
**EDIT:** Disabling snapStore fixes the issues I've mentioned.

Related:
samuelmeuli/action-snapcraft#36

When pushing a commit the CI succeeds, unless it's a release commit.
![εικόνα](https://user-images.githubusercontent.com/46350667/184981781-a1b331af-6524-4433-a7ea-b8e489d76bb3.png)

After running `npm run release`, the CI is triggered twice and it fails both times.
![εικόνα](https://user-images.githubusercontent.com/46350667/184982024-91ab93d3-d59c-48ad-80b5-b2eef33327c9.png)

Furthermore, the `latest-linux.yml` file is nowhere to be seen on the drafted release:
![εικόνα](https://user-images.githubusercontent.com/46350667/184982258-6af475b0-1611-4706-9df2-718615d63137.png)

**Comment by lefterisgar** [comment]
I have pushed a commit that should fix those issues. The release to Snapcraft worked this time.

**Comment by dusansimic** [comment]
> After running npm run release, the CI is triggered twice and it fails both times.

There shouldn't be any need to run `npm run release` since ci creates a draft release and publishes all artifacts (packages, specifically electron-builder does that). Only thing that needs to be done is turning a draft release into a regular release.

**Comment by lefterisgar** [comment]
> > After running npm run release, the CI is triggered twice and it fails both times.
> 
> There shouldn't be any need to run `npm run release` since ci creates a draft release and publishes all artifacts (packages, specifically electron-builder does that). Only thing that needs to be done is turning a draft release into a regular release.

Isn't this the command that automatically creates the release commit and the tag?

**Comment by lefterisgar** [comment]
Also, are you happy with how things are right now?

**Comment by dusansimic** [comment]
It seems that it does, I've just been doing it manually so I can bump dependencies and lock file on release 😅. It seems that everything is fine now. I'll bump the rpm and flatpak packages probably later today. Thanks for fixing everything!

**Comment by lefterisgar** [comment]
> It seems that it does, I've just been doing it manually so I can bump dependencies and lock file on release
Maybe it can also be done by squashing the second commit using rebase.

> It seems that everything is fine now. I'll bump the rpm and flatpak packages probably later today. Thanks for fixing everything!
Great! And I'm sorry for the trouble!

**Comment by lefterisgar** [comment]
One note: Should I separate the build action (so it doesn't run twice on release)? Because if we don't do that it runs twice and the one fails so you have to manually re-run it.

**Comment by dusansimic** [comment]
> Should I separate the build action (so it doesn't run twice on release)?

Yes, it should run only on tags, not on main branch too. Also, imho, build action should depend on test action. If the test fails, build shouldn't be created. That's why everything was put into one action (it's easier to create dependent tests).

**Comment by lefterisgar** [comment]
Alright I will see what I can do. Maybe copy-pasting the test action could work. But I will have to check the documentation to see if there is a better way.

**Comment by dusansimic** [comment]
> Maybe copy-pasting the test action could work.

If you mean making a duplicate of the test action, I don't really like that option. The old ci configuration was working quite well I think. Check out it was done as an inspiration but it's probable that it's enough for it to work.

**Comment by lefterisgar** [comment]
> I don't really like that option.
Me neither.

> The old ci configuration was working quite well I think.
It tries to build the whole application for all platforms on each commit. This is so slow and frequently results in errors and sometimes even overlaps with the actual release.

**Comment by dusansimic** [comment]
> It tries to build the whole application for all platforms on each commit.

This could be avoided by running the build job only on tags. That way tests would always run and builds would run only on tags and when tests pass.

**Comment by lefterisgar** [comment]
I agree. Looks like a good solution indeed.

> The old ci configuration was working quite well

This is what confused me but now I understand.

**Comment by lefterisgar** [comment]
Also because we are discussing about CI I wanted to mention something else.
Would you agree to have my Packagecloud key added as a GitHub secret over there so users can update Caprine without extra software (using APT)? At the moment this integration is done on my fork but it would be great if everything was done in a single place.
