### ISSUE TITLE
Bad rendering with dark mode

### ISSUE THREAD

**Issue by hydrielax** [sindresorhus/caprine#1880]
# Description

A large empty band appears on top of the window in dark mode. 
![image](https://user-images.githubusercontent.com/70099779/185698134-9d2d88c6-68ee-4f7c-ae8f-b936e486c7b2.png)

Environment: using Kubuntu 22.04 with Caprine installed as a flatpak package.

# Possible solution

Change the css variable `--header-height` to `0px` instead of `56px` in `.__fb-dark-mode` rule. Not sure if it is the right thing to do or if it has side effects but it worked for me.

**Comment by lefterisgar** [comment]
Yes this issue will be fixed in the next release.
