### ISSUE TITLE
Can't enable darkmode [Arch Linux]

### ISSUE THREAD

**Issue by Eris-JBG** [sindresorhus/caprine#1887]
I have the caprine package installed via pacman on arch, and as of 2.56, i can't enable dark mode at all. This issue persists in 2.56.1. I tried removing caprine via pacman, and removing ~/.config/Caprine before reinstalling, and still no long. Going to Debug -> Show Settings also shows `theme` as `"dark"`.

**Comment by lefterisgar** [comment]
Really weird. I haven't experienced such an issue.

**Comment by dusansimic** [comment]
Arch package is packaged in a different way (it uses external electron and runs the build source with it instead of packaging it with electron builder so it makes sense that it didn't happen on other distros). I'm investigating as I'm writing.

**Comment by dusansimic** [comment]
```
Unable to load preload script: /usr/lib/caprine/dist-js/browser.js
```

This error is thrown in the dev tools console.

**Comment by lefterisgar** [comment]
> Arch package is packaged in a different way (it uses external electron and runs the build source with it instead of packaging it with electron builder so it makes sense that it didn't happen on other distros). I'm investigating as I'm writing.

Dušan is correct. Does that mean we need to contact the maintainer?
Does the AppImage work in the meantime?

**Comment by Eris-JBG** [comment]
Yea tbh I don't really know what's going on with it. Initially i was seeing the bug around the bar at the top in dark mode, and switched to light mode, and since then I have not been able to switch back. If it helps, when i go to theme under View in the top bar, it has both Light Mode and Dark Mode with a check next to it, rather than the check disappearing on one when i select the other. the config.json also has the proper theme set. I will check to see if the behavior is the same in the appimage.

**Comment by dusansimic** [comment]
> Does that mean we need to contact the maintainer?

I wouldn't go as far as that for now. I'd rather first investigate myself a bit more. Once we know the cause of the issue, if it's related to the PKGBUILD I'll report it via Arch Bugtracker.

**Comment by lefterisgar** [comment]
> > Does that mean we need to contact the maintainer?
> 
> I wouldn't go as far as that for now. I'd rather first investigate myself a bit more. Once we know the cause of the issue, if it's related to the PKGBUILD I'll report it via Arch Bugtracker.

Awesome! Thanks for tracking down the issue!

**Comment by Eris-JBG** [comment]
I checked the appimage, and it works as expected, even defaults to dark mode like it should, so def something about the version in pacman. I am seeing some errors in the chromium devtools console within the app on the one of which is not present in the appimage, i'll paste it here tho it's not the most helpful. It does appear to be coming from renderer_init.

```
TypeError: Cannot read properties of undefined (reading 'app')
    at Object.<anonymous> (VM143 index.js:8:45)
    at Object.<anonymous> (VM143 index.js:15:3)
    at Module._compile (VM97 loader:1120:14)
    at Module._extensions..js (VM97 loader:1175:10)
    at Module.load (VM97 loader:988:32)
    at Module._load (VM97 loader:829:12)
    at c._load (VM123 asar_bundle:5:13343)
    at i._load (VM126 renderer_init:33:356)
    at Module.require (VM97 loader:1012:19)
    at require (VM96 helpers:102:18)
```

**Comment by dusansimic** [comment]
It looks to me like it's an issue with the remote module. I'm trying to figure out what's wrong right now but it might take some time.

**Comment by SlouchyButton** [comment]
I had same issue on Arch linux, but this escalated to not being able to start the app at all. I think this might be related issue, so I first comment here, eventually can make a separate issue.
When running caprine through CLI this is the error:
`caprine
Error launching app
Unable to find Electron app at /home/slouchy/ 

Cannot find module '/home/slouchy/ '
Require stack:
- /usr/lib/electron/resources/default_app.asar/main.js
- `
I have tried reinstalling with -Rns attributes (so the config files should be gone. I have also tried manually deleting the user config in home/.config/caprine, but didn't help.

**Comment by dusansimic** [comment]
I think I found the issue but I'm still working on fixing it. The problem is that `electron-is-dev` package needs to be patched in order to work on Electron 20 which is already being done but Arch build step installs dependencies with `npm install --ignore-scripts` which skips the postinstall script which contains the patch command. Also, it installs dependencies twice, once for building and once for production (without dev dependencies) which make a problem because `patch-package` is a dev dependency.

I'll work on this but I can't guarantee when it will be done. A long term solution is to fix the `electron-is-dev` package and bump dependencies on `electron-util` and `electron-debug` but that will also take some time.

**Comment by dusansimic** [comment]
Okay, I've found a way to fix it and I'll report it to Arch Bugtracker. Once the package maintainer fixes it, the issue will go away.

**Comment by freswa** [comment]
I've just pushed `caprine-2.56.1-2` - pls test :)

**Comment by dusansimic** [comment]
Everything works without issues for me. Thank you @freswa for the quick response!
