### ISSUE TITLE
Gemfury repository produces high(spammy) output on console for apt update

### ISSUE THREAD

**Issue by megatog615** [sindresorhus/caprine#1888]
This kind of output on the console is quite unsightly. It's like spamming my console. I've already done an update before and it still does this.

```
Ign:1 https://apt.fury.io/lefterisgar  InRelease
Hit:2 http://deb.debian.org/debian testing InRelease
Hit:3 http://deb.debian.org/debian testing-updates InRelease
Ign:4 https://apt.fury.io/lefterisgar  Release
Ign:5 https://apt.fury.io/lefterisgar  Packages
Ign:7 https://apt.fury.io/lefterisgar  Translation-en
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)
Get:5 https://apt.fury.io/lefterisgar  Packages [590 B]
Hit:12 http://deb.debian.org/debian-security testing-security InRelease
Ign:7 https://apt.fury.io/lefterisgar  Translation-en                
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)         
Ign:7 https://apt.fury.io/lefterisgar  Translation-en          
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)     
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)    
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)    
Ign:7 https://apt.fury.io/lefterisgar  Translation-en     
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US  
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:7 https://apt.fury.io/lefterisgar  Translation-en
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:7 https://apt.fury.io/lefterisgar  Translation-en
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:7 https://apt.fury.io/lefterisgar  Translation-en
Ign:8 https://apt.fury.io/lefterisgar  Translation-en_US
Ign:9 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:10 https://apt.fury.io/lefterisgar  Contents (deb)
Ign:11 https://apt.fury.io/lefterisgar  Contents (deb)
```

**Comment by dusansimic** [comment]
Could you post the repo file for Caprine? If you used recommended settings, it should be located in `/etc/apt/sources.list.d/caprine.list`.

**Comment by lefterisgar** [comment]
I can confirm this kind of issue. I will see what change can be done in order to fix it.

**Comment by lefterisgar** [comment]
It seems like I had fixed it in the script but not in the manual installation steps. Should be okay now.

**Comment by lefterisgar** [comment]
Just re-run the script or the commands below and it should sort itself out automatically.

**Comment by megatog615** [comment]
I did not use the script. I simply copied the repository line in the script into a new file at /etc/apt/sources.list.d/caprine.list

I've added repositories tons of times in the past. I didn't need a script to do it for me.

Thanks for fixing the problem. While I'm here, have you considered adding the caprine.list into the debian package so it gets automatically added when you install it? Other projects sometimes do this for convenience, although I'm not sure if that was sit right with every user.

**Comment by lefterisgar** [comment]
> I've added repositories tons of times in the past. I didn't need a script to do it for me.

It's okay whatever you use! :) I just forgot to update the manual install steps.

> While I'm here, have you considered adding the caprine.list into the debian package so it gets automatically added when you install it? Other projects sometimes do this for convenience, although I'm not sure if that would sit right with every user.

Yes, that's definitely something to consider. Right now the APT repo is unofficial (maintained by me) so it's not a good idea to do it. When we make it official, we will decide if it's worth it because as you have said not everyone would want it.
