### ISSUE TITLE
Caprine 2.0: app fails to work on current AMD drivers

### ISSUE THREAD

**Issue by hakur0** [sindresorhus/caprine#189]
Since 2.0, Caprine's window is completely blank after opening it. When I force AMD drivers to use my main GPU, the window remains blank. When forcing it to use my processor's GPU, the window shows up after some seconds, but it updates the screen every 5 to 10 seconds, so it's kind of impossible to use it.

Releases 1.8 and below work fine.

OS: Windows 10, Creators Update, 64 bits
GPU: AMD Radeon R7 M260 / Intel HD 4400
Drivers: Radeon 17.4.2 / Intel 20.19.15.4531

Where can I find electron's logs? Didn't seem to find them anywhere.

**Comment by sindresorhus** [comment]
Probably an issue with latest Electron. Do you have Vibrancy mode turned on? If yes, try turning it off (In the "View" menu).

**Comment by hakur0** [comment]
There's actually no vibrancy mode on any menu, for some reason. Tested on 2.1.0.

![screenshot](http://i.imgur.com/utdb3WY.png)

Also, just noticed that, when I'm forcing electron to use my Intel GPU, the window only updates it's content if I move it around the screen. Otherwise, it updates once after loading the app, and then stops redrawing the window forever.

**Comment by sindresorhus** [comment]
Try out the latest version of Caprine. It has been upgraded to many newer Chrome versions in the meantime, so this issue is probably fixed. Even if it's not, it's outside the control of this app, and it will have to be fixed by Chrome.
