### ISSUE TITLE
Caprine 2.55.4-3 on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by neutron1954** [sindresorhus/caprine#1890]
Since updating to Caprine 2.55.4-3, I've noticed that it stops receiving texts a few seconds after launching it.  But if I close it and relaunch it, it updates and displays newly received texts, and then stops receiving texts again.   The texts I am referring to are Facebook Messenger texts.

Bob Reed

---

Caprine 2.55.4-3
Electron 13.6.9
linux 5.15.0-46-generic
Locale: en-US

**Comment by lefterisgar** [comment]
First of all, this is an **unofficial version** made by me. Secondly, update to the latest official version which is now v2.56.1.

**Comment by HughPH** [comment]
With V2.56.1 I get what might be the same behaviour, but basically the whole UI locks up except the menus. I have hardware acceleration _disabled_.

It works on:
An Intel Celeron N3350 with 4GB RAM and Intel HD 500 graphics

It fails on:
An AMD Ryzen 5800X with 64GB RAM and Nvidia RTX 3080ti

**Comment by lefterisgar** [comment]
> It's no longer failing. Perhaps facebook had a bug?

Most likely...
