### ISSUE TITLE
Make the APT & COPR repositories official

### ISSUE THREAD

**Issue by lefterisgar** [sindresorhus/caprine#1895]
In the latest release, we have introduced automatic updates support for more distros, including deb based ones using APT. Right now, all the integration is done on my fork which is not really easy to manage because I have to sync on every new release and monitor both repositories for CI fails etc.

What I would like is that my Gemfury token is added here as a secret (GEMFURY_TOKEN).
@sindresorhus I don't have a problem if you want to create a new account, but I think it isn't needed.

When this is done, I can tweak the CI to upload to Gemfury on every new release and also add the automated BASH script here.

**NOTE:** The APT repo (including all the automation done on my fork) has been tested and is proven to work.

## Benefits:

- More transparent distribution process
- Less time required to push a new release to all users
- Reduced complexity
- Less prone to errors

**Comment by dusansimic** [comment]
While this is discussed, we could look into adding a webhook for my [COPR]() repository. That would automate distribution of rpm packages for RHEL based distros and openSUSE. It would however be ideal to put rpm spec file into this repo so it could be maintained here and updated before every release.

**Comment by lefterisgar** [comment]
Great idea! Ideally every distribution method should be added in this repository so if you can, open a PR or push directly whatever change is needed. I suppose that pushing to COPR requires a token, right?

**Comment by dusansimic** [comment]
> I suppose that pushing to COPR requires a token, right?

Actually no. We only need to add a webhook to this repo which is called on every release. COPR pulls this repo (which will contain the spec file) and it will build Caprine.

**Comment by lefterisgar** [comment]
> > I suppose that pushing to COPR requires a token, right?
> 
> Actually no. We only need to add a webhook to this repo which is called on every release. COPR pulls this repo (which will contain the spec file) and it will build Caprine. The webhook will have to be added by Sindre tho.

I see. Yes at this point we can't do much about it. So @sindresorhus needs to add the webhook and the token. How do I share it with him? Is an email good enough?

**Comment by sindresorhus** [comment]
> What I would like is that my Gemfury token is added here as a secret (GEMFURY_TOKEN).

Sure. Just email me the token. My email is in my profile.

**Comment by lefterisgar** [comment]
> > What I would like is that my Gemfury token is added here as a secret (GEMFURY_TOKEN).
> 
> Sure. Just email me the token. My email is in my profile.

Great! I've sent you an email.
