### ISSUE TITLE
Remove "install messenger desktop" button

### ISSUE THREAD

**Issue by piotreknow02** [sindresorhus/caprine#1897]
Remove the "install messenger desktop" button in the bottom left corner on sidebar
<img width="560" alt="Zrzut ekranu 2022-08-28 o 14 35 05" src="https://user-images.githubusercontent.com/65082017/187074434-84e24eb4-a78d-46c3-baf6-12bce54c0fd8.png">

**Comment by dusansimic** [comment]
This should've been fixed by one of recenet versions of Caprine. Which one are you running?

**Comment by dusansimic** [comment]
Good, could you send a pr or the updated query selector for the banner?
