### ISSUE TITLE
Unnecessary space between the menu and the conversion

### ISSUE THREAD

**Issue by pawelswiszcz** [sindresorhus/caprine#1898]
Hello,
I would like to report a small bug.Well, on Dark Mode there is a small unnecessary space between the menu and the conversion of which there is no light mode.

How to repeat the problem: View -> Theme -> Dark Mode

OS:
Description: Manjaro Linux
Release: 21.3.7
DE: gnome 42.4

Thanks for your hard work and this application!

![obraz](https://user-images.githubusercontent.com/1814271/187088450-628bd59b-0491-408a-821b-11ec2c4d26dd.png)

**Comment by dusansimic** [comment]
This should be fixed with the latest release of Caprine. Which version are you running?

**Comment by pawelswiszcz** [comment]
It seems I'm using the old version 2.55.7. I'll check a fresh one. Thanks for answer
