### ISSUE TITLE
Error on building in Ubuntu

### ISSUE THREAD

**Issue by vikas-parashar** [sindresorhus/caprine#19]
Hello,

I tried to build caprine on ubuntu and the following errors occured(http://pastebin.com/0M4WuxcY).

**Comment by sindresorhus** [comment]
You need to run `$ npm run build-linux`.

**Comment by vikas-parashar** [comment]
Tried. Still not working. http://pastebin.com/7ezqP7hW

**Comment by sindresorhus** [comment]
Did you run `$ npm install` first?

**Comment by vikas-parashar** [comment]
yeah, `npm install` followed by `npm start`.

**Comment by sindresorhus** [comment]
Not really sure where it's failing. Try installing `electron-packager` globally and try each command separately.

```
$ electron-packager . Caprine --overwrite --out=dist --ignore='^/dist$' --ignore='^/media/(?!Icon.png$).*' --prune --platform=linux --arch=x64 --app-bundle-id=com.sindresorhus.caprine --app-version=0.1.2 --version=0.33.3
```

```
cd dist/Caprine-linux-x64/
```

```
zip -ryq9 ../Caprine-linux-0.1.2.zip *
````

**Comment by vikas-parashar** [comment]
Since first error on building was `Command failed: /bin/sh -c npm prune --production`. I tried by removing `--prune` from the command and it worked.

**Comment by vikas-parashar** [comment]
I will try this on another system and check if error reproduces.

**Comment by vikas-parashar** [comment]
I tried by adding `npm prune --production` like this
`"build-linux": "npm prune --production && electron-packager . $npm_package_productName --overwrite --out=dist --ignore='^/dist$' --ignore='^/media/(?!Icon.png$).*' --prune --platform=linux --arch=x64 --app-bundle-id=com.sindresorhus.caprine --app-version=$npm_package_version --version=$npm_package_electronVersion && cd dist/Caprine-linux-x64/ && zip -ryq9 ../Caprine-linux-\"$npm_package_version\".zip *"` and it worked.

I am not sure if it can be considered as temporary fix untill [electron-packager](https://github.com/maxogden/electron-packager) resolves the issue.

**Comment by sindresorhus** [comment]
I don't want to end up with a bunch of temporary workarounds. I'm the only one that needs to build anyways. If for some weird reason you need this just work around it locally.

**Comment by vikas-parashar** [comment]
I suggested this fix, because it's same as what `--prune` flag do(at least that what I thought) and for other devs who might want to builld for some reason but I might be wrong since you know better and I'm just a learner so I'll try not to fix things again in these ways. Thanks!!
