### ISSUE TITLE
Cannot view large image

### ISSUE THREAD

**Issue by Jess4da** [sindresorhus/caprine#1909]
when click on image that anyone sent to chat then whole screen disappeared, need to hit `esc` to exit from it, no big image shown

![image](https://user-images.githubusercontent.com/55921466/189293390-d172d895-ce28-4549-ac36-78df9b9a78e1.png)

---

Caprine 2.56.1
Electron 20.0.3
win32 10.0.19044
Locale: en-GB

**Comment by dusansimic** [comment]
Happens due to #1906. New version will have the fix.

**Comment by tloc241** [comment]
man, i have this issue when the app have a new design :(

**Comment by Invactive** [comment]
Same, error still exist. Version 2.56.1

**Comment by VasilisTachta** [comment]
Removing hide-preferences-window class from html tag seems to fix the issue until relaunch.

**Comment by tolgaerok** [comment]
> Removing hide-preferences-window class from html tag seems to fix the issue until relaunch.

how?

**Comment by tolgaerok** [comment]
oh ok found the class by pressing ctl+shift+i.... so where is this html tag stored on the local machine?

**Comment by dusansimic** [comment]
> so where is this html tag stored on the local machine

It's part of a Caprine mechanism for loading saved preferences. This will be fixed by #1910 and it will work fine on the new release. I'd recommend that you don't change the Caprine code in order to remove hide-preferences-window class since it might cause other unwanted issues.

**Comment by tolgaerok** [comment]
> > so where is this html tag stored on the local machine
> 
> It's part of a Caprine mechanism for loading saved preferences. This will be fixed by #1910 and it will work fine on the new release. I'd recommend that you don't change the Caprine code in order to remove hide-preferences-window class since it might cause other unwanted issues.

ok, any idea when update will come out

**Comment by dusansimic** [comment]
> ok, any idea when update will come out

When we (developers) have enough free time to fix it. I can't promise anything now.

If anyone is interested in helping out, feel free to send a pull request with a proposed fix.
