### ISSUE TITLE
cannt forward messege 

### ISSUE THREAD

**Issue by tloc241** [sindresorhus/caprine#1918]
new mess layout cause me this problem, relaunh the app feel time but still not fix

**Comment by dusansimic** [comment]
It will be fixed by #1910

**Comment by Tristanslayer** [comment]
Hello, I am sorry but how do I use your pull request? I only know how to install from the releases section. Pardon me thank you.

**Comment by lefterisgar** [comment]
We need to merge it and then create a new release. You can't "use" a PR unless you have the knowledge to set up a dev environment.

**Comment by Tristanslayer** [comment]
thank you very much!
