### ISSUE TITLE
Sidebar on the Left?

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1919]
After reinstalling 255.6 again but ending up loading 256.1 anyway, a useless Sidebar has appeared to the left with Chats, People, Marketplace, Archived, Requests buttons. 
I can't get rid of it. Never seen this useless space hog before.

---

Caprine 2.56.1
Electron 20.0.3
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment]
It's added by the messenger website. At this point we don't plan on adding an option to remove/hide it. First we would like to fix all issues caused by it.
