### ISSUE TITLE
Cannot download files from within the Conversation

### ISSUE THREAD

**Issue by a224515a** [sindresorhus/caprine#1923]
the pointer changed to a "hand" when I moved the mouse to the file.
however, it was no response when I clicked 
any prompts or popup menu was not shown

(I can download the file using the fb website)

---

Caprine 2.56.1
Electron 20.0.3
win32 10.0.19044
Locale: zh-TW

**Comment by dusansimic** [comment]
Might be releated to #1906 but not yet verified

**Comment by dusansimic** [comment]
I've confirmed it, it's due to said issue.
