### ISSUE TITLE
can't remove messenge, can't forward both messenge and pic/file

### ISSUE THREAD

**Issue by tloc241** [sindresorhus/caprine#1924]
i dont have any of though issue when use debian base, arch is weird
also, can i revesre to old messenger layout?
---

Caprine 2.56.1
Electron 20.0.3
linux 5.15.65-1-MANJARO
Locale: en-US

**Comment by dusansimic** [comment]
What version of Caprine do you use on the Debain based machines?

> also, can i revesre to old messenger layout?

As far as we know, that is not possible. Facebook decides who gets the new ui and when.

**Comment by tloc241** [comment]
> 
right now it on 2.56.1, pretty up to day :)

**Comment by dusansimic** [comment]
You should have the same behavior if the versions are the same. What package format are you using for Manjaro and what for the Debian based distro?
