### ISSUE TITLE
picture not viewabe when clicked on

### ISSUE THREAD

**Issue by tolgaerok** [sindresorhus/caprine#1928]
picture attachments are not viewable when clicked on

---

Caprine 2.56.1
Electron 20.0.3
linux 5.15.0-48-generic
Locale: en-GB

**Comment by dusansimic** [comment]
Duplicate of #1909

**Comment by tolgaerok** [comment]
dosnt work. still no view of image

**Comment by dusansimic** [comment]
This issue is not closed as solved, it's a duplicate issue.
