### ISSUE TITLE
Unify all the colors used in darkmode.css using CSS variables

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#193]
Less duplication.

https://developers.google.com/web/updates/2016/02/css-variables-why-should-you-care

**Comment by shankariyerr** [comment]
@sindresorhus You mean, like this?
- [Method 1](https://gist.github.com/shankariyerr/155a28069c7efbb3cbd10f5a3acaaf38#file-dark-mode-css-variables) use CSS variables (as you suggested)
- [Method 2](https://gist.github.com/shankariyerr/155a28069c7efbb3cbd10f5a3acaaf38#file-unified-dark-mode) Method one + bring everything under one roof

**Comment by sindresorhus** [comment]
Method 1, it's easier when we need to have comments for each item. Also not all items have both background and color.
