### ISSUE TITLE
Attachment indicator broken color in dark mode

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1932]
![Screenshot from 2022-10-12 08-43-51](https://user-images.githubusercontent.com/12685466/195269481-720c2859-d2c7-4399-a0f3-a5e79ceee483.png)

It should probably have a dark background so it would blend in a bit more.

**Comment by sfrunza13** [comment]
Could I maybe give this a shot?

**Comment by sfrunza13** [comment]
![image](https://user-images.githubusercontent.com/77400826/195460218-5d816e45-ec1a-4466-bd3d-6507cfb87df7.png)
is the base 10 color in your dark-mode.css dark enough?

Should I also take a look at the name tag coloring? Or is this a part of a diff issue?
![image](https://user-images.githubusercontent.com/77400826/195460310-848db0d9-67a7-4396-8721-e9a49a2e1367.png)

**Comment by dusansimic** [comment]
I'd prefer that variables from `__fb-dark-mode` selector are used. Those are the ones provided by the Messenger website. However, most of the times these kinds of problems are caused by some class having hardcoded light colors. I'd recommend instead using a solution done in #1931. You'll just need to find that class that is causing the issue.

> Should I also take a look at the name tag coloring? Or is this a part of a diff issue?

There is no issue open for this so feel free to fix it too 😁.

**Comment by dusansimic** [comment]
Also, add a todo comment like there is one in the pr i linked in my previous comment. That way we can know which css styles are our design and which are patches for Facebooks buggy website 😅.
