### ISSUE TITLE
Video chat pill wrong icon color in dark mode

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1935]
![image](https://user-images.githubusercontent.com/12685466/195815095-e61d7578-43b9-4d56-a3bb-48712959cbf6.png)

**Comment by Anuran12** [comment]
@dusansimic  I want to fix the issue.

**Comment by dusansimic** [comment]
Feel free to work on this :). Send a pull request once you've made a working version. Take a look at some of past pull requests (#1933 and #1931 for example) as an inspiration how to fix the issue.
