### ISSUE TITLE
What are the command line options?

### ISSUE THREAD

**Issue by jistjak** [sindresorhus/caprine#1954]
it's not a bug or problem, i'm just wanting to know if there are any arguments we can pass to caprine in command line.
for example `caprine -h` would start caprine in minimized (or hidden) mode.
I don't know if `-h` is an option, i just use it to demonstrate my point.

Also could you please add the list of command line options to the readme.md and/or your website so others can benefit from the information thank you.

**Comment by dusansimic** [comment]
Currently, Caprine doesn't have any command line options but this feature could be explored. In general Electron apps don't have command line options, usually those startup settings are configured in the app itself (for example if you'd like it to start hidden, you have and option for that in `File > Caprine Settings > Launch Minimized`).

What other options are you looking for and what particular use case would you have for command line options?

**Comment by dusansimic** [comment]
> -h start hidden/minimized. This could be useful for starting caprine in the background during system start-up.

Is there a reason why you wouldn't use regular Caprine settings for starting hidden?

> -w=NUM set the window's width with NUM except replace NUM with a number of pixels
> -h=NUM set the window's height with NUMber of pixels. avoid conflict with -h by checking for "=" or just change -h to something else.
> -x=NUM set the window's left edge's position along the screen's horizontal axis (in pixels). 0=far left
> -y=NUM set the window's top edge's position along the screen's vertical axis (in pixels). 0=top of screen

Seems like an unnecessary feature, it's already being done automatically (saving size and window position on close).

> -account=UserID Start an instance with the specified userid. Must be signed in previously obvs, require password if needed.

We don't support that at the moment because Messenger website does not support it so we wont consider this one.

> -banana automatically block/ban every user with the name "Ana" just for the lulz... get it? BanAna Ban-Ana. I'm lame ik.

Why would a user want to do that on startup?

> -theme="Path.XML" Use a custom theme (doesnt have to be xml, it's just an example).

Users can already add a theme through the custom.css file.
