### ISSUE TITLE
Confirmation for sending image via paste action

### ISSUE THREAD

**Issue by veniversum** [sindresorhus/caprine#196]
Currently Messenger will automatically send any image data in the clipboard upon a paste action (`Ctrl/Cmd+V`), without any confirmation from the user. This can lead to unintentional sending of images.

Other messaging services like Telegram offers a confirmation prompt before sending the image in the clipboard.

We have the ability to [check the format of the clipboard content](https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardavailableformatstype) and alter the default behavior of the paste action.

**Comment by sindresorhus** [comment]
👍 👍 I'm always scared when I send an image with paste.

**Comment by veniversum** [comment]
Any suggestions on the best implementation? This is what I have currently: https://github.com/veniversum/caprine/commit/88b00f4e594fcb10d48816be996b1b4c67cb6b75

I can think of 2 ways to implement this:
1. Hook into `webContents.paste` function.
    - Doesn't seem to work/be possible, <kbd>ctrl</kbd><kbd>v</kbd> seems to be bypassing that completely. The one in edit menu works though.
2. Override OS default behavior using global shortcut.
    - Testing using custom menu item, but can't override default OS behavior. Global shortcut that is registered/unregistered on window focus works fine. Paste action via menu bypasses this, since we are only checking for the keyboard shortcut. 

Also it is difficult to display the image without using creating some custom UI elements, currently I've just used the icon area in the dialog box to show a small preview of the image. Here's what it looks like on Windows, no idea what it looks like on OSX/linux. 

![image](https://cloud.githubusercontent.com/assets/6357330/25695898/d80e19c6-30ac-11e7-95f0-70b30a7ed12a.png)

**Comment by sindresorhus** [comment]
I think a dialog box is good enough for now. This is how it looks on macOS:

<img width="532" alt="screen shot 2017-05-05 at 14 00 36" src="https://cloud.githubusercontent.com/assets/170270/25735121/88613fbc-319b-11e7-9152-95ec7b8927cf.png">

Can you do a pull request?

**Comment by sammarcus** [comment]
This is a really clever feature (for whatever reason clipboard images seems to be [buggy](https://github.com/rsms/fb-mac-messenger/issues/393) in what I used before Caprine). 

I would love if it was possible to toggle these confirmations, so I can turn them off when I have a lot of images to share 🤓

**Comment by sindresorhus** [comment]
If you're going to send multiple pictures, it's better to drag-n-drop or use the file picker.
