### ISSUE TITLE
[Linux issue] Typing delayed on Wayland

### ISSUE THREAD

**Issue by Pheggas** [sindresorhus/caprine#1960]
Hello. So i reinstalled my machine, this time with fresh Fedora 36 and Gnome as DE. By default, the Wayland option is selected so i logged in as my user, installed some flatpaks and tried Caprine too. 

At first it went great-ish but then i noticed that when i type something, at some point (and letter) it will stuck for a second and after then will display the letter. The funny thing on this is that when i continue typing before that 1 second mark, it will eventually show the "missing" letter as soon as i type another one.

It is really hard to describe and i eventually can send you a example video if you will want. Another interesting part is that i tried Caprine on my KDE setup (same Fedora 36 but this time with KDE Plasma) and X11 / Wayland. On both it worked well and didn't have this issue. So i'm not sure if i should write the issue here or on the Fedora / Wayland forum.

**Comment by dusansimic** [comment]
This sounds more like a Fedora/GNOME/Wayland issue. I run Fedora 38 (before that Fedora 37) on Wayland and have no issues, both with rpm and flatpak packages. I'll close this issue now since I don't think this is related to Caprine however if the issue persists, reach out again.
