### ISSUE TITLE
Privacy setting ain't included on Windows version

### ISSUE THREAD

**Issue by CSTE7007** [sindresorhus/caprine#1962]
Tested on:
- Windows 11 22H2 version
- Caprine-Setup-2.56.1 version 

Ain't included  Privacy settings at Caprine>File menu so the following features are unavailable:
- Block typing indicator
- Block seen indicator 

The logout isn't working. So when I logged out and relaunched/restarted Caprine I found myself logged in.

**Comment by dusansimic** [comment]
Explanation https://github.com/sindresorhus/caprine/issues/1930#issuecomment-1272502301
