### ISSUE TITLE
2.57.0 video/audio call application screen goes white & crashes

### ISSUE THREAD

**Issue by vanastasis** [sindresorhus/caprine#1964]
Caprine 2.57.0
6.0.0-kali3-amd64
Gnome 43.1

when making video or audio call it goes white and crashes, back to 2.56.1 and working again.

**Comment by orucky** [comment]
I can confirm for:

Caprine 2.57.0
Ubuntu 18.04.6 LTS (bionic)
GNU/Linux x86_64 5.4.0-132-generic #148~18.04.1-Ubuntu SMP Mon Oct 24 20:41:14 UTC 2022
KDE 5.12.9 (Plasma) / 5.44.0 (Frameworks) / 5.9.5 (Qt)

**Comment by Yamboy1** [comment]
Repro on Caprine 2.57.0 on Fedora 37, Cinnamon desktop

**Comment by manosmic** [comment]
same here 2.57.0
ubuntu 22.04 lts
gnome 42.5

**Comment by TT-gthb** [comment]
Same on MacOS Mojave 10.14.6, Caprine v2.57.0

**Comment by vanastasis** [comment]
2.57.1 same issue, video turns white then crashes.

Gnome 44
OS: Kali 64
Kernel: 6.1.0-kali7-amd64
