### ISSUE TITLE
dark mode doesnt set dark the menubar

### ISSUE THREAD

**Issue by EgyipTomi425** [sindresorhus/caprine#1965]
Hello! Id like if I am in dark mode, the menubar should turn on dark mode, because this white strip is bothering.
(The file, edit, help sidebar)

**Comment by dusansimic** [comment]
Which operating system and which version are you using. If it's Linux, what desktop environment/window manager are you using?

**Comment by lefterisgar** [comment]
I can confirm this on KDE. Seems like the menubar follows the system theme. On a system with light theme enabled (globally) even though dark mode is selected on Caprine's options, the menubar doesn't respect that. Setting dark mode for the whole system fixes it.
