### ISSUE TITLE
Corrupt (?) profile picture icons

### ISSUE THREAD

**Issue by Linux-Legend** [sindresorhus/caprine#1966]
I've just installed caprine, I've used it before and never had issues, however this time all of my chats profile picture icons have gotten corrupted or garbled. I'll attach a link to a photo so you can see what i mean.

[Photo](https://drive.google.com/file/d/17PpfPRy7orhM2W2LEtq9kXeEFJWQthK3/view?usp=share_link)

Any help would be greatly appreciated.
---

Caprine 2.57.0
Electron 21.2.3
linux 5.15.0-52-generic
Locale: en-GB

**Comment by dusansimic** [comment]
What distribution and installation method have you used?

**Comment by Linux-Legend** [comment]
Ubuntu 22.04 and installed via snap

**Comment by dusansimic** [comment]
Could you try installing it via some other package format (deb, AppImage or Flatpak). This might be related to just the snap package. There have been recurring troubles with it.

**Comment by Linux-Legend** [comment]
Okay, i'll give it a try tomorrow and let you know how it goes.

Thanks for your help so far

**Comment by Linux-Legend** [comment]
Good news is that the deb package is working perfectly, so like you said, I
think there is an issue with the snap package.

**Comment by Linux-Legend** [comment]
For anyone else reading this and having the issue, download the DEB package instead, it just works.

**Comment by Linux-Legend** [comment]
For anyone else reading this and having the issue, download the DEB package instead, it just works.
