### ISSUE TITLE
Zoom in problem

### ISSUE THREAD

**Issue by jnuno2000** [sindresorhus/caprine#1968]
Can't zoom in when i press ctrl +
---

Caprine 2.57.0
Electron 21.2.3
linux 5.15.0-53-generic
Locale: en-US

**Comment by SirAnxious** [comment]
Works for me.

> Caprine 2.57.0
> Electron 21.2.3
> win32 10.0.19044
> Locale: en-US

Linux problem?
Are you sure you using the +/- signs above your keys and not the numpad ones? 
(Numpad ones work fine in browser but not Caprine, me thinks)

**Comment by dusansimic** [comment]
Can't reproduce
