### ISSUE TITLE
Can not log-in on Linux Mint 20

### ISSUE THREAD

**Issue by kkafar** [sindresorhus/caprine#1972]
Hi! 

during first login attempt I encountered an error.

After following these steps:

1. Installing `deb-get` via [these instructions](https://github.com/wimpysworld/deb-get#install)
2. Installing `caprine` via [these instructions](https://github.com/sindresorhus/caprine#installation-using-deb-get)
3. Opening the app (installation process did not show any errors)
4. Filling my user credentials and attempting to log-in

This error occured:

![image](https://user-images.githubusercontent.com/50801299/207523659-e8209c23-9907-42e8-803a-ad9e77117e16.png)

The text is saying that "The link that was used could be damaged or the resource is no longer available".

Is this known issue? 

I'm using Linux Mint 20 with Cinnamon 4.6.7.

I basically know nothing of `Electron`, but looking at stack it uses, could it be a problem that I use `Brave Browser`? 

Edit: I looked it up and it seems that `Electron` comes bundled with `Chromium` -> then it is not it I guess ;D 

Please let me know in case any more info is needed.

**Comment by dusansimic** [comment]
This doesn't seem to me like an issue with Caprine, rather an issue on Messenger website. I'll close this issue for now since it's been open for quite a while but if it persists, please comment about it.
