### ISSUE TITLE
Messenger Settings and Preferences

### ISSUE THREAD

**Issue by BigSkyMG** [sindresorhus/caprine#1979]
Hello, I'm using Caprine version 2.57.0 on a Windows 11 device, and I can't seem to find the privacy settings. I'm specifically looking for the setting that would allow me to prevent people from knowing I've seen a message or that I'm typing a response. I don't see it when I look in the File drop down menu, and when I click on File > Messenger Settings or try hitting Ctrl + Comma, nothing happens (no menu appears). I also tried going down to my account photo in the lower left corner and clicking on Preferences, but nothing happens when I click on that either (no menu appears). Please let me know if I'm missing something or doing something wrong or if maybe there's currently less functionality in the Windows version compared to the Mac version. 

Thank you for your help :)

Mike

**Comment by dusansimic** [comment]
Privacy settings have been disabled since they are broken atm. https://github.com/sindresorhus/caprine/issues/1930#issuecomment-1272502301
