### ISSUE TITLE
No settings menu on Linux Mint 21.1 Cinamon

### ISSUE THREAD

**Issue by BenCooper-10101** [sindresorhus/caprine#1980]
"Messenger Settings" menu does not open, neither when selected from menu nor when using control-comma shortcut key.

Installed on Linux Mint 21.1 Cinamon.
---

Caprine 2.57.0
Electron 21.2.3
linux 5.15.0-58-generic
Locale: en-GB

**Comment by dusansimic** [comment]
Closing in favor of #1983
