### ISSUE TITLE
Class name issues resulting in `hide-preferences-window` not removed

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#1983]
Some class names in the Messenger website have changed which has resulted in the Caprine code working and not removing the `hide-preferences-window` class which hides the modals. This causes any modal to be hidden (including preferences, remove chat, votes, change nick, all kinds of menus...).

**Comment by efeftimov** [comment]
fixed it by deleting/commenting 92th line of the browser.css (usr/lib/caprine/css on manjaro)

html.hide-preferences-window div[class='x9f619 x1n2onr6 x1ja2u2z'] > div:nth-of-type(3) > div > div {display: none; }

**Comment by dusansimic** [comment]
@efeftimov that's a workaround at best. The goal of hiding preferences modal is to hide it from the user when some settings need to be applied (they are picked in the menu bar but the preferences modal needs to be opened to actually set them and that is done by programmatically opening it. To hide that process from the user, preferences modal is hidden using the css style you suggest should be removed.).
