### ISSUE TITLE
Most view options aren't working

### ISSUE THREAD

**Issue by cookingboy3** [sindresorhus/caprine#1984]
Running Caprine 2.57.0 on Windows 10 - this is a fresh install from today, as I just realized that Caprine has Windows builds too.

Most of the Caprine-specific options in the View menu are having no effects for me. While the zoom and theme controls work fine, the rest of the controls have issues.

"Hide Names and Avatars," the entire Sidebar menu, and "Show Message Buttons" can be selected and toggled but don't seem to do anything regardless of state. 

"Show Active Contacts," "Show Message Requests," and "Show Hidden Threads" don't do what their names state, but instead seem to put the Communities section in the sidebar into edit mode (as if you had clicked the "manage" button).

I have already tried relogging, relaunching, and reinstalling the app through both the installer and Chocolatey and the issue persists.

**Comment by gnanet** [comment]
Same here on linux, but additionally:

popups like messenger settings, or "forward to" also do not show

```
Caprine    2.57.0
Ubuntu 18.04.6 LTS
Kernel 5.4.0-138-generic
libc6:amd64    2.27-3ubuntu1.6
gnome-shell    3.28.4-0ubuntu18.04.7
gdm3    3.28.3-0ubuntu18.04.6
xserver-xorg    1:7.7+19ubuntu7.1
````

**Comment by cookingboy3** [comment]
> popups like messenger settings, or "forward to" also do not show
I think that this might be related to #1983

**Comment by dusansimic** [comment]
>> popups like messenger settings, or "forward to" also do not show

> I think that this might be related to https://github.com/sindresorhus/caprine/issues/1983

Corrrect.

Regarding the things reported in the issue, probably the cause is the same (Messenger ui has changed so Caprine code needs to be changed to).

**Comment by dvdlm** [comment]
Same issue here: Windows 10 Enterprise 21H2, installed Caprine  2.57.4  

Missing features:
- No privacy options (typing or read indicators)
- No effect:
  - Hide Names and Avatars
  - Hide Sidebar
- Broken: "Show Active Contacts," "Show Message Requests," and "Show Hidden Threads" 

And there is a "Try Messenger for Windows" at the bottom of the chats pane.
