### ISSUE TITLE
Add RHEL-9 package.

### ISSUE THREAD

**Issue by NicTanghe** [sindresorhus/caprine#1989]
Repository 'epel-9-x86_64' does not exist in project 'dusansimic/caprine'.
Available repositories: 'fedora-35-x86_64', 'fedora-rawhide-x86_64', 'fedora-36-x86_64', 'fedora-37-x86_64', 'opensuse-leap-15.3-x86_64', 'epel-8-x86_64', 'opensuse-tumbleweed-x86_64'

Please add a rhel-9 package.

**Comment by dusansimic** [comment]
EL9 package has been added to the COPR repo. Thanks for reaching out. Please keep in mind that RPM package (from COPR repo) is still unofficial (see the readme of the Caprine project). Until it becomes official it's better to submit bug reports and any other requests about it on the COPR project page, not here in the Caprine bug tracker.
