### ISSUE TITLE
No popup notifacations on arch linux KDE DE (sound or toast)

### ISSUE THREAD

**Issue by XDM-Inc** [sindresorhus/caprine#1991]
im running endeavor os  based on arch and while i have this running i don't get ANY sounds or popups from this app. clicking messenger settings also does not work. I also notice that in my system settings > notifications menu this app dose not even show up there.

**Comment by RobDean69** [comment]
I'm running Opensuse tumbleweed KDE and have the same issue. Caprine is installed via flatpak if that makes a difference.

**Comment by dusansimic** [comment]
Duplicate of #1825
