### ISSUE TITLE
Remove/Delete Dead

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1994]
As you know the Remove and Delete Buttons are inert. in 257.0.
My  Question is, would reinstalling fix those issues from your experience?

---

Caprine 2.57.0
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by mirenradia** [comment]
I can reproduce this on Fedora Linux 37. Furthermore, clicking on the existing reactions to a message does not work (should display a "Message reactions" popup showing who has reacted to a message and what they have reacted with).

**Comment by dusansimic** [comment]
Duplicate of #2004
