### ISSUE TITLE
Tray/notification icon color

### ISSUE THREAD

**Issue by patefoniq** [sindresorhus/caprine#1995]
Hi all.
Please, change the color of the notification icon. I don't know anyone who is using a white taskbar, but definitely, more than 70%/80% of users are using gray or just dark taskbar. So please change the color of this icon to white or light blue because it's invisible. Tested on KDE/Mate/Cinnamon. Look at the screenshot from the newest KDE Plasma:

![image](https://user-images.githubusercontent.com/11136688/224263825-bab071f2-00f0-4479-ad8a-bd0445dfb9b7.png)

On Windows, the situation is a bit better, but also not perfect (see the screenshot):

![image](https://user-images.githubusercontent.com/11136688/224264643-088ee1c7-2f97-4bef-b2ce-6a4e42e7c9d0.png)

**Comment by manhnt9** [comment]
Me too, on Ubuntu 20.04 there's no icon in current release (snap).

**Comment by patefoniq** [comment]
There is one more thing. On Windows below 10th program icon is appearing indeed, but it lacks of notifications due to basing on badge instead of color change or adding red dot like in skype, discord, teams, or slack.

![image](https://user-images.githubusercontent.com/11136688/224919716-015c60af-adc5-4c34-a727-a3189d13f7cf.png)

![image](https://user-images.githubusercontent.com/11136688/224922620-7860d6a2-a4b5-4ac9-97ef-26841222be18.png)

![image](https://user-images.githubusercontent.com/11136688/224920749-334db756-773b-4f2e-b4e1-2ee386631e84.png)

And Caprine (always the same, static icon - I have more than 10 unreaded messages):

![image](https://user-images.githubusercontent.com/11136688/224920619-d5eb4b01-2e80-4939-9275-d88e1a474b01.png)

**Comment by huyhoang8398** [comment]
No system tray with flathub / XFCE ubuntu 22.04
