### ISSUE TITLE
Distribute the AppImage file in an archive.

### ISSUE THREAD

**Issue by rokejulianlockhart** [sindresorhus/caprine#1998]
Not solely shall it be quicker to download, it'll negate the necessity of [`chmod +x Caprine-2.xx.x.AppImage`](https://github.com/sindresorhus/caprine#appimage:~:text=chmod%20%2Bx%20caprine-2.xx.x.appimage) because `.zip` and `.tar` retain the permissions their constituent files.

I suggest the ubiquitous `.zip` due to its inherent support in every OS, but `.tar.gz` ([`application/tar+gzip`](https://superuser.com/a/960710/904401#:~:text=version%20would%20be-,application%2Ftar%2Bgzip,-(file%20extensions%20.tar))) is probably the next best due to its brilliant compression to speed ratio.

AppImage exists to lower the barrier to entry. Having to perform terminal commands on it to get it to run is antithectical to that purpose.

**Comment by dusansimic** [comment]
> Not solely shall it be quicker to download, it'll negate the necessity of [chmod +x Caprine-2.xx.x.AppImage](https://github.com/sindresorhus/caprine#appimage:~:text=chmod%20%2Bx%20caprine-2.xx.x.appimage) because .zip and .tar retain the permissions their constituent files.

It's good security practice to manually change permissions for files to be executable.

> I suggest the ubiquitous .zip due to its inherent support in every OS, but .tar.gz ([application/tar+gzip](https://superuser.com/a/960710/904401#:~:text=version%20would%20be-,application%2Ftar%2Bgzip,-(file%20extensions%20.tar))) is probably the next best due to its brilliant compression to speed ratio.

Compressed size is less than 1% smaller than original. I don't see that as a significant difference, rather it requires an extra step which takes time.

> AppImage exists to lower the barrier to entry. Having to perform terminal commands on it to get it to run is antithectical to that purpose.

Users could change permissions through most modern file managers graphically.

If there is some other reason for compressing AppImage into an acrhive, I'm all ears but for now this proposition looks like it could bring more complexity than the current installation procedure for AppImage.
