### ISSUE TITLE
Droidcam

### ISSUE THREAD

**Issue by ViRuS-MaN** [sindresorhus/caprine#1999]
Hello i ask to you it s posible you include the possibility to use droidcam with you programme ?

---

Caprine 2.57.0
Electron 21.2.3
win32 10.0.19044
Locale: fr

**Comment by dusansimic** [comment]
At the moment we don't plan on implementing any additional features. If DroidCam creates a virtual webcam on your computer, you should be able to use it as a webcam during a video call.
