### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#2]
- [ ] Adjust the build script to build Windows app. Eg. `--platform=darwin --arch=x64` => `--all`.
- [ ] Icon. Need a `Icon.ico` file. https://github.com/maxogden/electron-packager#packageropts-callback
- [ ] Adjust the menu. Keyboard shortcuts are already cross-platform. Just need to make sure it's windowsy.
- [ ] Configure the `--version-string` in the build script. https://github.com/maxogden/electron-packager#packageropts-callback
- [ ] Ensure everything works as expected
- [ ] Add `brew install wine` to `Dev` section in the readme: https://github.com/maxogden/electron-packager#building-windows-apps-from-non-windows-platforms

**Comment by iiegor** [comment]
I'm working on this ([iiegor/caprine#windows-support](https://github.com/iiegor/caprine/tree/windows-support)).

All is right except the build script. In windows, the **$npm_package...** env variables are not working correctly so If a windows user wants to build for the platform the script will fail. Any suggestions?

Regarding the other points... icon file was added, all keyboard shortcuts are working and the app works as expected.

![img](http://i.imgur.com/7pHUdcz.png)

**Comment by sindresorhus** [comment]
Awesome! Do a pull request when you're ready for a review ;)

> All is right except the build script. In windows, the $npm_package... env variables are not working correctly so If a windows user wants to build for the platform the script will fail. Any suggestions?

It's Windows, so I guess you have to use `%$npm_package_name%` instead.
