### ISSUE TITLE
In-app updater

### ISSUE THREAD

**Issue by james-clark-5** [sindresorhus/caprine#200]
It'd be cool to have automate updating/checking for updates/the ability to check for updates in the app.

If you don't want to add it in the app (cluttering the UI), it could be a taskbar right-click option.

**Comment by sindresorhus** [comment]
It already has [silent auto-updating](https://github.com/sindresorhus/caprine/releases/tag/v2.0.0). I'm not really interesting in having any kind of UI for it.

**Comment by james-clark-5** [comment]
Ah, cheers!
