### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2000]
After mentioning that Delete/Remove Buttons don't work, I notice my React Icons no longer load/appear properly as well.
Not aware of too much activity from any associated source since 257.0 launch; very quiet.
That's why I ask if Caprine is Deprecated? I sure hope not.

---

Caprine 2.57.0
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by kacnje** [comment]
I just came to this "Issues" site with the same question. Caprine is a lovely client but has some bugs (described in other themes).

**Comment by dusansimic** [comment]
Duplicate of #2004
