### ISSUE TITLE
Dark theme broken

### ISSUE THREAD

**Issue by n0kovo** [sindresorhus/caprine#2003]
The dark theme looks like this until manually going to the menu and choosing Dark under Theme.
Changing conversations will make it revert back to this.

![image](https://user-images.githubusercontent.com/16690056/231327403-aea2e555-8541-4f46-a277-d26018c4150c.png)

**Comment by dusansimic** [comment]
What platform and installation method are you using? What version of Caprine are you using?

**Comment by filipruisl** [comment]
This issue has been persistent for me for ages. Am on the latest MacOS build.
