### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by n0kovo** [sindresorhus/caprine#2005]
Hey, @sindresorhus, it would be nice to know for sure whether this project is still considered active.
There doesn't seem to have been any kind of participation from yourself since about a year ago and with 192 open issues, it sure seems like the project has been more or less abandoned.

**Comment by sindresorhus** [comment]
Unless someone steps up to help maintain it, then yes.

**Comment by stonefrango** [comment]
@n0kovo The pinned and still open issue #713 also somewhat indicates this. The service is mostly relying on community support.

Updates are still being released, though.

**Comment by sindresorhus** [comment]
Not abandoned: https://github.com/sindresorhus/caprine/releases/tag/v2.57.4
