### ISSUE TITLE
257.1 Freezes

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2008]
After the Delete/Remove issues were fixed, I am sadly reporting a new issue.
Caprine 257.1 often freezes and needs to be Relaunched.
Hate to report  anything when you Folk work so hard to make it right.

---

Caprine 2.57.1
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by Alex313031** [comment]
See here > https://github.com/sindresorhus/caprine/issues/2011

**Comment by dusansimic** [comment]
Closing in favor of #2011
