### ISSUE TITLE
macOS icon size too large

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#2018]
The icon should have some padding ([Apple docs](https://developer.apple.com/design/human-interface-guidelines/app-icons)).

![image](https://user-images.githubusercontent.com/12685466/236675709-d52d1370-3b2d-4f92-9715-54f057d5a1eb.png)

This was done in https://github.com/sindresorhus/caprine/commit/cf78ee346aeb22bbd32e7455d1d5e8df5a0808b2 since the previous icon has some padding which made icon look a lot smaller compared to other ones on other platforms (namely Windows and Linux). A solution would be to use two different icons, one with white background and padding and one without white background and less padding for macOS and other platforms respectively.

**Comment by Jont828** [comment]
I'm having this bug too
