### ISSUE TITLE
Caprine captures F5 key presses while minimized to tray

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#202]
Hello,
I am using Manjaro GNU/Linux with Gnome 3. This issue has affected me some Caprine 2.0.

When Caprine is minimized to the tray, I can no longer use the f5 key to refresh pages in my browser. I have used the `xev` utility to see whats going on, and I can see while Carpine is minimized to the tray pressing f5 is being capture by another process.

If I bring Caprine back from the tray, or kill Caprine, then I can start using f5 normally again. I'm not sure if its just a coincidence that Caprine is built on web technologies and the f5 key happens to be the one affected.

Is there something I can do to help track down the origin of the issue and identify a fix?

**Comment by sindresorhus** [comment]
Thanks for reporting. Weird this hasn't been reported before. I'm using [`electron-debug`](https://github.com/sindresorhus/electron-debug/blob/74e90e8899457f473ac08588a8310f2839b6f1aa/index.js#L83) in Caprine, which should only register F5 when it's focused. Sounds like a bug in [`electron-localshortcut`](https://github.com/parro-it/electron-localshortcut). @parro-it Any thoughts?

**Comment by jamesrobb** [comment]
Glad to help. I have also noticed that ctrl+shift+c seems to become captured by Caprine as well. This makes copying from terminals a pain too as I then need to use the right-click menu to copy.

**Comment by parro-it** [comment]
Currently, `electron-localshortcut` unregisters shortcuts only on BrowserWindow instances blur and close events, but not on minification event.

@jamesrobb would you mind open an issue on [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) repo?

**Comment by jamesrobb** [comment]
@parro-it I definitely could, though I am not quite sure I understand the problem enough to file a bug with meaningful information. Could you aid in this?

**Comment by parro-it** [comment]
`electron-localshortcut` take care of register you're shortcuts only when your app windows has focus, to avoid the effects you describer in this issue. 

But to do this, it only listen to 'blur' events of windows, so when your app windows are all minified, the shortcuts are not unregistered, while they should....

**Comment by jamesrobb** [comment]
Submitted the bug.

**Comment by fatso83** [comment]
Just used a week trying to find out why Ctrl-R and the copy from terminal stopped working, and finally [managed to debug X today just to find the culprit was Caprine](https://askubuntu.com/questions/925732/some-ctrl-shortcuts-stop-working-after-resuming-from-standby/926156#926156). Thought I was original in finding it, but it seems not :smile:

**Comment by jamesrobb** [comment]
Still persists in 2.4.0

**Comment by parro-it** [comment]
@jamesrobb do you mean in version 2.0.0? I never published a 2.4.0 release on npm.
If you still have problems with windows minification, please open an issue on electron-localshortcut repo (or reopen the original issue if you prefer)

**Comment by parro-it** [comment]
@jamesrobb Oh sorry, I guess you mean Caprine 2.4.0...
I looked at package.json, it's still using version 1.1 of `electron-localshortcut`

**Comment by jamesrobb** [comment]
@parro-it Yes, i meant Caprine 2.4.0. Thanks for the super quick reply though :)

**Comment by parro-it** [comment]
> @parro-it Yes, i meant Caprine 2.4.0. Thanks for the super quick reply though :)

😄  you're welcome! I published a PR here and on electron-debug to update localshortcut version, this should solve the issue. Thank you for your efforts @jamesrobb
