### ISSUE TITLE
MP4 is not uploaded

### ISSUE THREAD

**Issue by czerwinski76** [sindresorhus/caprine#2020]
Uploading a MP4 in a ciscussion does not work.
With the website https://www.facebook.com/messages/t/ , it's OK.

---

Caprine 2.57.4
Electron 24.1.3
win32 10.0.19045
Locale: fr

**Comment by dusansimic** [comment]
Do you have an example file with which we could reproduce the issue? If not, we can't really investigate it.

**Comment by dusansimic** [comment]
Closing since there is no response.
