### ISSUE TITLE
Wrong password.

### ISSUE THREAD

**Issue by Min1oo** [sindresorhus/caprine#2025]
Hi, i can't log in to messenger with my password from facebook, which is correct. I dont know why?
![Zrzut ekranu z 2023-06-16 10-26-19](https://github.com/sindresorhus/caprine/assets/116849677/4b007c3a-9e76-4259-b7b0-246c416a23c3)

---

Caprine 2.57.4
Electron 24.1.3
linux 5.19.0-43-generic
Locale: pl

**Comment by dusansimic** [comment]
Please check the keyboard layout when you input the password. Other than that, this is not a Caprine issue.
