### ISSUE TITLE
Some shortcut doesn't work

### ISSUE THREAD

**Issue by thoussem** [sindresorhus/caprine#203]
These shortcuts do not work :
- Next conversation	**Cmd/Ctrl ] or Ctrl Tab**
- Previous conversation	**Cmd/Ctrl [ or Ctrl Shift Tab**
- Search conversations	**Cmd/Ctrl f**

I am using Ubuntu 16.04

**Comment by sindresorhus** [comment]
Confirmed. I forgot to put those menu items in the Linux/Windows menu... Done now: https://github.com/sindresorhus/caprine/commit/c8eed066f9bde6be2fe976e7a85700abb3279417

The Ctrl+Tab and Ctrl+Shift+Tab keyboard shortcuts still does not to work, even though they're defined in the menu. Weird. Maybe an Electron bug. @veniversum Thoughts?

Ctrl+F, Ctrl+], and Ctrl+[ works.

**Comment by sindresorhus** [comment]
Oh, it's actually working. It's just Parallels that captures those keys.

**Comment by sindresorhus** [comment]
New release is out: https://github.com/sindresorhus/caprine/releases/tag/v2.3.1

Thanks for reporting :)

**Comment by veniversum** [comment]
@sindresorhus That's a really quick patch! I just found out that `Ctrl+F` didn't work while thinking about adding a menu item/shortcut for **Search in current conversation**. Do you think we should add that in?

**Comment by sindresorhus** [comment]
@veniversum I don't use it very often, but if you think it could be useful, sure. I think the keyboard shortcut should be Cmd/Ctrl+Shift+F.
