### ISSUE TITLE
Older version - stop auto update?

### ISSUE THREAD

**Issue by ireallyhateaccounts** [sindresorhus/caprine#2034]
How do I keep Caprine from auto-updating? I installed older versions on a Win 8 machine because I get this error with the current. It will load just fine the first time, but then seems to auto-update before I can even look to see if there is a setting to disable. 

![image](https://github.com/sindresorhus/caprine/assets/140413379/184f886b-ea78-4362-a5fa-82d3b3134f07)

**Comment by dusansimic** [comment]
There is an option to disable automatic updates in `File` > `Caprine Settings` > `Automatic Updates`. That option should be unchecked in order to be disabled. You could uninstall the current version and install an older version you'd like to use.

**Comment by ireallyhateaccounts** [comment]
What version specifically? Because I downloaded quite a few and not a single one had this option in the menu like you described. I check immediately upon start, but it's never there. Then 2 minutes later it's completely unusable because the auto update starts.  I can then no longer even open it.
