### ISSUE TITLE
Not working well this version of . . .

### ISSUE THREAD

**Issue by Frewa01** [sindresorhus/caprine#2039]
Hi there,

I'm not thinking to change the OS because my opinion, but the last Caprine version to my OS had freezed now, not fully visible some things. :/ Could you update please to use it again well? :) ( like v2.57.1.1 )

Thank you! :)

---

Caprine 2.57.1
Electron 21.2.3
win32 6.3.9600
Locale: en-US

**Comment by dusansimic** [comment]
I'm not sure what you mean.

What are the issues? Provide some screenshots or error logs.

Also, there is version 2.58.0 out so you can try it out.

**Comment by Frewa01** [comment]
![1](https://github.com/sindresorhus/caprine/assets/140790775/58abd64a-8a20-45a4-895c-8ff98e3f7e50)

**Comment by dusansimic** [comment]
Caprine doesn't support Windows 8.1, 8 and 7 since v2.57.2. Legacy Windows version support is being discussed in https://github.com/sindresorhus/caprine/issues/2011

**Comment by Frewa01** [comment]
> Caprine doesn't support Windows 8.1, 8 and 7 since v2.57.2. Legacy Windows version support is being discussed in #2011

Okay, then that means i can delete definitively it. :/ That's all. Thx.
