### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#204]
Would be nice to have a simple landing page with a screenshot, short description and a download button to the latest release. Many non-tech user find GitHub intimidating. They trust a nice website more.

No build step. Just a simple static site hosted on GitHub Pages with some JavaScript to show the correct download button depending on the operating system.

Inspiration: http://www.goofyapp.com

**Comment by jblandino** [comment]
@sindresorhus ¿Do you have any preference of some colors or do not stop choosing us?

**Comment by jxom** [comment]
Hey @sindresorhus, I spent a couple of hours whipping up a simple landing page. Though I can't open a pull request with `gh-pages` as the base branch? Can you create one?

Here is the fork although: https://github.com/jxom/caprine/tree/gh-pages
https://jxom.github.io/caprine/

**Comment by shankariyerr** [comment]
Something like this? http://caprine-landing.surge.sh/  

A simple no-scroll landing page. I used @jxom 's `.js` as it is to fetch the latest build. Awesome man!

I used the grid system -  [Griddd](https://github.com/shankariyerr/griddd) which I recently built for the layout

fork: https://github.com/shankariyerr/caprine/tree/gh-pages

**Comment by veniversum** [comment]
I think it would be great to include some of the features too, such as dark theme, privacy features and keyboard shortcuts. It'd answer most questions like 'what makes this different from messenger.com in a web browser?'

**Comment by shankariyerr** [comment]
@veniversum Makes sense. Heading out. Will do it in a couple of hours.

**Comment by jxom** [comment]
@veniversum - I agree. Was gonna add some features, but just wanted to get something out. I added some features to the page! Check it out: https://jxom.github.io/caprine/

**Comment by jblandino** [comment]
@jxom i like this design bro 👍

**Comment by sindresorhus** [comment]
Wow. This is really awesome! Thanks both @jxom and @shankariyerr 🙌

We'll go with @jxom's proposal as it's the most complete.
@jxom I've created a `gh-pages` branch. Could you submit a pull request?
Could you make the main screenshot a bit smaller and the download button larger?

**Comment by sindresorhus** [comment]
@shankariyerr I could use a website for my [Touch Bar Simulator app](https://github.com/sindresorhus/touch-bar-simulator) if you would be interested in adapting your design for it? No worries if not.

**Comment by shankariyerr** [comment]
@sindresorhus I would be honoured to. Just let me know how you want it to be.

**Comment by jxom** [comment]
Opened a PR 👍 #217

**Comment by sindresorhus** [comment]
@shankariyerr Looking good! Can you do a pull request and we can discuss there? I've created a `gh-pages` branch on that repo.

**Comment by sindresorhus** [comment]
The website was done a long time ago, but I forgot to close this.
