### ISSUE TITLE
My issue was closed before I could even respond - disabling auto update

### ISSUE THREAD

**Issue by ireallyhateaccounts** [sindresorhus/caprine#2042]
What version specifically has the option to disable updates? Because I downloaded quite a few and not a single one had this option in the menu like you described. I check immediately upon start, but it's never there. Then 2 minutes later it's completely unusable because the auto update starts. I can then no longer even open it.

**Comment by dusansimic** [comment]
![select_auto_update](https://github.com/sindresorhus/caprine/assets/12685466/3926a059-1abe-40a5-9e2c-cd61b5f0fe7c)

**Comment by dusansimic** [comment]
Have you been able to find the setting?
