### ISSUE TITLE
[flatpak] Dark theme not respected on menu bar

### ISSUE THREAD

**Issue by TDuffinNTU** [sindresorhus/caprine#2043]
![image](https://github.com/sindresorhus/caprine/assets/43959652/7c01fcc3-eb1f-430b-a4d1-ece90c737e6a)

So the app appears to follow the dark theme everywhere _but_ the taskbar (as pictured).

System is Manjaro rolling with GNOME 44.3, Linux 6.1.41-1-MANJARO kernel.

**Comment by dusansimic** [comment]
This seems a bit unusual. I can't reproduce this on my Arch install. Do you use a custom GTK theme (Manjaro theme is considered a custom theme)?

**Comment by dusansimic** [comment]
Do you have the corresponding flatpak package for the theme installed?

**Comment by TDuffinNTU** [comment]
Just installed `org.gtk.Gtk3theme.adw-gtk3-dark`. No change but I guess I have to restart or something for it to take effect?

**Comment by TDuffinNTU** [comment]
Ah got it! had to set the theme for "legacy apps" in my tweaks tool :-)
