### ISSUE TITLE
2.58 installs into appdata by default with no option

### ISSUE THREAD

**Issue by yereverluvinunclebert** [sindresorhus/caprine#2045]
Caprine  should not install into appdata by default, it appears to provide no option for an alternative location giving the impression that it will only run from this folder. By default users will expect program files as that has been the default location for programs for at least a decade.

I am fairly certain older versions let you install elsewhere and as we all know, choice is good. 

What if you have a system drive, an applications drive and a data drive? You don't want to fill your Windows boot SSD with applications that default to C: and then hide themselves.

I have moved Caprine manually and it works fine, give users the option please during install time.

**Comment by yereverluvinunclebert** [comment]
same with the caprine installer/updater, don't hide it on C: or at least let people move it so you don't steal all their drive space.

**Comment by yereverluvinunclebert** [comment]
In addition, when Caprine is already installed, the installer knows all about the preceding installation, that it is running &c. Therefore it could easily derive the current folder, yet it ignores that and decides to install elsewhere. This is a little sloppy and doesn't sit right. 

Suggestion: just have a zipfile that users can unzip flat files into a location.
If you have an installer, then it needs to do what all installers have done for decades. Determine default folder location, provide choice, install there. There are several off-the-shelf installer tools that will do it all for you.

**Comment by Alex313031** [comment]
@yereverluvinunclebert I recently added this to my fork > https://github.com/Alex313031/caprine-ng

See commit > https://github.com/Alex313031/caprine-ng/commit/a256979d0f59e865ac653dfb2c21fa45ee598430
