### ISSUE TITLE
Dark mode isn't working

### ISSUE THREAD

**Issue by Adrian-Sebak** [sindresorhus/caprine#2046]
Dark mode isn't working
I'm using linux manjaro with cinnamon desktop enviroment 
---

Caprine 2.57.4
Electron 22.3.18
linux 6.1.41-1-MANJARO
Locale: sk

**Comment by dusansimic** [comment]
Plase provide some more information. What logs are displayed (you can see them in the console tab in devtools, open them by pressing F12).

What installation method do you use? If you're able, please update to the latest version of Caprine.

**Comment by Adrian-Sebak** [comment]
Apps is working correctly, but when I change theme to dark, nothing happens even after I restarted the app. But the setting are changed to dark mode. I used pacman to install this package. 

[www.messenger.com-1691423070383.log](https://github.com/sindresorhus/caprine/files/12282268/www.messenger.com-1691423070383.log)
[www.messenger.com-1691423083549.log](https://github.com/sindresorhus/caprine/files/12282269/www.messenger.com-1691423083549.log)
[www.messenger.com-1691423099455.log](https://github.com/sindresorhus/caprine/files/12282270/www.messenger.com-1691423099455.log)
[www.messenger.com-1691423114923.log](https://github.com/sindresorhus/caprine/files/12282271/www.messenger.com-1691423114923.log)
![Snímka obrazovky z 2023-08-07 17-46-27](https://github.com/sindresorhus/caprine/assets/117380196/fef86cc2-20e3-41c8-9029-24907a0f8dee)
![Snímka obrazovky z 2023-08-07 17-46-35](https://github.com/sindresorhus/caprine/assets/117380196/a542c196-4d22-4260-b597-bac6d913b91c)
![Snímka obrazovky z 2023-08-07 17-46-42](https://github.com/sindresorhus/caprine/assets/117380196/2d0cb6e7-5882-40d5-a86e-f9b3471e81f2)

**Comment by dusansimic** [comment]
This was already fixed with https://github.com/sindresorhus/caprine/pull/2037 (Caprine 2.58.0). Manjaro is a bit slow with updating packages from Arch repos.
