### ISSUE TITLE
You can't open the application "Caprine" because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by varunrau** [sindresorhus/caprine#205]
Error seen when trying to install Caprine v2.3.1

![image](https://cloud.githubusercontent.com/assets/1448222/26030233/8681639a-3801-11e7-878b-b89c93662b9f.png)

![image](https://cloud.githubusercontent.com/assets/1448222/26030224/705371c6-3801-11e7-9036-1958d84f2da0.png)

**Comment by sindresorhus** [comment]
You downloaded https://github.com/sindresorhus/caprine/releases/download/v2.3.1/caprine-2.3.1.dmg right? Works fine for me. Try downloading again. Maybe you had some internet connectivity issues when downloading the first time.

**Comment by koostamas** [comment]
This is a valid problem, even on MacOS Sonoma and an M2 MacBook, the solution is `xattr -c /Applications/Caprina.app`. I found the answer here: https://discussions.apple.com/thread/253714860?sortBy=rank
