### ISSUE TITLE
windows 10, middle of chat, Caprine freezes 

### ISSUE THREAD

**Issue by yereverluvinunclebert** [sindresorhus/caprine#2052]
windows 10, middle of chat, Caprine freezes, menus operating correctly but chat frozen. Have to kill Caprine from task manager and restart, shortly after does the same. Generally unreliable.

The chat is a normal text chat, no images, nothing special.

---

Caprine 2.58.0
Electron 24.1.3
win32 10.0.19044
Locale: en-GB

**Comment by drobotk** [comment]
Linux Mint 21.2 Cinnamon, latest flatpak version, same issue

**Comment by dusansimic** [comment]
Closing in favor of #2053
