### ISSUE TITLE
security update time

### ISSUE THREAD

**Issue by Jackalhz1980** [sindresorhus/caprine#2060]
security update time is incorrect showing logins to be minutes ago when device logged in previous day.  changed login credentials to a new account to ensure account had not been penetrated and verified same results    

---

Caprine 2.58.0
Electron 24.1.3
linux 6.1.0-kali9-amd64
Locale: en-US

**Comment by dusansimic** [comment]
This is not a Caprine issue. Caprine shows the [Messenger website](https://messenger.com) so it's an issue on the website side.
