### ISSUE TITLE
Caprine Linux Freezes

### ISSUE THREAD

**Issue by kacnje** [sindresorhus/caprine#2062]
New topic because I'm not sure if the main cause is the same as #2053. 
I have used Caprine (always the latest version) on Windows and Linux for years. As you can see in the topic "Caprine Windows Freezes", the application often freezes. 
On Linux (Mint) it wasn't so bad until some days ago. There was a problem from time to time, but not every day. Now (maybe days/weeks) it has become unusable. It freezes almost every five minutes. 
Is this problem connected to Electron?
If the author needs any information, just let me know.

**Comment by unizippro** [comment]
Just ran `caprine --trace-warnings` on Ubuntu 20.04 and used the application until it froze, entire log here:
``` bash
$ caprine --trace-warnings
SNAP env is defined, updater is disabled
checkForUpdatesAndNotify called, downloadPromise is null

(caprine:8255): Gtk-WARNING **: 09:12:18.225: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(caprine:8255): Gtk-WARNING **: 09:12:18.228: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(caprine:8255): Gtk-WARNING **: 09:12:18.228: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
(node:8255) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'checked')
    at /snap/caprine/59/resources/app.asar/dist-js/browser.js:208:34
    at async EventEmitter.listener (/snap/caprine/59/resources/app.asar/node_modules/electron-better-ipc/source/renderer.js:46:34)
(Use `caprine --trace-warnings ...` to show where the warning was created)
(node:8255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[8255:0913/091507.720108:ERROR:object_proxy.cc(623)] Failed to call method: org.gnome.SessionManager.Inhibit: object_path= /org/gnome/SessionManager: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.129" (uid=1000 pid=8255 comm="/snap/caprine/59/caprine --trace-warnings --no-san" label="snap.caprine.caprine (enforce)") interface="org.gnome.SessionManager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.gnome.SessionManager" (uid=1000 pid=3557 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
[8255:0913/091507.720133:ERROR:power_save_blocker_linux.cc(339)] No response to Inhibit() request!

```

The two first unhandled exceptions appear before the freeze. In contrast, the two errors appear during or after the freeze.

**Comment by kacnje** [comment]
I tried, but I don't understand how to do it. 
I installed Caprine with Flatpak and I found it in `/var/lib/flatpak/app/com.sindresorhus.Caprine/current/active/files/bin`
If I run your command, I get "_Command 'caprine' not found, did you mean ..._".

**Comment by djex** [comment]
I am having the same issue. Running Pop OS 20.04 LTS. Freezes randomly and sometimes to the point of where the application is unusable as it freezes so often. A key thing to note is when it freezes the top menu bar and menu items are still accessible. It seems the only part that freezes is the window that renders the facebook chat.

Going to run it in terminal to see if there are any relevant errors when it freezes.

**Comment by dusansimic** [comment]
There is no difference from my point of view with #2053. I'll rename the original pr and close this one to avoid confusion. It's most likely connected to receiving messages so it could be any of our mechanisms that start when a message is received (mutation observers).
