### ISSUE TITLE
Cannot Delete Messages - Temporary Solution Works

### ISSUE THREAD

**Issue by droleander** [sindresorhus/caprine#2067]
Still Cannot Delete Messages - Prompt Not Showing
- Automatically udpated Caprine to v. 2.58.1 (Appimage)
- xkill the Caprine process
- Reopened Caprine v 2.58.1
- Tried to delete conversation but there was no prompt

Tried Temporary solution...
- exit or xkill Caprine v. 2.58.1 (Appimage)
- delete ~/.config/Caprine folder
- restart Caprine v. 2.58.1 (Appimage)
- log-in
- delete message and the window prompt works:
Delete chat
Once you delete your copy of this conversation, it cannot be undone.
Cancel | Delete chat

- Also, deleting the ~/.config/Caprine folder temporarily solves the 2FA loop during login.
- Temporary issue is back again after restarting the Ubuntu Mate PC. Doing the temporary fixes did not work.
---

Caprine 2.58.1
Electron 24.1.3
linux 5.15.0-83-generic
Locale: en-US

**Comment by dusansimic** [comment]
Keep in mind that the latest Caprine version is 2.59.0. This problem however has occurred again after getting it fixed in one of previous versions and it will be fixed in the next release (https://github.com/sindresorhus/caprine/commit/c272a61953c2c6d7a685f2ce44edbafaac47491d).
