### ISSUE TITLE
More Flexible Window Moves

### ISSUE THREAD

**Issue by spyderdyne** [sindresorhus/caprine#2068]
<pre>2.58.1
OS X Big Sur
Intel 64bit</pre>

I am only rarely able to find any spot in the interface window of Caprine that allows me to move it around my screen. The edges of the windows are definitely resizable, nicely done, but using those to drag the window to another part of the desktop or to align with other HUD functions I may be using on a particular screen requires more than one resize of the window to move it.

Sometimes on rare occasions Caprine seems to allow me to move the window via clicking the top center of the application window, but it is fleeting or operating by some logic that I have thus far been unable to diagnose.

(please dont tell me this is a dupe, I checked EVERYWHErE I PROMISE!)
<img width="1440" alt="Screen Shot 2023-09-21 at 3 26 08 PM" src="https://github.com/sindresorhus/caprine/assets/3091731/fc49ce3b-2a67-48bb-ad99-f052d3a1958d">
<img width="596" alt="Screen Shot 2023-09-21 at 3 26 41 PM" src="https://github.com/sindresorhus/caprine/assets/3091731/79785fb3-2c5f-4dc4-83bf-4e42da42edf7">
<img width="336" alt="Screen Shot 2023-09-21 at 3 26 31 PM" src="https://github.com/sindresorhus/caprine/assets/3091731/8192a736-7023-4dcb-9139-0566f226bca7">

**Comment by kalyway101** [comment]
Came here to comment and indicate that I'm having the same issues. Unable to click and drag the window in almost any spot. It selects titles and text instead.
