### ISSUE TITLE
Privacy submenu isn't visible in the windows version

### ISSUE THREAD

**Issue by Mate5000** [sindresorhus/caprine#2089]
I can't find privacy options under File -> Caprine Settings -> Privacy
Just like in the #1930 issue
I am using windows 11 caprine v2.59.1

**Comment by dusansimic** [comment]
It was hidden in this commit https://github.com/sindresorhus/caprine/commit/b8519e693d9a3aebfdfc877addba6962707a6862 because it's currently broken. As I've said in the issue you've linked, it should be hidden. It's shown on Arch Linux because there's a bug in their packaging of Caprine.
