### ISSUE TITLE
Caprine Windows v2.59.1 - what does File->New Conversation do?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [sindresorhus/caprine#2093]
1. In Caprine, when I select File->New Conversation, there's no visible change on my screen, i.e., it doesn't seem to do anything. What is this supposed to do?

2. In my desktop browser, when I've logged in to Facebook and I go to the profile for someone I'm not currently friends with, I have the option to click on the blue "Message" button to start a new conversation. What are the equivalent steps in Caprine to search for and find a profile in Caprine, so I can start a new conversation?

**Comment by searinminecraft** [comment]
same as clicking the compose button.

![image](https://github.com/sindresorhus/caprine/assets/114207889/48937172-2d3a-4c67-9fab-df731f1b872f)

**Comment by UNIVAC-Colonel-Panic** [comment]
File->New Conversation doesn't do anything for me. Screen doesn't change.
