### ISSUE TITLE
cannot remove or forward anymore

### ISSUE THREAD

**Issue by MakarosVar** [sindresorhus/caprine#2096]
Cannot remove messages or forward messages in latest version( 2.59.1)

---

Caprine 2.59.1
Electron 24.8.6
linux 6.5.6-76060506-generic
Locale: en-US

**Comment by droleander** [comment]
> Cannot remove messages or forward messages in latest version( 2.59.1)
> 
> Caprine 2.59.1 Electron 24.8.6 linux 6.5.6-76060506-generic Locale: en-US

This issue persists even after deleting the Caprine folder in Ubuntu.

**Comment by McKristoffer** [comment]
Same here. caprine 2.59.1, linux 6.6.7
