### ISSUE TITLE
Cask installation failed

### ISSUE THREAD

**Issue by thedaniel** [sindresorhus/caprine#21]
```
> brew cask install caprine
Error: No available Cask for caprine
Error: nothing to install
2015-10-05 13:42:49
```

**Comment by sindresorhus** [comment]
You always have to do `brew cask update` first.

**Comment by thedaniel** [comment]
Maybe worth adding that to the README? I'm sure I'm not the only one expecting to paste the install command provided in the README and have it work.

**Comment by sindresorhus** [comment]
No that's expected knowledge.
