### ISSUE TITLE
clicking on an image does not expand the image

### ISSUE THREAD

**Issue by andyczerwonka** [sindresorhus/caprine#2102]
When I click on an image, that image is not expanded to full screen. This may be related to https://github.com/sindresorhus/caprine/issues/2103 as it feel like Chromium settings.

**Comment by mquevill** [comment]
Does this issue still exist in v2.59.2+? #2108 may have fixed this issue.

**Comment by andyczerwonka** [comment]
Confirmed that this works for me in `2.59.3`

**Comment by mzso** [comment]
Downloading the image also works. However some sign of it happening would be nice. It just silently appears in the downloads folder.
