### ISSUE TITLE
clicking a link does not open the link

### ISSUE THREAD

**Issue by andyczerwonka** [sindresorhus/caprine#2103]
When I click on a link (url)  that was sent to me, it does not open the link. It should open in my default browser. This may be related to https://github.com/sindresorhus/caprine/issues/2102

**Comment by marcusfschmidt** [comment]
I am having a similar issue on Mint. Have tried ensuring the default browser is set, and the behaviour is the same in both Cinnamon and Sway - no dice. I do not, however, experience the issue mentioned regarding image expansion, so I do not believe they are related.

**Comment by mquevill** [comment]
Does this issue still exist in v2.59.2+? #2108 may have fixed this issue.

**Comment by andyczerwonka** [comment]
Confirmed that this works for me in `2.59.3`
