### ISSUE TITLE
Reaction emojis is unintentionally heart emoji on click

### ISSUE THREAD

**Issue by thireo** [sindresorhus/caprine#2106]
Upon clicking the reaction button on a message, it automatically select the heart emoji and exits the reaction popup menu immediately. This seems to mostly happen after a refresh of the Caprine page (pressing F5).

See screencast video:
[Screencast from 01-03-2024 12:38:32 PM.webm](https://github.com/sindresorhus/caprine/assets/25148816/e7cd402e-fe91-4fc7-a610-7aa51e2653df)

**Comment by maetthew** [comment]
Having same issue
