### ISSUE TITLE
can't sign in on Ubuntu 22.04

### ISSUE THREAD

**Issue by anminhha** [sindresorhus/caprine#2111]
I checked my messenger's ID and password carefuly. Nothing is wrong but The caprine keep show me that the password is incorrected. I tried to login fb on web and it's correct password

**Comment by mquevill** [comment]
Are you still facing this issue with the most recent version of Caprine?

**Comment by goatastronaut0212** [comment]
@mquevill  I don't think he will ever come back to reply or even close this issue. There are people who aren't a developer. They have problem and come to GitHub to seek for help or just to report an issue, but later they even forget they do have a GitHub account. I hope they will be alright, and their problem is solved. After all, would you mind if you close the issue?

**Comment by goatastronaut0212** [comment]
> @mquevill I don't think he will ever come back to reply or even close this issue. There are people who aren't a developer. They have problem and come to GitHub to seek for help or just to report an issue, but later they even forget they do have a GitHub account. I hope they will be alright, and their problem is solved. After all, would you mind if you close the issue? Mine do work.

**Comment by mquevill** [comment]
Closing because stale and can't reproduce.
