### ISSUE TITLE
End-to-end encrypted chat PIN code dialog hidden

### ISSUE THREAD

**Issue by hlqviet** [sindresorhus/caprine#2113]
It seems the app prevents the PIN code modal from opening so I cannot enter the PIN code to decrypt messages.

OS: Debian 12
Installation: deb package

**Comment by hlqviet** [comment]
Workaround: Open the DevTools with `Ctrl + Shift + I` and execute the following code:
```javascript
document.documentElement.classList.add('hide-preferences-window')
```

**Comment by mzso** [comment]
@hlqviet 
> ```js
> document.documentElement.classList.remove('hide-preferences-window')
> ```

Thanks.
