### ISSUE TITLE
Chats keep scrolling up indefinitely

### ISSUE THREAD

**Issue by ienzo** [sindresorhus/caprine#2117]
I’m using 2.59.1 as an appimage on Linux Mint. So today, when I booted up Caprine, the chat kept getting scrolled up. Earlier messages kept getting loaded indefinitely. I couldn’t control the scroll bar on the right. Using my touchpad or mouse scroll button proved fruitless. I tried opening a chat with very few messages to see what would happen and it scrolled all the way to the top to show the profile picture and short bio. I couldn’t scroll down.

Initial instinct was to think that my config was perhaps corrupted. I reset Caprine’s config folder in `.config` and logged in again. The problem persisted. 

I am unsure what is causing this, but the app is unusable with this bug. I confirmed I can still send messages, but with the automatic scrolling up, it’s not usable. Is there anything else I can try to troubleshoot? I could try taking a GIF video of it, but I’m concerned about security.

**Comment by dCosminn** [comment]
I have the same issue, it started today.
Caprine 2.58.0, Ubuntu 22.04

**Comment by ienzo** [comment]
@dCosminn how did you install it? Appimage or deb?

**Comment by dCosminn** [comment]
@ienzo Deb i think. 
I'm guessing Facebook changed something today which broke Caprine?

**Comment by ienzo** [comment]
Looks like the problem has been resolved on Facebook’s side. Closing this.
