### ISSUE TITLE
Vibrancy outside of main content area

### ISSUE THREAD

**Issue by MechMykl** [sindresorhus/caprine#212]
Vibrancy is a great feature, so I wanted to offer up this tip. Other apps in the Mac ecosystem use a similar effect, and BusyCal in particular feels like they delivered this well.

The main chat area background's primary function is to make text readable. Since the sidebar items are "additional information", it might make sense to have Vibrancy only show there when turned on.

Example of Vibrancy on sidebar, but not main content area:
![screen shot 2017-05-17 at 1 32 46 am](https://cloud.githubusercontent.com/assets/5373827/26141364/1be5f346-3aa1-11e7-8e0c-b1f402282b3f.png)

**Comment by jamiestraw** [comment]
I was just about to suggest this myself - it'd look _really_ nice and even more native with vibrancy applied to the sidebar.

**Comment by sindresorhus** [comment]
This is the default behavior now.
