### ISSUE TITLE
Restore Missing Chat History. Enter PIN

### ISSUE THREAD

**Issue by architeck** [sindresorhus/caprine#2122]
I cannot see any of my chat history or any ongoing messages. There's a "Restore missing chat history. Enter PIN" message but clicking on the the "Enter Pin" link does nothing.

---

Caprine 2.59.1
Electron 24.8.6
win32 10.0.19045
Locale: en-GB

**Comment by giannistolou** [comment]
The same applies to #2113, and there is an open pull request for #2108

**Comment by architeck** [comment]
I updated to the latest version and see the pin window prompt. However, the prompt is stuck on "verifying your pin" and doesn't progress further. The prompt acknowledges an incorrect pin but does nothing to progress with a correct one.

**Comment by mquevill** [comment]
This should be fixed as of #2108. Reopen if you experience this issue in newer versions (v2.59.2+)

**Comment by slaughter3000** [comment]
Desktop.  FB messenger stuck on "verifying your PIN".  I enter the CORRECT numbers and every time I get stuck on the infinite circle and then get asked again.  Man, Brave literally just pulled this same crap with Instagram.  Infernal.  Sigh.  
I also reset my PIN on the phone app version.  THAT pin is not working either.
Any solution?

V174.48
