### ISSUE TITLE
Tray icon doesn't light up when a new message is received

### ISSUE THREAD

**Issue by Bunnnyface** [sindresorhus/caprine#2123]
Everything works fine, sound notifications pop out when a new message is received. but the tray icon doesn't light up.
Visual notification can be useful when speakers are off.
---

Caprine 2.59.1
Electron 24.8.6
win32 10.0.19045
Locale: fr

**Comment by mquevill** [comment]
This should be fixed in version 2.59.3 for the main Chats interface. (Marketplace messages will not trigger the tray icon yet, but changes are in progress: #2133)
