### ISSUE TITLE
Caprine doesn't load after the update to the 2.59.2 version

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#2125]
It's just a white window on Linux.
Installed via apt.

KDE Neon  5.27 (Based on Ubuntu 22.04)

**Comment by kukkjanos** [comment]
The same problem is also present with me

**Comment by vanastasis** [comment]
Can confirm, does not load, like previous version loads to white screen even when .config/caprine folder removed.

OS: Kali GNU/Linux Rolling x86_64 
Kernel: 6.6.9-amd64 
Uptime: 11 mins 
Packages: 3945 (dpkg), 43 (flatpak) 
Shell: zsh 5.9 
Resolution: 1920x1200, 1920x1080 
DE: GNOME 45.2 
WM: Mutter 
WM Theme: Kali-Dark 
Theme: Kali-Dark [GTK2/3] 
Icons: Flat-Remix-Blue-Dark [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 14 
CPU: AMD Ryzen 9 5950X (32) @ 4.700GHz 
GPU: NVIDIA GeForce RTX 3080 Ti 
Memory: 5012MiB / 64218MiB

**Comment by lbtbs** [comment]
The same with Flatpak on Fedora Workstation 39.

# System Details Report
---

## Report details
- **Date generated:**                              2024-02-20 00:09:59

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaCentre Gaming5 14ACN6
- **Memory:**                                      16,0 GiB
- **Processor:**                                   AMD Ryzen™ 7 5700G with Radeon™ Graphics × 16
- **Graphics:**                                    NV176
- **Disk Capacity:**                               512,1 GB

## Software Information:
- **Firmware Version:**                            O5EKT21A
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.7.4-200.fc39.x86_64

**Comment by dusansimic** [comment]
Closing this issue in favor of #2129. Please update to the latest version once it's released.

**Comment by lbtbs** [comment]
The new version is working. Thank you!
