### ISSUE TITLE
Caprine Showing Blank Screen

### ISSUE THREAD

**Issue by anarchoferret** [sindresorhus/caprine#2127]
When Caprine opens, it will show messenger for a second or two, then go to a blank screen.  This only started after the most recent update.

[Screenshot of Issue](https://github.com/sindresorhus/caprine/assets/70930754/74ef0334-09a1-4de5-9d47-15e649721dc9)

---

Caprine 2.59.2
Electron 26.4.0
linux 6.7.5-1-liquorix-amd64
Locale: en-US

**Comment by kmarty** [comment]
same issue here. Version 2.59.1 works fine, 2.59.2 is one blank page.

**Comment by AleksandarBayrev** [comment]
same here, flatpak version, had to downgrade to 2.59.1, too

**Comment by giannistolou** [comment]
> same here, flatpak version, had to downgrade to 2.59.1, too

I have also the same problem with the new flatpak update, Ubuntu 22.04.3 LTS

**Comment by dusansimic** [comment]
Closing this issue in favor of #2129. Please update to the latest version once it's released.
