### ISSUE TITLE
Caprine launches, no elements in GUI window

### ISSUE THREAD

**Issue by cement-head** [sindresorhus/caprine#2128]
Install caprine; launch; no elements in GUI
![image](https://github.com/sindresorhus/caprine/assets/1056700/034e5858-4a86-4b23-859d-30af425f98f4)

---

Caprine 2.59.2
Electron 26.4.0
linux 6.6.10-76060610-generic
Locale: en-US

**Comment by dusansimic** [comment]
Closing this issue in favor of #2129. Please update to the latest version once it's released.
