### ISSUE TITLE
Can't change language in different country

### ISSUE THREAD

**Issue by namkam5** [sindresorhus/caprine#214]
I am in Dubai, I downloaded it for windows and Linux and am having trouble since the starting page is in Arabic. not that it matters because its intuitive. but still probably worth looking into

**Comment by sindresorhus** [comment]
Yeah. I've gotten this too in Thailand. I wonder if there's a cookie we can set to force it to a specific language.

**Comment by veniversum** [comment]
Yup we can set the locale in cookies, just like the main Facebook site. For example `locale=zh_CN` forces the page to display in Chinese.

Would a `--locale=` command line flag be an appropriate solution for this? We could save the value in config too so it would only have to be run once with the flag.

**Comment by sindresorhus** [comment]
The locale should just be the same as your computer. https://electron.atom.io/docs/api/locales/
