### ISSUE TITLE
Cannot forward or remove messages

### ISSUE THREAD

**Issue by nbngtn** [sindresorhus/caprine#2142]
When clicking on the forward or remove message option, the web version will display a pop-up window for the command. However, when I try to do that from Caprine, nothing happens.

Linux: OpenSUSE Tumbleweed

**Comment by mquevill** [comment]
What version of Caprine are you using? There was a critical fix in v2.59.2 that should correct this.

**Comment by mquevill** [comment]
If you are still having this issue with v2.59.2+, please feel free to reopen this issue.
