### ISSUE TITLE
Caprine not working. 

### ISSUE THREAD

**Issue by redwingsred** [sindresorhus/caprine#2158]
I have downloaded Caprine from the Pop shop on Pop!_OS 22.04 and I tried on Gnome software center and all the versions of Caprine will log in, but the conversations wont load and it is a blank page with the messenger logo. It wont load. 

Maybe it needs updating? 

Thank You. 

---

Caprine 2.59.3
Electron 25.9.8
linux 6.8.0-76060800daily20240311-generic
Locale: en-US

**Comment by mquevill** [comment]
On a fresh install of Pop!_OS 22.04 (in VirtualBox), Caprine from the Pop Shop seems to work fine for me.

However, if you've used Caprine before on this machine, it may have logged you out and sent you to a different login page that may not work exactly as expected. If you switch the theme (e.g. Dark -> Light), does this help you see any place to log in?

Could you send a screenshot of what you are able to see? This would help with debugging.

**Comment by redwingsred** [comment]
Go ahead and close this Ticket, it started up fine after a couple updates and a restart. Thank You for the reply.

**Comment by mquevill** [comment]
Great news!
