### ISSUE TITLE
Option to turn off badges?

### ISSUE THREAD

**Issue by matthewmueller** [sindresorhus/caprine#216]
Hey there! Been using this app for awhile and really like it :-). 

I was wondering if it's possible to turn off the badge count. I found the preference to disable the notifications, but I'd also like to be able to turn off the red badge on OSX. Is that possible?

**Comment by sindresorhus** [comment]
Yeah, that makes sense. Not just for macOS though. Caprine shows a badge on Linux and Windows too.

**Comment by daveseco7** [comment]
If a user has **Bounce Dock on Message** enabled and badge counter disabled, should it keep bouncing with no red badge ?

**Comment by sindresorhus** [comment]
Yes
