### ISSUE TITLE
"Messenger Settings" doesn't open

### ISSUE THREAD

**Issue by Plut0nio** [sindresorhus/caprine#2165]
Title says it all, basically. I've tried going to File > Messenger Settings, hitting Ctrl+Comma, and clicking my profile pic in the bottom left corner and clicking "Preferences". None of these methods work. From what I've read, this was a known issue in the past that was supposed to have been fixed a while ago (see https://github.com/sindresorhus/caprine/pull/2006 and https://github.com/sindresorhus/caprine/pull/2056), so I'm not sure why I'm having this issue. I'm using the non-Flatpak version installed from the Gemfury repo using apt. I also have issues similar to https://github.com/sindresorhus/caprine/issues/2098, except in addition, View > Sidebar > any option and View > Show Message Buttons, and View > Hide Names and Avatars don't seem to have any effect on anything.

---

Caprine 2.60.1
Electron 29.0.1
Linux Mint 21.3 Cinnamon
linux 5.15.0-105-generic
Locale: en-US

**Comment by jara001** [comment]
Same here. I am using `.deb` from this repo.

---

Caprine 2.60.1
Electron 29.0.1
Ubuntu 22.04.3
linux 6.5.0-15-generic
Locale: cs

**Comment by ohshitgorillas** [comment]
Same. On Pop!_OS, installed from the Pop!_Shop.

Caprine 2.60.1
Pop!_OS 22.04 LTS
Linux 6.8.0-76060800daily20240311-generic
Locale: en-US

**Comment by iGom** [comment]
Same on Arch
2.60.1

**Comment by mquevill** [comment]
See my comments about these hidden windows here: https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948

Closing this issue in favor of #2167
