### ISSUE TITLE
Chat bots support for Dark Mode

### ISSUE THREAD

**Issue by veniversum** [sindresorhus/caprine#218]
Currently some components used by Facebook bots are styled poorly or unstyled in dark mode.

Examples include various templates and quick reply buttons (see screenshot below).
![image](https://cloud.githubusercontent.com/assets/6357330/26367530/76e32784-4021-11e7-874b-3e9208c1b435.png)

**Comment by WPend-com** [comment]
I was just about to say this too, 
![dark messenger- black text](https://cloud.githubusercontent.com/assets/28764280/26409354/4699dd8a-4098-11e7-84b0-7cadaa92f11a.png)
Maybe there is a way of controlling the text color of messenger bots in dark mode.
