### ISSUE TITLE
Dark mode theme doesn't fit in window

### ISSUE THREAD

**Issue by WrayOfSunshine** [sindresorhus/caprine#2180]
In light mode, the buttons at the bottom of the Caprine screen fit in the window with a clear buffer between them and the bottom of the window itself. In dark mode, however, they are cut off.

Light mode bottom of screen:
![image](https://github.com/sindresorhus/caprine/assets/14261370/1e900cee-3ba2-4bbf-97d8-348fb4636631)

Dark mode bottom of screen:
![image](https://github.com/sindresorhus/caprine/assets/14261370/4592dd4b-37d4-4e89-8883-9dbe0838c211)

Using my mouse wheel I can scroll the dark mode window up and down.

Uncertain how to reproduce, if it isn't happening to everyone

---

Caprine 2.60.1
Electron 29.0.1
linux 5.15.0-107-generic
Locale: en-US

**Comment by dan1mmm** [comment]
Same issue.

Caprine 2.60.1
Electron 29.0.1
win32 10.0.22631
Locale: zh-TW

**Comment by Sebron** [comment]
Does this need testing before merge?

**Comment by dan1mmm** [comment]
While the issue remains, the message bubble we sent turn disappears when it should be blue.

![image](https://github.com/sindresorhus/caprine/assets/86565219/24df999c-b6c4-40df-9ef0-6a9d2ddc3330)

**Comment by sebastian89n** [comment]
Same issue. Hope it gets fixed. I want to use dark mode but it's annoying.
