### ISSUE TITLE
Problem with synchronization of messages

### ISSUE THREAD

**Issue by grzegorj** [sindresorhus/caprine#2188]
After a new installation of Caprine, messages newer than of the end of March 2024 do not show up. Instead, you can see a message:  “Some messages are missing. Synchronize now.” (translated back from my local language into English)
“Synchronize now” looks like a hyperlink. But if you click it, nothing happens. Especially, no lacking messages re-appear.

If a new message shows in this conversation (not important, from me or from the person I am talking with), the previously seen message “Some messages are missing. Synchronize now.” is not seen any longer. Now the lacking messages are still invisible, and there is no way to make them appear again.

The messages in question are coded. The original client (Messenger) has no problems with bringing them back, so it must be not impossible. It is Caprine which has problem with them. And which is more, it seems to offer a function (“Synchronize now”) which does not work at all. So, what is it for?

---

Caprine 2.60.1
Electron 29.0.1
win32 10.0.22000
Locale: pl

**Comment by triforcely** [comment]
https://github.com/sindresorhus/caprine/issues/2167

**Comment by logiclrd** [comment]
"Not planned"?? If anything, this should have been closed as a duplicate...

**Comment by mquevill** [comment]
> "Not planned"?? If anything, this should have been closed as a duplicate...

It is closed as a duplicate. If you mouse over the "not planned" status, GitHub's help text is "Won't fix, can't repro, duplicate, stale". The only built-in options in GitHub are either "Close as completed" or "Close as not planned".
