### ISSUE TITLE
No Dark Mode

### ISSUE THREAD

**Issue by umop3plsdn** [sindresorhus/caprine#2193]
I'm using 2.60.1-1 and I cannot trigger dark mode for the life of me by using the selector for system auto or forced on or off. I type "document.querySelector('html').classList.add('__fb-dark-mode')" into the dev console WHICH WORKS but as soon as I move my cursor over the window it turns back white or when I press F12 to make it disappear again. Anyone got any ideas?

**Comment by agret** [comment]
Caprine overrides your Facebook setting. In Caprine click on View - Theme - Dark Mode
