### ISSUE TITLE
Oversized root element causing scrolling of whole window

### ISSUE THREAD

**Issue by Windows200000** [sindresorhus/caprine#2194]
When scrolling outside of a normally scrollable region (above Chats, above Conversations, on the sidebar) the whole window scrolls, which is a little disorienting and causes parts to be cut off. The same happens, when reaching the bottom of a conversation, as scrolling propagates to parent elements.

This happens both when Maximized and Windowed.

https://github.com/sindresorhus/caprine/assets/72623832/dc75f944-6562-4f49-b736-e4e816f5af54

**OS**: Windows 11 Pro 23H2 22635.3785
**version**: 2.60.1 from releases.

**Comment by mquevill** [comment]
I believe this is connected to #2180, and should hopefully be fixed when #2155 gets pulled in.
