### ISSUE TITLE
Simple fix: scrolling bug and dark theme issue (follow this)

### ISSUE THREAD

**Issue by devCKVargas** [sindresorhus/caprine#2196]
This is a temporary fix, but I just wanna put this here for anyone.
Also fixes: https://github.com/sindresorhus/caprine/pull/2155#issuecomment-2178244156, #2180, #2194, 
Does not fix: #2189

## Instruction
1. From the menu bar click `File` > `Caprine Settings` > `Advanced` > `Custom Styles`
    - If you get an error message saying: `This file does not have an app associated with it for performing this action` [follow this fix (windows)](https://github.com/sindresorhus/caprine/issues/2196#issuecomment-2193013151)
2. Paste the code below, save it and close the notepad or whatever editor you use
3. Click your caprine window to focus and `Ctrl + R` to reload the current changes

**[Another layout](https://github.com/sindresorhus/caprine/issues/2196#issuecomment-2194045345): no spacing and rounded corners**

## Code to paste in your custom.css:
```
/* variable */
.__fb-dark-mode {
	--card-spacing: 0px;
}

/* you can remove this to keep the space on the right most card*/
.x1mj4gcd.x1mj4gcd {
	padding-right: var(--card-spacing);
}

/* Remove top space between the cards and the menu bar */
.x13dmulc.x13dmulc {
	margin-top: var(--card-spacing); 
}

/* Fix user account picture cutout or bad spacing*/
.xz9dl7a.xz9dl7a  {
	padding-bottom: 6px; 
}
```

- This removes the spaces from the top and right corner of the cards to prevent the weird scrolling behavior but not #2189.
- It also adds a space between the user's profile photo on the bottom left corner.
- This would not mess with any themes whatsoever, so you won't encounter https://github.com/sindresorhus/caprine/pull/2155#issuecomment-2178244156.
Check these attached screenshots to see the before and after:

## Before
![before](https://github.com/sindresorhus/caprine/assets/50130192/0fa8dbf1-293f-4671-a9c5-b0c0d16a6c55)
## After
![after](https://github.com/sindresorhus/caprine/assets/50130192/56ebe031-9d27-4048-a083-24cccc123af0)
![cutout fixed](https://github.com/sindresorhus/caprine/assets/50130192/02b258d0-730d-44cf-860d-2cfa1e86bd36)

**Comment by devCKVargas** [comment]
### Fix of no app associated with .css

1. Open your run command window by pressing:

```
Windows Key + R
```
![screenshot of run command window](https://github.com/sindresorhus/caprine/assets/50130192/338ecc2e-1b9a-4fa8-b196-2694e7bf4d4a)

2. Paste and run this:

```
%appdata%\Caprine\custom.css
```

3. It should ask you what app should open the current file, select or find your text editor eg. notepad, code, sublime, etc..

![screenshot of a pop-up asking the user to pick an app to open the custom.css file](https://github.com/sindresorhus/caprine/assets/50130192/a6bb05e7-387a-4f6b-91a9-6f98f32bb2d5)

**Comment by devCKVargas** [comment]
## Code
```
/* variable */
.__fb-dark-mode {
	--card-spacing: 0px;
}

/* you can remove this to keep the space on the right most card*/
.x1mj4gcd.x1mj4gcd {
	padding-right: var(--card-spacing);
}

/* you can remove this to keep the space on the left most card (Inbox) */
.x1hys8i7.x1hys8i7 {
	padding-left: var(--card-spacing);
}

/* Removes the space from the left most corner */
.xdhzj85.xdhzj85 {
	margin-left: var(--card-spacing);
}

/* Remove top space between the cards and the menu bar */
.x13dmulc.x13dmulc {
	margin-top: var(--card-spacing); 
}

/* Fix user account picture cutout or bad spacing*/
.xz9dl7a.xz9dl7a  {
	padding-bottom: 6px; 
}

/* Removes the roundness of the corners */
.xzhurro.xzhurro, .xpyiiip.xpyiiip, .x88v6c3.x88v6c3, .x6gs93r.x6gs93r {
	border-radius: var(--card-spacing); 
}
```

## Screenshot

![Caprine_FO5s9pkgAx](https://github.com/sindresorhus/caprine/assets/50130192/9ab7a115-25a8-456a-a966-f5af2d558b03)

**Comment by mquevill** [comment]
Thanks for these temporary workarounds. Hopefully they should no longer be needed as of newer versions (v2.60.3).
