### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by v3rlain3** [sindresorhus/caprine#22]
please add support for configuring proxy

**Comment by sindresorhus** [comment]
No thanks

**Comment by pzi** [comment]
For anyone finding this issue, hope this helps:
I was looking for proxy support as well and have found the following worked for me.

Using [electron's session API method `setProxy`](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback) callback I wrapped `win.loadURL(mainURL);` in [`index.js:201`](https://github.com/sindresorhus/caprine/blob/master/index.js#L201) as follows:

```js
  win.webContents.session.setProxy({ proxyRules: 'http://proxy.foo.com:80' }, () => {
    win.loadURL(mainURL);
  })
```
Built the app and it works fine with the company proxy. Will just have to keep updating it manually when a new release comes out 😏

**Comment by olivierverville** [comment]
wow, no thanks? really ... wtf.

**Comment by ury2000** [comment]
really ?
I hoped find an Awesome Caprine, but i faced this issue

**Comment by ser** [comment]
system proxy setting are not being read. caprine says "no internet connection" and refuses to work.
