### ISSUE TITLE
Password possibly adding salt value to password before encryption.

### ISSUE THREAD

**Issue by actionboy6** [sindresorhus/caprine#2201]
I am attempting to sign into messenger using your program, 
Password is adding characters to the password before sending traffic to Facebook. I'm guessing that the salt value is being added before being sent for encryption to Facebook.

---

Caprine 2.60.1
Electron 29.0.1
linux 5.15.0-91-generic
Locale: en-US

**Comment by mquevill** [comment]
This is the same behavior that appears if you log into [messenger.com](https://www.messenger.com/) on a standard browser. There is no change to this behavior from Caprine's side. See discussion here: https://github.com/sindresorhus/caprine/issues/2137#issuecomment-1982232668

**Comment by mquevill** [comment]
Closing in favor of #2137.
