### ISSUE TITLE
can't forward messenge, pin messenge, open setting, can't scroll up old messege, can't open image in private chat, do not show up call

### ISSUE THREAD

**Issue by tloc241** [sindresorhus/caprine#2203]
my system: 
OS: Ubuntu 24.04
kernel: 6.9.9-1-liquorix-amd64
app version: 2.60.1 

if this duplicate, feel free to close it, <3

**Comment by czerwinski76** [comment]
+1
I can't open a discussion to write or read any message.

**Comment by kwongtn** [comment]
Same issue with 

Caprine 2.60.1
Electron 29.0.1
win32 10.0.26120
Locale: en-US

**Comment by mquevill** [comment]
This is related to #2167 and should be resolved by #2181.
