### ISSUE TITLE
[Link in body]

### ISSUE THREAD

**Issue by kamoldinovU** [sindresorhus/caprine#2206]
https://cdn.fbsbx.com/v/t59.2708-21/452627423_479675171679649_2602759786295430969_n.pptx/2024%E5%AD%A6%E5%B9%B4%E8%AB%96%E6%96%87%E7%99%BA%E8%A1%A8%E4%BC%9A_CJLU_%E3%82%AB%E3%83%A2%E3%83%AB%E3%83%87%EF%BD%B2%E3%83%8E%E3%83%95%E3%82%A6%E3%83%AB%E3%82%B0%E3%83%99%E3%82%AF_20240724_feedback.pptx?_nc_cat=107&ccb=1-7&_nc_sid=2b0e22&_nc_ohc=MkqoCJunlkcQ7kNvgHQHjFz&_nc_ht=cdn.fbsbx.com&oh=03_Q7cD1QEDzsO1kTyr65lgNKd5jWuW6KPffCkL4xA4yTElb-2hvg&oe=66A55030&dl=1&fbclid=IwZXh0bgNhZW0CMTEAAR237z9ej9aj9NBGbyjNJA0dVjIu90Ae7skzaSEvxWvopQ5jhbaHTRopv3s_aem_VFxq_bGfHDMGLRLwmu2sBQ

**Comment by mquevill** [comment]
Cannot determine what the issue is as the URL signature has expired.
