### ISSUE TITLE
End-to-end encryption rollout seems to break Caprine

### ISSUE THREAD

**Issue by jaymzh** [sindresorhus/caprine#2211]
I don't see any messages in any threads that FB has converted to E2E.

I see the related preferences to enable E2E under `Profile -> Privacy and Safety -> End-to-end encrypted chats -> Secure storage`, but it's set to "off: and clicking on that doesn't do anything.

**Comment by nutuxedo** [comment]
Hello, suffering this issue too.

**Comment by eoryb** [comment]
Same problem here :-(
_(With the current latest version 2.60.1 )_

**Comment by mquevill** [comment]
Duplicate of #2167.
