### ISSUE TITLE
Facebook Messenger security upgrade on mid June 2024 broke chat synchronicity with Caprine 2.60.1 Linux 

### ISSUE THREAD

**Issue by lortega70** [sindresorhus/caprine#2213]
Messages in Facebook Messenger app for iPhone and Caprine for Linux desktop were synchronised until 14 June 2024. Then I see an internal" legend in the iPhone app "Messenger upgraded the security of this chat. Messages and calls are secured with end-to-end encryption."
After that, none of the messages showing in my iPhone FB Messenger app show in my Caprine for Linux desktop application.
Caprine for Linux desktop shows a legend: "Messenger upgraded the security of this chat..." ... "Messages are missing. Sync now (button)". I press "Sync now" in Caprine, it shows a legend "code sent"; my iPhone shows me a pop-up message "Did you request a one-time code"?. I press a button "This was me" and the pop-up message displays a 6 digits code I'm supposed to enter in my other device. (Expires in 5 minutes). BUT there's nowhere to enter this code in the Caprine for Linux desktop application, so it cannot sync. 
---

Caprine 2.60.1
Electron 29.0.1
linux 5.15.0-116-generic
Locale: en-GB
I'm using Linux Mint 21.2 Cinnamon version 5.8.4. The Linux kernel is correct above.
Facebook Messenger app on iPhone 7 Plus

**Comment by mquevill** [comment]
Duplicate of #2167. Please see that issue for current workaround.
