### ISSUE TITLE
Caprine won't start

### ISSUE THREAD

**Issue by olilag** [sindresorhus/caprine#2220]
If I run the command `caprine` in terminal to start it, I only get the following printed to the terminal:
```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
```

My system is EndeavourOS, I downloaded `caprine` from AUR.

**Comment by olilag** [comment]
Update: `caprine` didn't like that I was auto-starting it through hyprland's `exec-once`. It works now that I removed that line from config.

**Comment by Sectimus** [comment]
I got this same problem, but KDE6 arch, not hyperland

https://github.com/sindresorhus/caprine/issues/2294
