### ISSUE TITLE
Constantly switching to Marketplace section

### ISSUE THREAD

**Issue by martinoak** [sindresorhus/caprine#2222]
When Caprine is opened, there is some kind of timer? that switches to Marketplace every few seconds. Its really annoying.

---

Caprine-pro 1.0.0
Electron 21.2.0
linux 6.8.0-41-generic
Locale: en-US

**Comment by mquevill** [comment]
You are not using Caprine, but instead "Caprine-pro" which is someone's very outdated fork. See here: https://github.com/sindresorhus/caprine/issues/2186#issuecomment-2150706844
