### ISSUE TITLE
Is caprine abadonware ?

### ISSUE THREAD

**Issue by spinalgr1990** [sindresorhus/caprine#2225]
Is caprine abadonware ?

**Comment by ewal** [comment]
My thoughts also. The UI looks sketchy and I hesitated before I entered my credentials. Luckily I have 2fa enabled.

**Comment by CybernetiX-S3C** [comment]
@spinalgr1990 @ewal  I am able to log in and have used this since the fist version. It has worked flawlessly and has been safe. But, syncing messages is an issue.

**Comment by kacnje** [comment]
Sadly, it looks so. 
With a few improvements, Caprine could be an excellent client. 
Does someone know of a similar program? The original Messenger client lacks many interesting features expected from a chat client.

**Comment by Jilmoire** [comment]
> My thoughts also. The UI looks sketchy and I hesitated before I entered my credentials. Luckily I have 2fa enabled. Btw, login didn't work.

when opening caprine, try pressing your f12 key and It will pull up an Inspect window. find the class `hide-preferences-window` and remove it.
more details here: https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948

**Comment by SilverSaw** [comment]
@Jilmoire not possible anymore to save our edits by removing `hide-preferences-window`, it is active during the current session, but returning back when i restart caprine this is happening since few days, do you know workaround ?

**Comment by Jilmoire** [comment]
Unfortunately, I don't know either.

**Comment by mquevill** [comment]
Caprine is ultimately a wrapper for the Messenger.com interface with a few added features. It has gotten harder to keep up with back-end changes especially. We'll always welcome contributions from the community.

[v2.60.2](https://github.com/sindresorhus/caprine/releases/tag/v2.60.2) was released today
