### ISSUE TITLE
Can't sync old messages. The input for the pin never appears

### ISSUE THREAD

**Issue by AndrejSavatic** [sindresorhus/caprine#2226]
---

Caprine 2.60.1
Electron 29.4.6
linux 6.10.8-arch1-1
Locale: en-US

**Comment by lordgabor** [comment]
https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948

> A temporary workaround: If you access the developer tools via F12, you can edit the main <html> element to remove the hide-preferences-window class from the list within class="...".

**Comment by mquevill** [comment]
Duplicate of #2167.
