### ISSUE TITLE
Messenger features not working

### ISSUE THREAD

**Issue by dwolfuk40** [sindresorhus/caprine#2230]
I'm running windows 11 x64 on three machines and all have the same issues

The ability to leave chats is there but does nothing. The same with report or delete chat. Archive chat works fine.
File -> Messenger Settings does nothing on my machine.

I could well be missing something but since it occurs on 3 machines. One is a brand new machine with fresh install.

---

Caprine 2.60.1
Electron 29.0.1
win32 10.0.22631
Locale: en-GB

**Comment by mquevill** [comment]
This issue should be fixed in #2181 in release [v2.60.2](https://github.com/sindresorhus/caprine/releases/tag/v2.60.2). If you're still having this behavior, feel free to reopen this issue.
