### ISSUE TITLE
End-to-end encryption: "restore now" link doesn't work

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#2242]
Steps to reproduce
- caprine 2.60.1
- windows 10
- have an encrypted conversation with someone using the Facebook Messenger app
- then log in to Caprine
- the following is displayed where you'd expect to see those messages
<img width="284" alt="image" src="https://github.com/user-attachments/assets/80cf3a14-4a4b-4930-8a61-f4bcc249f1cc">
- click "Restore now"

What happens?
- nothing

What should happen instead?
- you are prompted to enter your pin number, then your encrypted messages are loaded

**Comment by sidnoway** [comment]
This is a client-breaking bug. And with the ever-approaching deadline for the deprecation of the UWP Windows app, this would be very beneficial to fix because the new official client is an Edge wrapper.

**Comment by Sp3EdeR** [comment]
It looks like this may be a more generic issue. As far as I can see, some popup windows are not showing right now. If I try to open the Messenger settings within the app, that's also not showing. If I try to report a chat, its popup also does not show. So I'm guessing that nothing works that uses a popup dialog.

**Comment by Sp3EdeR** [comment]
I still have this issue in v2.60.2, @mquevill . Just checked. No popups are showing.

**Comment by Sp3EdeR** [comment]
I deleted all of the Electron cache folders to make sure everything is refreshed, but the issue still exists.

**Comment by mquevill** [comment]
@Sp3EdeR Can you check if you have the `hide-preferences-window` class when you open the developer tools (shortcut F12)?

**Comment by Sp3EdeR** [comment]
On the <html> tag, I do have that class on.

**Comment by mquevill** [comment]
Can you open the menu "Help" > "Report an issue..." and copy all the version numbers and locale information?

**Comment by Sp3EdeR** [comment]
Of course!

```
Caprine 2.60.2
Electron 29.0.1
win32 10.0.22631
Locale: hu
```

**Comment by mquevill** [comment]
This is a localization issue. See https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2509112013

I am closing this issue in favor of #2167
