### ISSUE TITLE
password text box

### ISSUE THREAD

**Issue by phydeaux24** [sindresorhus/caprine#2248]
Upon attempted login, my text box fills with autofill crap. I cannot enter my registered password. After typing my pw, any and all mouse clicks autofills the pw box with rando fill. What gives?

---

Caprine 2.60.1
Electron 29.0.1
linux 6.11.2-amd64
Locale: en-US

**Comment by mquevill** [comment]
This is the same behavior that appears if you log into [messenger.com](https://www.messenger.com/) on a standard browser. There is no change to this behavior from Caprine's side. See discussion here: https://github.com/sindresorhus/caprine/issues/2137#issuecomment-1982232668

Closing in favor of #2137.
