### ISSUE TITLE
Password Entry adds characters when clicking Login

### ISSUE THREAD

**Issue by EasyasPie123** [sindresorhus/caprine#2250]
I dont have this issue with any other apps and am running Linux Mint 22.  My username has no problems and when i type the password it appears correct and then when i click login an unknown amount of characters are added to my entered characters.

---

Caprine 2.59.3
Electron 25.9.8
linux 6.8.0-38-generic
Locale: en-GB

**Comment by mquevill** [comment]
This is the same behavior that appears if you log into [messenger.com](https://www.messenger.com/) on a standard browser. There is no change to this behavior from Caprine's side. See discussion here: https://github.com/sindresorhus/caprine/issues/2137#issuecomment-1982232668

Closing in favor of #2137.
