### ISSUE TITLE
Caprine for Mac No Longer Updated Since Apr 9, 2024. Switch to Messenger for Mac

### ISSUE THREAD

**Issue by Yodoma** [sindresorhus/caprine#2253]
I noticed that since April 9, 2024, Caprine for Mac has stopped receiving updates. Despite many reports of bugs, it seems nothing is being fixed. I deleted Caprine completely for my Mac. For continued access to Facebook messaging features, I've switched to Messenger for Mac from Facebook here [] (https://www.messenger.com/desktop). In the meantime, I'll be exploring other messaging apps. Let me know if you come across any good alternatives!

**Comment by mquevill** [comment]
New release of [v2.60.2](https://github.com/sindresorhus/caprine/releases/tag/v2.60.2) is out now
