### ISSUE TITLE
Release v2.60.2 only has Linux binaries

### ISSUE THREAD

**Issue by Sp3EdeR** [sindresorhus/caprine#2254]
It seems that the v2.60.2 release only contains the Linux binaries, and Mac and Windows ones are missing from it.
The build and publish action seems to have weird logs in the release creation parts for each platform: https://github.com/sindresorhus/caprine/actions/runs/12097909669

FYI, @mquevill

**Comment by mquevill** [comment]
I think I swapped the order of some of the build steps, which caused those issues in the release creation. I'm uploading the Mac and Windows ones now.
