### ISSUE TITLE
Can't scroll back past last few messages

### ISSUE THREAD

**Issue by 1raj1** [sindresorhus/caprine#2256]
Scrolling back in a (group or individual) chat past last few messages does not work; a spinning wheel indicating loading appears and the content never loads.
Screenshot (with names redacted) attached. Note the spinning mark at the top - can't scroll back past that.
![Zrzut ekranu z 2024-12-01 10-05-09](https://github.com/user-attachments/assets/e8f0e3d3-6d45-4a79-9ad3-ee895f0458b4)

---

Caprine 2.60.2
Electron 29.0.1
linux 5.15.0-126-generic
Locale: pl

**Comment by mquevill** [comment]
Do you still have this issue with v2.60.3? Some of the fixes in v2.60.2 may not work across different locales (non-English), but v2.60.3 should correct that.
