### ISSUE TITLE
"Messages are missing. Restore now" not working

### ISSUE THREAD

**Issue by mikulik86** [sindresorhus/caprine#2266]
After installation, my chats loaded only partly. There is a banner on the bottom of a chat saying `Messages are missing. Restore now`:
![image](https://github.com/user-attachments/assets/a0f577d7-2c6c-426b-90f2-51f1c32a2d5d)
When I click it, I'll get a one time code on my phone, but nothing else happens.
How do I get the messages restored?

---

Caprine 2.60.3
Electron 29.0.1
win32 10.0.22631
Locale: en-US

**Comment by dagerga** [comment]
Having the same issue

**Comment by dagerga** [comment]
> Why was this issue closed as not planned without at least an explanation? I'm having this problem right now after an upgrade from Debian 12 to 13.1. Some contacts shows the notice in your initial post and nothing happens when I click on the Restore now link. This has not been fixed.

https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948 here is a temporary fix but youll have to do it again every time Facebook f***s with their back end.
