### ISSUE TITLE
Archive menu item/shortcut doesn't work

### ISSUE THREAD

**Issue by yeastcapp** [sindresorhus/caprine#228]
Hi there,

Caprine's menu item/shortcut for archiving conversations doesn't seem to work.

Also, is there a way to bind the archive shortcut to another key?

Great app btw!

Tim

-

Caprine 2.3.1
Electron 1.6.7
darwin x64 16.6.0

**Comment by daveseco7** [comment]
Hello,

The same goes for the **Delete** and **Mute** conversation menu item/shortcut.
Tested with the version currently in master.
