### ISSUE TITLE
Strange view with 2FA

### ISSUE THREAD

**Issue by mahfysh-fb** [sindresorhus/caprine#229]
Use 2FA https://cl.ly/363h3L1v1W2l
-

Caprine 2.4.0
Electron 1.6.7
darwin x64 16.6.0

**Comment by sindresorhus** [comment]
@veniversum We need to either catch the URL and open it in a new window or style the page to look part of the app.

**Comment by veniversum** [comment]
@sindresorhus I think styling the page is the better option. The 2FA page would look somewhat off in a new window too with the truncated header and footers. Maybe we can hide those and pad the Facebook logo a bit to allow space for the window controls?

**Comment by sindresorhus** [comment]
I think we could just hide everything except for the Facebook logo and the form.

**Comment by Phuurl** [comment]
Also on the 2FA screen, none of the text is readable in dark mode.
<img width="912" alt="Screenshot 2019-05-25 at 11 07 04" src="https://user-images.githubusercontent.com/1835431/58367968-bf11d580-7edd-11e9-8ce8-379779c7db18.png">
