### ISSUE TITLE
Windows - focus window when interacting with notification

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#235]
Currently, clicking the notification will only dismiss it. Would be nice if it focused / restored the window and showed the relevant conversation as well.

**Comment by sindresorhus** [comment]
👍

**Comment by tamasviktor** [comment]
Hi @sindresorhus  maybe this docs helps for you: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts

**Comment by sindresorhus** [comment]
The notifications are triggered by the Facebook Messenger code, but I guess we could monkey-patch the `Notifications` API to hook into it and focus the window.

**Comment by tamasviktor** [comment]
Great! Thank you.

**Comment by jackwilsdon** [comment]
This also seems to be an issue on Ubuntu 18.04 - I assume it affects all OSes?

**Comment by CvX** [comment]
I believe this isn’t an issue anymore, is it? Closing for now.
