### ISSUE TITLE
Very high battery consumption in macOS

### ISSUE THREAD

**Issue by nthakor** [sindresorhus/caprine#238]
The app consumes a huge amount of battery in macOS. Its battery impact is way higher that safari and chrome. Please do something about it.

**Comment by zpv** [comment]
Can confirm -
Caprine has the highest avg energy impact, above Chrome.

![Pic](http://cl.ly/1V2j1A1q1Z2L/s.png)

**Comment by sindresorhus** [comment]
I've disabled hardware acceleration now, so we'll see in the next release whether it helps.

Hopefully Electron will add a way to force the integrated GPU instead of completely disabling GPU usage: https://github.com/electron/electron/issues/9842

**Comment by fatso83** [comment]
@sindresorhus, will that fix apply to the Linux version as well? I was about to report high power consumption on the Linux version, seeing that it consistently axed my battery life by 2/3 (~2 hours, instead of close to 7 hours).

**Comment by nthakor** [comment]
@sindresorhus Have you integrated this fix in the product?

**Comment by sindresorhus** [comment]
Yes

**Comment by sindresorhus** [comment]
"Hardware Acceleration" is on by default now because of glitches showing on some system without. You can turn off "Hardware Acceleration" in the settings.

Other than that, we can't do much about it. It's all on https://github.com/electron/electron Complain there.
