### ISSUE TITLE
Work Chat compatiblity

### ISSUE THREAD

**Issue by chabou** [sindresorhus/caprine#239]
I forked your project to add compatibility with Work Chat (Messenger version for Enterprise). I only changed 4 lines to make it work.

Are you interested in a PR to switch between Messenger and Work Chat ? If not, I'll maintain my fork, because I need it at work but it could be useful for other people.

**Comment by sindresorhus** [comment]
Sure :)

**Comment by chabou** [comment]
Implemented by #245
