### ISSUE TITLE
Fresh install on macOS 10.12.5

### ISSUE THREAD

**Issue by nicpolhamus** [sindresorhus/caprine#243]
I'm trying to launch Caprine, but everytime I launch it, the window is blank.
Here is a screenshot of what I'm looking at.

![image](https://user-images.githubusercontent.com/13815614/27765739-9f29cc76-5e7f-11e7-8a67-45739474b4b7.png)

Thanks for any assistance.

-

Caprine 2.4.0
Electron 1.6.7
darwin x64 16.6.0

**Comment by sindresorhus** [comment]
I cannot reproduce this. We probably fixed it at some point.
