### ISSUE TITLE
macOS High CPU Usage

### ISSUE THREAD

**Issue by zpv** [sindresorhus/caprine#244]
The Caprine Helper process seems to consistently have the highest CPU usage on my machine.

![image](https://user-images.githubusercontent.com/12267041/27772407-9706c552-5f16-11e7-9541-0cb3273330e9.png)

**Comment by tymscar** [comment]
I started experiencing this now as well. Almost exactly one year later. Never had a problem in the past 3 months of using this program.

**Comment by sindresorhus** [comment]
Not much we can do about this, unfortunately.

Go complain here: https://github.com/electron/electron
