### ISSUE TITLE
Block Facebook link tracking when "Copy link" chosen

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#248]
PR #226 fixed #224 when clicking on a link. If you right-click a link and choose "Copy link" the Facebook-wrapped tracking link is still copied, though.

**Comment by mgol** [comment]
cc @kevva

**Comment by kevva** [comment]
Probably best to do this when https://github.com/sindresorhus/electron-context-menu/pull/44 is merged.

**Comment by JoniVR** [comment]
+1 This would be really useful.
