### ISSUE TITLE
Frameless Window Option

### ISSUE THREAD

**Issue by Bush1do** [sindresorhus/caprine#249]
Has anyone considered a frameless window option? I found it makes the app look much sexier.

![example](https://user-images.githubusercontent.com/12645067/27996880-534530de-64ba-11e7-96d9-daba2d1396eb.png)
.

**Comment by PombaM** [comment]
:-1:

**Comment by sindresorhus** [comment]
How would you access the menus then?

**Comment by Bush1do** [comment]
Menus? The toolbar doesn't do much from what I've seen besides closing and minimizing the window (which could be done by adding an "X" button next to the info button) and just looks weird while using the dark theme.

**Comment by sindresorhus** [comment]
There are many menus. Press Alt to show them.

**Comment by Bush1do** [comment]
Unless there were some way to make the menus part of the app I guess it would be a setback
