### ISSUE TITLE
[enhancement] Locked Chats

### ISSUE THREAD

**Issue by parthradia** [sindresorhus/caprine#250]
Would love to see a "locked chats" feature:
- Special section in my inbox that requires a pass-code to enter. Automatically locks back up when Caprine window loses focus.
- Notifications for these chats are universal & anonymous - I should only see "New message - contents hidden"

Pretty useful for when I need to leave my laptop unattended for short periods of time, and I forget to put it to sleep immediately.

**Comment by Bush1do** [comment]
Caprine is literally the messenger website in the form of a desktop app.
So only Facebook can add or remove things I believe.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but this is not something I'm interested in adding. Too much work for too little gain. 😀

**Comment by parthradia** [comment]
Would you be open to a pull request? I have decent experience with Electron!

**Comment by sindresorhus** [comment]
Not for this, sorry.
