### ISSUE TITLE
Add support for downloading media

### ISSUE THREAD

**Issue by PombaM** [sindresorhus/caprine#253]
Caprine 2.4.0
Electron 1.6.7
linux x64 4.12.0-041200-generic

**Comment by sindresorhus** [comment]
Can you elaborate? Downloading media should already be working. What's not working? How to reproduce?

**Comment by PombaM** [comment]
Just double checked, medias are downloaded but silently (which was why I was led to believe that they weren't downloading).

Consider adding a notifications on & after medias are downloaded?? Not sure if electron has its own apis for that.

**Comment by veniversum** [comment]
Uploading media should work with drag & drop, and the add files button should display a native file selection dialog.

Downloading of media is handled by your default browser, just like any other links. Is this not the case?
