### ISSUE TITLE
Sign In Issue

### ISSUE THREAD

**Issue by iChristosK** [sindresorhus/caprine#254]
So I signed out from caprine. And now it's been stuck at this page for days.
Any way how to fix this and sign in?
Thank you in advance.

<img width="456" alt="screen shot 2017-07-12 at 11 34 01" src="https://user-images.githubusercontent.com/16455384/28108973-17ff8b6c-66f6-11e7-9b73-a9295ea31c02.png">

-

Caprine 2.5.0
Electron 1.6.7
darwin x64 16.6.0

**Comment by sindresorhus** [comment]
Closing as there have been no other reports about this and I can not reproduce.

**Comment by 8BitSloth** [comment]
I am experiencing the same issue. I had this same thing happen with Messenger for Desktop then decided to uninstall that and try Caprine. When I started up Caprine I am getting this exact window and nothing else.

My most recent change to Facebook was generating a new 2-factor secret.

Caprine 2.9.0
Electron 1.8.2
Arch Linux 4.15.7-1
