### ISSUE TITLE
Dark Mode with Vibrancy on High Sierra

### ISSUE THREAD

**Issue by round** [sindresorhus/caprine#260]
On High Sierra (10.3) Beta 2 the window appears as shown below when it is in Dark Mode with Vibrancy enabled:

<img width="1072" alt="screen shot 2017-07-19 at 1 47 52 pm" src="https://user-images.githubusercontent.com/2340336/28381452-e2abc4ec-6c88-11e7-90d4-58dce951457a.png">

The title bar appears to not compositing vibrancy. Here it is overlaid for context:

<img width="1264" alt="screen shot 2017-07-19 at 1 47 41 pm" src="https://user-images.githubusercontent.com/2340336/28381455-e59badca-6c88-11e7-8ba1-dc5e796fce8c.png">

**Comment by sindresorhus** [comment]
Seems like a bug with Electron. It might have been fixed in the latest Electron version, which is currently unstable.

**Comment by mdeboer** [comment]
Can confirm this also appears in other Electron apps, also see this issue:
https://github.com/electron/electron/issues/10521

**Comment by sindresorhus** [comment]
Closing in favor of #295 as this is not just a problem with dark mode.
