### ISSUE TITLE
Paste text content outside caprine moves that text to inside caprine

### ISSUE THREAD

**Issue by flipperfipper** [sindresorhus/caprine#263]
A lot of times on the Mac Im coping text and the content goes to caprine instead of where I want to. this is really annoying.

-

Caprine 2.5.0
Electron 1.6.7
darwin x64 16.5.0

**Comment by flipperfipper** [comment]
duplicated

**Comment by sindresorhus** [comment]
Duplicate of #258.

**Comment by sindresorhus** [comment]
New release is out that disables the problematic code: https://github.com/sindresorhus/caprine/releases/tag/v2.6.0
