### ISSUE TITLE
Add ability to remove names from group chat in any order.

### ISSUE THREAD

**Issue by bpsizemore** [sindresorhus/caprine#264]
Steps Taken:

1. Click new message icon
2. Add 3 people (joe, bob, jane)
3. I decide that I don't want joe in the chat, I have to delete all names in order to remove him.

Just a feature request to allow an easier way to remove individuals from group chats.

**Comment by veniversum** [comment]
You can already select entered names by clicking, and delete them individually (in any order) by backspacing. I see no need in introducing additional features for this in Caprine.
