### ISSUE TITLE
Clipboard text is being pasted to Caprine chat window while it is in the background

### ISSUE THREAD

**Issue by benknight** [sindresorhus/caprine#267]
There's some weird issue going on where, with Chrome in focus, if I select text, copy it and and then paste, the text is not pasted where my cursor is in Chrome, but where my cursor is in Caprine.  It seems like the active cursor in Caprine is somehow taking precedence over the active cursor in Chrome.  So far I am unable to provide steps to consistently reproduce.

Caprine Version 2.5.0 (2.5.0.529)
Chrome Version 59.0.3071.115
macOS 10.12.5

**Comment by veniversum** [comment]
Hey, this should be fixed in the [latest release](https://github.com/sindresorhus/caprine/releases/tag/v2.6.0). Please update and check if the issue still occurs.

**Comment by benknight** [comment]
You're right, closing this as a duplicate of #258
