### ISSUE TITLE
Archiving doesn't work

### ISSUE THREAD

**Issue by yeastcapp** [sindresorhus/caprine#268]
The "Archive Conversation" button in this screenshot does not work
<img width="225" alt="screen shot 2017-08-03 at 11 11 04 am" src="https://user-images.githubusercontent.com/56014/28928904-84a4bcf4-783c-11e7-97f0-23926db03c9f.png">

---

Caprine 2.6.0
Electron 1.6.7
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
Duplicate of #228
