### ISSUE TITLE
Notifications do not work in High Sierra

### ISSUE THREAD

**Issue by richardrobinson0924** [sindresorhus/caprine#269]
No notification banners in Notification Centre appear for Caprine; the only indication of a notification is the app icon bounce.

Notifications are enabled both in System Preferences and Caprine Preferences.

**Comment by sindresorhus** [comment]
High Sierra is still in beta, and it's buggy. I'll take a look at this again when High Sierra is officially out.

**Comment by vanshg** [comment]
Any updates on this?

**Comment by onimaca** [comment]
Any updates on this?

**Comment by bpetrynski** [comment]
Problem seems to persist. Are there any updates on this issue?

**Comment by danhp** [comment]
No repro on 10.13.4
