### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by mrzl** [sindresorhus/caprine#27]
good day, i like this project. do you plan to introduce any kind of encryption, like OTR? https://otr.cypherpunks.ca/

i would still like to be able to send encrypted messages over facebook chat, and i'm wondering if this is in the thinking. 

thanks!

**Comment by sindresorhus** [comment]
I don't see how that would be possible as this app merely wraps messenger.com with a bunch of tweaks and integrations rather than talking directly to the protocol. Happy to hear your thoughts if I'm wrong, though.
