### ISSUE TITLE
No setting menu on Windows

### ISSUE THREAD

**Issue by dudeedud4** [sindresorhus/caprine#272]
As stated in the title, I see no settings in the Windows version. Sorry if this is a duplicate, I looked but didn't see any other issue.

http://i.imgur.com/qk54kSr.png

**Comment by daveseco7** [comment]
Hi, 
You are correct, by default on Windows the upper toolbar it's not visible, but you can toggle it on by pressing the **_ALT_** key.

This behaviour is also present in all Linux DE

#208

**Comment by sindresorhus** [comment]
It's also documented in the readme.
