### ISSUE TITLE
Group chat participant names are difficult to see in dark mode

### ISSUE THREAD

**Issue by jamiestraw** [sindresorhus/caprine#273]
<img width="253" alt="group-chat-dark-mode" src="https://user-images.githubusercontent.com/8133259/29214547-adebcc42-7e9f-11e7-83d1-c6638252c4cc.png">

**Comment by chabou** [comment]
I fixed this for Work Chat with https://github.com/sindresorhus/caprine/pull/251
It could be the same CSS class

**Comment by jamiestraw** [comment]
@chabou you're right, seems to be the same class - in that case the fix would be to simply move that style from `workchat.css` to `dark-mode.css`
