### ISSUE TITLE
GIF: consumes a lot of CPU

### ISSUE THREAD

**Issue by davidwessman** [sindresorhus/caprine#274]
When I have a channel open with a gif rendered, `Caprine` and `Caprine Helper` consumes all my CPU. It stops as soon as I switch channel or when I scroll until it is not visible.

Mac OS: 10.12.6
Caprine: 2.6.1.548

**Comment by sindresorhus** [comment]
Rendering GIFs takes a lot of CPU. It's a very inefficient format and Chrome is not very good at rendering it efficiently either. Might improve when we upgrade Electron. Not really much we can do about it here.

**Comment by davidwessman** [comment]
> Rendering GIFs takes a lot of CPU. It's a very inefficient format and Chrome is not very good at rendering it efficiently either. Might improve when we upgrade Electron. Not really much we can do about it here.

Okay, good to know - is there anyway to "pause" them when windows is not focused?

**Comment by bfred-it** [comment]
`img {visibility:hidden}` perhaps.

Also I think videos keep playing even if Caprine is hidden or minimized.

**Comment by veniversum** [comment]
> Okay, good to know - is there anyway to "pause" them when windows is not focused?

By default, rendering is paused on macOS if window is not visible, or minimized in other OS. The behavior is described in detail [here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#page-visibility).

**Comment by Etheryte** [comment]
One option would be to implement a solution similar to what the mobile client does - replace GIFs with static images and only show the original when the image is hovered.
