### ISSUE TITLE
Message search result arrows not visible in dark mode

### ISSUE THREAD

**Issue by jamiestraw** [sindresorhus/caprine#278]
When searching messages in dark mode, the next/previous result arrows aren't visible.

![light](https://user-images.githubusercontent.com/8133259/29373549-883f443c-82a6-11e7-94f9-b8b858b2aed3.png)

![dark](https://user-images.githubusercontent.com/8133259/29373546-85dc63aa-82a6-11e7-9109-665843c47de1.png)

**Comment by sindresorhus** [comment]
PR welcome. Just needs some styling tweaks in dark-mode.css
