### ISSUE TITLE
Progress indicator for file downloads

### ISSUE THREAD

**Issue by Ryanb58** [sindresorhus/caprine#28]
It appears that there is no progress indicator or action applied upon a user downloading a file shared via another user. I looked into forking this repository in order to add this feature, however time is currently scarce in my life.

This issue can also gage to see if anyone else would benefit/want from this feature.

**Comment by sindresorhus** [comment]
Not something I've missed, but I would merge a good pull request.

http://electron.atom.io/docs/v0.34.0/api/session/#event-39-will-download-39
