### ISSUE TITLE
Group Calling

### ISSUE THREAD

**Issue by Raymond-Su** [sindresorhus/caprine#280]
It seems that voice/video calls work for conversations with individual people. However, they do not seem to work in group conversations.  Nothing seems to happen when I select the people I wish to talk to and click "Call". 
<img width="403" alt="screen shot 2017-08-25 at 4 30 00 pm" src="https://user-images.githubusercontent.com/31336843/29702067-b48fd340-89b2-11e7-9e6a-cc2db966d12b.png">
When I receive a call from others I cannot join the call as well

---

Caprine 2.6.1
Electron 1.6.7
darwin x64 16.6.0

**Comment by sindresorhus** [comment]
I think we need to whitelist the window title. https://github.com/sindresorhus/caprine/blob/0dba77d0a9f895b63f9458b0d6ee4257e792b98b/index.js#L258
