### ISSUE TITLE
Dark Mode Name should be something other than black

### ISSUE THREAD

**Issue by carlowahlstedt** [sindresorhus/caprine#281]
See below that you can barely see the name in the message.

<img width="82" alt="screen shot 2017-08-25 at 10 55 02 am" src="https://user-images.githubusercontent.com/2687687/29719463-1f4efa46-8984-11e7-8f6b-c21d4754e72c.png">

**Comment by sindresorhus** [comment]
PR welcome. Just needs some styling tweaks in `dark-mode.css`.

**Comment by carlowahlstedt** [comment]
Pulled the project down and tried to run it, but getting the error below. Also [npm-debug.log.txt](https://github.com/sindresorhus/caprine/files/1255077/npm-debug.log.txt)

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! caprine@2.6.1 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the caprine@2.6.1 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the caprine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
```

Electron is not globally installed. Any ideas?

**Comment by chabou** [comment]
It seems fixed in master by https://github.com/sindresorhus/caprine/pull/277

**Comment by carlowahlstedt** [comment]
@chabou any idea how releases work? There an automated build, nightly build?

**Comment by sindresorhus** [comment]
New release is out https://github.com/sindresorhus/caprine/releases/tag/v2.6.2

**Comment by sindresorhus** [comment]
@carlowahlstedt Make sure you did `npm install` before trying `npm start`. Also try removing `node_modules` and reinstalling. If that's not it, try upgrading to latest Node.js and npm.

**Comment by carlowahlstedt** [comment]
@sindresorhus Ugh, looks like I didn't wait for electron to install 🤦🏼‍♂️...looked like it was hung the first time...sorry. Thanks.
