### ISSUE TITLE
Add AppStream metainfo file

### ISSUE THREAD

**Issue by probonopd** [sindresorhus/caprine#282]
Please consider adding an AppStream metainfo file, https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

This would allow app centers and directories like https://appimage.github.io/caprine/ to present the application with more relevant metadata, screenshots etc.

Please close this ticket _once_ a new release including an AppStream file is available for download, then I can include it in https://appimage.github.io.

Reference:
https://github.com/AppImage/appimage.github.io/issues/63

**Comment by sindresorhus** [comment]
Sure, when https://github.com/electron-userland/electron-builder/issues/1993 is resolved.

**Comment by sindresorhus** [comment]
Closing as it doesn't seem like electron-builder will fix it anytime soon and it doesn't make sense to have this issue being noise in the issue tracker.

**Comment by probonopd** [comment]
Wouldn't there be a way of just adding that single file without needing special electron-builder support, e.g., using `extraResources` or `extraFiles`?

https://github.com/electron-userland/electron-builder/wiki/Options
