### ISSUE TITLE
Notifications disappear in windows 10

### ISSUE THREAD

**Issue by sgdgp** [sindresorhus/caprine#285]
On enabling the desktop notifications, the messages show the notifications but they disappear automatically after 1-2 secs from the windows 10 notification pane.

Please make the notifications about the new messages persistent unless a user chooses to clear the notification from the sidebar (side notification panel in windows 10)

**Comment by gcsecsey** [comment]
This is unfortunately an Electron issue: https://github.com/electron/electron/issues/3916

The very same issue has been raised with Rambox, and some investigation was made: https://github.com/ramboxapp/community-edition/issues/479#issuecomment-446541939

**Comment by dusansimic** [comment]
Stale
