### ISSUE TITLE
"Add people" list isn't readable with dark mode

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/caprine#287]
The "add people" list in group chat isn't readable at all since it's white on white.

![screen shot 2017-09-12 at 7 14 52 pm](https://user-images.githubusercontent.com/6525926/30319350-ccab21b0-97ee-11e7-9eef-219ebac36003.png)

**Comment by chabou** [comment]
What I done for Workchat could work. Someone should test moving these CSS classes in darkmode.css:
https://github.com/sindresorhus/caprine/blob/e245df9edaa5605e1c2fb996f460c31433230d4c/workchat.css#L76-L87
