### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by felicianotech** [sindresorhus/caprine#289]
If the default viewing mode and "Dark Mode" could be turned into two proper themes, then we could have other people submit their own themes as well.

I know I'd volunteer to make a theme.

**Comment by sindresorhus** [comment]
It's a nice idea, but not going to happen. It's already too much work having the dark theme. If we controlled the HTML it would be easy, but for every change in messenger.com, we need to update the CSS selectors. messenger.com also has a *lot* of UI to style. It's just too much to create and maintain.
