### ISSUE TITLE
Is there any chance this could be converted to a mobile app?

### ISSUE THREAD

**Issue by andypotts** [sindresorhus/caprine#290]
Is there any chance this could work on mobile (Android)? At the moment Facebook forces you to use their mobile app which uses too much battery. This would be great as a lightweight alternative.

**Comment by tschuy** [comment]
You might also be interested in Facebook's Messenger Lite: https://www.theverge.com/2017/5/18/15659414/facebook-messenger-lite-how-to-install

**Comment by kevva** [comment]
Electron isn't supported on mobile devices currently. See https://github.com/electron/electron/issues/562 and https://github.com/gabrielcsapo/electron-mobile.

**Comment by andypotts** [comment]
@tschuy it's not available in the UK.

@kevva I understand Electron doesn't work on mobile devices, but it's written in Javascript. So I was wondering if it would be possible, and how much work would be required to make it compatible with mobile devices.

**Comment by tschuy** [comment]
You can download the apk from a third party like APK Mirror and the app will work fine. APK Mirror is run by Android Police, an Android news blog, and as of yet has been very reliable (the instructions to install it from APK Mirror are in that Verge article). I've personally done this with my device in the United States and it's worked just fine for me.

Regarding porting Caprine to mobile, Caprine wraps the existing Facebook Messenger website. There are certain CSS tricks that can be done to make it work better on mobile, but quickly you'd run into problems with things like notifications without running the app continuously in the background, which would drain battery life. It's doable, but honestly downloading the messenger lite from APK Mirror is probably your best bet.

**Comment by kevva** [comment]
@andypotts, until Electron is supported on mobile devices I don't think we're going to move forward with this. I'd go with @tschuy suggestion.

**Comment by andypotts** [comment]
@tschuy @kevva thanks 👍
