### ISSUE TITLE
Transparent titlebar in macOS High Sierra when using vibrancy

### ISSUE THREAD

**Issue by stpoa** [sindresorhus/caprine#295]
![screen shot 2017-09-28 at 09 26 43](https://user-images.githubusercontent.com/19593179/30954148-62528ebe-a42f-11e7-86e3-ddcbfda1aa9f.png)

**Comment by sindresorhus** [comment]
Known Electron issue: https://github.com/electron/electron/issues/10521

Related to https://github.com/sindresorhus/caprine/issues/260.

**Comment by sindresorhus** [comment]
I've done a new release with a temporary fix: https://github.com/sindresorhus/caprine/releases/tag/v2.7.0

**Comment by veics** [comment]
this issue is not gone :-/

**Comment by veics** [comment]
this issue is not gone, and it is reproduced in v2.7.1

**Comment by z-ax** [comment]
@sindresorhus I kinda like it now with this "temporary fix". Looks a lot like other messengers I have, so now it's consistent :)
Is it possible to have layout like this as an option in future?

**Comment by sindresorhus** [comment]
No, but it’s open source, so you can do what you want in a fork ;)

**Comment by tsujamin** [comment]
Is it possible to toggle the titleBarStyle window option based on whether transparency is enabled? Or would this require reloading the app

Personally I find the hidden titlebar of more appeal than transparency, and its a shame we can't have both until this is fixed upstream

**Comment by nahive** [comment]
It's closed on electron side - maybe updating electron version now that `1.8.2` is marked as release would fix that (and other issues)?

**Comment by sindresorhus** [comment]
Vibrancy mode is now enabled again and it seems to work fine.
