### ISSUE TITLE
Memory leakage on extended use

### ISSUE THREAD

**Issue by shurygij** [sindresorhus/caprine#296]
When you leave Caprine on for a long period of time it starts using up more and more RAM and gets very laggy.

![image](https://user-images.githubusercontent.com/22663625/31026848-bee0d94c-a4fc-11e7-838e-fd1a4bfcc453.png)

Easily fixable by application restart but still something to note.

**Comment by anthonyraymond** [comment]
CTRL + R or switching to another conversation should fix the issue.

I've also experienced this issue, i believe that it's because all received/sent messages are kept until you switch to another conversation (you can see that the scroll bar keep growing)

**Comment by anthonyraymond** [comment]
CTRL + R or switching to another conversation should fix the issue.

I've also experienced this issue, i believe that it's because all received/sent messages are kept until you switch to another conversation (you can see that the scroll bar keep growing)

**Comment by pedrosanta** [comment]
Yep, I was also experiencing this issue. Any idea why? Is this fixable?

**Comment by sindresorhus** [comment]
Not much we can do about this, unfortunately...

You could try reporting the it to https://github.com/electron/electron
