### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#3]
Need to find a good auto-updater that will just update the app in the background like Atom or Chrome. I don't want any UI for that. It should update when a new version is published on GitHub Releases.

Candidates:
- https://github.com/jenslind/electron-gh-releases
- https://github.com/evolvelabs/electron-updater
- http://electron.atom.io/docs/v0.32.0/api/auto-updater/ _(requires an actual server and is OS X only...)_

**Comment by Ryanb58** [comment]
I really like the simplicity of electron-gh-releases.

**Comment by andersfischernielsen** [comment]
I think the only hurdle in implementing `electron-gh-releases` is the need to build using `grunt-electron-installer` for Windows.

**Comment by sindresorhus** [comment]
@andersfischernielsen Could use https://github.com/unindented/electron-installer-windows

**Comment by andersfischernielsen** [comment]
What does your current release workflow look like for Caprine, @sindresorhus?
It kinda depends on that as I see it. 

If using `electron-gh-releases` really is as simple as adding a `.json` to the root of the repo, then it shouldn't change much workflow wise, unless there's a signing issue with the app for Windows.(It should be noted that I don't really care for Windows support).

**Comment by sindresorhus** [comment]
> What does your current release workflow look like for Caprine, @sindresorhus?

`$ npm run build` and then I manually upload the ZIP files to the release.

> It should be noted that I don't really care for Windows support

Me neither. That's why this hasn't been a priority. For OS X homebrew works fine.

**Comment by terinjokes** [comment]
I'd also like to get the ability to enable auto-updates. I just upgraded from 1.0.0 because I didn't know there was updates.

**Comment by emannxx** [comment]
For Windows, you should consider using the official Electron UWP app converter, this way you could publish the app on the Windows 10 store which would handle installs, updates and pretty much everything else for you. 
+ Info - http://electron.atom.io/docs/tutorial/windows-store-guide/

**Comment by akashnimare** [comment]
Any updates on this?

**Comment by sindresorhus** [comment]
Finally done in: https://github.com/sindresorhus/caprine/releases/tag/v2.0.0 :)
