### ISSUE TITLE
Top bar in High Sierra

### ISSUE THREAD

**Issue by fribmendes** [sindresorhus/caprine#301]
Every since I upgraded to High Sierra, the top bar has been showing like this:

<img width="802" alt="screen shot 2017-10-05 at 15 59 13" src="https://user-images.githubusercontent.com/4325027/31234305-79eeaeba-a9e6-11e7-9520-09d47dab7b0c.png">

Have already upgraded to 2.7.1 and the issue persists.

**Comment by yangbrian** [comment]
I believe this is the workaround for #295

**Comment by fribmendes** [comment]
Oh, I saw that issue. Since it doesn't describe what the temporary fix is, it seemed to me it was something related to vibrancy and transparency. Closing in favor of #295, then.
