### ISSUE TITLE
Titlebar is visible on macOS High Sierra

### ISSUE THREAD

**Issue by nahive** [sindresorhus/caprine#303]
I was able to replicate this on two separate machines running High Sierra.

![screen shot 2017-10-09 at 22 22 01](https://user-images.githubusercontent.com/2961723/31357022-80df8aca-ad40-11e7-85a7-0fc69eea7b12.png)

So far I haven't found a way to hide the titlebar (as it was used to).

**Comment by sindresorhus** [comment]
It's a workaround for https://github.com/sindresorhus/caprine/issues/295.

**Comment by nahive** [comment]
Oh sorry, didn't notice as I was searching for 'titlebar' in issues.

**Comment by sindresorhus** [comment]
> I'll keep this issue open for discovery reasons.

**Comment by sindresorhus** [comment]
This was fixed
