### ISSUE TITLE
Select device before making video call

### ISSUE THREAD

**Issue by chansirip** [sindresorhus/caprine#307]
Can we do that? I want to use iGlasses as my default device.

Thank you
Chansiri Meelaodee

---

Caprine 2.7.1
Electron 1.6.7
darwin x64 15.6.0

**Comment by sindresorhus** [comment]
You can change the device during a call, but there's no way to do it before, as far as I know. This is outside of our control.

<img width="472" alt="screen shot 2017-10-15 at 14 05 36" src="https://user-images.githubusercontent.com/170270/31582583-01b03828-b1b2-11e7-81f3-b21138c4627c.png">
