### ISSUE TITLE
Consider publishing to the Windows Store

### ISSUE THREAD

**Issue by nozzlegear** [sindresorhus/caprine#315]
Hey, I've been using Caprine for a long time on Windows and really enjoy it. It'd be nice to see it in the Windows Store where we could easily download it without looking up this GitHub repo and downloading the exe. 

This doesn't require many changes, just installing `electron-windows-store` and configuring the script/certs. [I've got this running in a fork already](https://github.com/nozzlegear/caprine/commit/29bc993a1afc158b700ef1b6955441a9fb941864) and haven't had any problems building the appx, but wanted to open an issue here to get your thoughts on this before submitting a pull request.

Some of the benefits you get from converting to an appx and publishing on the Windows Store:

- A more convenient install experience. It's easier (imo) to just press "Install App" in the store instead of finding this repo and downloading/installing the exe.
- A nicer uninstall experience. When uninstalling an exe you have to open the control pane first, then find the program in the list of all other programs and press uninstall. With an app you can just uninstall it straight from the start menu. Compare the install/uninstall process of an [exe](https://user-images.githubusercontent.com/2417276/32147251-3e8bda3a-bcb2-11e7-9563-9f1c9ee8fefb.gif) with an [appx](https://user-images.githubusercontent.com/2417276/32147160-890f67f4-bcb0-11e7-993b-3b9c25f19d1b.gif).
- Built-in update experience. 
- Windows Store apps are cleaned up after uninstall and don't leave behind data/registry tweaks like an exe might. 

Some downsides, to be fair:

- This requires building on a Windows machine with the Win10 SDK installed. 
- I'm not sure if this is still a requirement, but at one point a developer had to [fill out this form](https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge) before submitting an Electron app to the store.
- The Windows Store has a web API to help automate releases, but it [seems to require an Azure Active Directory integration](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services). 🙄

To be clear I'm not suggesting support for Xbox, HoloLens or the now dead Windows Phone; this is still an Electron app and won't run on those platforms anyway. This is solely about the convenience of installing the app from the Windows Store.

**Comment by sindresorhus** [comment]
I understand it would be nice, but the downsides are just too big and I care too little about Windows (just being honest). The current setup is very nice for me. I just push a Git tag and everything builds automatically, and auto-updates are handled for all platforms. I'm not really interested in complicating that.

**Comment by nozzlegear** [comment]
No problem, that's sort of what I was expecting anyway. With your permission though I'd be interested in releasing and maintaining this in my own fork, though I understand if you don't want that either.

**Comment by sindresorhus** [comment]
Sure. No problem at all. This is open source. The more people that get access to it, the better. I'm happy to link to it too if you can commit to keeping it up to date.

**Comment by nozzlegear** [comment]
Awesome, thanks! I'll work on getting it published and update here with a link when it's done.

**Comment by nozzlegear** [comment]
Just a small update in case anybody is following this, I'm still going through the process for getting approval to publish electron apps on the Windows Store.

**Comment by nozzlegear** [comment]
Caprine is now published on the Windows Store: [https://www.microsoft.com/en-us/store/p/caprine/9n2b1r51zf4v](https://www.microsoft.com/en-us/store/p/caprine/9n2b1r51zf4v) . I'm working on some sort of automated system to automatically pull changes from this repository and publish to the store, but for now it's pretty easy to do it by hand.

**Comment by CvX** [comment]
@nozzlegear Hi there! 🙂Any updates on that? Looks like a lot of people are stuck on 2.11.0 downloaded from the Windows Store.

**Comment by nozzlegear** [comment]
Sure! I haven't used Messenger much in a long while so I've fallen behind on the updates. I'll get the changes merged and published this week!

**Comment by CvX** [comment]
Awesome, thank you! 🚀😃

We should look into integrating Windows Store publishing into Travis CI to make the process completely frictionless. 🙂

**Comment by nozzlegear** [comment]
@CvX I've actually unpublished the app from the Windows Store this morning, at the request of @sindresorhus. 

Sorry to everyone who's been using it, I simply haven't had the time to keep up with upstream changes and never found a great way to automate publishing to the Windows Store. If anyone wants to try their hand at it, check out the [appx.ps1](https://github.com/nozzlegear/caprine/blob/14c36db6dbc041f907b6834421cc712374ef7ba5/build/appx.ps1) file in my fork of Caprine, it should have enough info to get you started.
