### ISSUE TITLE
Notifications don't show up in the Notification Center on macOS

### ISSUE THREAD

**Issue by wojciechbielecki** [sindresorhus/caprine#317]
When a new message notification appears, it can't be found in the Notification Center after it disappears from the screen. Interestingly, when I had Do Not Disturb turned on, the notifications could be seen in the notification center, however they disappeared when I turned Do Not Disturb off. 
I'm currently on the newest version of High Sierra, but I remember this issue occurred in Sierra, too.
I checked my notification settings in System Preferences and I have the same settings for Caprine (including checked 'Show in Notification Center') as for other apps, whose notifications are remaining in the Notification Center. 

---

macOS High Sierra 10.13.1
Caprine 2.7.1
Electron 1.6.7
darwin x64 17.2.0

**Comment by parthradia** [comment]
Same issue here ... is this by design?

**Comment by lucastan96** [comment]
I was also wondering about this.. Is it possible to let messages stay in the notification center?
