### ISSUE TITLE
Call chatwindow in i3wm

### ISSUE THREAD

**Issue by remembertoremind** [sindresorhus/caprine#322]
Hi :) I would like to be able to call the chatwindow in i3wm - Is there any command to call/toggle the chatwindow? Similar to clicking the icon in the tray.

If Caprine is running and i give the command "caprine" in a terminal I get "Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged." in my terminal and "A JaveScript error occurred in the main process" in a separate window

Thanks :)

**Comment by andrewjong** [comment]
I get a similar error "JavaScript error occurred in the main process." This is what mine looks like. I am using i3wm on Manjaro Linux.

![2017-11-18-134313_537x418_scrot](https://user-images.githubusercontent.com/8121216/32985064-9d8ed492-cc66-11e7-8427-1030e0a8c17f.png)

**Comment by dusansimic** [comment]
This issue (the js error) was resolved. You should be able to run caprine and if it's already started it will just open the running window.
