### ISSUE TITLE
Media Constraints not met

### ISSUE THREAD

**Issue by chansirip** [sindresorhus/caprine#324]
An Error occured when trying to get access to Microphone. Media Constraints not met. but everthing is fine when I using Messenger on Chrome.

I tried to remove all preferences by App Cleaner, but it didn't help.

---

Caprine 2.7.1
Electron 1.6.7
darwin x64 15.6.0

**Comment by bappiislam** [comment]
i am suffering same problem when using facebook messenger group call, but one to one call in messenger are okey, whats the solution ???
thanks in advanced

**Comment by Ooiyenchun** [comment]
I have the same issue with bappiislam too

**Comment by lhee0209** [comment]
same on me too please help

**Comment by lapispencil** [comment]
I have the same issue when using messenger on chrome on PC. But works fine on messenger app on phone. Any updates on this?

**Comment by opalwave** [comment]
I am having the same problem also.

**Comment by mc7-sys** [comment]
sameeee oonnnn me
