### ISSUE TITLE
--minimize not giving expected behavior on macos

### ISSUE THREAD

**Issue by tigersoul925** [sindresorhus/caprine#327]
Hi,

The --minimize flag isn't getting expected behavior on macOS. The window does get minimized but on mac there's a dock and thus launching minimized usually means just starting the app without popping up any window since the app icon is available in the dock. Actually minimizing windows is rare and certainly when launching an app.

**Comment by sindresorhus** [comment]
The `--minimize` flag was not meant to be used on macOS. It was also just removed in #314. For macOS, https://github.com/sindresorhus/caprine/pull/231 will be the solution or checking the "Hide" checkbox in the "Login Items" system preferences.

**Comment by tigersoul925** [comment]
Checking the hide button does not make the app hide on launch I'm afraid, that was the first thing I tried.
