### ISSUE TITLE
Lack of notifications on Windows 10 Pro

### ISSUE THREAD

**Issue by MrRafalSzymanski** [sindresorhus/caprine#329]
Although I have all notifications related settings enabled in both Windows and Caprine there are no notification pop-ups at all. They do work on Windows 7 machine but no matter what I do or change I cannot get them on Windows 10.

I can hear the message sound though 

![Settings](https://i.imgur.com/71ERbiT.png)

![Settings -> Caprine](https://i.imgur.com/khELdzS.png)

![Caprine](https://i.imgur.com/zfV9SG9.png)

---

Caprine 2.7.1
Electron 1.6.7
win32 x64 10.0.14393

**Comment by dusansimic** [comment]
This issue is stale and currently notifications don't exist anyway on new design.
