### ISSUE TITLE
Close button overlays message request back button

### ISSUE THREAD

**Issue by vrunoa** [sindresorhus/caprine#33]
Hey @sindresorhus I got a message request on Caprine and the back button gets under the window close button, although it's clickable. Just wanna give feedback on this. 
![screen shot 2015-11-23 at 11 21 14 am](https://cloud.githubusercontent.com/assets/329957/11347033/8aac1106-91d4-11e5-88ce-7e1c24cb4fa1.png)

**Comment by sindresorhus** [comment]
Thanks for the report. I don't have time to look into this now, but a pull request would be welcome. Should be easy to just add a `browser.css` CSS override for it, moving the button to the right so it's not obstructed by the native buttons.

**Comment by vrunoa** [comment]
ok @sindresorhus , i'll take a look and create a PR with the fix.
