### ISSUE TITLE
Keyboard shortcut (Alt+Shift) overlap

### ISSUE THREAD

**Issue by thagorastos** [sindresorhus/caprine#332]
If you have your system change the keyboard layout with Alt+Shift, when in Caprine, the application menu also opens up and you have to hit Esc or click the composer with the mouse to close the menu and start typing.

---

Caprine 2.7.1
Electron 1.6.7
linux x64 4.10.0-40-generic

**Comment by sindresorhus** [comment]
What application menu? Caprine doesn't register any shortcut for Alt+Shift.

**Comment by IOAyman** [comment]
I do confirm this issue as well.

**Comment by Silverbullet069** [comment]
Are there any progress? I'm having the same problem
