### ISSUE TITLE
Toggle vibrancy during run, does not set vibrancy for next start of Caprine

### ISSUE THREAD

**Issue by yangwao** [sindresorhus/caprine#338]
```
uname -a
Darwin undefined 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```
To reproduce: Run Caprine, have dark mode, toggle Vibrancy, quit Caprine. Open Caprine again and Vibrancy is gone.

Also I would like add super dark/black mode, would be PR accepted?

**Comment by sindresorhus** [comment]
> Also I would like add super dark/black mode

What would be the difference? It's a lot of work to maintain a new theme and I'm the only activate maintainer here, so I'm not interested in taking on more work.

**Comment by yangwao** [comment]
Actual dark mode is more like dark blue, not dark black.
It's fine OSS, so anyone can fork it and keep maintenance on other fork.

To be ontopic, any tip where this vibrancy bug occurs? It's not saving this setting in localstorage?

**Comment by CvX** [comment]
I believe this has been fixed a while back. Closing.
