### ISSUE TITLE
Python markdown highlighting issue

### ISSUE THREAD

**Issue by AllanLRH** [sindresorhus/caprine#340]
Highlighting fails for raw strings – notice that highlighting of the string `char_pool`:

<img width="586" alt="screen shot 2017-12-17 at 12 00 31" src="https://user-images.githubusercontent.com/2641327/34078857-47db94a4-e322-11e7-8431-15c187146ee6.png">

It's rendered from:

    ```python
    #!/usr/bin/env python
    # -*- coding: utf8 -*-

    import random
    import sys
    try:
        import pyperclip
        clipboard = True
    except ImportError:
        clipboard = False


    if len(sys.argv) == 1:
        pw_len = 35
    elif len(sys.argv) == 2 and sys.argv[1].isdigit():
        pw_len = sys.argv[1]
    else:
        print("Wrong arguments, exiting.", file=sys.stderr)
        sys.exit(1)

    char_pool = R'''0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_{}'''
    pwd = ''.join([random.choice(char_pool) for _ in range(pw_len)])

    if clipboard:
        pyperclip.copy(pwd)
        print("The new password are placed in the clipboard.")
    else:
        print(pwd)
    ```

A possible fix might be to do the highlighting with [MagicPython](https://github.com/MagicStack/MagicPython#strings)?

**Comment by sindresorhus** [comment]
Caprine is not doing the highlighting. It's just overriding the theme to make it look better: https://github.com/sindresorhus/caprine/blob/100a437ed8ab294384d200d49b303a387aaf51b0/browser.css#L162-L209

**Comment by AllanLRH** [comment]
Allright, closing.
