### ISSUE TITLE
No binary package for v2.9.0

### ISSUE THREAD

**Issue by PeterDaveHello** [sindresorhus/caprine#341]
Just noticed that v2.9.0 was tagged for about 1 day but looks like there is still no binary package.

@sindresorhus is there anything I can help? Many thanks!

**Comment by sindresorhus** [comment]
I feel asleep before Travis finished building them, so they were just there as a draft. It's out now.

**Comment by PeterDaveHello** [comment]
https://github.com/caskroom/homebrew-cask/pull/42075
