### ISSUE TITLE
Important feature is missing: How to read Requested messages? 

### ISSUE THREAD

**Issue by jhjaweuqioiqtasdgjhlagaeyuiab** [sindresorhus/caprine#343]
Hi there, Today I found this app is missing a really important feature that we can not get new messages from stranger (requested messages from people who are not in the friend list). I think this should be added soon.
Thanks for your time!

**Comment by Rezonansowy** [comment]
Confirmed, this is really important.

**Comment by Rezonansowy** [comment]
I referenced it here: #352

**Comment by Rezonansowy** [comment]
#352

**Comment by CvX** [comment]
“Show Message Requests” has been added to app’s menu a while back! 🎉 Closing!
