### ISSUE TITLE
Create a donate menu entry and a project donate page

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#345]
We should create a donate menu entry in the Caprine app and set up a project donate page. It would be nice to have an opportunity to donate to this fantastic project. We need software like this ;) Let's consider PayPal, Bitcoin, Litecoin, etc.

Here's the example from KeePass app:
![](https://raw.githubusercontent.com/dlech/Keebuntu/master/doc/images/ubuntu-app-menu-screenshot.png)

**EDIT**: The current Caprine menu is as follows:
<img width="371" alt="current menu state" src="https://user-images.githubusercontent.com/6929363/34419856-38232be8-ebd4-11e7-9597-19f0541bc3ce.png">

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/caprine/commit/bc78d71ed7219f9bff52996110c84954782c061b
