### ISSUE TITLE
Implement an in-app auto-updater

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#347]
Would be very handy to have an in-app auto-updater which can check online for the newest release of caprine and perform an update. There should be a setting called ''Enable auto update'' or something similar, so the user can decide whether to use it or not.

Something similar is implemented in Atom Editor:
![](https://discourse-cdn-sjc1.com/business/uploads/github_atom/425/0379459cd3807327.png)

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
Caprine already has an auto-updater built-in (Mentioned in the readme). It's just silent and makes sure everyone is always on the latest version. I'm not intersted in adding a setting for that. It just works like Chrome.

**Comment by Rezonansowy** [comment]
@sindresorhus OK, good to know. THen it didn't work in the past version of Caprine so I had to upgrade it manually. That's why I filed this ticked but it seems to be fixed now (in the current version).
