### ISSUE TITLE
Create a brew/macports and AppStore distribution channels

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#349]
Hi Sindre! Some your apps like [Battery Indicator](https://sindresorhus.com/battery-indicator) are accessible on Apple App Store, others like [Touch Bar Simulator](https://github.com/sindresorhus/touch-bar-simulator) are available via package managers like [Homebrew](https://brew.sh).

It would be nice to have some extra distribution channel as it'll help with the accessibility of the app and to spread its popularity too!

Another important advantage is that it can also act as a way to update the app, instead of/alongside with implementing a built-in updater.

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
It's already available on Homebrew Cask. I've tried to submit it to the App Store, but couldn't build it properly. Closing in favor of #88.
