### ISSUE TITLE
Window buttons overlap with the settings button

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/caprine#35]
<img width="176" alt="screenshot 2015-12-01 17 38 27" src="https://cloud.githubusercontent.com/assets/471278/11507039/76866f76-9852-11e5-870a-b54ef27a8a6b.png">

**Comment by sindresorhus** [comment]
Are you using the latest version? This was fixed.

**Comment by silvenon** [comment]
Oh, I had 0.2.0, I thought it magically auto-updates. How should we update it?

**Comment by sindresorhus** [comment]
Same way you installed it. I haven't had the time to implement auto-update yet.

**Comment by silvenon** [comment]
I had to reinstall it (delete + install). I guess it's a cask issue.
