### ISSUE TITLE
Compact mode doesn't work with the right sidebar

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#350]
When you resize the Caprine window to a smaller size, it should present appearance as follows:
![](https://github.com/sindresorhus/caprine/raw/master/media/screenshot-compact.png)

The problem is that the right sidebar is still showing, which breaks the layout making the whole GUI hard to use.

Here's the current problem screenshot:
![sidebar layout problem](https://user-images.githubusercontent.com/6929363/34421734-0809cb0a-ebdf-11e7-9ff2-58b9813ab197.png)

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
Yes, it should automatically hide the right-sidebar when the window is too small to show it.
