### ISSUE TITLE
Implement a mini shuffle mode

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#351]
We already have a concept of a compact mode in Caprine. It looks like this:
![](https://github.com/sindresorhus/caprine/raw/master/media/screenshot-compact.png)

But when the app window is even more sized down, it would be nice to hide the left sidebar as well. It can be called a _shuffle mode_ for example. And could look like this:
<img width="769" alt="shuffle mode 2" src="https://user-images.githubusercontent.com/6929363/34421996-b972b360-ebe0-11e7-8a08-a1b317f2f194.png">

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
You can already do this with "View" => "Toggle Sidebar".

**Comment by Rezonansowy** [comment]
@sindresorhus That's right but it should happen automatically as a part of the compact mode. When the user sizes down the app window more that in the firsdt image, not only right sidebar but also the left one should hide.

**Comment by sindresorhus** [comment]
We made it an explicit action as users might be confused how to change conversation if the sidebar is suddenly gone.

**Comment by Rezonansowy** [comment]
I see. I think if users notice that sidebar hides when they make the app window smaller, they will for sure see the connection between these two actions, so they shouldn't be confused. The second argument is that users are familiar with a responsive design which is present of most of the websites today. Hiding the left sidebar should be available only when the app window is really small. I mean the window width which is less than the current minimum window width.

The implementation will allow scaling down the window even more (width=300px) to have only the little conversation window. Keeping the left sidebar in such small window would break the layout of the conversation pane.
