### ISSUE TITLE
Missing Messenger menu in Caprine

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#352]
A menu which allows user view Archived Threads, Unread Threads, Active Contacts and Connection Requests is missing. It looks like this on Messenger website:
<img width="317" alt="missing menu" src="https://user-images.githubusercontent.com/6929363/34422076-3154f942-ebe1-11e7-8feb-1e0c28e126f4.png">

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
It's intentionally hidden. What we should do is to add those to the native app "View" menu.

**Comment by CvX** [comment]
Most of those eventually made it to the menu. Do we need to add any more?

**Comment by mquevill** [comment]
The only options shown there that still don't exist are Privacy Policy and Cookie Policy. While I could see some benefit of including them in Caprine, I don't think they're necessary.

**Comment by yatharth** [comment]
Agreed with @mquevill that all the important actions have made it to the menu; imo issue can be closed!
