### ISSUE TITLE
Feature request: Draft messages & Trash

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#353]
It would be awesome to have in Caprine something like Draft messages and Trash.
This could be done with HTML5 local storage or similar technology.

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
When you delete a message, you decide whether to delete it forever or archive it. That's an alternative to what you propose, but solves the same use-cases. You can find archived messages by just going to a specific contact.

**Comment by Rezonansowy** [comment]
@sindresorhus I'm not sure I understand your point. What do you mean by archiving single messages? Maybe I wasn't enough specific because I don't mean deleting or archiving whole conversations but single messages. I mean this:
<img width="254" alt="delete single message" src="https://user-images.githubusercontent.com/6929363/34438461-1ad2c5ca-ec75-11e7-84cb-71d93f344f52.png">

**Comment by Rezonansowy** [comment]
This is a feature request as many messaging apps form 21st century have this out-of-the-box and FB Messenger is missing this by default. Many users would appreciate this, including me. IMO having a way to restore things you delete is important in today's computing.

**Comment by sindresorhus** [comment]
I see. I still not don't think it's useful enough to spend time on and maintain though, sorry. It's just not something I would ever use. If I delete a single message, I do it for a reason.

**Comment by Rezonansowy** [comment]
Maintaining is a reasonable thing so I see your point. But please note that many users are different than you, they sometimes delete a message because they want to hide it from eyes of other chat participants but does it mean they want to hide it to themselves as well? Having a visual log would be very useful to see what messages you deleted from the others, so you can have access to a reason why you deleted them. It acts "like a trash" only because it's without the restore function, which is impossible to implement with Messenger.

**Comment by Rezonansowy** [comment]
I changed the title because Trash was misleading. It's not a Trash in terms of present computing.
