### ISSUE TITLE
Optionally hide feature buttons (pictures, emojis, gifs, etc)

### ISSUE THREAD

**Issue by hhsnopek** [sindresorhus/caprine#355]
The Messenger Lite App removes these icons along the bottom of the app. It would be great to have the ability to optionally remove them. Or add a mode that replaces all of them with one "send" icon.

![screen shot 2018-01-01 at 12 17 17 pm](https://user-images.githubusercontent.com/2363940/34469483-f9a40d5c-eeed-11e7-8b31-6bbdb386edd4.png)

**Comment by sindresorhus** [comment]
I don't think they should be removed completely as you sometimes want them, but I agree that usually, they're just noise. Maybe one button that expands them.

**Comment by hhsnopek** [comment]
Thank you @dusansimic 🙌
