### ISSUE TITLE
Why don't you use mainWindow.hide() instead of mainWindow.minimize()?

### ISSUE THREAD

**Issue by KSXGitHub** [sindresorhus/caprine#359]
I checked `Launch Minimized` (in Files menu) to be able to launch Caprine in background. The thing is that Caprine window blinks (it appears and then disappears). This won't be a problem with `mainWindow.hide()`

**Comment by sindresorhus** [comment]
I don't know, to be honest. Probably an oversight. It was added here: https://github.com/sindresorhus/caprine/commit/a7a388662f05881b839e844c61a3b9bc02e8a7c1

**Comment by KSXGitHub** [comment]
Why don't you change it to `mainWindow.hide()`?

I cloned this repo, changed and built it myself, window no longer blink.
