### ISSUE TITLE
Plans do not use the correct font color in dark mode

### ISSUE THREAD

**Issue by skaematik** [sindresorhus/caprine#360]
<img width="313" alt="pasted_image_7_1_18__2_19_pm" src="https://user-images.githubusercontent.com/10680719/34646195-0c7860dc-f3b6-11e7-855d-6e9a85cfccad.png">

It should say:
"Sun Jan 7 at 4 PM 
You and {name removed} will
also be reminded 1 hour before"

**Comment by dusansimic** [comment]
Fixed with https://github.com/sindresorhus/caprine/pull/361. This issue can be closed.
