### ISSUE TITLE
Top Navigation bar showing up as grey. Is this normal? All images show there being now widow nav bar at all

### ISSUE THREAD

**Issue by elvinos** [sindresorhus/caprine#362]
<img width="876" alt="screenshot" src="https://user-images.githubusercontent.com/10270600/34676142-c648b32c-f483-11e7-9944-a79ec1d1aa0e.png">

**Comment by sindresorhus** [comment]
I had to disable the custom navbar because of Electron + High Sierra bug: https://github.com/sindresorhus/caprine/issues/295

**Comment by tsujamin** [comment]
Goofy gets around this on High Sierra somehow, I'm not sure if it's an electron version issue though

**Comment by mrpinkcat** [comment]
Hi @sindresorhus ! The issue [electron/electron#10521](https://github.com/electron/electron/issues/10521) seem to be fixed. It is possible to restore the design of your screenshot ?

**Comment by sindresorhus** [comment]
@mrpinkcat It's still broken, just in a different way, see: https://github.com/sindresorhus/caprine/pull/399

**Comment by sindresorhus** [comment]
Vote up this issue instead: https://github.com/electron/electron/issues/10886 Or better yet, someone submit a PR.

**Comment by hroland** [comment]
Any updates?
