### ISSUE TITLE
Toggling Themes on Linux Mint 18.1

### ISSUE THREAD

**Issue by Arkasian** [sindresorhus/caprine#365]
Toggling themes using hotkey: Ctrl+D is not working for Linux Mint 18.1.

**Comment by tamasviktor** [comment]
Not working on Windows 10 too.

**Comment by mquevill** [comment]
A variation of this issue still exists for me in v2.38.0 on Linux Mint 19.2.

Actually, it does work as long as I've clicked on the side bar (but not on a user's profile picture) or on the top info bar (where it shows the current message title). If the last place I've clicked is in the message itself or on the menubar, the shortcut does not work, even though the window is still active.

**Comment by dusansimic** [comment]
This seems to work in the latest release. If the problem still exists, please ping me in the comment.
