### ISSUE TITLE
Title bar not inline like in screenshots

### ISSUE THREAD

**Issue by ollypolly** [sindresorhus/caprine#373]
<img width="739" alt="screen shot 2018-01-20 at 01 20 10" src="https://user-images.githubusercontent.com/24544400/35178372-19d9b0c2-fd80-11e7-862e-2a4abe65c200.png">
Compared to:
<img width="739" src="https://sindresorhus.com/caprine/images/screenshot-dark.png" />

Macbook Pro Early 2013 High Sierra 10.13.2

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/caprine/issues/362. I'll keep this issue open for discovery.
