### ISSUE TITLE
Compile a second Caprine

### ISSUE THREAD

**Issue by raphaelc2009** [sindresorhus/caprine#379]
Hi,
Is it possible (on macOS High Sierra) to compile a second instance of Caprine with a different icon separate from the first one for use with a second account ?
Thanks!

**Comment by sindresorhus** [comment]
Yes, but you'll need to do it yourself. You need to make sure the [`appId`](https://github.com/sindresorhus/caprine/blob/master/package.json#L48) is different between the apps and you can change the icon here: https://github.com/sindresorhus/caprine/tree/master/static
