### ISSUE TITLE
Cannot update from 2.7.1 on macOS

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#380]
Version 2.7.1 cannot be auto-updated to 2.9.0, at least on macOS. The following error appears in  ~/Library/Logs/Caprine/log.log
```
[2018-01-29 10:44:14.721] [info] Checking for update
[2018-01-29 10:44:16.130] [error] Error: Error: Cannot find latest-mac.json in the latest release artifacts (https://github.com/sindresorhus/caprine/releases/download/v2.9.0/latest-mac.json): HttpError: 404 Not Found
"method: undefined url: https://github.com/sindresorhus/caprine/releases/download/v2.9.0/latest-mac.json\n\n    Please double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404
```

**Comment by sindresorhus** [comment]
@develar It seems electron-builder changed from `.json` to `.yml` for the macOS update file. Shouldn't it try both, at least for some versions, so users are able to upgrade?

**Comment by develar** [comment]
`latest-mac.json` is generated by electron-builder. But I don't see this file in the artifacts — https://github.com/sindresorhus/caprine/releases/tag/v2.9.0

@sindresorhus Reason is that you set `"electronUpdaterCompatibility": ">=2.18.2"` Obviously, it means that old users cannot upgrade. Please remove it.

**Comment by sindresorhus** [comment]
> Reason is that you set "electronUpdaterCompatibility": ">=2.18.2" Obviously, it means that old users cannot upgrade.

That was not obvious to me.

**Comment by sindresorhus** [comment]
I've manually added the required JSON file to the latest release so people will be automatically upgraded again.
