### ISSUE TITLE
Videos are not responsive and the view isn't scrollable

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/caprine#388]
<img width="447" alt="video" src="https://user-images.githubusercontent.com/1402241/35930188-da60b8a8-0c63-11e8-9927-9d84d4170a67.png">

Result is a Facebook video that is clipped and the right-side controls can't be accessed

**Comment by dusansimic** [comment]
This issue has been fixed with https://github.com/sindresorhus/caprine/pull/382 so it can be closed. There is no version with this fix yet so you'll have to wait for next release or build Caprine yourself.

**Comment by bfred-it** [comment]
Thank you!
