### ISSUE TITLE
Preferences menu item is not working on macOS when logged out

### ISSUE THREAD

**Issue by danielhusar** [sindresorhus/caprine#40]
Latest app and OSX El Capitan 10.11.2

<img width="331" alt="screen shot 2016-01-06 at 18 51 18" src="https://cloud.githubusercontent.com/assets/1857751/12151347/9e65bac2-b4a6-11e5-8cb0-9dc8a24cd3b8.png">

**Comment by sindresorhus** [comment]
I'm on that exact same setup and works fine for me.

**Comment by danielhusar** [comment]
Aye, it just doesn't work if you are logged off.

**Comment by sindresorhus** [comment]
Ok, should probably be disabled when logged out. Unfortunately there's currently no way to dynamically modify menu items. https://github.com/atom/electron/issues/2934
