### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by raphaelc2009** [sindresorhus/caprine#402]
Hi the sign in page never loards
Tested it with v2.8 and 2.9 on windows
Tested on macOS with 2.9 dmg and with git compilation
Still blank or forever spinning circule at lauch.
I even tried different ISP, VPNS...
Also brew cask install caprine doesn't install caprien on mac.
Any idea why ?

**Comment by drkovac3** [comment]
I am having the same issue and I am on El Capitan 10.11.4

**Comment by raphaelc2009** [comment]
Yeah I am on High Sierra on Mac and Win 10 Pro on PC

**Comment by raphaelc2009** [comment]
Accessing the messenger.com website from Chrome does the same thing unless already connected to Facebook.

**Comment by drkovac3** [comment]
Try this one.  It worked immediately for me https://github.com/danielbuechele/goofy/releases

**Comment by raphaelc2009** [comment]
@drkovac3 will try Thanks!

**Comment by raphaelc2009** [comment]
Iwas able to get in to work by recompiling and changing messenger.com/login for legin.messenger.com in index.js

**Comment by raphaelc2009** [comment]
Also little snitch was blovking the connection

**Comment by raphaelc2009** [comment]
Compied with these chages on windows too. Works flawlessy

**Comment by proactivematter** [comment]
Same, can't login as of recently. Tried deleting Caprine from Application Support, but the issue persists.

**Comment by dusansimic** [comment]
AFAIK this is fixed. For those who still have this issue, please update to the latest version of Caprine if you haven't already.
