### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by chreriksen** [sindresorhus/caprine#404]
Great work with the app. Would love for the option of checking for updates automatically to stay on the current releases.

**Comment by sindresorhus** [comment]
From the readme:

> Silent auto-updates

There's nothing you need to do. It updates silently in the background.

**Comment by sammarcus** [comment]
@sindresorhus I've been running 2.9.0 on macOS 10.13.3 and it hasn't updated to 2.10.0. I could manually download the latest release but how else can I troubleshoot why the self updating is not working?

Thank you!

**Comment by sammarcus** [comment]
Whoops, forgot to mention this was originally downloaded via dmg, not brew.
