### ISSUE TITLE
[Feature Request] Return Key Starts New Line

### ISSUE THREAD

**Issue by skymakai** [sindresorhus/caprine#409]
Feature request to change behavior of Return/Enter key.  As is, the Return key activates the message Send action; creating a new line requires using the Alt/Option key.

**Comment by humanfactors** [comment]
This is just the default for Facebook messenger. Try pushing shift delete like all other applications. This issue should be closed as this would be a terrible usability change that would drive most users crazy.

**Comment by qm3ster** [comment]
@humanfactors it can(must) be configurable, or even context-aware like in gitter.

**Comment by skymakai** [comment]
@humanfactors 
>Shift+Delete
Haha.

**Comment by dusansimic** [comment]
The default behavior for almost every messaging app is that `Return` key sends a message and `Shift+Return` starts a new line. This shouldn't change.
