### ISSUE TITLE
Use retina assets on HiDPI screens

### ISSUE THREAD

**Issue by oskarkrawczyk** [sindresorhus/caprine#41]
Unfortunately on retina screens the assets are really blurry.

<img width="355" alt="screen shot 2016-01-07 at 16 58 53" src="https://cloud.githubusercontent.com/assets/34213/12174991/096a76dc-b560-11e5-9d46-8030dd5835c2.png">

**Comment by kevva** [comment]
Those icons comes from Messenger itself.

**Comment by oskarkrawczyk** [comment]
Yes I know.

Anyway, seems like turning Caprine off and on, makes the webview load retina assets.
