### ISSUE TITLE
Can't click and drag windows in macOS

### ISSUE THREAD

**Issue by carlowahlstedt** [sindresorhus/caprine#410]
Version: 2.10.0.676

I can't drag the window around. I try click and drag, as well as three finger drag. Everything else seems to work. Resizing, clicking on various menu options, etc.

**Comment by MikeASchneider** [comment]
Been having this issue as well, it started on Monday. One workaround I've found is that you can use resizing to move the window, just pull the left side leftwards and then pull the right side leftwards as well, or vice versa.

**Comment by calvinmm** [comment]
I am seeing this behavior on version 2.9.0.630.

**Comment by devkinetic** [comment]
I've noticed this especially if I hide the sidebar. The window cannot be moved. The only clickable area for dragging is the top of the sidebar window.

**Comment by sporkman** [comment]
Still see this, current version is 2.10.0.676.

The only way to move it is to basically grab from the corners and "resize" it into place.

**Comment by stevenvo** [comment]
Hey team, this issue still persists today May 13th, any plan to fix?
