### ISSUE TITLE
Package for NixOS please

### ISSUE THREAD

**Issue by coretemp** [sindresorhus/caprine#411]
There is a current package in NixOS, but it just wraps the debian package. I will likely never run a binary from an untrusted source on my system. So, it would be great if you could package this in https://github.com/NixOS/nixpkgs. 
The previous project was packaged at `pkgs/applications/networking/instant-messengers/messenger-for-desktop/default.nix`, but again that's not what I am interested in. 

It might be that you need to fix your build system such that it builds more easily on more operating systems, etc.

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/electron-userland/electron-builder about adding support for NixOS, and I'll enable it when it's supported in `electron-builder`.

**Comment by ivegotasthma** [comment]
What's the status on this?

**Comment by sindresorhus** [comment]
Closing as I don't see this being implemented in electron-builder anytime soon. PR welcome for support when it's implemented in electron-builder.
