### ISSUE TITLE
[Feature Request] WhatsApp tab

### ISSUE THREAD

**Issue by Sadi58** [sindresorhus/caprine#415]
Thanks a lot for this great utility.
I wonder if this could be enhanced without too much effort to have a tabbed window containing WhatsApp Messenger as well as Facebook Messenger, perhaps by combining two projects into one (see https://github.com/Enrico204/Whatsapp-Desktop), which could also mean more efficient use of computer resources...

**Comment by sindresorhus** [comment]
That's way outside the scope of this app. You should check out https://meetfranz.com
