### ISSUE TITLE
App icon problem in Linux

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#416]
I have a problem with icon i Ubuntu 17.10. The icon is default application icon (not electron icon) but when Caprine is opened it has separate indicator from the pinned one but this indicator HAS an icon tho it is larger size.
![image](https://user-images.githubusercontent.com/12685466/37865283-d13eb132-2f7a-11e8-846a-1549635e11b0.png)
The fourth icon from top is pinned Caprine and the last icon is opened Caprine window indicator. The last icon clearly has higher resolution and it looks ugly.
I haven't tried on any other distro tho.

By the way I've been building Caprine myself lately and this has appeared somewhere around commit that updated `build`  directory structure (https://github.com/sindresorhus/caprine/commit/065aa47ed191f2d251a134b8947b7d7131d41d8f).

- Electron version: 1.7.10
- OS: Ubuntu 17.10

**Comment by ErikEklund** [comment]
Same on Mint 18.3 and Docky, it uses the default icon. No unread badges visible either (not sure if this is supported on Docky, but if not it would be a great addition). Screenshot attached.

![screenshot from 2018-04-09 08-32-29](https://user-images.githubusercontent.com/1064329/38482698-a8386f14-3bd0-11e8-8902-c27dc1eb9a30.png)

**Comment by sindresorhus** [comment]
@ErikEklund Maybe related to https://github.com/electron-userland/electron-builder/issues/2577

**Comment by Yan-Solo** [comment]
Any update on this?

**Comment by michaelarnauts** [comment]
The unofficial Microsoft Teams electron wrapper has no problem with this and the code should be quite similar i suppose: https://github.com/ivelkov/teams-for-linux

**Comment by dusansimic** [comment]
Well the solution to the problem is simple. Add `icons` folder in `build` that contains icons of different sizes like in [ivelkov/teams-for-linux](https://github.com/ivelkov/teams-for-linux). This would be just a temporary solution until this issue is fixed in electron-builder! Any thoughts about adding this @sindresorhus? I can do a PR for this.

Note: This is a fix for Linux only since this issue appears only on Linux.

**Comment by sindresorhus** [comment]
I've done the recommended workaround in [2.13.0](https://github.com/sindresorhus/caprine/releases/tag/v2.13.0).

**Comment by dusansimic** [comment]
Thanks!

**Comment by sindresorhus** [comment]
Keeping this open so I remember to revert it when it’s fixed in electron-builder.

**Comment by michaelarnauts** [comment]
The workaround made sure that the icon was there, but it's not linked to the `.desktop` file, so if you add it as a favorite, it's a different icon as the running instance.

**Comment by michaelarnauts** [comment]
Allright, adding a `StartupWMClass=caprine` fixes that. Who creates that desktop file? Is it also electron?

**Comment by sindresorhus** [comment]
electron-builder

**Comment by michaelarnauts** [comment]
It seems this is controlled trough the `linux`.`desktop` parameter in the `package.json`.
See https://github.com/ivelkov/teams-for-linux/blob/b107aa8e9078d3f9c64e8b4b985ceb83816024a6/package.json#L38

**Comment by michaelarnauts** [comment]
I'm not sure how to test this, but I guess this could work: https://github.com/michaelarnauts/caprine/commit/b6d28a7cbf8f2d6a6f5ad78d2eb854d577b729a1

**Comment by sindresorhus** [comment]
@michaelarnauts This should be fixed in `electron-builder`. Open an issue over there.

**Comment by dusansimic** [comment]
This issue is resloved. Closing the issue.
