### ISSUE TITLE
Blank page after internet activated

### ISSUE THREAD

**Issue by vogu66** [sindresorhus/caprine#421]
if internet isn't activated/doesn't work when the app starts, the app stays blank after internet is back

---

Caprine 2.10.0
Electron 1.8.4
linux x64 4.14.30-1-MANJARO

**Comment by sindresorhus** [comment]
Yeah, we should detect when the internet comes back and try reloading. For now, you can manually reload with Cmd/Ctrl+R.

**Comment by Catarax** [comment]
This happen often when you set a task for caprine at the startup.

**Comment by dbdness** [comment]
> This happen often when you set a task for caprine at the startup.

I experience this too on macOS. Is there any way we can launch Caprine (minimised or not) at startup without editing macOS login items and avoid manually reloading with Cmd+R? I couldn't seem to find anything about it. I saw this issue #313 that seemed to add an option to the GUI, but I don't see any startup-related settings in Caprine Preferences. I'm at version 2.23.

Thanks for the hard work by the way, I really like the app.
