### ISSUE TITLE
Brew cask not working

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/caprine#43]
```console
$ brew cask install caprine
Error: Cask 'caprine' definition is invalid: Bad header line: parse failed
```

Not entirely sure what that error means, but install via Homebrew seems to be broken.

**Comment by sindresorhus** [comment]
Saw this exact error message in another thread yesterday.

The fix was:

```
$ brew uninstall --force brew-cask; brew update
```

Seems cask was integrated in brew or something.

**Comment by Qix-** [comment]
Cool :+1: thanks!
