### ISSUE TITLE
Set urgency hint when a message is received and Caprine isn't focused

### ISSUE THREAD

**Issue by currybullen** [sindresorhus/caprine#435]
I use i3wm on Linux and it would be nice if Caprine set the urgency hint flag when an new message was received (and the window isn't focused) so that you'd know that you have unread messages. This is useful if you're not at the computer when the message is received, when you get back you'll still get notified through the workspace icon/window border.

While googling for this I stumbled upon a similar feature request (https://github.com/yakyak/yakyak/issues/101) for a Google Hangouts desktop application called YakYak and it seems like it is doable in Electron.

**Comment by LackOfGumption** [comment]
Hi, I'd like to try and get this working if it's still available.
Seems mainWindow.flashFrame is already implemented for Windows so should be easy to get it to work for the others too.
