### ISSUE TITLE
Notifications Muted... and dark mode unreaded messages...

### ISSUE THREAD

**Issue by dachronos** [sindresorhus/caprine#437]
when aplication starts the option "Mute notification" are checked... I uncheck but if close the app and start again, again "Mute notification" are checked...

In "Dark Mode" the unreaded messages no have a hightlight color.

---

Caprine 2.12.1
Electron 1.8.6
linux x64 3.16.0-4-amd64

**Comment by dusansimic** [comment]
@dachronos the 'highlight color' in dark mode is actually the bold font on unread messages and conversation name. But I agree this is not visible enough, maybe it should get a lighter shade or something like that.
