### ISSUE TITLE
Download / Right Click "Save Image" Does nothing.

### ISSUE THREAD

**Issue by lilchancep** [sindresorhus/caprine#444]
Windows 10 April 2018 Update

I cannot save images with caprine in any way,

Caprine Version 2.12.1

**Comment by sindresorhus** [comment]
Saving images works for me on macOS 10.13.

**Comment by ForumLiker** [comment]
The same problem on Linux

**Comment by veniversum** [comment]
On Windows it downloads into the default Downloads directory.

The behavior is consistent with other electron apps e.g. Slack.

**Comment by lilchancep** [comment]
I apologize. I was so used to getting prompted where to save something. Thank you!
