### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by igorzhariy** [sindresorhus/caprine#448]
Search didn't help much. I'm getting blank screen on first start on 2.12.0 and 2.12.1 running on Mac os 10.13.4 and can't log in

**Comment by igorzhariy** [comment]
Building with login.messenger.com instead of messenger.com/login didn't help as well..

**Comment by nacr** [comment]
Yap POP!OS the same.

**Comment by SkullMasher** [comment]
Hello There I have a "blank screen" has well on Debian.

Running Caprine through the command line reveals a problem when the app is checking for update.

```
[19:22:57.145] [info] Checking for update
[19:22:57.282] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:380:27
    at Generator.next (<anonymous>)
From previous event:
...
```
[Full log if that can help](https://pastebin.com/v2pk5Dxg)

While I'm at it, thank you for your work.

**Comment by kdl88** [comment]
Look's like the problem solved. Today I tried to launch Caprine version 2.12.1 under Debian and program works out of the box. Thank you for your quick fix.

**Comment by SkullMasher** [comment]
Yeah me too. Would be interested to know what happened.

**Comment by igorzhariy** [comment]
Can confirm. Fixed by itself.
