### ISSUE TITLE
Hide window on Escape

### ISSUE THREAD

**Issue by itsrexb** [sindresorhus/caprine#449]
Hi, how do we hide the window on Esc in ubuntu 16.04?  Thanks!

**Comment by zdenekvecera** [comment]
It is bad. Closing the window through ESC would be great. It would be comfortable and, moreover, it is quite standard.

**Comment by zdenekvecera** [comment]
Thanks, but I have Windows 10. 

Why do not you want to implement window minimization with ESC directly in the Caprine application? Thanks. It would be more intuitive for the user.
