### ISSUE TITLE
Use a nicer tray icon

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#450]
please make tray icon something more stylish.

currently on kde looks like:
https://i.imgur.com/TtQcdoA.png

would love:
https://imgur.com/8FTEoLv (this is from numix icon set)
or something monochrome

**Comment by centraleffects** [comment]
This is how it looks in Ubuntu 16.04  task bar a question icon
https://www.dropbox.com/s/pu9ug1nj9nmzvqp/Screenshot%20from%202018-05-11%2002-37-08.png?dl=0

**Comment by jimmy213** [comment]
Speaking of nicer tray icon, it might be better to be grey when there isn't any new message and teal (I think that's the color) when a message arrives.
That way, it should be more obvious when a new message arrives, as it's hard to see the little red dot sometimes.

**Comment by alekksander** [comment]
@jimmy213 good idea. if there is green light for this from the dev (@sindresorhus), i could try to design two svg (png?) icons.

**Comment by Pobega** [comment]
The way that @jimmy213 describes it is how Messenger for Desktop does it, and it would be much appreciated. It's the main way I notice when I get new messages.

**Comment by jimmy213** [comment]
To tell you the truth, I had this in mind, as I was using it before moving to Caprine.

**Comment by Smatchcube** [comment]
It looks perfectly fine with the app image on my machine.
![2018-06-06-103506_1920x1080_scrot](https://user-images.githubusercontent.com/19359975/41026730-93e192b6-6975-11e8-990e-8d871ee9cc35.png)

**Comment by sindresorhus** [comment]
> Speaking of nicer tray icon, it might be better to be grey when there isn't any new message and teal (I think that's the color) when a message arrives.
That way, it should be more obvious when a new message arrives, as it's hard to see the little red dot sometimes.

Yeah, sure. PR welcome.

**Comment by Pobega** [comment]
@Smatchcube 

This is how Messenger for Desktop (and all the other programs I've used) do it:
![screenshot from 2018-06-06 13-42-12](https://user-images.githubusercontent.com/474525/41055488-7961d8be-698f-11e8-8aa9-b67ff5cec14c.png)

And on new message:

![screenshot from 2018-06-06 13-48-20](https://user-images.githubusercontent.com/474525/41055839-4a36c206-6990-11e8-9248-631990ceb755.png)

**Comment by pintergreg** [comment]
With #482 we've got new gray tray icon, witch is in my opinion somewhat better but it is just a grayscale version of the old one. I would like to see some symbolic icons (maybe with an option).

I used Inkscape to convert the Caprine icon to SVG and create a simplier version to visualize my idea.

The current, grayscaled icon:

![caprine_current](https://user-images.githubusercontent.com/3854784/41832672-3d29c29a-784d-11e8-8945-7df362d513a0.png)

My modified version:

![caprine_smybolic](https://user-images.githubusercontent.com/3854784/41832692-50c50ddc-784d-11e8-9069-d946c50b0fa1.png)

Unread could be white (I used a 5% gray) or even blue.
And finally [the SVG file](https://gist.github.com/pintergreg/575fb032e69ec2e3c9e05100989ce86c).

What d you think?

**Comment by sindresorhus** [comment]
@pintergreg Yeah, I agree the flat one (yours) looks better.

**Comment by alekksander** [comment]
with newest build it's still like:

https://i.imgur.com/TtQcdoA.png

under newest kde plasma

**Comment by sindresorhus** [comment]
@alekksander Probably related to https://github.com/electron/electron/issues/12791

**Comment by whitecrownclown** [comment]
It seems this can't be done at the moment, at least not using svg because of [electron/electron#9642](https://github.com/electron/electron/issues/9642)

**Comment by maxoku** [comment]
Now it shows dark gray icon and blue when message comes. Would it be possible to somehow personalize it to show it blue normally? Then when message come add a red dot or change color?

**Comment by alekksander** [comment]
yes, it's possible. https://github.com/sindresorhus/caprine/tree/master/static here are pngs used to display regular and unread icons. You have to swap these with one You prefer (which means inkscape, or photoshop work ahead of You.) i use icons from numix to integrate to my system nicely
![Screenshot_20200513_202406](https://user-images.githubusercontent.com/3148302/81850276-0ca4a980-9558-11ea-9763-fb1d308ec91d.png)
![Screenshot_20200513_202657](https://user-images.githubusercontent.com/3148302/81850300-18906b80-9558-11ea-90d8-972fad3136db.png)
![Screenshot_20200513_202729](https://user-images.githubusercontent.com/3148302/81850367-2c3bd200-9558-11ea-9b2a-83b7a45e8aea.png)

compiling electron is very easy. almost too easy ;)

**Comment by maxoku** [comment]
@alekksander 
But how exactly?

**Comment by alekksander** [comment]
please pm me:
https://privnote.com/tvpJpCrI#RU3p6pl6w
