### ISSUE TITLE
Notifications on the taskbar

### ISSUE THREAD

**Issue by ForumLiker** [sindresorhus/caprine#452]
Hello. Can you make notifications on the taskbar with a new inbox message? On my DE cinnamon there are no notifications, only label Caprine.

**Comment by sindresorhus** [comment]
Can you share a screenshot of what it currently looks like? I'm not familiar with DE Cinnamon.

**Comment by ForumLiker** [comment]
![deepinscreenshot_ - _20180513014448](https://user-images.githubusercontent.com/11502792/39962143-36592b42-564f-11e8-8d51-373abb10f1c6.png)
for example, how notifications are displayed in another application (shows the number of unread messages)
https://github.com/aluxian/Messenger-for-Desktop
![deepinscreenshot_ - _20180513014915](https://user-images.githubusercontent.com/11502792/39962170-ffe03afa-564f-11e8-81e5-5f997165929a.png)
![deepinscreenshot_ - _20180513014927](https://user-images.githubusercontent.com/11502792/39962173-028434d2-5650-11e8-8b89-4e3e2c788215.png)
alternately displays the name of the person who sent the message and the number of all unread messages
https://github.com/brandonwu/Facebook-Messenger-Desktop
maybe you'll have to take the code from their project

**Comment by dusansimic** [comment]
This would mean changing the title of a window. I would recommend to add an option for enabling/disabling this since I personally find it annoying to have a number that vary in the window title and some other people would probably too. I would be happy to make a PR for this.

**Comment by ForumLiker** [comment]
The red dot is not visible from the couch, it is very small. For example: other applications completely change the color of the icon

**Comment by sindresorhus** [comment]
@ForumLiker If you need to see it from the couch, you could turn on notifications. Those are more visible.

**Comment by ForumLiker** [comment]
The red dot is not visible from the couch, it is very small. For example: other applications completely change the color of the icon

**Comment by dusansimic** [comment]
Current behavior is that Caprine icon is gray until there is a new message, then it turns blue. As this behavior was requested by the author, I'll close this issue.
