### ISSUE TITLE
Links suddenly stopped being treated as links - they are just text now in the messages

### ISSUE THREAD

**Issue by andrewsdv** [sindresorhus/caprine#457]
It's strange but links suddenly stopped being treated as links - they are just text now in the messages. Upgraded Caprine from 2.7 to 2.12 but that didn't help. Restarted linux but that also didn't help. Could you please help me sort out this issue?

Thanks.

---

Caprine 2.12.1
Electron 1.8.6
linux x64 4.13.0-41-generic

**Comment by cawa-93** [comment]
This is a problem on the side of the facebook messenger

**Comment by andrewsdv** [comment]
@cawa-93 So what shall I do? It's not clear for me still after your answer how the issue could be solved.

**Comment by cawa-93** [comment]
@andrewsdv 
1. Make sure the links in your web browser are displayed correctly.
2. If not - just wait. I think the developers of the facebook messenger are already aware of the problem and will soon solve it.
3. Open this issue again if you notice that the links are correct in the web version but still do not work in the caprine.

**Comment by andrewsdv** [comment]
Links are parsed correctly now, @cawa-93 was right.
