### ISSUE TITLE
Linux - segfault when clicking on notification

### ISSUE THREAD

**Issue by baldpale** [sindresorhus/caprine#46]
It happens both on Gnome and Plasma (KDE). When I click on native notification to see message, Caprine crashes.
There's message from kernel:
`[14261.845970] Caprine[10685]: segfault at 0 ip 000000000312ed9b sp 00007ffdde03ad30 error 4 in Caprine[400000+3860000]`
Feel free to ask me anything to try, test and deliver any logs.

-

Caprine 0.5.1
linux x64 4.3.3-3-ARCH

**Comment by phamdaniel** [comment]
Could you try the latest release v0.6.0 as de4baed835988db48b898f5869afb80397dd118e

**Comment by baldpale** [comment]
It is indeed. I'm sorry - didn't notice update. Please close this.
