### ISSUE TITLE
Publish to Snap Store

### ISSUE THREAD

**Issue by lpan** [sindresorhus/caprine#460]
I would be interested in working on this if you think it is a good idea :slightly_smiling_face: 

https://snapcraft.io/store

**Comment by sindresorhus** [comment]
Sure. I've registered the name `caprine` on the Snap store. I need some help with setting up the config in package.json for Snap: https://www.electron.build/configuration/snap

**Comment by sindresorhus** [comment]
Note to self. Docs for publishing: https://docs.snapcraft.io/build-snaps/upload

**Comment by lpan** [comment]
Amazing

**Comment by lpan** [comment]
@sindresorhus any updates on this? Do you still need help setting up the config?

**Comment by sindresorhus** [comment]
@lpan See #464

**Comment by lpan** [comment]
@sindresorhus have you published Caprine to the Snap store? :slightly_smiling_face:

**Comment by sindresorhus** [comment]
It's published now: https://snapcraft.io/caprine

**Comment by sindresorhus** [comment]
Let me know how it works.

**Comment by sindresorhus** [comment]
Also please vote up this issue: https://github.com/electron-userland/electron-builder/issues/3187

// @dusansimic
