### ISSUE TITLE
No icon in tray on Ubuntu 18.04 with Community Theme installed

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#461]
System: Ubuntu 18.04 x64 with Community Theme installed

There is no app tray icon :(
![image](https://user-images.githubusercontent.com/24995381/40256556-ebc9ec40-5afb-11e8-8de6-45324fb884b6.png)

**Comment by vanushwashere** [comment]
It disappears if on login you select Community Theme session,
Here is  [https://github.com/ubuntu/gnome-shell-communitheme/issues/15#issuecomment-381224806](link) to the issue and workaround like adding *env XDG_CURRENT_DESKTOP=Unity* to launch options.

**Comment by sindresorhus** [comment]
This will be fixed when we upgrade to [Electron](https://electron.atom.io) v2. We can't do that yet as v2 as many other bugs that would affect us...

**Comment by sindresorhus** [comment]
Can you try the latest version? https://github.com/sindresorhus/caprine/releases/tag/v2.13.0

**Comment by vanushwashere** [comment]
@sindresorhus I can confirm that problem has gone
![image](https://user-images.githubusercontent.com/24995381/40281184-0ae2d1f4-5c6f-11e8-9e64-fbcd2dcd2592.png)
