### ISSUE TITLE
No icon in Ubuntu 18.04

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#462]
System: Ubuntu 18.04 x64
There is no icon in GNOME
![image](https://user-images.githubusercontent.com/24995381/40256618-1b740c5a-5afc-11e8-8bc6-a7035c54aef2.png)

**Comment by vanushwashere** [comment]
As a workaround I suggest to manuly download svg icon to `/opt/Caprine/` folder, edit `/usr/share/applicaitons/caprine.desktop/` file and provide full path to svg icon in Icon= field

**Comment by sindresorhus** [comment]
Duplicate of #416
