### ISSUE TITLE
Enable vibrancy mode again

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#463]
It had to be disabled so we could upgrade to Electron v2, where vibrancy is super buggy.

**Comment by StivMs** [comment]
Does this affect the grey theme too? The white theme is to bright to use.

**Comment by sindresorhus** [comment]
If you mean the dark mode, it’s still there.

**Comment by StivMs** [comment]
No, the recent version had 3 themes, super white, Grey and then vibrant /dark. I mean the Grey one which is way better to look at.

**Comment by sindresorhus** [comment]
The "gray" theme is the light theme with vibrancy mode turned on. It's gone temporarily. It's unfortunately out of our control.

**Comment by simgust** [comment]
Sucks, would be awesome to have :( Maybe the readme should reflect this, though.

**Comment by oliver92** [comment]
+1 for vibrancy :) Are you planning on bringing it back?

**Comment by sindresorhus** [comment]
Good news. Vibrancy mode is finally back in the latest version: https://github.com/sindresorhus/caprine/releases/tag/v2.21.0
