### ISSUE TITLE
Request - Power safe mode

### ISSUE THREAD

**Issue by FrankMa1** [sindresorhus/caprine#469]
Hello,
I recently noticed that Caprine (MacOS) is switching graphics card from Integrated to High Performance which causes undesired energy impact.
Would be great if it was possible to switch.
Thank you.

**Comment by bodak** [comment]
Hardware acceleration has been re-enabled with Electron 2.0 migration.
From @sindresorhus "I also had to enable hardware acceleration again as having it off caused a lot of rendering artifacts."

Commit:
https://github.com/sindresorhus/caprine/commit/676b2277406442f511f9017b77d0516a1c4b2988

See past issues: 
https://github.com/electron/electron/issues/9842
https://github.com/sindresorhus/caprine/issues/238

**Comment by sindresorhus** [comment]
We also need https://github.com/electron/electron/issues/1615, so we can only switch to the integrated GPU when on battery, for best performance.

**Comment by d235j** [comment]
@sindresorhus I'm not experiencing rendering artifacts with a hand-patched version that disables acceleration. Can you check if this still happens? Perhaps the cause was fixed in Electron 3.x.

**Comment by skymakai** [comment]
d235j, would you please point to where there are instructions on 'hand-patching' to disable acceleration?

**Comment by d235j** [comment]
@skymakai 
Re-add this line and rebuild:
https://github.com/sindresorhus/caprine/commit/676b2277406442f511f9017b77d0516a1c4b2988#diff-168726dbe96b3ce427e7fedce31bb0bcL24

**Comment by kevinjalbert** [comment]
@skymakai I'll have to give this a try and see if I see any rendering artifacts myself.

It is unfortunate that Caprine is the only app that I have at times which switches the graphics to high performance effectively cutting my battery time in half. I would love to see something which keeps the graphics card in-check.

Will report my findings later.

**Comment by kevinjalbert** [comment]
Just reporting that I haven't seen anything off from a rendering perspective. I've made a PR #620 that adds a config so that people can selectively disable hardware acceleration.
