### ISSUE TITLE
Locale detection / matching incorrectly.

### ISSUE THREAD

**Issue by PeterDaveHello** [sindresorhus/caprine#471]
Hello,

I'm a big fan of Caprine, using for a while, everything looks cool, just also noticed a small issue for a while, in my *Traditional Chinese* environment, caprine starts with Facebook's *Simplified Chinese* interface, which is interesting, because of Facebook supports Traditional Chinese for a long time and can detect the locale automatically in the browsers without a problem, so I took a while to find what happened, and after a quick digging, I found some something, here's my report:

The problem was caused here:
https://github.com/sindresorhus/caprine/blob/v2.13.1/index.js#L137
```js
const userLocale = facebookLocales.bestFacebookLocaleFor(app.getLocale());
```

The locale string returned by electron(`app.getLocale()`) uses `-` to separate language and country(See 
[Electron / API / Locales](https://electronjs.org/docs/api/locales)), however, the library `facebook-locales` didn't handle locales with `-` properly, instead, it can only handle the locale strings that separate language and country with `_`.

The problem not only just affect Traditional Chinese but all the locales having `-` to separate their main language and country, like `en-IN`, `en-GB`, `fr-FR` ... etc. See: http://fbdevwiki.com/wiki/Locales

I've fired an issue to upstream here: https://github.com/wix/facebook-locales/issues/3 and also sent a pull request here: https://github.com/wix/facebook-locales/pull/4

So once the pull request was accepted and the version of `facebook-locales` was bumped, I'd be happy to help update the version of `facebook-locales` here and help test the result. If the pull request was rejected, then I'll like to help adjust the locale string to feed to `facebook-locales`, so that we can finally have the correct locale mapping, or if it's acceptable, I'd also be happy to send a pull request to adjust the locale string now in Caprine repository, then we don't need to wait for upstream ;)

**Comment by cawa-93** [comment]
Maybe should temporarily apply the next fix?
```js
const userLocale = facebookLocales.bestFacebookLocaleFor(app.getLocale().replace('-', '_'));
```

**Comment by PeterDaveHello** [comment]
I can do that with @sindresorhus's agreement, @sindresorhus what do you think?

**Comment by sindresorhus** [comment]
Sure

**Comment by PeterDaveHello** [comment]
Sent in #473!
