### ISSUE TITLE
No vibrancy mode on macOS 10.13.4 (17E202)

### ISSUE THREAD

**Issue by YannMCX** [sindresorhus/caprine#475]
I can't enable Vibrancy Mode
---

Caprine 2.13.1
Electron 2.0.1
darwin x64 17.5.0

**Comment by sindresorhus** [comment]
Duplicate of #463

**Comment by robjtede** [comment]
_commenting here since the duplicate issue is locked_

How's support for vibrancy in the now-stable v3 ?
