### ISSUE TITLE
Fake your real identity by automatically faking your behavior

### ISSUE THREAD

**Issue by dumblob** [sindresorhus/caprine#477]
For quite some time I was thinking how to prevent disclosure of the most important (at least in my opinion) information of yours. Namely your very own real unique identity described by your behavior, preferences, etc.

There seem to be some techniques which could work. For example:

* automated background activity with auto-generated content not distinguishable from your own activity (imagine [Markov chains](https://en.wikipedia.org/wiki/Markov_chain ) like in this [example](http://kingjamesprogramming.tumblr.com/ )).
* randomly delayed real activity of yours (or not totally random, but based on the locality where your global IP address appears)
* ...

What do you think?

**Comment by dumblob** [comment]
I'm feeling really dumb now as I didn't notice there are already tons of partial implementations of this proposal - just google `markov github facebook` or just search for `markov facebook` in the GitHub search.

**Comment by dusansimic** [comment]
This is an interesting technology however it's not the goal of Caprine. Caprine is a messaging app. This could be a cool extension for a web browser or something.
