### ISSUE TITLE
New conversation icon overlaps window buttons (macOS)

### ISSUE THREAD

**Issue by simgust** [sindresorhus/caprine#481]
When the window is small enough to trigger the collapsed side bar, the new conversation icon sits behind the window buttons in (macOS).

<img width="170" alt="skjermbilde 2018-06-05 kl 14 46 40" src="https://user-images.githubusercontent.com/6162667/40976863-a3e55aea-68cf-11e8-9e96-210ce7c1c509.png">

**Comment by cawa-93** [comment]
It was fixed https://github.com/sindresorhus/caprine/pull/476

**Comment by simgust** [comment]
Awesome!
