### ISSUE TITLE
Cannot enable microphone for voice call on Linux

### ISSUE THREAD

**Issue by cdr255** [sindresorhus/caprine#484]
![screenshot from 2018-06-06 23-08-18](https://user-images.githubusercontent.com/1392828/41076222-8f993772-69de-11e8-9fed-e1076e447d8e.png)

I might be missing a configuration option somewhere, but when I try to join or make a voice call on Fedora 28 I'm presented with the above screen. It looks similar to the one in chromium, except the "Allow" and "Block" buttons are hidden or missing. 

The only recourse is to close this window, upon which Facebook thinks I very quickly joined and left a call. I confirmed voice calls do work through chromium, so I don't think it's a problem with my setup, though I can supply more information if needed.

**Comment by truefriend-cz** [comment]
I have problem too. Author not solving problem long time... (from first versions 7 Feb 2016).

**Comment by FarhanSalafi** [comment]
I have problem too. what are the author doing.

**Comment by Rezonansowy** [comment]
Same here. Please review the report and assign it. Thank you.

**Comment by salvipeter** [comment]
Still there...
System: 5.6.5-1-MANJARO x86_64
Version: 2.45.0-1
