### ISSUE TITLE
Cannot find module '/tmp/.mount_caprinyOf1Mc/resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by MarioPereira** [sindresorhus/caprine#485]
I have been using Caprine for some months now, and today it auto-updated (as usual) but would not start after update. Launching Caprine AppImage from a terminal gives the following error:

module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_caprinyOf1Mc/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

I'm using Xubuntu 17.10, if it helps

**Comment by sindresorhus** [comment]
See https://github.com/electron-userland/electron-builder/issues/2958
