### ISSUE TITLE
AppImage build number

### ISSUE THREAD

**Issue by ljubacanoa** [sindresorhus/caprine#489]
Can you please remove build numbers from image as on every update caprine-XXX.AppImage desktop launchers became useless, forcing us to create new launchers (including for startup)? Also, now yu fixed issue with build 14 but we need again to 'fix' our *.desktop files.

**Comment by sindresorhus** [comment]
I'm using `electron-builder` for building AppImage. You need to request that over there: https://github.com/electron-userland/electron-builder
