### ISSUE TITLE
App name not in Windows taskbar context menu

### ISSUE THREAD

**Issue by martellaj** [sindresorhus/caprine#49]
Not sure what other details to supply. Please let me know if this is unclear. :dancer: 

![image](https://cloud.githubusercontent.com/assets/1019478/12959670/4b3bd4d8-cfec-11e5-81b5-44b448daa746.png)

**Comment by sindresorhus** [comment]
That's weird. We set the product name in the build step: https://github.com/sindresorhus/caprine/blob/782b99b0a7678cf2a1758b056702c163206af151/package.json#L27

```
--version-string.ProductVersion=$npm_package_electronVersion
```

See the Electron package docs: https://github.com/maxogden/electron-packager

I don't use Windows and don't have time looking into this, but help welcome :)

-

// @iiegor

**Comment by grawlinson** [comment]
Just chiming in to say that I don't have this issue. Running the latest version of Windows 10 Pro, if that helps.
![issue49](https://cloud.githubusercontent.com/assets/4408051/13032761/25b75626-d364-11e5-9b57-dff01577f242.png)

**Comment by sindresorhus** [comment]
@martellaj Do you still see the issue with the latest Caprine version? https://github.com/sindresorhus/caprine/releases/tag/v1.2.2
