### ISSUE TITLE
Redundant scrollbar in message entry (Windows)

### ISSUE THREAD

**Issue by NeedsAdjustment** [sindresorhus/caprine#490]
A redundant scrollbar appears if the window size is small enough that the right sidebar is hidden and the left sidebar is not toggled to hidden.

![not good](https://user-images.githubusercontent.com/10917143/41163142-fe42e610-6b8b-11e8-8937-e95810e6da3c.png)

**Comment by ivancuric** [comment]
Fixed in https://github.com/sindresorhus/caprine/pull/153, but rejected.

**Comment by NeedsAdjustment** [comment]
That's really unfortunate; in my opinion the scrollbar bug becomes a lot more obvious and apparent with the dark theme; and moreover it's been an issue for over a year now so it's not like messenger.com has been updating and breaking css tweaks.

Oh well.

**Comment by ivancuric** [comment]
@sindresorhus any chance of reconsidering the PR?

**Comment by sindresorhus** [comment]
Fixed in the latest release.
