### ISSUE TITLE
how to disable auto-focus when new message coming?

### ISSUE THREAD

**Issue by fluency03** [sindresorhus/caprine#492]
Recently, I found that caprine will be auto-focused when new message is coming or other people have read the message and the status of read changed. 

It was not the case previously and it is very annoying. Because whenever and whichever application I am using, I will be bounced back to Caprine. 

I would like to know how can I disable it?

I am on MacOS 10.13.5
Caprine version is 2.14.1 

Thanks.

**Comment by janosorcsik** [comment]
Update to the latest version. This issue has been fixed.

**Comment by fluency03** [comment]
Thanks ! @janosorcsik

**Comment by alok** [comment]
I have this issue too, and I'm on the latest release.
