### ISSUE TITLE
Notifications preference not remembered

### ISSUE THREAD

**Issue by petko** [sindresorhus/caprine#498]
Every time I start Caprine, Desktop Notifications are enabled, even though I disabled them in the Preferences during the previous launch (and this is respected for the duration of the previous session). I use Caprine 2.14.2 under Windows 10.

**Comment by petko** [comment]
The problem is back in 2.16.0, I am afraid..

**Comment by sindresorhus** [comment]
// @dusansimic

**Comment by dusansimic** [comment]
@petko you're supposed to toggle notifications option in menu bar, not in preferences. There is no event listener for toggling notifications options through preferences, but that feature could be added.

**Comment by petko** [comment]
Sorry, I am not aware of the internals of Caprine. But I think that it should be possible in the Preferences too. If not, it either should be disabled there or there should be some kind of reminder that it is not remembered between sessions. Because if you change it in the Preferences, it stays for the duration of the session.

**Comment by dusansimic** [comment]
I agree, @sindresorhus any thoughts on adding event listeners for preferences dialog or hiding options from preferences?

**Comment by sindresorhus** [comment]
@dusansimic We can just hide it from Preferences.
