### ISSUE TITLE
Can't remove link preview + every app open show me settings popup

### ISSUE THREAD

**Issue by Widziks92** [sindresorhus/caprine#502]
1. https://i.imgur.com/hj1hN4S.png
If i paste link into "Type a message..." and want to remove it (ex. i see wrong link). I can't do that (only turn off and turn on app works and clear it). 

2. If i quit app and open it i see settings popup every time i open app.
https://imgur.com/3F9lubB

App and OS info:
Caprine: Version 2.14.2 (2.14.2.808)
OS: macOS High Sierra, version: 10.13.3

**Comment by cawa-93** [comment]
It was fixed there https://github.com/sindresorhus/caprine/pull/493

**Comment by dusansimic** [comment]
The second issue is also fixed in https://github.com/sindresorhus/caprine/pull/500.

**Comment by dusansimic** [comment]
This issue is fixed.
