### ISSUE TITLE
Any way to have Caprine not try to run bluetooth on startup? 

### ISSUE THREAD

**Issue by qoaa** [sindresorhus/caprine#507]
my pc doesn't have bluetooth so ive got that service disabled and have systemctl masked it of course. For some reason Caprine tries to run it still. I don't see any options in the menu to disable attempt to access bluetooth. Is there a command line option I missed? It's not a big issue since the service is masked but perhaps option to disable logging to syslog or maybe that exists hehe not sure 

I'm using the portable version '_caprine-2.15.0-x86_64.AppImage_' in Linux Mint 18.3 Cinnamon 

from syslog:

> Jun 24 16:41:23 cito dbus[872]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
> Jun 24 16:41:23 cito dbus[872]: [system] Activation via systemd failed for unit 'dbus-org.bluez.service': Unit dbus-org.bluez.service is masked.

every time i open Caprine that always occurs. 

Further details on my system 

Mint 18.3 64bit
Cinnamon 3.6.7
Kernel 4.13.0-45-generic

**Comment by sindresorhus** [comment]
That's unfortunately out of our control. It's Chrome, through Electron, that tries to do that. Probably because of the Web Bluetooth API.

**Comment by qoaa** [comment]
I kinda figured that was the issue.


Thank you very much for the information and confirmation though. Love the program, thank you
