### ISSUE TITLE
Add package for Chocolatey

### ISSUE THREAD

**Issue by tracker1** [sindresorhus/caprine#509]
It would be really nice if the installer could be run unattended via Chocolatey...

https://chocolatey.org/

**Comment by sindresorhus** [comment]
Can you open an issue on https://github.com/electron-userland/electron-builder for Chocolatey support? It will need to be added there first.

**Comment by tracker1** [comment]
Feature request requested...

https://github.com/electron-userland/electron-builder/issues/3060

**Comment by tracker1** [comment]
Similarly adding as a brew cask install in homebrew.

**Comment by sindresorhus** [comment]
> Similarly adding as a brew cask install in homebrew.

It's already there.

**Comment by tracker1** [comment]
@sindresorhus per the request in electron-builder, looks like you just have to have a Chocolatey script run the windows installer with a `/S` argument for a silent install.. :-)

**Comment by sindresorhus** [comment]
@tracker1 I think you misunderstood me. I meant you need to open an issue on `electron-builder` to add support for generating a Chocolatey-ready package. That includes a Nuspec and other things. `electron-builder` already has various targets, like NSIS. Chocolatey would be another one. For requirements, see: https://chocolatey.org/docs/create-packages#okay-how-do-i-create-packages

**Comment by tech189** [comment]
Does electron-builder now support generating Chocolatey-ready packages? I would love to have a package for caprine :)

**Comment by sindresorhus** [comment]
@tech189 No

**Comment by sindresorhus** [comment]
If anyone wants this, open an issue on `electron-builder` like I said.

**Comment by mquevill** [comment]
I created a [Chocolatey package for Caprine](https://chocolatey.org/packages/caprine) starting with v2.35.0. It is now approved and available for download.
