### ISSUE TITLE
Menu item and shortcut for quickly deleting a conversation

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#51]
A user suggested it would be useful to have a menu item and shortcut for this.

Anyone wanna try doing a pull request? I can mentor.

**Comment by grawlinson** [comment]
I'd be willing to give this a go, however I have no exposure to Electron. More than happy to look at Electron guides & other Electron applications to get an idea of how it works.

What do you mean by mentor?

**Comment by sindresorhus** [comment]
> What do you mean by mentor?

Help you get started and answer any questions.

-

Take a look through the Electron docs first. What needs to be done is to add the menu item to the OS X and Linux menu templates in `menu.js`. The menu item define the keyboard shortcut too. Need to figure out the best shortcut to use. The action that is triggered from the menu needs to trigger the a method using IPC (see existing menu items) and in `browser.js` there needs to be a method to listen to the IPC event and do the actual action by triggering the correct DOM elements (see existing events).

**Comment by sindresorhus** [comment]
@phamdaniel Interested? Of course not until we resolve the open PRs :)

**Comment by phamdaniel** [comment]
I had a quick look at it and there isn't an easy way of selecting the correct DOM element. The main reason for this is that the first popup lists aren't removed after they are closed and are name pretty arbitrarily. There might be a better way of approaching this but no promises.

**Comment by phamdaniel** [comment]
Actually scrap what I said above, I figured it out... PR incoming.
