### ISSUE TITLE
Cannot login with two-factor authentication

### ISSUE THREAD

**Issue by StoppingBuck** [sindresorhus/caprine#511]
Having 2FA enabled on your Facebook account makes you unable to use Caprine as Facebook blocks the attempt

**Comment by uocxp** [comment]
i can't confirm. I am using the app with 2FA

**Comment by sindresorhus** [comment]
@StoppingBuck Are you sure you're using the latest version of Caprine? This was fixed some time ago: https://github.com/sindresorhus/caprine/commit/69d22e06bcd7ec46433424e8b85e1e127aa2584f

**Comment by StoppingBuck** [comment]
I've actually deleted my Facebook account in the meantime, so I guess I can't confirm if this bug is still present. Feel free to close the issue.
