### ISSUE TITLE
Missing message icon does not disappear

### ISSUE THREAD

**Issue by Silver360** [sindresorhus/caprine#514]
The red icon (missing message) Is still on task bar after reading. After reload app it disappears but app need to be reload which is annoying.

Windows 10

**Comment by rtpHarry** [comment]
Yeah I get this a lot as well. It is minor but annoying.

Caprine 2.8.0
Electron 1.7.9
win32 x64 10.0.17134

**Comment by rtpHarry** [comment]
Looks like this is a dupe of #499

**Comment by Borinius** [comment]
I have the same issue aswell.

**Comment by rtpHarry** [comment]
Looks like it might be fixed in an upcoming version? https://github.com/sindresorhus/caprine/pull/531

**Comment by dusansimic** [comment]
Afaik, this work with no problems now and the issue seems stale. I'll close it now.
