### ISSUE TITLE
Add Sparkle.framework for auto updating on macOS

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#515]
https://sparkle-project.org

Almost every macOS app which is not in the App Store uses this handy framework for updating. I think Caprine needs is very much too.

**Comment by sindresorhus** [comment]
Caprine already has silently auto-updates using https://www.electron.build/auto-update

**Comment by gklka** [comment]
Then it is not working. I’m using Caprine since 1 year now and not even once updated itself.

**Comment by janosorcsik** [comment]
The auto-update only checks when the app started. We need to check more often.

**Comment by gklka** [comment]
I practically never quit, so this is the problem for me.
