### ISSUE TITLE
Sound option not remembered

### ISSUE THREAD

**Issue by petko** [sindresorhus/caprine#519]
Every time I start Caprine, Sound option is enabled, even though I disabled it in the Preferences during the previous launch (and this is respected for the duration of the previous session). I use Caprine 2.15.1 under Windows 10.

P.S.: There was the same problem with the Notifications option, but it is fixed now.

**Comment by sindresorhus** [comment]
// @dusansimic

**Comment by Fisher26** [comment]
Can confirm the same issue, MacOS High Sierra running Caprine 2.15.1, sound option is lost upon app reboot.

**Comment by Curbsidecollection** [comment]
Same issue. Running MacOS High Sierra 10.13.5 and Caprine 2.15.1. 

Mute Notifications option keeps sounds off but also disables badges obviously.

**Comment by dusansimic** [comment]
This issue is fixed (https://github.com/sindresorhus/caprine/pull/523) and is waiting for merge. You just need to be patient now.

**Comment by Curbsidecollection** [comment]
Oh great no worries. Awesome application.
