### ISSUE TITLE
Windows Startup minimized on tray

### ISSUE THREAD

**Issue by juanjotoronja** [sindresorhus/caprine#52]
This program works flawless on windows 7 it open pictures, play videos and even open links in the default browser. It needs a last addition to make it perfect, an option to launch on startup minimized on the system tray.
Sorry to pull a request in here but doesn't let me pull one in the other way. Thanks

**Comment by sindresorhus** [comment]
A good PR would be merged, but not something I care about. And you can already achieve it yourself: http://ask-leo.com/how_do_i_get_a_windows_application_to_start_automatically_on_login_and_start_minimized.html

**Comment by cwilli34** [comment]
This isn't possible on Linux.  There should still be an option to have Caprine start minimized, or at lease a command line option to start minimized.  This should be reopened as a feature or enhancement that is wanted. #
