### ISSUE TITLE
Work Chat does not work anymore

### ISSUE THREAD

**Issue by alexandreblin** [sindresorhus/caprine#520]
Work Chat doesn't work anymore since version 2.13.0 : it used to work perfectly but now, starting Caprine just opens a new tab in Safari redirecting to the web version of Work Chat, and the Caprine window becomes blank:
![screen shot 2018-07-03 at 10 03 37](https://user-images.githubusercontent.com/1523191/42206873-b201af5e-7ea8-11e8-9e58-a3d4262d0723.png)

This happens on every version from 2.13.0 to 2.15.1

**Comment by sindresorhus** [comment]
Probably related to https://github.com/sindresorhus/caprine/commit/ec73bb20aff07d8c07f2ebc883869c16d9f70de9 I had to blacklist all URLs except for known valid ones as Messenger stopped opening an external link in a new window, which caused it to just redirect the messenger window.

What's the URL for work chat?

**Comment by alexandreblin** [comment]
The URL format for Work Chat is `https://COMPANY_NAME.facebook.com/chat/`

**Comment by alexandreblin** [comment]
I did some tests, when not logged in, we are redirected to `https://work.facebook.com` to log in, then the form is POSTed to `https://COMPANY_NAME.facebook.com/login` and finally redirects to `https://COMPANY_NAME.facebook.com/chat/`
