### ISSUE TITLE
Notification badge does not work in gnome, icon is greyed out

### ISSUE THREAD

**Issue by jpt-avaleo** [sindresorhus/caprine#522]
![image](https://user-images.githubusercontent.com/35026733/42210562-a1173e08-7eb1-11e8-9085-7eeeb20eeb92.png)

This icon up top used to be blue at all times and it had a small red notification badge indicating unread messages, similiar to what slack has on the picture.

**Comment by dusansimic** [comment]
This is actually a new tray icon. There is no bug.
See https://github.com/sindresorhus/caprine/pull/482
