### ISSUE TITLE
[Feature] Adding IRC-mode

### ISSUE THREAD

**Issue by bodak** [sindresorhus/caprine#527]
This is a work-in-progress with the goal of hiding features of Messenger and make it resemble a clear chat interface.

**IRC-mode:**
- Create compact contact list by hiding profile icons and reducing margins
- Create compact chat window
- Time-stamps in front of each message
- Replaces images in chat with clickable [image]
- Hides reactions to messages and option to react
- Hides link previews
- Compatible with dark-mode

**Comparison screenshots:**

IRC-mode on
![irc-mode_on](https://user-images.githubusercontent.com/6807878/42459496-9d11915a-8393-11e8-9df3-a7e677537504.png)
IRC-mode off
![irc-mode_off](https://user-images.githubusercontent.com/6807878/42459506-a2aed104-8393-11e8-9de2-e8742afe7e3c.png)

**Known Issues:** [help wanted from CSS wizards]
- [ ] Time-stamp padding/margin. Pulling the time-stamp in front of the chat rectangle by using negative margins. This bugs out the rest of the line. Probably better approaches exist.
- [ ] Compact mode is not addressed
- [ ] Various other CSS features not addressed
- [ ] Nice to have: convert time-stamp into more compact form ("May 1st, 10:26AM" -> "01.05.18 10:26")

**Code commit:**
https://github.com/bodak/caprine/commit/3649f9e4c8275ef22f718a655f654e7443830041

(Initial irc-style CSS by https://userstyles.org/styles/123634/irc-style-messenger-com)

**Comment by cawa-93** [comment]
I find it superfluous

**Comment by sindresorhus** [comment]
I think it would be better to implement a way for users to easily apply their own CSS tweaks and the ability to share them.

**Comment by alekksander** [comment]
wow, this smells good

**Comment by bodak** [comment]
@sindresorhus I will close this for now in favor of a wider CSS tweak implementation.
