### ISSUE TITLE
Mac OS Features

### ISSUE THREAD

**Issue by sanchez** [sindresorhus/caprine#528]
I installed Caprine this morning and have been using it throughout the day, however I can't seem to get some of the features working. I read in the issues already that Vibrancy isn't supported anymore but the readme still lists it as featured. I also can't seem to get the Quick Access Conversations from the dock working or the touchbar. I have tried this using both through downloading the dmg file and installing it that way and through brew. Both times I am listed as using version 2.15.1

Thanks

**Comment by peauc** [comment]
Same as I on MacOS 10.13.5 on my MacBook Pro (15-inch, 2017)

**Comment by abhivs** [comment]
Same here, version 2.15.1 on OS X 10.13.6.

**Comment by sindresorhus** [comment]
Good news. Vibrancy mode is finally back in the latest version: https://github.com/sindresorhus/caprine/releases/tag/v2.21.0
