### ISSUE TITLE
Change conversation shortcuts on OS X

### ISSUE THREAD

**Issue by oskarkrawczyk** [sindresorhus/caprine#53]
This is funny but I opened up Atom, and wanted to implement conversation switching just to find out it's already there, only under key binding that I would never expected.

I'm kind of used to the native tab switching keys on OS X: `CMD + Shift + [` and `CMD + Shift + ]`.

I'm sure there's a reason why Caprine is currently using different ones, but perhaps it would make a good idea to change them for a more native experience?

**Comment by sindresorhus** [comment]
I think Ctrl+Tab is more common.? And it's easier to type.

Both shortcuts work in Chrome, Messages.app, Safari, etc, though.

**Comment by oskarkrawczyk** [comment]
Interesting, I've never heard of this shortcut, actually asked a bunch of friends, they also use `CMD+Shift+[]` – which also work everywhere.

And since that's the case, perhaps we could have both as well?

What are your thoughts?

**Comment by sindresorhus** [comment]
> I've never heard of this shortcut, actually asked a bunch of friends, they also use CMD+Shift+[] – which also work everywhere.

I had never heard of `CMD+Shift+[]` until just now either.

> And since that's the case, perhaps we could have both as well?

Sure.

**Comment by oskarkrawczyk** [comment]
It shall be done
