### ISSUE TITLE
Subtitle is decentered

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#533]
<img width="768" alt="screen shot 2018-07-12 at 8 24 45" src="https://user-images.githubusercontent.com/866694/42616053-1b06c2c2-85ad-11e8-95fe-7830a3547412.png">

Since 2.16.0.

**Comment by sindresorhus** [comment]
// @cawa-93

**Comment by cawa-93** [comment]
@janosorcsik fix this on #534
