### ISSUE TITLE
Small Bug with React Emojis

### ISSUE THREAD

**Issue by lamofgod** [sindresorhus/caprine#536]
Is there a way I can lower the "seen" pictures so they don't interfere with react emojis? Example in attached image.
Also, is there a way to add easy access to active contacts around the top left area of the window (in between the maximize size window button and the create new chat button)? Highlighted in red in other image.

<img width="166" alt="screen shot 2018-07-16 at 10 10 09 am" src="https://user-images.githubusercontent.com/8324776/42774871-bfab5d78-88e7-11e8-9d99-f2c12136c359.png">
<img width="351" alt="screen shot 2018-07-16 at 10 37 30 am" src="https://user-images.githubusercontent.com/8324776/42775062-4acfea36-88e8-11e8-8ff5-17f5614c8ec6.png">

**Comment by dusansimic** [comment]
As far as I know, the "seen" issue is fixed by messenger and you can access active contacts through View menu. I don't like adding any more buttons and options to empty space since it's intended to be empty.
