### ISSUE TITLE
Settings popup is open on every launch (macOS)

### ISSUE THREAD

**Issue by simgust** [sindresorhus/caprine#538]
Apparently this is fixed (https://github.com/sindresorhus/caprine/issues/502), but I’m not getting the update. Is there any way to force an update?

**Comment by vanushwashere** [comment]
Same on Ubuntu 18.04 with Caprine installed via snap

**Comment by alechp** [comment]
Is anyone still having this popup issue appear on every launch?

Experiencing this issue on _v2.22.1_. 
Confirmed with _Mac dmg_ & _brew cask_ install paths 

<img width="396" alt="screen shot 2018-12-11 at 1 39 31 pm" src="https://user-images.githubusercontent.com/3058939/49832129-aad08680-fd4a-11e8-9484-4628bc45e390.png">
<img width="1904" alt="screen shot 2018-12-11 at 1 43 53 pm redacted" src="https://user-images.githubusercontent.com/3058939/49832285-11ee3b00-fd4b-11e8-98a8-dd7200ebe939.png">

**Comment by vanushwashere** [comment]
I have that issue on latest Kde Neon with Caprine installed via Snap

**Comment by xavierbriole** [comment]
Yes, same issue since today.

**Comment by alechp** [comment]
Confirmed. Issue resolved for me as well. Version 2.23.0 (2.23.0.1054)

<img width="396" alt="screen shot 2018-12-17 at 4 50 03 pm" src="https://user-images.githubusercontent.com/3058939/50125002-d7d5db00-021b-11e9-9da9-e8e1b9a6637c.png">
