### ISSUE TITLE
"No internet connection" false alarm that cannot be dismissed

### ISSUE THREAD

**Issue by RJVB** [sindresorhus/caprine#543]
I tend to get a "No internet connection" alert message above the list of my open chats even if my internet connection is (back) up. When this happens I can only restart the application; logging out doesn't work.
(In addition, the entire caprine window went blank after I clicked on the "report issue" menu, except for the menubar.)

---

Caprine 2.14.2
Electron 2.0.2
linux x64 4.14.23-ck1-mainline-core2-rjvb

**Comment by dusansimic** [comment]
Regarding the "no internet" false alarm, that is a Messenger.com bug and not a Caprine bug. Messenger is not always perfect 🙁. As for the freezing caprine window on "report issue" click, it think that was fixed. Try installing the latest version of Caprine just to make sure.
