### ISSUE TITLE
Sounds are enabled after restart even when I turn them off

### ISSUE THREAD

**Issue by jpt-avaleo** [sindresorhus/caprine#548]

**Comment by jpt-avaleo** [comment]
This is on Manjaro with Gnome.

**Comment by sindresorhus** [comment]
// @dusansimic

**Comment by dusansimic** [comment]
@jpt-avaleo is there any way that I can reproduce that since it works on my machine?

**Comment by jpt-avaleo** [comment]
No idea how to reproduce it, maybe this is specific to Linux distro or desktop env?

**Comment by jpt-avaleo** [comment]
It is fixed in newest version. Sorry for the trouble.
