### ISSUE TITLE
[feature request] Add transparency to the main UI

### ISSUE THREAD

**Issue by possessedbysatan** [sindresorhus/caprine#550]
We know that there's already Vibrant mode for macOS, but there's nothing else for other platforms. 

However, it is possible to add transparency to Caprine's background. This opens up a lot of possibilities (at least in Linux platforms). In the screenshot below, an app is using just plain transparency and the compositor blurs the background. Caprine could use plain transparency to achieve a similar effect (just making transparent the background, but not the content, as in macOS). 

![screenshot_2018-08-04_14-26-29](https://user-images.githubusercontent.com/18079515/43679879-38fed2da-97f3-11e8-9c45-20c9064e4539.png)

**Comment by sindresorhus** [comment]
Sorry, not worth the trouble.
