### ISSUE TITLE
Update channel

### ISSUE THREAD

**Issue by Merlin-09** [sindresorhus/caprine#551]
Hello,

thanks for your software, it is really nice and useful.

I know it's not very polite to ask for something when you do this on your free time, but hey, one can try :-)

I use linux, and it would be nice if caprine could tell us when an update is available. I guess this would be nice for every os out there

Thanks again

**Comment by sindresorhus** [comment]
Caprine doesn't have update notifications as it auto-updates on macOS, Windows, and Linux if you use AppImage. If you use `deb`, it has its own mechanism for notifying about updates.
