### ISSUE TITLE
Screen share not working

### ISSUE THREAD

**Issue by tamasviktor** [sindresorhus/caprine#554]
Dear Developers!

![screenshot_1](https://user-images.githubusercontent.com/2786590/43899230-887d56aa-9be1-11e8-8c4c-cb62b36ec129.png)

Everytime when we click to Screen share button we get "Add extension message" :(

Ty.

---

Caprine 2.16.0
Electron 2.0.4
win32 x64 10.0.17134

**Comment by pkuczynski** [comment]
When you click add extension it takes you to the page, but you are not able to install it. I found this thread https://github.com/electron/electron/issues/1498 but apparently its not possible to install chrome extensions in electron...?

**Comment by andrewjong** [comment]
Could this help? https://www.npmjs.com/package/electron-chrome-extension

**Comment by pkuczynski** [comment]
@sindresorhus do you think we should approach it this way?
