### ISSUE TITLE
False Positive? MALICIOUS

### ISSUE THREAD

**Issue by antuketot76** [sindresorhus/caprine#555]
Hi @sindresorhus  below are the result as below, is it false positive?
Please clear up with this AV company for file intergrity.

VIRUSTOTAL - [HERE](https://www.virustotal.com/#/file/9f8a7dc72d35e39e4093b44209f17c73382cbdb44f5de3af2c45815d1a554870/detection)

HYBRID ANALYSIS - [HERE](https://www.hybrid-analysis.com/sample/9f8a7dc72d35e39e4093b44209f17c73382cbdb44f5de3af2c45815d1a554870/5b6c4de37ca3e1547877f4e5)

![image](https://user-images.githubusercontent.com/33280865/43906154-8d02cb6e-9c2d-11e8-9936-3424ab769740.png)

**Comment by sindresorhus** [comment]
It's a false-positive. Anti-virus apps are junk.

See: https://github.com/beakerbrowser/beaker/issues/898
