### ISSUE TITLE
Linux appindicator icon

### ISSUE THREAD

**Issue by muzzzdy** [sindresorhus/caprine#556]
In latest Gnome there's no tray anymore.
Can AppIndicators support be added so Caprine can work with https://github.com/Ubuntu/gnome-shell-extension-appindicator ?

**Comment by sindresorhus** [comment]
This needs to be fixed in Electron: https://github.com/electron/electron/issues/10427

**Comment by dusansimic** [comment]
@muzzzdy please specify which version of Gnome are you using since it works perfectly on 3.28 with the latest version of Caprine.

**Comment by daenney** [comment]
It doesn't work for me with GNOME 3.28 either. They removed the old tray, so unless you have something like TopIcons Plus installed no icon for Caprine will show anymore.

**Comment by muzzzdy** [comment]
I use Gnome 3.28.2. There's no tray to display icon at all.

**Comment by dusansimic** [comment]
The tray icon on my machine is working perfectly. Try enabling `Ubuntu appindicators` extension. On which version of Caprine does that occur?

**Comment by muzzzdy** [comment]
I have appindicators extension - no Caprine in here.

**Comment by daenney** [comment]
Same, I have the Ubuntu/kstatusNotifier/AppIndicator extension installed and loaded, even rebuilt it yesterday. Works fine with applications like Keybase, but no dice for Caprine.

**Comment by dusansimic** [comment]
Issue is stale and tray icon works in the latest version of Caprine with the extensions that is linked in the issue description. Closing.
