### ISSUE TITLE
Wrong Categories

### ISSUE THREAD

**Issue by pavroo** [sindresorhus/caprine#565]
Hi
The desktop file of a Debian package has wrong Categories: Chat
It can not display the app in the system's menu.
Should be: Network

Regards
pavroo

**Comment by sindresorhus** [comment]
This is already fixed in master: https://github.com/sindresorhus/caprine/commit/cb5e9f699abba2016b7b68141563de89d47e4b04#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R91
