### ISSUE TITLE
Scanned by Hybrid Analysis

### ISSUE THREAD

**Issue by antuketot76** [sindresorhus/caprine#570]
Latest scanned by Hybrid Analysis.
Complete analysis - [HERE](https://www.hybrid-analysis.com/sample/47b8bf872d2c841e212572400a3b69ce4135dbcc5a8dde45b79f965cc0b89516/5b8536077ca3e17bfa1bd563)

![image](https://user-images.githubusercontent.com/33280865/44722923-91902b00-ab09-11e8-9662-77791507d533.png)

**Comment by sindresorhus** [comment]
Please stop using awful anti-virus software...

**Comment by sindresorhus** [comment]
Duplicate of #555
