### ISSUE TITLE
Camera isn't recognised. 

### ISSUE THREAD

**Issue by vsimitsis** [sindresorhus/caprine#571]
Hi i just installed Caprine on my desktop using Linux Ubuntu 18.04.1. Everything seems to work (Thank you for that. Awesome work) except the camera on video calls. Caprine can't find my HD Pro Webcam C920 while it works everywhere else by default including the web version of messenger and facebook. Please let me know what other information about my system you need.

---

Caprine 2.17.0
Electron 2.0.8
linux x64 4.15.0-33-generic

**Comment by trmaphi** [comment]
@vsimitsis How did you install Caprine via snap?

**Comment by vsimitsis** [comment]
@trmaphi sorry for taking so long to respond. Thanks for your comment. I don't remember how i installed it back then, i think it was from Software center but not sure. I removed it and installed it the way you told me and works now perfectly. Awesome! :+1:

**Comment by maxowp** [comment]
1) go to Applications.
2) select "caprine". 
3) clic on "autorisation".
4) check/uncheck what you want. 

![Capture d’écran de 2019-03-29 15-01-07](https://user-images.githubusercontent.com/49069695/55238712-7a4b2480-5235-11e9-8ab6-6cdfc10605fa.png)

**Comment by trmaphi** [comment]
@sindresorhus I think this issue should be closed.
