### ISSUE TITLE
Can no longer disable notification pop ups on OSX

### ISSUE THREAD

**Issue by AN9999** [sindresorhus/caprine#572]
What happened to it? It's really annoying to have them pop up over the screen I'm working on. Thanks.
.........................
<img width="512" alt="screen shot 2018-08-28 at 9 59 40 pm" src="https://user-images.githubusercontent.com/40033116/44760703-08c7be00-ab0e-11e8-8043-956a17f76c06.png">

**Comment by dusansimic** [comment]
This is done through the mute notifications option in the menu bar. Go to `File -> Caprine Settings -> Mute Notifications`. Toggle the Mute Notifications option on or off to disable and enable notifications respectively.
