### ISSUE TITLE
JavaScript error when opening Caprine from a .desktop file when it is already running

### ISSUE THREAD

**Issue by DrDoctor13** [sindresorhus/caprine#573]
![image](https://user-images.githubusercontent.com/11695921/44790256-eca73980-ab6c-11e8-9332-42e12d4c1ed0.png)
Sorry for screenshot, I couldn't copy-paste inside the error box.

**Comment by khongi** [comment]
I have the same issue, this occurs when I click the pinned caprine icon in the taskbar instead of clicking on the tray icon. I'm using latest Manjaro KDE.

**Comment by CvX** [comment]
Does this issue still persist?

**Comment by mquevill** [comment]
I believe this issue is resolved in more recent versions. Opening from a .desktop file or from the terminal simply brings up the window and then stops the "new" process. Tested with Linux Mint 20.1 Cinnamon DE 4.8.6.

**Comment by dusansimic** [comment]
I agree, this seems to be fixed.
