### ISSUE TITLE
Workplace SSO not working

### ISSUE THREAD

**Issue by fstarkenberg** [sindresorhus/caprine#574]
With Single Sign On enabled for Workplace (SAML authentication) Caprine is not prompting me to authorise the app. I enter my email address in Caprine and Chrome opens mycompany.facebook.com/chat and automatically signs me in.
The Caprine window  just remains gray.

![image](https://user-images.githubusercontent.com/7057635/44835941-e4670100-ac35-11e8-9555-3f506f7b64ae.png)

---

Caprine 2.17.0
Electron 2.0.8
darwin x64 17.5.0

**Comment by sindresorhus** [comment]
There must be something faulty with the Workchat URL detection here: https://github.com/sindresorhus/caprine/blob/76349a8b7e2fa16e30d6da44e53b6782f8b9222a/index.js#L317-L333 It should already cover `mycompany.facebook.com/chat` though. Can you note down the first URL it opens in your browser? Maybe there's an URL than then redirects to `mycompany.facebook.com/chat`.

**Comment by fstarkenberg** [comment]
Looks like it opens `https://login.microsoftonline.com/` first, since that's the identity provider we're using for SAML authentication.

**Comment by Jonher937** [comment]
I have the exact same issue, we're also using MS Azure as SSO provider.
Checking what addresses are used when trying to browse companyname.facebook.com/chat in Chrome shows:
companyname.facebook.com/chat >
login.microsoftonline.com prompting for authentication >
companyname.facebook.com/chat

![Chrome inspect](https://i.imgur.com/AyMvHti.png)

What type of info would be usefull to help resolve this issue?
Thanks.

**Comment by SteveM2020** [comment]
Caprine is asking me for a workplaces address. I don't have one. I'm retired. What's the matter with this thing? I've used this for a few years and never had this problem before. It won't accept my username and password for Facebook.
