### ISSUE TITLE
Caprine requires High Performance GPU on Mojave

### ISSUE THREAD

**Issue by Joshie100** [sindresorhus/caprine#576]
Hey there, safter logging in, Caprine switches from integrated GPU to dedicated on my MBP 2018, thus draining significant battery. Could this be fixed?

**Comment by d235j** [comment]
[YakYak](https://github.com/yakyak/yakyak) for Google Hangouts seems to get around this by disabling acceleration. Does disabling acceleration seriously break things here?

**Comment by gklka** [comment]
I have the latest MacBook Pro 15” (2018). This machine runs 3-4 hours on battery with Caprine running, and 8-10 hours without it. The reason is the dedicated GPU. Please try to fix it somehow, it makes a huge difference for us!

**Comment by sindresorhus** [comment]
In the latest version, there's an option to disable hardware acceleration. https://github.com/sindresorhus/caprine/releases/tag/v2.21.0
