### ISSUE TITLE
No Flatpak install option for Linux users

### ISSUE THREAD

**Issue by yerbestpal** [sindresorhus/caprine#577]
I recently migrated to Fedora from Ubuntu. Though I appreciate that there are only so many distros you can support, Flatpak support would make installation much easier for many users, as well as increase user base.

**Comment by sindresorhus** [comment]
It needs to be supported by `electron-builder` first. See: https://github.com/electron-userland/electron-builder/issues/3212

**Comment by sindresorhus** [comment]
Going to pass on Flatpack because of http://flatkill.org/

**Comment by TamasBarta** [comment]
The problem with flatkill.org is that most of its complaints are about packagers not the format itself. Letting a project die from starvation (no packages distributed in its library) because of a random website doesn't help it improve. Also I saw Caprine on Snapcraft and I don't know if you're the packager or someone else did it for you, but every single discussion I came across about flatkill.org agrees that Snap is ever worse. If I make a snapkill.org, will you stop supporting the packaging of Caprine in Snap?
No offensive intentions in my comment, I love you made Caprine, but it looks like the discussion around Flatpak and Snap is hacked with money (Cannonical), and bullshit like flatkill.org, an anonymus random manipulative piece of text on the internet.

**Comment by yerbestpal** [comment]
I agree that it is a hasty decision ie flatkill.org, but I can understand if you don't want to cater to yet _another_ packing format for Linux, since the app is very well supported outside of Flatpak.

**Comment by zer09** [comment]
@sindresorhus please add support for flatpak

**Comment by yerbestpal** [comment]
@zer09 doubtful that anything will come of that since the issue is closed. I would be interested in maintaining a Flatpak of Caprine, though I have zero experience in it. Once I have more time, I will look into it.

**Comment by TheEvilSkeleton** [comment]
@yerbestpal in case you're interested, I create a flatpak: https://github.com/TheEvilSkeleton/com.sindresorhus.Caprine

I based it from [com.wire.WireDesktop.yml](https://github.com/flathub/com.wire.WireDesktop/blob/master/com.wire.WireDesktop.yml), so all my thanks goes to them for making my life much easier.

Anyway, just run:

```console
git clone https://github.com/TheEvilSkeleton/com.sindresorhus.Caprine.git ~/com.sindresorhus.Caprine
git clone https://github.com/flathub/shared-modules/tree/master ~/com.sindresorhus.Caprine/shared-modules
cd ~
flatpak-builder --force-clean --install-deps-from=flathub --install --user build-dir com.sindresorhus.Caprine.yml
```

And you should have the flatpak running.

I'm not planning to publish it in Flathub as I am not planning to maintain it anytime soon, but just letting everyone know that I'll be keeping this flatpak so if anyone wants to maintain it, they are free to do so.

**Comment by TheEvilSkeleton** [comment]
> Going to pass on Flatpack because of http://flatkill.org/

(Now https://flatkill.org/2020/)

That article is a legit shitpost and it's spread with FUD.

> Almost all popular apps on Flathub still come with filesystem=host or filesystem=home permissions, in other words, write access to the user home directory (and more) so all it takes to escape the sandbox is trivial echo download_and_execute_evil >> ~/.bashrc. That's it.

> Almost all popular apps on Flathub still come with filesystem=host or filesystem=home permissions

This is completely false. Steam, Discord, Chrome and Spotify don't come with those permissions, and they're probably the most popular programs.

> Gimp

They're planning on fixing it: https://github.com/flathub/org.gimp.GIMP/pull/74#issuecomment-716149065, and then again, developers use GIMP very extensively, thus requiring more permissions.

> VSCodium, PyCharm

Seriously? Those are IDEs. Why would one just unironically restrict an IDE?

> [...] are still not sandboxed.

That makes no sense. All programs are sandboxed and there's no option to remove the sandboxing.

> echo download_and_execute_evil >> ~/.bashrc.

That's a fair point, but that almost never happens with popular programs, unless someone can prove me wrong.

> Flatpak apps and runtimes STILL contain long known security holes

Those are fair points, but he's targeting Flatpak when it's obviously a packager issue.

---

This post was made to hate on Flatpak just for the sake on hating.

**Comment by dusansimic** [comment]
@TheEvilSkeleton I agree that most of the problems with outdated libraries and no security patches is the packagers fault, not formats. I also agree that Flatpak does a lot of good, I use it myself. However, flatkill.org is not really the reason we don't want to support it. The main, and probably the only reason, is that it's not supported by [Electron Builder](https://www.electron.build/). We want to have a clean pipeline and run builds that are easy to maintain and debug (which still proves to be a challenge if you're building for 5 targets). Until Electron Builder adds Flatpak support, we won't consider adding it.

Anyone is however welcome to make their own builds and even share them with everyone else! For example, we're not maintaining the Arch package.

Again, we personally don't have anything against Flatpak, we just don't want to maintain our scripts for building the Flatpak package.

**Comment by TheEvilSkeleton** [comment]
@dusansimic what are your thoughts on using something like [electron-installer-flatpak](https://github.com/endlessm/electron-installer-flatpak) in the meantime? I don't know much about it because I'm pretty new in Electron, but it might be useful.

**Comment by dusansimic** [comment]
@TheEvilSkeleton thanks for the link. As I said, we are trying to stick to Electron Builder but electron-installer might be useful for third party package, not an official one. I can see that it uses an outdated base package for electron (io.atom.electron.BaseApp) while the latest one is org.electronjs.Electron2.BaseApp. I'm not sure what's the difference and which version of electron do they actually run but if anyone has any input on this it would be very welcome!

**Comment by TheEvilSkeleton** [comment]
@dusansimic good news! https://github.com/electron-userland/electron-builder/pull/5711#event-4571578474

I don't know much about Electron, but this might interest you.

**Comment by dusansimic** [comment]
> good news! electron-userland/electron-builder#5711 (comment)

Thanks @TheEvilSkeleton for this! I'm sorry this waited for so long but I didn't have much free time and I first wanted to learn a bit more about flatpak packaging. I've made my own flatpak manifest for Caprine [1] that seems to work. I'm not sure we can add Caprine to Flathub without making our own manifest but you seem to be more experienced in making flatpak packages than I am 😊. If you find some time, please check out my manifest. You can comment on it in an issue on the mainfest repo. It's based on the instructions for building pacakges for Electron apps [2]. I would prefer building Caprine for the package than reusing other packages files like you did in your own manifest however thank you for the contributions you made so far 😁!

[1] https://github.com/dusansimic/flatpaks/tree/main/com.sindresorhus.Caprine
[2] https://docs.flatpak.org/en/latest/electron.html

**Comment by TheEvilSkeleton** [comment]
@dusansimic looks good to me so far. I took a look yesterday and I was going to mention migrating from appdata.xml, but I saw the latest commit which does that, so that's really good.

Have you tried locally verifying if it works or not? You can use [fp-build](https://github.com/lionirdeadman/fp-build/) script to test everything locally.

**Comment by TheEvilSkeleton** [comment]
Just FYI for anyone reading through this issue, Caprine is now available on [Flathub](https://flathub.org/apps/details/com.sindresorhus.Caprine)!

**Comment by Danik1601** [comment]
> Just FYI for anyone reading through this issue, Caprine is now available on Flathub!

@sindresorhus, much appreciated, sir!

Please take a look at the https://github.com/sindresorhus/caprine/pull/1834. 
And please consider adding a Flathub link on https://sindresorhus.com/caprine/ next to or instead of download button.
