### ISSUE TITLE
Sponsoring Project

### ISSUE THREAD

**Issue by sammarcus** [sindresorhus/caprine#581]
Hi Sindre,

I know that you're active on Patreon but was curious if there were any other ways to financially sponsor your work. I couldn't find you on Venmo; do you have another preferred payment platform (PayPal, etc?)

Posting as a public issue instead of an email so it's easier for others to quickly find this info as well ☺️

Thank you!

**Comment by sindresorhus** [comment]
Thanks for asking. Besides [Patreon](https://www.patreon.com/sindresorhus), you can sponsor/donate here:

- [My PayPal](https://www.paypal.me/sindresorhus)
- [BuyMeACoffee.com](https://www.buymeacoffee.com/sindresorhus)
- Bitcoin (BTC): 18h9q67KByyEWb7cAQbq8fDSZJqF4aeVMY
- Litecoin (LTC): LZTqq2KdLzD1xKXEPrEmRXSVrJwsT9VsJ1
- Ethereum (ETH): 0xc55d3d86Fb9E52613EFD7156DDd9eff8a1e6C199

**Comment by sammarcus** [comment]
Perfect! Thanks so much 😃 🙏
