### ISSUE TITLE
Chat title not aligned vertically on macOS

### ISSUE THREAD

**Issue by simgust** [sindresorhus/caprine#586]
The title of the chat is not aligned correctly vertically. It’s way too high up.

<img width="915" alt="skjermbilde 2018-09-17 kl 11 03 13" src="https://user-images.githubusercontent.com/6162667/45614282-4ebad680-ba69-11e8-805f-f4bef37331a8.png">

**Comment by jonjesbuzz** [comment]
The "Active x ago" label is back
