### ISSUE TITLE
Typing @ switches to the next conversation

### ISSUE THREAD

**Issue by sp00x** [sindresorhus/caprine#592]
Typing @ seems to just switch to the next conversion/person/group.. Often end up trying to address someone in a group and writing the message in the next  conversation instead..

@ on this keyboard is AltGr + 2 (Norwegian keyboard), if that makes it clearer what's going on....

---

Caprine 2.18.0
Electron 2.0.8
win32 x64 6.1.7601

**Comment by emileber** [comment]
Duplicate of https://github.com/sindresorhus/caprine/issues/539

**Comment by sp00x** [comment]
@emileber  Oops, searched but didn't find it. Sorry. Closing this one.

**Comment by emileber** [comment]
No worries, I just have the same issue and knew it already existed! 😉
