### ISSUE TITLE
Does not work with 2FA

### ISSUE THREAD

**Issue by AdrianTP** [sindresorhus/caprine#596]
I use a Yubikey as my U2F for Facebook (and Messenger).

Caprine seems to have a problem with this.

Screenshot: https://snag.gy/g1WVHD.jpg

It does not recognise my Yubikey (makes sense, since it's not Chrome and thus lacks the required plugin). Clicking on "Use a different method" opens a new browser window to facebook.com, rather than taking me through the usual process of using my fallback (Google Authenticator).

Franz and Goofy both handled this elegantly by simply loading the appropriate next step within the app window.

I'm trying out several options side-by-side to see what I like, and it looks like (for now, at least) Caprine gets culled from the running a bit early because I cannot even use it.

☹️

**Comment by P-Odziomek** [comment]
Still does not work.
It is impossible to log in with Caprine when U2F key is configured and required. I'm using Feitian ePass FIDO with my Facebook account.
