### ISSUE TITLE
Tray icon needs rework or option to turn off

### ISSUE THREAD

**Issue by Jimi-James** [sindresorhus/caprine#60]
I have a few problems with the tray icon:
-The show/hide right-click menu is extremely cumbersome compared to what most other programs do: click to hide; click again to show.
-There is no start-minimized option (and I mean minimized to tray, not as a minimized window).
-The icon doesn't change when there are unread messages, making it almost pointless as I still have to manually show the messages window to check after I've been away from the computer.

Because of these problems, I actually currently get a much better tray icon out of using alltray with the -H option. However, since I can't turn caprine's icon off, that leaves me with 2 icons. Because of that, I'm stuck on the seemingly abandoned other unofficial Messenger (https://github.com/Aluxian/Facebook-Messenger-Desktop) because it does not have a tray icon, making alltray viable.

**Comment by sindresorhus** [comment]
> The show/hide right-click menu is extremely cumbersome compared to what most other programs do: click to hide; click again to show.

That's exactly what you can do in the latest version. https://github.com/sindresorhus/caprine/commit/4c793d6d2c713471daba9e6494a8801e1a6970d4

> There is no start-minimized option

That's because you can do that in the OS. No need for an option in every single app.

> The icon doesn't change when there are unread messages, making it almost pointless as I still have to manually show the messages window to check after I've been away from the computer.

There are still notifications, though. I don't think it's possible to dynamically change the tray icon, but you could always open an issue on https://github.com/atom/electron. I would be happy to add it if possible.

**Comment by Jimi-James** [comment]
Oh. I should've checked the newest version, then.
>That's because you can do that in the OS. No need for an option in every single app.
I can do that in the OS? How? I've never heard of that feature.

**Comment by sindresorhus** [comment]
I was talking about Windows. No idea how things work on Linux.

**Comment by Jimi-James** [comment]
So, can you please work on adding that feature? Even if I was on Windows, I would not have been OK with just minimizing the window to the taskbar.

**Comment by Jimi-James** [comment]
Sorry for taking a while to reply on this one, but:
>There are still notifications, though. I don't think it's possible to dynamically change the tray icon, but you could always open an issue on https://github.com/atom/electron. I would be happy to add it if possible.

It looks to me like it is possible to dynamically change the icon, though for a time it seemed like it wasn't: https://github.com/atom/electron/issues/1473
So, I can open a new issue for it if you want (please say so if that's the case), but I definitely need the tray icon to change when there's an unread message so that I can leave my computer and miss notifications without missing the messages.

**Comment by sindresorhus** [comment]
> So, can you please work on adding that feature?

No, but see: https://github.com/sindresorhus/caprine/issues/64.

> It looks to me like it is possible to dynamically change the icon

It's possible to change it dynamically, true, but it accepts a path, not a buffer. So you would have to write an image to disk whenever the count changes, which is suboptimal. I suggest you open an issue on Electron for adding support for `tray` to accept an image buffer in addition to a path. That would make what you're asking a lot simpler. Feel free to open a new issue here for it after opening the Electron issue and make sure to cross-link them.

**Comment by Jimi-James** [comment]
Suboptimal is better than nothing. I have plenty of scripts that write something to disk. Why don't you plan to implement that for now, and open an issue about changing the buffer yourself? I don't know enough about these two projects to explain that properly, and you do. How do you not agree that only having notifications but not having a way to notice them after those brief few seconds is much more supoptimal?
