### ISSUE TITLE
Export conversation

### ISSUE THREAD

**Issue by Eloar** [sindresorhus/caprine#602]
_That is Feature Request (proposal)_

It would be quite useful feature to be able to export conversation as file either text or image.

**Comment by gklka** [comment]
I don’t think it’s possible, since Facebook provides threads in parts, and exporting a conversation would mean to go through all the older fragments one by one. This is a bigger task compared to the lightweight nature of Caprine.

**Comment by sindresorhus** [comment]
Maybe if the Facebook Messenger API can do this: https://developers.facebook.com/docs/messenger-platform/send-messages

**Comment by dusansimic** [comment]
This feature is available through Facebook Download Your Information page (https://www.facebook.com/help/212802592074644/?ref=u2u). It doesn't download just one conversation but all of the conversations and only the messages that are included in the time span. It might be a bit over the top for some people but it is possible to download the conversations with the media files included (sound and photos). Is this what you were looking fore or is it something else?

**Comment by spoorun** [comment]
> This feature is available through Facebook Download Your Information page (https://www.facebook.com/help/212802592074644/?ref=u2u). It doesn't download just one conversation but all of the conversations and only the messages that are included in the time span. It might be a bit over the top for some people but it is possible to download the conversations with the media files included (sound and photos). Is this what you were looking fore or is it something else?

Download your data is useful.

I'd suggest that this request is more a way to export or sync messages in a more usable manner, and regularly (rather than having to do an entire 'download your data' request and then receive it).

**Comment by dusansimic** [comment]
> Caprine is feature complete. However, we welcome contributions for improvements and bug fixes.

This is a quote from the project readme. I linked Download Your Information because there is no plan for adding this feature to the project. If someone is interested in adding it, we welcome contributions but we won't work on it ourselves.
