### ISSUE TITLE
Conversations appearing as unread after restart

### ISSUE THREAD

**Issue by ghost** [sindresorhus/caprine#603]
I'm in Windows 10 LTSB 2016 and have the problem that whenever I restart Caprine, whatever conversations that Caprine marked as read reappear as unread. Only after I go on facebook (where the conversations also appear as unread) and read them, does the status save.

**Comment by yenson-lau** [comment]
This also happens to me on Windows 10 and Ubuntu 18.04

**Comment by LogX7** [comment]
+1 ... i'm on caprine 2.28.0 on linux mint 19

**Comment by JoniVR** [comment]
Do you happen to use the "Block Seen Indicator" feature? 
I'm getting this on my phone too (when I switch to my phone the convo's are unread), but I think that's because it's blocking the seen indicator.
