### ISSUE TITLE
Typing indicator is white in dark mode

### ISSUE THREAD

**Issue by Fisher26** [sindresorhus/caprine#604]
When someone is typing, the indicator has a huge white rectangle around it. ![Image of bug](https://i.pics.rs/a1MIT.png)

**Comment by saikksub** [comment]
@Fisher26 
I am able to view normal indicator
<img width="194" alt="screen shot 2018-10-09 at 6 03 34 pm" src="https://user-images.githubusercontent.com/35134207/46669727-ea191480-cbed-11e8-96db-fd3049db1cfc.png">

Can you share setups to reproduce this issue?

**Comment by Fisher26** [comment]
Basically update MacOS to Mojave and set the dark mode, only two things that have changed, worked just fine beforehand.
