### ISSUE TITLE
Best App for Windows But

### ISSUE THREAD

**Issue by dudusandi** [sindresorhus/caprine#607]
Best App for Windows But doesnt have notification, only sounds.

**Comment by CvX** [comment]
I've tested notifications the latest version (2.28.0) on Windows (10) and they work.
Could you confirm whether or not you still have this issue?

![screenshot 2019-02-18 10 19 29](https://user-images.githubusercontent.com/66961/52940548-219b8880-3367-11e9-8a3e-4325ce0892e5.png)

**Comment by dudusandi** [comment]
In the lastest version works great the notifications. Thanks. Best app!
