### ISSUE TITLE
tray icon

### ISSUE THREAD

**Issue by filipstojakovic** [sindresorhus/caprine#609]
Is there any way to close massenger to tray? Also i get this exception.

![screenshot_2018-10-10_19-56-38](https://user-images.githubusercontent.com/32577154/46755974-b1993980-ccc6-11e8-9862-638b5b7f6f42.png)

---

Caprine 2.18.0
Electron 2.0.11
linux x64 4.14.74-1-MANJARO

**Comment by CvX** [comment]
@filipstojakovic Is this issue still present in the latest version (2.33.1)?

**Comment by dusansimic** [comment]
I think this was fixed in one of past releases. Please update to the latest version of Caprine to get all the fixes.
