### ISSUE TITLE
When resizing, text box resizes too small to use

### ISSUE THREAD

**Issue by cwilli34** [sindresorhus/caprine#61]
I am using Caprine on Manjaro Linux, Cinnamon Desktop.  I have this issue with MessengerforDesktop, and Caprine, that if you resize the width of the window smaller all the icons (add picture, choose stickers, GIF, send money, etc), or the space where they should be, shove the text box so small that horizontal and vertical scrollbars actually show up, and when the window is about 300px wide it leaves the text box like 20px wide.  I have attached a screenshot.
![screenshot from 2016-03-08 15-47-46](https://cloud.githubusercontent.com/assets/9610352/13616740/34083b22-e549-11e5-9811-8aa82d818511.png)

**Comment by phamdaniel** [comment]
I'm going to close this as this was fixed on Facebook's end.
![image](https://cloud.githubusercontent.com/assets/3745612/14761853/ca42df52-0939-11e6-8971-7d0a1551ef30.png)
