### ISSUE TITLE
Notifications do not remain in the notification centre (OS X El Capitan 10.11.6)

### ISSUE THREAD

**Issue by TechGizmo** [sindresorhus/caprine#611]
Caprine Version 2.19.0 (2.19.0.945)
OS X El Capitan 10.11.6

When a new message is received, the notification banner fades in from the top right of the display (as expected) but when it fades out I cannot find it in the notification centre (as it appears and disappears right after in the notification centre) even though I have not read the message. The dock badge still works (by showing a 1 in a red circle). I would be happy to provide more information if necessary to help address this issue. Thanks!

Edit: The issue is very similar to a whatsapp desktop notification bug (that has since been fixed). The video link can be found here https://www.youtube.com/watch?v=6pkQQ7eXmoE

**Comment by dusansimic** [comment]
Stale and notifications are removed from Messenger website so it doesn't work either way.
