### ISSUE TITLE
Gtk-Message: Failed to load module "canberra-gtk-module" on Ubuntu 18.04 (snap package)

### ISSUE THREAD

**Issue by PiotrDabrowskey** [sindresorhus/caprine#615]
Trying to start caprine installed by snap fails and results in:

```bash
piotr@dab:~$ caprine
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Trace/breakpoint trap (core dumped)
```

Ubuntu version:
```bash
piotr@dab:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
caprine version:
```bash
piotr@dab:~$ snap info --verbose caprine
name:      caprine
summary:   Caprine
publisher: Sindre Sorhus (sindresorhus)
license:   unset
description: |
  Caprine is an unofficial and privacy focused Facebook Messenger app with many useful features.
commands:
  - caprine
notes:               
  private:           false
  confinement:       strict
  devmode:           false
  jailmode:          false
  trymode:           false
  enabled:           true
  broken:            false
  ignore-validation: false
snap-id:      UluDLd64Rry6IYTesGapYwu8sfuZmwbu
tracking:     stable
refresh-date: yesterday at 17:41 CEST
channels:                     
  stable:    2.19.0 (4) 109MB -
  candidate: ↑                
  beta:      ↑                
  edge:      ↑                
installed:   2.19.0 (4) 109MB
```

**Comment by sindresorhus** [comment]
Sounds related to https://github.com/electron-userland/electron-builder/issues/2981

You could also try some of the tips in https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

**Comment by PiotrDabrowskey** [comment]
Thanks! Installing `canberra-gtk-module` from apt does not solve the problem as, if I understand correctly, snaps packages uses snaps as dependencies (`core`, `core18` and so on) instead of system packages. Anyway it looks like a wider problem in electron, related also to this: https://github.com/electron/electron/issues/13767

I'll just wait for the fix (keeping eye on the related issues) and close this as soon as it's fixed, but feel free to close it now if you want.

**Comment by PiotrDabrowskey** [comment]
Recently I did a reinstall (`sudo snap remove caprine && sudo snap install caprine`) and suddenly it started working properly. Back then, when this issue affected me, I was trying the reinstall a few times during time span of a week, and it helped only until the first run - closing and reopening caprine resulted in the error (each reinstall allowed to open the app once, but forced me to log in every time).

I'm closing this issue as I'm not aware of any other users affected by this.
