### ISSUE TITLE
Clicking images doesn't do anything

### ISSUE THREAD

**Issue by ralphSQ** [sindresorhus/caprine#616]
When i click on images, the app doesn't open the image. Also, when hovering on images, the mouse pointer does not change to the hand thing.

When trying to open an image in the sidebar > shared photos tab, the mouse pointer changes to a hand but clicking on an image doesn't do anything either. 

I'm on windows 10 1083.

---

Caprine 2.18.0
Electron 2.0.8
win32 x64 10.0.17134

**Comment by dusansimic** [comment]
This seems like an old issue and this works now in the latest version. Please update to the lates version of Caprine. If this issue persists, feel free to comment on this issue.
