### ISSUE TITLE
Notification popover doesn't hide automatically after 2.20.0 (macOS)

### ISSUE THREAD

**Issue by karmeleon** [sindresorhus/caprine#617]
When I get a message, I see a notification banner as expected, but it has a button labeled "Close". Also, these notifications don't slide away after a few seconds like they used to. Instead, they just pile up on the side of my monitor. They should not have this behavior.

---
Caprine 2.20.0
macOS 10.14

**Comment by janosorcsik** [comment]
In the System Preferences open the Notifications category and try to change Caprine alert style to banner.

**Comment by karmeleon** [comment]
Ah, yeah, that did it. Wonder why it got changed to that in the first place? Thanks!

**Comment by janosorcsik** [comment]
I think this is the default behavior of Caprine.

https://github.com/sindresorhus/caprine/blob/e8b194f00938b544578e860b2091518586e3676f/package.json#L72

**Comment by karmeleon** [comment]
Ah ok, it was just different than it used to be. I prefer banner alerts for anything other than important notifications like calendar events, but to each their own :)
