### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Mogy11** [sindresorhus/caprine#624]
Hello,Caprine for Win 10 is working fine but just I do not getting the notification in the corner I just get the sound and in the taskbar app icon blinking...So in the Settings I do check Desktop Notification Enabled but I do not getting notification...So can you help me with that ? Thanks in advance,app is super fast,smooth

---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.17134

**Comment by bogdan-calapod** [comment]
Same here - notifications enabled, everything seems that should work properly, but no action center notifications.

**Comment by CvX** [comment]
Closing this issue for now. Please let us know if the issue is still present in the latest version (2.33.1).

**Comment by hamzabou21** [comment]
I'm still facing the same problem
