### ISSUE TITLE
Automatically disable hardware acceleration when on battery

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#625]
Requires https://github.com/electron/electron/issues/1615

**Comment by whitecrownclown** [comment]
@sindresorhus https://github.com/electron/electron/issues/1615 seems to be solved. I'm getting the `on-battery` event, however, how would we disable hardware acceleration without restarting `Caprine` afterwards? Do we just prompt the user with a message and then let him decide?

**Comment by sindresorhus** [comment]
> how would we disable hardware acceleration without restarting `Caprine` afterwards?

Someone needs to open an issue on [Electron](https://github.com/electron/electron) requesting the ability to change hardware acceleration without having to restart. Prompting would be annoying and not much better than just manually changing and we can't automatically change as the user might be in the middle of writing a message.

**Comment by sindresorhus** [comment]
Electron declined https://github.com/electron/electron/issues/17011, so I don't see this being feasible to implement.
