### ISSUE TITLE
Notifications freeze and title missing and click mistake

### ISSUE THREAD

**Issue by luxkyluke** [sindresorhus/caprine#626]
I'm on macOS High Sierra and since the last Caprine update all the notifications pop in corner right but won't disappear automatically by themselves, I have to close them one by one.
Moreover, the notification's title is always "Caprine", it doesn't tell me who's talking to me. Content extract message and picture are ok. 
And the click event doesn't open the right conversation, i think this problem is linked to the notifications stack order.

**Comment by willashley23** [comment]
I also have this problem, the notifications are persistent. 

I also have noticed that reading a message in Caprine does not seem to update the read status in the native Messenger app, so if I chat with someone in Caprine, then switch to my phone, I'll have badges on my Messenger app, and it will be marked as _unread_ inside the app itself. Is this a matter of a missing API to communicate that a message has been read?

**Comment by sindresorhus** [comment]
// @janosorcsik

**Comment by freewill404** [comment]
Can confirm the same problem.

**Comment by janosorcsik** [comment]
@sindresorhus I send a PR to change the default alert style to the banner. #631 

@luxkyluke Please show a picture or video about the title and click problem. I am on High Sierra too, but I don't see anywhere Caprine in the title.
<img width="370" alt="kepernyofoto 2018-10-28 - 19 13 05" src="https://user-images.githubusercontent.com/4984853/47620051-e76f5800-dae5-11e8-9e49-7b8f1aa0012e.png">
Only in the Notification Center, but it is not a problem.
<img width="347" alt="kepernyofoto 2018-10-28 - 19 15 27" src="https://user-images.githubusercontent.com/4984853/47620054-eb9b7580-dae5-11e8-8da6-ceddd455bdc3.png">
And after I clicked on notification, Caprine always jumped to the right people.

@willashley23 Did you enable the block seen indicator in the menu?

**Comment by luxkyluke** [comment]
@janosorcsik in fact, the problem seems to only append with conversations.

<img width="358" alt="capture d ecran 2018-10-28 a 19 48 12" src="https://user-images.githubusercontent.com/9282904/47620545-70d55900-daeb-11e8-8c67-7c213b6c051d.png">

<img width="332" alt="capture d ecran 2018-10-28 a 19 51 03" src="https://user-images.githubusercontent.com/9282904/47620531-5a2f0200-daeb-11e8-9581-1746a010b65b.png">

**Comment by dhharris** [comment]
Also happens in macOS mojave

**Comment by apenney** [comment]
Came to see if anyone else has reported this.  Same thing, I see notifications in mojave that just stick around forever.
