### ISSUE TITLE
Alt-Shift shows the menu

### ISSUE THREAD

**Issue by walkero-gr** [sindresorhus/caprine#628]
Hello there,
I have an issue with the Alt-Shift keyboard combination, which enables the menu of the program, which also I use for layout change of the keyboard. This is happening at least on Linux. Is there a way to disable it?

**Comment by sindresorhus** [comment]
Caprine doesn't register the shortcut Alt+Shift.

**Comment by walkero-gr** [comment]
Thank you for your reply. I believe it has to do with the following issue of electron
https://github.com/electron/electron/issues/11106
