### ISSUE TITLE
Dark mode + vibrancy broken on app restart

### ISSUE THREAD

**Issue by neegool** [sindresorhus/caprine#633]
When I toggle dark mode + vibrancy while the app is open, it looks like this:
<img width="641" alt="screen shot 2018-10-31 at 3 49 55 pm" src="https://user-images.githubusercontent.com/2795476/47773373-ce081f00-dd24-11e8-8064-e4ccf7a78747.png">

But when I restarted the app, it looks like this:
<img width="634" alt="screen shot 2018-10-31 at 3 49 41 pm" src="https://user-images.githubusercontent.com/2795476/47773399-dd876800-dd24-11e8-9314-4301b465a2b5.png">

re-toggling Vibrancy fixes the problem. The problem does not appear to affect Light mode.

I'm currently using 2.21.0.

**Comment by sindresorhus** [comment]
// @phoomparin

**Comment by neegool** [comment]
**UPDATE:** I've identified that this problem is being caused by the workaround for the white flash on startup. Commenting out the following line in `browser.js` eliminates the issue:

```
// Prevent flash of white on startup when in dark mode
// TODO: find a CSS-only solution
if (config.get('darkMode')) {
	document.documentElement.style.backgroundColor = '#192633';
}
```
