### ISSUE TITLE
Visible scroll bar when chat buttons are below the input field

### ISSUE THREAD

**Issue by khongi** [sindresorhus/caprine#636]
Resize the window width so that the "choose picture", "insert sticker" etc. buttons are below the "Type a message..."
![scrollbar](https://user-images.githubusercontent.com/11983684/47778191-96827e00-dcf6-11e8-8ea8-d01d1401bc28.PNG)

---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.17134

**Comment by CvX** [comment]
Closing this issue for now. Please let us know if the issue is still present in the latest version (2.33.1).
