### ISSUE TITLE
Seen Indicator incorrectly shows message time instead of Seen time

### ISSUE THREAD

**Issue by WalidHella** [sindresorhus/caprine#642]
Sometimes, the seen indicator shows the time of sending the message and not the actual Seen time. I logged in to Facebook on my browser to and saw that the Seen time is different. 
I'm not sure how to reproduce the bug, though.

**Comment by CvX** [comment]
Caprine doesn't change the "Seen" time. If there was/is any bug, I'm pretty sure it's on the [Messenger's](https://messenger.com) side. I'm closing this, but please reopen this if you happen to stumble upon this issue again and if you confirm that it doesn't affect https://messenger.com.
