### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by snembrini** [sindresorhus/caprine#643]
My own camera will not be recognized and will not start
---

Caprine 2.21.0
Electron 3.0.6
linux x64 4.15.0-38-generic

**Comment by vanushwashere** [comment]
My too
Latest Caprine installed by snap on Kde Neon with all updates

**Comment by sindresorhus** [comment]
This should be fixed in the latest version. The problem was https://github.com/sindresorhus/caprine/commit/d13c79251dce0e524e8d02028fd5c067243467d3.
