### ISSUE TITLE
dark mode - file transfer display bug

### ISSUE THREAD

**Issue by rtpHarry** [sindresorhus/caprine#645]
New one today, sending a text file in dark mode gives you a poor display:

![image](https://user-images.githubusercontent.com/1038062/48046934-cc2cd880-e1c8-11e8-9ccd-ee1903726a14.png)

Fixed it with this snippet:

```
html.dark-mode ._2zl5 {
    background-color: transparent;
}
```

As you can see the dark mode is having a go at styling it but something further up is jumping in and resetting the background colour:

![image](https://user-images.githubusercontent.com/1038062/48047166-c5529580-e1c9-11e8-8d3c-58a8a5c2f5ba.png)

So with my snippet you end up with this:

![image](https://user-images.githubusercontent.com/1038062/48047188-d7cccf00-e1c9-11e8-8411-3002890f18fc.png)

**Comment by rtpHarry** [comment]
Oh but wait, it leaves a hidden remove button in the top corner:

![image](https://user-images.githubusercontent.com/1038062/48047339-5c1f5200-e1ca-11e8-8e3b-225ba114cc94.png)

Which is provided by a Messenger sprite sheet:

![image](https://user-images.githubusercontent.com/1038062/48047381-71947c00-e1ca-11e8-8d18-b3adef10df2a.png)

Has "dark mode remove button" been solved elsewhere in the app that a snippet can pulled from?

One alternative is to switch the snippet around and force the backgrounds to be all white, but then you have to replace the text colours inside as well and I'm not sure if there are any variations then.

**Comment by rtpHarry** [comment]
@CvX great work with #757! 

I was about to close this issue out but I think maybe you missed the hidden cancel button like I did when I was working on this? 

Looking at your "Tweak attached files" screenshots I can't see the cancel button in any of them.

**Comment by CvX** [comment]
Please correct me if I'm wrong, but the "Remove attachment" icon is supposed to show up only on hover and it works in dark mode:

<img width="274" alt="screen shot 2019-02-16 at 22 33 39" src="https://user-images.githubusercontent.com/66961/52905494-28c57800-323b-11e9-98c2-57190eb954a7.png"> <img width="274" alt="screen shot 2019-02-16 at 22 33 43" src="https://user-images.githubusercontent.com/66961/52905493-282ce180-323b-11e9-8a5d-fdbadec035b9.png">

**Comment by rtpHarry** [comment]
Ah ok, my bad, guess this is done then! Great work.
