### ISSUE TITLE
Notification doesn't disappear MacOS Mojave

### ISSUE THREAD

**Issue by lauevrar77** [sindresorhus/caprine#650]
In MacOS Mojave, notification appears as usual MacOS notifications (up-right on the screen) but doesn't disappear at all. 
I always have to click on the close button that is really annoying.

**Comment by sindresorhus** [comment]
This should have been fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.21.0 Make sure you're on the latest version.

**Comment by lauevrar77** [comment]
I just checked and it's the version I have. But still have te problem.

**Comment by justin-robinson** [comment]
Same here but I'm on High Sierra. Running Caprine 2.21.0

**Comment by ChadMoran** [comment]
Seeing same on Sierra.  Caprine 2.21.0 (2.21.0.997)

**Comment by janosorcsik** [comment]
In the System Preferences open the Notifications category and try to change Caprine alert style to banner.

The fix is in the new version, but I think the old setting doesn't disappear from the Caprine setting file.

**Comment by kosma** [comment]
This fix really should be in README... I've been running a modified version of Caprine for a month (disabling the "reply" function) and I almost filed an issue about this (but Github's "related issues" thing led me here).
