### ISSUE TITLE
Titlebar theming on Windows

### ISSUE THREAD

**Issue by IdiosApps** [sindresorhus/caprine#652]
![image](https://user-images.githubusercontent.com/12559216/48347360-ff161700-e675-11e8-8a5b-072b514fb678.png)

Is it possible to theme the title bar to be dark (and make the text/buttons white)?

Maybe Windows supports this, as they have dark theming elsewhere (Windows 10):
![image](https://user-images.githubusercontent.com/12559216/48347473-3e446800-e676-11e8-8e50-503f445c1246.png)

**Comment by temannin** [comment]
It seems for Electron apps, the only way to get a Windows style menu bar without building it from scratch is to implement something like this:

[https://github.com/sidneys/electron-titlebar-windows](https://github.com/sidneys/electron-titlebar-windows)

This is not the native solution you're looking for but it seems to be the only option there is at the moment.

**Comment by sindresorhus** [comment]
There was an [Electron issue about this](https://github.com/electron/electron/issues/1582) years ago, but it never went anywhere. When https://github.com/electron/electron/issues/15316 is fixed, we could at least add an option to follow the system dark mode, which should (in theory) change the title bar.

Yes, Windows has a native dark mode: https://www.groovypost.com/news/preview-dark-mode-coming-windows-10-anniversary-update/

**Comment by jakobhviid** [comment]
Hey. This is the last thing that annoys me with dark mode on windows, so i looked a bit into it and found this:

https://www.npmjs.com/package/electron-titlebar-windows
![image](https://user-images.githubusercontent.com/4179396/59624293-abe9d280-9136-11e9-9bac-1241e2dfbceb.png)

I do not know enough about electron to validate if this is a viable alternative, and have to leave that to someone else.
The way i see it, only the top bar is missing the theming, and the rest can be achieved by hiding the menu bar:

![image](https://user-images.githubusercontent.com/4179396/59624474-1ef34900-9137-11e9-8860-aaecf936f46f.png)

**Comment by jakobhviid** [comment]
Also, here is an alternative where the github page and source code is actually available:

https://github.com/AlexTorresSk/custom-electron-titlebar

**Comment by MrScottyTay** [comment]
Anything happening with this?
