### ISSUE TITLE
Unread messages in conversation list (dark mode)

### ISSUE THREAD

**Issue by ilovefriedchicken** [sindresorhus/caprine#654]
**Problem:**
In the conversation list while running the light theme, Caprine lists unread conversations elegantly by showing them with a thicker bold font. However, in dark mode, each unread conversation is made blue which sometimes may give the wrong impression while using the application. 

For example, say there is only one unread conversation in the list. From a visual standpoint you may think that (at a glance) the blue highlighted conversation may be your current active conversation in the window, and so the user may think they are in a conversation with someone else when in fact the blue highlighted conversation is indicative of an unread message - not the current active chat.

This is a problem that I have noticed many of my friends running into after recommending this application to them for its dark mode. 

**Solution:**
Making the current active conversation box in the conversation list a darker shade to the rest of the items in a conversation list (like light theme), and giving a bold typeface to unread messages will go a long way in improving usability. 

Alternatively, a blue dot next to an unread conversation (in much the same way that dark mode Messages app on Mojave works) should suffice in being a visually clear indicator of an unread message.

**Comment by kornelt** [comment]
Absolutely this, the stock Messages app in mojave dark mode uses the blue highlight to show the current active conversation, so it's quite confusing
