### ISSUE TITLE
program very slow in some windows 7 machine

### ISSUE THREAD

**Issue by escoltajuverf** [sindresorhus/caprine#657]
probably an electron bug but im hoping there is a workaround for this issue

the issue seems similar to this bug 

https://github.com/electron/electron/issues/12895

**Comment by phylop** [comment]
I have this same issue on my Windows 7 machine.

**Comment by puerto-rico** [comment]
i found out the rolling back to the 2.18 snap on ubuntu 18.04 made the app work fast again.

**Comment by sindresorhus** [comment]
Closing as this is an Electron issue and we can't relly do anything about it.
