### ISSUE TITLE
Find Conversations does not perform any action on macOS Mojave 10.14.1

### ISSUE THREAD

**Issue by yqbk** [sindresorhus/caprine#658]
Neither shortcut cmd+k nor clicking Conversation > Find Conversation does work in Caprine 2.21.1 on my macOS Mojave 10.14.1. The same with Conversation > Search Conversation (cmd+f).

The only shortcut that works for me is File > New Conversation (cmd+n).

I tried to restart and reinstall Caprine but it hasn't solved the problem.

**Comment by sindresorhus** [comment]
The CSS class names probably changed and the selectors needs to be updated.

**Comment by yqbk** [comment]
It seems that it works when I enlarge the app. When the app window is small enough (instead of a full name with profile picture on the left only the picture is displayed) - it stops working.
