### ISSUE TITLE
Dark Menu on Ubuntu 18.10 with Yaru default theme

### ISSUE THREAD

**Issue by Skynet100Gaming** [sindresorhus/caprine#659]
Hi,

On Ubuntu 18.10 with the latest Caprine installed the main menu at the top is completely unreadable and incredibly dark it might have something to do with the new Yaru theme which Ubuntu now uses but an update to the software would be appreciated to make the main menu at the top readable. I would appreciate you trying Ubuntu 18.10 out with Caprine installed to see what I mean with the default theme or another tester to confirm the issue.

**Comment by sindresorhus** [comment]
This is an Electron issue: https://github.com/electron/electron/issues/15194

**Comment by CvX** [comment]
The electron issue has been fixed. Can we close this issue?

**Comment by Skynet100Gaming** [comment]
Yeah sure! If the issue is fixed which in this case it has I'll close this bug report. At least the Electron devs listened which is great!
