### ISSUE TITLE
Notifications don't work for me on El Capitan

### ISSUE THREAD

**Issue by mgol** [sindresorhus/caprine#66]
I'm on latest El Capitan (10.11.3 (15D21)) & Caprine 1.2.0. I see the badge & hear the sound when a new message arrives but there is no notification banner. When I go to System Preferences -> Notifications I don't even see a Caprine entry; I see lots of them for other apps.

I have Chrome notifications disabled but that shouldn't affect standalone Electron apps that use native system notifications (by default Chrome uses its own flavor not integrating well with the OS).

**Comment by sindresorhus** [comment]
Probably related to https://github.com/atom/electron/releases/tag/v0.37.2

> Fix notifications not showing.

I'll try to get out a new release soon.

**Comment by sindresorhus** [comment]
Does https://github.com/sindresorhus/caprine/releases/tag/v1.2.1 fix it?

**Comment by mgol** [comment]
It works now, thanks!
