### ISSUE TITLE
snap: Unable to use input method(ibus)

### ISSUE THREAD

**Issue by extraymond** [sindresorhus/caprine#661]
Hi! After yesterday's update, I'm no longer able to use input method in caprine.

os: ubuntu 18.04
caprine: 2.22.1 (9)

I believe the problem can be solved by launching the program using desktop-launch alone with one of the snap desktop-helpers (desktop-gtk or desktop-glib-only).

Remember to include desktop-legacy so the snap have access to input methods too.

**Comment by sindresorhus** [comment]
> Remember to include desktop-legacy so the snap have access to input methods too.

That is already included by default: https://www.electron.build/configuration/snap

**Comment by extraymond** [comment]
Thx!! Sorry to mention that it has been working for awhile. Haven't remember to report back XD. You can close this now.
