### ISSUE TITLE
Notification Flashing

### ISSUE THREAD

**Issue by Vexorify** [sindresorhus/caprine#662]
I have a Group Chat muted on Messenger but I still receive the little badge icon + the window flashing in the taskbar. The only way to disable that is to Mute Notifications through Caprine settings, but then that mutes my direct messages as well.  Is there anyway to disable that for muted conversations?

Picture reference: https://i.imgur.com/cP8mQcG.png

**Comment by dusansimic** [comment]
This happens because Caprine counts unread messages and displays the number in the indicator. I can make a PR to count only messages that are unread and unmuted @sindresorhus

**Comment by sindresorhus** [comment]
Sounds good

**Comment by whaevr** [comment]
Awesome! 😄 I updated today and this started happening. Good to see its already got a PR
