### ISSUE TITLE
Caprine keeps refreshing

### ISSUE THREAD

**Issue by regineblanco** [sindresorhus/caprine#665]
Hi, what's happening with Caprine? Every time I click on a chatbox on the left side, the app refreshes. I also can't react to a friend's chat anymore, I can't see that tiny hover button on a chat bubble.
---

Caprine 2.22.1
Electron 3.0.9
darwin 18.0.0
Locale: en-US

**Comment by z-ax** [comment]
Works fine for me on OSX.
