### ISSUE TITLE
responding to calls isn't working

### ISSUE THREAD

**Issue by LogX7** [sindresorhus/caprine#668]
OS : Linux Mint 19 - Cinnamon 3.8.9
Version : 2.21.1

when i get a call i click on respond and nothing happens

**Comment by drt0** [comment]
I'm having the same issue, it worked fine on around version 2.19

**Comment by piomar123** [comment]
Confirmed on Windows 10, version 2.23.0.
Current workaround is to call back which immediately joins the call.
