### ISSUE TITLE
Typing indicator looks odd with vibrance enabled

### ISSUE THREAD

**Issue by jrusinek** [sindresorhus/caprine#669]
The typing indicator in vibrance mode is not transparent

![captura de tela 2018-12-02 as 13 54 57](https://user-images.githubusercontent.com/271641/49340005-3e62d280-f63a-11e8-945f-b558484a1df4.png)

---

Caprine 2.22.1
Electron 3.0.9
darwin 18.2.0
Locale: pt-BR

**Comment by CvX** [comment]
Does this issue still occur on the latest version (2.28.0)?

**Comment by jrusinek** [comment]
It's fine now ❤️

**Comment by jrusinek** [comment]
![captura de tela 2019-02-23 as 09 29 30](https://user-images.githubusercontent.com/271641/53283957-b9291e80-374d-11e9-8ea8-4809fcb0ac90.png)

Still happening :(
