### ISSUE TITLE
Option to use native Apple emoji

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/caprine#672]
The Facebook emoji set looks terrible. The messenger app on iOS uses native Apple emojis. It would be great if Caprine could do this too

**Comment by felixfbecker** [comment]
Good idea. This selector gives all FB emojis on the page:
```js
document.querySelectorAll('img[src*="emoji.php"')
```
The URL for 😄 is `https://static.xx.fbcdn.net/images/emoji.php/v9/t71/2/16/1f604.png`. The basename of the path, `1f604`, corresponds to the Unicode codepoint of the emoji, `U+1F604`.

But Facebook also puts the real emoji directly into the `alt` property, so we can easily replace all emojis with:
```js
for (const img of document.querySelectorAll('img[src*="emoji.php"')) {
  img.replaceWith(img.alt)
}
```

![image](https://user-images.githubusercontent.com/10532611/49698685-623c9000-fbc7-11e8-8264-e62463240e1e.png)

Now these emojis look a bit mispositioned and small, so add a bit of styling:
```js
document.querySelectorAll('img[src*="emoji.php"').forEach(img => {
  const span = document.createElement('span')
  span.className = 'native-emoji'
  span.textContent = img.alt
  img.replaceWith(span)
})
```
```css
.native-emoji {
    font-size: 1.2em;
    display: inline-block;
    top: 0.12em;
    position: relative;
}
```

And voila:

![image](https://user-images.githubusercontent.com/10532611/49698672-328d8800-fbc7-11e8-9721-2eda864a1283.png)

**Comment by felixfbecker** [comment]
I'm unsure where the MutationObserver code for this would have to be added

**Comment by SolarLiner** [comment]
I would love for this to be the default for all platforms. I didn't like Facebook's previous set, but this one is even worse.

**Comment by felixfbecker** [comment]
Yeah I agree. It's reasonable for a website to have their own style, but a native app should always use native OS styles. The Windows emoji set looks amazing too.

**Comment by felixfbecker** [comment]
@sindresorhus any pointer where the code above would have to be added?

**Comment by sindresorhus** [comment]
@felixfbecker The MutationObserver should target the message container, which is `#js_1`. The code itself should be added in https://github.com/sindresorhus/caprine/blob/master/browser.js

**Comment by felixfbecker** [comment]
Hmm, I can't find any element on the page if I run `document.getElementById('#js_1')` in the console

**Comment by JoniVR** [comment]
@felixfbecker 
try 
```js
document.querySelector('#js_1');
```
