### ISSUE TITLE
Badge still showing unread count for muted chats 

### ISSUE THREAD

**Issue by paul-arthurthiery** [sindresorhus/caprine#674]
I'm currently running Caprine 2.22 on MacOS Mojave and there doesn't seem to be any option to hide the unread count badge for muted chats. 
This is kind of annoying and it would be great to hide it completely for muted chats !

**Comment by felixfbecker** [comment]
Yeah I have the same problem. It should just not be considered for the badge like in the mobile app.

Can I help somehow in setting up automatic releases so we don't need to wait for fixes in the future?

**Comment by dusansimic** [comment]
@felixfbecker I like that idea. There should be nightly since I'm still for stable builds. @sindresorhus any thoughts on this?

**Comment by sindresorhus** [comment]
This is fixed in the latest release.

Regarding nightly releases. I'm not super interested in having to maintain that, but if someone does a good PR, I would merge it.
