### ISSUE TITLE
Enable @channel expansion in group conversations

### ISSUE THREAD

**Issue by JonathanGin52** [sindresorhus/caprine#675]
It would be awesome if Caprine had a feature that would enable it to automatically expand `@here` and `@channel` alerts similar to the way [Slack](https://get.slack.help/hc/en-us/articles/202009646-Notify-a-channel-or-workspace) implements these features.

![image](https://user-images.githubusercontent.com/26397946/49708984-296cdd00-fc00-11e8-814c-182f5f6ed4b5.png)

**Comment by sindresorhus** [comment]
For this to work, it would have to be supported on the Messenger backend. We could potentially implement support for `@here` for people using Caprine, but that's very limiting, so not sure it's worth the effort.
