### ISSUE TITLE
emoticon

### ISSUE THREAD

**Issue by Mattrak** [sindresorhus/caprine#678]
Click on emoticon show blank window nothing appears

---

Caprine 2.22.1
Electron 3.0.9
darwin 18.2.0
Locale: fr

**Comment by Ahmad-AbdulAziz** [comment]
The same happened for me Whenever I try to use the emoticon it shows a blank window restarting the messenger fixes the problem however I still can't reuse the emoticons, I tried to reinstall the software multiple time.

---

Caprine 2.18.0
Electron 2.0.12
linux x64 4.19.6-1-MANJARO

**Comment by TheGum** [comment]
@Ahmad-AbdulAziz You can exit the blank screen by pressing F5 key.

**Comment by dusatvoj** [comment]
@Mattrak Same problem

**Comment by RaunoT** [comment]
Can confirm, same for me.

**Comment by Mattrak** [comment]
It is working normally today I don't know why, same version

**Comment by dusansimic** [comment]
Related to https://github.com/sindresorhus/caprine/issues/680
