### ISSUE TITLE
Caprine Hanges when I paste a picture into composer

### ISSUE THREAD

**Issue by Ahmad-AbdulAziz** [sindresorhus/caprine#679]
I tried to paste a picture (using clipman on manjaro) and it hangs, I didn't experience similar issues it just happened on it own  
---

Caprine 2.18.0
Electron 2.0.12
linux x64 4.19.6-1-MANJARO

**Comment by Ahmad-AbdulAziz** [comment]
![untitled](https://user-images.githubusercontent.com/24931147/49805297-7a461800-fd5d-11e8-8e39-abbf2279c664.png)

**Comment by Ahmad-AbdulAziz** [comment]
![untitled](https://user-images.githubusercontent.com/24931147/49805397-b0839780-fd5d-11e8-93c1-78f2298b4764.png)

**Comment by dusansimic** [comment]
Closing since issue is stale and the problem doesn't exist on the latest release. Try it and if the problem is still there, open a new issue.
