### ISSUE TITLE
Support for HiDPI

### ISSUE THREAD

**Issue by mmirkov** [sindresorhus/caprine#68]
Could you please include support for hidpi? The font looks quite small on Windows 10.

**Comment by forivall** [comment]
I think that's something that would need to be supported in electron, since electron does hidpi fine on macs.

**Comment by sindresorhus** [comment]
Yup. This is totally up to Electron. We're just using a browser window.

I would recommend opening an issue here: https://github.com/atom/electron

**Comment by mmirkov** [comment]
I've managed to fix this (Windows 10) by adding a "zoomFactor: 1.2," under "webPreferences" in index.js.
