### ISSUE TITLE
Emoji button bug

### ISSUE THREAD

**Issue by capngloval** [sindresorhus/caprine#681]
The emoji button puts caprine into a blank white or black screen with nothing visible. Not a big issue, but I wanted to mention it.

---

Caprine 2.22.1
Electron 3.0.9
linux 4.15.0-20-generic
Locale: en-US

**Comment by mikigal** [comment]
I have the same problem.

Caprine 2.22.1
macOS High Sierra

**Comment by mrwnmonm** [comment]
I have the same issue too.
macOS Mojave. 10.4

**Comment by dusansimic** [comment]
Related to https://github.com/sindresorhus/caprine/issues/680

**Comment by CvX** [comment]
Fixed in #941
