### ISSUE TITLE
"Reply to" icon missing 

### ISSUE THREAD

**Issue by filipruisl** [sindresorhus/caprine#682]
"Reply to" icon missing , the one among "react" and "more", next to the message bubble. 

<img width="258" alt="screenshot 2018-12-11 at 21 04 49" src="https://user-images.githubusercontent.com/33035240/49826971-7976ab80-fd88-11e8-9ff2-7dbcb31ace42.png">

**Comment by CvX** [comment]
I'm not sure what icon are you referring to. Could you show a screenshot of it from https://messenger.com?

**Comment by JoniVR** [comment]
@CvX 	
I think he means this one: 
![screenshot 2019-02-20 at 13 08 27](https://user-images.githubusercontent.com/7591717/53090771-a70e6c80-3510-11e9-9af0-30d99382a991.png)


Although I'm not seeing this issue myself.

**Comment by CvX** [comment]
Fascinating! 😃 I don't think I've ever seen this. In what context does this show up? All incoming messages?

**Comment by JoniVR** [comment]
<img src="https://user-images.githubusercontent.com/7591717/53096219-efcd2200-351e-11e9-8fbd-2b29535c053d.gif" alt="test" width="450px"/>

All messages for me, although I'm not seeing this bug. 
You're saying you don't have these reply arrows?

**Comment by filipruisl** [comment]
[image: Screen Shot 2019-02-20 at 14.55.41.png]
Exactly that! I still don't see them.
However, it could be some weird late feature roll-out, as the arrows have
dissapeared from the mobile client as well. so I guess I can close it here?

>

**Comment by JoniVR** [comment]
Yes, my best guess would be facebook is just A/B some of this stuff. For example I've been getting a dark mode on mobile too while some other people haven't.

**Comment by CvX** [comment]
I always get the short end of the stick when it comes to Facebook/Messenger trials and A/B tests! 😄 These never get enabled on my account. 😉 

I wonder if there's a way to trigger them on the client side… 🤔 That would be very useful in debugging issues that only a portion of Caprine user-base experiences.

**Comment by JoniVR** [comment]
I remember years back I signed up for the Facebook "new timeline" feature, but that's literally years ago, and that's the only thing I ever did, but I do seem to always get to test new stuff early. I don't think it's related but it's the only thing I remember doing related to it. Perhaps they have a sign-in thing somewhere.

If you own an Android phone you could sign up to the Android beta tester thing, but idk if that will make you a tester for other stuff.

**Comment by CvX** [comment]
Pardon me staying off-topic, but here’s an example of a Messenger trial and how to enable it: https://twitter.com/flyosity/status/1101937773790052352/photo/1 😃

**Comment by CvX** [comment]
Is this still an issue? I eventually also got the reply feature and those icons show up correctly here. 🙂

**Comment by filipruisl** [comment]
Nope, feel free to close it :)

--
Filip Ruisl
