### ISSUE TITLE
Toggling the blue highlight on conversations

### ISSUE THREAD

**Issue by Vexorify** [sindresorhus/caprine#683]
So currently I am using v2.21.1 instead of v2.22.1 because I don't enjoy the blue highlight on conversations while using the default white theme. Is it possible to make it a toggle or something?

**Comment by sindresorhus** [comment]
Not interested in an option for this. The blue highlight is was chosen to make it look more native.

When https://github.com/sindresorhus/caprine/pull/651 is merged, you can override the styles you don't like.

**Comment by Vexorify** [comment]
Perfect then.
