### ISSUE TITLE
Optionally hide tray icon?

### ISSUE THREAD

**Issue by ransagy** [sindresorhus/caprine#684]
Is there a way to optionally hide/not use the tray icon at all? The 'Quit on window close' option does half of what i'd want in this feature suggestion.

Generally, I always have Caprine open, along side several other messenger apps, so the window is not even minimized most of the time and the icon simply adds clutter for me.

How complicated would it be to simply not use an icon and just live from the taskbar entry until closed?

**Comment by novdddd** [comment]
Maybe something like this is ok:

```js
  if (!settings.get('hideTray')) {
    tray.create();
  }
```

Saw it from here  https://github.com/klaussinani/tusk/blob/master/index.js#L78

**Comment by ransagy** [comment]
That's a good start, but i assume a few more things will need to be changed as there are probably other interactions with the tray from the code i can see. Might be worth a try though.
