### ISSUE TITLE
Unable to run OSX

### ISSUE THREAD

**Issue by uhlhosting** [sindresorhus/caprine#685]
Unable to run Caprine after installing HandsOff! Osx Mojave.

---
<img width="842" alt="image" src="https://user-images.githubusercontent.com/6324047/50237055-33d76580-03bc-11e9-8fbf-1c601879b543.png">

Caprine 2.23.0
Electron 3.0.12
darwin 18.2.0
Locale: en-US

**Comment by Beardless** [comment]
Same for me
Caprine 2.23.0

**Comment by sindresorhus** [comment]
You probably have a firewall blocking the connection.

**Comment by Beardless** [comment]
My os firewall is off

**Comment by JoniVR** [comment]
I think this is probably HandsOff blocking something, also @Beardless could you click open those error messages? (click the little arrow next to the icon).

**Comment by polgiron** [comment]
Hello guys, I have not installed HandsOff and my firewall is off as well.
I'm getting the same blank page. How do you display the console for this app?
Cheers!

**Comment by JoniVR** [comment]
@polgiron 
Try `F12`.
If that doesn't work try `Ctrl+Shift+i` for Windows and `Cmd+Option+i` for Mac.

**Comment by polgiron** [comment]
Thank you, here are my errors:

![image](https://user-images.githubusercontent.com/8901804/51189333-bbd75f00-18d7-11e9-8415-d9779dbb355a.png)

**Comment by RemiKalbe** [comment]
Same here,

<img width="802" alt="image" src="https://user-images.githubusercontent.com/8604600/51853896-b6dbcc00-2329-11e9-9f52-747a82770588.png">

**Comment by mquevill** [comment]
From what I can tell, Hands Off! does not support newer versions of MacOS (e.g. Big Sur, even Catalina) and the general support for the software has been going downhill. There have even been many reports of it not working properly on Mojave, which is the OS from the original poster.

For users with no firewall settings and not using Hands Off!, I hope this issue has been cleared with recent versions. I would say it's safe to close this issue for now.
