### ISSUE TITLE
Hide menu enabled, now no way to get it back on Ubuntu

### ISSUE THREAD

**Issue by doktorszike** [sindresorhus/caprine#686]
I've set the menu to hidden, now there is now way to get it back.
Ubuntu MATE 18.04.1 LTS
installed: Caprine 2.23.0 (10) 110MB
Pressing ALT does not help.
Restarting the app does not help.
Let me know if you need further info.

**Comment by caesay** [comment]
Caprine uses `electron-store` to persist settings. This in turn saves the data to electron's `app.getPath("appData")` directory. From the [electron docs](https://electronjs.org/docs/api/app#appgetpathname), this folder is at the following location:

- `%APPDATA%` on Windows
- `$XDG_CONFIG_HOME` or `~/.config` on Linux
- `~/Library/Application Support` on macOS

I have verified this is the case for me, my config file is at `%APPDATA%\Caprine\config.json`. This is a simple json file, feel free to edit it to restore your menu and close this ticket if this solves your issue.

**Comment by doktorszike** [comment]
Thank you, yes it solved the problem indeed.
I have installed Caprine via snap on ubuntu 18.04, so for future reference, you can find the above mentioned config.json file on the following path:
/home/user/snap/caprine/10/.config/Caprine/config.json

I edited:
	"autoHideMenuBar": true,
to
	"autoHideMenuBar": false,
Restarted the app and it is back.
