### ISSUE TITLE
Modifying Light Theme with Custom.css

### ISSUE THREAD

**Issue by Vexorify** [sindresorhus/caprine#688]
With the latest release, I have been able to change the "selected-conversation-background" to the default messenger color (not a fan of the blue), and I've been able to hide the blue dot next to new messages in the conversation list. How can I change the selected conversation's text color from being white when selected?

**Comment by outpoints** [comment]
Did you ever figure it out?
And mind sharing your CSS that you've made?
Would love to have some inspiration :)

**Comment by Vexorify** [comment]
@sindresorhus is there currently a way to edit the text color on the selected conversation in the custom.css file?

**Comment by rosoau** [comment]
hi guys. I'm using a dark theme and managed to change some text from white to orange. 
It is such lines as;	--base-seventy: rgba(255, 72, 0, 0.9);
this makes orange appear in: contact names and the content of their chat-bubble to me 
and 3rd party info and on the login window text boxes entries
all the other lines I left at white, like this one:  	--base-fourty: rgba(255, 255, 255, 0.6);
this is white with RGB at fullest 255, 255, 255 and then the intensity of the colour: 0.6 (was at 0.4)
I suppose you have the same custom.css in light mode
If you are interested here is my theme: "saffron-wine" shown from line 11 onwards: 

:root {
	--base: #FF4800;
	--base-ninety: rgba(255, 255, 255, 0.9);
	--base-seventy-five: rgba(255, 255, 255, 0.75);
	--base-seventy: rgba(255, 72, 0, 0.9);
	--base-fifty: rgba(255, 255, 255, 0.5);
	--base-fourty: rgba(255, 255, 255, 0.6);
	--base-thiry: rgba(255, 255, 255, 0.3);
	--base-twenty: rgba(255, 255, 255, 0.2);
	--base-five: rgba(255, 255, 255, 0.05);
	--base-ten: rgba(255, 255, 255, 0.1);
	--base-nine: rgba(255, 255, 255, 0.09);
	--container-color: #16000F;
	--list-header-color: #210A1B;
	--blue: #00E1FF;
	--selected-conversation-background: linear-gradient(hsla(209, 110%, 15%, 0.9), hsla(209, 110%, 8%, 0.9));
}
You may want to save the original custom.css in case you want to revert
![messenger_025](https://user-images.githubusercontent.com/13397926/51349000-48606800-1af8-11e9-9f17-13b45e9c58ea.png)

**Comment by rosoau** [comment]
In the meantime the custom.css has changed and contains the tweak for the login window colours:
	--container-dark-color: #12000D;
If the old file persists then the login background remains white and can't be changed;
that is until the new custom.css is installed
It is best to deinstall and purge caprine before installing the latest version 2.27.0; 
also to delete folder: ~/.config/Caprine/ 
then on the first run click on File > Caprine Settings > Advanced > Custom Style 
and there change the colours you want.
It may also be necessary to change line 3 of ~/.config/Caprine/config.json to:
	"darkMode": true,
save changes and then to accept the changes do: Ctrl + R

**Comment by dusansimic** [comment]
Custom css file applies styles after our custom styles so anything that is overwritten in custom file is the thing that's applied. For light mode styles, just apply styles to element in a regular way and for dark mode, apply styles to element by prefixing with the `html.dark-mode` element (check out our css patches in the source code to see examples). If you have issues with writing the css, this shouldn't be a place to discuss those, that's a css issue not a Caprine issue. If you find an issue with css patches that are part of Caprine source code, that would be a Caprine issue and feel free to open an issue about it.
