### ISSUE TITLE
Newline in input box

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#69]
There's a blank newline in the text input field that appears after every message sent. Using OSX.

**Comment by phamdaniel** [comment]
Are you on the latest version 1.2.1? I doesn't seem to be happening on my end.

**Comment by z-ax** [comment]
Same to me - remember that bug, but seems fixed some releases ago and can't reproduce anymore.

**Comment by ivancuric** [comment]
Yep, installed via homebrew.

**Comment by sindresorhus** [comment]
@ivancuric The latest version is 1.2.1. The one on homebrew is 1.1.0.

**Comment by ivancuric** [comment]
```shell
~ ❯❯❯ brew cask info caprine
caprine: 1.2.1
Caprine
https://github.com/sindresorhus/caprine
/opt/homebrew-cask/Caskroom/caprine/1.2.1 (196 files, 107M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/caprine.rb
==> Contents
  Caprine.app (app)
```

**Comment by sindresorhus** [comment]
My mistake too. Seems `brew cask info caprine` reflects the state before `brew update`, which is super stupid. Glad to hear everything is working :)
