### ISSUE TITLE
Inability to answer messenger calls

### ISSUE THREAD

**Issue by arcues19875** [sindresorhus/caprine#690]
Friend tried calling me on Messenger, tried accepting the call via the pop-up that appeared. Nothing happens, call doesn't follow through. Pop up window just disappears

---

Caprine 2.22.1
Electron 3.0.9
win32 10.0.17134
Locale: en-US

**Comment by dusansimic** [comment]
Closing because issue is stale and the issue doesn't exist in the latest release.
