### ISSUE TITLE
Pressing F5 button crashes Caprine window

### ISSUE THREAD

**Issue by matkaz** [sindresorhus/caprine#691]
After pressing F5 button content of a Caprine window becomes entirely white and the window closes after a while. Tray icon remains visible and is fully functional after the window closes.

Steps to reproduce:

- click on tray icon to open Caprine window
- press F5 on keyboard

Occurs: usually (for some reason, which is unknown for me, few times this behaviour have not occurred)
Environment: Kubuntu 18.04.1

---

Caprine 2.23.0
Electron 3.0.12
linux 4.15.0-43-generic
Locale: pl

**Comment by a-mateva** [comment]
It does the same thing with me, too. Same thing happens when you press Ctrl + R to refresh it. And I installed Caprine like a week and a half ago or something and this has been happening for 2 days now.

**Comment by polynar** [comment]
When i refresh the page CMD + R, F5 the vibrancy is crashing.
![caprine-vib-crash 2019-06-21 12_14_54](https://user-images.githubusercontent.com/1795922/59915963-3758b180-941e-11e9-9c7e-88b8256c67ba.gif)

**Comment by CvX** [comment]
@polynar that issue is tracked in #712

**Comment by z-ax** [comment]
LGTM with recent version.
