### ISSUE TITLE
Tray icon is too big

### ISSUE THREAD

**Issue by bsucker98** [sindresorhus/caprine#695]
just look at the tray icon, it's bigger than other tray icons

---

Caprine 2.24.0
Electron 4.0.1
linux 4.19.12-106.current
Locale: en-US

**Comment by sindresorhus** [comment]
Tray icons are a mess on Linux for Electron apps. Not much we can do about it. https://github.com/electron/electron/search?q=tray+icon+is%3Aissue&state=open&type=Issues

**Comment by bsucker98** [comment]
Understood...yah, seems an issue with linux. even many other apps tend to have big tray icon..tnx:)
