### ISSUE TITLE
Toggle when left clicked 

### ISSUE THREAD

**Issue by bmorashad** [sindresorhus/caprine#696]
for both left and right click it just shows up the usual right click menu, & that doesn't serve the purpose of a tray icon fully.

**Comment by rosoau** [comment]
I'll second that. It would be great if:
left click opens the main window
right click shows option to quit
no more than that
Most tray icons will open the main application window on left click
This is a great little app and worthwhile to improve as much as possible

**Comment by Xapphire13** [comment]
[This line](https://github.com/sindresorhus/caprine/blob/44e9c10/readme.md#L166) in the README says that you can click the menu icon, but that's not the case 😿

**Comment by whitecrownclown** [comment]
I figured out the issue on this, I still need to test it on `linux` and `windows`, but I'll get back with a PR.

**Comment by SilverSaw** [comment]
seems to be fixed, don`t know when but tested on 2.57.0
