### ISSUE TITLE
Block the delivery receipts feature

### ISSUE THREAD

**Issue by Im3lo0sh** [sindresorhus/caprine#699]
Since you you can hide last seen / typing indicator
Can there be an option to block delivery receipts ( when someone sends you a message and you are online they can see that it has been delivered to you )? .. 
the urls to block are:
`*.facebook.com/*delivery_receipts*`
`*.messenger.com/*delivery_receipts*`
`*.facebook.com/*unread_threads*`
`*.messenger.com/*unread_threads*`

**Comment by sindresorhus** [comment]
Sounds like a useful feature. PR welcome :)
