### ISSUE TITLE
Blurry icon rendering on OSX (non-retina)

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#70]
Messenger.com in Chrome vs Caprine:
![image](https://cloud.githubusercontent.com/assets/2827047/14138126/c219bc78-f66b-11e5-8acb-c10ab29a3556.png)
Can't inspect it, but it's probably because it downloads the retina spritemap and dowscales it.

**Comment by sindresorhus** [comment]
@ivancuric Is this still the case with latest?

**Comment by ivancuric** [comment]
Yep. Using a MacBook retina on an external non-retina display. Works ok on the laptop screen.

**Comment by sindresorhus** [comment]
Try pressing Cmd+R.

**Comment by ivancuric** [comment]
I'm an idiot. Thanks.

**Comment by sindresorhus** [comment]
I don't think there's any way around this other than reopening that app or refreshing the page. And I definitely don't want to do either on a display change. Open to suggestions though.
