### ISSUE TITLE
Clicking on notifications doesn't open window on macOS

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#700]
Since v2.24 clicking on system notifications when Caprine's window is closed (with ⌘W) does not do anything. It should (and it used to) open and bring Caprine to the front, then focus the selected conversation.

**Comment by janosorcsik** [comment]
@gklka @sindresorhus Electron 4 has a new feature: the Context Isolation. If the Context Isolation enabled the global objects cannot be modified.
In Caprine this flag is true therefore my monkey patch on the notification doesn't work.
We need to disable this.
