### ISSUE TITLE
Inactive windows should have gray sidebar selection colors

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#702]
Inactive windows lack their prominent highlight color to let the user navigate more easy between his/her apps and find the active one. The prominent blue highlight color in the sidebar should be changed to gray when the window is inactive. See the attached examples in the other ticket: #701

**Comment by sindresorhus** [comment]
For reference, this is how it should look in light mode:

<img width="370" alt="screen shot 2019-01-16 at 15 16 59" src="https://user-images.githubusercontent.com/170270/51235350-d413b080-19a1-11e9-886e-a1b15563ff12.png">

**Comment by sindresorhus** [comment]
The best solution would be to listen for the BrowserWindow `blur` and `focus` events and set a class on the body which is then used to override the highlight color.
