### ISSUE TITLE
Dark sidebar vibrancy color is much darker than expected

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#703]
Compare it to Messages app:

<img width="667" alt="screenshot 2019-01-09 at 10 00 51" src="https://user-images.githubusercontent.com/866694/50888269-93da8e00-13f5-11e9-9a32-59aefa24ae5e.png">

It might has some unnecessary transparent gray background I suppose.

**Comment by sindresorhus** [comment]
// @neegool
