### ISSUE TITLE
Crop chat names on Touchbar

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#705]
<img width="1085" alt="touch bar shot 2019-01-09 at 11 22 52" src="https://user-images.githubusercontent.com/866694/50893380-fc7b3800-1400-11e9-8922-f4c77b5f71ab.png">

Sometimes chat names can be very long. I think you should just crop them to ~25-30 characters.

**Comment by sindresorhus** [comment]
Good idea! Pull request welcome :)
