### ISSUE TITLE
Store Dark mode flag when after user made a change

### ISSUE THREAD

**Issue by z-ax** [sindresorhus/caprine#71]
Lastly, I don't really like to use the dark mode for chat, so noticed one issue with OS X has dark menu bar in Settings and my personal preference.

Would really appreciate the app to store if I did my choise, because for every launch or reload it's dark again.

Let's say, for `undefined`/`null` it'll be in auto mode, like now, and for boolean value - just use it instead of check.

**Comment by sindresorhus** [comment]
Why would you active OS X Dark Mode if you don't want it dark?

> Let's say, for undefined/null it'll be in auto mode, like now, and for boolean value - just use it instead of check.

That wouldn't work as you would never be able to go back to auto mode after manually overriding once. 

Could maybe persist the manual override until the OS X dark mode changes. What do you think about that?

**Comment by z-ax** [comment]
> you would never be able to go back to auto mode after manually overriding once

Exactly, it is the way how it should work :) If it's user's preference - should be changed to manual mode, if changed once - will change when will want to again.

I prefer dark menu bars and dock, they don't distract me as light do while working.
But few weeks ago I realised that all reading in the middle of screen is better to be light.

Anyways, it's not about me, but about user preferences and I find kinda annoying switch from app's Dark mode from time to time. Decision is up to you :)

**Comment by sindresorhus** [comment]
You didn't answer my question.

> Exactly, it is the way how it should work :) If it's user's preference - should be changed to manual mode, if changed once - will change when will want to again.

Not being able to easily go back to the initial state is horrible UX. I would never do it that way.

> Anyways, it's not about me, but about user preferences

No, it *is* about you. No one else has reported this being an issue.

**Comment by z-ax** [comment]
Sorry, about option persist? I don't really see how that should work. Other option is to have 3 states - `auto`, `light`, `dark` and show this value in Menu, like "Mode: Auto (Dark)/Light/Dark" and change on click instead of "Toggle Dark Mode".

For UX - checked all apps I have and none except Caprine automatically applies Dark mode layout inside the app without option to turn it off permanently. The light layout is default from Facebook. And personally I don't see any connection between dark menu bar of OS X and custom dark design of Facebook Messenger.

**Comment by sindresorhus** [comment]
> And personally I don't see any connection between dark menu bar of OS X and custom dark design of Facebook Messenger.

It's called OS X Dark Mode, not Dark Menubar. The menu bar is not the only thing that is dark. The dock is dark too.

-

I'll keep this open for other ideas, but I'm not going to complicate it with multiple states like that.

**Comment by sindresorhus** [comment]
Turns out I was wrong on this one, or rather, this was unexpected and unwanted by most users.

**Comment by z-ax** [comment]
@sindresorhus, thanks! I was thinking to use another app because of 2 tiny, but annoying things, including this one. Was pretty happy to read release notes and see it's gone :)
