### ISSUE TITLE
Always reopens the last message

### ISSUE THREAD

**Issue by nodarkthings** [sindresorhus/caprine#710]
When I launch Caprine, it always comes back to the same correspondent (the last message sent or read): it would be more interesting to have it open to the last correspondent read, even if it's not the last message.
It would be nice having that option in the prefs.

---

Caprine 2.25.0
Electron 4.0.1
darwin 15.6.0
Locale: fr

**Comment by ericachio** [comment]
If I understand correctly, whenever Caprine is launched, it automatically opens the top conversation, and you would like it to open to which ever one you had most recently read (assumably a conversation lower in the chat bar)?
I think messenger itself will also automatically open to the most recent/top conversation. I wonder if it would be implementable.

**Comment by nodarkthings** [comment]
Hi!
Three months later, I don't remember if I had a particular issue — I mean different from FB messenger... Anyway, you're right, it's the same behavior for Caprine and Messenger.
I think that I meant: when you have 2 conversations simultaneously, maybe there is one that is more important to you even if the other one has got an answer, so you might want to stick to it the next time you launch the app. But, probably, it would be something that needs to be implemented by FB, indeed.
Thanks anyway.
