### ISSUE TITLE
Windows — Caprine not listed in the per-app notification settings

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#72]
I'd like to disable the native OS sound notification specifically for Caprine like I did in OSX, but the app is not listed in the per-app notification settings.

This might be a problem with Electron itself, or related to https://github.com/sindresorhus/caprine/issues/49

**Comment by sindresorhus** [comment]
Seems related to https://github.com/electron/electron/issues/4973.

**Comment by sindresorhus** [comment]
Should be fixed in https://github.com/sindresorhus/caprine/releases/tag/v1.2.2.

**Comment by ivancuric** [comment]
Nope, still not visible...

**Comment by gotenyama** [comment]
Is this issue fixed ?
