### ISSUE TITLE
Windows 10: window not vissible when toggled

### ISSUE THREAD

**Issue by matjaz132** [sindresorhus/caprine#721]
So I'm having a problem when I open Caprine, it shows in taskbar but when I click on taskbar the window is not showing.

**Comment by 0xbaadf00d** [comment]
Probably same bug, I have this issue since today. The app screen stay white

![image](https://user-images.githubusercontent.com/1005086/51132782-782b1980-1833-11e9-8e82-53a61944fced.png)

**Comment by Constant-ine** [comment]
Looks like the issue has been fixed now.
