### ISSUE TITLE
Chat background colour

### ISSUE THREAD

**Issue by rosoau** [sindresorhus/caprine#728]
I'm republishing this issue as I filed it together with a different issue under another name #640 

The chat background colours supplied are too light against white text in dark mode.
I suggest to introduce some extra colours onto your palette.
I made a little chart on showing how white shows up with your colours nr. 1 4 8 10 12 14
then the same at half of the intensity/value and full saturation
and again at a quarter of the intensity/value and full saturation
numbers are shown in hexadecimal code
three other dark backgrounds are also suggested
![dark-bgs](https://user-images.githubusercontent.com/13397926/51277235-1af9b880-1a2b-11e9-8ea6-668fbcc5ecb7.png)

**Comment by dusansimic** [comment]
The chat colors are not made by Caprine, they are made by Messenger website. There are also plenty of dark colors you can choose from. Also users could customize the colors themselves by editing custom.css (File > Caprine Settings > Advanced > Custom Styles).

**Comment by rosoau** [comment]
editing custom.css does not work in Linux
I had been given a file that works and looks very different
[custom.css.gz](https://github.com/sindresorhus/caprine/files/9366530/custom.css.gz)
