### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#73]
Hello,

I am using Caprine with Ubuntu 15.04. I think it would be nice to have the ability to zoom, as in scale the text/images. It would make reading the text much easier.

**Comment by sindresorhus** [comment]
Good idea. PR welcome :)

<img width="310" alt="screen shot 2016-04-08 at 21 07 43" src="https://cloud.githubusercontent.com/assets/170270/14386174/f3f3ad62-fdcd-11e5-9fc3-9617e99cbceb.png">

Should work the same as Chrome.

**Comment by jamesrobb** [comment]
What is the picture above exactly? Is it possible to bring this up somehow within the application?

**Comment by phamdaniel** [comment]
The above is a screenshot from chrome, so there's no way to bring it up. It's the goal of how the zoom functionality should look like.
