### ISSUE TITLE
Unable to view shared photos

### ISSUE THREAD

**Issue by samomiklavc99** [sindresorhus/caprine#734]
When clicking on one of the shared photos or any photo in chat it won't open
---

Caprine 2.27.0
Electron 4.0.1
win32 10.0.17763
Locale: sl

**Comment by CvX** [comment]
Does the problem persist after you restart Caprine? Does it also happen when you log in on https://messenger.com?

**Comment by samomiklavc99** [comment]
Problem is fixed only on some chats but on the others it's still there. It doesn't happen on messenger.com

**Comment by CvX** [comment]
I couldn't reproduce this issue. All shared media (photos, gif, movies) display correctly across all my conversations. I don't see anything that Caprine does that would interfere with shared photos… 🤔

Has anyone else here had this problem? Any ideas?

**Comment by samomiklavc99** [comment]
It's working well in 2.27.1. Thanks for quick response and help!
