### ISSUE TITLE
Text when searching for GIF

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#74]
Hello,

On Ubuntu 15.04, when searching for a GIF to insert into the chat, the text one types into the search box is not visible, though the search term is recognized and appropriate GIFs appear in the search.

**Comment by sindresorhus** [comment]
Confirmed. OS X too. Seems to be a bug with dark mode. Works in light mode (Ctrl+D).

-

// @oskarkrawczyk @phamdaniel

**Comment by oskarkrawczyk** [comment]
Will have a look

**Comment by sindresorhus** [comment]
@oskarkrawczyk See: https://github.com/sindresorhus/caprine/issues/76
