### ISSUE TITLE
language 

### ISSUE THREAD

**Issue by cabban** [sindresorhus/caprine#742]
hello, how can i change to my language cause i cant share anything all is on wrong language :Ö(

**Comment by CvX** [comment]
Hi!

* what's your operating system?
* what's your operating system's language?
* what language is Messenger currently using?
* and what language was expected?

**Comment by cabban** [comment]
Thank u

Windows 10
Swedish
English
Swedish cause it has been messenger on desktop before . But this program no
language selection 😀cheers

tisdag 22 januari 2019 skrev Jarek Radosz <notifications@github.com>:

**Comment by CvX** [comment]
Oh, it seems that currently Messenger has only login screen localized… I've tried with a couple of languages ('sv', 'pl', 'de', 'es') and both login screens (Messenger and "Workplace by facebook") are translated, but none of the interface.

It is localized on mobile platforms, so maybe there's a chance they'll do it here too.

**Comment by cabban** [comment]
Caprine 2.27.1
Electron 4.0.1
win32 10.0.17763
Locale: sv

why cant messenger be on swedish i gonna force to get back to desktop :(

**Comment by CvX** [comment]
Could you tell me in which exactly Messenger app was it working for you before? Was it the official app (https://www.microsoft.com/en-us/p/messenger/9wzdncrf0083)?

I'll have to check it out, but it's unlikely that Caprine will able to provide extensive multi-language support.

**Comment by cabban** [comment]
Messenger for desktop  i have Swedish on :) cheers

Den fre 25 jan. 2019 kl 21:08 skrev Jarek Radosz <notifications@github.com>:

**Comment by CvX** [comment]
Ok, I've tried Messenger's official Windows app. As you've said it is localized, but it's a native Windows app, and it has its own translations (some are shared with their iOS app). So unless Facebook decides to apply these translations to their web app (https://messenger.com), Caprine can't use those. Sorry!
Gotta keep fingers crossed! 🤞🙂

**Comment by cabban** [comment]
But messenger for desktop is like Caprine I have Swedish I hade from first
i had from fork . Strange that is not possible here well well. Can't use
this cause I can't share anything with my friends . Shame 🤨grejt program
other wise

onsdag 30 januari 2019 skrev Jarek Radosz <notifications@github.com>:
