### ISSUE TITLE
Custom css styles not working

### ISSUE THREAD

**Issue by a-mateva** [sindresorhus/caprine#748]
I have been using Caprine for a week or so and I was super impressed with it. I made myself a custom gradient for the selected conversation background by overriding the default style in the Advanced -> Custom Styles section and it worked out beautifully. However, when a few days later, I decided to tweak it a bit - the selected conversation background turned the default blue and nothing I do can change it. 

Any ideas on how I can fix this?

**Comment by CvX** [comment]
Hey. I've tried changing colors locally and it did work. Can you show us your custom CSS?

**Comment by a-mateva** [comment]
![image](https://user-images.githubusercontent.com/35598271/51760001-31aaaa00-20d2-11e9-846e-62a0ba625cb3.png)

**Comment by CvX** [comment]
Hm, I don't see anything out of ordinary here…

**Comment by a-mateva** [comment]
Exactly, it was all fine a few days ago and when I decided to tweak it (after leaving it as it had been for a few days), it just went back to default blue and there was nothing I could do about it. Also, it crashes when I press Ctrl + R or F5.

**Comment by rosoau** [comment]
i had a similar confusion and the solution was to;
de-install/purge caprine
make a note of your tweaks
delete folder ~/.config/Caprine
re-install the latest version 2.27.1
login
in view check: dark mode
then call up the custom.css
and proceed from there to tweak and save and Ctrl+R
hope this will get it going again

**Comment by harpalassi** [comment]
Is there a way to change the blue of the conversation bubbles? i edited the `blue` in the `css` file, but it changed the blue highlight for the sidebar and the blue if i click and hold on a bubble, but the conversation itself is still the default. 

i also tried `selected  conversation background` but that didn't seem to affect it.

**Comment by a-mateva** [comment]
Personally, I have no idea what the `blue` is for but `selected-conversation-background` does the job for me, I did a gradient on mine. Try the solution that @rosoau suggested - it worked for me :)

**Comment by harpalassi** [comment]
thanks for your reply - tried messing with `selected-conversation-background` (did a red to green gradient) and it only changed the highlight on the sidebar - but nothing with the actual chat bubble colors. i can't figure out what `blue` is for either. the rest of the options look like they're all set to greyscale - so i'm not sure where the chat bubble colors are.

**Comment by a-mateva** [comment]
Hang on, what do you mean my 'chat bubble colors'

**Comment by harpalassi** [comment]
![image](https://user-images.githubusercontent.com/25518370/52146365-24894000-2629-11e9-8b21-527dcb383393.png)
For example, where the "sf" "ad" "saf" etc are. I'm trying to change that to a different blue or even another color altogether.

**Comment by a-mateva** [comment]
I haven’t really explored this option and don’t know if it is an option altogether but as far as I am aware, you can only change the chat colors when you go to the right sidebar and customize the color from there. Unfortunately, Facebook only offers a limited array of colors so I can see your frustration. I will delve further into this but like I said, as far as I am aware, Caprine doesn’t override that setting.

**Comment by harpalassi** [comment]
I see. Thanks for clearing that up! I did see green bubble colors in this pull request - 
https://github.com/sindresorhus/caprine/pull/739

looks like it never went through though. That's what got me thinking it was possible.

**Comment by ntwb** [comment]
Marginally off topic, but the `custom.css` path, can it be `~/.config/caprine`? 
(Upper or lower case for the C, i.e. `Caprine` or can it be `caprine`)

Or does it have to be ?libray/Application Support/Caprine/custom.css`?

I'd like to store the `custom.css` file in my _dotfiles_ hence the query.

**Comment by hadallen** [comment]
also experiencing this on archlinux, Caprine version 2.55.4. tried uninstalling/purging/reinstalling to no avail. custom css entries are not being applied

**Comment by rosoau** [comment]
I had been given a custom.css by the developers a while ago. It looks very different to the short form. Perhaps you can try to change colours in that. You can save the original to custom.css.orig. It is in: ~/.config/Caprine. The .txt extension needs to be removed. It was added to publish it here. Hope this helps
[custom.css.txt](https://github.com/sindresorhus/caprine/files/8647784/custom.css.txt)
.

**Comment by hadallen** [comment]
> I had been given a custom.css by the developers a while ago. It looks very different to the short form. Perhaps you can try to change colours in that. You can save the original to custom.css.orig. It is in: ~/.config/Caprine. The .txt extension needs to be removed. It was added to publish it here. Hope this helps [custom.css.txt](https://github.com/sindresorhus/caprine/files/8647784/custom.css.txt) .

thank you, this worked for me
