### ISSUE TITLE
enhancement request: Photos browser

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#749]
2.27.1 (2.27.1.1153)
i want the ability to attach images from Photos.app (macOS).
like in messenger inside facebook, i can open a finder window and choose Photos below the other folders and favourites, and a mini Photos browser opens

---

Caprine 2.27.1
Electron 4.0.1
darwin 18.0.0
Locale: en-GB

**Comment by CvX** [comment]
Caprine already does this. It's the first button on the left in the message composer.

<img alt="attaching photos" width="600" src="https://user-images.githubusercontent.com/66961/51864844-1abfbe00-2345-11e9-9312-95054b26e246.png">
