### ISSUE TITLE
Add unread message indicator to tray

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#75]
Hello,

I have tested by having friends message me when the window is up, and minimized to the tray, in either case the libnotify style notifications do not come up.

**Comment by sindresorhus** [comment]
Did you activate it in the Preferences?

**Comment by jamesrobb** [comment]
Sorry, you're right, I did not have them turned on.

That being said though, a flashing tray icon might be nice to let one know there is an unread message still should someone not be looking at the screen when the libnotify message comes up.

**Comment by sindresorhus** [comment]
I wouldn't want it to flash, but some kind of badge to indicate a new message could maybe be nice. Not sure whether it's possible to change the icon dynamically though, as it's set as a path. https://github.com/sindresorhus/caprine/blob/36c79780c8799719be65921a553949ae667662c5/tray.js#L4

**Comment by tschuy** [comment]
You can update the tray icon programatically: https://github.com/electron/electron/blob/master/docs/api/tray.md#traysetimageimage

**Comment by sindresorhus** [comment]
@tschuy Oh, didn't realize that's supported now. Should make it much easier to implement.

**Comment by sindresorhus** [comment]
PR welcome :)
