### ISSUE TITLE
ability to turn off linking of time related words 

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#750]
2.27.1 (2.27.1.1153)
in my language, norwegian, we use the word 'one' a lot. ('one should do that'). that word in norwegian is 'man'. that word is also an abbreviation for 'mandag' (monday). sometimes, i write the word 'man' three times in a sentence, and every one get underlined, suggesting i mean 'monday', and want to make an appointment for that day. it is super annoying. i want to turn that linking behaviour off completely, or at least specifically for that word, since it's used so often

**Comment by sindresorhus** [comment]
This is unfortunately outside our control. Caprine is just a wrapper for messenger.com. You'll need to report this to Facebook Messenger. Go to https://www.messenger.com, login, click the cog icon, click "Report a Problem".

**Comment by 639me** [comment]
yah i also did that!. takk sindre!
