### ISSUE TITLE
New Messenger icon

### ISSUE THREAD

**Issue by neegool** [sindresorhus/caprine#751]
So Messenger has recently rebranded. Perhaps it's a good idea to adapt their new logo in the app.

The one below is extracted from the iOS app.
<img width="512" alt="messenger" src="https://user-images.githubusercontent.com/2795476/51910277-b7e42a80-2409-11e9-98aa-522020814a31.png">

**Comment by sindresorhus** [comment]
I recreated the app icon from scratch by manually tracing the above image.
