### ISSUE TITLE
Updater doesn't work on Windows

### ISSUE THREAD

**Issue by CvX** [sindresorhus/caprine#752]
_Reposting this (from https://github.com/sindresorhus/caprine/commit/00746cfce60b4332eb03945ad48e0888a90fa9e0#commitcomment-32009798) as an issue so it doesn't fall through the cracks_ 🙂 cc: @sindresorhus

(…) here's another issue. This time on Windows (2.26.0 to 2.27.1):
```
Sign verification failed, installer signed with incorrect certificate: publisherNames: Developer ID Application: Sindre Sorhus (YG56YK5RN5)

[error] Error: Error: New version 2.27.1 is not signed by the application owner: publisherNames: Developer ID Application: Sindre Sorhus (YG56YK5RN5)
```

The full log is here: https://gist.github.com/CvX/9af41b1cbbb5f8bb9215f4d288680d1d

> I don't think Windows builds were ever signed. (?)

Turns out they are signed. 😅

Both Mac and Windows builds are signed using your Apple dev cert (“Developer ID Application: Sindre Sorhus (YG56YK5RN5)”) which is signed by Apple’s “Developer ID Certification Authority”.

Certificate validation on Windows fails because of “[A certificate chain could not be built to a trusted root authority](https://gist.github.com/CvX/9af41b1cbbb5f8bb9215f4d288680d1d#file-caprine-windows-log-L159)”.

On macOS the chain of trust is unbroken: 
```sh
 $ codesign -dvvvv Caprine-2.27.0.dmg 2>&1 | grep Authority=
 Authority=Developer ID Application: Sindre Sorhus (YG56YK5RN5) 
Authority=Developer ID Certification Authority
 Authority=Apple Root CA 
```

On Windows, there’s most likely no “Developer ID Certification Authority” certificate installed by default, hence the failure.

Windows build is signed if either `WIN_CSC_LINK` or `CSC_LINK` env var is set. `CSC_LINK` is set on CI.
[Travis CI logs](https://travis-ci.org/sindresorhus/caprine/jobs/481981105) show that electron-build is signing: dist/mac/Caprine.app, dist/win-unpacked/Caprine.exe, dist/win-unpacked/resources/elevate.exe, dist/.__uninstaller-nsis-caprine.exe, dist/Caprine Setup 2.27.1.exe

Alright, onto **possible fixes** (speculative fixes :wink:):
* [Export](https://www.electron.build/code-signing#how-to-export-certificate-on-macos) the “Developer ID Certification Authority” cert together with the “Developer ID Application” cert to make sure the chain of trust is complete on Windows. I have no idea whether it would work, but if it did it would be the best scenario, being able to have Windows binaries signed.
* Or: Generate a separate certificate for Windows binaries, and [set `WIN_CSC_LINK` and `WIN_CSC_KEY_PASSWORD` on CI](https://www.electron.build/code-signing)
* Or: Disable code signing on Windows. It may be possible by adding a `sign` key to ~~`nsis` build target~~ `win` build option in package.json with a value that’s a path to a module which would export a no-op function. At least that’s what I gather from reading the electron-builder code…

**Comment by sindresorhus** [comment]
I think we can just set `"win.verifyUpdateCodeSignature": false`. See https://github.com/electron-userland/electron-builder/issues/3458#issuecomment-437270389

**Comment by CvX** [comment]
That would work around the issue, but only for the future builds, i.e. current users would have to manually update Caprine to the version with a fix, and only then auto updates would resume.

Fixing the certificate chain or generating a new certificate with the same CN field, would fix the issue for all users. (looking at the code again I don't think "solution" 3 would do anything for us)

**Comment by sindresorhus** [comment]
> On Windows, there’s most likely no “Developer ID Certification Authority” certificate installed by default, hence the failure.

But updates on Windows have been working previously, so that doesn't explain it.

**Comment by sindresorhus** [comment]
> Fixing the certificate chain or generating a new certificate with the same CN field, would fix the issue for all users.

Would it though. According to https://github.com/electron-userland/electron-builder/issues/1930:

> MS doesn't add your certificate authority to default bundled trusted authorities.

And the electron-builder docs says you need to buy a Windows approved certificate for it to work: https://www.electron.build/code-signing

**Comment by sindresorhus** [comment]
@CvX Is this still an issue? What should we do about it?

**Comment by CvX** [comment]
I’ll let you know after the next release. 🙂

So far, I’ve manually updated Caprine on my Windows PC to the latest version. We’ll see if it correctly updates to the next one.

I wonder if we should implement a way to inform users (of a specific versions range) about any required actions in such situations. 🤔

**Comment by sindresorhus** [comment]
@CvX New release is out: https://github.com/sindresorhus/caprine/releases/tag/v2.30.0

**Comment by CvX** [comment]
The auto update from 2.28/2.29 to 2.30 ran without any issues. So the issue is solved (at least for new users and those who manually update to 2.28+). I'm closing this.
