### ISSUE TITLE
Mac OS: Caprine doesn't start, blank window

### ISSUE THREAD

**Issue by Webbrother** [sindresorhus/caprine#753]
OS: Mac OS 10.14.2
Version: 2.27.1 (2.27.1.1153)

When I open the app it has just blank screen. I tried reinstall it but didn't help.

**Comment by Sylk** [comment]
Came here to say this also. Force close it, and re-install do nothing. Please advise.

**Comment by danfrankj** [comment]
Same issue on Mac OS 10.14.2

**Comment by Sylk** [comment]
Hey @sindresorhus can you give some guidance on this, I will try and solve it.

**Comment by Sylk** [comment]
Hello @Webbrother @danfrankj did the issue self resolve for you guys?

Because it ended up self resolving for me.

**Comment by danfrankj** [comment]
@Sylk it did seem to self-resolve ... not sure what happened but no longer is an issue ...

**Comment by Sylk** [comment]
@danfrankj can you close this?

**Comment by danfrankj** [comment]
@Sylk I didn't open this issue, @Webbrother can close if it's resolved.

**Comment by tracker1** [comment]
reboot (or kill all related processes) and delete the app directory... sorry, not sure where that is at the moment, on a windows machine currently or would confirm... I think it's in your user directory/library/appname a lot of the time.

Next time you start the app, you'll need to login to FB again.

**Comment by kentrh** [comment]
I encountered this issue just now and I deleted the app and the data in `/Users/--||--/Library/Application Support/Caprine` as suggested by @tracker1 and installed again with `brew cask install caprine` and it was all good. 

Don't know if I had to delete the app though, but that always like a good thing to do in these scenarios ><

**Comment by Gideon-Felt** [comment]
Im on Ubuntu with blank screen, just installed it.

**Comment by dusansimic** [comment]
This seems to be solved. Closing the issue. If the issue still persists, file a new report.
