### ISSUE TITLE
No tooltips and modals are showing up

### ISSUE THREAD

**Issue by szhu** [sindresorhus/caprine#759]
The following aren't showing up for me:
- Timestamps on hover
- The recipient selector after you click the new message button
- The reaction picker for reacting to messages
- The settings modal

I've used Caprine with no issues for a few months now. The above issues started a few days ago.

Caprine version 2.27.1.1153
macOS 10.14.2

**Comment by AreD** [comment]
I have the same problem too. After restart app modals some time work well.

Caprine version 2.27.1.1153
macOS 10.14.1

**Comment by AreD** [comment]
After deleting the Caprine data ~/Library/Application Support/Caprine/ Caprine works well for a long time.

**Comment by szhu** [comment]
Ah that worked, thanks!
