### ISSUE TITLE
macOS Mojave - No notifications for messages in group chats

### ISSUE THREAD

**Issue by JohnnyMcL** [sindresorhus/caprine#761]
I am not receiving any notifications for messages received in group chats despite Caprine's badge indicator updating properly, and receiving notifications just fine for individual chats.

**Comment by sindresorhus** [comment]
What Caprine version are you on?

**Comment by JohnnyMcL** [comment]
I'm currently on Caprine Version 2.28.0 (2.28.0.1220) and this problem is still persisting.

**Comment by CvX** [comment]
Couldn't reproduce this issue.

Are you sure that the conversations in question aren't muted or ignored?
Or are there any specific circumstances where this happens?

**Comment by JohnnyMcL** [comment]
None of the conversations are muted, that was the first thing that I checked. It seems that now I am sometimes receiving group chat notifications just fine and sometimes not receiving any at all. I have been trying to figure out what might be different in each case, but I really can't figure out what is going on.

**Comment by yerbestpal** [comment]
I have the same issue on Fedora 29. I will update with build info asap.

**Comment by dusansimic** [comment]
Closing since it's stale and notifications were removed from Messenger website so it doesn't work either way.
