### ISSUE TITLE
Hight ram usage

### ISSUE THREAD

**Issue by Sykursen** [sindresorhus/caprine#763]
Hello,
I use caprine since a month and today I look my task manager and surprise.
![image](https://user-images.githubusercontent.com/18405490/52521226-cfbe7880-2c6b-11e9-894d-926131d2f4b9.png)
I'm very worry by the ram usage of caprine. Is It possible to fix it ?

**Comment by Sykursen** [comment]
Caprine 2.27.1
Electron 4.0.1
win32 10.0.17763
Locale: fr

**Comment by alekksander** [comment]
i experienced few memory leaks too, but didn't „catch it” on screenshot. what's more intriguing my OS is linux with kde 5.14.5 / caprine 2.27.1. on weaker unit it's very noticeable regarding performance.

**Comment by sindresorhus** [comment]
Not much we can do about this, unfortunately...

You could try reporting the it to https://github.com/electron/electron
