### ISSUE TITLE
The apps never loads

### ISSUE THREAD

**Issue by thekoshkina** [sindresorhus/caprine#764]
The login screen never comes up

The moment i start the app  the following appers screen and nothing else happens
<img width="912" alt="screen shot 2019-02-10 at 15 49 36" src="https://user-images.githubusercontent.com/16907519/52529738-847b9700-2d4b-11e9-8684-c7f92830274d.png">

OS: Mac OS Mojave 10.14 

---

Caprine 2.27.1
Electron 4.0.1
darwin 18.0.0
Locale: en-GB

**Comment by abdullahemad12** [comment]
Are you blocking facebook using the localhost or blocking it by anyway? make sure you can access facebook via your browser. It happened to me when I was blocking facebook

**Comment by thekoshkina** [comment]
That's exactly what it was. 

My content blocker was not blocking messenger.com, only facebook.com. I didn't realise the app needed access to it. 

Works perfectly now. Thank you
