### ISSUE TITLE
search up/down buttons are invisible under dark mode

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#767]
white theme:
![image](https://user-images.githubusercontent.com/3148302/52534004-006de300-2d3c-11e9-9719-aab958e91e2a.png)

dark theme:
![image](https://user-images.githubusercontent.com/3148302/52534008-124f8600-2d3c-11e9-9950-eb76eab87bff.png)

**Comment by andrewjong** [comment]
Try alekksander, try updating your caprine to the latest version! 2.28. I had this issue before on 2.23 as well, but after updating it's fixed.

**Comment by alekksander** [comment]
thanks!
