### ISSUE TITLE
Feature to hide name of current conversation (people, group)

### ISSUE THREAD

**Issue by thanhtunguet** [sindresorhus/caprine#768]
Hi,
When I use Messenger on my laptop in public, I wish that it has feature to hide the name of current conversation I'm focus on (even the tiny profile picture beside every message).
I can think of a button or an option of the context menu when I right click anywhere in the conversation area.
Hope our community will make this feature come true.

**Comment by alexandrepa** [comment]
I'd like to give it a try about a feature likes that. I was thinking of something that you can turn On like the "Dark Mode". I could hide the names and pictures in the current conversation but also in the conversation list. Or maybe I could replace the pictures with a black circle and the first letter of the person name inside it.
What do you think @sindresorhus ? Is it an interesting feature?

**Comment by sindresorhus** [comment]
> Or maybe I could replace the pictures with a black circle and the first letter of the person name inside it.

Yeah, I think this is a must. Otherise, you'll have no idea who you're chatting with.

**Comment by thanhtunguet** [comment]
> > Or maybe I could replace the pictures with a black circle and the first letter of the person name inside it.
> 
> Yeah, I think this is a must. Otherise, you'll have no idea who you're chatting with.

It does not matter when I just want to chat with only one person and I don't want others to know who he/she is!

**Comment by sindresorhus** [comment]
@thanhtunguet You are not our only user. When adding new features, we need to balance the use-cases.

**Comment by thanhtunguet** [comment]
> @thanhtunguet You are not our only user. When adding new features, we need to balance the use-cases.

I have just given an example.

**Comment by AlexBolot** [comment]
Hi @thanhtunguet, do you have any update on that feature ? I don't see it in the last release bundled (`2.43.0`), do I have to clone the repository and build it myself ? :)

More-over, I'd like to suggest an extension to that feature ! I think it could be interesting to have a shortcut to blur-out all text on display (conversations content, groupe names). This could be used, for example if there's someone behind me and I want to hide my conversations without closing Caprine.

What do you think ?

**Comment by thanhtunguet** [comment]
@AlexBolot 
Yes, you have to fork this repository and build it yourself. I requested this feature months ago but now I am not sure it is accepted/implemented or not.
Your idea of blurring the contents instead of closing the app is so awesome. I love it, too.
If you are able to implement it, I hope that you would share it with me. Many thanks!
