### ISSUE TITLE
Auto Dark can cause a javascript exception 

### ISSUE THREAD

**Issue by phamdaniel** [sindresorhus/caprine#77]
Figured it out! Auto dark no longer works after reloading a page (Cmd + R)

![image](https://cloud.githubusercontent.com/assets/3745612/14390716/826732f0-fd86-11e5-9469-78d0dc1b934c.png)

**Comment by sindresorhus** [comment]
The fact that you could refresh was a bug I just fixed: https://github.com/sindresorhus/caprine/commit/36c79780c8799719be65921a553949ae667662c5. Caprine is not a browser.
