### ISSUE TITLE
Facebook Workplace is interfering

### ISSUE THREAD

**Issue by Federfleisch** [sindresorhus/caprine#771]
Hello,

About an hour ago, Caprine suddenly stopped working and was replaced by a Workplace log in page (see below), and stayed that way since then. 

Can anyone help?

Thx

![capture d ecran 2019-02-12 a 11 55 35](https://user-images.githubusercontent.com/14271051/52630880-abf27100-2ebd-11e9-9e29-7772d5497683.png)

**Comment by whitecrownclown** [comment]
You can switch between Messenger and Work Chat at the top menu. Here's a [screenshot](https://imgur.com/a/2as2CEN). Click the Switch to Messenger option.

**Comment by Federfleisch** [comment]
I didn't see it, altough I checked that menu. Thanks a lot! 
Guess I must have `⌘!`-ed by mistake...
