### ISSUE TITLE
Can't see recall message in dark theme

### ISSUE THREAD

**Issue by tonyyang924** [sindresorhus/caprine#776]
![2019-02-11 1 38 05](https://user-images.githubusercontent.com/12247447/52695186-cd7b5780-2fa6-11e9-9c83-d26b9a2a290c.png)

**Comment by CvX** [comment]
Please upgrade to the latest version (2.28.0). It should fix this issue.

**Comment by tonyyang924** [comment]
it works fine~ thx!

![2019-02-14 4 36 27](https://user-images.githubusercontent.com/12247447/52773780-b73ccc80-3076-11e9-87b3-d976f35198d9.png)
