### ISSUE TITLE
Desktop notifications cease when Caprine is minimised to the tray

### ISSUE THREAD

**Issue by r0tekatze** [sindresorhus/caprine#777]
On Windows 7, when I click the tray icon to reduce Caprine to the tray, it also ceases to display the notifications that normally display when the Caprine window is open.

**Comment by CvX** [comment]
Couldn't reproduce this problem. I've just tried the latest Caprine version (2.28.0) on Windows 7 and I was able to receive notifications when minimized (both to task bar and to tray).

**Comment by r0tekatze** [comment]
Updated to 2.29.0, testing again.

**Comment by r0tekatze** [comment]
As of 2.29.0, this is no longer an issue.
