### ISSUE TITLE
dark mode - upon reloading, list turns gray

### ISSUE THREAD

**Issue by magnusundqvist** [sindresorhus/caprine#778]
MacOS Mojave, dark mode enabled.
If Caprine looses connection with chat and you press cmd + R in order to reload/refresh the app the list of ongoing chats turns back to bright mode whilst the chat itself stays in dark mode. 
To toggle between dark mode and non dark mode in the menu does not help. 
A swich to work chat does help, so does a reboot of Caprine.

Thnx for a awesome app, keep up the good work!
Best regards!

**Comment by CvX** [comment]
This issue is tracked in #712.

**Comment by magnusundqvist** [comment]
Thank you, i searched but could not find this. I see you in #712
