### ISSUE TITLE
Message buttons not working on Mac

### ISSUE THREAD

**Issue by amilasokan** [sindresorhus/caprine#779]
None of the bottom buttons respond on tap or show the emoji/sticker popup.

**Comment by amilasokan** [comment]
![screen recording 2019-02-13 at 5 19 03 pm](https://user-images.githubusercontent.com/36857049/52714607-bbec7c80-2fb3-11e9-9aa9-b1b299575f26.gif)

**Comment by rwojnarowski** [comment]
Same issue for me. I'm on newest version of Caprine. Sometimes buttons will respond but after long wait (about 30 second) or sometimes it will crash completely:
<img width="514" alt="caprine" src="https://user-images.githubusercontent.com/7086808/52717678-ef261000-2fa1-11e9-812b-92204f93fc14.png">

Caprine Version `2.28.0 (2.28.0.1220)`
Mac OS X `10.14.3`

**Comment by alexandrepa** [comment]
Same issue for me on Windows 10 with the last version of Caprine !

**Comment by whitecrownclown** [comment]
@alexandrepa @rwojnarowski @amilasokan 

I tried the latest version as well on macos 10.14.3 and it's not occuring. Maybe it's related to caprine settings.

Could you do one of the following: *First backup your settings, just in case*

- upload/screenshot settings "Debug > Show Settings" to view them
- delete settings "Debug > Delete Settings" and retry
- open devtools (fn+12) before clicking the buttons and paste here any error you see

Thank you!

**Comment by amilasokan** [comment]
<img width="980" alt="screen shot 2019-02-13 at 8 48 02 pm" src="https://user-images.githubusercontent.com/36857049/52728743-47283b00-2fd1-11e9-960d-73b38e7f9d05.png">

**Comment by amilasokan** [comment]
<img width="980" alt="screen shot 2019-02-13 at 8 48 02 pm" src="https://user-images.githubusercontent.com/36857049/52728849-763eac80-2fd1-11e9-95e7-47651a292f6d.png">

**Comment by amilasokan** [comment]
<img width="1440" alt="screen shot 2019-02-13 at 8 54 35 pm" src="https://user-images.githubusercontent.com/36857049/52728918-979f9880-2fd1-11e9-9b92-e3ed3606b1b2.png">

**Comment by alexandrepa** [comment]
Same error here !

**Comment by CvX** [comment]
@amilasokan Thanks for the screenshot! I've submitted a fix (more of a workaround really): #781

**Comment by amilasokan** [comment]
Solved the issue. This is the code change I made, Please update the app.

window.onload=function(){
async function withMenu(menuButtonElement, callback) {
    const { classList } = document.documentElement;
    // Prevent the dropdown menu from displaying
    classList.add('hide-dropdowns');
    // Click the menu button
    menuButtonElement.click();
    // Wait for the menu to close before removing the 'hide-dropdowns' class
    const menuLayer = document.querySelector('.uiContextualLayerPositioner:not(.hidden_elem)');
    const observer = new MutationObserver(() => {
        if (menuLayer.classList.contains('hidden_elem')) {
            classList.remove('hide-dropdowns');
            observer.disconnect();
        }
    });
    observer.observe(menuLayer, { attributes: true, attributeFilter: ['class'] });


		await callback();
	}

**Comment by amilasokan** [comment]
![screen recording 2019-02-14 at 12 15 22 am](https://user-images.githubusercontent.com/36857049/52740990-cc214d80-2fed-11e9-8cc9-6929ea9326ed.gif)
