### ISSUE TITLE
No Messenger Icon in the Task Manager

### ISSUE THREAD

**Issue by cwilli34** [sindresorhus/caprine#78]
Only a white box appears.  There is no messenger icon in the task manager.
![caprine_screenshot](https://cloud.githubusercontent.com/assets/9610352/14614999/a05ff556-0571-11e6-9cd8-45c390b93dfa.png)

-

Caprine 1.1.0
linux x64 4.4.6-1-MANJARO
DE: KDE Plasma 5

**Comment by sindresorhus** [comment]
Upgrade Caprine. This was fixed a long time ago https://github.com/sindresorhus/caprine/commit/c150350d547070b56db7f576ed7a6ff23c3d0a3d.

**Comment by forivall** [comment]
My bad, I haven't been using caprine much, so I haven't been keeping the aur PKGBUILD up to date.

@cwilli34 do you want to be a co-maintainer on aur?

**Comment by cwilli34** [comment]
@forivall I don't really have too much time to do it.  Just trying to get it working on my own Linux distro good.  I am having a lot of issues with Caprine at the moment in Manjaro with KDE.  Caprine doesn't stay in the task manager after about a minute.  Just disappears.  I have not worked with Electron much, so I don't know if I am missing dependencies or not, because I don't have Electron installed on my system.  

Please reference #79 in regards to the pkg in AUR.  There are some issues installing it.  I had to edit the pkg build file to get it to work.  Not sure how to debug the icon in the task manager issue.
