### ISSUE TITLE
Some pop-up windows are not displayed.

### ISSUE THREAD

**Issue by AreD** [sindresorhus/caprine#792]
Some pop-up windows do not appear or do not respond.
![example](https://habrastorage.org/webt/av/vf/yk/avvfykg0i3vshbibzbl6przdovc.gif)

Developer tools has error:
```js
Uncaught (in promise) TypeError: Cannot read property 'click' of null
    at selectMenuItem (VM91 browser.js:42)
    at withSettingsMenu (VM91 browser.js:289)
    at withMenu (VM91 browser.js:35)
    at withSettingsMenu (VM91 browser.js:38)

```
---

Caprine 2.29.0
Electron 4.0.4
darwin 15.6.0
Locale: en-US

**Comment by dusansimic** [comment]
This issue doesn't occur on the latest version of Caprine. Please update to the latest version.
