### ISSUE TITLE
Dark theme not working on Windows 10

### ISSUE THREAD

**Issue by samomiklavc99** [sindresorhus/caprine#799]
When I updated the app to 2.30.0 the dark mode doesn't work anymore so the app is constantly in light mode regardless if setting for dark mode is on or off. I have tried to change the setting and reinstall the app but issue is still present.

---

Caprine 2.30.0
Electron 4.0.1
win32 10.0.17763
Locale: sl

**Comment by CvX** [comment]
Could you take a screenshot of the issue? I couldn't reproduce it on my win10 PC.

**Comment by samomiklavc99** [comment]
![image](https://user-images.githubusercontent.com/46385168/53807720-94545880-3f50-11e9-8377-e4520f56e669.png)

**Comment by prediscover** [comment]
I could not reproduce this issue either.
Works fine.


Caprine 2.30.0
Electron 4.0.1
win32 10.0.17763
Locale: en

**Comment by samomiklavc99** [comment]
It's working now in 2.30.1 as normal

**Comment by dinamic** [comment]
It sounds like the problem is resolved already. @samomiklavc99 do you mind closing this issue?

Thanks :)

**Comment by samomiklavc99** [comment]
You can close it
