### ISSUE TITLE
Question: how does this work?

### ISSUE THREAD

**Issue by mrjjwright** [sindresorhus/caprine#8]
Silly question.  But where is the source code for this app?  I don't understand how it works.  I am familiar with Electron but where is the actual source code for the app?

**Comment by arthurvr** [comment]
It's simply an electron wrapper around facebook's site: https://github.com/sindresorhus/caprine/blob/07aab55954cb95012a07b913c7414ce266fd71cb/index.js#L47, if that's what you're wondering about.

**Comment by mrjjwright** [comment]
Oh thanks!  I had no idea that site existed.
