### ISSUE TITLE
Can't forward images

### ISSUE THREAD

**Issue by AnamolRajbhandari** [sindresorhus/caprine#801]
Can't forward images to friends. The forward box isn't visible but if i hover over the image, I cursor changes to clickable icon so I'm guessing the forward box's height is not right. 

---

Caprine 2.30.0
Electron 4.0.5
darwin 18.2.0
Locale: en-US

**Comment by whitecrownclown** [comment]
@AnamolRajbhandari Could you attach a screenshot or give more details? Which forward button are you referring to? There's more than one.
<img width="451" alt="screenshot 2019-02-27 at 17 53 01" src="https://user-images.githubusercontent.com/8309417/53503419-ae0d2000-3ab8-11e9-8459-39b251db8032.png">
<img width="1260" alt="screenshot 2019-02-27 at 17 53 40" src="https://user-images.githubusercontent.com/8309417/53503420-ae0d2000-3ab8-11e9-857e-bdc08e6abe93.png">

**Comment by AnamolRajbhandari** [comment]
Both of them do not work. I just tried again.

**Comment by AnamolRajbhandari** [comment]
I'm on MacOS Mojave 10.14.3

**Comment by tuchandra** [comment]
Experiencing this as well, same OS. Neither forward button works for me (I can click to open an image without issue). No messages in the console either.

**Comment by kypes** [comment]
Also having this issue on the latest version 2.33.0 - Windows 10 Build 1903.

**Comment by CvX** [comment]
@kypes I can confirm that. Looking into it.

**Comment by whitecrownclown** [comment]
@CvX 

<img width="320" alt="Screenshot 2019-06-28 at 19 42 40" src="https://user-images.githubusercontent.com/8309417/60357655-e841ec00-99dc-11e9-9ab1-06d5fb023218.png">

Apparently the dialog is hidden.
