### ISSUE TITLE
display bug for shared videos

### ISSUE THREAD

**Issue by crshlx** [sindresorhus/caprine#805]
Hi, it's been a while since this display bug for shared videos exists on Caprine.

Caprine 
<img width="629" alt="capture d ecran 2019-03-01 a 19 13 16" src="https://user-images.githubusercontent.com/18457418/53657519-aaaf9b00-3c56-11e9-9272-eb1a3c5335e9.png">

Messenger.com
<img width="511" alt="capture d ecran 2019-03-01 a 19 14 45" src="https://user-images.githubusercontent.com/18457418/53657530-b307d600-3c56-11e9-9856-039b320c69dc.png">

Caprine
<img width="1135" alt="capture d ecran 2019-03-01 a 19 15 36" src="https://user-images.githubusercontent.com/18457418/53657541-b8fdb700-3c56-11e9-805e-14a0d03648e2.png">

Messenger.com
<img width="726" alt="capture d ecran 2019-03-01 a 19 15 19" src="https://user-images.githubusercontent.com/18457418/53657554-c2871f00-3c56-11e9-80d7-d67c5ffb81ec.png">

Caprine 2.30.0
macOS 10.14.3
Locale : be-FR

**Comment by CvX** [comment]
This one is caused by https://github.com/sindresorhus/caprine/pull/382, cc: @dusansimic
