### ISSUE TITLE
Reimplement retired messenger functionality of arrow keys to switch chats

### ISSUE THREAD

**Issue by oisinhenry** [sindresorhus/caprine#806]
Messenger web used to have this functionality of using the up/down arrow keys to switch through conversations when no text box was in focus. May make a PR for this eventually but don't currently have the time on my hands.

**Comment by sindresorhus** [comment]
We already have keyboard shortcuts for this:

<img width="456" alt="screen shot 2019-03-04 at 11 04 40" src="https://user-images.githubusercontent.com/170270/53709909-55010b80-3e6d-11e9-858f-82bafba81c50.png">

I don't really see the point in adding more. The shortcuts we support are also universal for most apps and can be used at any time in Caprine, not just when the text field is *not* focused.

**Comment by CvX** [comment]
Btw. currently the Messenger's shortcut for moving between conversations is alt-up and alt-down.

**Comment by oisinhenry** [comment]
Appreciate the insightful response. Wasn't aware of all this to be
perfectly honest.
