### ISSUE TITLE
The code execution cannot proceed because node.dll was not found

### ISSUE THREAD

**Issue by drt0** [sindresorhus/caprine#807]
Hi, I get this error when I updated to latest windows version. Error message also says "Reinstalling the program may fix this problem" but I get the same error again.

**Comment by sindresorhus** [comment]
Do you happen to have some anti-virus software installed? Usually, this kind of error is the result of anti-virus incorrectly detecting something and removing files.

**Comment by drt0** [comment]
> Do you happen to have some anti-virus software installed? Usually, this kind of error is the result of anti-virus incorrectly detecting something and removing files.

I only have Windows Defender, I got a warning before running the installer but I told it to install anyway.

**Comment by sindresorhus** [comment]
Closing as there isn't anything we can do about this. Most likely it's just your computer doing something dumb.

**Comment by rstacruz** [comment]
Hey there, just leaving one data point here: running this in Windows 10 Home gets me a Windows SmartScreen warning.

> ![image](https://user-images.githubusercontent.com/74385/63206121-f9ac9800-c0f1-11e9-8fa5-1465eb9feea8.png)

To get around this, I had to go to `Properties...` on the installer file and check `Unblock`.

> ![image](https://user-images.githubusercontent.com/74385/63206145-4bedb900-c0f2-11e9-83cd-0be1610ff304.png)

Hope this helps any Windows 10 users trying to install this app!

**Comment by yllekz** [comment]
Commenting on this as the soft block still displays when you go to run the latest installer. Is there any way to get this to not be recognized by Defender SmartScreen as a risk?
