### ISSUE TITLE
Error on quit

### ISSUE THREAD

**Issue by adrienhuchet** [sindresorhus/caprine#809]
<img width="532" alt="capture d ecran 2019-03-05 a 16 00 11" src="https://user-images.githubusercontent.com/22013150/53814411-da64e880-3f5f-11e9-9312-8625bf7ef8f1.png">
when I minimize the app and right click on the icon and click on quit this error show up

**Comment by whitecrownclown** [comment]
@adrienhuchet What version of `Caprine` are you using? I don't see it happening on v2.30

**Comment by adrienhuchet** [comment]
<img width="289" alt="capture d ecran 2019-03-05 a 21 51 12" src="https://user-images.githubusercontent.com/22013150/53836685-e4eba600-3f90-11e9-9ea8-b2894e4280f7.png">

I use v2.30

**Comment by sindresorhus** [comment]
@adrienhuchet Does it happen every time? I tried reproducing it with the same Caprine version and I'm not seeing the error.

**Comment by adrienhuchet** [comment]
No, it does not happen every time. I have not had the error lately !

**Comment by ookangzheng** [comment]
I have this issue sometimes bad internet or sleep and wake up Mbpr will cause this problem

**Comment by sindresorhus** [comment]
If someone can reliably reproduce this, please open an issue on https://github.com/electron/electron
