### ISSUE TITLE
REQUEST: Autorefresh after selected time.

### ISSUE THREAD

**Issue by matjaz132** [sindresorhus/caprine#810]
Hello!

I don't know if I'm requesting features right but having auto refresh would really help. After a while, when chat becomes long, the program starts to use a lot of RAM. Refreshing program releases a lot of program's RAM. The problem becomes visible, when you have program opened on a remote/local computer ( server (PC always on)) and you chat via mobile. That computer gets clogged RAM, and other programs start to slow down. 

Thank you!

**Comment by mirouhml** [comment]
Yea I just started using this software after it was open for less than 24h it became slow so I checked the RAM usage and it was around 2.5GBs, I think an auto-refresh for this software will be a good addition.

**Comment by sindresorhus** [comment]
I don't think auto-refresh is a good idea as you might be in the middle of writing a message when it refreshes. We could have some smart heuristics to try to prevent that, but it's not easy to make it perfect.

**Comment by allanlaal** [comment]
its because its using Chromium, which is the best memflooder in the browser world

**Comment by z-ax** [comment]
> I don't think auto-refresh is a good idea as you might be in the middle of writing a message when it refreshes. We could have some smart heuristics to try to prevent that, but it's not easy to make it perfect.

It can just check if window is in focus and not refresh if it is, refresh otherwise. If it's periodic, it will help anyways :)
