### ISSUE TITLE
Caprine reloads every time I change chats

### ISSUE THREAD

**Issue by KTamas** [sindresorhus/caprine#812]
Every time I click on a new chat, Caprine reloads. It started about a day and a half ago.

**Comment by Spyruf** [comment]
I had the same issue and then it just stopped working as well (all the graphics didn't seem to be loading properly).

**Comment by T-Zahil** [comment]
Same for me

**Comment by AyushSingh13** [comment]
Same here for me - I'm using the Messenger for Mac app as a fallback

**Comment by KTamas** [comment]
yeah I switched back to Goofy for now. A shame as I prefer Caprine.
