### ISSUE TITLE
Login page not loading

### ISSUE THREAD

**Issue by tackoo** [sindresorhus/caprine#815]
After logging out app stuck in this page: https://imgur.com/a/dC9sl7k

Edit: Even though my email and password did not appear as I typed, I was able to login after typing them correctly. Then the app was working fine after logging in.
---

Caprine 2.30.0
Electron 4.0.5
darwin 18.2.0
Locale: en-US

**Comment by sindresorhus** [comment]
Probably because Facebook was down the other day.
