### ISSUE TITLE
input bug (iBus, Korean, snap) 

### ISSUE THREAD

**Issue by jjangga0214** [sindresorhus/caprine#819]
Hi. 

I installed caprine as snap app on ubuntu 18.10 using ibus as input method.
I found that writing Korean doesn't work as expected. Every time I write a block(Korean writing system's minimal component), it literally breaks. I had to repeatedly write them to complete the sentence.  I found this happens on facebook.com on chrome as well. Wonder why this happens and if it's a bug of electron or not.

Thanks.

**Comment by ComputerPark** [comment]
+1. Happening here too.
on Ubuntu 18.10 and using ibus (hangul) as Korean input method.

**Comment by sindresorhus** [comment]
Maybe there's a Snap "plug" we need to add for this. It was the case with missing camera support: https://github.com/sindresorhus/caprine/pull/813 I'm not familiar enough with Snap to answer this.

**Comment by trmaphi** [comment]
I'm using iBus normally on caprine to in [ibus-teni](https://github.com/teni-ime/ibus-teni).
