### ISSUE TITLE
Ubuntu badge notifications 

### ISSUE THREAD

**Issue by wojciechgizynski-kreditech** [sindresorhus/caprine#820]
Hi there, thanks for your work! I'm trying to get Caprine to show badges when new messages come. I'm on Ubuntu 18.04 LTS, I have Ubuntu dock enabled in Gnome Tweaks. There's [a script](https://paste.ubuntu.com/25615125/) that tests if the badge support is active and it is. But I'm not seeing any badges from Caprine. Any help?

**Comment by sindresorhus** [comment]
Might be related to https://github.com/electron/electron/issues/16001 or might be another problem.

What Caprine installer type (Snap, DEB, etc) do you use?

**Comment by wojciechgizynski-kreditech** [comment]
I've installed Caprine directly from Ubuntu Software Center:

![Screenshot from 2019-03-18 13-33-30](https://user-images.githubusercontent.com/47739695/54530322-bbfce500-4982-11e9-8463-ba09023aaba0.png)

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/caprine/issues/819#issuecomment-473891363. Maybe there's a Snap "plug" we're missing.

**Comment by wojciechgizynski** [comment]
Shall I try reinstalling using a different method?

**Comment by sindresorhus** [comment]
Yes, try the DEB.

**Comment by jayarjo** [comment]
@sindresorhus did you have any success? 

From what I understand it is impossible to show badge in Ubuntu 18.04, since it is not based on Unity anymore.

**Comment by TryHardDood** [comment]
This might help: https://github.com/signalapp/Signal-Desktop/pull/3390

**Comment by firasdib** [comment]
Whats the status on this? No notifications on Manjaro Gnome for me.

**Comment by dusansimic** [comment]
Stale and afaik indicators don't work since notifications are removed from messenger website. Once that issue is fixed, if this issue is still there we'll reopen this one.
