### ISSUE TITLE
Certain chats have broken formatting 

### ISSUE THREAD

**Issue by groundhogxp** [sindresorhus/caprine#821]
Hi,

For some reason, some of my chats have broken formats, e.g. profile photos don't show up, read receipts taking up too much space on the side, sticker becoming profile photo.

<img width="536" alt="Screen Shot 2019-03-18 at 4 58 59 PM" src="https://user-images.githubusercontent.com/26798840/54571267-24f25600-499f-11e9-86c3-250c1ba9a5df.png">

**Comment by dusansimic** [comment]
From what I see from the image, profile photos are not loaded which is a problem with Messenger and not Caprine. If there are some specific issues regarding other formatting and if you have images of those, please ping this issue. For now I will close this.
