### ISSUE TITLE
Feature Request: Add more info on About window

### ISSUE THREAD

**Issue by baltzyee** [sindresorhus/caprine#824]
Would you think it is good to add more information about the system and the app on the About window, like Microsoft VS Code does:

![Sketch](https://user-images.githubusercontent.com/48568695/54771242-87e92480-4c0d-11e9-870e-376401a26972.png)

Maybe also a copy button. It may be useful. Like the app! Cheers!

**Comment by sindresorhus** [comment]
Why? That's not really relevant for the average user.

**Comment by baltzyee** [comment]
OK! I close it the issue 😀 Thank you!
