### ISSUE TITLE
Menu icon missing in 2.30.1 Linux

### ISSUE THREAD

**Issue by linuxlite** [sindresorhus/caprine#826]
Using the 64bit deb package on Github. See below, self explanatory:

![Screenshot_2019-03-22_13-20-31](https://user-images.githubusercontent.com/5382578/54793022-76535b80-4ca5-11e9-9740-63f1491b9a52.png)

Icon has been there in previous versions.

**Comment by linuxlite** [comment]
Simple fix.

1. Resize icon from 1024x1024 in 0x0 dir. to 48x48 and move icon to 48x48 dir.
2. Rebuild hicolor icon-theme.cache

`sudo gtk-update-icon-cache /usr/share/icons/hicolor/`

Icon now appears in Menu.

**Comment by Leny1996** [comment]
I don't have 0x0 dir in /usr/share/icons/hicolor/ and in 48x48 there is caprine icon, also in other directories I can find them.

Command didn't changed anything.

**Comment by yerbestpal** [comment]
The proposed workaround for this issue doesn't seem to work for myself since there is no /usr/share/icons/hicolor/0x0 directory.

**Comment by dusansimic** [comment]
This is fixed in the latest release. Please update Caprine.
