### ISSUE TITLE
Webcam selection option

### ISSUE THREAD

**Issue by bourretbrandon** [sindresorhus/caprine#829]
I'm using a laptop with a built-in webcam (bad quality) AND an external USB webcam (good quality). I wish to use Caprine with the good external webcam and not the bad built-in webcam. But I can't find any settings in Caprine (or in my Linux Mint distro) that will allow me to select which webcam to use. The "uvcview" driver runs both webcams, so blacklisting that module is not an option. Any help (or a feature in Caprine to select a webcam) would be appreciated. Thanks for a great tool otherwise.

---

Caprine 2.30.1
Electron 4.1.0
linux 4.15.0-46201903221420-generic
Locale: en-US

**Comment by bourretbrandon** [comment]
What I did finally manage to do was create a udev rule to blacklist/disable my built-in webcam by its device ID. Now the only webcam the system and Caprine sees is my external USB webcam. I never want to use the built-in webcam anyway, so problem sort of solved. But moving forward, it would be nice if Caprine could have an option to select which webcam to use. Thanks again.

**Comment by sindresorhus** [comment]
I think you can select the webcam when doing a call in the Messenger interface.

**Comment by maxowp** [comment]
1) go to Applications.
2) select "caprine". 
3) clic on "autorisation".
4) check/uncheck what you want. 

![Capture d’écran de 2019-03-29 15-01-07](https://user-images.githubusercontent.com/49069695/55238712-7a4b2480-5235-11e9-8ab6-6cdfc10605fa.png)
