### ISSUE TITLE
UI completely broken since recent messenger change

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/caprine#830]
Some point last week there was the message "A new version of messenger is available, click to reload". Since reloading, my app looks like this:

<img width="1278" alt="Screenshot 2019-03-26 at 21 17 04" src="https://user-images.githubusercontent.com/10532611/55030664-22ca7000-500d-11e9-8ae3-5409995871fc.png">

**Comment by CvX** [comment]
Looks like you won the A/B testing or early rollout lottery. 😉 Any visual differences on the https://messenger.com?

**Comment by felixfbecker** [comment]
Not noticing anything

**Comment by CvX** [comment]
@felixfbecker any change?

**Comment by felixfbecker** [comment]
Interesting, it fixed itself.
