### ISSUE TITLE
UI Background Change on Refresh

### ISSUE THREAD

**Issue by n3a9** [sindresorhus/caprine#833]
On macOS 10.14.4, Dark mode enabled. I have the full-window vibrancy enabled. On refresh the background changes to a different, unreadable color. 

![caprine_refresh_ui_bug](https://user-images.githubusercontent.com/7104017/55178205-f3258000-5152-11e9-94f1-ed70958a83d8.gif)

**Comment by CvX** [comment]
The issue is tracked in #712 🙂
