### ISSUE TITLE
Not getting desktop notifications

### ISSUE THREAD

**Issue by teomor** [sindresorhus/caprine#834]
No steps to reproduce really. Just receiving messages and the dock count works but the banners don't show up. Sometimes they do, but most of the time they don't.

---

Caprine 2.30.1
Electron 4.1.0
darwin 18.5.0
Locale: en-GB

**Comment by Distearth** [comment]
Same

**Comment by maxoku** [comment]
Same in Windows 8.1. No notifications and no option in settings like it was disabled and hidden by purpose.

**Comment by sugat009** [comment]
Same in Manjaro 20. Notifications not showing up. Sounds are working though.

**Comment by dusansimic** [comment]
Tracking this issue on #1562
