### ISSUE TITLE
Notifications delivered multiple times - macOS Mojave

### ISSUE THREAD

**Issue by clerkenwellconsulting** [sindresorhus/caprine#836]
First of all, I must say that Caprine is great, the only Messenger client good enough to use on a daily basis in macOS.

The issue I'm facing is that it seems that notifications about new messages are delivered either the laptop reconnects to the internet or just wakes up from sleep. So if I say I have a notification about 2 new messages and I don't reply immediately, next time I reconnect to the internet I get a notification about the same two messages, which sometimes can be pretty annoying

**Comment by equals215** [comment]
Same here !

**Comment by dusansimic** [comment]
Closing since it's stale and the notifications were removed from Messenger website so they don't exist either way for now.
