### ISSUE TITLE
Refreshing and updating (messenger.com update) breaks the interface

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#839]
- When the app misbehaves and I want to reload it without relaunching, I tend to use Electron's CMD-R.
- When messenger.com displays a banner that it has an update and you click it

Caprine's colors and sidebar will be broken. Transparent parts become white and almost everything looks bad.

<img width="839" alt="Screenshot 2019-04-04 at 10 22 31" src="https://user-images.githubusercontent.com/866694/55540604-9f231a00-56c3-11e9-9c2f-1d97c24f849b.png">

**Comment by CvX** [comment]
The issue is tracked in #712 🙂
