### ISSUE TITLE
Default audio device not respected on some devices

### ISSUE THREAD

**Issue by JoniVR** [sindresorhus/caprine#840]
I've been having this issue for quite some time now and decided to make an issue to see if I'm the only one experiencing this.

## Description
Whenever I select my monitor as an audio output device, all caprine sounds still output through my internal speakers. So if I mute my monitor sound (when the monitor is the default audio device), it will still play sounds through the internal Macbook speakers.

I tested if it was any other tool I'm using (MonitorControl would be a possible candidate for causing issues) but it wasn't. I'm thinking this might be an electron bug? It only seems to happen with my monitor, I tested it with my Airpods and it seemed to be fine. 

## Steps to reproduce
1. Set monitor as default audio device (mine uses displayport)
2. Mute monitor sound
3. Trigger notification
--> The sound will still output through internal Macbook speakers.

I'm sure this won't be reproducible for everyone, but I'm pretty sure it's either electron or caprine. 

Anyone else experiencing this? Any ideas what it could be? Let me know if you want my to test some other stuff.

<hr>
Caprine 2.30.2 (2.30.2.1338)

macOS 10.14.4

I've been having this issue for several macOS and Caprine versions though (as long as I can remember)

**Comment by JoniVR** [comment]
Okay, I tested it with the [electron-api-demos application](https://github.com/electron/electron-api-demos) (v2.0.2) and it seems to happen there as well. So this is most probably an electron bug.

**Comment by whitecrownclown** [comment]
Related electron issues: https://github.com/electron/electron/issues/12365 and https://github.com/electron/electron/issues/12311
