### ISSUE TITLE
New Features: Active Contracts

### ISSUE THREAD

**Issue by MSQRD-dot-com** [sindresorhus/caprine#842]
Can you please add some/all of these features:

1) Add an active contacts button next to the create new message button to view active contacts

2) A keystroke to invoke active contact mode (I assume this one should be simple, maybe command-shift-a)

3) Much like the Facebook app, can you put minutes people have been inactive for? and add a yellow icon?

4) Can you add a green circle icon to match the facebook style

**Comment by CvX** [comment]
1. I'm not sure about this one. Caprine mostly just tweaks and fixes the UI rather than adds arbitrary elements to it. @sindresorhus?
2. Not opposed to that, but cmd-shift-a is already taken (it archives the current conversation)
3. & 4. That's a limitation of https://messenger.com

**Comment by sindresorhus** [comment]
Everything we add comes with a maintenance cost. I don't see 1 and 2 being worth the cost. 2 and 3 are not up to us.

You can add a keyboard shortcut for any menu item if you're on macOS:
https://www.intego.com/mac-security-blog/how-to-make-custom-keyboard-shortcuts-for-any-macos-menu-items-and-to-launch-your-favorite-apps/
