### ISSUE TITLE
Caprine blocks mobile notifications while open

### ISSUE THREAD

**Issue by dgghita** [sindresorhus/caprine#846]
If Caprine is open, mobile notifications for Messenger don't go through. I have tested this with 2 Android phones (Galaxy S8+ and Huawei P30 Pro) and an iPhone 7 Plus.

---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.18362

**Comment by CvX** [comment]
A side note: the 2.11.0 is over a year old now, the current version is 2.30.2.

Anyway, Caprine's behavior matches Messenger's, i.e. if you have https://messenger.com open it is as if you have the app open on your phone – it means you're "active" and all notifications/activity goes to that device.

**Comment by dgghita** [comment]
Thanks for the reply!

I expected them to still appear if, say, the app is out of focus, or the conversation is not the active one. Sounds like I need to untick the "active" box in the preferences to get the behavior I want. I'll play around with it and get back with the results. 

Regarding the version: that is strange. I have the latest one published on the Microsoft Store. Is that not supported anymore?

**Comment by dgghita** [comment]
I checked on the latest version and you are right. Both messenger.com and messengerfordesktop.com behave like this now. It would be great if it were able to not block mobile notifications while the app is out of focus (or, even better, for all but active conversation). Telegram does this well, by the way, and it's also quick to clear stale mobile notifications, but I guess there are some limitations when you're proxying FB's online messenger.

That said, I would be curious to know why the Store version isn't being updated anymore. It provides a more secure way to install and run apps in my opinion.

**Comment by CvX** [comment]
Yeah, I don't think there's much we could do. It's either:
* the app is "active" so it's notified on new messages, but other devices aren't
* or: we somehow block all the communication with messenger.com when the window is in the background – other devices get notifications, but the app doesn't get any sounds, notifications, or badges

…so, not much of a choice, really.

And the Microsoft Store version? There's an explanation in its description: "(…)Originally created by Sindre Sorhus at https://github.com/sindresorhus/caprine, this Windows Store version has been forked and packaged with the creator's consent.(…)"

The fork is located at https://github.com/nozzlegear/caprine and seems abandoned…

**Comment by dgghita** [comment]
Right. I figured it was an all or nothing type of deal. I did however notice that having Caprine open on multiple machines would sometimes give me notifications on both. Guess I should chalk that down to happenstance.

Regarding the Store app, apologies for failing to read the description. I went in completely assuming that it was part of the project.

Thanks for your help, it's clear now.
