### ISSUE TITLE
Blank screen after a while

### ISSUE THREAD

**Issue by wojciechgizynski** [sindresorhus/caprine#847]
I'm on Ubuntu 18.04 LTS, have been using Caprine for a while now. This usually happens over night - I lock the screen, leave the machine running and when I get back to it after ~14 hours Caprine has a blank white screen. There is no View>Refresh command or anything like that (e.g. Slack app does have it), so the only way I found to deal with that is to close the app and start it back again.

**Comment by dusansimic** [comment]
We've added Relaunch Caprine option (File -> Relaunch Caprine) which would reload Caprine.

**Comment by wojciechgizynski** [comment]
Thanks for letting me know.
