### ISSUE TITLE
Caprine can't load a single page from Messenger but can from Workplace

### ISSUE THREAD

**Issue by equals215** [sindresorhus/caprine#849]
Hi,
I'm currently struggling with Caprine on Mac OS Mojave 10.14.4 trying to open the main page of Messenger.
<img width="1030" alt="Capture d’écran 2019-04-08 à 16 48 59" src="https://user-images.githubusercontent.com/20166324/55801550-9a50d280-5ad6-11e9-8fdf-e178715d46dd.png">
As you can see on the screenshot, I'm only getting a blank page. This is happening since I've clicked on Reload to have the latest version of Messenger.
Tried to uninstall it from Apps folder, from homebrew, installed it back with several different versions either from the releases or from homebrew, it's still not working.

**Comment by dusansimic** [comment]
Hi! Is this issue resolved or does it still occur? This could be just a bug that took place when new Messenger design came out.
