### ISSUE TITLE
Can't compose a new message

### ISSUE THREAD

**Issue by chrismessina** [sindresorhus/caprine#850]
When I tap the "compose" button, the page refreshes but stays on the current chat, rather than opening the new message composer.

---

Caprine 2.30.2
Electron 4.1.3
darwin 18.5.0
Locale: en-US

**Comment by jaflo** [comment]
Is this still an issue? I cannot repro by clicking on the pen and paper icon in the sidebar.

**Comment by chrismessina** [comment]
I'm guessing this is no longer an issue. It can be closed.
