### ISSUE TITLE
Tell FB to mark messages as read

### ISSUE THREAD

**Issue by willashley23** [sindresorhus/caprine#852]
Whenever you read a message on Caprine, it doesn't inform Facebook that you've read the messages, so the Messenger app on my phone still has notification badges and inside the app it still has them marked as unread.

**Comment by spramij** [comment]
Would you be able to provide more info? I just tried with the app open on my phone, Caprine minimized on my PC, and after receiving a message on Messenger, the contact did get highlighted on the app, but as soon as I opened Caprine and switched to that conversation it got marked as read on my phone as well.

**Comment by willashley23** [comment]
I think the main difference is that I do not have the iOS app open on my phone at all when this happens. I may having a long conversation on caprine without ever checking my phone, and when I'm done and go to check it on iOS, the app has the last message sent by my friend highlighted as unread.

**Comment by spramij** [comment]
I've had both scenarios happen to me without any issues. I'm guessing it's an iOS specific issue
