### ISSUE TITLE
Request: Change notification sound

### ISSUE THREAD

**Issue by vico93** [sindresorhus/caprine#853]
Can this be done? I want to experiment with type.wma.

Thanks in advance!

**Comment by rachelyhe** [comment]
What environment are you working in, @vpontin?

This enhancement could probably be added by using Electron's [Notification event emitter](https://github.com/electron/electron/blob/master/docs/api/notification.md) and fiddling with the `sound` attribute. I'm sure you could add a sound selector and file upload for .wma files as well, though it would be cool to at least be able to set the notification sound to different system sounds.

**Comment by vpontin** [comment]
I'm currently using Caprine on Windows 10 x64.

In fact it doesnt to support .wma natively, i could just convert the sound (actually the msn notification sound) to mp3 or other format supported by Electron.
