### ISSUE TITLE
Very slow response when trying to move between conversations. Also is there any way to uninstall it?

### ISSUE THREAD

**Issue by patryczek803** [sindresorhus/caprine#854]
---

Caprine 2.30.2
Electron 4.1.3
linux 4.18.0-17-generic
Locale: en-GB

**Comment by Jonher937** [comment]
How did you install caprine? For example "AppImage" is not a package you install, so there's no way to uninstall a AppImage

**Comment by patryczek803** [comment]
Hi Jonathan,

Thanks for the reply. I am quite new to the Linux and I've already figured
it out.Thanks again.


KR,
Patryk

**Comment by Jonher937** [comment]
For the "slow response" I think there needs to be more info and how it can be reproduced.

**Comment by gklka** [comment]
It's an issue for me too. I'm using macOS Catalina and the app was installed from dmg. The issue exists since a few months now, so I don't think it is Catalina-related or anything. I use a 6-core i7 CPU.

This is what I experience: clicking conversations in the sidebar or navigating between them using keyboard shortcuts requires 1-3 sec to complete. So I click a name, 1-3 sec pasts and then Caprine switches to the new conversation. This used to be instant. Is this a Caprine regression or a messenger.com one?

**Comment by mlyle** [comment]
In general, it feels like Caprine falls apart after a few days of uptime.  On Linux, after a few days, CPU use creeps up to a constant 10-20%, and then shortly after that conversations take a long time to toggle.  I sort of suspect that GIFs make this much worse / trigger earlier, but I don't have a repro.

**Comment by googlebleh** [comment]
I'm also seeing responsiveness grind to a halt after long uptimes on Linux. Just like mlyle, it usually takes a few days, and results in upwards of 3 seconds to switch between conversations (both clicking, and Alt+up/down). My conversations don't typically have a lot of GIFs in them, but I'll keep an eye out now.

**Comment by mlyle** [comment]
Was there a fix for this?  I'm still seeing this on version 2.55.7.  I suppose bumping Electron, etc, could make a difference, but I'm not sure how you'd know it was fixed the same day those commits came in.

Currently takes 2.5 seconds to switch conversations on a fast M1 Max laptop after a few days of uptime.

**Comment by lefterisgar** [comment]
Yes, a new Electron version is on its way to the next release.

**Comment by lefterisgar** [comment]
Try [my fork](https://github.com/lefterisgar/caprine) and report whether it fixes the issue or not. We can reopen it if needed.

**Comment by mlyle** [comment]
> Try [my fork](https://github.com/lefterisgar/caprine) and report whether it fixes the issue or not. We can reopen it if needed.

Thank you!  I didn't realize there was a fork!  I'll probably hold off until a next release because it doesn't look like there's a MacOS package.
