### ISSUE TITLE
Update homebrew cask

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/caprine#86]
Thanks :)

**Comment by sindresorhus** [comment]
I unfortunately don't have time to submit a pull request to Homebrew Cask for every update.

Was hoping someone in the community would be willing to subscribe to the release feed: https://github.com/sindresorhus/caprine/releases.atom and do it on new releases.

-

// @victorpopkov @vinkla

**Comment by victorpopkov** [comment]
Sure, not a problem. I will try to keep it updated when making massive cask updates. The update to v1.3.0, however, was done in https://github.com/caskroom/homebrew-cask/pull/20876.

**Comment by sindresorhus** [comment]
Thank you @victorpopkov. I appreciate it :)

**Comment by vinkla** [comment]
👍
