### ISSUE TITLE
Blank Window and Icon

### ISSUE THREAD

**Issue by rahidulislam** [sindresorhus/caprine#864]
When I start caprine , it shows blank window. it can not show icon in menu bar. I use elementary os junu 5.
![Screenshot from 2019-04-21 11-35-18](https://user-images.githubusercontent.com/33887458/56465871-918ec380-6429-11e9-93cd-c08d5a916e2b.png)
![Screenshot from 2019-04-21 22 46 13](https://user-images.githubusercontent.com/33887458/56473023-96826000-6487-11e9-947f-d5a97bdfee3f.png)

---

Caprine 2.30.2
Electron 4.1.3
linux 4.15.0-47-generic
Locale: en-US

**Comment by dusansimic** [comment]
Regarding the blank icon, that issue is know. It's a bug in Electron builder and there is a workaround https://github.com/sindresorhus/caprine/issues/782#issuecomment-465383700.

Is the issue of Caprine not loading still there?
