### ISSUE TITLE
removed messages invisible in dark mode

### ISSUE THREAD

**Issue by Bellog** [sindresorhus/caprine#868]
When using dark mode, bubble <you removed a message> is completely white, making it impossible to read it.
Here is the link showing how it looks like: [imgur link](https://i.imgur.com/KI9E28a.png)

Steps to reproduce:
1. Turn on dark mode
2. delete any message for everyone

Caprine 2.25.1
Electron 4.0.1
win32 10.0.18362
Locale: en-US

**Comment by CvX** [comment]
This issue has been fixed in #757, you're using a 3 month old Caprine version (latest one is 2.30.2). 🙂
