### ISSUE TITLE
Messenger settings not responsive

### ISSUE THREAD

**Issue by rachelyhe** [sindresorhus/caprine#869]
When opening "Messenger Preferences", the popup does not resize on Mac. Ideally this would be fixed with the CSS height attribute and a scroll bar. 

Behavior seen here:
![image](https://user-images.githubusercontent.com/32414721/56691114-1d645200-66ad-11e9-91e2-a1f4be20aa30.png)
---
Caprine 2.30.2 (2.30.2.1338)
Mac OS 10.14.2

**Comment by CvX** [comment]
It is fixed in #843, it just wasn't released yet. 🙂
