### ISSUE TITLE
the snap version won't open

### ISSUE THREAD

**Issue by zany130** [sindresorhus/caprine#876]
Ubuntu 18.04 kernal 4.19.36

snap won't open trying to open form the terminal gives me this 
The SUID sandbox helper binary was found but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/caprine/22/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
  I have tried Uninstalling and reinstalling

**Comment by malyzeli** [comment]
Problem occurs only with latest Caprine version **`2.31.0`**.

To keep Caprine working you can rollback to previous version `2.30` using `snap revert` until issue is resolved.

```
> snap revert caprine
caprine reverted to 2.30.2
```

**Comment by boriseto** [comment]
He tried uninstalling and reinstalling again. I don't think that the "revert" command would help him since there is nothing to revert to now.

**Comment by malyzeli** [comment]
Yay, good point!
In that case downloading compiled release should work..
Btw is there any way to install specific version using snap CLI?

**Comment by boriseto** [comment]
Yes. Download the snap locally and then "snap install filename"

**Comment by weirdbricks** [comment]
Hello, 

I am seeing the same issue with `2.31.0` on Ubuntu 18:

Output:

```
$ caprine 
[24620:0429/082256.665293:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/caprine/22/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

Running with sudo gave me a different message: 

```
sudo caprine 
[sudo] password for lamprosc: 
mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Documents': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Desktop': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Downloads': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Music': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Pictures': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Videos': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Public': No such file or directory
ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Templates': No such file or directory
```

Snap version:

```
snap list
Name               Version                     Rev   Tracking  Publisher        Notes
caprine            2.31.0                      22    stable    sindresorhus     -
```

Ubuntu version:

```
cat /etc/issue.net 
Ubuntu 18.04.2 LTS
```

I reverted back to the previous version by using: 

```
sudo snap revert caprine
caprine reverted to 2.30.2
```

and caprine works again. Please let me know if there's any further details I can provide.

**Comment by vanushwashere** [comment]
Same  error on Ubuntu-based Kde Neon distro
Reinstalled manually as @boriseto suggested

**Comment by skiwichu** [comment]
Same issue on Ubuntu 19.04

**Comment by linuxxxer** [comment]
error: cannot revert "caprine": no revision to revert to
I tried to revert Caprine on Linux Mint 19.1, apparently this error I got

**Comment by sloika** [comment]
I also cannot revert it, so I downloaded the previous version (2.30.2). It works well so far.

**Comment by linuxxxer** [comment]
I installed the previous version too, works good, only icon is missing, but it doesn't matter for me.

**Comment by xaviervilla** [comment]
16.04 affected as well.

as malyzeli stated above, `snap revert caprine` fixed the issue immediately :+1:

**Comment by ztangent** [comment]
Seems like it's fine with the latest Caprine update! (Version, 2.31.1, installed using the .deb version, haven't tried through Snap.)

**Comment by yerbestpal** [comment]
@ztangent this issue is related to the snap build only.

**Comment by inoculos** [comment]
would chown allow those /Root files to be accessible? Just running as sudo wouldn't work and it seems odd that those files are in /Root

**Comment by inoculos** [comment]
> Hello,
> 
> I am seeing the same issue with `2.31.0` on Ubuntu 18:
> 
> Output:
> 
> ```
> $ caprine 
> [24620:0429/082256.665293:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/caprine/22/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap (core dumped)
> ```
> 
> Running with sudo gave me a different message:
> 
> ```
> sudo caprine 
> [sudo] password for lamprosc: 
> mkdir: cannot create directory '/run/user/0': Permission denied
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Documents': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Desktop': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Downloads': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Music': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Pictures': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Videos': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Public': No such file or directory
> ln: failed to create symbolic link '/root/snap/caprine/22/snap/caprine/22/Templates': No such file or directory
> ```

Seems off those files are in /Root. Would chown allow them to load? I am curious if thats is were they install in working versions.

**Comment by sindresorhus** [comment]
There's a new version out. Can you check if that works better?

**Comment by hhsnopek** [comment]
@sindresorhus it's now working on Ubuntu 18.04.2, kernel 4.15.0-1043, snap version 2.39

thank you for the release 🎉

**Comment by sindresorhus** [comment]
Great!

**Comment by Slapbox** [comment]
@sindresorhus can you describe how you resolved this?
