### ISSUE TITLE
Bug(?) with Caprine on Windows

### ISSUE THREAD

**Issue by harrisonjr98** [sindresorhus/caprine#877]
Hey there! First of all, I totally love Caprine on Windows and plan to leave a tip soon as a small thanks for making a smooth, free desktop container for Messenger that supports a good looking dark mode! I just am sending this to report a behavior that I believe to be a bug (but maybe it isn't!) When I see a notification badge on the taskbar icon to indicate a new unread message and go into the app and click the sender to view the message, the thread comes up as expected. However, the badge does not disappear from the icon until I send a reply or click another thread on the sidebar. I assume this is a bug because it doesn't match the behavior of Messenger.com itself, but if some people prefer this behavior it would be *really* nice to get a toggle to allow the badge to vanish the second the relevant thread is entered. Thanks for reading this, and again I really appreciate the app in the first place!

---

Caprine 2.30.2
Electron 4.1.3
win32 10.0.17763
Locale: en-US

**Comment by maxoku** [comment]
I can confirm that, it's annoying. It should make the badge vanish immediately after reading.

**Comment by harrisonjr98** [comment]
Glad it's not just me that was having this issue. I actually went back to using the browser version instead of Caprine, but would love to move back if this is solved. The first-party Messenger app released on the Microsoft Store recently is hot garbage, can't even see any of my Marketplace correspondence on it.

**Comment by dusansimic** [comment]
This is an old issue and the behavior is different now (it works as it's expected). It might have been fixed by the redesign. The indicators afaik don't work yet but that is another issue.
