### ISSUE TITLE
Messenger Preferences don't launch when sidebar closed & doesn't display properly when in Dark Mode

### ISSUE THREAD

**Issue by alechp** [sindresorhus/caprine#879]
Issue: `Messenger Preferences don't launch when sidebar closed & doesn't display properly when in Dark Mode`

Related: https://github.com/sindresorhus/caprine/issues/584

Recreate: 
1. Close sidebar
2. Shortcut: `CMD + ,` or Click: `Caprine` -> `Messenger Preferences`
3. Nothing happens

Examples:

**light - with sidebar closed**
No screenshot. Preferences modal simply doesn't launch.

**light (regular) mode - w/ sidebar open**
> Sidebar is opened and preferences open up just fine

<img width="1904" alt="preferences_light" src="https://user-images.githubusercontent.com/3058939/56869981-34f94e80-69bd-11e9-8cfd-ea52983ef65c.png">

**dark mode - w/ sidebar opened**
> Sidebar is opened and preferences open. But since dark mode is enabled, the non-dark mode preferences styles seems to break. 

<img width="1904" alt="preferences_dark" src="https://user-images.githubusercontent.com/3058939/56869992-5bb78500-69bd-11e9-8963-b756a181b867.png">

**Comment by CvX** [comment]
Inability to open preferences with sidebar closed is a known problem. Not sure if there was an issue added in this repo though. 👍 

The dark mode preferences issue I could not reproduce.

**Comment by alechp** [comment]
I see. Thanks for the confirmation

Which version of Caprine are you running? I’m on 2.31.0
