### ISSUE TITLE
Publish in the Mac App Store

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#88]
Would be nice and would give us auto-update functionality on OS X for free. I'm happy to do the actual publish, but I need help with setting up the build script and stuff.

https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#os-xmac-app-store-targets-only

https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md

**Comment by Kegley** [comment]
Would like this also

**Comment by Etheryte** [comment]
Wouldn't it be better to simply use [Electron's built-in auto-updater](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md)? That way you will get the latest version automatically out of the box and as an additional bonus you don't have to bother with the app store acceptance.

**Comment by sindresorhus** [comment]
It's not really about the auto-updating anymore, but the Mac App Store brings convenience for the user, so yes, it's worth it.

**Comment by AshikNesin** [comment]
@sindresorhus Anyone working on this?

**Comment by sindresorhus** [comment]
@AshikNesin It's [all set up](https://github.com/sindresorhus/caprine/blob/e4059b5bf05e2ee26c06c183d7b82393dcff2931/package.json#L64) on the builder side of things. I just couldn't get it to launch locally when built for MAS and it got rejected from the App Store for not launching. Help welcome to debug it.

**Comment by AshikNesin** [comment]
@sindresorhus Cool.. Will ping you if I find anything 😄

**Comment by sindresorhus** [comment]
Closing as it will not be possible to publish this to the App Store... https://github.com/sindresorhus/caprine/pull/903#issuecomment-529078516
