### ISSUE TITLE
Issues with Facebook Marketplace conversations in dark mode

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#881]
![Screenshot 2019-04-29 at 8 12 51](https://user-images.githubusercontent.com/866694/56878965-e7c9bb00-6a56-11e9-9fce-6276cf9cdb92.png)

1. little action icons are black on black at the top of the conversation

2. the marketplace item details section in the right column has also black on black texts

**Comment by panda7789** [comment]
1. fixed in #1147 
2. in attached PR
