### ISSUE TITLE
Caprine 2.31 Q4OS does not work

### ISSUE THREAD

**Issue by polska1** [sindresorhus/caprine#882]
At the bottom of the links to photos after opening the application and log.
The previous version 2.30.2 works ok
[](url)https://naforum.zapodaj.net/641d26640382.jpg.html
[](url)https://zapodaj.net/16aadd426e58b.jpg.html

**Comment by dusansimic** [comment]
Both links are broken. I'll open this if there is any new information. You can also drag and drop photos here so they would be saved on GitHub.
