### ISSUE TITLE
Missing Icons on Linux

### ISSUE THREAD

**Issue by truefriend-cz** [sindresorhus/caprine#888]
In last version missing icon. (deb package).

**Comment by Lyeuiechang** [comment]
https://github.com/sindresorhus/caprine/issues/826#issuecomment-475452989
 
linuxlite commented on 22 Mar

Simple fix.
1.     Resize icon from 1024x1024 in 0x0 dir. to 48x48 and move icon to 48x48 dir.
2.     Rebuild hicolor icon-theme.cache

`sudo gtk-update-icon-cache /usr/share/icons/hicolor/`

Icon now appears in Menu.

![圖片](https://user-images.githubusercontent.com/26355486/57181684-6eecb800-6ec9-11e9-8113-bcc63df8e4f9.png)

**Comment by xcom169** [comment]
> In last version missing icon. (deb package).

I'm also having this issue.

**Comment by dusansimic** [comment]
This is fixed in the latest build. Please update Caprine.
