### ISSUE TITLE
Focus text input on window.show()

### ISSUE THREAD

**Issue by zakius** [sindresorhus/caprine#890]
When toggled from tray (and WIP #827) message input box is not focused making it much harder to use keyboard only

**Comment by sindresorhus** [comment]
Are you on Windows? If so, I think this was an issue with the framework we use: https://github.com/electron/electron/pull/18080

**Comment by zakius** [comment]
I am

though it looks like webview gets focus, but on another element inside of it, since I can easily nabigate with `tab`

But I'll try checking if that patch changes anything and report back

**Comment by zakius** [comment]
Unfortunately I can't make it work with specified branch or commit of electron, but I assume that latest package (from 3 days ago) already includes this fix and it does not focus text input still
