### ISSUE TITLE
Change shortcut

### ISSUE THREAD

**Issue by mateuszbierkat** [sindresorhus/caprine#891]
Hi, I think we need opportunities to change shortcuts. In polish language it's necessary to press cmd + e to get ę but when I press this combination it shows insert emoji window. Can you add shortcuts setting to Caprine? It will be amazing!
---

Caprine 2.31.0
Electron 5.0.0
darwin 18.5.0
Locale: pl

**Comment by sindresorhus** [comment]
You can change any shortcut, see: https://github.com/sindresorhus/caprine#tip

**Comment by CvX** [comment]
The key combination to enter an "ę" character is actually `option + E`, which doesn't collide with any known Messenger/Caprine shortcuts.

**Comment by lukewma** [comment]
Hi Im just piggybacking on this
Are there any options for changing the keyboard shortcuts in windows? The tip only mentions mac, and creating specific ahk profiles would be a lot.
