### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by MicxSamonte** [sindresorhus/caprine#892]
**Steps to Reproduce**
1. Open Caprine as windowed mode
2. Wait for the last conversation to load
3. Click a conversation (in my case, a group chat)
4. Click an image inside the conversation or wait for a few seconds
5. White screen of death

---

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17134
Locale: en-US

**Comment by dusansimic** [comment]
I couldn't reproduce this. Try updating to the latest Caprine version.
