### ISSUE TITLE
dark mode - message requests - text unreadable

### ISSUE THREAD

**Issue by rtpHarry** [sindresorhus/caprine#896]
If somebody tries to contact you that isn't in your friend list, for example via a group you're in, then it comes in under the new messages requests.

The confirmation question is currently showing as dark unreadable text:

![image](https://user-images.githubusercontent.com/1038062/57434769-533d3500-726e-11e9-812a-0144e0dd7856.png)

**Comment by mikigal** [comment]
Fixed in PR #971
