### ISSUE TITLE
Messenger does not update nor show new message notifications after random period

### ISSUE THREAD

**Issue by dodancs** [sindresorhus/caprine#898]
Launch the app. Leave it running and occasionaly reply to messages. After a while people start calling me and my friends to tell me that I did not read their message. I then refresh the client using Ctrl+R and it shows the new messages... This is completely unusable. Please fix.

---

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by marcus13345** [comment]
this is an issue for me as well, here are my specs: 

Caprine 2.23.0
Electron 3.0.12
win32 10.0.17134
Locale: en-US

**Comment by ashtonx** [comment]
Same Issue. Stuff arrives on phone without problem.

Caprine 2.30.2
Electron 4.1.4
linux 5.0.13-arch1-1-ARCH
Locale: en-US

**Comment by pkuczynski** [comment]
I am also experiencing the same issue :(

Caprine 2.31.0
macOS 10.14.4

**Comment by pkuczynski** [comment]
Duplicate of #893?

**Comment by Nawor3565** [comment]
Here too

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by jeremyclement** [comment]
Same for me

**Comment by realtaras** [comment]
Yep, I have this issue too.

Version 2.33.1 (2.33.1.1510)
MacOS: 10.14.5

**Comment by lotus42** [comment]
Also have this issue.

Version 2.34.0 (2.34.0.1549)
MacOS: 10.14.5

**Comment by Spounka** [comment]
same here, Arch Linux
Version: 2.56.1-2
uname -a: Linux spounka-pc 5.19.9-arch1-1 SMP PREEMPT_DYNAMIC Thu, 15 Sep 2022 16:08:26 +0000 x86_64 GNU/Linux

**Comment by dusansimic** [comment]
Stale and can't reproduce
