### ISSUE TITLE
Is there overview of how this works?

### ISSUE THREAD

**Issue by techsin** [sindresorhus/caprine#900]
I wanted to contribute, yet I'm unable to reverse engineer the code. Not sure when notification is facebook one or desktop one. It looks like facebook is being opened in the background and being interacted with. Not sure where though. 

Can someone give 5 minute overview of what's happening.

**Comment by borowyalan** [comment]
@techsin We could try to make the dev documentation happen, if you are still interested. Seems like a nice learning opportunity.

**Comment by techsin** [comment]
yea why not.

**Comment by borowyalan** [comment]
Please leave me a message at borowyalan@gmail.com so we can discuss it further.
