### ISSUE TITLE
Auto-scrolling not working when receiving new messages

### ISSUE THREAD

**Issue by SongRongLee** [sindresorhus/caprine#902]
1. Fresh install caprine and login.
2. Chat with someone, waiting for the message.
3. When new message received, it will look like this:
![60356997_2430430680617208_8001429673361801216_n](https://user-images.githubusercontent.com/17636996/57969024-6e155500-79a4-11e9-8617-f86fe43b1aa7.png)
It is cropped and need to manually scroll a bit to read the whole message. It's odd that sometimes this doesn't happen, still cant find out what's the precondition.  

**This happens on both windows and mac versions, the screenshot was shot on mac version**  

---

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17134
Locale: zh-TW

**Comment by ViliusVZ** [comment]
I also have this issue.

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by gklka** [comment]
It happens with group chats only for me.

Version 2.37.0 (2.37.0)
macOS 10.14.6

**Comment by dusansimic** [comment]
This is fixed in the latest build. Please update Caprine.
