### ISSUE TITLE
Not getting notified after latest update

### ISSUE THREAD

**Issue by LogX7** [sindresorhus/caprine#905]
Hello, i updated caprine to the latest version (2.31.0)

and now i don't get notified when i receive a new message, i'm on linux mint 19.1

**Comment by tamassengel** [comment]
Same on macOS 10.14.5. Also, the whole Messenger UI is changed and the layout is now somewhat broken.

**Comment by pkuczynski** [comment]
Duplicate of #893?

**Comment by sindresorhus** [comment]
Duplicate of #893
