### ISSUE TITLE
calls not working after latest update

### ISSUE THREAD

**Issue by fennecinspace** [sindresorhus/caprine#906]
Hello, i updated to (2.31.0)

now when i receive a call, i hear the sound, but nothing appears (to accept, decline ..etc)

i'm on mint 19.1

**Comment by Kallyopae** [comment]
Same issue on 2.31.1 + no badge notification or settings working + if i try to set a convo or group on mute, the options to do that don't appear either

**Comment by huylv** [comment]
Can't receive call on MacOS 10.13. Still hear the ringing sound but looks like the pop-up doesn't show up.
