### ISSUE TITLE
Forward and Remove messages are not working

### ISSUE THREAD

**Issue by DragosOnisei** [sindresorhus/caprine#912]
Hi!

Fist of all I wanna express my gratitude for the amazing job and brilliant app that you made.

But some small issues appeared in the latest update:

1 The Forward option is not working
2. Remove message option is not working.

Have a beautiful night!
---

Caprine 2.31.1
Electron 5.0.2
darwin 18.6.0
Locale: en-GB

**Comment by pkuczynski** [comment]
Both seem to be working for me with the latest version. Do you still encounter the issue?

**Comment by mihaimetal** [comment]
Forward broke about 2 weeks ago. Still not working.

**Comment by CvX** [comment]
This one will probably be fixed by #916.

**Comment by reganlawton** [comment]
I’m not sure if it will BUT I can update a new PR that has backwards support for new and old DOM selectors as I did in #916. 

Shouldn’t take long and can try have a look in the morning (AEST). Should be just cross referencing the selectors.

**Comment by CvX** [comment]
It does fix those for me. 🙂

**Comment by reganlawton** [comment]
Then we are laughing! Great! I’ll get updating from my dev build to the new version tomorrow 🙏

**Comment by DragosOnisei** [comment]
Amazing!

Thank you amazing people.

This issue is now resolved!
