### ISSUE TITLE
Messenger preferences and Notifactions option not pop up

### ISSUE THREAD

**Issue by ookangzheng** [sindresorhus/caprine#924]
https://want2.be/caprine-problem.mp4
Example ~~

**Comment by reganlawton** [comment]
This is a dupe of #911 which is because like myself your Facebook isn't updated to the new UI change yet.

**Comment by ookangzheng** [comment]
Hmm, since It works for couple days, but starting from yesterday, I cant use cmd+, again to open up "Preferences" dialog window

**Comment by CvX** [comment]
2.33.1?
