### ISSUE TITLE
Cant remove messages

### ISSUE THREAD

**Issue by batmonkey** [sindresorhus/caprine#925]
1. Click on message I just sent
2. Click "More"
3. Click "Remove"

Nothing happens

---

Caprine 2.31.2
Electron 5.0.2
win32 10.0.17134
Locale: en-GB

**Comment by batmonkey** [comment]
When installed from the Windows Store, (instead of the .exe),  it worked okay

**Comment by CvX** [comment]
Please note that the Windows Store version is outdated. And while the latest version does have a few broken things if you don't have a new Messenger UI enabled, it will be fixed by PR #916. 🙂
