### ISSUE TITLE
message read in Caprine but still marked as unread on Messenger.com & mobile app

### ISSUE THREAD

**Issue by vardecab** [sindresorhus/caprine#928]
Hey! 

When I read a new message on Caprine it's no longer unread - badge on app icon disappears so is blue dot next to the message in app - which is of course expected behavior. 

However, when I go to Messenger.com, Facebook.com or Messenger mobile app (Android) those messages I responded to via Caprine are still marked as unread. Why would that be a case? 🤔

_Caprine: 2.31.2 (2.31.2.1405)
macOS: 10.14.5_

Issue similar to this one, which is closed but I think, based on my case, not fixed:
[Tell FB to mark messages as read #852](https://github.com/sindresorhus/caprine/issues/852)

**Comment by reganlawton** [comment]
I noticed this bug too but it was on and off for me.

**Comment by charlesyz** [comment]
I was having this issue, as well as messages randomly popping back in caprine as "unread". realized it's because I have "privacy->block seen indicator" set on.

**Comment by reganlawton** [comment]
@charlesyz this isn’t the issue in my case. That said that makes for a valid reason for most people.
