### ISSUE TITLE
First run on Linux does not seem to do anything

### ISSUE THREAD

**Issue by winek** [sindresorhus/caprine#93]
Did a quick `strace` and `mkdir ~/.config/Caprine` fixes the issue.

**Comment by sindresorhus** [comment]
I think this was fixed in the latest Electron version.

@danhp Right?

**Comment by danhp** [comment]
Yup, I didnt know at the time but this is actually fixed with the lastest bump I did

**Comment by sindresorhus** [comment]
[1.3.1 is out](https://github.com/sindresorhus/caprine/releases/tag/v1.3.1)
