### ISSUE TITLE
Why does the application send request to icanhazip.com?

### ISSUE THREAD

**Issue by van-tienhoang** [sindresorhus/caprine#931]
Hello,

By monitoring the internet traffic, I see that app send request to ipv4.icanhazip.com. Could the author or someone tell me why? I do not see the website address on the source code.

I am using the mac version, installed by homebrew.

**Comment by CvX** [comment]
Caprine is using [is-online](https://github.com/sindresorhus/is-online#how-it-works), which in turn uses the icanhazip.com to check for the connection.
