### ISSUE TITLE
Setting option/icon Missing, Log-out and Messenger setting option is not working

### ISSUE THREAD

**Issue by MIKParadox** [sindresorhus/caprine#932]
### **Log out option isn't working**
Can't log out from Caprine
### **Messenger Setting** (Ctrl+,) option isn't working 
Can't access the setting of messenger such as **turning active status on/off.**
### **Setting option is missing**
Facebook Messenger Caprine: 
![image](https://user-images.githubusercontent.com/9998928/59293551-36e34c80-8ca1-11e9-9cf7-d0e26e9c0220.png)
Normal Facebook Messenger of PC having the gear icon is missing in the current version of Caprine.
Facebook Messenger in PC: 
![image](https://user-images.githubusercontent.com/9998928/59293382-e8ce4900-8ca0-11e9-8e04-cdb9d0f17a88.png)
---
Caprine 2.31.2
Electron 5.0.2
win32 10.0.18362
Locale: en-US
---

Caprine 2.31.2
Electron 5.0.2
win32 10.0.18362
Locale: en-US

**Comment by CvX** [comment]
This issue is tracked in #911 (and will be closed by #916). 🙂
