### ISSUE TITLE
Popup conversation settings don't show up on 2.31.1 and 2.31.2

### ISSUE THREAD

**Issue by AggelosM** [sindresorhus/caprine#934]
Since version 2.31.1 the popup windows when you press "Notifications" or "Edit Nicknames" etc don't show up.

Same on 2.31.2 so I had to downgrade to 2.31.0 which works fine.

---

Caprine 2.31.2
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by CvX** [comment]
Please follow the issue in #911 (which will be resolved by #916). 🙂

**Comment by AggelosM** [comment]
I'm still having this problem on the new version,

---

Caprine 2.33.0
Electron 5.0.5
win32 10.0.17763
Locale: en-US

**Comment by CvX** [comment]
#970 should fix this
