### ISSUE TITLE
Ability to hide notification content

### ISSUE THREAD

**Issue by marcinlesek** [sindresorhus/caprine#937]
Hello,

firstly, great app - thanks for developing and maintaining. 👏 

I'm writing to ask, if `Caprine` actually have feature to hide content of message in desktop notification? Something like Slack way of not showing what someone sent to us, but only notification that this person send something (without message text). 🤔 

Best regards,
Marcin

**Comment by sindresorhus** [comment]
Can you share screenshot of how the Slack notification looks like? Also the Slack setting to turn it on. For inspiration.

**Comment by marcinlesek** [comment]
Yea, for sure. Let's check this out, here below is normal message from slack with message content:

<img width="377" alt="Screenshot 2019-06-15 at 8 53 16 PM" src="https://user-images.githubusercontent.com/13199192/59555397-add65900-8fb1-11e9-838e-92f7c72639e5.png">

We see message content `Hello Marcin`. Now, we could change it in Slack settings to unchecked:

<img width="666" alt="Screenshot 2019-06-15 at 8 34 40 PM" src="https://user-images.githubusercontent.com/13199192/59555398-bfb7fc00-8fb1-11e9-9bd3-48920b48784d.png">

And now, notification looks like this:

<img width="371" alt="Screenshot 2019-06-15 at 8 54 03 PM" src="https://user-images.githubusercontent.com/13199192/59555410-f42bb800-8fb1-11e9-85b8-d6c1ef7e0b7e.png">

As we see above, we couldn't see content of message, only information that from who message arrived. 

Hope it helps @sindresorhus 😉
