### ISSUE TITLE
Colors look washed out

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#938]
The latest version (2.31.3.1433) seems to use the wrong color space. Previously colors were bright and vibrant on my P3 color space MacBook Pro display. Current colors look scaled down to sRGB color space.

**Comment by CvX** [comment]
The colorspace is correct, it was the previous look that was a bug. 🙂It was recently fixed (https://github.com/sindresorhus/caprine/commit/b9c461efdb01c6e341d69f839e33ee8e3b6f595d).

For a long time the color correction has been disabled, which resulted in colors on P3 screens to be stretched out (i.e. all colors looked like they had saturation cranked up to 150% 😅).

Please compare the current colors to Chrome and/or Safari to see if they match.

**Comment by gklka** [comment]
I see. Then consider this issue resolved. Sorry about reporting it.
