### ISSUE TITLE
Missing Icons on Linux. Release 1.3.0

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#94]
Hello,

When grabbing grabbing release 1.3.0, I notice that the icons are not present in the package, so to create my `.desktop` file, I was required to grab the icon from an earlier version.

Using Ubuntu 16.04 LTS

**Comment by danhp** [comment]
Now that we use asar to package the app we should add an icon outside of that package for convenience.

**Comment by sindresorhus** [comment]
@danhp Yup. I've realized this too. I'm considering using a better build system and adding support for `deb` and `rpm` packages. Maybe https://github.com/electron-userland/electron-builder

**Comment by forivall** [comment]
I just grab it from the repo in the Arch PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=caprine-bin

**Comment by sindresorhus** [comment]
I've disabled Asar for Linux for now, so [1.3.1](https://github.com/sindresorhus/caprine/releases/tag/v1.3.1) should work.

**Comment by sindresorhus** [comment]
Should be fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
