### ISSUE TITLE
Windows dark mode text box is white

### ISSUE THREAD

**Issue by Dalacu** [sindresorhus/caprine#948]
Seems like CSS is fucked up. Yesterday it was fine, now I just turned on my PC and that crap looking white background on every emoticon really pissed me off. 

Please find a fix for that, I am using your app for 6 months now and I was really thinking to donate.

![Annotation 2019-06-22 021317](https://user-images.githubusercontent.com/48447931/59955635-0a46e600-9494-11e9-851b-f89f7a1257f1.jpg)
![Annotation 2019-06-22 021712](https://user-images.githubusercontent.com/48447931/59955637-0c10a980-9494-11e9-9baa-7260093fe7a3.jpg)

Thanks.

**Comment by dscos** [comment]
Same on MacOS.
