### ISSUE TITLE
Show Message Buttons Not Working

### ISSUE THREAD

**Issue by janazleonhart** [sindresorhus/caprine#950]
When I click show message buttons, nothing changes.  Where as when my wife does it, removes the buttons.  Also for some reason the text bar is right in the middle of the buttons.

Caprine 2.32.1
Windows 7

**Comment by CvX** [comment]
Looks like the message button hiding code has to be updated to support the new Messenger UI. Thanks for the report!

And the centered message field seems like a new Message UI thing (as seen in e.g #948)
