### ISSUE TITLE
White message bar still appear in small size window

### ISSUE THREAD

**Issue by lnminh58** [sindresorhus/caprine#951]
![Screen Shot 2019-06-23 at 10 06 11 AM](https://user-images.githubusercontent.com/32949327/59971078-43b84800-959f-11e9-98a3-ce0a111f18f6.png)

Please! fix this bug. I only want to use small size window, but this bug make me cannot send message.

**Comment by dscos** [comment]
![Screen Shot 2019-06-24 at 12 39 02 PM](https://user-images.githubusercontent.com/14156552/60039889-628d0c00-967d-11e9-8911-1e119f6d72f2.jpg)

Issue happens even when the sidebar is not collapsed. Normal behavior when window is maximized/fullscreen though.

**Comment by CvX** [comment]
@dscos just to confirm, that’s Caprine 2.32.1?

**Comment by dscos** [comment]
@CvX correct. 2.32.1.1482 to be exact

**Comment by dscos** [comment]
I don't know if it's useful information or not, but the breakpoint for me between the expected behavior and the message bar going white appears to be about 2300 pixels wide.

**Comment by pkuczynski** [comment]
I tested this and can not reproduce this issue. Does anyone else can? @lnminh58 which version of Caprine do you have?

**Comment by dscos** [comment]
This issue is no longer happening for me under 2.33.1
