### ISSUE TITLE
When i toggle dark mode and the dark mode is enabled then the color changes to white where you type messages and it's unable to see what i'm typing. Any solution?

### ISSUE THREAD

**Issue by sakib-shahriyar** [sindresorhus/caprine#952]
---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.18362

**Comment by sakib-shahriyar** [comment]
[
![1](https://user-images.githubusercontent.com/25507188/59981267-9be45e00-9622-11e9-9b0c-f09b0cfa30a4.PNG)
](url)

**Comment by sakib-shahriyar** [comment]
![1](https://user-images.githubusercontent.com/25507188/59981277-cf26ed00-9622-11e9-85ec-50584bc5af9f.PNG)

**Comment by sakib-shahriyar** [comment]
![1](https://user-images.githubusercontent.com/25507188/59981299-0a292080-9623-11e9-80e0-2d2e2208f5a1.PNG)

**Comment by CvX** [comment]
Please try the latest version (2.32.1)

**Comment by sakib-shahriyar** [comment]
Thanks! Solved the issue
