### ISSUE TITLE
white on white

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#954]
macOS: dark. 
caprine: follow system appearance.
UI is dark except text field which is white, with white text  color.
haven't updated OS in a while, so this must have come with a caprine update, or something
macOS 10.14.4
---

Caprine 2.31.3
Electron 5.0.2
darwin 18.5.0
Locale: nb

**Comment by CvX** [comment]
Please update to the latest version (2.32.1). If the problem persists, please follow #951.

**Comment by 639me** [comment]
seems to be solved with that version. thanks
