### ISSUE TITLE
Unable to change chat emoji in version 1.3.0

### ISSUE THREAD

**Issue by jamesrobb** [sindresorhus/caprine#96]
Hello,

When trying to change he chat emjoi in release 1.3.0, the popup appears, but no icons appear within the pop up.

Using Ubuntu 16.04 LTS

**Comment by danhp** [comment]
Seems to be working fine on OS X and Windows even in Dark Mode.
![image](https://cloud.githubusercontent.com/assets/3745612/15179306/d59a6e5c-1748-11e6-8eb3-f5d77bdb0440.png)

**Comment by danhp** [comment]
hmmmm, this seems to be happening on master though

**Comment by jamesrobb** [comment]
I've tried again in Dark Mode, and still the same behavior, unfortunately.

//-- James Robb
//-- +354.666.0887 (Iceland/Ísland)

**Comment by sindresorhus** [comment]
Works fine for me with latest version.

@jamesrobb Can you try https://github.com/sindresorhus/caprine/releases/tag/1.4.0 ?

**Comment by danhp** [comment]
This was fixed on Facebook's end as it also works in Chrome again.

**Comment by jamesrobb** [comment]
works!
