### ISSUE TITLE
New Vs Old Layout

### ISSUE THREAD

**Issue by arromeo** [sindresorhus/caprine#960]
Some of the issues that have been closed in the last few days have had to do with the new layout on Messenger.com. When I navigate to the website I can see the new layout, but in Caprine it's still the old layout.

My local repo is up to date and I've tried clearing the settings and data but it's still the old layout. There are a few issues I wanted to work on, but I'm thinking that I should probably have the correct version of the app showing up first.

Feel free to close this issue. I was just wondering if anyone had some info on this. This is on Ubuntu if that is at all relevant.

**Comment by mikigal** [comment]
Simply wait for Facebook rollout. I have 2 another versions of layout on my 2 computers, it's normal

**Comment by CvX** [comment]
@arromeo That’s interesting! If clearing the app data on messenger.com won’t trigger a “downgrade”, that could mean it would be possible to force the new UI by, for example, manipulating the user-agent string (though I’m guessing they use a more complex browser fingerprinting strategy).

**Comment by ookangzheng** [comment]
Would be good somehow user can set custom User-agent

**Comment by reganlawton** [comment]
If we can manipulate the UI version @CvX then these backward patching issues will not be an issue anymore.

**Comment by CvX** [comment]
Yeah, I’d love to enable the new UI for all Caprine users, but we don’t know how to do it (or if it’s even possible).

We could start experimenting with user-agent (though I’m guessing that won’t be enough).
Can anyone share their browser’s (or Caprine’s) user-agent string with which they get the new UI?

**Comment by mikigal** [comment]
@CvX `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Caprine/2.32.1 Chrome/73.0.3683.121 Electron/5.0.4 Safari/537.36"`

On my PC I've got another UI (Newer?), I will update later this post with second User-Agent

**Comment by CvX** [comment]
Yeah, I’ve tried those user-agent strings, but unsurprisingly nothing changed. 😉

I wonder what other signals do they use…

**Comment by reganlawton** [comment]
Facebook needs an option feature to “bet” the new UI 🙄
