### ISSUE TITLE
Changing font in custom styles

### ISSUE THREAD

**Issue by hurani** [sindresorhus/caprine#961]
Can't seem to figure out how to change the font of the program. I tried editing font and font-family in custom.css but the font never changes, something seems to be overriding it since I can change the colours in custom.css just fine.

Any suggestions?

**Comment by whitecrownclown** [comment]
@hurani 	

`custom.css` is a css file included in `Caprine`. You can change the font family by writing css targeting your needs. <i>!important</i> might be needed for the changes to override `caprine`/`messenger` defaults. 

For example:

Adding this inside your `custom.css`

<img width="631" alt="Screenshot 2019-06-26 at 00 44 06" src="https://user-images.githubusercontent.com/8309417/60135923-8babba80-97ab-11e9-8934-1e5a1b22f4b2.png">

**In app:**

<img width="578" alt="Screenshot 2019-06-26 at 00 43 14" src="https://user-images.githubusercontent.com/8309417/60135919-89e1f700-97ab-11e9-8882-494b353f4170.png">

**In devtools you can see the default font-family overwritten:**

<img width="322" alt="Screenshot 2019-06-26 at 00 48 23" src="https://user-images.githubusercontent.com/8309417/60136181-2c9a7580-97ac-11e9-913a-937b28112130.png">

**Comment by Abdunnafi** [comment]
love
this is my edit (just below the custom.css)
html, body { font-family:Noto Sans Bengali !important;}
