### ISSUE TITLE
2.33.0 - Exit tray menu item is gone, only Caprine menu item available

### ISSUE THREAD

**Issue by dotpointer** [sindresorhus/caprine#965]
Debian 9.9 MATE.

Caprine current version 2.33.0, previous version 2.27.

There has been some regressions lately regarding the tray icon. First the possibility to double click on the icon to open the program from the tray was removed.

Now with the upgrade from 2.27 to 2.33.0 is **the Exit menu item on the tray gone**. I only have Caprine in the menu. To quit the program I now need to open it and go to File, Quit.

**Comment by sedmicha** [comment]
Same issue on Linux Mint 19.1 with Cinnamon with Caprine 2.33.0

**Comment by sindresorhus** [comment]
// @whitecrownclown

**Comment by dotpointer** [comment]
Sorry for being bitter, it is a good program. :hugs:

**Comment by whitecrownclown** [comment]
I could not reproduce this on Windows and i don't have access to a Linux machine right now. I'll have one this weekend.
