### ISSUE TITLE
dark mode - "do you want to accept messages" text

### ISSUE THREAD

**Issue by rtpHarry** [sindresorhus/caprine#967]
![image](https://user-images.githubusercontent.com/1038062/60289943-2e9a3b00-994a-11e9-92fb-06171d1f3ca4.png)

Sorry, I'm not running the latest version of Caprine. I'm on 2.31.3.

Maybe this is already fixed but thought I would submit it while I had it as these things aren't easily repeatable.

**Comment by mikigal** [comment]
Fixed, PR #971
