### ISSUE TITLE
Add KDE emoji support

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#969]
please consider adding kde emoji support. that would be fun!

![Screenshot_20190628_164552](https://user-images.githubusercontent.com/3148302/60350808-a73ddd80-99c4-11e9-91c3-48432a09ba96.png)

**Comment by sindresorhus** [comment]
The "System" on is what you want. It uses the system emojis, which should be KDE in your case.

**Comment by alekksander** [comment]
but it doesn't recognize any from other 5 visible variants.

**Comment by CvX** [comment]
I’ve looked at the [KDE documentation](https://docs.kde.org/stable5/en/kde-workspace/kcontrol/emoticons/index.html). Those aren’t emoji, but inline images that automatically replace matching text emoticons in supported KDE applications.

1. Messenger doesn’t support inline images
2. Electron/Chromium doesn’t support that KDE-specific text replacement feature

Not much we can do here!
