### ISSUE TITLE
Restore auto updates on Linux

### ISSUE THREAD

**Issue by CvX** [sindresorhus/caprine#972]
Linux auto updates were disabled in f0eba4a813f48f9486f676726a2de012156df55d because of the issues reported in #966.

Would be great to find solution to those issues! 🙂

**Comment by sindresorhus** [comment]
electron-builder is redoing their AppImage support: https://github.com/electron-userland/electron-builder/releases/tag/v21.0.1 So would be good to wait for that and also wait a little bit after that until all the initial issues are resolved.

Snap users gets updates through the Snapcraft store, so they're not affected.
