### ISSUE TITLE
Previews prior to sending, or lack there of.

### ISSUE THREAD

**Issue by KlausKT** [sindresorhus/caprine#977]
Description: 
No indication if a generated preview attached, prior to sending, and no way to clear it, as far as i know, apart from restarting the application. (note: i am referring to previews prior to sending, preview show up fine, once sent)

Applies to: 
Any link that generates a preview.

I know this may be an intentional (lack of) feature to keep system resources down. Or a constraint due to complications of accessing the messenger API or similar, But it is rather frustrating. ... Or i am just dumb, and somehow turned off something, blocking it.
---

Caprine 2.11.0
Electron 1.8.4
win32 x64 10.0.18362

**Comment by CvX** [comment]
Please update to the latest version (2.33.1) and report back! 🙂

**Comment by KlausKT** [comment]
So it was me being dumb, and didn't update.

Thanks, does work ;)
