### ISSUE TITLE
Error in textbox dark mode

### ISSUE THREAD

**Issue by BerkeinR** [sindresorhus/caprine#980]
![image](https://user-images.githubusercontent.com/35840496/60458107-078b8400-9c3e-11e9-9186-7e4a54e0a6f8.png)

The textbox for typing messages is still white so because of that you can't see what you're typing

---

Caprine 2.30.2
Electron 4.1.4
linux 4.19.49-1-MANJARO
Locale: en-US

**Comment by CvX** [comment]
Please try the latest version (2.33.1)
