### ISSUE TITLE
Set privacy options globally, overwrite manually for each converstion

### ISSUE THREAD

**Issue by benjaminforras** [sindresorhus/caprine#983]
We already have the Privacy settings that is used globally.

My feature request is that users can set these privacy settings per conversation.
(Maybe clicking on the gear in the conversation list and adding these options to the menu)

**Comment by sindresorhus** [comment]
Yes, would be nice, but I don't think we can easily do that technically, as the current implementation just blocks certain calls to Facebook, globally.

**Comment by TryHardDood** [comment]
When are those calls being sent to Facebook? Can't we just check it? 

For ex.: When I open a conversation it'll check for those url and then block it IF the current page url is containing the username or the id. 
Has to be a window navigate event or something to track it.

**Comment by dusansimic** [comment]
This feature is out of scope for now. Currently the privacy features are not working so once that feature is revisited we could consider it, especially of there are some contributions made.
