### ISSUE TITLE
Check for update or auto-update button

### ISSUE THREAD

**Issue by btdat2506** [sindresorhus/caprine#984]
As far as I can say, Caprine is the greatest app for FB Messenger for me despite I suffered with a lot of bugs (which is will be removed on update). However, I am not always free to go to github source or the website to download the dmg and the drag it into the application folder. I hope that this feature will be included soon on it. Thanks.

**Comment by CvX** [comment]
MacOS and Windows versions do auto-update (when you restart the app). On Linux that has been recently disabled (see: #972).

A visual indicator for updates being available is being considered in #936. 🙂
