### ISSUE TITLE
AppImage for 2.33.1 about modal says version 2.31.3

### ISSUE THREAD

**Issue by TomFaulkner** [sindresorhus/caprine#988]
I don't know if the file actually contains 2.33.1 or 2.31.3 but it seems to say it is 2.31.3. It seems 2.33.0 is the same way. Maybe I am doing something wrong?

**Comment by CvX** [comment]
I’ve just downloaded the 2.33.1, and it contains 2.33.1. The “About“ modal shows the same.

I don’t know how exactly AppImage works, maybe there’s a previous version (2.31.3) that’s cached and is being launched instead?

**Comment by TomFaulkner** [comment]
> maybe there’s a previous version (2.31.3) that’s cached and is being launched instead?

That's why I included maybe I'm doing something wrong. I guess I'll start trying to figure out what that is. I deleted the original AppImage first and Gnome no longer shows it in the search. Time to research I suppose.

**Comment by TomFaulkner** [comment]
I tried another time and searched for AppImage caching, I can't find anywhere that says there is a cache, nor can I find cache files. Anyway, I installed the snap version instead, so I'm closing the issue.
