### ISSUE TITLE
"Delete conversation" doesn't work on linux mint 19.1

### ISSUE THREAD

**Issue by stoza** [sindresorhus/caprine#992]
When the "delete conversation" button is pressed, there is a little freeze of the application an then the conversation isn't deleted

**Comment by CvX** [comment]
What’s your Caprine version? 2.33.1? (that’s the latest one)

**Comment by stoza** [comment]
yes it's the 2.33.1 version

**Comment by mquevill** [comment]
I am able to delete conversations without any trouble on Linux Mint 19.1 with Caprine 2.34.0.

**Comment by dusansimic** [comment]
Solved
