### ISSUE TITLE
Linux - segfault when cancelling file adding

### ISSUE THREAD

**Issue by sewera** [sindresorhus/caprine#993]
## Quick explanation
When in conversation I clicked `Add files` and then in popup file manager clicked `Cancel`,
a segfault occured: `[1]    9448 segmentation fault (core dumped)  caprine`.

### System specs
- Caprine version: 2.33.1
- Node version: 11.15.0
- Electron version: 5.0.6
- OS: Arch Linux x86_64
- WM: i3wm
- File manager: Thunar

**Comment by klaasg** [comment]
Same happens when I actually select a file and try to send it. Program terminates immediatly and same error.
Same system specs, I just don't have a file manager. It's using the default gtk/electron file chooser? Don't know alot about this really.

Further info:
It happens both in group and non-group chats.

**Comment by Samgarr** [comment]
Segfault occured when i'm trying upload a file. This issue come with latest version, i think.

* Caprine version: 2.34.0
* Node version: 11.15.0
* Electron version: 5.0.7
* OS: Arch Linux x86_64, 5.2.1-arch1-1-ARCH
* WM: i3wm
* File manager: Dolphin

```
[ 2977.856827] caprine[4621]: segfault at 100000007 ip 00007fd9082edded sp 00007ffd6171a970 error 4 in libgobject-2.0.so.0.6000.5[7fd9082d5000+32000]
```

**Comment by jazzsewera** [comment]
@Samgarr Not happening in my setup, segfault occurs only when I cancel file adding.
- Caprine version: 2.34.0
- Node version: 11.15.0
- Electron version: 5.0.8
- OS: Arch Linux x86_64, 5.1.15-arch1-1-ARCH (I had many screen freezing issues with newer kernels)
- WM: i3wm
- File manager: Thunar

Maybe try updating electron or using a different FM?

**Comment by Samgarr** [comment]
I'm getting segfault in both situations - when i'm uploading file or canceling file dialog, even with updated Electron. Btw, does file manager matters? My Caprine opens files through GtkFileChooserDialog, not by Dolphin.
